/*****************************************************************************

 @(#) $Id: ds1.h,v 0.9.2.8 2009-01-03 10:51:10 brian Exp $

 -----------------------------------------------------------------------------

 Copyright (c) 2008-2009  Monavacom Limited <http://www.monavacom.com/>
 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; version 3 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 -----------------------------------------------------------------------------

 Last Modified $Date: 2009-01-03 10:51:10 $ by $Author: brian $

 -----------------------------------------------------------------------------

 $Log: ds1.h,v $
 Revision 0.9.2.8  2009-01-03 10:51:10  brian
 - updated agent

 Revision 0.9.2.7  2009-01-02 15:04:18  brian
 - updated agents

 Revision 0.9.2.6  2008-12-31 16:04:50  brian
 - updated mibs

 Revision 0.9.2.5  2008-12-24 13:40:56  brian
 - updated mibs

 *****************************************************************************/

#ifndef __LOCAL_DS1_H__
#define __LOCAL_DS1_H__

#ident "@(#) $RCSfile: ds1.h,v $ $Name:  $($Revision: 0.9.2.8 $) Copyright (c) 2008-2009 Monavacom Limited."

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */
/* our storage structure(s) */
struct ds1_data {
	uint ds1_request;
};
struct dsx1ConfigTable_data {
	uint dsx1ConfigTable_request;
	uint dsx1ConfigTable_refs;
	long dsx1LineIndex;
	long dsx1IfIndex;
	long dsx1TimeElapsed;
	long dsx1ValidIntervals;
	long dsx1LineType;
	long dsx1LineCoding;
	long dsx1SendCode;
	uint8_t *dsx1CircuitIdentifier;
	size_t dsx1CircuitIdentifierLen;
	long dsx1LoopbackConfig;
	long dsx1LineStatus;
	long dsx1SignalMode;
	long dsx1TransmitClockSource;
	long dsx1Fdl;
	long dsx1InvalidIntervals;
	long dsx1LineLength;
	long dsx1LineStatusLastChange;
	long dsx1LineStatusChangeTrapEnable;
	long dsx1LoopbackStatus;
	long dsx1Ds1ChannelNumber;
	long dsx1Channelization;
	long dsx1LineMode;
	long dsx1LineBuildOut;
	long dsx1LineImpedance;
};
struct dsx1CurrentTable_data {
	uint dsx1CurrentTable_request;
	uint dsx1CurrentTable_refs;
	long dsx1CurrentIndex;
	long dsx1CurrentESs;
	long dsx1CurrentSESs;
	long dsx1CurrentSEFSs;
	long dsx1CurrentUASs;
	long dsx1CurrentCSSs;
	long dsx1CurrentPCVs;
	long dsx1CurrentLESs;
	long dsx1CurrentBESs;
	long dsx1CurrentDMs;
	long dsx1CurrentLCVs;
};
struct dsx1IntervalTable_data {
	uint dsx1IntervalTable_request;
	uint dsx1IntervalTable_refs;
	long dsx1IntervalIndex;
	long dsx1IntervalNumber;
	long dsx1IntervalESs;
	long dsx1IntervalSESs;
	long dsx1IntervalSEFSs;
	long dsx1IntervalUASs;
	long dsx1IntervalCSSs;
	long dsx1IntervalPCVs;
	long dsx1IntervalLESs;
	long dsx1IntervalBESs;
	long dsx1IntervalDMs;
	long dsx1IntervalLCVs;
	long dsx1IntervalValidData;
};
struct dsx1TotalTable_data {
	uint dsx1TotalTable_request;
	uint dsx1TotalTable_refs;
	long dsx1TotalIndex;
	long dsx1TotalESs;
	long dsx1TotalSESs;
	long dsx1TotalSEFSs;
	long dsx1TotalUASs;
	long dsx1TotalCSSs;
	long dsx1TotalPCVs;
	long dsx1TotalLESs;
	long dsx1TotalBESs;
	long dsx1TotalDMs;
	long dsx1TotalLCVs;
};
struct dsx1FarEndCurrentTable_data {
	uint dsx1FarEndCurrentTable_request;
	uint dsx1FarEndCurrentTable_refs;
	long dsx1FarEndCurrentIndex;
	long dsx1FarEndTimeElapsed;
	long dsx1FarEndValidIntervals;
	long dsx1FarEndCurrentESs;
	long dsx1FarEndCurrentSESs;
	long dsx1FarEndCurrentSEFSs;
	long dsx1FarEndCurrentUASs;
	long dsx1FarEndCurrentCSSs;
	long dsx1FarEndCurrentLESs;
	long dsx1FarEndCurrentPCVs;
	long dsx1FarEndCurrentBESs;
	long dsx1FarEndCurrentDMs;
	long dsx1FarEndInvalidIntervals;
};
struct dsx1FarEndIntervalTable_data {
	uint dsx1FarEndIntervalTable_request;
	uint dsx1FarEndIntervalTable_refs;
	long dsx1FarEndIntervalIndex;
	long dsx1FarEndIntervalNumber;
	long dsx1FarEndIntervalESs;
	long dsx1FarEndIntervalSESs;
	long dsx1FarEndIntervalSEFSs;
	long dsx1FarEndIntervalUASs;
	long dsx1FarEndIntervalCSSs;
	long dsx1FarEndIntervalLESs;
	long dsx1FarEndIntervalPCVs;
	long dsx1FarEndIntervalBESs;
	long dsx1FarEndIntervalDMs;
	long dsx1FarEndIntervalValidData;
};
struct dsx1FarEndTotalTable_data {
	uint dsx1FarEndTotalTable_request;
	uint dsx1FarEndTotalTable_refs;
	long dsx1FarEndTotalIndex;
	long dsx1FarEndTotalESs;
	long dsx1FarEndTotalSESs;
	long dsx1FarEndTotalSEFSs;
	long dsx1FarEndTotalUASs;
	long dsx1FarEndTotalCSSs;
	long dsx1FarEndTotalLESs;
	long dsx1FarEndTotalPCVs;
	long dsx1FarEndTotalBESs;
	long dsx1FarEndTotalDMs;
};
struct dsx1FracTable_data {
	uint dsx1FracTable_request;
	uint dsx1FracTable_refs;
	long dsx1FracIndex;
	long dsx1FracNumber;
	long dsx1FracIfIndex;
};
struct dsx1ChanMappingTable_data {
	uint dsx1ChanMappingTable_request;
	uint dsx1ChanMappingTable_refs;
	long ifIndex;
	long dsx1Ds1ChannelNumber;
	long dsx1ChanMappedIfIndex;
};

/* storage declarations */
extern struct ds1_data *ds1Storage;
extern struct header_complex_index *dsx1ConfigTableStorage;
extern struct header_complex_index *dsx1CurrentTableStorage;
extern struct header_complex_index *dsx1IntervalTableStorage;
extern struct header_complex_index *dsx1TotalTableStorage;
extern struct header_complex_index *dsx1FarEndCurrentTableStorage;
extern struct header_complex_index *dsx1FarEndIntervalTableStorage;
extern struct header_complex_index *dsx1FarEndTotalTableStorage;
extern struct header_complex_index *dsx1FracTableStorage;
extern struct header_complex_index *dsx1ChanMappingTableStorage;

/* enum definitions from the covered mib sections */

#define DSX1LINETYPE_OTHER                       1
#define DSX1LINETYPE_DSX1ESF                     2
#define DSX1LINETYPE_DSX1D4                      3
#define DSX1LINETYPE_DSX1E1                      4
#define DSX1LINETYPE_DSX1E1CRC                   5
#define DSX1LINETYPE_DSX1E1MF                    6
#define DSX1LINETYPE_DSX1E1CRCMF                 7
#define DSX1LINETYPE_DSX1UNFRAMED                8
#define DSX1LINETYPE_DSX1E1UNFRAMED              9
#define DSX1LINETYPE_DSX1DS2M12                  10
#define DSX1LINETYPE_DSX1E2                      11
#define DSX1LINETYPE_DSX1E1Q50                   12
#define DSX1LINETYPE_DSX1E1Q50CRC                13
#define DSX1LINETYPE_DSX1J1ESF                   14
#define DSX1LINETYPE_DSX1J1UNFRAMED              16

#define DSX1LINECODING_DSX1JBZS                  1
#define DSX1LINECODING_DSX1B8ZS                  2
#define DSX1LINECODING_DSX1HDB3                  3
#define DSX1LINECODING_DSX1ZBTSI                 4
#define DSX1LINECODING_DSX1AMI                   5
#define DSX1LINECODING_OTHER                     6
#define DSX1LINECODING_DSX1B6ZS                  7

#define DSX1SENDCODE_DSX1SENDNOCODE              1
#define DSX1SENDCODE_DSX1SENDLINECODE            2
#define DSX1SENDCODE_DSX1SENDPAYLOADCODE         3
#define DSX1SENDCODE_DSX1SENDRESETCODE           4
#define DSX1SENDCODE_DSX1SENDQRS                 5
#define DSX1SENDCODE_DSX1SEND511PATTERN          6
#define DSX1SENDCODE_DSX1SEND3IN24PATTERN        7
#define DSX1SENDCODE_DSX1SENDOTHERTESTPATTERN    8

#define DSX1LOOPBACKCONFIG_DSX1NOLOOP            1
#define DSX1LOOPBACKCONFIG_DSX1PAYLOADLOOP       2
#define DSX1LOOPBACKCONFIG_DSX1LINELOOP          3
#define DSX1LOOPBACKCONFIG_DSX1OTHERLOOP         4
#define DSX1LOOPBACKCONFIG_DSX1INWARDLOOP        5
#define DSX1LOOPBACKCONFIG_DSX1DUALLOOP          6

#define DSX1SIGNALMODE_NONE                      1
#define DSX1SIGNALMODE_ROBBEDBIT                 2
#define DSX1SIGNALMODE_BITORIENTED               3
#define DSX1SIGNALMODE_MESSAGEORIENTED           4
#define DSX1SIGNALMODE_OTHER                     5

#define DSX1TRANSMITCLOCKSOURCE_LOOPTIMING       1
#define DSX1TRANSMITCLOCKSOURCE_LOCALTIMING      2
#define DSX1TRANSMITCLOCKSOURCE_THROUGHTIMING    3
#define DSX1TRANSMITCLOCKSOURCE_ADAPTIVE         4

#define DSX1LINESTATUSCHANGETRAPENABLE_ENABLED   1
#define DSX1LINESTATUSCHANGETRAPENABLE_DISABLED  2

#define DSX1CHANNELIZATION_DISABLED              1
#define DSX1CHANNELIZATION_ENABLEDDS0            2
#define DSX1CHANNELIZATION_ENABLEDDS1            3

#define DSX1LINEMODE_CSU                         1
#define DSX1LINEMODE_DSU                         2

#define DSX1LINEBUILDOUT_NOTAPPLICABLE           1
#define DSX1LINEBUILDOUT_NEG75DB                 2
#define DSX1LINEBUILDOUT_NEG15DB                 3
#define DSX1LINEBUILDOUT_NEG225DB                4
#define DSX1LINEBUILDOUT_ZERODB                  5

#define DSX1LINEIMPEDANCE_NOTAPPLICABLE          1
#define DSX1LINEIMPEDANCE_UNBALANCED75OHMS       2
#define DSX1LINEIMPEDANCE_BALANCED100OHMS        3
#define DSX1LINEIMPEDANCE_BALANCED120OHMS        4

#define DSX1INTERVALVALIDDATA_TRUE               1
#define DSX1INTERVALVALIDDATA_FALSE              2

#define DSX1FARENDINTERVALVALIDDATA_TRUE         1
#define DSX1FARENDINTERVALVALIDDATA_FALSE        2

/* notifications */
extern oid dsx1LineStatusChange_oid[10];

/* scalars accessible only for notify */

/* object id definitions */
/* function prototypes */
void init_ds1(void);
void deinit_ds1(void);
int term_ds1(int majorID, int minorID, void *serverarg, void *clientarg);
FindVarMethod var_ds1;
void parse_ds1(const char *, char *);
SNMPCallback store_ds1;
void refresh_ds1(void);
FindVarMethod var_dsx1ConfigTable;
struct dsx1ConfigTable_data *dsx1ConfigTable_create(void);
struct dsx1ConfigTable_data *dsx1ConfigTable_duplicate(struct dsx1ConfigTable_data *);
int dsx1ConfigTable_destroy(struct dsx1ConfigTable_data **);
int dsx1ConfigTable_add(struct dsx1ConfigTable_data *);
int dsx1ConfigTable_del(struct dsx1ConfigTable_data *);
void parse_dsx1ConfigTable(const char *, char *);
SNMPCallback store_dsx1ConfigTable;
void refresh_dsx1ConfigTable(void);
FindVarMethod var_dsx1CurrentTable;
struct dsx1CurrentTable_data *dsx1CurrentTable_create(void);
struct dsx1CurrentTable_data *dsx1CurrentTable_duplicate(struct dsx1CurrentTable_data *);
int dsx1CurrentTable_destroy(struct dsx1CurrentTable_data **);
int dsx1CurrentTable_add(struct dsx1CurrentTable_data *);
int dsx1CurrentTable_del(struct dsx1CurrentTable_data *);
void parse_dsx1CurrentTable(const char *, char *);
SNMPCallback store_dsx1CurrentTable;
void refresh_dsx1CurrentTable(void);
FindVarMethod var_dsx1IntervalTable;
struct dsx1IntervalTable_data *dsx1IntervalTable_create(void);
struct dsx1IntervalTable_data *dsx1IntervalTable_duplicate(struct dsx1IntervalTable_data *);
int dsx1IntervalTable_destroy(struct dsx1IntervalTable_data **);
int dsx1IntervalTable_add(struct dsx1IntervalTable_data *);
int dsx1IntervalTable_del(struct dsx1IntervalTable_data *);
void parse_dsx1IntervalTable(const char *, char *);
SNMPCallback store_dsx1IntervalTable;
void refresh_dsx1IntervalTable(void);
FindVarMethod var_dsx1TotalTable;
struct dsx1TotalTable_data *dsx1TotalTable_create(void);
struct dsx1TotalTable_data *dsx1TotalTable_duplicate(struct dsx1TotalTable_data *);
int dsx1TotalTable_destroy(struct dsx1TotalTable_data **);
int dsx1TotalTable_add(struct dsx1TotalTable_data *);
int dsx1TotalTable_del(struct dsx1TotalTable_data *);
void parse_dsx1TotalTable(const char *, char *);
SNMPCallback store_dsx1TotalTable;
void refresh_dsx1TotalTable(void);
FindVarMethod var_dsx1FarEndCurrentTable;
struct dsx1FarEndCurrentTable_data *dsx1FarEndCurrentTable_create(void);
struct dsx1FarEndCurrentTable_data *dsx1FarEndCurrentTable_duplicate(struct dsx1FarEndCurrentTable_data *);
int dsx1FarEndCurrentTable_destroy(struct dsx1FarEndCurrentTable_data **);
int dsx1FarEndCurrentTable_add(struct dsx1FarEndCurrentTable_data *);
int dsx1FarEndCurrentTable_del(struct dsx1FarEndCurrentTable_data *);
void parse_dsx1FarEndCurrentTable(const char *, char *);
SNMPCallback store_dsx1FarEndCurrentTable;
void refresh_dsx1FarEndCurrentTable(void);
FindVarMethod var_dsx1FarEndIntervalTable;
struct dsx1FarEndIntervalTable_data *dsx1FarEndIntervalTable_create(void);
struct dsx1FarEndIntervalTable_data *dsx1FarEndIntervalTable_duplicate(struct dsx1FarEndIntervalTable_data *);
int dsx1FarEndIntervalTable_destroy(struct dsx1FarEndIntervalTable_data **);
int dsx1FarEndIntervalTable_add(struct dsx1FarEndIntervalTable_data *);
int dsx1FarEndIntervalTable_del(struct dsx1FarEndIntervalTable_data *);
void parse_dsx1FarEndIntervalTable(const char *, char *);
SNMPCallback store_dsx1FarEndIntervalTable;
void refresh_dsx1FarEndIntervalTable(void);
FindVarMethod var_dsx1FarEndTotalTable;
struct dsx1FarEndTotalTable_data *dsx1FarEndTotalTable_create(void);
struct dsx1FarEndTotalTable_data *dsx1FarEndTotalTable_duplicate(struct dsx1FarEndTotalTable_data *);
int dsx1FarEndTotalTable_destroy(struct dsx1FarEndTotalTable_data **);
int dsx1FarEndTotalTable_add(struct dsx1FarEndTotalTable_data *);
int dsx1FarEndTotalTable_del(struct dsx1FarEndTotalTable_data *);
void parse_dsx1FarEndTotalTable(const char *, char *);
SNMPCallback store_dsx1FarEndTotalTable;
void refresh_dsx1FarEndTotalTable(void);
FindVarMethod var_dsx1FracTable;
struct dsx1FracTable_data *dsx1FracTable_create(void);
struct dsx1FracTable_data *dsx1FracTable_duplicate(struct dsx1FracTable_data *);
int dsx1FracTable_destroy(struct dsx1FracTable_data **);
int dsx1FracTable_add(struct dsx1FracTable_data *);
int dsx1FracTable_del(struct dsx1FracTable_data *);
void parse_dsx1FracTable(const char *, char *);
SNMPCallback store_dsx1FracTable;
void refresh_dsx1FracTable(void);
FindVarMethod var_dsx1ChanMappingTable;
struct dsx1ChanMappingTable_data *dsx1ChanMappingTable_create(void);
struct dsx1ChanMappingTable_data *dsx1ChanMappingTable_duplicate(struct dsx1ChanMappingTable_data *);
int dsx1ChanMappingTable_destroy(struct dsx1ChanMappingTable_data **);
int dsx1ChanMappingTable_add(struct dsx1ChanMappingTable_data *);
int dsx1ChanMappingTable_del(struct dsx1ChanMappingTable_data *);
void parse_dsx1ChanMappingTable(const char *, char *);
SNMPCallback store_dsx1ChanMappingTable;
void refresh_dsx1ChanMappingTable(void);

WriteMethod write_dsx1LineType;
WriteMethod write_dsx1LineCoding;
WriteMethod write_dsx1SendCode;
WriteMethod write_dsx1CircuitIdentifier;
WriteMethod write_dsx1LoopbackConfig;
WriteMethod write_dsx1SignalMode;
WriteMethod write_dsx1TransmitClockSource;
WriteMethod write_dsx1Fdl;
WriteMethod write_dsx1LineLength;
WriteMethod write_dsx1LineStatusChangeTrapEnable;
WriteMethod write_dsx1Channelization;
WriteMethod write_dsx1LineMode;
WriteMethod write_dsx1LineBuildOut;
WriteMethod write_dsx1LineImpedance;
WriteMethod write_dsx1FracIfIndex;
#endif				/* __LOCAL_DS1_H__ */
