'\" rtp
.\" -*- nroff -*- vim: ft=nroff nocin nosi
.\"
.\" @(#) $Id: CH_ERROR_ACK.7.man,v 0.9.2.1 2006/10/14 06:37:23 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (c) 2001-2006  OpenSS7 Corporation <http://www.openss7.com/>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.  The author(s) will take no responsibility in it.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" -------------------------------------------------------------------------
.\"
.\" U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
.\" on behalf of the U.S. Government ("Government"), the following
.\" provisions apply to you.  If the Software is supplied by the Department
.\" of Defense ("DoD"), it is classified as "Commercial Computer Software"
.\" under paragraph 252.227-7014 of the DoD Supplement to the Federal
.\" Acquisition Regulations ("DFARS") (or any successor regulations) and the
.\" Government is acquiring only the license rights granted herein (the
.\" license rights customarily provided to non-Government users).  If the
.\" Software is supplied to any unit or agency of the Government other than
.\" DoD, it is classified as "Restricted Computer Software" and the
.\" Government's rights in the Software are defined in paragraph 52.227-19
.\" of the Federal Acquisition Regulations ("FAR") (or any successor
.\" regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
.\" NASA Supplement to the FAR (or any successor regulations).
.\"
.\" =========================================================================
.\" 
.\" Commercial licensing and support of this software is available from
.\" OpenSS7 Corporation at a fee.  See http://www.openss7.com/
.\" 
.\" =========================================================================
.\"
.\" Last Modified $Date: 2006/10/14 06:37:23 $ by $Author: brian $
.\"
.\" -------------------------------------------------------------------------
.\"
.\" $Log: CH_ERROR_ACK.7.man,v $
.\" Revision 0.9.2.1  2006/10/14 06:37:23  brian
.\" - added manpages, module, drivers, headers from strss7 package
.\"
.\" Revision 0.9.2.5  2006/04/05 09:43:13  brian
.\" - moved .so line and updated headers
.\"
.\" =========================================================================
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database strchan.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.so strchan.macros
.\"
.\"
.TH CH_ERROR_ACK 7 "@PACKAGE_DATE@" "@PACKAGE@-@VERSION@" "Channel Interface (CHI)"
.SH NAME
.B CH_ERROR_ACK, CH_error_ack, CH_error_ack_t
\- error acknowledgment
.SH SYNOPSIS
This primitive consists of one
.B M_PCPROTO
message block, structured as follows:
.sp
.nf
\fC\s-1\
typedef struct CH_error_ack {
    ch_ulong ch_primitive;      /* always CH_ERROR_ACK */
    ch_ulong ch_error_primitive;/* primitive in error */
    ch_ulong ch_error_type;     /* CHI error */
    ch_ulong ch_unix_error;     /* UNIX error */
    ch_ulong ch_state;          /* resulting state */
} CH_error_ack_t;
\s+1\fR
.fi
.SH DESCRIPTION
For primitives that required local acknowledgment, this primitive provides
negative acknowlegment on the receipt of the primitive.
.SH PARAMETERS
This primitive contains the following parameters:
.TP
.I ch_primitive
indicates the primitive type.  Always
.BR CH_ERROR_ACK .
.TP
.I ch_error_primitive
indicates the primitive that was received in error.  This field can be one of
the following values:
.sp
.TS
tab(:);
ll.
\fBCH_INFO_REQ\fR(7):information request
\fBCH_OPTMGMT_REQ\fR(7):options management request
\fBCH_ATTACH_REQ\fR(7):attach channel request
\fBCH_DETACH_REQ\fR(7):detach channel request
\fBCH_ENABLE_REQ\fR(7):enable channel request
\fBCH_DISABLE_REQ\fR(7):disable channel request
\fBCH_CONNECT_REQ\fR(7):channel connection request
\fBCH_DISCONNECT_REQ\fR(7):channel disconnection request
.TE
.TP
.I ch_error_type
indicates the error type.  See
.IR \*(lqERRROS\*(rq ,
below.
.TP
.I ch_unix_error
indicates the
.BR UNIX \(rg
error number,
.IR errno (3).
When
.I ch_error_type is
.BR CHSYSERR ,
this field contains the
.BR Linux \(rq
.IR errno (3).
Otherwise, this field is ignored by the channel service user and coded zero
(0) by the channel service provider.
.TP
.I ch_state
indicates the resulting state of the channel service provider.  This is the
state from which the errored primitive was issued.
.SH ORIGINATOR
Channel Service Provider.
.SH STATE
This primitive is issued in any state when a local acknowlegment is
outstanding.  The resulting state is the state in which the errored primitive
was issued.
.SH ERRORS
The error type,
.IR ch_error_type ,
can be one of the following values:
.TP 16
.RB [ CHSYSERR ]
.I UNIX system error.
A UNIX system error occured during the execution of the primitive, and the
UNIX error number,
.IR errno (3),
is indicated in the
.I ch_unix_error
field of the
.B CH_ERROR_ACK
primitive.
.TP
.RB [ CHBADADDR ]
.I Bad address format or content.
A specified address was poorly formatted or contained invalid information.
.TP
.RB [ CHOUTSTATE ]
.I Interface out of state.
The primitive would place the interface out of state.  The errored primitive
must be issued from a specific set of valid states, yet the errored primitive
was not issued in one of the states for which it is valid.
.TP
.RB [ CHBADOPT ]
.I Bad options format or content.
Specified options were poorly formatted or contained invalid information.
.TP
.RB [ CHBADPARM ]
.I Bad parameter format or content.
Specified options contained a parameter that was poorly formatted or contained
invalid information.
.TP
.RB [ CHBADPARMTYPE ]
.I Bad paramater structure type.
Specified parameter type was not recognized or was poorly formatted for the
specified type.
.TP
.RB [ CHBADFLAG ]
.I Bad flag.
Specified flags were invalid.
.TP
.RB [ CHBADPRIM ]
.I Bad primitive.
The primitive type was unrecongnized or the primitive message block was poorly
formatted for the message type.
.TP
.RB [ CHNOTSUPP ]
.I Primitive not supported.
The primitive type was recognized, but is not supported for the stream or
channel service provider to which the errored primitive was issued.
.TP
.RB [ CHNOADDR ]
.I Address could not be assigned.
No address was specified in the errored primitive, and the channel service
provider could not assign one.
.TP
.RB [ CHADDRBUSY ]
.I Address is busy.
The address specified in the errored primitive is already in use by another
stream.
.SH "SEE ALSO"
.BR CH_INFO_REQ (7),
.BR CH_OPTMGMT_REQ (7),
.BR CH_ATTACH_REQ (7),
.BR CH_DETACH_REQ (7),
.BR CH_ENABLE_REQ (7),
.BR CH_DISABLE_REQ (7),
.BR CH_CONNECT_REQ (7),
.BR CH_DISCONNECT_REQ (7).
.SH VERSIONS
This manpage was written for CHI Version 1.
.XX
.[
chi
.]
.[
$LIST$
.]
.TI
