/* demsb.h - DEC DEMSA router interface (part b!) */

/* 
 * $Header: /xtel/isode/isode/h/RCS/demsb.h,v 9.0 1992/06/16 12:17:57 isode Rel $
 *
 *
 * $Log: demsb.h,v $
 * Revision 9.0  1992/06/16  12:17:57  isode
 * Release 8.0
 *
 */

/*
 *				  NOTICE
 *
 *    Acquisition, use, and distribution of this module and related
 *    materials are subject to the restrictions of a license agreement.
 *    Consult the Preface in the User's Manual for the full terms of
 *    this agreement.
 *
 */


/* definitions for DEMSA-BOX  */
t_list_of_conn_desc list_of_conn_desc[our_TABLE_SIZE] = {
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
NOTOK, NOTOK,
};
