#!/bin/bash
# =============================================================================
# 
# @(#) $RCSfile: check_libs,v $ $Name:  $($Revision: 0.9.2.1 $) $Date: 2005/01/17 14:20:16 $
#
# -----------------------------------------------------------------------------
#
# Copyright (c) 2001-2005  OpenSS7 Corporation <http://www.openss7.com>
# Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
#
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 675 Mass
# Ave, Cambridge, MA 02139, USA.
#
# -----------------------------------------------------------------------------
#
# U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
# behalf of the U.S. Government ("Government"), the following provisions apply
# to you.  If the Software is supplied by the Department of Defense ("DoD"), it
# is classified as "Commercial Computer Software" under paragraph 252.227-7014
# of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
# successor regulations) and the Government is acquiring only the license rights
# granted herein (the license rights customarily provided to non-Government
# users).  If the Software is supplied to any unit or agency of the Government
# other than DoD, it is classified as "Restricted Computer Software" and the
# Government's rights in the Software are defined in paragraph 52.227-19 of the
# Federal Acquisition Regulations ("FAR") (or any success regulations) or, in
# the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
# (or any successor regulations).
#
# -----------------------------------------------------------------------------
#
# Commercial licensing and support of this software is available from OpenSS7
# Corporation at a fee.  See http://www.openss7.com/
#
# -----------------------------------------------------------------------------
#
# Last Modified $Date: 2005/01/17 14:20:16 $ by $Author: brian $
#
# =============================================================================

me=`basename $0`
retval=0

exec 5>$me.log

export -p >&5

echo_v()
{
	if test -n "$MAINTAINER_MODE" ; then
		echo "$me: I: $1"
	fi
}

echo_d()
{
	if test -n "$MAINTAINER_MODE" ; then
		echo "$me: D: $1"
	fi
	echo "$me: D: $1" >&5
}

echo_e()
{
	echo "$me: E: $1" >&2
	echo "$me: E: $1" >&5
}

echo_w()
{
	if test -n "$MAINTAINER_MODE" ; then
		echo "$me: W: $1" >&2
	fi
	echo "$me: W: $1" >&5
}

rm -f Libraries.map
libs=
for lib in $lib_LTLIBRARIES
do
	l=`basename $lib`
	l=.libs/`echo $l | sed -e 's|\.la$|.a|'`
	if test -e $l
	then :
	else
		echo_e "Cannot find library $l."
		retval=1
		continue
	fi
	nm -s $l | grep '\<B\>\|\<D\>\|\<T\>' | sed -e 's|^.* ||' >> Libraries.map
done

#
# Check for manual pages for exported symbols.
#
while read symbol
do
	found=
	for dir in ./doc $srcdir/doc . $srcdir
	do
		for section in 2 3
		do
			f="$dir/man/man$section/$symbol.$section"
			if test -e $f
			then
				echo_v "Found manual page for $symbol, $f."
				found="${found}${found:+ }$f"
			fi
			if test -e ${f}s
			then
				echo_v "Found manual page for $symbol, ${f}s."
				found="${found}${found:+ }${f}s"
			fi
		done
	done
	if test -z "$found"
	then
		echo_e "Cannot find manpage for symbol $symbol"
		echo_v "---------------------------------------------------------------"
		retval=1
		continue;
	fi
	for page in $found
	do
		echo_d "man $page"
		# this only works for ascii
		if man $page | sed -e 's/.[[:cntrl:]]//g' > ${me}_$$.out 2> ${me}_$$.err \
			&& test -n "`cat ${me}_$$.out`" \
			&& test -z "`cat ${me}_$$.err`"
		then
			echo_v "Manual page $page formats correctly."
		else
			echo_e "Error formatting manual page $page"
			echo_d "stderr was:"
			while read line ; do echo_d "$line" ; done < ${me}_$$.err
			echo_d "stdout was:"
			while read line ; do echo_d "$line" ; done < ${me}_$$.out
			retval=1
			continue
		fi
		# check for mandatory sections
		while read section
		do
			if (grep -- "$section" ${me}_$$.out >/dev/null 2>&1)
			then
				echo_v "Found in $page, section $section."
			else
				echo_e "cannot find section '$section' in $page"
				retval=1
				continue;
			fi
		done<<_ACEOF
NAME
SYNOPSIS
DESCRIPTION
IDENTIFICATION
_ACEOF
		# check for recommended sections
		while read section
		do
			if (grep -- "$section" ${me}_$$.out >/dev/null 2>&1)
			then
				echo_v "Found in $page, section $section."
			else
				echo_w "cannot find section '$section' in $page"
			fi
		done<<_ACEOF
ARGUMENTS
RETURN
ERRORS
CONTEXT
COMPATIBILITY
CONFORMANCE
HISTORY
_ACEOF
	done
	echo_v "---------------------------------------------------------------"
done <Libraries.map

rm -f Libraries.map ${me}_$$.out ${me}_$$.err

exit $retval
