#!/bin/bash
# =============================================================================
# 
# @(#) $RCSfile: netbenchmark,v $ $Name:  $($Revision: 1.1.2.1 $) $Date: 2004/08/10 05:30:29 $
#
# -----------------------------------------------------------------------------
#
# Copyright (c) 2001-2004  OpenSS7 Corporation <http://www.openss7.com>
# Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
#
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 675 Mass
# Ave, Cambridge, MA 02139, USA.
#
# -----------------------------------------------------------------------------
#
# U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
# behalf of the U.S. Government ("Government"), the following provisions apply
# to you.  If the Software is supplied by the Department of Defense ("DoD"), it
# is classified as "Commercial Computer Software" under paragraph 252.227-7014
# of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
# successor regulations) and the Government is acquiring only the license rights
# granted herein (the license rights customarily provided to non-Government
# users).  If the Software is supplied to any unit or agency of the Government
# other than DoD, it is classified as "Restricted Computer Software" and the
# Government's rights in the Software are defined in paragraph 52.227-19 of the
# Federal Acquisition Regulations ("FAR") (or any success regulations) or, in
# the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
# (or any successor regulations).
#
# -----------------------------------------------------------------------------
#
# Commercial licensing and support of this software is available from OpenSS7
# Corporation at a fee.  See http://www.openss7.com/
#
# -----------------------------------------------------------------------------
#
# Last Modified $Date: 2004/08/10 05:30:29 $ by $Author: brian $
#
# =============================================================================

ECHO='echo'
SHELL='/bin/bash'
SED='sed'

# check that we have a working $ECHO
if test "X$1" = X--no-reexec ; then
# Discard the --no-reexec flag and continue
    shift
elif test "X$1" = X--fallback-echo ; then
    :
else
    exec $SHELL "$0" --no-reexec ${1+"$@"}
fi

if test "X$1" = X--fallback ; then
    shift
    cat <<EOF
$*
EOF
    exit 0
fi

program=`$ECHO "$0" | $SED -e 's%^.*/%%'`
modename="$program"

ident='$RCSfile: netbenchmark,v $ $Name:  $($Revision: 1.1.2.1 $)'

HELP="Try \`$program --help' for more information."

MKDIR='mkdir'
MV='/bin/mv -f'
RM='/bin/rm -f'

# Sed substitution that helps us do robust quoting.  It backslashifies
# metacharacters that are still active within double-quoted strings.
Xsed="$SED"' -e 1s/^X//'
sed_quote_subst='s/\([\\`\\"$\\\\]\)/\\\1/g'
# test EBCDIC or ASCII
case `$ECHO A | od -x` in
    *[Cc]1*) # EBCDIC based system
	SP2NL="tr '\100' '\n'"
	NL2SP="tr '\r\n' '\100\100'"
	;;
    *) # Assume ASCII based system
	SP2NL="tr '\040' '\012'"
	NL2SP="tr '\015\012' '\040\040'"
	;;
esac

# NLS nuisances
# Only set LANG and LC_ALL to C if already set.
# These must not be set unconditionally because not all systems understand
# e.g. LANG=C (notably SCO).
# We save the old values to restore during execute mode.
if test "${LC_ALL+set}" = set ; then
    save_LC_ALL="$LC_ALL" ; LC_ALL=C ; export LC_ALL
fi
if test "${LANG+set}" = set ; then
    save_LANG="$LANG" ; LANG=C ;  export LANG
fi

# Make sure IFS has a sensible default
: ${IFS=" 	"}

my_letters='abcdefghijklmnopqrstuvwxyz'
my_LETTERS='ABCDEFGHIJLKMNOPQRSTUVWXYZ'
my_Letters=$my_letters$my_LETTERS
my_numbers='0123456789'
my_alphano=$my_Letters$my_numbers
my_uppercase="$SED y%*$my_letters%P$my_LETTERS%;s%[^_$my_alphano]%_%g"
my_tokenize="$SED s%[^a-zA-Z0-9]%_%g"

# defaults

command=
filename=
debug=0
verbose=1

function version()
{
    if test :${show:-yes} = :no ; then
	return
    fi
    cat <<EOF
$program:
    $ident
    Copyright (c) 2001-2004  OpenSS7 Corporation.  All Rights Reserved.
    Distributed under GPL Version 2, included here by reference.
EOF
}

function usage()
{
    if test :${show:-yes} = :no ; then
	return
    fi
    cat <<EOF
Usage:
    $program [options]
    $program { -h | --help }
    $program { -V | --version }
    $program { -C | --copying }
EOF
}

function help()
{
    if test :${show:-yes} = :no ; then
	return
    fi
    usage
    cat <<EOF
Options:
    -n, --dry-run
	do not execute but verify actions
    -q, --quiet
	supress normal output
    -D, --debug [LEVEL]
	increase or set debugging verbosity
    -v, --verbose [LEVEL]
	increase or set output verbosity
    -h, --help
	prints this usage information and exits
    -V, --version
	prints the version information and exits
    -C, --copying
	prints copying permissions and exits
EOF
}

function copying()
{
    if test :${show:-yes} = :no ; then
	return
    fi
    cat <<EOF
--------------------------------------------------------------------------------
$ident
--------------------------------------------------------------------------------
Copyright (c) 2001-2004  OpenSS7 Corporation <http://www.openss7.com/>
Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>

All Rights Reserved.
--------------------------------------------------------------------------------
This program is free software; you can  redistribute  it and/or modify  it under
the terms  of the GNU General Public License  as  published by the Free Software
Foundation; either  version  2  of  the  License, or (at  your option) any later
version.

This program is distributed in the hope that it will  be useful, but WITHOUT ANY
WARRANTY; without event  the implied warranty of MECHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.  See the GNU General Public License for more details.

You should  have received a copy of the GNU  General  Public License  along with
this program; if not, write to the Free Software Foundation, Inc., 675 Mass Ave.
Cambridge, MA 02139, USA.
--------------------------------------------------------------------------------
U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on behalf
of the U.S. Government ("Government"), the following provisions apply to you. If
the Software is supplied by the  Department of Defense ("DoD"), it is classified
as "Commercial  Computer  Software"  under  paragraph  252.227-7014  of the  DoD
Supplement  to the  Federal Acquisition Regulations  ("DFARS") (or any successor
regulations) and the  Government  is acquiring  only the  license rights granted
herein (the license rights customarily provided to non-Government users). If the
Software is supplied to any unit or agency of the Government  other than DoD, it
is  classified as  "Restricted Computer Software" and the Government's rights in
the Software  are defined  in  paragraph 52.227-19  of the  Federal  Acquisition
Regulations ("FAR")  (or any successor regulations) or, in the cases of NASA, in
paragraph  18.52.227-86 of  the  NASA  Supplement  to the FAR (or any  successor
regulations).
--------------------------------------------------------------------------------
Commercial  licensing  and  support of this  software is  available from OpenSS7
Corporation at a fee.  See http://www.openss7.com/
--------------------------------------------------------------------------------
EOF
}

function option_unrec()
{
    if test ${verbose:-0} -gt 0 ; then
	opt=`$ECHO -n "X$1" | $Xsed -e 's|=.*||'`
	$ECHO "$program: syntax error -- \`$opt' unrecognized" >&2
	( usage ) >&2
    fi
    exit 2
}

function option_noarg()
{
    if test ${verbose:-0} -gt 0 ; then
	opt=`$ECHO -n "X$1" | $Xsed -e 's|=.*||'`
	$ECHO "$program: syntax error -- \`$opt' does not accept an argument" >&2
	( usage ) >&2
    fi
    exit 2
}

function option_needarg()
{
    if test ${verbose:-0} -gt 0 ; then
	$ECHO "$program: syntax error -- \`$1' requires an argument" >&2
	( usage ) >&2
    fi
    exit 2
}

function option_after()
{
    if test ${verbose:-0} -gt 0 ; then
	$ECHO "$program: syntax error -- \`$1' cannot occur after \`$2'" >&2
	( usage ) >&2
    fi
    exit 2
}

function option_with()
{
    if test ${verbose:-0} -gt 0 ; then
	$ECHO "$program: syntax error -- \`$1' cannot occur with \`$2'" >&2
	( usage ) >&2
    fi
    exit 2
}

# Parse our command line options once, thoroughly.
while test "$#" -gt 0 -o ":$more" != ":"
do
    if test ":$more" != ":" ; then
	arg="-$more"
	more=
    else
	arg="$1"
	shift
    fi
    if test x"$more_options" = xno ; then
	nonopt="$arg"
	break
    fi
    # check for attached option argument
    case $arg in
	--filename=* | --filenam=* | --filena=* | --filen=* | --file=* | --fil=* | --fi=* | --f=*)
	    optarg=`$ECHO "X$arg" | $Xsed -e 's/[-_a-zA-Z0-9]*=//'`
	    ;;
	--*=*)
	    option_noarg $arg ;;
	-[nqDvhVC])
	    optarg= ;;
	-[nqDvhVC]*)
	    optarg=
	    more=`$ECHO "X$arg" | $Xsed -e 's|-[cdinqDvhVC]||'`
	    eval "arg=\`$ECHO \"X$arg\" | $Xsed -e 's|$more||'\`"
	    ;;
	-f)
	    optarg= ;;
	-f*)
	    optarg=`$ECHO "X$arg" | $Xsed -e 's|-f||'` ;;
	*)
	    optarg= ;;
    esac
    # check for optional or required option argument
    if test -n "$prev" ; then
	case $arg in
	    -*) # optional arguments not forthcoming
		case $prev in
		    debug | verbose) eval "(($prev++))" ;;
		    # these have required arguments
		    filename)
			option_needarg $prevopt ;;
		esac
		prev= ; prevopt=
		;;
	    *) # if the previous option needs an argument, assign it.
		eval "$prev=\"\$arg\""
		prev= ; prevopt=
		continue
		;;
	esac
    fi
    # Have we seen a non-optional argument yet?
    case $arg in
	--help | --h | --Help | --H | -h | -H | -\? | --\?)
	    show_help=yes
	    if test ":$command" = ":" ; then command=none ; fi
	    ;;
	--version | --versio | --versi | --vers | -V)
	    show_version=yes
	    if test ":$command" = ":" ; then command=none ; fi
	    ;;
	--copying | --copyin | --copyi | --copy | --cop | --co | --c | -C)
	    show_copying=yes
	    if test ":$command" = ":" ; then command=none ; fi
	    ;;
	--verbose | --verbos | --verbo | --verb)
	    prevopt="$arg"
	    prev=verbose
	    ;;
	-v)
	    ((verbose++))
	    ;;
	--verbose=* | --verbos=* | --verbo=* | --verb=*)
	    verbose="$optarg"
	    ;;
	--debug | --debu | --deb)
	    prevopt="$arg"
	    prev=debug
	    ;;
	-D)
	    $ECHO "$program: enabling shell trace mode" 1>&2
	    set -x
	    ;;
	--debug=* | --debu=* | --deb=*)
	    debug="$optarg"
	    ;;
	--dry-run | --dryrun | --n | -n)
	    run=no
	    ;;
	--quiet | --silent | -q)
	    show=no
	    verbose=0
	    debug=0
	    ;;
	--filename | --filenam | --filena | --filen | --file | --fis | --fi | --f | -f)
	    if test ":$command" = ":config" ; then option_with --filename --config ; fi
	    if test ":$command" = ":" ; then command=filename ; fi
	    prevopt="$arg"
	    prev=filename
	    ;;
	--filename=* | --filenam=* | --filena=* | --filen=* | --file=* | --fil=* | --fi=* | --f=* | -f*)
	    filename="$optarg"
	    if test ":$command" = ":config" ; then option_with --filename --config ; fi
	    if test ":$command" = ":" ; then command=filename ; fi
	    ;;
	--config | --confi | --conf | --con | --co | --c | -c)
	    if test ":$command" != ":" -a ":$command" != ":config" ; then option_after $arg --$command ; fi
	    command=config
	    ;;
	--install | --instal | --insta | --inst | --ins | --in | --i | -i)
	    if test ":$command" != ":" -a ":$command" != ":install" ; then option_after $arg --$command ; fi
	    command=install
	    ;;
	--delete | --delet | --dele | --del | --de | --d | -d)
	    if test ":$command" != ":" -a ":$command" != ":delete" ; then option_after $arg --$command ; fi
	    command=delete
	    ;;
	--)
	    # end of options
	    more_options=no
	    ;;
	-*)
	    option_unrec $arg
	    ;;
	*)
	    nonopt="${nonopt}${nonopt:+ }'$arg'"
	    ;;
    esac
done

# hit end of list wanting an argument
case $prev in
    # these have optional arguments
    debug | verbose) eval "(($prev++))" ;;
    # the rest have required arguments
    filename)
	option_needarg $prevopt ;;
esac

if test x"$nonopt${nonopt:+ }${1+$@}" != "x" ; then
    eval "files=($nonopt${nonopt:+ }${1+$@})"
else
    files=
fi

# assign all defaults
if test ":$command" = ":" ; then
    command=
fi
if test ":$filename" = ":" ; then
    for file in `$ECHO -n "$default_filesrch" | $SED -e 's|:| |g'` ; do
	if test -f $file ; then
	    default_filename="$file"
	    break
	fi
    done
    filename="$default_filename"
fi

function none_command()
{
    if test -n "$show_version$show_help$show_copying" ; then
	if test ${verbose:-0} -gt 1 ; then
	    $ECHO "Displaying information"
	fi
	if test ":$show_version" != ":" ; then
	    version
	fi
	if test ":$show_help" != ":" ; then
	    help
	fi
	if test ":$show_copying" != ":" ; then
	    copying
	fi
    fi
}

case "$program" in
    *)
	:
	;;
esac

case "$command" in
    none)
	none_command
	;;
    *)
	( usage ) >&2
	exit 1
	;;
esac




# vim: ft=sh noet sw=4 nocindent
