'\" rtp
.\" -*- nroff -*- vim: ft=nroff noautoindent nocindent nosmartindent
.\"
.\" @(#) $Id: msgsize.9.man,v 0.9.2.7 2005/05/14 08:34:27 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (C) 2001-2005  OpenSS7 Corporation <www.openss7.com>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" -------------------------------------------------------------------------
.\"
.\" U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
.\" on behalf of the U.S. Government ("Government"), the following
.\" provisions apply to you.  If the Software is supplied by the Department
.\" of Defense ("DoD"), it is classified as "Commercial Computer Software"
.\" under paragraph 252.227-7014 of the DoD Supplement to the Federal
.\" Acquisition Regulations ("DFARS") (or any successor regulations) and the
.\" Government is acquiring only the license rights granted herein (the
.\" license rights customarily provided to non-Government users).  If the
.\" Software is supplied to any unit or agency of the Government other than
.\" DoD, it is classified as "Restricted Computer Software" and the
.\" Government's rights in the Software are defined in paragraph 52.227-19
.\" of the Federal Acquisition Regulations ("FAR") (or any successor
.\" regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
.\" NASA Supplement to the FAR (or any successor regulations).
.\"
.\" =========================================================================
.\" 
.\" Commercial licensing and support of this software is available from
.\" OpenSS7 Corporation at a fee.  See http://www.openss7.com/
.\" 
.\" =========================================================================
.\"
.\" Last Modified $Date: 2005/05/14 08:34:27 $ by $Author: brian $
.\"
.\" =========================================================================
.so streams.macros
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database streams.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.\"
.\"
.TH MSGSIZE 9 "@PACKAGE_DATE@" "@PACKAGE@-@VERSION@" "@PACKAGE_TITLE@ DDI/DKI"
.\"
.\"
.SH NAME
.B msgsize
\- calculate the size of the message blocks in a \fISTREAMS\fP message
.\"
.\"
.SH SYNOPSIS
.PP
.B #include <sys/stream.h>
.HP
.BI "int msgsize(mblk_t *" mp );
.\"
.\"
.SH ARGUMENTS
.TP
.I mp
the message to count message bytes.
.\"
.\"
.SH DESCRIPTION
.PP
.BR msgsize ()
counts the size of all of the blocks in the message pointed to by
.IR mp .
.\"
.\"
.SH RETURN
.PP
Upon success,
.BR msgsize ()
returns the number of bytes in the message pointed to by
.IR mp .
.PP
Upon failure,
.BR msgsize ()
returns zero (0).
.\"
.\"
.SH ERRORS
.PP
.BR msgsize ()
fails and returns zero (0) when
the message pointer
.I mp
is
.BR NULL .
.\"
.\"
.SH CONTEXT
.PP
.BR msgsize ()
can be called from any context, including user context, module procedures,
callouts, callbacks, soft interrupts and interrupt service routines.
.\"
.\"
.SH MP-STREAMS
.PP
.BR msgsize ()
is MP-safe.  It is the responsibility of the caller, however, to ensure
exclusive access to the passed in message.
.\"
.\"
.SH NOTICES
.PP
.BR msgsize ()
is used internally to count the size of messages place on and taken off of
message queues.
.\"
.\"
.SH "SEE ALSO"
.PP
.BR msgdsize (9),
.BR xmsgsize (9).
.\"
.\"
.SH BUGS
.PP
.BR msgsize ()
has no known bugs.
.\"
.\"
.SH COMPATIBILITY
.PP
.BR msgsize ()
is compatible with LiS
.[
LiS
.]
with the following exceptions:
.IP \(em \w'\(em\(em'u
.BR msgsize ()
counts the size
.RI ( b_wptr  " - " b_rptr )
of all blocks in the message.
LiS counts the absolute size
.RI ( db_lim " - " db_base )
of all blocks in the message.
.PP
Symbol
.BR lis_msgsize ()
is provided for compatibility with LiS.  See
.BR liscompat (9).
.PP
See
.BR STREAMS (9)
for additional compatibility information.
.\"
.\"
.SH CONFORMANCE
.PP
.BR msgsize ()
is an LiS specific function.
.\"
.\"
.SH HISTORY
.PP
.BR msgsize ()
first appeared in LiS.
.\"
.\"
.[
$LIST$
.]
.TI
