/*****************************************************************************

 @(#) $RCSfile: ds0.c,v $ $Name:  $($Revision: 1.1.2.3 $) $Date: 2011-05-31 09:46:11 $

 -----------------------------------------------------------------------------

 Copyright (c) 2008-2012  Monavacon Limited <http://www.monavacon.com/>
 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software: you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation, version 3 of the license.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 -----------------------------------------------------------------------------

 Last Modified $Date: 2011-05-31 09:46:11 $ by $Author: brian $

 -----------------------------------------------------------------------------

 $Log: ds0.c,v $
 Revision 1.1.2.3  2011-05-31 09:46:11  brian
 - new distros

 Revision 1.1.2.2  2010-11-28 14:22:11  brian
 - remove #ident, protect _XOPEN_SOURCE

 Revision 1.1.2.1  2009-06-21 11:42:31  brian
 - added files to new distro

 Revision 0.9.2.3  2009-02-18 20:18:57  brian
 - updated agents

 Revision 0.9.2.2  2009-01-19 13:31:54  brian
 - updating standalone agents

 Revision 0.9.2.1  2009-01-16 20:39:30  brian
 - added standard mibs

 *****************************************************************************/

static char const ident[] = "$RCSfile: ds0.c,v $ $Name:  $($Revision: 1.1.2.3 $) $Date: 2011-05-31 09:46:11 $";

/* This file was generated by mib2c and is intended for use as
   a mib module for the ucd-snmp snmpd agent. */
#include <ucd-snmp/ucd-snmp-config.h>
#include <ucd-snmp/ucd-snmp-includes.h>
#include <ucd-snmp/ucd-snmp-agent-includes.h>
#include <ucd-snmp/agent_trap.h>
#include <ucd-snmp/callback.h>
#include <ucd-snmp/snmp-tc.h>
#include <ucd-snmp/default_store.h>
#include <ucd-snmp/snmp_alarm.h>
/* The following header files are mangled in most recent net-snmp releases so
 * the versions from UCD-SNMP 4.2.5 are included here.  */
#if defined HAVE_LIBNETSNMP
#else				/* defined HAVE_LIBNETSNMP */
#endif				/* defined HAVE_LIBNETSNMP */
/* These are messed up on both. */
#include "ds_agent.h"
#ifdef HAVE_UCD_SNMP_UTIL_FUNCS_H
#include <ucd-snmp/util_funcs.h>
/* Many recent net-snmp UCD compatible headers do not declare header_generic. */
int header_generic(struct variable *, oid *, size_t *, int, size_t *, WriteMethod **);
#else				/* HAVE_UCD_SNMP_UTIL_FUNCS_H */
#include "util_funcs.h"
#endif				/* HAVE_UCD_SNMP_UTIL_FUNCS_H */
#ifdef HAVE_UCD_SNMP_HEADER_COMPLEX_H
#include <ucd-snmp/header_complex.h>
#else				/* HAVE_UCD_SNMP_HEADER_COMPLEX_H */
#include "header_complex.h"
#endif				/* HAVE_UCD_SNMP_HEADER_COMPLEX_H */
/* This one is the other way around: it is just fine for net-snmp, but
 * ucd-snmp does not provide the header file at all.  */
#ifdef HAVE_UCD_SNMP_MIB_MODULES_H
#include <ucd-snmp/mib_modules.h>
#else				/* HAVE_UCD_SNMP_MIB_MODULES_H */
#ifdef HAVE_NET_SNMP_AGENT_MIB_MODULES_H
#include <net-snmp/agent/mib_modules.h>
#else				/* HAVE_NET_SNMP_AGENT_MIB_MODULES_H */
#include "mib_modules.h"
#endif				/* HAVE_NET_SNMP_AGENT_MIB_MODULES_H */
#endif				/* HAVE_UCD_SNMP_MIB_MODULES_H */
#include <stdint.h>
#include <signal.h>
#include <sys/stat.h>		/* for struct stat, fstat() */
#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>
#include <pwd.h>		/* for getpwuid() getpwnam() */
#include <grp.h>		/* for getgrgid() getgrnam() */
#include <libgen.h>		/* for basename() */
#include <fcntl.h>		/* for O_CREAT */
#include <sys/sysctl.h>		/* for sysctl */
#include <errno.h>
#include <string.h>
#ifdef _GNU_SOURCE
#include <getopt.h>
#endif
#include "ds0.h"
#undef MASTER
#define MY_FACILITY(__pri)	(LOG_DAEMON|(__pri))
#if defined MODULE
#if defined MASTER
const char sa_program[] = "ds0";
int sa_fclose = 1;			/* default close files between requests */
int sa_changed = 1;			/* indication to reread MIB configuration */
int sa_stats_refresh = 1;		/* indications that statistics, the mib or its tables need to be refreshed */
int sa_request = 1;			/* request number for per-request actions */
int sa_dump = 0;			/* default packet dump */
int sa_debug = 0;			/* default no debug */
#endif				/* defined MASTER */
#endif				/* defined MODULE */
static int my_fd = -1;			/* file descriptor for this MIB's use */
static int my_readfd = -1;		/* file descriptor for autonomnous events */
volatile int ds0_refresh = 1;
volatile int dsx0ConfigTable_refresh = 1;
volatile int dsx0ChanMappingTable_refresh = 1;

/*
 * ds0_variables_oid: object identifier for ds0
 * This is the top level oid that we want to register under.  This is essentially a prefix, with the
 * suffix appearing in the variable below.
 */
oid ds0_variables_oid[8] = { 1, 3, 6, 1, 2, 1, 10, 81 };

/*
 * Oids for use in notifications defined in this MIB.
 */

/*
 * Oids accessible only for notify defined in this MIB.
 */

/*
 * Other oids defined in this MIB.
 */
oid ds0ConfigGroup_oid[11] = { 1, 3, 6, 1, 2, 1, 10, 81, 2, 1, 1 };
oid ds0Compliance_oid[11] = { 1, 3, 6, 1, 2, 1, 10, 81, 2, 2, 1 };
static oid zeroDotZero_oid[2] = { 0, 0 };
static oid snmpTrapOID_oid[11] = { 1, 3, 6, 1, 6, 3, 1, 1, 4, 1, 0 };

/*
 * variable4 ds0_variables: tree for ds0
 * This variable defines function callbacks and type return information for the ds0 mib section
 */
struct variable4 ds0_variables[] = {
	/* magic number, variable type, ro/rw, callback fn, L, oidsuffix */
#define   DSX0DS0CHANNELNUMBER  2
	{(u_char) DSX0DS0CHANNELNUMBER, ASN_INTEGER, RONLY, var_dsx0ConfigTable, 3, {1, 1, 1}},
#define   DSX0ROBBEDBITSIGNALLING  3
	{(u_char) DSX0ROBBEDBITSIGNALLING, ASN_INTEGER, RWRITE, var_dsx0ConfigTable, 3, {1, 1, 2}},
#define   DSX0CIRCUITIDENTIFIER  4
	{(u_char) DSX0CIRCUITIDENTIFIER, ASN_OCTET_STR, RWRITE, var_dsx0ConfigTable, 3, {1, 1, 3}},
#define   DSX0IDLECODE          5
	{(u_char) DSX0IDLECODE, ASN_INTEGER, RWRITE, var_dsx0ConfigTable, 3, {1, 1, 4}},
#define   DSX0SEIZEDCODE        6
	{(u_char) DSX0SEIZEDCODE, ASN_INTEGER, RWRITE, var_dsx0ConfigTable, 3, {1, 1, 5}},
#define   DSX0RECEIVEDCODE      7
	{(u_char) DSX0RECEIVEDCODE, ASN_INTEGER, RONLY, var_dsx0ConfigTable, 3, {1, 1, 6}},
#define   DSX0TRANSMITCODESENABLE  8
	{(u_char) DSX0TRANSMITCODESENABLE, ASN_INTEGER, RWRITE, var_dsx0ConfigTable, 3, {1, 1, 7}},
#define   DSX0DS0BUNDLEMAPPEDIFINDEX  9
	{(u_char) DSX0DS0BUNDLEMAPPEDIFINDEX, ASN_INTEGER, RONLY, var_dsx0ConfigTable, 3, {1, 1, 8}},
#define   DSX0CHANMAPPEDIFINDEX  12
	{(u_char) DSX0CHANMAPPEDIFINDEX, ASN_INTEGER, RONLY, var_dsx0ChanMappingTable, 3, {3, 1, 1}},
};

/* (L = length of the oidsuffix) */
struct ds0_data *ds0Storage = NULL;

/* global storage of our data, saved in and configured by header_complex() */
struct header_complex_index *dsx0ConfigTableStorage = NULL;
struct header_complex_index *dsx0ChanMappingTableStorage = NULL;

void (*ds0old_signal_handler) (int) = NULL;	/* save old signal handler just in case */
void ds0_loop_handler(int);
void ds0_fd_handler(int, void *);

/**
 * @fn void init_ds0(void)
 * @brief ds0 initialization routine.
 *
 * This is called when the agent starts up.  At a minimum, registration of the MIB variables
 * structure (ds0_variables) should take place here.  By default the function also
 * registers the configuration handler and configuration store callbacks.
 *
 * Additional registrations that may be considered here are calls to regsiter_readfd(),
 * register_writefd() and register_exceptfd() for hooking into the snmpd event loop, but only when
 * used as a loadable module.  By default this function establishes a single file descriptor to
 * read, or upon which to handle exceptions.  Note that the snmpd only supports a maximum of 32
 * extneral file descriptors, so these should be used sparingly.
 *
 * When running as a loadable module, it is also necessary to hook into the snmpd event loop so that
 * the current request number can be deteremined.  This is accomplished by using a trick of the
 * external_signal_scheduled and external_signal_handler mechanism which is called on each event
 * loop when external_signal_scheduled is non-zero.  This is used to increment the sa_request value
 * on each snmpd event loop interation so that calls to MIB tree functions can determine whether
 * they belong to a fresh request or not (primarily for cacheing and possibly to clean up non-polled
 * file descriptors).
 */
void
init_ds0(void)
{
	(void) my_fd;
	(void) zeroDotZero_oid;
	(void) snmpTrapOID_oid;
	DEBUGMSGTL(("ds0", "init_ds0: initializing...  "));
	/* register ourselves with the agent to handle our mib tree */
	REGISTER_MIB("ds0", ds0_variables, variable4, ds0_variables_oid);
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_SHUTDOWN, term_ds0, NULL);
	/* register our config handler(s) to deal with registrations */
	snmpd_register_config_handler("ds0", parse_ds0, NULL, "HELP STRING");
	snmpd_register_config_handler("dsx0ConfigTable", parse_dsx0ConfigTable, NULL, "HELP STRING");
	snmpd_register_config_handler("dsx0ChanMappingTable", parse_dsx0ChanMappingTable, NULL, "HELP STRING");

	/* we need to be called back later to store our data */
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_STORE_DATA, store_ds0, NULL);
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_STORE_DATA, store_dsx0ConfigTable, NULL);
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_STORE_DATA, store_dsx0ChanMappingTable, NULL);

	/* place any other initialization junk you need here */
	if (my_readfd >= 0) {
		register_readfd(my_readfd, ds0_fd_handler, (void *) 0);
		register_exceptfd(my_readfd, ds0_fd_handler, (void *) 1);
	}
	ds0old_signal_handler = external_signal_handler[SIGCHLD];
	external_signal_handler[SIGCHLD] = &ds0_loop_handler;
	external_signal_scheduled[SIGCHLD] = 1;
	DEBUGMSGTL(("ds0", "done.\n"));
}

/**
 * @fn void deinit_ds0(void)
 * @brief deinitialization routine.
 *
 * This is called before the agent is unloaded.  At a minimum, deregistration of the MIB variables
 * structure (ds0_variables) should take place here.  By default, the function also
 * deregisters the the configuration file handlers for the MIB variables and table rows.
 *
 * Additional deregistrations that may be required here are calls to unregister_readfd(),
 * unregister_writefd() and unregsiter_exceptfd() for unhooking from the snmpd event loop, but only
 * when used as a loadable module.  By default if a read file descriptor exists, it is unregistered.
 */
void
deinit_ds0(void)
{
	DEBUGMSGTL(("ds0", "deinit_ds0: deinitializating...  "));
	external_signal_handler[SIGCHLD] = ds0old_signal_handler;
	if (my_readfd >= 0) {
		unregister_exceptfd(my_readfd);
		unregister_readfd(my_readfd);
		close(my_readfd);
		my_readfd = -1;
	}
	unregister_mib(ds0_variables_oid, sizeof(ds0_variables_oid) / sizeof(oid));
	snmpd_unregister_config_handler("ds0");
	snmpd_unregister_config_handler("dsx0ConfigTable");
	snmpd_unregister_config_handler("dsx0ChanMappingTable");

	/* place any other de-initialization junk you need here */
	DEBUGMSGTL(("ds0", "done.\n"));
}

int
term_ds0(int majorID, int minorID, void *serverarg, void *clientarg)
{
	DEBUGMSGTL(("ds0", "term_ds0: terminating...  "));
	deinit_ds0();
	DEBUGMSGTL(("ds0", "done.\n"));
	return 0;
}

/**
 * @fn struct ds0_data *ds0_create(void)
 * @brief create a fresh data structure representing scalars in ds0.
 *
 * Creates a new ds0_data structure by allocating dynamic memory for the structure and
 * initializing the default values of scalars in ds0.
 */
struct ds0_data *
ds0_create(void)
{
	struct ds0_data *StorageNew = SNMP_MALLOC_STRUCT(ds0_data);

	DEBUGMSGTL(("ds0", "ds0_create: creating scalars...  "));
	if (StorageNew != NULL) {
		/* XXX: fill in default scalar values here into StorageNew */

	}
      done:
	DEBUGMSGTL(("ds0", "done.\n"));
	return (StorageNew);
	goto nomem;
      nomem:
	ds0_destroy(&StorageNew);
	goto done;
}

/**
 * @fn struct ds0_data *ds0_duplicate(struct ds0_data *thedata)
 * @param thedata the mib structure to duplicate
 * @brief duplicate a mib structure for the mib
 *
 * Duplicates the specified mib structure @param thedata and returns a pointer to the newly
 * allocated mib structure on success, or NULL on failure.
 */
struct ds0_data *
ds0_duplicate(struct ds0_data *thedata)
{
	struct ds0_data *StorageNew = SNMP_MALLOC_STRUCT(ds0_data);

	DEBUGMSGTL(("ds0", "ds0_duplicate: duplicating mib... "));
	if (StorageNew != NULL) {
	}
      done:
	DEBUGMSGTL(("ds0", "done.\n"));
	return (StorageNew);
	goto destroy;
      destroy:
	ds0_destroy(&StorageNew);
	goto done;
}

/**
 * @fn int ds0_destroy(struct ds0_data **thedata)
 * @param thedata pointer to the data structure in ds0.
 * @brief delete a scalars structure from ds0.
 *
 * Frees scalars that were previously removed from ds0.  Note that the strings associated
 * with octet strings, object identifiers and bit strings still attached to the structure will also
 * be freed.  The pointer that was passed in @param thedata will be set to NULL if it is not already
 * NULL.
 */
int
ds0_destroy(struct ds0_data **thedata)
{
	struct ds0_data *StorageDel;

	DEBUGMSGTL(("ds0", "ds0_destroy: deleting scalars...  "));
	if ((StorageDel = *thedata) != NULL) {
		SNMP_FREE(StorageDel);
		*thedata = StorageDel;
	}
	DEBUGMSGTL(("ds0", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int ds0_add(struct ds0_data *thedata)
 * @param thedata the structure representing ds0 scalars.
 * @brief adds node to the ds0 scalar data set.
 *
 * Adds a scalar structure to the ds0 data set.  Note that this function is necessary even
 * when the scalar values are not peristent.
 */
int
ds0_add(struct ds0_data *thedata)
{
	DEBUGMSGTL(("ds0", "ds0_add: adding data...  "));
	if (thedata)
		ds0Storage = thedata;
	DEBUGMSGTL(("ds0", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn void parse_ds0(const char *token, char *line)
 * @param token token used within the configuration file.
 * @param line line from configuration file matching the token.
 * @brief parse configuration file for ds0 entries.
 *
 * This callback is called by UCD-SNMP when it parses a configuration file and finds a configuration
 * file line for the registsred token (in this case ds0).  This routine is invoked by
 * UCD-SNMP to read the values of scalars in the MIB from the configuration file.  Note that this
 * procedure may exist regardless of the persistence of the MIB.  If there are no configured entries
 * in the configuration MIB, this function will simply not be called.
 */
void
parse_ds0(const char *token, char *line)
{
	size_t tmpsize;
	struct ds0_data *StorageTmp = ds0_create();

	DEBUGMSGTL(("ds0", "parse_ds0: parsing config...  "));
	if (StorageTmp == NULL) {
		config_perror("malloc failure");
		return;
	}
	/* XXX: remove individual scalars that are not persistent */
	ds0_add(StorageTmp);
	(void) tmpsize;
	DEBUGMSGTL(("ds0", "done.\n"));
}

/*
 * store_ds0(): stores .conf file entries needed to configure the mib.
 */
int
store_ds0(int majorID, int minorID, void *serverarg, void *clientarg)
{
	char line[SNMP_MAXBUF];
	char *cptr;
	size_t tmpsize;
	struct ds0_data *StorageTmp;

	DEBUGMSGTL(("ds0", "store_ds0: storing data...  "));
	refresh_ds0(1);
	if ((StorageTmp = ds0Storage) == NULL) {
		DEBUGMSGTL(("ds0", "error.\n"));
		return SNMPERR_GENERR;
	}
	(void) tmpsize;
	/* XXX: comment entire section if no scalars are persistent */
	{
		memset(line, 0, sizeof(line));
		strcat(line, "ds0 ");
		cptr = line + strlen(line);
		(void) cptr;
		/* XXX: remove individual scalars that are not persistent */
		snmpd_store_config(line);
	}
	DEBUGMSGTL(("ds0", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int check_ds0(struct ds0_data *StorageTmp, struct ds0_data *StorageOld)
 * @param StorageTmp the data as updated
 * @param StorageOld the data previous to update
 *
 * This function is used by mibs.  It is used to check, all scalars at a time, the varbinds
 * belonging to the mib.  This function is called for the first varbind in a mib at the beginning of
 * the ACTION phase.  The COMMIT phase does not ensue unless this check passes.  This function can
 * return SNMP_ERR_NOERR or a specific SNMP error value.  Values in StorageOld are the values before
 * the varbinds on the mib were applied; the values in StorageTmp are the new values.  The function
 * is permitted to change the values in StorageTmp to correct them; however, preferences should be
 * made for setting values that were not in the varbinds.
 */
int
check_ds0(struct ds0_data *StorageTmp, struct ds0_data *StorageOld)
{
	/* XXX: provide code to check the scalars for consistency */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int update_ds0(struct ds0_data *StorageTmp, struct ds0_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the set operation (ACTION phase)
 *
 * This function is used by mibs.  It is used to update, all scalars at a time, the varbinds
 * belonging to the mib.  This function is called for the first varbind in a mib at the beginning of
 * the COMMIT phase.  The start of the ACTION phase performs a consistency check on the mib before
 * allowing the request to proceed to the COMMIT phase.  The COMMIT phase then arrives here with
 * consistency already checked (see check_ds0()).  This function can
 * return SNMP_ERR_NOERROR or SNMP_ERR_COMMITFAILED.  Values in StorageOld are the values before the
 * varbinds on the mib were applied: the values in StorageTmp are the new values.
 */
int
update_ds0(struct ds0_data *StorageTmp, struct ds0_data *StorageOld)
{
	/* XXX: provide code to update the row with the underlying device */
	ds0_refresh = 1;
	return SNMP_ERR_NOERROR;
}

/**
 * @fn revert_ds0(struct 
 * @fn void revert_ds0(struct ds0_data *StorageTmp, struct ds0_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the undo operation (UNDO phase)
 */
void
revert_ds0(struct ds0_data *StorageTmp, struct ds0_data *StorageOld)
{
	/* XXX: provide code to revert the row with the underlying device */
	update_ds0(StorageOld, NULL);
}

/**
 * @fn void refresh_ds0(int force)
 * @param force forced refresh when non-zero.
 * @brief refresh the scalar values of ds0.
 *
 * Normally the values retrieved from the operating system are cached.  When the agent receives a
 * SIGPOLL from an open STREAMS configuration or administrative driver Stream, the STREAMS subsystem
 * indicates to the agent that the cache has been invalidated and that it should reread scalars and
 * tables from the STREAMS subsystem.  This function is used when the agent starts for the first
 * time, or after a SIGPOLL has been received (and a scalar has been requested).
 */
void
refresh_ds0(int force)
{
	if (ds0Storage == NULL) {
		struct ds0_data *StorageNew;

		if ((StorageNew = ds0_create()) == NULL)
			return;
		ds0Storage = StorageNew;
		ds0_refresh = 1;
	}
	if (!force && ds0_refresh == 0)
		return;
	DEBUGMSGTL(("ds0", "refresh_ds0: refreshing...  "));
	/* XXX: Update scalars as required here... */
	ds0_refresh = 0;
	DEBUGMSGTL(("ds0", "done.\n"));
}

/**
 * @fn u_char * var_ds0(struct variable *vp, oid *name, size_t *length, int exact, size_t *var_len, WriteMethod **write_method)
 * @param vp a pointer to the entry in the variables table for the requested variable.
 * @param name the object identifier for which to find.
 * @param length the length of the object identifier.
 * @param exact whether the name is exact.
 * @param var_len a pointer to the length of the representation of the object.
 * @param write_method a pointer to a write method for the object.
 * @brief locate variables in ds0.
 *
 * This function returns a pointer to a memory area that is static across the request that contains
 * the UCD-SNMP representation of the scalar (so that it may be used to read from for a GET,
 * GET-NEXT or GET-BULK request).  This returned pointer may be NULL, in which case the function is
 * telling UCD-SNMP that the scalar does not exist for reading; however, if write_method is
 * overwritten with a non-NULL value, the function is telling UCD-SNMP that the scalar exists for
 * writing.  Write-only objects can be effected in this way.
 */
u_char *
var_ds0(struct variable *vp, oid * name, size_t *length, int exact, size_t *var_len, WriteMethod ** write_method)
{
	struct ds0_data *StorageTmp;
	u_char *rval;

	DEBUGMSGTL(("ds0", "var_ds0: lookup up varbind...  "));
	if (header_generic(vp, name, length, exact, var_len, write_method) == MATCH_FAILED)
		return NULL;
	/* Refresh the MIB values if required. */
	refresh_ds0(0);
	if ((StorageTmp = ds0Storage) == NULL) {
		DEBUGMSGTL(("ds0", "no datastructure.\n"));
		return NULL;
	}
	*write_method = NULL;
	*var_len = 0;
	rval = NULL;
	/* This is where we do the value assignments for the mib results. */
	switch (vp->magic) {
	default:
		ERROR_MSG("");
	}
	if (rval)
		DEBUGMSGTL(("ds0", "found.\n"));
	else
		DEBUGMSGTL(("ds0", "not found.\n"));
	return (rval);
}

/**
 * @fn struct dsx0ConfigTable_data *dsx0ConfigTable_create(void)
 * @brief create a fresh data structure representing a new row in the dsx0ConfigTable table.
 *
 * Creates a new dsx0ConfigTable_data structure by allocating dynamic memory for the structure and
 * initializing the default values of columns in the table.  The row status object, if any, should
 * be set to RS_NOTREADY.
 */
struct dsx0ConfigTable_data *
dsx0ConfigTable_create(void)
{
	struct dsx0ConfigTable_data *StorageNew = SNMP_MALLOC_STRUCT(dsx0ConfigTable_data);

	DEBUGMSGTL(("ds0", "dsx0ConfigTable_create: creating row...  "));
	if (StorageNew != NULL) {
		/* XXX: fill in default row values here into StorageNew */
		StorageNew->ifIndex = 0;
		StorageNew->dsx0Ds0ChannelNumber = 0;
		StorageNew->dsx0RobbedBitSignalling = 0;
		if ((StorageNew->dsx0CircuitIdentifier = malloc(1)) == NULL)
			goto nomem;
		StorageNew->dsx0CircuitIdentifierLen = 0;
		StorageNew->dsx0CircuitIdentifier[StorageNew->dsx0CircuitIdentifierLen] = 0;
		StorageNew->dsx0IdleCode = 0;
		StorageNew->dsx0SeizedCode = 0;
		StorageNew->dsx0ReceivedCode = 0;
		StorageNew->dsx0TransmitCodesEnable = 0;
		StorageNew->dsx0Ds0BundleMappedIfIndex = 0;
	}
      done:
	DEBUGMSGTL(("ds0", "done.\n"));
	return (StorageNew);
	goto nomem;
      nomem:
	dsx0ConfigTable_destroy(&StorageNew);
	goto done;
}

/**
 * @fn struct dsx0ConfigTable_data *dsx0ConfigTable_duplicate(struct dsx0ConfigTable_data *thedata)
 * @param thedata the row structure to duplicate.
 * @brief duplicate a row structure for a table.
 *
 * Duplicates the specified row structure @param thedata and returns a pointer to the newly
 * allocated row structure on success, or NULL on failure.
 */
struct dsx0ConfigTable_data *
dsx0ConfigTable_duplicate(struct dsx0ConfigTable_data *thedata)
{
	struct dsx0ConfigTable_data *StorageNew = SNMP_MALLOC_STRUCT(dsx0ConfigTable_data);

	DEBUGMSGTL(("ds0", "dsx0ConfigTable_duplicate: duplicating row...  "));
	if (StorageNew != NULL) {
		StorageNew->dsx0ConfigTable_id = thedata->dsx0ConfigTable_id;
		StorageNew->ifIndex = thedata->ifIndex;
		StorageNew->dsx0Ds0ChannelNumber = thedata->dsx0Ds0ChannelNumber;
		StorageNew->dsx0RobbedBitSignalling = thedata->dsx0RobbedBitSignalling;
		if (!(StorageNew->dsx0CircuitIdentifier = malloc(thedata->dsx0CircuitIdentifierLen + 1)))
			goto destroy;
		memcpy(StorageNew->dsx0CircuitIdentifier, thedata->dsx0CircuitIdentifier, thedata->dsx0CircuitIdentifierLen);
		StorageNew->dsx0CircuitIdentifierLen = thedata->dsx0CircuitIdentifierLen;
		StorageNew->dsx0CircuitIdentifier[StorageNew->dsx0CircuitIdentifierLen] = 0;
		StorageNew->dsx0IdleCode = thedata->dsx0IdleCode;
		StorageNew->dsx0SeizedCode = thedata->dsx0SeizedCode;
		StorageNew->dsx0ReceivedCode = thedata->dsx0ReceivedCode;
		StorageNew->dsx0TransmitCodesEnable = thedata->dsx0TransmitCodesEnable;
		StorageNew->dsx0Ds0BundleMappedIfIndex = thedata->dsx0Ds0BundleMappedIfIndex;
	}
      done:
	DEBUGMSGTL(("ds0", "done.\n"));
	return (StorageNew);
	goto destroy;
      destroy:
	dsx0ConfigTable_destroy(&StorageNew);
	goto done;
}

/**
 * @fn int dsx0ConfigTable_destroy(struct dsx0ConfigTable_data **thedata)
 * @param thedata pointer to the extracted or existing data structure in the table.
 * @brief delete a row structure from a table.
 *
 * Frees a table row that was previously removed from a table.  Note that the strings associated
 * with octet strings, object identifiers and bit strings still attached to the structure will also
 * be freed.  The pointer that was passed in @param thedata will be set to NULL if it is not already
 * NULL.
 */
int
dsx0ConfigTable_destroy(struct dsx0ConfigTable_data **thedata)
{
	struct dsx0ConfigTable_data *StorageDel;

	DEBUGMSGTL(("ds0", "dsx0ConfigTable_destroy: deleting row...  "));
	if ((StorageDel = *thedata) != NULL) {
		SNMP_FREE(StorageDel->dsx0CircuitIdentifier);
		StorageDel->dsx0CircuitIdentifierLen = 0;
		SNMP_FREE(StorageDel);
		*thedata = StorageDel;
	}
	DEBUGMSGTL(("ds0", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int dsx0ConfigTable_add(struct dsx0ConfigTable_data *thedata)
 * @param thedata the structure representing the new row in the table.
 * @brief adds a row to the dsx0ConfigTable table data set.
 *
 * Adds a table row structure to the dsx0ConfigTable table.  Note that this function is necessary even
 * when the table rows are not peristent.  This function can be used within this MIB or other MIBs
 * by the agent to create rows within the table autonomously.
 */
int
dsx0ConfigTable_add(struct dsx0ConfigTable_data *thedata)
{
	struct variable_list *vars = NULL;

	DEBUGMSGTL(("ds0", "dsx0ConfigTable_add: adding data...  "));
	if (thedata) {
		/* add the index variables to the varbind list, which is used by header_complex to index the data */
		/* ifIndex */
		snmp_varlist_add_variable(&vars, NULL, 0, ASN_INTEGER, (u_char *) &thedata->ifIndex, sizeof(thedata->ifIndex));
		header_complex_add_data(&dsx0ConfigTableStorage, vars, thedata);
	}
	DEBUGMSGTL(("ds0", "registered an entry.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int dsx0ConfigTable_del(struct dsx0ConfigTable_data *thedata)
 * @param thedata pointer to the extracted or existing data structure in the table.
 * @brief delete a row structure from a table.
 *
 * Deletes a table row structure from the dsx0ConfigTable table but does not free it.  Note that this
 * function is necessary even when the table rows are not persistent.  This function can be used
 * within this MIB or another MIB by the agent to delete rows from the table autonomously.  The data
 * structure may either be already extracted from the data set, or the structure may still exist in
 * the data set.  This function will extract the row from the table if it has not already been
 * performed by the caller.
 */
int
dsx0ConfigTable_del(struct dsx0ConfigTable_data *thedata)
{
	struct dsx0ConfigTable_data *StorageDel;

	DEBUGMSGTL(("ds0", "dsx0ConfigTable_data: deleting data...  "));
	if ((StorageDel = thedata) != NULL) {
		struct header_complex_index *hciptr;

		if ((hciptr = header_complex_find_entry(dsx0ConfigTableStorage, StorageDel)) != NULL)
			header_complex_extract_entry(&dsx0ConfigTableStorage, hciptr);
	}
	DEBUGMSGTL(("ds0", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn void parse_dsx0ConfigTable(const char *token, char *line)
 * @param token token used within the configuration file.
 * @param line line from configuration file matching the token.
 * @brief parse configuration file for dsx0ConfigTable entries.
 *
 * This callback is called by UCD-SNMP when it parses a configuration file and finds a configuration
 * file line for the registsred token (in this case dsx0ConfigTable).  This routine is invoked by UCD-SNMP
 * to read the values of each row in the table from the configuration file.  Note that this
 * procedure may exist regardless of the persistence of the table.  If there are no configured
 * entries in the configuration table, this function will simply not be called.
 */
void
parse_dsx0ConfigTable(const char *token, char *line)
{
	size_t tmpsize;
	struct dsx0ConfigTable_data *StorageTmp = dsx0ConfigTable_create();

	DEBUGMSGTL(("ds0", "parse_dsx0ConfigTable: parsing config...  "));
	if (StorageTmp == NULL) {
		config_perror("malloc failure");
		return;
	}
	/* XXX: remove individual columns if not persistent */
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->ifIndex, &tmpsize);
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->dsx0Ds0ChannelNumber, &tmpsize);
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->dsx0RobbedBitSignalling, &tmpsize);
	SNMP_FREE(StorageTmp->dsx0CircuitIdentifier);
	line = read_config_read_data(ASN_OCTET_STR, line, &StorageTmp->dsx0CircuitIdentifier, &StorageTmp->dsx0CircuitIdentifierLen);
	if (StorageTmp->dsx0CircuitIdentifier == NULL) {
		config_perror("invalid specification for dsx0CircuitIdentifier");
		return;
	}
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->dsx0IdleCode, &tmpsize);
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->dsx0SeizedCode, &tmpsize);
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->dsx0ReceivedCode, &tmpsize);
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->dsx0TransmitCodesEnable, &tmpsize);
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->dsx0Ds0BundleMappedIfIndex, &tmpsize);
	dsx0ConfigTable_add(StorageTmp);
	(void) tmpsize;
	DEBUGMSGTL(("ds0", "done.\n"));
}

/*
 * store_dsx0ConfigTable(): store configuraiton file for dsx0ConfigTable
 * stores .conf file entries needed to configure the mib.
 */
int
store_dsx0ConfigTable(int majorID, int minorID, void *serverarg, void *clientarg)
{
	char line[SNMP_MAXBUF];
	char *cptr;
	size_t tmpsize;
	struct dsx0ConfigTable_data *StorageTmp;
	struct header_complex_index *hcindex;

	DEBUGMSGTL(("ds0", "store_dsx0ConfigTable: storing data...  "));
	refresh_dsx0ConfigTable(1);
	(void) tmpsize;
	for (hcindex = dsx0ConfigTableStorage; hcindex != NULL; hcindex = hcindex->next) {
		StorageTmp = (struct dsx0ConfigTable_data *) hcindex->data;
		/* XXX: comment entire section if row not persistent */
		{
			memset(line, 0, sizeof(line));
			strcat(line, "dsx0ConfigTable ");
			cptr = line + strlen(line);
			(void) cptr;
			/* XXX: remove individual columns if not persistent */
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->ifIndex, &tmpsize);
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->dsx0Ds0ChannelNumber, &tmpsize);
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->dsx0RobbedBitSignalling, &tmpsize);
			cptr = read_config_store_data(ASN_OCTET_STR, cptr, &StorageTmp->dsx0CircuitIdentifier, &StorageTmp->dsx0CircuitIdentifierLen);
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->dsx0IdleCode, &tmpsize);
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->dsx0SeizedCode, &tmpsize);
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->dsx0ReceivedCode, &tmpsize);
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->dsx0TransmitCodesEnable, &tmpsize);
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->dsx0Ds0BundleMappedIfIndex, &tmpsize);
			snmpd_store_config(line);
		}
	}
	DEBUGMSGTL(("ds0", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn struct dsx0ChanMappingTable_data *dsx0ChanMappingTable_create(void)
 * @brief create a fresh data structure representing a new row in the dsx0ChanMappingTable table.
 *
 * Creates a new dsx0ChanMappingTable_data structure by allocating dynamic memory for the structure and
 * initializing the default values of columns in the table.  The row status object, if any, should
 * be set to RS_NOTREADY.
 */
struct dsx0ChanMappingTable_data *
dsx0ChanMappingTable_create(void)
{
	struct dsx0ChanMappingTable_data *StorageNew = SNMP_MALLOC_STRUCT(dsx0ChanMappingTable_data);

	DEBUGMSGTL(("ds0", "dsx0ChanMappingTable_create: creating row...  "));
	if (StorageNew != NULL) {
		/* XXX: fill in default row values here into StorageNew */
		StorageNew->ifIndex = 0;
		StorageNew->dsx0Ds0ChannelNumber = 0;
		StorageNew->dsx0ChanMappedIfIndex = 0;
	}
      done:
	DEBUGMSGTL(("ds0", "done.\n"));
	return (StorageNew);
	goto nomem;
      nomem:
	dsx0ChanMappingTable_destroy(&StorageNew);
	goto done;
}

/**
 * @fn struct dsx0ChanMappingTable_data *dsx0ChanMappingTable_duplicate(struct dsx0ChanMappingTable_data *thedata)
 * @param thedata the row structure to duplicate.
 * @brief duplicate a row structure for a table.
 *
 * Duplicates the specified row structure @param thedata and returns a pointer to the newly
 * allocated row structure on success, or NULL on failure.
 */
struct dsx0ChanMappingTable_data *
dsx0ChanMappingTable_duplicate(struct dsx0ChanMappingTable_data *thedata)
{
	struct dsx0ChanMappingTable_data *StorageNew = SNMP_MALLOC_STRUCT(dsx0ChanMappingTable_data);

	DEBUGMSGTL(("ds0", "dsx0ChanMappingTable_duplicate: duplicating row...  "));
	if (StorageNew != NULL) {
		StorageNew->dsx0ChanMappingTable_id = thedata->dsx0ChanMappingTable_id;
		StorageNew->ifIndex = thedata->ifIndex;
		StorageNew->dsx0Ds0ChannelNumber = thedata->dsx0Ds0ChannelNumber;
		StorageNew->dsx0ChanMappedIfIndex = thedata->dsx0ChanMappedIfIndex;
	}
      done:
	DEBUGMSGTL(("ds0", "done.\n"));
	return (StorageNew);
	goto destroy;
      destroy:
	dsx0ChanMappingTable_destroy(&StorageNew);
	goto done;
}

/**
 * @fn int dsx0ChanMappingTable_destroy(struct dsx0ChanMappingTable_data **thedata)
 * @param thedata pointer to the extracted or existing data structure in the table.
 * @brief delete a row structure from a table.
 *
 * Frees a table row that was previously removed from a table.  Note that the strings associated
 * with octet strings, object identifiers and bit strings still attached to the structure will also
 * be freed.  The pointer that was passed in @param thedata will be set to NULL if it is not already
 * NULL.
 */
int
dsx0ChanMappingTable_destroy(struct dsx0ChanMappingTable_data **thedata)
{
	struct dsx0ChanMappingTable_data *StorageDel;

	DEBUGMSGTL(("ds0", "dsx0ChanMappingTable_destroy: deleting row...  "));
	if ((StorageDel = *thedata) != NULL) {
		SNMP_FREE(StorageDel);
		*thedata = StorageDel;
	}
	DEBUGMSGTL(("ds0", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int dsx0ChanMappingTable_add(struct dsx0ChanMappingTable_data *thedata)
 * @param thedata the structure representing the new row in the table.
 * @brief adds a row to the dsx0ChanMappingTable table data set.
 *
 * Adds a table row structure to the dsx0ChanMappingTable table.  Note that this function is necessary even
 * when the table rows are not peristent.  This function can be used within this MIB or other MIBs
 * by the agent to create rows within the table autonomously.
 */
int
dsx0ChanMappingTable_add(struct dsx0ChanMappingTable_data *thedata)
{
	struct variable_list *vars = NULL;

	DEBUGMSGTL(("ds0", "dsx0ChanMappingTable_add: adding data...  "));
	if (thedata) {
		/* add the index variables to the varbind list, which is used by header_complex to index the data */
		/* ifIndex */
		snmp_varlist_add_variable(&vars, NULL, 0, ASN_INTEGER, (u_char *) &thedata->ifIndex, sizeof(thedata->ifIndex));
		/* dsx0Ds0ChannelNumber */
		snmp_varlist_add_variable(&vars, NULL, 0, ASN_INTEGER, (u_char *) &thedata->dsx0Ds0ChannelNumber, sizeof(thedata->dsx0Ds0ChannelNumber));
		header_complex_add_data(&dsx0ChanMappingTableStorage, vars, thedata);
	}
	DEBUGMSGTL(("ds0", "registered an entry.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int dsx0ChanMappingTable_del(struct dsx0ChanMappingTable_data *thedata)
 * @param thedata pointer to the extracted or existing data structure in the table.
 * @brief delete a row structure from a table.
 *
 * Deletes a table row structure from the dsx0ChanMappingTable table but does not free it.  Note that this
 * function is necessary even when the table rows are not persistent.  This function can be used
 * within this MIB or another MIB by the agent to delete rows from the table autonomously.  The data
 * structure may either be already extracted from the data set, or the structure may still exist in
 * the data set.  This function will extract the row from the table if it has not already been
 * performed by the caller.
 */
int
dsx0ChanMappingTable_del(struct dsx0ChanMappingTable_data *thedata)
{
	struct dsx0ChanMappingTable_data *StorageDel;

	DEBUGMSGTL(("ds0", "dsx0ChanMappingTable_data: deleting data...  "));
	if ((StorageDel = thedata) != NULL) {
		struct header_complex_index *hciptr;

		if ((hciptr = header_complex_find_entry(dsx0ChanMappingTableStorage, StorageDel)) != NULL)
			header_complex_extract_entry(&dsx0ChanMappingTableStorage, hciptr);
	}
	DEBUGMSGTL(("ds0", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn void parse_dsx0ChanMappingTable(const char *token, char *line)
 * @param token token used within the configuration file.
 * @param line line from configuration file matching the token.
 * @brief parse configuration file for dsx0ChanMappingTable entries.
 *
 * This callback is called by UCD-SNMP when it parses a configuration file and finds a configuration
 * file line for the registsred token (in this case dsx0ChanMappingTable).  This routine is invoked by UCD-SNMP
 * to read the values of each row in the table from the configuration file.  Note that this
 * procedure may exist regardless of the persistence of the table.  If there are no configured
 * entries in the configuration table, this function will simply not be called.
 */
void
parse_dsx0ChanMappingTable(const char *token, char *line)
{
	size_t tmpsize;
	struct dsx0ChanMappingTable_data *StorageTmp = dsx0ChanMappingTable_create();

	DEBUGMSGTL(("ds0", "parse_dsx0ChanMappingTable: parsing config...  "));
	if (StorageTmp == NULL) {
		config_perror("malloc failure");
		return;
	}
	/* XXX: remove individual columns if not persistent */
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->ifIndex, &tmpsize);
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->dsx0Ds0ChannelNumber, &tmpsize);
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->dsx0ChanMappedIfIndex, &tmpsize);
	dsx0ChanMappingTable_add(StorageTmp);
	(void) tmpsize;
	DEBUGMSGTL(("ds0", "done.\n"));
}

/*
 * store_dsx0ChanMappingTable(): store configuraiton file for dsx0ChanMappingTable
 * stores .conf file entries needed to configure the mib.
 */
int
store_dsx0ChanMappingTable(int majorID, int minorID, void *serverarg, void *clientarg)
{
	char line[SNMP_MAXBUF];
	char *cptr;
	size_t tmpsize;
	struct dsx0ChanMappingTable_data *StorageTmp;
	struct header_complex_index *hcindex;

	DEBUGMSGTL(("ds0", "store_dsx0ChanMappingTable: storing data...  "));
	refresh_dsx0ChanMappingTable(1);
	(void) tmpsize;
	for (hcindex = dsx0ChanMappingTableStorage; hcindex != NULL; hcindex = hcindex->next) {
		StorageTmp = (struct dsx0ChanMappingTable_data *) hcindex->data;
		/* XXX: comment entire section if row not persistent */
		{
			memset(line, 0, sizeof(line));
			strcat(line, "dsx0ChanMappingTable ");
			cptr = line + strlen(line);
			(void) cptr;
			/* XXX: remove individual columns if not persistent */
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->ifIndex, &tmpsize);
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->dsx0Ds0ChannelNumber, &tmpsize);
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->dsx0ChanMappedIfIndex, &tmpsize);
			snmpd_store_config(line);
		}
	}
	DEBUGMSGTL(("ds0", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int check_dsx0ConfigTable_row(struct dsx0ConfigTable_data *StorageTmp, struct dsx0ConfigTable_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 *
 * This function is used both by tables that do and do not contain a RowStatus object.  It is used
 * to check, row-at-a-time, the varbinds belonging to the row.  Note that this function is not used
 * when rows are created or destroyed.  This function is called for the first varbind in a row at
 * the beginning of the ACTION phase.  The start of the ACTION pahse performs this consitency check
 * on the row before allowing the request to proceed to the COMMIT phase.  This function can return
 * SNMP_ERR_NOERR or a specific SNMP error value.  Values in StorageOld are the values before the
 * varbinds on the mib were applied; the values in StorageTmp are the new values.  The function is
 * permitted to change the values in StorageTmp to correct them; however, preference should be made
 * for setting values where were not in the varbinds.
 */
int
check_dsx0ConfigTable_row(struct dsx0ConfigTable_data *StorageTmp, struct dsx0ConfigTable_data *StorageOld)
{
	/* XXX: provide code to check the row for consistency */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int update_dsx0ConfigTable_row(struct dsx0ConfigTable_data *StorageTmp, struct dsx0ConfigTable_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the set operation (ACTION phase) on a row
 *
 * This function is used both by tables that do and do not contain a RowStatus object.  It is used
 * to update, row-at-a-time, the varbinds belonging to the row.  Note that this function is not used
 * when rows are created or destroyed.  This function is called for the first varbind in a row at
 * the beginning of the COMMIT phase.  The start of the ACTION phase performs a consistency check on
 * the row before allowing the request to proceed to the COMMIT phase.  The COMMIT phase then
 * arrives here with consistency already checked (see check_dsx0ConfigTable_row()).  This function can
 * return SNMP_ERR_NOERROR or SNMP_ERR_COMMITFAILED.  Values in StorageOld are the values before the
 * varbinds on the row were applied: the values in StorageTmp are the new values.
 */
int
update_dsx0ConfigTable_row(struct dsx0ConfigTable_data *StorageTmp, struct dsx0ConfigTable_data *StorageOld)
{
	/* XXX: provide code to update the row with the underlying device */
	dsx0ConfigTable_refresh = 1;
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int revert_dsx0ConfigTable_row(struct dsx0ConfigTable_data *StorageTmp, struct dsx0ConfigTable_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the undo operation (UNDO phase) on a row
 */
void
revert_dsx0ConfigTable_row(struct dsx0ConfigTable_data *StorageTmp, struct dsx0ConfigTable_data *StorageOld)
{
	/* XXX: provide code to revert the row with the underlying device */
	update_dsx0ConfigTable_row(StorageOld, NULL);
}

/**
 * @fn void refresh_dsx0ConfigTable_row(struct dsx0ConfigTable_data *StorageTmp, int force)
 * @param StorageTmp the data row to refresh.
 * @param force force refresh if non-zero.
 * @brief refresh the contents of the dsx0ConfigTable row.
 *
 * Normally the values retrieved from the operating system are cached.  However, if a row contains
 * temporal values, such as statistics counters, gauges, timestamps, or other transient columns, it
 * may be necessary to refresh the row on some other basis, but normally only once per request.
 */
struct dsx0ConfigTable_data *
refresh_dsx0ConfigTable_row(struct dsx0ConfigTable_data *StorageTmp, int force)
{
	if (!StorageTmp || (!force && StorageTmp->dsx0ConfigTable_request == sa_request))
		return (StorageTmp);
	/* XXX: update row; delete it and return NULL if the row has disappeared */
	StorageTmp->dsx0ConfigTable_request = sa_request;
	return (StorageTmp);
}

/**
 * @fn void refresh_dsx0ConfigTable(int force)
 * @param force force refresh if non-zero.
 * @brief refresh the scalar values of the dsx0ConfigTable.
 *
 * Normally the values retrieved from the operating system are cached.  When the agent receives a
 * SIGPOLL from an open STREAMS configuration or administrative driver Stream, the STREAMS subsystem
 * indicates to the agent that the cache has been invalidated and that it should reread scalars and
 * tables from the STREAMS subsystem.  This function is used when the agent starts for the first
 * time, or after a SIGPOLL has been received (and a row or column has been requested).
 */
void
refresh_dsx0ConfigTable(int force)
{
	if (!force && dsx0ConfigTable_refresh == 0)
		return;
	/* XXX: Here, update the table as required... */
	dsx0ConfigTable_refresh = 0;
}

/**
 * @fn u_char *var_dsx0ConfigTable(struct variable *vp, oid *name, size_t *length, int exact, size_t *var_len, WriteMethod **write_method)
 * @brief locate variables in dsx0ConfigTable.
 *
 * Handle this table separately from the scalar value case.  The workings of this are basically the
 * same as for var_ds0 above.
 */
u_char *
var_dsx0ConfigTable(struct variable *vp, oid * name, size_t *length, int exact, size_t *var_len, WriteMethod ** write_method)
{
	struct dsx0ConfigTable_data *StorageTmp = NULL;
	u_char *rval;

	DEBUGMSGTL(("ds0", "var_dsx0ConfigTable: Entering...  \n"));
	/* Make sure that the storage data does not need to be refreshed before checking the header. */
	refresh_dsx0ConfigTable(0);
	/* This assumes you have registered all your data properly with header_complex_add() somewhere before this. */
	while ((StorageTmp = header_complex(dsx0ConfigTableStorage, vp, name, length, exact, var_len, write_method)))
		if ((StorageTmp = refresh_dsx0ConfigTable_row(StorageTmp, 0)) || exact)
			break;
	*write_method = NULL;
	*var_len = 0;
	rval = NULL;
	/* This is where we do the value assignments for the mib results. */
	switch (vp->magic) {
	case (u_char) DSX0DS0CHANNELNUMBER:	/* ReadOnly */
		if (!StorageTmp)
			break;
		*var_len = sizeof(StorageTmp->dsx0Ds0ChannelNumber);
		rval = (u_char *) &StorageTmp->dsx0Ds0ChannelNumber;
		break;
	case (u_char) DSX0ROBBEDBITSIGNALLING:	/* ReadWrite */
		*write_method = write_dsx0RobbedBitSignalling;
		if (!StorageTmp)
			break;
		*var_len = sizeof(StorageTmp->dsx0RobbedBitSignalling);
		rval = (u_char *) &StorageTmp->dsx0RobbedBitSignalling;
		break;
	case (u_char) DSX0CIRCUITIDENTIFIER:	/* ReadWrite */
		*write_method = write_dsx0CircuitIdentifier;
		if (!StorageTmp)
			break;
		*var_len = StorageTmp->dsx0CircuitIdentifierLen;
		rval = (u_char *) StorageTmp->dsx0CircuitIdentifier;
		break;
	case (u_char) DSX0IDLECODE:	/* ReadWrite */
		*write_method = write_dsx0IdleCode;
		if (!StorageTmp)
			break;
		*var_len = sizeof(StorageTmp->dsx0IdleCode);
		rval = (u_char *) &StorageTmp->dsx0IdleCode;
		break;
	case (u_char) DSX0SEIZEDCODE:	/* ReadWrite */
		*write_method = write_dsx0SeizedCode;
		if (!StorageTmp)
			break;
		*var_len = sizeof(StorageTmp->dsx0SeizedCode);
		rval = (u_char *) &StorageTmp->dsx0SeizedCode;
		break;
	case (u_char) DSX0RECEIVEDCODE:	/* ReadOnly */
		if (!StorageTmp)
			break;
		*var_len = sizeof(StorageTmp->dsx0ReceivedCode);
		rval = (u_char *) &StorageTmp->dsx0ReceivedCode;
		break;
	case (u_char) DSX0TRANSMITCODESENABLE:	/* ReadWrite */
		*write_method = write_dsx0TransmitCodesEnable;
		if (!StorageTmp)
			break;
		*var_len = sizeof(StorageTmp->dsx0TransmitCodesEnable);
		rval = (u_char *) &StorageTmp->dsx0TransmitCodesEnable;
		break;
	case (u_char) DSX0DS0BUNDLEMAPPEDIFINDEX:	/* ReadOnly */
		if (!StorageTmp)
			break;
		*var_len = sizeof(StorageTmp->dsx0Ds0BundleMappedIfIndex);
		rval = (u_char *) &StorageTmp->dsx0Ds0BundleMappedIfIndex;
		break;
	default:
		ERROR_MSG("");
	}
	return (rval);
}

/**
 * @fn int check_dsx0ChanMappingTable_row(struct dsx0ChanMappingTable_data *StorageTmp, struct dsx0ChanMappingTable_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 *
 * This function is used both by tables that do and do not contain a RowStatus object.  It is used
 * to check, row-at-a-time, the varbinds belonging to the row.  Note that this function is not used
 * when rows are created or destroyed.  This function is called for the first varbind in a row at
 * the beginning of the ACTION phase.  The start of the ACTION pahse performs this consitency check
 * on the row before allowing the request to proceed to the COMMIT phase.  This function can return
 * SNMP_ERR_NOERR or a specific SNMP error value.  Values in StorageOld are the values before the
 * varbinds on the mib were applied; the values in StorageTmp are the new values.  The function is
 * permitted to change the values in StorageTmp to correct them; however, preference should be made
 * for setting values where were not in the varbinds.
 */
int
check_dsx0ChanMappingTable_row(struct dsx0ChanMappingTable_data *StorageTmp, struct dsx0ChanMappingTable_data *StorageOld)
{
	/* XXX: provide code to check the row for consistency */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int update_dsx0ChanMappingTable_row(struct dsx0ChanMappingTable_data *StorageTmp, struct dsx0ChanMappingTable_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the set operation (ACTION phase) on a row
 *
 * This function is used both by tables that do and do not contain a RowStatus object.  It is used
 * to update, row-at-a-time, the varbinds belonging to the row.  Note that this function is not used
 * when rows are created or destroyed.  This function is called for the first varbind in a row at
 * the beginning of the COMMIT phase.  The start of the ACTION phase performs a consistency check on
 * the row before allowing the request to proceed to the COMMIT phase.  The COMMIT phase then
 * arrives here with consistency already checked (see check_dsx0ChanMappingTable_row()).  This function can
 * return SNMP_ERR_NOERROR or SNMP_ERR_COMMITFAILED.  Values in StorageOld are the values before the
 * varbinds on the row were applied: the values in StorageTmp are the new values.
 */
int
update_dsx0ChanMappingTable_row(struct dsx0ChanMappingTable_data *StorageTmp, struct dsx0ChanMappingTable_data *StorageOld)
{
	/* XXX: provide code to update the row with the underlying device */
	dsx0ChanMappingTable_refresh = 1;
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int revert_dsx0ChanMappingTable_row(struct dsx0ChanMappingTable_data *StorageTmp, struct dsx0ChanMappingTable_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the undo operation (UNDO phase) on a row
 */
void
revert_dsx0ChanMappingTable_row(struct dsx0ChanMappingTable_data *StorageTmp, struct dsx0ChanMappingTable_data *StorageOld)
{
	/* XXX: provide code to revert the row with the underlying device */
	update_dsx0ChanMappingTable_row(StorageOld, NULL);
}

/**
 * @fn void refresh_dsx0ChanMappingTable_row(struct dsx0ChanMappingTable_data *StorageTmp, int force)
 * @param StorageTmp the data row to refresh.
 * @param force force refresh if non-zero.
 * @brief refresh the contents of the dsx0ChanMappingTable row.
 *
 * Normally the values retrieved from the operating system are cached.  However, if a row contains
 * temporal values, such as statistics counters, gauges, timestamps, or other transient columns, it
 * may be necessary to refresh the row on some other basis, but normally only once per request.
 */
struct dsx0ChanMappingTable_data *
refresh_dsx0ChanMappingTable_row(struct dsx0ChanMappingTable_data *StorageTmp, int force)
{
	if (!StorageTmp || (!force && StorageTmp->dsx0ChanMappingTable_request == sa_request))
		return (StorageTmp);
	/* XXX: update row; delete it and return NULL if the row has disappeared */
	StorageTmp->dsx0ChanMappingTable_request = sa_request;
	return (StorageTmp);
}

/**
 * @fn void refresh_dsx0ChanMappingTable(int force)
 * @param force force refresh if non-zero.
 * @brief refresh the scalar values of the dsx0ChanMappingTable.
 *
 * Normally the values retrieved from the operating system are cached.  When the agent receives a
 * SIGPOLL from an open STREAMS configuration or administrative driver Stream, the STREAMS subsystem
 * indicates to the agent that the cache has been invalidated and that it should reread scalars and
 * tables from the STREAMS subsystem.  This function is used when the agent starts for the first
 * time, or after a SIGPOLL has been received (and a row or column has been requested).
 */
void
refresh_dsx0ChanMappingTable(int force)
{
	if (!force && dsx0ChanMappingTable_refresh == 0)
		return;
	/* XXX: Here, update the table as required... */
	dsx0ChanMappingTable_refresh = 0;
}

/**
 * @fn u_char *var_dsx0ChanMappingTable(struct variable *vp, oid *name, size_t *length, int exact, size_t *var_len, WriteMethod **write_method)
 * @brief locate variables in dsx0ChanMappingTable.
 *
 * Handle this table separately from the scalar value case.  The workings of this are basically the
 * same as for var_ds0 above.
 */
u_char *
var_dsx0ChanMappingTable(struct variable *vp, oid * name, size_t *length, int exact, size_t *var_len, WriteMethod ** write_method)
{
	struct dsx0ChanMappingTable_data *StorageTmp = NULL;
	u_char *rval;

	DEBUGMSGTL(("ds0", "var_dsx0ChanMappingTable: Entering...  \n"));
	/* Make sure that the storage data does not need to be refreshed before checking the header. */
	refresh_dsx0ChanMappingTable(0);
	/* This assumes you have registered all your data properly with header_complex_add() somewhere before this. */
	while ((StorageTmp = header_complex(dsx0ChanMappingTableStorage, vp, name, length, exact, var_len, write_method)))
		if ((StorageTmp = refresh_dsx0ChanMappingTable_row(StorageTmp, 0)) || exact)
			break;
	*write_method = NULL;
	*var_len = 0;
	rval = NULL;
	/* This is where we do the value assignments for the mib results. */
	switch (vp->magic) {
	case (u_char) DSX0CHANMAPPEDIFINDEX:	/* ReadOnly */
		if (!StorageTmp)
			break;
		*var_len = sizeof(StorageTmp->dsx0ChanMappedIfIndex);
		rval = (u_char *) &StorageTmp->dsx0ChanMappedIfIndex;
		break;
	default:
		ERROR_MSG("");
	}
	return (rval);
}

/**
 * @fn int write_dsx0RobbedBitSignalling(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid *name, size_t name_len)
 * @param action the stage of the SET operation.
 * @param var_val pointer to the varbind value.
 * @param var_val_type the ASN type.
 * @param var_val_len the length of the varbind value.
 * @param statP static pointer.
 * @param name the varbind OID.
 * @param name_len number of elements in OID.
 * @brief Table row and column write routine.
 */
int
write_dsx0RobbedBitSignalling(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	struct dsx0ConfigTable_data *StorageTmp = NULL, *StorageOld = NULL;
	size_t newlen = name_len - 11;
	long set_value = *((long *) var_val);
	int ret = SNMP_ERR_NOERROR;

	DEBUGMSGTL(("ds0", "write_dsx0RobbedBitSignalling entering action=%d...  \n", action));
	if (StorageTmp == NULL)
		return SNMP_ERR_NOSUCHNAME;
	StorageTmp = header_complex(dsx0ConfigTableStorage, NULL, &name[11], &newlen, 1, NULL, NULL);
	if (StorageTmp == NULL)
		return SNMP_ERR_NOSUCHNAME;	/* remove if you support creation here */
	switch (action) {
	case RESERVE1:
		if (var_val_type != ASN_INTEGER) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0RobbedBitSignalling not ASN_INTEGER\n");
			return SNMP_ERR_WRONGTYPE;
		}
		if (var_val_len > sizeof(int32_t)) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0RobbedBitSignalling: bad length\n");
			return SNMP_ERR_WRONGLENGTH;
		}
		switch (set_value) {
		case TV_TRUE:
		case TV_FALSE:
			break;
		default:
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0RobbedBitSignalling: bad value\n");
			return SNMP_ERR_WRONGVALUE;
		}
		/* one allocation for the whole row */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) == NULL)
			if (StorageTmp->dsx0ConfigTable_rsvs == 0)
				if ((StorageOld = StorageTmp->dsx0ConfigTable_old = dsx0ConfigTable_duplicate(StorageTmp)) == NULL)
					return SNMP_ERR_RESOURCEUNAVAILABLE;
		if (StorageOld != NULL)
			StorageTmp->dsx0ConfigTable_rsvs++;
		StorageTmp->dsx0RobbedBitSignalling = set_value;
		/* XXX: insert code to consistency check this particular varbind, if necessary (so error codes are applied to varbinds) */
		break;
	case RESERVE2:		/* memory reseveration, final preparation... */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) != NULL) {
			/* one consistency check for the whole row */
			if (StorageTmp->dsx0ConfigTable_tsts == 0)
				if ((ret = check_dsx0ConfigTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->dsx0ConfigTable_tsts++;
		}
		break;
	case ACTION:		/* The variable has been stored in StorageTmp->dsx0RobbedBitSignalling for you to use, and you have just been asked to do something with it.  Note that anything done
				   here must be reversable in the UNDO case */
		/* XXX: insert code to set this particular varbind, if necessary */
		/* one set action for the whole row */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) != NULL) {
			/* XXX: insert code to set this particular varbind, if necessary */
			if (StorageTmp->dsx0ConfigTable_sets == 0)
				if ((ret = update_dsx0ConfigTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->dsx0ConfigTable_sets++;
		}
		break;
	case COMMIT:		/* Things are working well, so it's now safe to make the change permanently.  Make sure that anything done here can't fail! */
		/* one commit for the whole mib */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) != NULL) {
			dsx0ConfigTable_destroy(&StorageTmp->dsx0ConfigTable_old);
			StorageTmp->dsx0ConfigTable_rsvs = 0;
			StorageTmp->dsx0ConfigTable_tsts = 0;
			StorageTmp->dsx0ConfigTable_sets = 0;
		}
		break;
	case UNDO:		/* Back out any changes made in the ACTION case */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) == NULL)
			break;
		/* XXX: insert code to undo any action performed on this particular varbind */
		if (--StorageTmp->dsx0ConfigTable_sets == 0)
			revert_dsx0ConfigTable_row(StorageTmp, StorageOld);
		/* fall through */
	case FREE:		/* Release any resources that have been allocated */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) == NULL)
			break;
		StorageTmp->dsx0RobbedBitSignalling = StorageOld->dsx0RobbedBitSignalling;
		if (--StorageTmp->dsx0ConfigTable_rsvs == 0)
			dsx0ConfigTable_destroy(&StorageTmp->dsx0ConfigTable_old);
		break;
	}
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int write_dsx0CircuitIdentifier(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid *name, size_t name_len)
 * @param action the stage of the SET operation.
 * @param var_val pointer to the varbind value.
 * @param var_val_type the ASN type.
 * @param var_val_len the length of the varbind value.
 * @param statP static pointer.
 * @param name the varbind OID.
 * @param name_len number of elements in OID.
 * @brief Table row and column write routine.
 */
int
write_dsx0CircuitIdentifier(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	struct dsx0ConfigTable_data *StorageTmp = NULL, *StorageOld = NULL;
	size_t newlen = name_len - 11;
	uint8_t *string = NULL;
	int ret = SNMP_ERR_NOERROR;

	DEBUGMSGTL(("ds0", "write_dsx0CircuitIdentifier entering action=%d...  \n", action));
	if (StorageTmp == NULL)
		return SNMP_ERR_NOSUCHNAME;
	StorageTmp = header_complex(dsx0ConfigTableStorage, NULL, &name[11], &newlen, 1, NULL, NULL);
	if (StorageTmp == NULL)
		return SNMP_ERR_NOSUCHNAME;	/* remove if you support creation here */
	switch (action) {
	case RESERVE1:
		if (var_val_type != ASN_OCTET_STR) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0CircuitIdentifier not ASN_OCTET_STR\n");
			return SNMP_ERR_WRONGTYPE;
		}
		/* Note: ranges 0..255 */
		if (var_val_len > SPRINT_MAX_LEN || ((0 > var_val_len || var_val_len > 255))) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0CircuitIdentifier: bad length\n");
			return SNMP_ERR_WRONGLENGTH;
		}
		/* one allocation for the whole row */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) == NULL)
			if (StorageTmp->dsx0ConfigTable_rsvs == 0)
				if ((StorageOld = StorageTmp->dsx0ConfigTable_old = dsx0ConfigTable_duplicate(StorageTmp)) == NULL)
					return SNMP_ERR_RESOURCEUNAVAILABLE;
		if (StorageOld != NULL)
			StorageTmp->dsx0ConfigTable_rsvs++;
		if ((string = malloc(var_val_len + 1)) == NULL)
			return SNMP_ERR_RESOURCEUNAVAILABLE;
		memcpy((void *) string, (void *) var_val, var_val_len);
		string[var_val_len] = 0;
		SNMP_FREE(StorageTmp->dsx0CircuitIdentifier);
		StorageTmp->dsx0CircuitIdentifier = string;
		StorageTmp->dsx0CircuitIdentifierLen = var_val_len;
		/* XXX: insert code to consistency check this particular varbind, if necessary (so error codes are applied to varbinds) */
		break;
	case RESERVE2:		/* memory reseveration, final preparation... */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) != NULL) {
			/* one consistency check for the whole row */
			if (StorageTmp->dsx0ConfigTable_tsts == 0)
				if ((ret = check_dsx0ConfigTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->dsx0ConfigTable_tsts++;
		}
		break;
	case ACTION:		/* The variable has been stored in StorageTmp->dsx0CircuitIdentifier for you to use, and you have just been asked to do something with it.  Note that anything done
				   here must be reversable in the UNDO case */
		/* XXX: insert code to set this particular varbind, if necessary */
		/* one set action for the whole row */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) != NULL) {
			/* XXX: insert code to set this particular varbind, if necessary */
			if (StorageTmp->dsx0ConfigTable_sets == 0)
				if ((ret = update_dsx0ConfigTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->dsx0ConfigTable_sets++;
		}
		break;
	case COMMIT:		/* Things are working well, so it's now safe to make the change permanently.  Make sure that anything done here can't fail! */
		/* one commit for the whole mib */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) != NULL) {
			dsx0ConfigTable_destroy(&StorageTmp->dsx0ConfigTable_old);
			StorageTmp->dsx0ConfigTable_rsvs = 0;
			StorageTmp->dsx0ConfigTable_tsts = 0;
			StorageTmp->dsx0ConfigTable_sets = 0;
		}
		break;
	case UNDO:		/* Back out any changes made in the ACTION case */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) == NULL)
			break;
		/* XXX: insert code to undo any action performed on this particular varbind */
		if (--StorageTmp->dsx0ConfigTable_sets == 0)
			revert_dsx0ConfigTable_row(StorageTmp, StorageOld);
		/* fall through */
	case FREE:		/* Release any resources that have been allocated */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) == NULL)
			break;
		if (StorageOld->dsx0CircuitIdentifier != NULL) {
			SNMP_FREE(StorageTmp->dsx0CircuitIdentifier);
			StorageTmp->dsx0CircuitIdentifier = StorageOld->dsx0CircuitIdentifier;
			StorageTmp->dsx0CircuitIdentifierLen = StorageOld->dsx0CircuitIdentifierLen;
			StorageOld->dsx0CircuitIdentifier = NULL;
			StorageOld->dsx0CircuitIdentifierLen = 0;
		}
		if (--StorageTmp->dsx0ConfigTable_rsvs == 0)
			dsx0ConfigTable_destroy(&StorageTmp->dsx0ConfigTable_old);
		break;
	}
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int write_dsx0IdleCode(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid *name, size_t name_len)
 * @param action the stage of the SET operation.
 * @param var_val pointer to the varbind value.
 * @param var_val_type the ASN type.
 * @param var_val_len the length of the varbind value.
 * @param statP static pointer.
 * @param name the varbind OID.
 * @param name_len number of elements in OID.
 * @brief Table row and column write routine.
 */
int
write_dsx0IdleCode(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	struct dsx0ConfigTable_data *StorageTmp = NULL, *StorageOld = NULL;
	size_t newlen = name_len - 11;
	long set_value = *((long *) var_val);
	int ret = SNMP_ERR_NOERROR;

	DEBUGMSGTL(("ds0", "write_dsx0IdleCode entering action=%d...  \n", action));
	if (StorageTmp == NULL)
		return SNMP_ERR_NOSUCHNAME;
	StorageTmp = header_complex(dsx0ConfigTableStorage, NULL, &name[11], &newlen, 1, NULL, NULL);
	if (StorageTmp == NULL)
		return SNMP_ERR_NOSUCHNAME;	/* remove if you support creation here */
	switch (action) {
	case RESERVE1:
		if (var_val_type != ASN_INTEGER) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0IdleCode not ASN_INTEGER\n");
			return SNMP_ERR_WRONGTYPE;
		}
		if (var_val_len > sizeof(int32_t)) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0IdleCode: bad length\n");
			return SNMP_ERR_WRONGLENGTH;
		}
		/* Note: ranges 0..15 */
		if ((0 > set_value || set_value > 15)) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0IdleCode: bad value\n");
			return SNMP_ERR_WRONGVALUE;
		}
		/* one allocation for the whole row */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) == NULL)
			if (StorageTmp->dsx0ConfigTable_rsvs == 0)
				if ((StorageOld = StorageTmp->dsx0ConfigTable_old = dsx0ConfigTable_duplicate(StorageTmp)) == NULL)
					return SNMP_ERR_RESOURCEUNAVAILABLE;
		if (StorageOld != NULL)
			StorageTmp->dsx0ConfigTable_rsvs++;
		StorageTmp->dsx0IdleCode = set_value;
		/* XXX: insert code to consistency check this particular varbind, if necessary (so error codes are applied to varbinds) */
		break;
	case RESERVE2:		/* memory reseveration, final preparation... */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) != NULL) {
			/* one consistency check for the whole row */
			if (StorageTmp->dsx0ConfigTable_tsts == 0)
				if ((ret = check_dsx0ConfigTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->dsx0ConfigTable_tsts++;
		}
		break;
	case ACTION:		/* The variable has been stored in StorageTmp->dsx0IdleCode for you to use, and you have just been asked to do something with it.  Note that anything done here must be 
				   reversable in the UNDO case */
		/* XXX: insert code to set this particular varbind, if necessary */
		/* one set action for the whole row */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) != NULL) {
			/* XXX: insert code to set this particular varbind, if necessary */
			if (StorageTmp->dsx0ConfigTable_sets == 0)
				if ((ret = update_dsx0ConfigTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->dsx0ConfigTable_sets++;
		}
		break;
	case COMMIT:		/* Things are working well, so it's now safe to make the change permanently.  Make sure that anything done here can't fail! */
		/* one commit for the whole mib */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) != NULL) {
			dsx0ConfigTable_destroy(&StorageTmp->dsx0ConfigTable_old);
			StorageTmp->dsx0ConfigTable_rsvs = 0;
			StorageTmp->dsx0ConfigTable_tsts = 0;
			StorageTmp->dsx0ConfigTable_sets = 0;
		}
		break;
	case UNDO:		/* Back out any changes made in the ACTION case */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) == NULL)
			break;
		/* XXX: insert code to undo any action performed on this particular varbind */
		if (--StorageTmp->dsx0ConfigTable_sets == 0)
			revert_dsx0ConfigTable_row(StorageTmp, StorageOld);
		/* fall through */
	case FREE:		/* Release any resources that have been allocated */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) == NULL)
			break;
		StorageTmp->dsx0IdleCode = StorageOld->dsx0IdleCode;
		if (--StorageTmp->dsx0ConfigTable_rsvs == 0)
			dsx0ConfigTable_destroy(&StorageTmp->dsx0ConfigTable_old);
		break;
	}
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int write_dsx0SeizedCode(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid *name, size_t name_len)
 * @param action the stage of the SET operation.
 * @param var_val pointer to the varbind value.
 * @param var_val_type the ASN type.
 * @param var_val_len the length of the varbind value.
 * @param statP static pointer.
 * @param name the varbind OID.
 * @param name_len number of elements in OID.
 * @brief Table row and column write routine.
 */
int
write_dsx0SeizedCode(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	struct dsx0ConfigTable_data *StorageTmp = NULL, *StorageOld = NULL;
	size_t newlen = name_len - 11;
	long set_value = *((long *) var_val);
	int ret = SNMP_ERR_NOERROR;

	DEBUGMSGTL(("ds0", "write_dsx0SeizedCode entering action=%d...  \n", action));
	if (StorageTmp == NULL)
		return SNMP_ERR_NOSUCHNAME;
	StorageTmp = header_complex(dsx0ConfigTableStorage, NULL, &name[11], &newlen, 1, NULL, NULL);
	if (StorageTmp == NULL)
		return SNMP_ERR_NOSUCHNAME;	/* remove if you support creation here */
	switch (action) {
	case RESERVE1:
		if (var_val_type != ASN_INTEGER) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0SeizedCode not ASN_INTEGER\n");
			return SNMP_ERR_WRONGTYPE;
		}
		if (var_val_len > sizeof(int32_t)) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0SeizedCode: bad length\n");
			return SNMP_ERR_WRONGLENGTH;
		}
		/* Note: ranges 0..15 */
		if ((0 > set_value || set_value > 15)) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0SeizedCode: bad value\n");
			return SNMP_ERR_WRONGVALUE;
		}
		/* one allocation for the whole row */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) == NULL)
			if (StorageTmp->dsx0ConfigTable_rsvs == 0)
				if ((StorageOld = StorageTmp->dsx0ConfigTable_old = dsx0ConfigTable_duplicate(StorageTmp)) == NULL)
					return SNMP_ERR_RESOURCEUNAVAILABLE;
		if (StorageOld != NULL)
			StorageTmp->dsx0ConfigTable_rsvs++;
		StorageTmp->dsx0SeizedCode = set_value;
		/* XXX: insert code to consistency check this particular varbind, if necessary (so error codes are applied to varbinds) */
		break;
	case RESERVE2:		/* memory reseveration, final preparation... */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) != NULL) {
			/* one consistency check for the whole row */
			if (StorageTmp->dsx0ConfigTable_tsts == 0)
				if ((ret = check_dsx0ConfigTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->dsx0ConfigTable_tsts++;
		}
		break;
	case ACTION:		/* The variable has been stored in StorageTmp->dsx0SeizedCode for you to use, and you have just been asked to do something with it.  Note that anything done here must
				   be reversable in the UNDO case */
		/* XXX: insert code to set this particular varbind, if necessary */
		/* one set action for the whole row */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) != NULL) {
			/* XXX: insert code to set this particular varbind, if necessary */
			if (StorageTmp->dsx0ConfigTable_sets == 0)
				if ((ret = update_dsx0ConfigTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->dsx0ConfigTable_sets++;
		}
		break;
	case COMMIT:		/* Things are working well, so it's now safe to make the change permanently.  Make sure that anything done here can't fail! */
		/* one commit for the whole mib */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) != NULL) {
			dsx0ConfigTable_destroy(&StorageTmp->dsx0ConfigTable_old);
			StorageTmp->dsx0ConfigTable_rsvs = 0;
			StorageTmp->dsx0ConfigTable_tsts = 0;
			StorageTmp->dsx0ConfigTable_sets = 0;
		}
		break;
	case UNDO:		/* Back out any changes made in the ACTION case */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) == NULL)
			break;
		/* XXX: insert code to undo any action performed on this particular varbind */
		if (--StorageTmp->dsx0ConfigTable_sets == 0)
			revert_dsx0ConfigTable_row(StorageTmp, StorageOld);
		/* fall through */
	case FREE:		/* Release any resources that have been allocated */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) == NULL)
			break;
		StorageTmp->dsx0SeizedCode = StorageOld->dsx0SeizedCode;
		if (--StorageTmp->dsx0ConfigTable_rsvs == 0)
			dsx0ConfigTable_destroy(&StorageTmp->dsx0ConfigTable_old);
		break;
	}
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int write_dsx0TransmitCodesEnable(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid *name, size_t name_len)
 * @param action the stage of the SET operation.
 * @param var_val pointer to the varbind value.
 * @param var_val_type the ASN type.
 * @param var_val_len the length of the varbind value.
 * @param statP static pointer.
 * @param name the varbind OID.
 * @param name_len number of elements in OID.
 * @brief Table row and column write routine.
 */
int
write_dsx0TransmitCodesEnable(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	struct dsx0ConfigTable_data *StorageTmp = NULL, *StorageOld = NULL;
	size_t newlen = name_len - 11;
	long set_value = *((long *) var_val);
	int ret = SNMP_ERR_NOERROR;

	DEBUGMSGTL(("ds0", "write_dsx0TransmitCodesEnable entering action=%d...  \n", action));
	if (StorageTmp == NULL)
		return SNMP_ERR_NOSUCHNAME;
	StorageTmp = header_complex(dsx0ConfigTableStorage, NULL, &name[11], &newlen, 1, NULL, NULL);
	if (StorageTmp == NULL)
		return SNMP_ERR_NOSUCHNAME;	/* remove if you support creation here */
	switch (action) {
	case RESERVE1:
		if (var_val_type != ASN_INTEGER) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0TransmitCodesEnable not ASN_INTEGER\n");
			return SNMP_ERR_WRONGTYPE;
		}
		if (var_val_len > sizeof(int32_t)) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0TransmitCodesEnable: bad length\n");
			return SNMP_ERR_WRONGLENGTH;
		}
		switch (set_value) {
		case TV_TRUE:
		case TV_FALSE:
			break;
		default:
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0TransmitCodesEnable: bad value\n");
			return SNMP_ERR_WRONGVALUE;
		}
		/* one allocation for the whole row */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) == NULL)
			if (StorageTmp->dsx0ConfigTable_rsvs == 0)
				if ((StorageOld = StorageTmp->dsx0ConfigTable_old = dsx0ConfigTable_duplicate(StorageTmp)) == NULL)
					return SNMP_ERR_RESOURCEUNAVAILABLE;
		if (StorageOld != NULL)
			StorageTmp->dsx0ConfigTable_rsvs++;
		StorageTmp->dsx0TransmitCodesEnable = set_value;
		/* XXX: insert code to consistency check this particular varbind, if necessary (so error codes are applied to varbinds) */
		break;
	case RESERVE2:		/* memory reseveration, final preparation... */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) != NULL) {
			/* one consistency check for the whole row */
			if (StorageTmp->dsx0ConfigTable_tsts == 0)
				if ((ret = check_dsx0ConfigTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->dsx0ConfigTable_tsts++;
		}
		break;
	case ACTION:		/* The variable has been stored in StorageTmp->dsx0TransmitCodesEnable for you to use, and you have just been asked to do something with it.  Note that anything done
				   here must be reversable in the UNDO case */
		/* XXX: insert code to set this particular varbind, if necessary */
		/* one set action for the whole row */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) != NULL) {
			/* XXX: insert code to set this particular varbind, if necessary */
			if (StorageTmp->dsx0ConfigTable_sets == 0)
				if ((ret = update_dsx0ConfigTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->dsx0ConfigTable_sets++;
		}
		break;
	case COMMIT:		/* Things are working well, so it's now safe to make the change permanently.  Make sure that anything done here can't fail! */
		/* one commit for the whole mib */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) != NULL) {
			dsx0ConfigTable_destroy(&StorageTmp->dsx0ConfigTable_old);
			StorageTmp->dsx0ConfigTable_rsvs = 0;
			StorageTmp->dsx0ConfigTable_tsts = 0;
			StorageTmp->dsx0ConfigTable_sets = 0;
		}
		break;
	case UNDO:		/* Back out any changes made in the ACTION case */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) == NULL)
			break;
		/* XXX: insert code to undo any action performed on this particular varbind */
		if (--StorageTmp->dsx0ConfigTable_sets == 0)
			revert_dsx0ConfigTable_row(StorageTmp, StorageOld);
		/* fall through */
	case FREE:		/* Release any resources that have been allocated */
		if ((StorageOld = StorageTmp->dsx0ConfigTable_old) == NULL)
			break;
		StorageTmp->dsx0TransmitCodesEnable = StorageOld->dsx0TransmitCodesEnable;
		if (--StorageTmp->dsx0ConfigTable_rsvs == 0)
			dsx0ConfigTable_destroy(&StorageTmp->dsx0ConfigTable_old);
		break;
	}
	return SNMP_ERR_NOERROR;
}

/**
 * @fn void ds0_loop_handler(int dummy)
 * @param sig signal number
 * @brief handle event loop interation.
 *
 * This function is registered so that, when operating as a module, snmpd will call it one per event
 * loop interation.  This function is called before the next requst is processed and after the
 * previous request is processed.  Two things are done here:  1) The file descriptor that is used to
 * synchronize the agent with (pseudo-)device drivers is closed.  (Another approach, instead of
 * closing each time, would be to restart a timer each time that a request is made (loop is
 * performed) and if it expires, close the file descriptor).  2) The request number is incremented.
 * Although a request is not generated for each loop of the snmp event loop, it is true that a new
 * request cannot be generated without performing a loop.  Therefore, the sa_request is not the
 * request number but it is a temporally unique identifier for a request.
 */
void
ds0_loop_handler(int sig)
{
	DEBUGMSGTL(("ds0", "ds0_loop_handler: executing loop handler...  "));
	/* close files after each request */
	if (sa_fclose) {
		if (my_fd >= 0) {
			close(my_fd);
			my_fd = -1;
		}
	}
#if defined MASTER
	/* prepare for next request */
	sa_request++;
#endif				/* defined MASTER */
	if (external_signal_scheduled[sig] == 0)
		external_signal_scheduled[sig]--;
	if (ds0old_signal_handler != NULL)
		(*ds0old_signal_handler) (sig);
	DEBUGMSGTL(("ds0", "done.\n"));
}

/**
 * @fn void ds0_fd_handler(int fd, void *dummy)
 * @param fd file descriptor to read.
 * @param dummy client data passed to registration function (always NULL).
 * @brief handle read event on file descriptor.
 *
 * This read file descriptor handler is normally used for (pseudo-)device drivers that generate
 * statistical collection interval events, alarm events, or other operational measurement events, by
 * placing a message on the read queue of the "event handling" Stream.  Normally this routine
 * would adjust counts in some table or scalars, generate SNMP traps representing on-occurence
 * events, first and interval events, and alarm indications.
 */
void
ds0_fd_handler(int fd, void *dummy)
{
	DEBUGMSGTL(("ds0", "ds0_fd_handler: executing fd handler...  "));
	/* XXX: place actions to handle my_fd here... */
	DEBUGMSGTL(("ds0", "done.\n"));
	return;
}
