/*****************************************************************************

 @(#) $RCSfile: ds0Bundle.c,v $ $Name:  $($Revision: 1.1.2.2 $) $Date: 2010-11-28 14:22:11 $

 -----------------------------------------------------------------------------

 Copyright (c) 2008-2012  Monavacon Limited <http://www.monavacon.com/>
 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software: you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation, version 3 of the license.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 -----------------------------------------------------------------------------

 Last Modified $Date: 2010-11-28 14:22:11 $ by $Author: brian $

 -----------------------------------------------------------------------------

 $Log: ds0Bundle.c,v $
 Revision 1.1.2.2  2010-11-28 14:22:11  brian
 - remove #ident, protect _XOPEN_SOURCE

 Revision 1.1.2.1  2009-06-21 11:42:31  brian
 - added files to new distro

 Revision 0.9.2.3  2009-02-18 20:18:58  brian
 - updated agents

 Revision 0.9.2.2  2009-01-19 13:31:54  brian
 - updating standalone agents

 Revision 0.9.2.1  2009-01-16 20:39:30  brian
 - added standard mibs

 *****************************************************************************/

static char const ident[] = "$RCSfile: ds0Bundle.c,v $ $Name:  $($Revision: 1.1.2.2 $) $Date: 2010-11-28 14:22:11 $";

/* This file was generated by mib2c and is intended for use as
   a mib module for the ucd-snmp snmpd agent. */
#include <ucd-snmp/ucd-snmp-config.h>
#include <ucd-snmp/ucd-snmp-includes.h>
#include <ucd-snmp/ucd-snmp-agent-includes.h>
#include <ucd-snmp/agent_trap.h>
#include <ucd-snmp/callback.h>
#include <ucd-snmp/snmp-tc.h>
#include <ucd-snmp/default_store.h>
#include <ucd-snmp/snmp_alarm.h>
/* The following header files are mangled in most recent net-snmp releases so
 * the versions from UCD-SNMP 4.2.5 are included here.  */
#if defined HAVE_LIBNETSNMP
#else				/* defined HAVE_LIBNETSNMP */
#endif				/* defined HAVE_LIBNETSNMP */
/* These are messed up on both. */
#include "ds_agent.h"
#ifdef HAVE_UCD_SNMP_UTIL_FUNCS_H
#include <ucd-snmp/util_funcs.h>
/* Many recent net-snmp UCD compatible headers do not declare header_generic. */
int header_generic(struct variable *, oid *, size_t *, int, size_t *, WriteMethod **);
#else				/* HAVE_UCD_SNMP_UTIL_FUNCS_H */
#include "util_funcs.h"
#endif				/* HAVE_UCD_SNMP_UTIL_FUNCS_H */
#ifdef HAVE_UCD_SNMP_HEADER_COMPLEX_H
#include <ucd-snmp/header_complex.h>
#else				/* HAVE_UCD_SNMP_HEADER_COMPLEX_H */
#include "header_complex.h"
#endif				/* HAVE_UCD_SNMP_HEADER_COMPLEX_H */
/* This one is the other way around: it is just fine for net-snmp, but
 * ucd-snmp does not provide the header file at all.  */
#ifdef HAVE_UCD_SNMP_MIB_MODULES_H
#include <ucd-snmp/mib_modules.h>
#else				/* HAVE_UCD_SNMP_MIB_MODULES_H */
#ifdef HAVE_NET_SNMP_AGENT_MIB_MODULES_H
#include <net-snmp/agent/mib_modules.h>
#else				/* HAVE_NET_SNMP_AGENT_MIB_MODULES_H */
#include "mib_modules.h"
#endif				/* HAVE_NET_SNMP_AGENT_MIB_MODULES_H */
#endif				/* HAVE_UCD_SNMP_MIB_MODULES_H */
#include <stdint.h>
#include <signal.h>
#include <sys/stat.h>		/* for struct stat, fstat() */
#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>
#include <pwd.h>		/* for getpwuid() getpwnam() */
#include <grp.h>		/* for getgrgid() getgrnam() */
#include <libgen.h>		/* for basename() */
#include <fcntl.h>		/* for O_CREAT */
#include <sys/sysctl.h>		/* for sysctl */
#include <errno.h>
#include <string.h>
#ifdef _GNU_SOURCE
#include <getopt.h>
#endif
#include "ds0Bundle.h"
#undef MASTER
#define MY_FACILITY(__pri)	(LOG_DAEMON|(__pri))
#if defined MODULE
#if defined MASTER
const char sa_program[] = "ds0Bundle";
int sa_fclose = 1;			/* default close files between requests */
int sa_changed = 1;			/* indication to reread MIB configuration */
int sa_stats_refresh = 1;		/* indications that statistics, the mib or its tables need to be refreshed */
int sa_request = 1;			/* request number for per-request actions */
int sa_dump = 0;			/* default packet dump */
int sa_debug = 0;			/* default no debug */
#endif				/* defined MASTER */
#endif				/* defined MODULE */
static int my_fd = -1;			/* file descriptor for this MIB's use */
static int my_readfd = -1;		/* file descriptor for autonomnous events */
volatile int ds0Bundle_refresh = 1;
volatile int dsx0BondingTable_refresh = 1;
volatile int dsx0BundleTable_refresh = 1;

/*
 * ds0Bundle_variables_oid: object identifier for ds0Bundle
 * This is the top level oid that we want to register under.  This is essentially a prefix, with the
 * suffix appearing in the variable below.
 */
oid ds0Bundle_variables_oid[8] = { 1, 3, 6, 1, 2, 1, 10, 82 };
oid dsx0BondingTable_variables_oid[10] = { 1, 3, 6, 1, 2, 1, 10, 82, 1, 1 };
oid dsx0BundleTable_variables_oid[10] = { 1, 3, 6, 1, 2, 1, 10, 82, 3, 1 };

/*
 * Oids for use in notifications defined in this MIB.
 */

/*
 * Oids accessible only for notify defined in this MIB.
 */

/*
 * Other oids defined in this MIB.
 */
oid ds0BondingGroup_oid[11] = { 1, 3, 6, 1, 2, 1, 10, 82, 4, 1, 1 };
oid ds0BundleConfigGroup_oid[11] = { 1, 3, 6, 1, 2, 1, 10, 82, 4, 1, 2 };
oid ds0BundleCompliance_oid[11] = { 1, 3, 6, 1, 2, 1, 10, 82, 4, 2, 1 };
static oid zeroDotZero_oid[2] = { 0, 0 };
static oid snmpTrapOID_oid[11] = { 1, 3, 6, 1, 6, 3, 1, 1, 4, 1, 0 };

/*
 * variable4 ds0Bundle_variables: tree for ds0Bundle
 * This variable defines function callbacks and type return information for the ds0Bundle mib section
 */
struct variable4 ds0Bundle_variables[] = {
	/* magic number, variable type, ro/rw, callback fn, L, oidsuffix */
#define   DSX0BONDMODE          2
	{(u_char) DSX0BONDMODE, ASN_INTEGER, RWRITE, var_dsx0BondingTable, 3, {1, 1, 1}},
#define   DSX0BONDSTATUS        3
	{(u_char) DSX0BONDSTATUS, ASN_INTEGER, RONLY, var_dsx0BondingTable, 3, {1, 1, 2}},
#define   DSX0BONDROWSTATUS     4
	{(u_char) DSX0BONDROWSTATUS, ASN_INTEGER, RWRITE, var_dsx0BondingTable, 3, {1, 1, 3}},
#define   DSX0BUNDLENEXTINDEX   5
	{(u_char) DSX0BUNDLENEXTINDEX, ASN_INTEGER, RWRITE, var_ds0Bundle, 1, {2}},
#define   DSX0BUNDLEIFINDEX     6
	{(u_char) DSX0BUNDLEIFINDEX, ASN_INTEGER, RONLY, var_dsx0BundleTable, 3, {3, 1, 2}},
#define   DSX0BUNDLECIRCUITIDENTIFIER  7
	{(u_char) DSX0BUNDLECIRCUITIDENTIFIER, ASN_OCTET_STR, RWRITE, var_dsx0BundleTable, 3, {3, 1, 3}},
#define   DSX0BUNDLEROWSTATUS   8
	{(u_char) DSX0BUNDLEROWSTATUS, ASN_INTEGER, RWRITE, var_dsx0BundleTable, 3, {3, 1, 4}},
};

/* (L = length of the oidsuffix) */
struct ds0Bundle_data *ds0BundleStorage = NULL;

/* global storage of our data, saved in and configured by header_complex() */
struct header_complex_index *dsx0BondingTableStorage = NULL;
struct header_complex_index *dsx0BundleTableStorage = NULL;

void (*ds0Bundleold_signal_handler) (int) = NULL;	/* save old signal handler just in case */
void ds0Bundle_loop_handler(int);
void ds0Bundle_fd_handler(int, void *);

/**
 * @fn void init_ds0Bundle(void)
 * @brief ds0Bundle initialization routine.
 *
 * This is called when the agent starts up.  At a minimum, registration of the MIB variables
 * structure (ds0Bundle_variables) should take place here.  By default the function also
 * registers the configuration handler and configuration store callbacks.
 *
 * Additional registrations that may be considered here are calls to regsiter_readfd(),
 * register_writefd() and register_exceptfd() for hooking into the snmpd event loop, but only when
 * used as a loadable module.  By default this function establishes a single file descriptor to
 * read, or upon which to handle exceptions.  Note that the snmpd only supports a maximum of 32
 * extneral file descriptors, so these should be used sparingly.
 *
 * When running as a loadable module, it is also necessary to hook into the snmpd event loop so that
 * the current request number can be deteremined.  This is accomplished by using a trick of the
 * external_signal_scheduled and external_signal_handler mechanism which is called on each event
 * loop when external_signal_scheduled is non-zero.  This is used to increment the sa_request value
 * on each snmpd event loop interation so that calls to MIB tree functions can determine whether
 * they belong to a fresh request or not (primarily for cacheing and possibly to clean up non-polled
 * file descriptors).
 */
void
init_ds0Bundle(void)
{
	(void) my_fd;
	(void) zeroDotZero_oid;
	(void) snmpTrapOID_oid;
	DEBUGMSGTL(("ds0Bundle", "init_ds0Bundle: initializing...  "));
	/* register ourselves with the agent to handle our mib tree */
	REGISTER_MIB("ds0Bundle", ds0Bundle_variables, variable4, ds0Bundle_variables_oid);
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_SHUTDOWN, term_ds0Bundle, NULL);
	/* register our config handler(s) to deal with registrations */
	snmpd_register_config_handler("ds0Bundle", parse_ds0Bundle, NULL, "HELP STRING");
	snmpd_register_config_handler("dsx0BondingTable", parse_dsx0BondingTable, NULL, "HELP STRING");
	snmpd_register_config_handler("dsx0BundleTable", parse_dsx0BundleTable, NULL, "HELP STRING");

	/* we need to be called back later to store our data */
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_STORE_DATA, store_ds0Bundle, NULL);
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_STORE_DATA, store_dsx0BondingTable, NULL);
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_STORE_DATA, store_dsx0BundleTable, NULL);

	/* place any other initialization junk you need here */
	if (my_readfd >= 0) {
		register_readfd(my_readfd, ds0Bundle_fd_handler, (void *) 0);
		register_exceptfd(my_readfd, ds0Bundle_fd_handler, (void *) 1);
	}
	ds0Bundleold_signal_handler = external_signal_handler[SIGCHLD];
	external_signal_handler[SIGCHLD] = &ds0Bundle_loop_handler;
	external_signal_scheduled[SIGCHLD] = 1;
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
}

/**
 * @fn void deinit_ds0Bundle(void)
 * @brief deinitialization routine.
 *
 * This is called before the agent is unloaded.  At a minimum, deregistration of the MIB variables
 * structure (ds0Bundle_variables) should take place here.  By default, the function also
 * deregisters the the configuration file handlers for the MIB variables and table rows.
 *
 * Additional deregistrations that may be required here are calls to unregister_readfd(),
 * unregister_writefd() and unregsiter_exceptfd() for unhooking from the snmpd event loop, but only
 * when used as a loadable module.  By default if a read file descriptor exists, it is unregistered.
 */
void
deinit_ds0Bundle(void)
{
	DEBUGMSGTL(("ds0Bundle", "deinit_ds0Bundle: deinitializating...  "));
	external_signal_handler[SIGCHLD] = ds0Bundleold_signal_handler;
	if (my_readfd >= 0) {
		unregister_exceptfd(my_readfd);
		unregister_readfd(my_readfd);
		close(my_readfd);
		my_readfd = -1;
	}
	unregister_mib(ds0Bundle_variables_oid, sizeof(ds0Bundle_variables_oid) / sizeof(oid));
	snmpd_unregister_config_handler("ds0Bundle");
	snmpd_unregister_config_handler("dsx0BondingTable");
	snmpd_unregister_config_handler("dsx0BundleTable");

	/* place any other de-initialization junk you need here */
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
}

int
term_ds0Bundle(int majorID, int minorID, void *serverarg, void *clientarg)
{
	DEBUGMSGTL(("ds0Bundle", "term_ds0Bundle: terminating...  "));
	deinit_ds0Bundle();
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
	return 0;
}

/**
 * @fn struct ds0Bundle_data *ds0Bundle_create(void)
 * @brief create a fresh data structure representing scalars in ds0Bundle.
 *
 * Creates a new ds0Bundle_data structure by allocating dynamic memory for the structure and
 * initializing the default values of scalars in ds0Bundle.
 */
struct ds0Bundle_data *
ds0Bundle_create(void)
{
	struct ds0Bundle_data *StorageNew = SNMP_MALLOC_STRUCT(ds0Bundle_data);

	DEBUGMSGTL(("ds0Bundle", "ds0Bundle_create: creating scalars...  "));
	if (StorageNew != NULL) {
		/* XXX: fill in default scalar values here into StorageNew */
		StorageNew->dsx0BundleNextIndex = 0;

	}
      done:
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
	return (StorageNew);
	goto nomem;
      nomem:
	ds0Bundle_destroy(&StorageNew);
	goto done;
}

/**
 * @fn struct ds0Bundle_data *ds0Bundle_duplicate(struct ds0Bundle_data *thedata)
 * @param thedata the mib structure to duplicate
 * @brief duplicate a mib structure for the mib
 *
 * Duplicates the specified mib structure @param thedata and returns a pointer to the newly
 * allocated mib structure on success, or NULL on failure.
 */
struct ds0Bundle_data *
ds0Bundle_duplicate(struct ds0Bundle_data *thedata)
{
	struct ds0Bundle_data *StorageNew = SNMP_MALLOC_STRUCT(ds0Bundle_data);

	DEBUGMSGTL(("ds0Bundle", "ds0Bundle_duplicate: duplicating mib... "));
	if (StorageNew != NULL) {
		StorageNew->dsx0BundleNextIndex = thedata->dsx0BundleNextIndex;
	}
      done:
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
	return (StorageNew);
	goto destroy;
      destroy:
	ds0Bundle_destroy(&StorageNew);
	goto done;
}

/**
 * @fn int ds0Bundle_destroy(struct ds0Bundle_data **thedata)
 * @param thedata pointer to the data structure in ds0Bundle.
 * @brief delete a scalars structure from ds0Bundle.
 *
 * Frees scalars that were previously removed from ds0Bundle.  Note that the strings associated
 * with octet strings, object identifiers and bit strings still attached to the structure will also
 * be freed.  The pointer that was passed in @param thedata will be set to NULL if it is not already
 * NULL.
 */
int
ds0Bundle_destroy(struct ds0Bundle_data **thedata)
{
	struct ds0Bundle_data *StorageDel;

	DEBUGMSGTL(("ds0Bundle", "ds0Bundle_destroy: deleting scalars...  "));
	if ((StorageDel = *thedata) != NULL) {
		SNMP_FREE(StorageDel);
		*thedata = StorageDel;
	}
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int ds0Bundle_add(struct ds0Bundle_data *thedata)
 * @param thedata the structure representing ds0Bundle scalars.
 * @brief adds node to the ds0Bundle scalar data set.
 *
 * Adds a scalar structure to the ds0Bundle data set.  Note that this function is necessary even
 * when the scalar values are not peristent.
 */
int
ds0Bundle_add(struct ds0Bundle_data *thedata)
{
	DEBUGMSGTL(("ds0Bundle", "ds0Bundle_add: adding data...  "));
	if (thedata)
		ds0BundleStorage = thedata;
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn void parse_ds0Bundle(const char *token, char *line)
 * @param token token used within the configuration file.
 * @param line line from configuration file matching the token.
 * @brief parse configuration file for ds0Bundle entries.
 *
 * This callback is called by UCD-SNMP when it parses a configuration file and finds a configuration
 * file line for the registsred token (in this case ds0Bundle).  This routine is invoked by
 * UCD-SNMP to read the values of scalars in the MIB from the configuration file.  Note that this
 * procedure may exist regardless of the persistence of the MIB.  If there are no configured entries
 * in the configuration MIB, this function will simply not be called.
 */
void
parse_ds0Bundle(const char *token, char *line)
{
	size_t tmpsize;
	struct ds0Bundle_data *StorageTmp = ds0Bundle_create();

	DEBUGMSGTL(("ds0Bundle", "parse_ds0Bundle: parsing config...  "));
	if (StorageTmp == NULL) {
		config_perror("malloc failure");
		return;
	}
	/* XXX: remove individual scalars that are not persistent */
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->dsx0BundleNextIndex, &tmpsize);
	ds0Bundle_add(StorageTmp);
	(void) tmpsize;
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
}

/*
 * store_ds0Bundle(): stores .conf file entries needed to configure the mib.
 */
int
store_ds0Bundle(int majorID, int minorID, void *serverarg, void *clientarg)
{
	char line[SNMP_MAXBUF];
	char *cptr;
	size_t tmpsize;
	struct ds0Bundle_data *StorageTmp;

	DEBUGMSGTL(("ds0Bundle", "store_ds0Bundle: storing data...  "));
	refresh_ds0Bundle(1);
	if ((StorageTmp = ds0BundleStorage) == NULL) {
		DEBUGMSGTL(("ds0Bundle", "error.\n"));
		return SNMPERR_GENERR;
	}
	(void) tmpsize;
	/* XXX: comment entire section if no scalars are persistent */
	{
		memset(line, 0, sizeof(line));
		strcat(line, "ds0Bundle ");
		cptr = line + strlen(line);
		(void) cptr;
		/* XXX: remove individual scalars that are not persistent */
		cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->dsx0BundleNextIndex, &tmpsize);
		snmpd_store_config(line);
	}
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int check_ds0Bundle(struct ds0Bundle_data *StorageTmp, struct ds0Bundle_data *StorageOld)
 * @param StorageTmp the data as updated
 * @param StorageOld the data previous to update
 *
 * This function is used by mibs.  It is used to check, all scalars at a time, the varbinds
 * belonging to the mib.  This function is called for the first varbind in a mib at the beginning of
 * the ACTION phase.  The COMMIT phase does not ensue unless this check passes.  This function can
 * return SNMP_ERR_NOERR or a specific SNMP error value.  Values in StorageOld are the values before
 * the varbinds on the mib were applied; the values in StorageTmp are the new values.  The function
 * is permitted to change the values in StorageTmp to correct them; however, preferences should be
 * made for setting values that were not in the varbinds.
 */
int
check_ds0Bundle(struct ds0Bundle_data *StorageTmp, struct ds0Bundle_data *StorageOld)
{
	/* XXX: provide code to check the scalars for consistency */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int update_ds0Bundle(struct ds0Bundle_data *StorageTmp, struct ds0Bundle_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the set operation (ACTION phase)
 *
 * This function is used by mibs.  It is used to update, all scalars at a time, the varbinds
 * belonging to the mib.  This function is called for the first varbind in a mib at the beginning of
 * the COMMIT phase.  The start of the ACTION phase performs a consistency check on the mib before
 * allowing the request to proceed to the COMMIT phase.  The COMMIT phase then arrives here with
 * consistency already checked (see check_ds0Bundle()).  This function can
 * return SNMP_ERR_NOERROR or SNMP_ERR_COMMITFAILED.  Values in StorageOld are the values before the
 * varbinds on the mib were applied: the values in StorageTmp are the new values.
 */
int
update_ds0Bundle(struct ds0Bundle_data *StorageTmp, struct ds0Bundle_data *StorageOld)
{
	/* XXX: provide code to update the row with the underlying device */
	ds0Bundle_refresh = 1;
	return SNMP_ERR_NOERROR;
}

/**
 * @fn revert_ds0Bundle(struct 
 * @fn void revert_ds0Bundle(struct ds0Bundle_data *StorageTmp, struct ds0Bundle_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the undo operation (UNDO phase)
 */
void
revert_ds0Bundle(struct ds0Bundle_data *StorageTmp, struct ds0Bundle_data *StorageOld)
{
	/* XXX: provide code to revert the row with the underlying device */
	update_ds0Bundle(StorageOld, NULL);
}

/**
 * @fn void refresh_ds0Bundle(int force)
 * @param force forced refresh when non-zero.
 * @brief refresh the scalar values of ds0Bundle.
 *
 * Normally the values retrieved from the operating system are cached.  When the agent receives a
 * SIGPOLL from an open STREAMS configuration or administrative driver Stream, the STREAMS subsystem
 * indicates to the agent that the cache has been invalidated and that it should reread scalars and
 * tables from the STREAMS subsystem.  This function is used when the agent starts for the first
 * time, or after a SIGPOLL has been received (and a scalar has been requested).
 */
void
refresh_ds0Bundle(int force)
{
	if (ds0BundleStorage == NULL) {
		struct ds0Bundle_data *StorageNew;

		if ((StorageNew = ds0Bundle_create()) == NULL)
			return;
		ds0BundleStorage = StorageNew;
		ds0Bundle_refresh = 1;
	}
	if (!force && ds0Bundle_refresh == 0)
		return;
	DEBUGMSGTL(("ds0Bundle", "refresh_ds0Bundle: refreshing...  "));
	/* XXX: Update scalars as required here... */
	ds0Bundle_refresh = 0;
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
}

/**
 * @fn u_char * var_ds0Bundle(struct variable *vp, oid *name, size_t *length, int exact, size_t *var_len, WriteMethod **write_method)
 * @param vp a pointer to the entry in the variables table for the requested variable.
 * @param name the object identifier for which to find.
 * @param length the length of the object identifier.
 * @param exact whether the name is exact.
 * @param var_len a pointer to the length of the representation of the object.
 * @param write_method a pointer to a write method for the object.
 * @brief locate variables in ds0Bundle.
 *
 * This function returns a pointer to a memory area that is static across the request that contains
 * the UCD-SNMP representation of the scalar (so that it may be used to read from for a GET,
 * GET-NEXT or GET-BULK request).  This returned pointer may be NULL, in which case the function is
 * telling UCD-SNMP that the scalar does not exist for reading; however, if write_method is
 * overwritten with a non-NULL value, the function is telling UCD-SNMP that the scalar exists for
 * writing.  Write-only objects can be effected in this way.
 */
u_char *
var_ds0Bundle(struct variable *vp, oid * name, size_t *length, int exact, size_t *var_len, WriteMethod ** write_method)
{
	struct ds0Bundle_data *StorageTmp;
	u_char *rval;

	DEBUGMSGTL(("ds0Bundle", "var_ds0Bundle: lookup up varbind...  "));
	if (header_generic(vp, name, length, exact, var_len, write_method) == MATCH_FAILED)
		return NULL;
	/* Refresh the MIB values if required. */
	refresh_ds0Bundle(0);
	if ((StorageTmp = ds0BundleStorage) == NULL) {
		DEBUGMSGTL(("ds0Bundle", "no datastructure.\n"));
		return NULL;
	}
	*write_method = NULL;
	*var_len = 0;
	rval = NULL;
	/* This is where we do the value assignments for the mib results. */
	switch (vp->magic) {
	case (u_char) DSX0BUNDLENEXTINDEX:	/* ReadWrite */
		*write_method = write_dsx0BundleNextIndex;
		if (!StorageTmp)
			break;
		*var_len = sizeof(StorageTmp->dsx0BundleNextIndex);
		rval = (u_char *) &StorageTmp->dsx0BundleNextIndex;
		break;
	default:
		ERROR_MSG("");
	}
	if (rval)
		DEBUGMSGTL(("ds0Bundle", "found.\n"));
	else
		DEBUGMSGTL(("ds0Bundle", "not found.\n"));
	return (rval);
}

/**
 * @fn struct dsx0BondingTable_data *dsx0BondingTable_create(void)
 * @brief create a fresh data structure representing a new row in the dsx0BondingTable table.
 *
 * Creates a new dsx0BondingTable_data structure by allocating dynamic memory for the structure and
 * initializing the default values of columns in the table.  The row status object, if any, should
 * be set to RS_NOTREADY.
 */
struct dsx0BondingTable_data *
dsx0BondingTable_create(void)
{
	struct dsx0BondingTable_data *StorageNew = SNMP_MALLOC_STRUCT(dsx0BondingTable_data);

	DEBUGMSGTL(("ds0Bundle", "dsx0BondingTable_create: creating row...  "));
	if (StorageNew != NULL) {
		/* XXX: fill in default row values here into StorageNew */
		StorageNew->ifIndex = 0;
		StorageNew->dsx0BondMode = 0;
		StorageNew->dsx0BondStatus = 0;
		StorageNew->dsx0BondRowStatus = 0;
		StorageNew->dsx0BondRowStatus = RS_NOTREADY;
	}
      done:
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
	return (StorageNew);
	goto nomem;
      nomem:
	dsx0BondingTable_destroy(&StorageNew);
	goto done;
}

/**
 * @fn struct dsx0BondingTable_data *dsx0BondingTable_duplicate(struct dsx0BondingTable_data *thedata)
 * @param thedata the row structure to duplicate.
 * @brief duplicate a row structure for a table.
 *
 * Duplicates the specified row structure @param thedata and returns a pointer to the newly
 * allocated row structure on success, or NULL on failure.
 */
struct dsx0BondingTable_data *
dsx0BondingTable_duplicate(struct dsx0BondingTable_data *thedata)
{
	struct dsx0BondingTable_data *StorageNew = SNMP_MALLOC_STRUCT(dsx0BondingTable_data);

	DEBUGMSGTL(("ds0Bundle", "dsx0BondingTable_duplicate: duplicating row...  "));
	if (StorageNew != NULL) {
		StorageNew->dsx0BondingTable_id = thedata->dsx0BondingTable_id;
		StorageNew->ifIndex = thedata->ifIndex;
		StorageNew->dsx0BondMode = thedata->dsx0BondMode;
		StorageNew->dsx0BondStatus = thedata->dsx0BondStatus;
		StorageNew->dsx0BondRowStatus = thedata->dsx0BondRowStatus;
	}
      done:
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
	return (StorageNew);
	goto destroy;
      destroy:
	dsx0BondingTable_destroy(&StorageNew);
	goto done;
}

/**
 * @fn int dsx0BondingTable_destroy(struct dsx0BondingTable_data **thedata)
 * @param thedata pointer to the extracted or existing data structure in the table.
 * @brief delete a row structure from a table.
 *
 * Frees a table row that was previously removed from a table.  Note that the strings associated
 * with octet strings, object identifiers and bit strings still attached to the structure will also
 * be freed.  The pointer that was passed in @param thedata will be set to NULL if it is not already
 * NULL.
 */
int
dsx0BondingTable_destroy(struct dsx0BondingTable_data **thedata)
{
	struct dsx0BondingTable_data *StorageDel;

	DEBUGMSGTL(("ds0Bundle", "dsx0BondingTable_destroy: deleting row...  "));
	if ((StorageDel = *thedata) != NULL) {
		SNMP_FREE(StorageDel);
		*thedata = StorageDel;
	}
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int dsx0BondingTable_add(struct dsx0BondingTable_data *thedata)
 * @param thedata the structure representing the new row in the table.
 * @brief adds a row to the dsx0BondingTable table data set.
 *
 * Adds a table row structure to the dsx0BondingTable table.  Note that this function is necessary even
 * when the table rows are not peristent.  This function can be used within this MIB or other MIBs
 * by the agent to create rows within the table autonomously.
 */
int
dsx0BondingTable_add(struct dsx0BondingTable_data *thedata)
{
	struct variable_list *vars = NULL;

	DEBUGMSGTL(("ds0Bundle", "dsx0BondingTable_add: adding data...  "));
	if (thedata) {
		/* add the index variables to the varbind list, which is used by header_complex to index the data */
		/* ifIndex */
		snmp_varlist_add_variable(&vars, NULL, 0, ASN_INTEGER, (u_char *) &thedata->ifIndex, sizeof(thedata->ifIndex));
		header_complex_add_data(&dsx0BondingTableStorage, vars, thedata);
	}
	DEBUGMSGTL(("ds0Bundle", "registered an entry.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int dsx0BondingTable_del(struct dsx0BondingTable_data *thedata)
 * @param thedata pointer to the extracted or existing data structure in the table.
 * @brief delete a row structure from a table.
 *
 * Deletes a table row structure from the dsx0BondingTable table but does not free it.  Note that this
 * function is necessary even when the table rows are not persistent.  This function can be used
 * within this MIB or another MIB by the agent to delete rows from the table autonomously.  The data
 * structure may either be already extracted from the data set, or the structure may still exist in
 * the data set.  This function will extract the row from the table if it has not already been
 * performed by the caller.
 */
int
dsx0BondingTable_del(struct dsx0BondingTable_data *thedata)
{
	struct dsx0BondingTable_data *StorageDel;

	DEBUGMSGTL(("ds0Bundle", "dsx0BondingTable_data: deleting data...  "));
	if ((StorageDel = thedata) != NULL) {
		struct header_complex_index *hciptr;

		if ((hciptr = header_complex_find_entry(dsx0BondingTableStorage, StorageDel)) != NULL)
			header_complex_extract_entry(&dsx0BondingTableStorage, hciptr);
	}
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn void parse_dsx0BondingTable(const char *token, char *line)
 * @param token token used within the configuration file.
 * @param line line from configuration file matching the token.
 * @brief parse configuration file for dsx0BondingTable entries.
 *
 * This callback is called by UCD-SNMP when it parses a configuration file and finds a configuration
 * file line for the registsred token (in this case dsx0BondingTable).  This routine is invoked by UCD-SNMP
 * to read the values of each row in the table from the configuration file.  Note that this
 * procedure may exist regardless of the persistence of the table.  If there are no configured
 * entries in the configuration table, this function will simply not be called.
 */
void
parse_dsx0BondingTable(const char *token, char *line)
{
	size_t tmpsize;
	struct dsx0BondingTable_data *StorageTmp = dsx0BondingTable_create();

	DEBUGMSGTL(("ds0Bundle", "parse_dsx0BondingTable: parsing config...  "));
	if (StorageTmp == NULL) {
		config_perror("malloc failure");
		return;
	}
	/* XXX: remove individual columns if not persistent */
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->ifIndex, &tmpsize);
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->dsx0BondMode, &tmpsize);
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->dsx0BondStatus, &tmpsize);
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->dsx0BondRowStatus, &tmpsize);
	dsx0BondingTable_add(StorageTmp);
	(void) tmpsize;
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
}

/*
 * store_dsx0BondingTable(): store configuraiton file for dsx0BondingTable
 * stores .conf file entries needed to configure the mib.
 */
int
store_dsx0BondingTable(int majorID, int minorID, void *serverarg, void *clientarg)
{
	char line[SNMP_MAXBUF];
	char *cptr;
	size_t tmpsize;
	struct dsx0BondingTable_data *StorageTmp;
	struct header_complex_index *hcindex;

	DEBUGMSGTL(("ds0Bundle", "store_dsx0BondingTable: storing data...  "));
	refresh_dsx0BondingTable(1);
	(void) tmpsize;
	for (hcindex = dsx0BondingTableStorage; hcindex != NULL; hcindex = hcindex->next) {
		StorageTmp = (struct dsx0BondingTable_data *) hcindex->data;
		/* XXX: comment entire section if row not persistent */
		{
			memset(line, 0, sizeof(line));
			strcat(line, "dsx0BondingTable ");
			cptr = line + strlen(line);
			(void) cptr;
			/* XXX: remove individual columns if not persistent */
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->ifIndex, &tmpsize);
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->dsx0BondMode, &tmpsize);
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->dsx0BondStatus, &tmpsize);
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->dsx0BondRowStatus, &tmpsize);
			snmpd_store_config(line);
		}
	}
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn struct dsx0BundleTable_data *dsx0BundleTable_create(void)
 * @brief create a fresh data structure representing a new row in the dsx0BundleTable table.
 *
 * Creates a new dsx0BundleTable_data structure by allocating dynamic memory for the structure and
 * initializing the default values of columns in the table.  The row status object, if any, should
 * be set to RS_NOTREADY.
 */
struct dsx0BundleTable_data *
dsx0BundleTable_create(void)
{
	struct dsx0BundleTable_data *StorageNew = SNMP_MALLOC_STRUCT(dsx0BundleTable_data);

	DEBUGMSGTL(("ds0Bundle", "dsx0BundleTable_create: creating row...  "));
	if (StorageNew != NULL) {
		/* XXX: fill in default row values here into StorageNew */
		StorageNew->dsx0BundleIfIndex = 0;
		if ((StorageNew->dsx0BundleCircuitIdentifier = malloc(1)) == NULL)
			goto nomem;
		StorageNew->dsx0BundleCircuitIdentifierLen = 0;
		StorageNew->dsx0BundleCircuitIdentifier[StorageNew->dsx0BundleCircuitIdentifierLen] = 0;
		StorageNew->dsx0BundleRowStatus = 0;
		StorageNew->dsx0BundleRowStatus = RS_NOTREADY;
	}
      done:
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
	return (StorageNew);
	goto nomem;
      nomem:
	dsx0BundleTable_destroy(&StorageNew);
	goto done;
}

/**
 * @fn struct dsx0BundleTable_data *dsx0BundleTable_duplicate(struct dsx0BundleTable_data *thedata)
 * @param thedata the row structure to duplicate.
 * @brief duplicate a row structure for a table.
 *
 * Duplicates the specified row structure @param thedata and returns a pointer to the newly
 * allocated row structure on success, or NULL on failure.
 */
struct dsx0BundleTable_data *
dsx0BundleTable_duplicate(struct dsx0BundleTable_data *thedata)
{
	struct dsx0BundleTable_data *StorageNew = SNMP_MALLOC_STRUCT(dsx0BundleTable_data);

	DEBUGMSGTL(("ds0Bundle", "dsx0BundleTable_duplicate: duplicating row...  "));
	if (StorageNew != NULL) {
		StorageNew->dsx0BundleTable_id = thedata->dsx0BundleTable_id;
		StorageNew->dsx0BundleIndex = thedata->dsx0BundleIndex;
		StorageNew->dsx0BundleIfIndex = thedata->dsx0BundleIfIndex;
		if (!(StorageNew->dsx0BundleCircuitIdentifier = malloc(thedata->dsx0BundleCircuitIdentifierLen + 1)))
			goto destroy;
		memcpy(StorageNew->dsx0BundleCircuitIdentifier, thedata->dsx0BundleCircuitIdentifier, thedata->dsx0BundleCircuitIdentifierLen);
		StorageNew->dsx0BundleCircuitIdentifierLen = thedata->dsx0BundleCircuitIdentifierLen;
		StorageNew->dsx0BundleCircuitIdentifier[StorageNew->dsx0BundleCircuitIdentifierLen] = 0;
		StorageNew->dsx0BundleRowStatus = thedata->dsx0BundleRowStatus;
	}
      done:
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
	return (StorageNew);
	goto destroy;
      destroy:
	dsx0BundleTable_destroy(&StorageNew);
	goto done;
}

/**
 * @fn int dsx0BundleTable_destroy(struct dsx0BundleTable_data **thedata)
 * @param thedata pointer to the extracted or existing data structure in the table.
 * @brief delete a row structure from a table.
 *
 * Frees a table row that was previously removed from a table.  Note that the strings associated
 * with octet strings, object identifiers and bit strings still attached to the structure will also
 * be freed.  The pointer that was passed in @param thedata will be set to NULL if it is not already
 * NULL.
 */
int
dsx0BundleTable_destroy(struct dsx0BundleTable_data **thedata)
{
	struct dsx0BundleTable_data *StorageDel;

	DEBUGMSGTL(("ds0Bundle", "dsx0BundleTable_destroy: deleting row...  "));
	if ((StorageDel = *thedata) != NULL) {
		SNMP_FREE(StorageDel->dsx0BundleCircuitIdentifier);
		StorageDel->dsx0BundleCircuitIdentifierLen = 0;
		SNMP_FREE(StorageDel);
		*thedata = StorageDel;
	}
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int dsx0BundleTable_add(struct dsx0BundleTable_data *thedata)
 * @param thedata the structure representing the new row in the table.
 * @brief adds a row to the dsx0BundleTable table data set.
 *
 * Adds a table row structure to the dsx0BundleTable table.  Note that this function is necessary even
 * when the table rows are not peristent.  This function can be used within this MIB or other MIBs
 * by the agent to create rows within the table autonomously.
 */
int
dsx0BundleTable_add(struct dsx0BundleTable_data *thedata)
{
	struct variable_list *vars = NULL;

	DEBUGMSGTL(("ds0Bundle", "dsx0BundleTable_add: adding data...  "));
	if (thedata) {
		/* add the index variables to the varbind list, which is used by header_complex to index the data */
		/* dsx0BundleIndex */
		snmp_varlist_add_variable(&vars, NULL, 0, ASN_INTEGER, (u_char *) &thedata->dsx0BundleIndex, sizeof(thedata->dsx0BundleIndex));
		header_complex_add_data(&dsx0BundleTableStorage, vars, thedata);
	}
	DEBUGMSGTL(("ds0Bundle", "registered an entry.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int dsx0BundleTable_del(struct dsx0BundleTable_data *thedata)
 * @param thedata pointer to the extracted or existing data structure in the table.
 * @brief delete a row structure from a table.
 *
 * Deletes a table row structure from the dsx0BundleTable table but does not free it.  Note that this
 * function is necessary even when the table rows are not persistent.  This function can be used
 * within this MIB or another MIB by the agent to delete rows from the table autonomously.  The data
 * structure may either be already extracted from the data set, or the structure may still exist in
 * the data set.  This function will extract the row from the table if it has not already been
 * performed by the caller.
 */
int
dsx0BundleTable_del(struct dsx0BundleTable_data *thedata)
{
	struct dsx0BundleTable_data *StorageDel;

	DEBUGMSGTL(("ds0Bundle", "dsx0BundleTable_data: deleting data...  "));
	if ((StorageDel = thedata) != NULL) {
		struct header_complex_index *hciptr;

		if ((hciptr = header_complex_find_entry(dsx0BundleTableStorage, StorageDel)) != NULL)
			header_complex_extract_entry(&dsx0BundleTableStorage, hciptr);
	}
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn void parse_dsx0BundleTable(const char *token, char *line)
 * @param token token used within the configuration file.
 * @param line line from configuration file matching the token.
 * @brief parse configuration file for dsx0BundleTable entries.
 *
 * This callback is called by UCD-SNMP when it parses a configuration file and finds a configuration
 * file line for the registsred token (in this case dsx0BundleTable).  This routine is invoked by UCD-SNMP
 * to read the values of each row in the table from the configuration file.  Note that this
 * procedure may exist regardless of the persistence of the table.  If there are no configured
 * entries in the configuration table, this function will simply not be called.
 */
void
parse_dsx0BundleTable(const char *token, char *line)
{
	size_t tmpsize;
	struct dsx0BundleTable_data *StorageTmp = dsx0BundleTable_create();

	DEBUGMSGTL(("ds0Bundle", "parse_dsx0BundleTable: parsing config...  "));
	if (StorageTmp == NULL) {
		config_perror("malloc failure");
		return;
	}
	/* XXX: remove individual columns if not persistent */
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->dsx0BundleIndex, &tmpsize);
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->dsx0BundleIfIndex, &tmpsize);
	SNMP_FREE(StorageTmp->dsx0BundleCircuitIdentifier);
	line = read_config_read_data(ASN_OCTET_STR, line, &StorageTmp->dsx0BundleCircuitIdentifier, &StorageTmp->dsx0BundleCircuitIdentifierLen);
	if (StorageTmp->dsx0BundleCircuitIdentifier == NULL) {
		config_perror("invalid specification for dsx0BundleCircuitIdentifier");
		return;
	}
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->dsx0BundleRowStatus, &tmpsize);
	dsx0BundleTable_add(StorageTmp);
	(void) tmpsize;
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
}

/*
 * store_dsx0BundleTable(): store configuraiton file for dsx0BundleTable
 * stores .conf file entries needed to configure the mib.
 */
int
store_dsx0BundleTable(int majorID, int minorID, void *serverarg, void *clientarg)
{
	char line[SNMP_MAXBUF];
	char *cptr;
	size_t tmpsize;
	struct dsx0BundleTable_data *StorageTmp;
	struct header_complex_index *hcindex;

	DEBUGMSGTL(("ds0Bundle", "store_dsx0BundleTable: storing data...  "));
	refresh_dsx0BundleTable(1);
	(void) tmpsize;
	for (hcindex = dsx0BundleTableStorage; hcindex != NULL; hcindex = hcindex->next) {
		StorageTmp = (struct dsx0BundleTable_data *) hcindex->data;
		/* XXX: comment entire section if row not persistent */
		{
			memset(line, 0, sizeof(line));
			strcat(line, "dsx0BundleTable ");
			cptr = line + strlen(line);
			(void) cptr;
			/* XXX: remove individual columns if not persistent */
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->dsx0BundleIndex, &tmpsize);
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->dsx0BundleIfIndex, &tmpsize);
			cptr = read_config_store_data(ASN_OCTET_STR, cptr, &StorageTmp->dsx0BundleCircuitIdentifier, &StorageTmp->dsx0BundleCircuitIdentifierLen);
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->dsx0BundleRowStatus, &tmpsize);
			snmpd_store_config(line);
		}
	}
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int activate_dsx0BondingTable_row(struct dsx0BondingTable_data *StorageTmp)
 * @param StorageTmp the data row to activate
 * @brief commit activation of a row to the underlying device
 *
 * This function is used by tables that contain a RowStatus object.  It is used to move the row from
 * the RS_NOTINSERVICE state to the RS_ACTIVE state.  It is also used when transitioning from the
 * RS_CREATEANDGO state to the RS_ACTIVE state.  If activation fails, the function should return
 * SNMP_ERR_COMMITFAILED; otherwise, SNMP_ERR_NOERROR.
 */
int
activate_dsx0BondingTable_row(struct dsx0BondingTable_data *StorageTmp)
{
	/* XXX: provide code to activate the row with the underlying device */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int deactivate_dsx0BondingTable_row(struct dsx0BondingTable_data *StorageTmp)
 * @param StorageTmp the data row to deactivate
 * @brief commit deactivation of a row to the underlying device
 *
 * This function is used by tables that contain a RowStatus object.  It is used to move the row from
 * the RS_ACTIVE state to the RS_NOTINSERVICE state.  It is also used when transitioning from the
 * RS_ACTIVE state to the RS_DESTROY state.  If deactivation fails, the function should return
 * SNMP_ERR_COMMITFAILED; otherwise, SNMP_ERR_NOERROR.
 */
int
deactivate_dsx0BondingTable_row(struct dsx0BondingTable_data *StorageTmp)
{
	/* XXX: provide code to deactivate the row with the underlying device */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int activate_dsx0BundleTable_row(struct dsx0BundleTable_data *StorageTmp)
 * @param StorageTmp the data row to activate
 * @brief commit activation of a row to the underlying device
 *
 * This function is used by tables that contain a RowStatus object.  It is used to move the row from
 * the RS_NOTINSERVICE state to the RS_ACTIVE state.  It is also used when transitioning from the
 * RS_CREATEANDGO state to the RS_ACTIVE state.  If activation fails, the function should return
 * SNMP_ERR_COMMITFAILED; otherwise, SNMP_ERR_NOERROR.
 */
int
activate_dsx0BundleTable_row(struct dsx0BundleTable_data *StorageTmp)
{
	/* XXX: provide code to activate the row with the underlying device */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int deactivate_dsx0BundleTable_row(struct dsx0BundleTable_data *StorageTmp)
 * @param StorageTmp the data row to deactivate
 * @brief commit deactivation of a row to the underlying device
 *
 * This function is used by tables that contain a RowStatus object.  It is used to move the row from
 * the RS_ACTIVE state to the RS_NOTINSERVICE state.  It is also used when transitioning from the
 * RS_ACTIVE state to the RS_DESTROY state.  If deactivation fails, the function should return
 * SNMP_ERR_COMMITFAILED; otherwise, SNMP_ERR_NOERROR.
 */
int
deactivate_dsx0BundleTable_row(struct dsx0BundleTable_data *StorageTmp)
{
	/* XXX: provide code to deactivate the row with the underlying device */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int check_dsx0BondingTable_row(struct dsx0BondingTable_data *StorageTmp, struct dsx0BondingTable_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 *
 * This function is used both by tables that do and do not contain a RowStatus object.  It is used
 * to check, row-at-a-time, the varbinds belonging to the row.  Note that this function is not used
 * when rows are created or destroyed.  This function is called for the first varbind in a row at
 * the beginning of the ACTION phase.  The start of the ACTION pahse performs this consitency check
 * on the row before allowing the request to proceed to the COMMIT phase.  This function can return
 * SNMP_ERR_NOERR or a specific SNMP error value.  Values in StorageOld are the values before the
 * varbinds on the mib were applied; the values in StorageTmp are the new values.  The function is
 * permitted to change the values in StorageTmp to correct them; however, preference should be made
 * for setting values where were not in the varbinds.
 */
int
check_dsx0BondingTable_row(struct dsx0BondingTable_data *StorageTmp, struct dsx0BondingTable_data *StorageOld)
{
	/* XXX: provide code to check the row for consistency */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int update_dsx0BondingTable_row(struct dsx0BondingTable_data *StorageTmp, struct dsx0BondingTable_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the set operation (ACTION phase) on a row
 *
 * This function is used both by tables that do and do not contain a RowStatus object.  It is used
 * to update, row-at-a-time, the varbinds belonging to the row.  Note that this function is not used
 * when rows are created or destroyed.  This function is called for the first varbind in a row at
 * the beginning of the COMMIT phase.  The start of the ACTION phase performs a consistency check on
 * the row before allowing the request to proceed to the COMMIT phase.  The COMMIT phase then
 * arrives here with consistency already checked (see check_dsx0BondingTable_row()).  This function can
 * return SNMP_ERR_NOERROR or SNMP_ERR_COMMITFAILED.  Values in StorageOld are the values before the
 * varbinds on the row were applied: the values in StorageTmp are the new values.
 */
int
update_dsx0BondingTable_row(struct dsx0BondingTable_data *StorageTmp, struct dsx0BondingTable_data *StorageOld)
{
	/* XXX: provide code to update the row with the underlying device */
	dsx0BondingTable_refresh = 1;
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int revert_dsx0BondingTable_row(struct dsx0BondingTable_data *StorageTmp, struct dsx0BondingTable_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the undo operation (UNDO phase) on a row
 */
void
revert_dsx0BondingTable_row(struct dsx0BondingTable_data *StorageTmp, struct dsx0BondingTable_data *StorageOld)
{
	/* XXX: provide code to revert the row with the underlying device */
	update_dsx0BondingTable_row(StorageOld, NULL);
}

/**
 * @fn void refresh_dsx0BondingTable_row(struct dsx0BondingTable_data *StorageTmp, int force)
 * @param StorageTmp the data row to refresh.
 * @param force force refresh if non-zero.
 * @brief refresh the contents of the dsx0BondingTable row.
 *
 * Normally the values retrieved from the operating system are cached.  However, if a row contains
 * temporal values, such as statistics counters, gauges, timestamps, or other transient columns, it
 * may be necessary to refresh the row on some other basis, but normally only once per request.
 */
struct dsx0BondingTable_data *
refresh_dsx0BondingTable_row(struct dsx0BondingTable_data *StorageTmp, int force)
{
	if (!StorageTmp || (!force && StorageTmp->dsx0BondingTable_request == sa_request))
		return (StorageTmp);
	/* XXX: update row; delete it and return NULL if the row has disappeared */
	StorageTmp->dsx0BondingTable_request = sa_request;
	return (StorageTmp);
}

/**
 * @fn void refresh_dsx0BondingTable(int force)
 * @param force force refresh if non-zero.
 * @brief refresh the scalar values of the dsx0BondingTable.
 *
 * Normally the values retrieved from the operating system are cached.  When the agent receives a
 * SIGPOLL from an open STREAMS configuration or administrative driver Stream, the STREAMS subsystem
 * indicates to the agent that the cache has been invalidated and that it should reread scalars and
 * tables from the STREAMS subsystem.  This function is used when the agent starts for the first
 * time, or after a SIGPOLL has been received (and a row or column has been requested).
 */
void
refresh_dsx0BondingTable(int force)
{
	if (!force && dsx0BondingTable_refresh == 0)
		return;
	/* XXX: Here, update the table as required... */
	dsx0BondingTable_refresh = 0;
}

/**
 * @fn u_char *var_dsx0BondingTable(struct variable *vp, oid *name, size_t *length, int exact, size_t *var_len, WriteMethod **write_method)
 * @brief locate variables in dsx0BondingTable.
 *
 * Handle this table separately from the scalar value case.  The workings of this are basically the
 * same as for var_ds0Bundle above.
 */
u_char *
var_dsx0BondingTable(struct variable *vp, oid * name, size_t *length, int exact, size_t *var_len, WriteMethod ** write_method)
{
	struct dsx0BondingTable_data *StorageTmp = NULL;
	u_char *rval;

	DEBUGMSGTL(("ds0Bundle", "var_dsx0BondingTable: Entering...  \n"));
	/* Make sure that the storage data does not need to be refreshed before checking the header. */
	refresh_dsx0BondingTable(0);
	/* This assumes you have registered all your data properly with header_complex_add() somewhere before this. */
	while ((StorageTmp = header_complex(dsx0BondingTableStorage, vp, name, length, exact, var_len, write_method)))
		if ((StorageTmp = refresh_dsx0BondingTable_row(StorageTmp, 0)) || exact)
			break;
	*write_method = NULL;
	*var_len = 0;
	rval = NULL;
	/* This is where we do the value assignments for the mib results. */
	switch (vp->magic) {
	case (u_char) DSX0BONDMODE:	/* Create */
		*write_method = write_dsx0BondMode;
		if (!StorageTmp)
			break;
		*var_len = sizeof(StorageTmp->dsx0BondMode);
		rval = (u_char *) &StorageTmp->dsx0BondMode;
		break;
	case (u_char) DSX0BONDSTATUS:	/* ReadOnly */
		if (!StorageTmp)
			break;
		*var_len = sizeof(StorageTmp->dsx0BondStatus);
		rval = (u_char *) &StorageTmp->dsx0BondStatus;
		break;
	case (u_char) DSX0BONDROWSTATUS:	/* Create */
		*write_method = write_dsx0BondRowStatus;
		if (!StorageTmp)
			break;
		*var_len = sizeof(StorageTmp->dsx0BondRowStatus);
		rval = (u_char *) &StorageTmp->dsx0BondRowStatus;
		break;
	default:
		ERROR_MSG("");
	}
	return (rval);
}

/**
 * @fn int check_dsx0BundleTable_row(struct dsx0BundleTable_data *StorageTmp, struct dsx0BundleTable_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 *
 * This function is used both by tables that do and do not contain a RowStatus object.  It is used
 * to check, row-at-a-time, the varbinds belonging to the row.  Note that this function is not used
 * when rows are created or destroyed.  This function is called for the first varbind in a row at
 * the beginning of the ACTION phase.  The start of the ACTION pahse performs this consitency check
 * on the row before allowing the request to proceed to the COMMIT phase.  This function can return
 * SNMP_ERR_NOERR or a specific SNMP error value.  Values in StorageOld are the values before the
 * varbinds on the mib were applied; the values in StorageTmp are the new values.  The function is
 * permitted to change the values in StorageTmp to correct them; however, preference should be made
 * for setting values where were not in the varbinds.
 */
int
check_dsx0BundleTable_row(struct dsx0BundleTable_data *StorageTmp, struct dsx0BundleTable_data *StorageOld)
{
	/* XXX: provide code to check the row for consistency */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int update_dsx0BundleTable_row(struct dsx0BundleTable_data *StorageTmp, struct dsx0BundleTable_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the set operation (ACTION phase) on a row
 *
 * This function is used both by tables that do and do not contain a RowStatus object.  It is used
 * to update, row-at-a-time, the varbinds belonging to the row.  Note that this function is not used
 * when rows are created or destroyed.  This function is called for the first varbind in a row at
 * the beginning of the COMMIT phase.  The start of the ACTION phase performs a consistency check on
 * the row before allowing the request to proceed to the COMMIT phase.  The COMMIT phase then
 * arrives here with consistency already checked (see check_dsx0BundleTable_row()).  This function can
 * return SNMP_ERR_NOERROR or SNMP_ERR_COMMITFAILED.  Values in StorageOld are the values before the
 * varbinds on the row were applied: the values in StorageTmp are the new values.
 */
int
update_dsx0BundleTable_row(struct dsx0BundleTable_data *StorageTmp, struct dsx0BundleTable_data *StorageOld)
{
	/* XXX: provide code to update the row with the underlying device */
	dsx0BundleTable_refresh = 1;
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int revert_dsx0BundleTable_row(struct dsx0BundleTable_data *StorageTmp, struct dsx0BundleTable_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the undo operation (UNDO phase) on a row
 */
void
revert_dsx0BundleTable_row(struct dsx0BundleTable_data *StorageTmp, struct dsx0BundleTable_data *StorageOld)
{
	/* XXX: provide code to revert the row with the underlying device */
	update_dsx0BundleTable_row(StorageOld, NULL);
}

/**
 * @fn void refresh_dsx0BundleTable_row(struct dsx0BundleTable_data *StorageTmp, int force)
 * @param StorageTmp the data row to refresh.
 * @param force force refresh if non-zero.
 * @brief refresh the contents of the dsx0BundleTable row.
 *
 * Normally the values retrieved from the operating system are cached.  However, if a row contains
 * temporal values, such as statistics counters, gauges, timestamps, or other transient columns, it
 * may be necessary to refresh the row on some other basis, but normally only once per request.
 */
struct dsx0BundleTable_data *
refresh_dsx0BundleTable_row(struct dsx0BundleTable_data *StorageTmp, int force)
{
	if (!StorageTmp || (!force && StorageTmp->dsx0BundleTable_request == sa_request))
		return (StorageTmp);
	/* XXX: update row; delete it and return NULL if the row has disappeared */
	StorageTmp->dsx0BundleTable_request = sa_request;
	return (StorageTmp);
}

/**
 * @fn void refresh_dsx0BundleTable(int force)
 * @param force force refresh if non-zero.
 * @brief refresh the scalar values of the dsx0BundleTable.
 *
 * Normally the values retrieved from the operating system are cached.  When the agent receives a
 * SIGPOLL from an open STREAMS configuration or administrative driver Stream, the STREAMS subsystem
 * indicates to the agent that the cache has been invalidated and that it should reread scalars and
 * tables from the STREAMS subsystem.  This function is used when the agent starts for the first
 * time, or after a SIGPOLL has been received (and a row or column has been requested).
 */
void
refresh_dsx0BundleTable(int force)
{
	if (!force && dsx0BundleTable_refresh == 0)
		return;
	/* XXX: Here, update the table as required... */
	dsx0BundleTable_refresh = 0;
}

/**
 * @fn u_char *var_dsx0BundleTable(struct variable *vp, oid *name, size_t *length, int exact, size_t *var_len, WriteMethod **write_method)
 * @brief locate variables in dsx0BundleTable.
 *
 * Handle this table separately from the scalar value case.  The workings of this are basically the
 * same as for var_ds0Bundle above.
 */
u_char *
var_dsx0BundleTable(struct variable *vp, oid * name, size_t *length, int exact, size_t *var_len, WriteMethod ** write_method)
{
	struct dsx0BundleTable_data *StorageTmp = NULL;
	u_char *rval;

	DEBUGMSGTL(("ds0Bundle", "var_dsx0BundleTable: Entering...  \n"));
	/* Make sure that the storage data does not need to be refreshed before checking the header. */
	refresh_dsx0BundleTable(0);
	/* This assumes you have registered all your data properly with header_complex_add() somewhere before this. */
	while ((StorageTmp = header_complex(dsx0BundleTableStorage, vp, name, length, exact, var_len, write_method)))
		if ((StorageTmp = refresh_dsx0BundleTable_row(StorageTmp, 0)) || exact)
			break;
	*write_method = NULL;
	*var_len = 0;
	rval = NULL;
	/* This is where we do the value assignments for the mib results. */
	switch (vp->magic) {
	case (u_char) DSX0BUNDLEIFINDEX:	/* ReadOnly */
		if (!StorageTmp)
			break;
		*var_len = sizeof(StorageTmp->dsx0BundleIfIndex);
		rval = (u_char *) &StorageTmp->dsx0BundleIfIndex;
		break;
	case (u_char) DSX0BUNDLECIRCUITIDENTIFIER:	/* Create */
		*write_method = write_dsx0BundleCircuitIdentifier;
		if (!StorageTmp)
			break;
		*var_len = StorageTmp->dsx0BundleCircuitIdentifierLen;
		rval = (u_char *) StorageTmp->dsx0BundleCircuitIdentifier;
		break;
	case (u_char) DSX0BUNDLEROWSTATUS:	/* Create */
		*write_method = write_dsx0BundleRowStatus;
		if (!StorageTmp)
			break;
		*var_len = sizeof(StorageTmp->dsx0BundleRowStatus);
		rval = (u_char *) &StorageTmp->dsx0BundleRowStatus;
		break;
	default:
		ERROR_MSG("");
	}
	return (rval);
}

/**
 * @fn int write_dsx0BondMode(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid *name, size_t name_len)
 * @param action the stage of the SET operation.
 * @param var_val pointer to the varbind value.
 * @param var_val_type the ASN type.
 * @param var_val_len the length of the varbind value.
 * @param statP static pointer.
 * @param name the varbind OID.
 * @param name_len number of elements in OID.
 * @brief Table row and column write routine.
 */
int
write_dsx0BondMode(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	struct dsx0BondingTable_data *StorageTmp = NULL, *StorageOld = NULL;
	size_t newlen = name_len - 11;
	long set_value = *((long *) var_val);
	int ret = SNMP_ERR_NOERROR;

	DEBUGMSGTL(("ds0Bundle", "write_dsx0BondMode entering action=%d...  \n", action));
	if (StorageTmp == NULL)
		return SNMP_ERR_NOSUCHNAME;
	StorageTmp = header_complex(dsx0BondingTableStorage, NULL, &name[11], &newlen, 1, NULL, NULL);
	switch (action) {
	case RESERVE1:
		if (StorageTmp != NULL && statP == NULL) {
			/* have row but no column */
			switch (StorageTmp->dsx0BondRowStatus) {
			case RS_ACTIVE:
				/* cannot create non-existent column while active */
				snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0BondMode: but column non-existent\n");
				return SNMP_ERR_INCONSISTENTVALUE;
			case RS_NOTINSERVICE:
			case RS_NOTREADY:
				/* assume column can be created */
				break;
			}
		}
		if (var_val_type != ASN_INTEGER) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0BondMode not ASN_INTEGER\n");
			return SNMP_ERR_WRONGTYPE;
		}
		if (var_val_len > sizeof(int32_t)) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0BondMode: bad length\n");
			return SNMP_ERR_WRONGLENGTH;
		}
		switch (set_value) {
		case DSX0BONDMODE_NONE:
		case DSX0BONDMODE_OTHER:
		case DSX0BONDMODE_MODE0:
		case DSX0BONDMODE_MODE1:
		case DSX0BONDMODE_MODE2:
		case DSX0BONDMODE_MODE3:
			break;
		default:
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0BondMode: bad value\n");
			return SNMP_ERR_WRONGVALUE;
		}
		/* one allocation for the whole row */
		if ((StorageOld = StorageTmp->dsx0BondingTable_old) == NULL)
			if (StorageTmp->dsx0BondingTable_rsvs == 0)
				if ((StorageOld = StorageTmp->dsx0BondingTable_old = dsx0BondingTable_duplicate(StorageTmp)) == NULL)
					return SNMP_ERR_RESOURCEUNAVAILABLE;
		if (StorageOld != NULL)
			StorageTmp->dsx0BondingTable_rsvs++;
		StorageTmp->dsx0BondMode = set_value;
		/* XXX: insert code to consistency check this particular varbind, if necessary (so error codes are applied to varbinds) */
		break;
	case RESERVE2:		/* memory reseveration, final preparation... */
		if ((StorageOld = StorageTmp->dsx0BondingTable_old) != NULL) {
			/* one consistency check for the whole row */
			if (StorageTmp->dsx0BondingTable_tsts == 0)
				if ((ret = check_dsx0BondingTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->dsx0BondingTable_tsts++;
		}
		break;
	case ACTION:		/* The variable has been stored in StorageTmp->dsx0BondMode for you to use, and you have just been asked to do something with it.  Note that anything done here must be 
				   reversable in the UNDO case */
		if (StorageTmp == NULL)
			return SNMP_ERR_NOSUCHNAME;
		/* XXX: insert code to set this particular varbind, if necessary */
		/* one set action for the whole row */
		if ((StorageOld = StorageTmp->dsx0BondingTable_old) != NULL) {
			/* XXX: insert code to set this particular varbind, if necessary */
			if (StorageTmp->dsx0BondingTable_sets == 0)
				if ((ret = update_dsx0BondingTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->dsx0BondingTable_sets++;
		}
		break;
	case COMMIT:		/* Things are working well, so it's now safe to make the change permanently.  Make sure that anything done here can't fail! */
		/* one commit for the whole mib */
		if ((StorageOld = StorageTmp->dsx0BondingTable_old) != NULL) {
			dsx0BondingTable_destroy(&StorageTmp->dsx0BondingTable_old);
			StorageTmp->dsx0BondingTable_rsvs = 0;
			StorageTmp->dsx0BondingTable_tsts = 0;
			StorageTmp->dsx0BondingTable_sets = 0;
		}
		break;
	case UNDO:		/* Back out any changes made in the ACTION case */
		if ((StorageOld = StorageTmp->dsx0BondingTable_old) == NULL)
			break;
		/* XXX: insert code to undo any action performed on this particular varbind */
		if (--StorageTmp->dsx0BondingTable_sets == 0)
			revert_dsx0BondingTable_row(StorageTmp, StorageOld);
		/* fall through */
	case FREE:		/* Release any resources that have been allocated */
		if ((StorageOld = StorageTmp->dsx0BondingTable_old) == NULL)
			break;
		StorageTmp->dsx0BondMode = StorageOld->dsx0BondMode;
		if (--StorageTmp->dsx0BondingTable_rsvs == 0)
			dsx0BondingTable_destroy(&StorageTmp->dsx0BondingTable_old);
		break;
	}
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int write_dsx0BundleCircuitIdentifier(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid *name, size_t name_len)
 * @param action the stage of the SET operation.
 * @param var_val pointer to the varbind value.
 * @param var_val_type the ASN type.
 * @param var_val_len the length of the varbind value.
 * @param statP static pointer.
 * @param name the varbind OID.
 * @param name_len number of elements in OID.
 * @brief Table row and column write routine.
 */
int
write_dsx0BundleCircuitIdentifier(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	struct dsx0BundleTable_data *StorageTmp = NULL, *StorageOld = NULL;
	size_t newlen = name_len - 11;
	uint8_t *string = NULL;
	int ret = SNMP_ERR_NOERROR;

	DEBUGMSGTL(("ds0Bundle", "write_dsx0BundleCircuitIdentifier entering action=%d...  \n", action));
	if (StorageTmp == NULL)
		return SNMP_ERR_NOSUCHNAME;
	StorageTmp = header_complex(dsx0BundleTableStorage, NULL, &name[11], &newlen, 1, NULL, NULL);
	switch (action) {
	case RESERVE1:
		if (StorageTmp != NULL && statP == NULL) {
			/* have row but no column */
			switch (StorageTmp->dsx0BundleRowStatus) {
			case RS_ACTIVE:
				/* cannot create non-existent column while active */
				snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0BundleCircuitIdentifier: but column non-existent\n");
				return SNMP_ERR_INCONSISTENTVALUE;
			case RS_NOTINSERVICE:
			case RS_NOTREADY:
				/* assume column can be created */
				break;
			}
		}
		if (var_val_type != ASN_OCTET_STR) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0BundleCircuitIdentifier not ASN_OCTET_STR\n");
			return SNMP_ERR_WRONGTYPE;
		}
		/* Note: ranges 0..255 */
		if (var_val_len > SPRINT_MAX_LEN || ((0 > var_val_len || var_val_len > 255))) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0BundleCircuitIdentifier: bad length\n");
			return SNMP_ERR_WRONGLENGTH;
		}
		/* one allocation for the whole row */
		if ((StorageOld = StorageTmp->dsx0BundleTable_old) == NULL)
			if (StorageTmp->dsx0BundleTable_rsvs == 0)
				if ((StorageOld = StorageTmp->dsx0BundleTable_old = dsx0BundleTable_duplicate(StorageTmp)) == NULL)
					return SNMP_ERR_RESOURCEUNAVAILABLE;
		if (StorageOld != NULL)
			StorageTmp->dsx0BundleTable_rsvs++;
		if ((string = malloc(var_val_len + 1)) == NULL)
			return SNMP_ERR_RESOURCEUNAVAILABLE;
		memcpy((void *) string, (void *) var_val, var_val_len);
		string[var_val_len] = 0;
		SNMP_FREE(StorageTmp->dsx0BundleCircuitIdentifier);
		StorageTmp->dsx0BundleCircuitIdentifier = string;
		StorageTmp->dsx0BundleCircuitIdentifierLen = var_val_len;
		/* XXX: insert code to consistency check this particular varbind, if necessary (so error codes are applied to varbinds) */
		break;
	case RESERVE2:		/* memory reseveration, final preparation... */
		if ((StorageOld = StorageTmp->dsx0BundleTable_old) != NULL) {
			/* one consistency check for the whole row */
			if (StorageTmp->dsx0BundleTable_tsts == 0)
				if ((ret = check_dsx0BundleTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->dsx0BundleTable_tsts++;
		}
		break;
	case ACTION:		/* The variable has been stored in StorageTmp->dsx0BundleCircuitIdentifier for you to use, and you have just been asked to do something with it.  Note that anything
				   done here must be reversable in the UNDO case */
		if (StorageTmp == NULL)
			return SNMP_ERR_NOSUCHNAME;
		/* XXX: insert code to set this particular varbind, if necessary */
		/* one set action for the whole row */
		if ((StorageOld = StorageTmp->dsx0BundleTable_old) != NULL) {
			/* XXX: insert code to set this particular varbind, if necessary */
			if (StorageTmp->dsx0BundleTable_sets == 0)
				if ((ret = update_dsx0BundleTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->dsx0BundleTable_sets++;
		}
		break;
	case COMMIT:		/* Things are working well, so it's now safe to make the change permanently.  Make sure that anything done here can't fail! */
		/* one commit for the whole mib */
		if ((StorageOld = StorageTmp->dsx0BundleTable_old) != NULL) {
			dsx0BundleTable_destroy(&StorageTmp->dsx0BundleTable_old);
			StorageTmp->dsx0BundleTable_rsvs = 0;
			StorageTmp->dsx0BundleTable_tsts = 0;
			StorageTmp->dsx0BundleTable_sets = 0;
		}
		break;
	case UNDO:		/* Back out any changes made in the ACTION case */
		if ((StorageOld = StorageTmp->dsx0BundleTable_old) == NULL)
			break;
		/* XXX: insert code to undo any action performed on this particular varbind */
		if (--StorageTmp->dsx0BundleTable_sets == 0)
			revert_dsx0BundleTable_row(StorageTmp, StorageOld);
		/* fall through */
	case FREE:		/* Release any resources that have been allocated */
		if ((StorageOld = StorageTmp->dsx0BundleTable_old) == NULL)
			break;
		if (StorageOld->dsx0BundleCircuitIdentifier != NULL) {
			SNMP_FREE(StorageTmp->dsx0BundleCircuitIdentifier);
			StorageTmp->dsx0BundleCircuitIdentifier = StorageOld->dsx0BundleCircuitIdentifier;
			StorageTmp->dsx0BundleCircuitIdentifierLen = StorageOld->dsx0BundleCircuitIdentifierLen;
			StorageOld->dsx0BundleCircuitIdentifier = NULL;
			StorageOld->dsx0BundleCircuitIdentifierLen = 0;
		}
		if (--StorageTmp->dsx0BundleTable_rsvs == 0)
			dsx0BundleTable_destroy(&StorageTmp->dsx0BundleTable_old);
		break;
	}
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int write_dsx0BundleNextIndex(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid *name, size_t name_len)
 * @param action the stage of the SET operation.
 * @param var_val pointer to the varbind value.
 * @param var_val_type the ASN type.
 * @param var_val_len the length of the varbind value.
 * @param statP static pointer.
 * @param name the varbind OID.
 * @param name_len number of elements in OID.
 * @brief Scalar write routine.
 */
int
write_dsx0BundleNextIndex(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	struct ds0Bundle_data *StorageTmp = NULL, *StorageOld = NULL;
	long set_value = *((long *) var_val);
	int ret = SNMP_ERR_NOERROR;

	DEBUGMSGTL(("ds0Bundle", "write_dsx0BundleNextIndex entering action=%d...  \n", action));
	if ((StorageTmp = ds0BundleStorage) == NULL)
		return SNMP_ERR_NOSUCHNAME;
	switch (action) {
	case RESERVE1:
		if (var_val_type != ASN_INTEGER) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0BundleNextIndex not ASN_INTEGER\n");
			return SNMP_ERR_WRONGTYPE;
		}
		if (var_val_len > sizeof(int32_t)) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0BundleNextIndex: bad length\n");
			return SNMP_ERR_WRONGLENGTH;
		}
		/* Note: ranges 0..2147483647 */
		if ((0 > set_value || set_value > 2147483647)) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0BundleNextIndex: bad value\n");
			return SNMP_ERR_WRONGVALUE;
		}
		/* one allocation for whole mib */
		if ((StorageOld = StorageTmp->ds0Bundle_old) == NULL)
			if (StorageTmp->ds0Bundle_rsvs == 0)
				if ((StorageOld = StorageTmp->ds0Bundle_old = ds0Bundle_duplicate(StorageTmp)) == NULL)
					return SNMP_ERR_RESOURCEUNAVAILABLE;
		if (StorageOld != NULL)
			StorageTmp->ds0Bundle_rsvs++;
		StorageTmp->dsx0BundleNextIndex = set_value;
		/* XXX: insert code to consistency check this particular varbind, if necessary (so error codes are applied to varbinds) */
		break;
	case RESERVE2:		/* memory reseveration, final preparation... */
		if ((StorageOld = StorageTmp->ds0Bundle_old) != NULL) {
			/* one consistency check for the whole mib */
			if (StorageTmp->ds0Bundle_tsts == 0)
				if ((ret = check_ds0Bundle(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->ds0Bundle_tsts++;
		}
		break;
	case ACTION:		/* The variable has been stored in StorageTmp->dsx0BundleNextIndex for you to use, and you have just been asked to do something with it.  Note that anything done here
				   must be reversable in the UNDO case */
		/* XXX: insert code to set this particular varbind, if necessary */
		/* one set action for the whole mib */
		if ((StorageOld = StorageTmp->ds0Bundle_old) != NULL) {
			/* XXX: insert code to set this particular varbind, if necessary */
			if (StorageTmp->ds0Bundle_sets == 0)
				if ((ret = update_ds0Bundle(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->ds0Bundle_sets++;
		}
		break;
	case COMMIT:		/* Things are working well, so it's now safe to make the change permanently.  Make sure that anything done here can't fail! */
		/* one commit for the whole mib */
		if ((StorageOld = StorageTmp->ds0Bundle_old) != NULL) {
			ds0Bundle_destroy(&StorageTmp->ds0Bundle_old);
			StorageTmp->ds0Bundle_rsvs = 0;
			StorageTmp->ds0Bundle_tsts = 0;
			StorageTmp->ds0Bundle_sets = 0;
		}
		break;
	case UNDO:		/* Back out any changes made in the ACTION case */
		if ((StorageOld = StorageTmp->ds0Bundle_old) == NULL)
			break;
		/* XXX: insert code to undo any action performed on this particular varbind */
		if (--StorageTmp->ds0Bundle_tsts == 0)
			revert_ds0Bundle(StorageTmp, StorageOld);
		/* fall through */
	case FREE:		/* Release any resources that have been allocated */
		if ((StorageOld = StorageTmp->ds0Bundle_old) == NULL)
			break;
		StorageTmp->dsx0BundleNextIndex = StorageOld->dsx0BundleNextIndex;
		if (--StorageTmp->ds0Bundle_rsvs == 0)
			ds0Bundle_destroy(&StorageTmp->ds0Bundle_old);
		break;
	}
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int can_act_dsx0BondingTable_row(struct dsx0BondingTable_data *StorageTmp)
 * @param StorageTmp the data (as updated)
 * @brief check whether an inactive table row can be activated
 *
 * This function is used by the ACTION phase of a RowStatus object to test whether an inactive table
 * row can be activated.  Returns SNMP_ERR_NOERROR when activation is permitted; an SNMP error
 * value, otherwise.  This function might use a 'test' operation against the driver to ensure that
 * the commit phase will succeed.
 */
int
can_act_dsx0BondingTable_row(struct dsx0BondingTable_data *StorageTmp)
{
	/* XXX: provide code to check whether the new or inactive table row can be activated */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int can_deact_dsx0BondingTable_row(struct dsx0BondingTable_data *StorageTmp)
 * @param StorageTmp the data (as updated)
 * @brief check whether an active table row can be deactivated
 *
 * This function is used by the ACTION phase of a RowStatus object to test whether an active table
 * row can be deactivated.  Returns SNMP_ERR_NOERROR when deactivation is permitted; an SNMP error
 * value, otherwise.  This function might use a 'test' operation against the driver to ensure that
 * the commit phase will succeed.
 */
int
can_deact_dsx0BondingTable_row(struct dsx0BondingTable_data *StorageTmp)
{
	/* XXX: provide code to check whether the active table row can be deactivated */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int can_act_dsx0BundleTable_row(struct dsx0BundleTable_data *StorageTmp)
 * @param StorageTmp the data (as updated)
 * @brief check whether an inactive table row can be activated
 *
 * This function is used by the ACTION phase of a RowStatus object to test whether an inactive table
 * row can be activated.  Returns SNMP_ERR_NOERROR when activation is permitted; an SNMP error
 * value, otherwise.  This function might use a 'test' operation against the driver to ensure that
 * the commit phase will succeed.
 */
int
can_act_dsx0BundleTable_row(struct dsx0BundleTable_data *StorageTmp)
{
	/* XXX: provide code to check whether the new or inactive table row can be activated */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int can_deact_dsx0BundleTable_row(struct dsx0BundleTable_data *StorageTmp)
 * @param StorageTmp the data (as updated)
 * @brief check whether an active table row can be deactivated
 *
 * This function is used by the ACTION phase of a RowStatus object to test whether an active table
 * row can be deactivated.  Returns SNMP_ERR_NOERROR when deactivation is permitted; an SNMP error
 * value, otherwise.  This function might use a 'test' operation against the driver to ensure that
 * the commit phase will succeed.
 */
int
can_deact_dsx0BundleTable_row(struct dsx0BundleTable_data *StorageTmp)
{
	/* XXX: provide code to check whether the active table row can be deactivated */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int write_dsx0BondRowStatus(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid *name, size_t name_len)
 * @param action the stage of the SET operation.
 * @param var_val pointer to the varbind value.
 * @param var_val_type the ASN type.
 * @param var_val_len the length of the varbind value.
 * @param statP static pointer.
 * @param name the varbind OID.
 * @param name_len number of elements in OID.
 * @brief Row status write routine.
 */
int
write_dsx0BondRowStatus(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	struct dsx0BondingTable_data *StorageTmp = NULL, *StorageOld = NULL;
	static struct dsx0BondingTable_data *StorageNew, *StorageDel;
	size_t newlen = name_len - 11;
	int set_value, ret;
	static struct variable_list *vars, *vp;

	DEBUGMSGTL(("ds0Bundle", "write_dsx0BondRowStatus entering action=%d...  \n", action));
	StorageTmp = header_complex(dsx0BondingTableStorage, NULL, &name[11], &newlen, 1, NULL, NULL);
	if (var_val_type != ASN_INTEGER || var_val == NULL) {
		snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0BondRowStatus not ASN_INTEGER\n");
		return SNMP_ERR_WRONGTYPE;
	}
	set_value = *((long *) var_val);
	/* check legal range, and notReady is reserved for us, not a user */
	if (set_value < 1 || set_value > 6 || set_value == RS_NOTREADY) {
		snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0BondRowStatus: bad value\n");
		return SNMP_ERR_WRONGVALUE;
	}
	switch (action) {
	case RESERVE1:
		/* stage one: test validity */
		StorageNew = StorageDel = NULL;
		vars = vp = NULL;
		switch (set_value) {
		case RS_CREATEANDGO:
		case RS_CREATEANDWAIT:
			if (StorageTmp != NULL)
				/* cannot create existing row */
				return SNMP_ERR_INCONSISTENTVALUE;
			/* creation */
			vars = NULL;
			/* ifIndex */
			if ((vp = snmp_varlist_add_variable(&vars, NULL, 0, ASN_INTEGER, NULL, 0)) == NULL) {
				snmp_free_varbind(vars);
				return SNMP_ERR_RESOURCEUNAVAILABLE;
			}
			if (header_complex_parse_oid(&(name[11]), newlen, vars) != SNMPERR_SUCCESS) {
				snmp_free_varbind(vars);
				return SNMP_ERR_INCONSISTENTNAME;
			}
			vp = vars;
			/* ifIndex */
			if (vp->val_len > sizeof(int32_t)) {
				snmp_log(MY_FACILITY(LOG_NOTICE), "index ifIndex: bad length\n");
				snmp_free_varbind(vars);
				return SNMP_ERR_INCONSISTENTNAME;
			}
			/* Note: ranges 1..2147483647 */
			if ((1 > (long) *vp->val.integer || (long) *vp->val.integer > 2147483647)) {
				snmp_log(MY_FACILITY(LOG_NOTICE), "index ifIndex: bad value\n");
				snmp_free_varbind(vars);
				return SNMP_ERR_INCONSISTENTNAME;
			}
			vp = vp->next_variable;
			if ((StorageNew = dsx0BondingTable_create()) == NULL) {
				snmp_free_varbind(vars);
				return SNMP_ERR_RESOURCEUNAVAILABLE;
			}
			StorageNew->dsx0BondingTable_rsvs = 1;
			vp = vars;
			StorageNew->ifIndex = (long) *vp->val.integer;
			vp = vp->next_variable;
			header_complex_add_data(&dsx0BondingTableStorage, vars, StorageNew);	/* frees vars */
			break;
		case RS_ACTIVE:
		case RS_NOTINSERVICE:
			if (StorageTmp == NULL)
				/* cannot change state of non-existent row */
				return SNMP_ERR_INCONSISTENTVALUE;
			if (StorageTmp->dsx0BondRowStatus == RS_NOTREADY)
				/* cannot change state of row that is not ready */
				return SNMP_ERR_INCONSISTENTVALUE;
			/* XXX: interaction with row storage type needed */
			if (set_value == RS_NOTINSERVICE && StorageTmp->dsx0BondingTable_refs > 0)
				/* row is busy and cannot be moved to the RS_NOTINSERVICE state */
				return SNMP_ERR_INCONSISTENTVALUE;
			/* activate or deactivate */
			if (StorageTmp == NULL)
				return SNMP_ERR_NOSUCHNAME;
			/* one allocation for the whole row */
			if ((StorageOld = StorageTmp->dsx0BondingTable_old) == NULL)
				if (StorageTmp->dsx0BondingTable_rsvs == 0)
					if ((StorageOld = StorageTmp->dsx0BondingTable_old = dsx0BondingTable_duplicate(StorageTmp)) == NULL)
						return SNMP_ERR_RESOURCEUNAVAILABLE;
			if (StorageOld != NULL)
				StorageTmp->dsx0BondingTable_rsvs++;
			break;
		case RS_DESTROY:
			if (StorageTmp == NULL)
				/* cannot destroy non-existent row */
				return SNMP_ERR_INCONSISTENTVALUE;
			/* XXX: interaction with row storage type needed */
			if (StorageTmp->dsx0BondingTable_refs > 0)
				/* row is busy and cannot be deleted */
				return SNMP_ERR_INCONSISTENTVALUE;
			/* destroy */
			if (StorageTmp != NULL) {
				/* exists, extract it for now */
				StorageDel = StorageTmp;
				dsx0BondingTable_del(StorageDel);
			} else {
				StorageDel = NULL;
			}
			break;
		case RS_NOTREADY:
			/* management station cannot set this, only agent can */
		default:
			return SNMP_ERR_INCONSISTENTVALUE;
		}
		break;
	case RESERVE2:
		/* memory reseveration, final preparation... */
		switch (set_value) {
		case RS_CREATEANDGO:
			/* check that activation is possible */
			if ((ret = can_act_dsx0BondingTable_row(StorageNew)) != SNMP_ERR_NOERROR)
				return (ret);
			break;
		case RS_CREATEANDWAIT:
			break;
		case RS_ACTIVE:
			/* check that activation is possible */
			if (StorageTmp->dsx0BondRowStatus != RS_ACTIVE)
				if ((ret = can_act_dsx0BondingTable_row(StorageTmp)) != SNMP_ERR_NOERROR)
					return (ret);
			break;
		case RS_NOTINSERVICE:
			/* check that deactivation is possible */
			if (StorageTmp->dsx0BondRowStatus != RS_NOTINSERVICE)
				if ((ret = can_deact_dsx0BondingTable_row(StorageTmp)) != SNMP_ERR_NOERROR)
					return (ret);
			break;
		case RS_DESTROY:
			/* check that deactivation is possible */
			if (StorageTmp->dsx0BondRowStatus != RS_NOTINSERVICE)
				if ((ret = can_deact_dsx0BondingTable_row(StorageTmp)) != SNMP_ERR_NOERROR)
					return (ret);
			break;
		default:
			return SNMP_ERR_WRONGVALUE;
		}
		break;
	case ACTION:
		/* The variable has been stored in StorageTmp->dsx0BondRowStatus for you to use, and you have just been asked to do something with it.  Note that anything done here must be reversable 
		   in the UNDO case */
		switch (set_value) {
		case RS_CREATEANDGO:
			/* activate with underlying device */
			if (activate_dsx0BondingTable_row(StorageNew) != SNMP_ERR_NOERROR)
				return SNMP_ERR_COMMITFAILED;
			break;
		case RS_CREATEANDWAIT:
			break;
		case RS_ACTIVE:
			/* state change already performed */
			if (StorageTmp->dsx0BondRowStatus != RS_ACTIVE) {
				/* activate with underlying device */
				if (activate_dsx0BondingTable_row(StorageTmp) != SNMP_ERR_NOERROR)
					return SNMP_ERR_COMMITFAILED;
			}
			break;
		case RS_NOTINSERVICE:
			/* state change already performed */
			if (StorageTmp->dsx0BondRowStatus != RS_NOTINSERVICE) {
				/* deactivate with underlying device */
				if (deactivate_dsx0BondingTable_row(StorageTmp) != SNMP_ERR_NOERROR)
					return SNMP_ERR_COMMITFAILED;
			}
			break;
		case RS_DESTROY:
			/* commit destrution to underlying device */
			if (StorageDel == NULL)
				break;
			/* deactivate with underlying device */
			if (deactivate_dsx0BondingTable_row(StorageDel) != SNMP_ERR_NOERROR)
				return SNMP_ERR_COMMITFAILED;
			break;
		default:
			return SNMP_ERR_WRONGVALUE;
		}
		break;
	case COMMIT:
		/* Things are working well, so it's now safe to make the change permanently.  Make sure that anything done here can't fail! */
		switch (set_value) {
		case RS_CREATEANDGO:
			StorageNew->dsx0BondRowStatus = RS_ACTIVE;
			break;
		case RS_CREATEANDWAIT:
			StorageNew->dsx0BondRowStatus = RS_NOTINSERVICE;
			break;
		case RS_ACTIVE:
		case RS_NOTINSERVICE:
			StorageNew->dsx0BondRowStatus = set_value;
			if ((StorageOld = StorageTmp->dsx0BondingTable_old) != NULL) {
				dsx0BondingTable_destroy(&StorageTmp->dsx0BondingTable_old);
				StorageTmp->dsx0BondingTable_rsvs = 0;
				StorageTmp->dsx0BondingTable_tsts = 0;
				StorageTmp->dsx0BondingTable_sets = 0;
			}
			break;
		case RS_DESTROY:
			dsx0BondingTable_destroy(&StorageDel);
			break;
		}
		break;
	case UNDO:
		/* Back out any changes made in the ACTION case */
		switch (set_value) {
		case RS_CREATEANDGO:
			/* deactivate with underlying device */
			deactivate_dsx0BondingTable_row(StorageNew);
			break;
		case RS_CREATEANDWAIT:
			break;
		case RS_ACTIVE:
			if (StorageTmp->dsx0BondRowStatus == RS_NOTINSERVICE)
				/* deactivate with underlying device */
				deactivate_dsx0BondingTable_row(StorageTmp);
			break;
		case RS_NOTINSERVICE:
			if (StorageTmp->dsx0BondRowStatus == RS_ACTIVE)
				/* activate with underlying device */
				activate_dsx0BondingTable_row(StorageTmp);
			break;
		case RS_DESTROY:
			break;
		}
		/* fall through */
	case FREE:
		/* Release any resources that have been allocated */
		switch (set_value) {
		case RS_CREATEANDGO:
		case RS_CREATEANDWAIT:
			/* creation */
			if (StorageNew) {
				dsx0BondingTable_del(StorageNew);
				dsx0BondingTable_destroy(&StorageNew);
			}
			break;
		case RS_ACTIVE:
		case RS_NOTINSERVICE:
			if ((StorageOld = StorageTmp->dsx0BondingTable_old) == NULL)
				break;
			if (--StorageTmp->dsx0BondingTable_rsvs == 0)
				dsx0BondingTable_destroy(&StorageTmp->dsx0BondingTable_old);
			break;
		case RS_DESTROY:
			/* row deletion, so add it again */
			if (StorageDel)
				dsx0BondingTable_add(StorageDel);
			break;
		}
		break;
	}
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int write_dsx0BundleRowStatus(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid *name, size_t name_len)
 * @param action the stage of the SET operation.
 * @param var_val pointer to the varbind value.
 * @param var_val_type the ASN type.
 * @param var_val_len the length of the varbind value.
 * @param statP static pointer.
 * @param name the varbind OID.
 * @param name_len number of elements in OID.
 * @brief Row status write routine.
 */
int
write_dsx0BundleRowStatus(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	struct dsx0BundleTable_data *StorageTmp = NULL, *StorageOld = NULL;
	static struct dsx0BundleTable_data *StorageNew, *StorageDel;
	size_t newlen = name_len - 11;
	int set_value, ret;
	static struct variable_list *vars, *vp;

	DEBUGMSGTL(("ds0Bundle", "write_dsx0BundleRowStatus entering action=%d...  \n", action));
	StorageTmp = header_complex(dsx0BundleTableStorage, NULL, &name[11], &newlen, 1, NULL, NULL);
	if (var_val_type != ASN_INTEGER || var_val == NULL) {
		snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0BundleRowStatus not ASN_INTEGER\n");
		return SNMP_ERR_WRONGTYPE;
	}
	set_value = *((long *) var_val);
	/* check legal range, and notReady is reserved for us, not a user */
	if (set_value < 1 || set_value > 6 || set_value == RS_NOTREADY) {
		snmp_log(MY_FACILITY(LOG_NOTICE), "write to dsx0BundleRowStatus: bad value\n");
		return SNMP_ERR_WRONGVALUE;
	}
	switch (action) {
	case RESERVE1:
		/* stage one: test validity */
		StorageNew = StorageDel = NULL;
		vars = vp = NULL;
		switch (set_value) {
		case RS_CREATEANDGO:
		case RS_CREATEANDWAIT:
			if (StorageTmp != NULL)
				/* cannot create existing row */
				return SNMP_ERR_INCONSISTENTVALUE;
			/* creation */
			vars = NULL;
			/* dsx0BundleIndex */
			if ((vp = snmp_varlist_add_variable(&vars, NULL, 0, ASN_INTEGER, NULL, 0)) == NULL) {
				snmp_free_varbind(vars);
				return SNMP_ERR_RESOURCEUNAVAILABLE;
			}
			if (header_complex_parse_oid(&(name[11]), newlen, vars) != SNMPERR_SUCCESS) {
				snmp_free_varbind(vars);
				return SNMP_ERR_INCONSISTENTNAME;
			}
			vp = vars;
			/* dsx0BundleIndex */
			if (vp->val_len > sizeof(int32_t)) {
				snmp_log(MY_FACILITY(LOG_NOTICE), "index dsx0BundleIndex: bad length\n");
				snmp_free_varbind(vars);
				return SNMP_ERR_INCONSISTENTNAME;
			}
			/* Note: ranges 0..2147483647 */
			if ((0 > (long) *vp->val.integer || (long) *vp->val.integer > 2147483647)) {
				snmp_log(MY_FACILITY(LOG_NOTICE), "index dsx0BundleIndex: bad value\n");
				snmp_free_varbind(vars);
				return SNMP_ERR_INCONSISTENTNAME;
			}
			vp = vp->next_variable;
			if ((StorageNew = dsx0BundleTable_create()) == NULL) {
				snmp_free_varbind(vars);
				return SNMP_ERR_RESOURCEUNAVAILABLE;
			}
			StorageNew->dsx0BundleTable_rsvs = 1;
			vp = vars;
			StorageNew->dsx0BundleIndex = (long) *vp->val.integer;
			vp = vp->next_variable;
			header_complex_add_data(&dsx0BundleTableStorage, vars, StorageNew);	/* frees vars */
			break;
		case RS_ACTIVE:
		case RS_NOTINSERVICE:
			if (StorageTmp == NULL)
				/* cannot change state of non-existent row */
				return SNMP_ERR_INCONSISTENTVALUE;
			if (StorageTmp->dsx0BundleRowStatus == RS_NOTREADY)
				/* cannot change state of row that is not ready */
				return SNMP_ERR_INCONSISTENTVALUE;
			/* XXX: interaction with row storage type needed */
			if (set_value == RS_NOTINSERVICE && StorageTmp->dsx0BundleTable_refs > 0)
				/* row is busy and cannot be moved to the RS_NOTINSERVICE state */
				return SNMP_ERR_INCONSISTENTVALUE;
			/* activate or deactivate */
			if (StorageTmp == NULL)
				return SNMP_ERR_NOSUCHNAME;
			/* one allocation for the whole row */
			if ((StorageOld = StorageTmp->dsx0BundleTable_old) == NULL)
				if (StorageTmp->dsx0BundleTable_rsvs == 0)
					if ((StorageOld = StorageTmp->dsx0BundleTable_old = dsx0BundleTable_duplicate(StorageTmp)) == NULL)
						return SNMP_ERR_RESOURCEUNAVAILABLE;
			if (StorageOld != NULL)
				StorageTmp->dsx0BundleTable_rsvs++;
			break;
		case RS_DESTROY:
			if (StorageTmp == NULL)
				/* cannot destroy non-existent row */
				return SNMP_ERR_INCONSISTENTVALUE;
			/* XXX: interaction with row storage type needed */
			if (StorageTmp->dsx0BundleTable_refs > 0)
				/* row is busy and cannot be deleted */
				return SNMP_ERR_INCONSISTENTVALUE;
			/* destroy */
			if (StorageTmp != NULL) {
				/* exists, extract it for now */
				StorageDel = StorageTmp;
				dsx0BundleTable_del(StorageDel);
			} else {
				StorageDel = NULL;
			}
			break;
		case RS_NOTREADY:
			/* management station cannot set this, only agent can */
		default:
			return SNMP_ERR_INCONSISTENTVALUE;
		}
		break;
	case RESERVE2:
		/* memory reseveration, final preparation... */
		switch (set_value) {
		case RS_CREATEANDGO:
			/* check that activation is possible */
			if ((ret = can_act_dsx0BundleTable_row(StorageNew)) != SNMP_ERR_NOERROR)
				return (ret);
			break;
		case RS_CREATEANDWAIT:
			break;
		case RS_ACTIVE:
			/* check that activation is possible */
			if (StorageTmp->dsx0BundleRowStatus != RS_ACTIVE)
				if ((ret = can_act_dsx0BundleTable_row(StorageTmp)) != SNMP_ERR_NOERROR)
					return (ret);
			break;
		case RS_NOTINSERVICE:
			/* check that deactivation is possible */
			if (StorageTmp->dsx0BundleRowStatus != RS_NOTINSERVICE)
				if ((ret = can_deact_dsx0BundleTable_row(StorageTmp)) != SNMP_ERR_NOERROR)
					return (ret);
			break;
		case RS_DESTROY:
			/* check that deactivation is possible */
			if (StorageTmp->dsx0BundleRowStatus != RS_NOTINSERVICE)
				if ((ret = can_deact_dsx0BundleTable_row(StorageTmp)) != SNMP_ERR_NOERROR)
					return (ret);
			break;
		default:
			return SNMP_ERR_WRONGVALUE;
		}
		break;
	case ACTION:
		/* The variable has been stored in StorageTmp->dsx0BundleRowStatus for you to use, and you have just been asked to do something with it.  Note that anything done here must be
		   reversable in the UNDO case */
		switch (set_value) {
		case RS_CREATEANDGO:
			/* activate with underlying device */
			if (activate_dsx0BundleTable_row(StorageNew) != SNMP_ERR_NOERROR)
				return SNMP_ERR_COMMITFAILED;
			break;
		case RS_CREATEANDWAIT:
			break;
		case RS_ACTIVE:
			/* state change already performed */
			if (StorageTmp->dsx0BundleRowStatus != RS_ACTIVE) {
				/* activate with underlying device */
				if (activate_dsx0BundleTable_row(StorageTmp) != SNMP_ERR_NOERROR)
					return SNMP_ERR_COMMITFAILED;
			}
			break;
		case RS_NOTINSERVICE:
			/* state change already performed */
			if (StorageTmp->dsx0BundleRowStatus != RS_NOTINSERVICE) {
				/* deactivate with underlying device */
				if (deactivate_dsx0BundleTable_row(StorageTmp) != SNMP_ERR_NOERROR)
					return SNMP_ERR_COMMITFAILED;
			}
			break;
		case RS_DESTROY:
			/* commit destrution to underlying device */
			if (StorageDel == NULL)
				break;
			/* deactivate with underlying device */
			if (deactivate_dsx0BundleTable_row(StorageDel) != SNMP_ERR_NOERROR)
				return SNMP_ERR_COMMITFAILED;
			break;
		default:
			return SNMP_ERR_WRONGVALUE;
		}
		break;
	case COMMIT:
		/* Things are working well, so it's now safe to make the change permanently.  Make sure that anything done here can't fail! */
		switch (set_value) {
		case RS_CREATEANDGO:
			StorageNew->dsx0BundleRowStatus = RS_ACTIVE;
			break;
		case RS_CREATEANDWAIT:
			StorageNew->dsx0BundleRowStatus = RS_NOTINSERVICE;
			break;
		case RS_ACTIVE:
		case RS_NOTINSERVICE:
			StorageNew->dsx0BundleRowStatus = set_value;
			if ((StorageOld = StorageTmp->dsx0BundleTable_old) != NULL) {
				dsx0BundleTable_destroy(&StorageTmp->dsx0BundleTable_old);
				StorageTmp->dsx0BundleTable_rsvs = 0;
				StorageTmp->dsx0BundleTable_tsts = 0;
				StorageTmp->dsx0BundleTable_sets = 0;
			}
			break;
		case RS_DESTROY:
			dsx0BundleTable_destroy(&StorageDel);
			break;
		}
		break;
	case UNDO:
		/* Back out any changes made in the ACTION case */
		switch (set_value) {
		case RS_CREATEANDGO:
			/* deactivate with underlying device */
			deactivate_dsx0BundleTable_row(StorageNew);
			break;
		case RS_CREATEANDWAIT:
			break;
		case RS_ACTIVE:
			if (StorageTmp->dsx0BundleRowStatus == RS_NOTINSERVICE)
				/* deactivate with underlying device */
				deactivate_dsx0BundleTable_row(StorageTmp);
			break;
		case RS_NOTINSERVICE:
			if (StorageTmp->dsx0BundleRowStatus == RS_ACTIVE)
				/* activate with underlying device */
				activate_dsx0BundleTable_row(StorageTmp);
			break;
		case RS_DESTROY:
			break;
		}
		/* fall through */
	case FREE:
		/* Release any resources that have been allocated */
		switch (set_value) {
		case RS_CREATEANDGO:
		case RS_CREATEANDWAIT:
			/* creation */
			if (StorageNew) {
				dsx0BundleTable_del(StorageNew);
				dsx0BundleTable_destroy(&StorageNew);
			}
			break;
		case RS_ACTIVE:
		case RS_NOTINSERVICE:
			if ((StorageOld = StorageTmp->dsx0BundleTable_old) == NULL)
				break;
			if (--StorageTmp->dsx0BundleTable_rsvs == 0)
				dsx0BundleTable_destroy(&StorageTmp->dsx0BundleTable_old);
			break;
		case RS_DESTROY:
			/* row deletion, so add it again */
			if (StorageDel)
				dsx0BundleTable_add(StorageDel);
			break;
		}
		break;
	}
	return SNMP_ERR_NOERROR;
}

/**
 * @fn void ds0Bundle_loop_handler(int dummy)
 * @param sig signal number
 * @brief handle event loop interation.
 *
 * This function is registered so that, when operating as a module, snmpd will call it one per event
 * loop interation.  This function is called before the next requst is processed and after the
 * previous request is processed.  Two things are done here:  1) The file descriptor that is used to
 * synchronize the agent with (pseudo-)device drivers is closed.  (Another approach, instead of
 * closing each time, would be to restart a timer each time that a request is made (loop is
 * performed) and if it expires, close the file descriptor).  2) The request number is incremented.
 * Although a request is not generated for each loop of the snmp event loop, it is true that a new
 * request cannot be generated without performing a loop.  Therefore, the sa_request is not the
 * request number but it is a temporally unique identifier for a request.
 */
void
ds0Bundle_loop_handler(int sig)
{
	DEBUGMSGTL(("ds0Bundle", "ds0Bundle_loop_handler: executing loop handler...  "));
	/* close files after each request */
	if (sa_fclose) {
		if (my_fd >= 0) {
			close(my_fd);
			my_fd = -1;
		}
	}
#if defined MASTER
	/* prepare for next request */
	sa_request++;
#endif				/* defined MASTER */
	if (external_signal_scheduled[sig] == 0)
		external_signal_scheduled[sig]--;
	if (ds0Bundleold_signal_handler != NULL)
		(*ds0Bundleold_signal_handler) (sig);
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
}

/**
 * @fn void ds0Bundle_fd_handler(int fd, void *dummy)
 * @param fd file descriptor to read.
 * @param dummy client data passed to registration function (always NULL).
 * @brief handle read event on file descriptor.
 *
 * This read file descriptor handler is normally used for (pseudo-)device drivers that generate
 * statistical collection interval events, alarm events, or other operational measurement events, by
 * placing a message on the read queue of the "event handling" Stream.  Normally this routine
 * would adjust counts in some table or scalars, generate SNMP traps representing on-occurence
 * events, first and interval events, and alarm indications.
 */
void
ds0Bundle_fd_handler(int fd, void *dummy)
{
	DEBUGMSGTL(("ds0Bundle", "ds0Bundle_fd_handler: executing fd handler...  "));
	/* XXX: place actions to handle my_fd here... */
	DEBUGMSGTL(("ds0Bundle", "done.\n"));
	return;
}
