/*****************************************************************************

 @(#) src/snmp/llcMIB.h

 -----------------------------------------------------------------------------

 Copyright (c) 2008-2015  Monavacon Limited <http://www.monavacon.com/>
 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; version 3 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 *****************************************************************************/

#ifndef __LOCAL_LLCMIB_H__
#define __LOCAL_LLCMIB_H__

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */

extern const char sa_program[];
extern int sa_fclose;			/* default close files between requests */
extern int sa_changed;			/* indication to reread MIB configuration */
extern int sa_stats_refresh;		/* indications that statistics, the mib or its tables need to be refreshed */
extern int sa_request;			/* request number for per-request actions */

/* our storage structure(s) */
struct llcMIB_data {
	struct llcMIB_data *llcMIB_old;
	uint llcMIB_rsvs;
	uint llcMIB_tsts;
	uint llcMIB_sets;
	uint llcMIB_request;
	long llcDiscontinuityTime;	/* ReadOnly */
	long lLCConnection2DefaultMaximumRetransmissions;	/* ReadWrite */
	long lLCConnection2DefaultReceivedWindowSize;	/* ReadWrite */
	long lLCConnection2DefaultSendWindowSize;	/* ReadWrite */
	long lLCConnection2DefaultAcknowledgeTimeoutValue;	/* ReadWrite */
	long lLCConnection2DefaultBusyStateTimeoutValue;	/* ReadWrite */
	long lLCConnection2DefaultPBitTimeoutValue;	/* ReadWrite */
	long lLCConnection2DefaultRejectTimeoutValue;	/* ReadWrite */
	uint8_t *lLCConnection2DefaultRoute;	/* ReadWrite */
	size_t lLCConnection2DefaultRouteLen;
	long lLCConnection2DefaultKStep;	/* ReadWrite */
	long lLCConnection2DefaultMaxSendWindowSize;	/* ReadWrite */
	long lLCConnection2DefaultOptionalTolerationIPDUs;	/* ReadWrite */
	long lLCConnectionlessAckDefaultMaximumLLCInformationFieldSize;	/* ReadWrite */
	long lLCConnectionlessAckDefaultMaximumRetransmissions;	/* ReadWrite */
};
struct mACDLETable_data {
	struct mACDLETable_data *mACDLETable_old;
	uint mACDLETable_rsvs;
	uint mACDLETable_tsts;
	uint mACDLETable_sets;
	uint mACDLETable_request;
	uint mACDLETable_refs;
	uint mACDLETable_id;
	uint8_t *mACDLECommunicationsEntityId;	/* NoAccess */
	size_t mACDLECommunicationsEntityIdLen;
	oid *mACDLELocalSapNames;	/* Create */
	size_t mACDLELocalSapNamesLen;
	long mACDLEOperationalState;	/* ReadOnly */
	oid *mACDLEProviderEntityNames;	/* Create */
	size_t mACDLEProviderEntityNamesLen;
	long mACDLERowStatus;		/* Create */
};
struct mACTable_data {
	struct mACTable_data *mACTable_old;
	uint mACTable_rsvs;
	uint mACTable_tsts;
	uint mACTable_sets;
	uint mACTable_request;
	uint mACTable_refs;
	uint mACTable_id;
	uint8_t *mACDLECommunicationsEntityId;	/* NoAccess */
	size_t mACDLECommunicationsEntityIdLen;
	long mACOperationalState;	/* ReadOnly */
	uint8_t *mACId;			/* NoAccess */
	size_t mACIdLen;
	long mACRowStatus;		/* Create */
};
struct resourceTypeIdTable_data {
	struct resourceTypeIdTable_data *resourceTypeIdTable_old;
	uint resourceTypeIdTable_rsvs;
	uint resourceTypeIdTable_tsts;
	uint resourceTypeIdTable_sets;
	uint resourceTypeIdTable_request;
	uint resourceTypeIdTable_refs;
	uint resourceTypeIdTable_id;
	uint8_t *mACDLECommunicationsEntityId;	/* NoAccess */
	size_t mACDLECommunicationsEntityIdLen;
	uint8_t *resourceTypeIdName;	/* ReadOnly */
	size_t resourceTypeIdNameLen;
	uint8_t *resourceInfoManufacturerOUI;	/* ReadOnly */
	size_t resourceInfoManufacturerOUILen;
	uint8_t *resourceInfoManufacturerName;	/* ReadOnly */
	size_t resourceInfoManufacturerNameLen;
	uint8_t *resourceInfoManufacturerProductName;	/* ReadOnly */
	size_t resourceInfoManufacturerProductNameLen;
	uint8_t *resourceInfoManufacturerProductVersion;	/* ReadOnly */
	size_t resourceInfoManufacturerProductVersionLen;
};
struct dLSAPTable_data {
	struct dLSAPTable_data *dLSAPTable_old;
	uint dLSAPTable_rsvs;
	uint dLSAPTable_tsts;
	uint dLSAPTable_sets;
	uint dLSAPTable_request;
	uint dLSAPTable_refs;
	uint dLSAPTable_id;
	uint8_t *mACDLECommunicationsEntityId;	/* NoAccess */
	size_t mACDLECommunicationsEntityIdLen;
	uint8_t *dLSAPSapId;		/* NoAccess */
	size_t dLSAPSapIdLen;
	long dLSAPSap1Address;		/* Create */
	oid *dLSAPUserEntityNames;	/* Create */
	size_t dLSAPUserEntityNamesLen;
	long dLSAPRowStatus;		/* Create */
};
struct lLCDLETable_data {
	struct lLCDLETable_data *lLCDLETable_old;
	uint lLCDLETable_rsvs;
	uint lLCDLETable_tsts;
	uint lLCDLETable_sets;
	uint lLCDLETable_request;
	uint lLCDLETable_refs;
	uint lLCDLETable_id;
	uint8_t *lLCDLECommunicationsEntityId;	/* NoAccess */
	size_t lLCDLECommunicationsEntityIdLen;
	oid *lLCDLELocalSapNames;	/* Create */
	size_t lLCDLELocalSapNamesLen;
	long lLCDLEOperationalState;	/* ReadOnly */
	oid *lLCDLEProviderEntityNames;	/* Create */
	size_t lLCDLEProviderEntityNamesLen;
	long lLCDLERowStatus;		/* Create */
};
struct lLCStationTable_data {
	struct lLCStationTable_data *lLCStationTable_old;
	uint lLCStationTable_rsvs;
	uint lLCStationTable_tsts;
	uint lLCStationTable_sets;
	uint lLCStationTable_request;
	uint lLCStationTable_refs;
	uint lLCStationTable_id;
	uint8_t *lLCDLECommunicationsEntityId;	/* NoAccess */
	size_t lLCDLECommunicationsEntityIdLen;
	uint8_t *dLSAPSapId;		/* NoAccess */
	size_t dLSAPSapIdLen;
	uint8_t *lLCStationLLCName;	/* ReadWrite */
	size_t lLCStationLLCNameLen;
	long lLCStationMaximumLSAPsConfigured;	/* ReadOnly */
	long lLCStationNumberOfActiveLSAPs;	/* ReadOnly */
	uint8_t *lLCStationSupportedServicesTypes;	/* ReadWrite */
	size_t lLCStationSupportedServicesTypesLen;
	long lLCStationStatus;		/* ReadOnly */
	long lLCStationType1AcknowledgeTimeoutValue;	/* ReadWrite */
	long lLCStationType1MaximumRetryCount;	/* ReadWrite */
	long lLCStationMaximumPDUN3;	/* ReadWrite */
	long lLCStationMaximumRetransmissions4;	/* ReadWrite */
	long lLCStationReceiveVariableLifetime;	/* ReadWrite */
	long lLCStationTransmitVariableLifetime;	/* ReadWrite */
	long lLCStationType3AcknowledgeTimeoutValue;	/* ReadWrite */
	long lLCStationType3Retransmissions;	/* ReadOnly */
	long lLCStationAvgBufferUseSize;	/* ReadOnly */
	long lLCStationBufferProblems;	/* ReadOnly */
	long lLCStationBufferSize;	/* ReadWrite */
	long lLCStationMaxBufferUseSize;	/* ReadOnly */
	long lLCStationInactiveLSAP;	/* ReadOnly */
	long lLCStationPDUsDiscard;	/* ReadOnly */
	uint8_t *lLCStationSTRIndicator;	/* ReadWrite */
	size_t lLCStationSTRIndicatorLen;
	long lLCStationVersionNumber;	/* ReadWrite */
	long lLCStationType1AcknowledgmentTimerTimeouts;	/* ReadOnly */
};
struct lLCSAPTable_data {
	struct lLCSAPTable_data *lLCSAPTable_old;
	uint lLCSAPTable_rsvs;
	uint lLCSAPTable_tsts;
	uint lLCSAPTable_sets;
	uint lLCSAPTable_request;
	uint lLCSAPTable_refs;
	uint lLCSAPTable_id;
	uint8_t *lLCDLECommunicationsEntityId;	/* NoAccess */
	size_t lLCDLECommunicationsEntityIdLen;
	uint8_t *dLSAPSapId;		/* NoAccess */
	size_t dLSAPSapIdLen;
	uint8_t *lLCSAPName;		/* NoAccess */
	size_t lLCSAPNameLen;
	uint8_t *lLCSAPAddress;		/* ReadOnly */
	size_t lLCSAPAddressLen;
	long lLCSAPRDE;			/* ReadOnly */
};
struct rDESetupTable_data {
	struct rDESetupTable_data *rDESetupTable_old;
	uint rDESetupTable_rsvs;
	uint rDESetupTable_tsts;
	uint rDESetupTable_sets;
	uint rDESetupTable_request;
	uint rDESetupTable_refs;
	uint rDESetupTable_id;
	uint8_t *lLCDLECommunicationsEntityId;	/* NoAccess */
	size_t lLCDLECommunicationsEntityIdLen;
	uint8_t *dLSAPSapId;		/* NoAccess */
	size_t dLSAPSapIdLen;
	long rDESetupAgingEnabled;	/* ReadWrite */
	long rDESetupAgingValue;	/* ReadWrite */
	long rDESetupEnableType2Reset;	/* ReadWrite */
	long rDESetupMaximumRouteDescriptors;	/* ReadWrite */
	long rDESetupMaximumResponseTime;	/* ReadWrite */
	long rDESetupMinimumPDUSize;	/* ReadWrite */
	long rDESetupRDEHold;		/* ReadWrite */
	long rDESetupRDEReplace;	/* ReadWrite */
	long rDESetupName;		/* ReadOnly */
	long rDESetupResetOnTestEnabled;	/* ReadWrite */
};
struct rDEPairTable_data {
	struct rDEPairTable_data *rDEPairTable_old;
	uint rDEPairTable_rsvs;
	uint rDEPairTable_tsts;
	uint rDEPairTable_sets;
	uint rDEPairTable_request;
	uint rDEPairTable_refs;
	uint rDEPairTable_id;
	uint8_t *lLCDLECommunicationsEntityId;	/* NoAccess */
	size_t lLCDLECommunicationsEntityIdLen;
	uint8_t *dLSAPSapId;		/* NoAccess */
	size_t dLSAPSapIdLen;
	uint8_t *rDEPairName;		/* NoAccess */
	size_t rDEPairNameLen;
	long rDEPairDiscardCounter;	/* ReadOnly */
	long rDEPairNSRPDUCounter;	/* ReadOnly */
	long rDEPairNSRSelectedCounter;	/* ReadOnly */
	uint8_t *rDEPairRIF;		/* ReadOnly */
	size_t rDEPairRIFLen;
	long rDEPairSRFPDUCounter;	/* ReadOnly */
	long rDEPairQueryCounter;	/* ReadOnly */
};
struct lLCCLPMTable_data {
	struct lLCCLPMTable_data *lLCCLPMTable_old;
	uint lLCCLPMTable_rsvs;
	uint lLCCLPMTable_tsts;
	uint lLCCLPMTable_sets;
	uint lLCCLPMTable_request;
	uint lLCCLPMTable_refs;
	uint lLCCLPMTable_id;
	uint8_t *lLCCLPMClProtocolMachineId;	/* NoAccess */
	size_t lLCCLPMClProtocolMachineIdLen;
	long lLCCLPMOperationalState;	/* ReadOnly */
	long lLCCLPMTotalRemoteSAPs;	/* ReadOnly */
	long lLCCLPMRowStatus;		/* Create */
};
struct lLCConnectionLessTable_data {
	struct lLCConnectionLessTable_data *lLCConnectionLessTable_old;
	uint lLCConnectionLessTable_rsvs;
	uint lLCConnectionLessTable_tsts;
	uint lLCConnectionLessTable_sets;
	uint lLCConnectionLessTable_request;
	uint lLCConnectionLessTable_refs;
	uint lLCConnectionLessTable_id;
	uint8_t *lLCCLPMClProtocolMachineId;	/* NoAccess */
	size_t lLCCLPMClProtocolMachineIdLen;
	uint8_t *lLCCLPMClProtocolMachineId;	/* NoAccess */
	size_t lLCCLPMClProtocolMachineIdLen;
	uint8_t *lLCConnectionlessName;	/* ReadWrite */
	size_t lLCConnectionlessNameLen;
	long lLCConnectionlessMaximumLLCInformationFieldSize;	/* ReadWrite */
	long lLCConnectionlessTESTReceivedABBResponse;	/* ReadOnly */
	long lLCConnectionlessTESTReceivedCommand;	/* ReadOnly */
	long lLCConnectionlessTESTReceivedResponse;	/* ReadOnly */
	long lLCConnectionlessTESTSentABBResponse;	/* ReadOnly */
	long lLCConnectionlessTESTSentCommand;	/* ReadOnly */
	long lLCConnectionlessTESTSentResponse;	/* ReadOnly */
	long lLCConnectionlessUIReceived;	/* ReadOnly */
	long lLCConnectionlessUISent;	/* ReadOnly */
	long lLCConnectionlessXIDReceivedCommand;	/* ReadOnly */
	long lLCConnectionlessXIDReceivedResponse;	/* ReadOnly */
	long lLCConnectionlessXIDSentCommand;	/* ReadOnly */
	long lLCConnectionlessXIDSentResponse;	/* ReadOnly */
};
struct lLCCOPMTable_data {
	struct lLCCOPMTable_data *lLCCOPMTable_old;
	uint lLCCOPMTable_rsvs;
	uint lLCCOPMTable_tsts;
	uint lLCCOPMTable_sets;
	uint lLCCOPMTable_request;
	uint lLCCOPMTable_refs;
	uint lLCCOPMTable_id;
	uint8_t *lLCCOPMCoProtocolMachineId;	/* NoAccess */
	size_t lLCCOPMCoProtocolMachineIdLen;
	long lLCCOPMOperationalState;	/* ReadOnly */
	long lLCCOPMRowStatus;		/* Create */
};
struct lLCConnection2Table_data {
	struct lLCConnection2Table_data *lLCConnection2Table_old;
	uint lLCConnection2Table_rsvs;
	uint lLCConnection2Table_tsts;
	uint lLCConnection2Table_sets;
	uint lLCConnection2Table_request;
	uint lLCConnection2Table_refs;
	uint lLCConnection2Table_id;
	uint8_t *lLCCOPMCoProtocolMachineId;	/* NoAccess */
	size_t lLCCOPMCoProtocolMachineIdLen;
	uint8_t *lLCCOPMCoProtocolMachineId;	/* NoAccess */
	size_t lLCCOPMCoProtocolMachineIdLen;
	uint8_t *lLCConnection2Name;	/* ReadWrite */
	size_t lLCConnection2NameLen;
	long lLCConnection2MaximumRetransmissions;	/* ReadWrite */
	long lLCConnection2ReceivedWindowSize;	/* ReadWrite */
	long lLCConnection2SendWindowSize;	/* ReadWrite */
	long lLCConnection2AcknowledgeTimeoutValue;	/* ReadWrite */
	long lLCConnection2BusyStateTimeoutValue;	/* ReadWrite */
	long lLCConnection2PBitTimeoutValue;	/* ReadWrite */
	long lLCConnection2RejectTimeoutValue;	/* ReadWrite */
	long lLCConnection2LocalBusy;	/* ReadOnly */
	long lLCConnection2RemoteBusy;	/* ReadOnly */
	long lLCConnection2RemoteReset;	/* ReadOnly */
	long lLCConnection2LocalReset;	/* ReadOnly */
	long lLCConnection2ProviderReset;	/* ReadOnly */
	uint8_t *lLCConnection2Route;	/* ReadWrite */
	size_t lLCConnection2RouteLen;
	long lLCConnection2KStep;	/* ReadWrite */
	long lLCConnection2MaxSendWindowSize;	/* ReadWrite */
	long lLCConnection2ReceivedI;	/* ReadOnly */
	long lLCConnection2SentI;	/* ReadOnly */
	long lLCConnection2SentAcks;	/* ReadOnly */
	long lLCConnection2ReceivedAcks;	/* ReadOnly */
	long lLCConnection2ReceivedFRMR;	/* ReadOnly */
	long lLCConnection2SentFRMR;	/* ReadOnly */
	long lLCConnection2ReceivedRR;	/* ReadOnly */
	long lLCConnection2SentRR;	/* ReadOnly */
	long lLCConnection2ReceivedRNR;	/* ReadOnly */
	long lLCConnection2SentRNR;	/* ReadOnly */
	long lLCConnection2ReceivedREJ;	/* ReadOnly */
	long lLCConnection2SentREJ;	/* ReadOnly */
	long lLCConnection2ReceivedSABME;	/* ReadOnly */
	long lLCConnection2SentSABME;	/* ReadOnly */
	long lLCConnection2ReceivedUA;	/* ReadOnly */
	long lLCConnection2SentUA;	/* ReadOnly */
	long lLCConnection2ReceivedDISC;	/* ReadOnly */
	long lLCConnection2SentDISC;	/* ReadOnly */
	long lLCConnection2ReceivedDM;	/* ReadOnly */
	long lLCConnection2SentDM;	/* ReadOnly */
	long lLCConnection2PDUsDiscarded1;	/* ReadOnly */
	long lLCConnection2PDUsDiscarded2;	/* ReadOnly */
	long lLCConnection2PDURetransmissions;	/* ReadOnly */
	long lLCConnection2OptionalTolerationIPDUs;	/* ReadWrite */
	long lLCConnection2DuplicateIPDUsReceived;	/* ReadOnly */
	long lLCConnection2Violation;	/* ReadOnly */
	long lLCConnection2ProtocolState;	/* ReadOnly */
	long lLCConnection2AdministrativeState;	/* ReadWrite */
	long lLCConnection2OperationalState;	/* ReadOnly */
	long lLCConnection2UsageState;	/* ReadOnly */
	uint8_t *lLCConnection2ProceduralStatus;	/* ReadOnly */
	size_t lLCConnection2ProceduralStatusLen;
	uint8_t *lLCConnection2AlarmStatus;	/* ReadWrite */
	size_t lLCConnection2AlarmStatusLen;
};
struct lLCConnection2IVMOTable_data {
	struct lLCConnection2IVMOTable_data *lLCConnection2IVMOTable_old;
	uint lLCConnection2IVMOTable_rsvs;
	uint lLCConnection2IVMOTable_tsts;
	uint lLCConnection2IVMOTable_sets;
	uint lLCConnection2IVMOTable_request;
	uint lLCConnection2IVMOTable_refs;
	uint lLCConnection2IVMOTable_id;
	uint8_t *lLCConnection2IVMOName;	/* NoAccess */
	size_t lLCConnection2IVMONameLen;
	ulong lLCConnection2IVMOMaximumRetransmissions;	/* ReadWrite */
	ulong lLCConnection2IVMOReceivedWindowSize;	/* ReadWrite */
	ulong lLCConnection2IVMOSendWindowSize;	/* ReadWrite */
	long lLCConnection2IVMOAcknowledgeTimeoutValue;	/* ReadWrite */
	long lLCConnection2IVMOBusyStateTimeoutValue;	/* ReadWrite */
	long lLCConnection2IVMOBitTimeoutValue;	/* ReadWrite */
	long lLCConnection2IVMORejectTimeoutValue;	/* ReadWrite */
	uint8_t *lLCConnection2IVMORoute;	/* ReadWrite */
	size_t lLCConnection2IVMORouteLen;
	ulong lLCConnection2IVMOKStep;	/* ReadWrite */
	ulong lLCConnection2IVMOMaxSendWindowSize;	/* ReadWrite */
	long lLCConnection2IVMOOptionalTolerationIPDUs;	/* ReadWrite */
};
struct lLCConnectionlessAckTable_data {
	struct lLCConnectionlessAckTable_data *lLCConnectionlessAckTable_old;
	uint lLCConnectionlessAckTable_rsvs;
	uint lLCConnectionlessAckTable_tsts;
	uint lLCConnectionlessAckTable_sets;
	uint lLCConnectionlessAckTable_request;
	uint lLCConnectionlessAckTable_refs;
	uint lLCConnectionlessAckTable_id;
	uint8_t *lLCCOPMCoProtocolMachineId;	/* NoAccess */
	size_t lLCCOPMCoProtocolMachineIdLen;
	uint8_t *lLCCOPMCoProtocolMachineId;	/* NoAccess */
	size_t lLCCOPMCoProtocolMachineIdLen;
	uint8_t *lLCConnectionlessAckName;	/* ReadOnly */
	size_t lLCConnectionlessAckNameLen;
	long lLCConnectionlessAckMaximumLLCInformationFieldSize;	/* ReadWrite */
	long lLCConnectionlessAckMaximumRetransmissions;	/* ReadWrite */
	long lLCConnectionlessAckTESTReceivedABBResponse;	/* ReadOnly */
	long lLCConnectionlessAckTESTReceivedCommand;	/* ReadOnly */
	long lLCConnectionlessAckTESTReceivedResponse;	/* ReadOnly */
	long lLCConnectionlessAckTESTSentABBResponse;	/* ReadOnly */
	long lLCConnectionlessAckTESTSentCommand;	/* ReadOnly */
	long lLCConnectionlessAckTESTSentResponse;	/* ReadOnly */
	long lLCConnectionlessAckReceiveResources;	/* ReadWrite */
	long lLCConnectionlessAckUIReceived;	/* ReadOnly */
	long lLCConnectionlessAckUISent;	/* ReadOnly */
	long lLCConnectionlessAckXIDReceivedCommand;	/* ReadOnly */
	long lLCConnectionlessAckXIDReceivedResponse;	/* ReadOnly */
	long lLCConnectionlessAckXIDSentCommand;	/* ReadOnly */
	long lLCConnectionlessAckXIDSentResponse;	/* ReadOnly */
	long lLCConnectionlessAckRetransmissions;	/* ReadOnly */
	long lLCConnectionlessAckNoResponse;	/* ReadOnly */
	long lLCConnectionlessAckCommandIP;	/* ReadOnly */
	long lLCConnectionlessAckCommandIT;	/* ReadOnly */
	long lLCConnectionlessAckCommandOK;	/* ReadOnly */
	long lLCConnectionlessAckCommandPE;	/* ReadOnly */
	long lLCConnectionlessAckCommandRS;	/* ReadOnly */
	long lLCConnectionlessAckCommandUE;	/* ReadOnly */
	long lLCConnectionlessAckCommandUN;	/* ReadOnly */
	long lLCConnectionlessAckReceivedACCommand;	/* ReadOnly */
	long lLCConnectionlessAckSentACCommand;	/* ReadOnly */
	long lLCConnectionlessAckResponseIP;	/* ReadOnly */
	long lLCConnectionlessAckResponseIT;	/* ReadOnly */
	long lLCConnectionlessAckResponseNE;	/* ReadOnly */
	long lLCConnectionlessAckResponseNR;	/* ReadOnly */
	long lLCConnectionlessAckResponseOK;	/* ReadOnly */
	long lLCConnectionlessAckResponseRS;	/* ReadOnly */
	long lLCConnectionlessAckResponseUE;	/* ReadOnly */
	long lLCConnectionlessAckResponseUN;	/* ReadOnly */
	long lLCConnectionlessAckViolation;	/* ReadOnly */
};
struct lLCConnectionlessAckIVMOTable_data {
	struct lLCConnectionlessAckIVMOTable_data *lLCConnectionlessAckIVMOTable_old;
	uint lLCConnectionlessAckIVMOTable_rsvs;
	uint lLCConnectionlessAckIVMOTable_tsts;
	uint lLCConnectionlessAckIVMOTable_sets;
	uint lLCConnectionlessAckIVMOTable_request;
	uint lLCConnectionlessAckIVMOTable_refs;
	uint lLCConnectionlessAckIVMOTable_id;
	uint8_t *lLCConnectionlessAckIVMOName;	/* NoAccess */
	size_t lLCConnectionlessAckIVMONameLen;
	long lLCConnectionlessAckIVMOMaximumLLCInformationFieldSize;	/* Create */
	long lLCConnectionlessAckIVMOMaximumRetransmissions;	/* Create */
	long lLCConnectionlessAckIVMORowStatus;	/* Create */
};

/* storage declarations */
extern struct llcMIB_data *llcMIBStorage;
extern struct header_complex_index *mACDLETableStorage;
extern struct header_complex_index *mACTableStorage;
extern struct header_complex_index *resourceTypeIdTableStorage;
extern struct header_complex_index *dLSAPTableStorage;
extern struct header_complex_index *lLCDLETableStorage;
extern struct header_complex_index *lLCStationTableStorage;
extern struct header_complex_index *lLCSAPTableStorage;
extern struct header_complex_index *rDESetupTableStorage;
extern struct header_complex_index *rDEPairTableStorage;
extern struct header_complex_index *lLCCLPMTableStorage;
extern struct header_complex_index *lLCConnectionLessTableStorage;
extern struct header_complex_index *lLCCOPMTableStorage;
extern struct header_complex_index *lLCConnection2TableStorage;
extern struct header_complex_index *lLCConnection2IVMOTableStorage;
extern struct header_complex_index *lLCConnectionlessAckTableStorage;
extern struct header_complex_index *lLCConnectionlessAckIVMOTableStorage;

/* enum definitions from the covered mib sections */

#define MACDLEOPERATIONALSTATE_DISABLED          0
#define MACDLEOPERATIONALSTATE_ENABLED           1

#define MACOPERATIONALSTATE_DISABLED             0
#define MACOPERATIONALSTATE_ENABLED              1

#define LLCDLEOPERATIONALSTATE_DISABLED          0
#define LLCDLEOPERATIONALSTATE_ENABLED           1

#define LLCSTATIONSUPPORTEDSERVICESTYPES_TYPE1   0
#define LLCSTATIONSUPPORTEDSERVICESTYPES_TYPE2   1
#define LLCSTATIONSUPPORTEDSERVICESTYPES_TYPE3INITIATE 2
#define LLCSTATIONSUPPORTEDSERVICESTYPES_TYPE3RECEIVEDATA 3
#define LLCSTATIONSUPPORTEDSERVICESTYPES_TYPE3RETURNDATA 4

#define LLCSTATIONSTATUS_UP                      0
#define LLCSTATIONSTATUS_DOWN                    1
#define LLCSTATIONSTATUS_OTHER                   2

#define LLCSTATIONSTRINDICATOR_NSR               0
#define LLCSTATIONSTRINDICATOR_STE               1

#define LLCSAPRDE_TRUE                           1
#define LLCSAPRDE_FALSE                          2

#define RDESETUPAGINGENABLED_TRUE                1
#define RDESETUPAGINGENABLED_FALSE               2

#define RDESETUPRDEHOLD_TRUE                     1
#define RDESETUPRDEHOLD_FALSE                    2

#define RDESETUPRDEREPLACE_TRUE                  1
#define RDESETUPRDEREPLACE_FALSE                 2

#define RDESETUPRESETONTESTENABLED_TRUE          1
#define RDESETUPRESETONTESTENABLED_FALSE         2

#define LLCCLPMOPERATIONALSTATE_DISABLED         0
#define LLCCLPMOPERATIONALSTATE_ENABLED          1

#define LLCCOPMOPERATIONALSTATE_DISABLED         0
#define LLCCOPMOPERATIONALSTATE_ENABLED          1

#define LLCCONNECTION2OPTIONALTOLERATIONIPDUS_TRUE 1
#define LLCCONNECTION2OPTIONALTOLERATIONIPDUS_FALSE 2

#define LLCCONNECTION2PROTOCOLSTATE_DISCONNECTEDPHASE 0
#define LLCCONNECTION2PROTOCOLSTATE_LINKDICONNECTIONPHASE 1
#define LLCCONNECTION2PROTOCOLSTATE_LINKSETUPPHASE 2
#define LLCCONNECTION2PROTOCOLSTATE_INFORMATIONTRANSFERPHASE 3
#define LLCCONNECTION2PROTOCOLSTATE_FRAMEREJECTCONDITION 4
#define LLCCONNECTION2PROTOCOLSTATE_BUSYCONDITION 5
#define LLCCONNECTION2PROTOCOLSTATE_SENTREJECTCONDITION 6
#define LLCCONNECTION2PROTOCOLSTATE_SYSTEMPARAMETERSANDERRORRECOVERY 7

#define LLCCONNECTION2ADMINISTRATIVESTATE_LOCKED 0
#define LLCCONNECTION2ADMINISTRATIVESTATE_UNLOCKED 1
#define LLCCONNECTION2ADMINISTRATIVESTATE_SHUTTINGDOWN 2

#define LLCCONNECTION2OPERATIONALSTATE_DISABLED  0
#define LLCCONNECTION2OPERATIONALSTATE_ENABLED   1

#define LLCCONNECTION2USAGESTATE_IDLE            0
#define LLCCONNECTION2USAGESTATE_ACTIVE          1
#define LLCCONNECTION2USAGESTATE_BUSY            2

#define LLCCONNECTION2PROCEDURALSTATUS_INITIALIZATIONREQUIRED 0
#define LLCCONNECTION2PROCEDURALSTATUS_NOTINITIALIZED 1
#define LLCCONNECTION2PROCEDURALSTATUS_INITIALIZING 2
#define LLCCONNECTION2PROCEDURALSTATUS_REPORTING 3
#define LLCCONNECTION2PROCEDURALSTATUS_TERMINATING 4

#define LLCCONNECTION2ALARMSTATUS_UNDERREPAIR    0
#define LLCCONNECTION2ALARMSTATUS_CRITICAL       1
#define LLCCONNECTION2ALARMSTATUS_MAJOR          2
#define LLCCONNECTION2ALARMSTATUS_MINOR          3
#define LLCCONNECTION2ALARMSTATUS_ALARMOUTSTANDING 4

#define LLCCONNECTION2IVMOOPTIONALTOLERATIONIPDUS_TRUE 1
#define LLCCONNECTION2IVMOOPTIONALTOLERATIONIPDUS_FALSE 2

#define LLCCONNECTIONLESSACKRECEIVERESOURCES_TRUE 1
#define LLCCONNECTIONLESSACKRECEIVERESOURCES_FALSE 2

#define LLCCONNECTION2DEFAULTOPTIONALTOLERATIONIPDUS_TRUE 1
#define LLCCONNECTION2DEFAULTOPTIONALTOLERATIONIPDUS_FALSE 2

/* notifications */
extern oid lLCConnection2Event_oid[11];
extern oid lLCClessACKEvent_oid[11];
extern oid lLCStationEvent_oid[11];

/* scalars accessible only for notify */
extern oid pdusDiscarded1_oid[12];
extern oid pdusDiscarded2_oid[12];
extern oid pduRetransmissions_oid[12];
extern oid acknowledgeTimeout_oid[12];
extern oid busyStateTimeout_oid[12];
extern oid rejectTimeout_oid[12];
extern oid pBitTimeout_oid[12];
extern oid type2Violation_oid[12];
extern oid retranmissions_oid[12];
extern oid type3Violation_oid[12];
extern oid noResponse_oid[12];
extern oid pdusDiscarded_oid[12];
extern oid bufferProblems_oid[12];

/* object id definitions */
extern oid macBasicMandatoryGroup_oid[12];
extern oid llcBasicMandatoryGroup_oid[12];
extern oid llcBasicConditionalGroup_oid[12];
extern oid llcBasicStatisticsGroup_oid[12];
extern oid llcBasicNotificationGroup_oid[12];
extern oid llcBasicParametersGroup_oid[12];
extern oid llcType1MandatoryGroup_oid[12];
extern oid llcType1StatisticsGroup_oid[12];
extern oid llcType2MandatoryGroup_oid[12];
extern oid llcType2ConditionalGroup_oid[12];
extern oid llcType2StatisticsGroup_oid[12];
extern oid llcType2InitialValuesGroup_oid[12];
extern oid llcType2InitialValueDefaultsGroup_oid[12];
extern oid llcType2NotificationGroup_oid[12];
extern oid llcType2ParametersGroup_oid[12];
extern oid llcType2RDEConditionalGroup_oid[12];
extern oid llcType3MandatoryGroup_oid[12];
extern oid llcType3ConditionalGroup_oid[12];
extern oid llcType3StatisticsGroup_oid[12];
extern oid llcType3NotificationGroup_oid[12];
extern oid llcType3ParametersGroup_oid[12];
extern oid llcType3IntialValuesGroup_oid[12];
extern oid llcType3InitialValueDefaultsGroup_oid[12];
extern oid llcTmnStateGroup_oid[12];
extern oid llcMIBCompliance_oid[12];

/* function prototypes */
/* trap function prototypes */
extern void send_lLCConnection2Event_v2trap(struct variable_list *);
extern void send_lLCClessACKEvent_v2trap(struct variable_list *);
extern void send_lLCStationEvent_v2trap(struct variable_list *);

/* variable function prototypes */
void init_llcMIB(void);
void deinit_llcMIB(void);
int term_llcMIB(int majorID, int minorID, void *serverarg, void *clientarg);
FindVarMethod var_llcMIB;
struct llcMIB_data *llcMIB_create(void);
struct llcMIB_data *llcMIB_duplicate(struct llcMIB_data *);
int llcMIB_destroy(struct llcMIB_data **);
int llcMIB_add(struct llcMIB_data *);
void parse_llcMIB(const char *, char *);
SNMPCallback store_llcMIB;
void refresh_llcMIB(int);
FindVarMethod var_mACDLETable;
struct mACDLETable_data *mACDLETable_create(void);
struct mACDLETable_data *mACDLETable_duplicate(struct mACDLETable_data *);
int mACDLETable_destroy(struct mACDLETable_data **);
int mACDLETable_add(struct mACDLETable_data *);
int mACDLETable_del(struct mACDLETable_data *);
void parse_mACDLETable(const char *, char *);
SNMPCallback store_mACDLETable;
void refresh_mACDLETable(int);
FindVarMethod var_mACTable;
struct mACTable_data *mACTable_create(void);
struct mACTable_data *mACTable_duplicate(struct mACTable_data *);
int mACTable_destroy(struct mACTable_data **);
int mACTable_add(struct mACTable_data *);
int mACTable_del(struct mACTable_data *);
void parse_mACTable(const char *, char *);
SNMPCallback store_mACTable;
void refresh_mACTable(int);
FindVarMethod var_resourceTypeIdTable;
struct resourceTypeIdTable_data *resourceTypeIdTable_create(void);
struct resourceTypeIdTable_data *resourceTypeIdTable_duplicate(struct resourceTypeIdTable_data *);
int resourceTypeIdTable_destroy(struct resourceTypeIdTable_data **);
int resourceTypeIdTable_add(struct resourceTypeIdTable_data *);
int resourceTypeIdTable_del(struct resourceTypeIdTable_data *);
void parse_resourceTypeIdTable(const char *, char *);
SNMPCallback store_resourceTypeIdTable;
void refresh_resourceTypeIdTable(int);
FindVarMethod var_dLSAPTable;
struct dLSAPTable_data *dLSAPTable_create(void);
struct dLSAPTable_data *dLSAPTable_duplicate(struct dLSAPTable_data *);
int dLSAPTable_destroy(struct dLSAPTable_data **);
int dLSAPTable_add(struct dLSAPTable_data *);
int dLSAPTable_del(struct dLSAPTable_data *);
void parse_dLSAPTable(const char *, char *);
SNMPCallback store_dLSAPTable;
void refresh_dLSAPTable(int);
FindVarMethod var_lLCDLETable;
struct lLCDLETable_data *lLCDLETable_create(void);
struct lLCDLETable_data *lLCDLETable_duplicate(struct lLCDLETable_data *);
int lLCDLETable_destroy(struct lLCDLETable_data **);
int lLCDLETable_add(struct lLCDLETable_data *);
int lLCDLETable_del(struct lLCDLETable_data *);
void parse_lLCDLETable(const char *, char *);
SNMPCallback store_lLCDLETable;
void refresh_lLCDLETable(int);
FindVarMethod var_lLCStationTable;
struct lLCStationTable_data *lLCStationTable_create(void);
struct lLCStationTable_data *lLCStationTable_duplicate(struct lLCStationTable_data *);
int lLCStationTable_destroy(struct lLCStationTable_data **);
int lLCStationTable_add(struct lLCStationTable_data *);
int lLCStationTable_del(struct lLCStationTable_data *);
void parse_lLCStationTable(const char *, char *);
SNMPCallback store_lLCStationTable;
void refresh_lLCStationTable(int);
FindVarMethod var_lLCSAPTable;
struct lLCSAPTable_data *lLCSAPTable_create(void);
struct lLCSAPTable_data *lLCSAPTable_duplicate(struct lLCSAPTable_data *);
int lLCSAPTable_destroy(struct lLCSAPTable_data **);
int lLCSAPTable_add(struct lLCSAPTable_data *);
int lLCSAPTable_del(struct lLCSAPTable_data *);
void parse_lLCSAPTable(const char *, char *);
SNMPCallback store_lLCSAPTable;
void refresh_lLCSAPTable(int);
FindVarMethod var_rDESetupTable;
struct rDESetupTable_data *rDESetupTable_create(void);
struct rDESetupTable_data *rDESetupTable_duplicate(struct rDESetupTable_data *);
int rDESetupTable_destroy(struct rDESetupTable_data **);
int rDESetupTable_add(struct rDESetupTable_data *);
int rDESetupTable_del(struct rDESetupTable_data *);
void parse_rDESetupTable(const char *, char *);
SNMPCallback store_rDESetupTable;
void refresh_rDESetupTable(int);
FindVarMethod var_rDEPairTable;
struct rDEPairTable_data *rDEPairTable_create(void);
struct rDEPairTable_data *rDEPairTable_duplicate(struct rDEPairTable_data *);
int rDEPairTable_destroy(struct rDEPairTable_data **);
int rDEPairTable_add(struct rDEPairTable_data *);
int rDEPairTable_del(struct rDEPairTable_data *);
void parse_rDEPairTable(const char *, char *);
SNMPCallback store_rDEPairTable;
void refresh_rDEPairTable(int);
FindVarMethod var_lLCCLPMTable;
struct lLCCLPMTable_data *lLCCLPMTable_create(void);
struct lLCCLPMTable_data *lLCCLPMTable_duplicate(struct lLCCLPMTable_data *);
int lLCCLPMTable_destroy(struct lLCCLPMTable_data **);
int lLCCLPMTable_add(struct lLCCLPMTable_data *);
int lLCCLPMTable_del(struct lLCCLPMTable_data *);
void parse_lLCCLPMTable(const char *, char *);
SNMPCallback store_lLCCLPMTable;
void refresh_lLCCLPMTable(int);
FindVarMethod var_lLCConnectionLessTable;
struct lLCConnectionLessTable_data *lLCConnectionLessTable_create(void);
struct lLCConnectionLessTable_data *lLCConnectionLessTable_duplicate(struct lLCConnectionLessTable_data *);
int lLCConnectionLessTable_destroy(struct lLCConnectionLessTable_data **);
int lLCConnectionLessTable_add(struct lLCConnectionLessTable_data *);
int lLCConnectionLessTable_del(struct lLCConnectionLessTable_data *);
void parse_lLCConnectionLessTable(const char *, char *);
SNMPCallback store_lLCConnectionLessTable;
void refresh_lLCConnectionLessTable(int);
FindVarMethod var_lLCCOPMTable;
struct lLCCOPMTable_data *lLCCOPMTable_create(void);
struct lLCCOPMTable_data *lLCCOPMTable_duplicate(struct lLCCOPMTable_data *);
int lLCCOPMTable_destroy(struct lLCCOPMTable_data **);
int lLCCOPMTable_add(struct lLCCOPMTable_data *);
int lLCCOPMTable_del(struct lLCCOPMTable_data *);
void parse_lLCCOPMTable(const char *, char *);
SNMPCallback store_lLCCOPMTable;
void refresh_lLCCOPMTable(int);
FindVarMethod var_lLCConnection2Table;
struct lLCConnection2Table_data *lLCConnection2Table_create(void);
struct lLCConnection2Table_data *lLCConnection2Table_duplicate(struct lLCConnection2Table_data *);
int lLCConnection2Table_destroy(struct lLCConnection2Table_data **);
int lLCConnection2Table_add(struct lLCConnection2Table_data *);
int lLCConnection2Table_del(struct lLCConnection2Table_data *);
void parse_lLCConnection2Table(const char *, char *);
SNMPCallback store_lLCConnection2Table;
void refresh_lLCConnection2Table(int);
FindVarMethod var_lLCConnection2IVMOTable;
struct lLCConnection2IVMOTable_data *lLCConnection2IVMOTable_create(void);
struct lLCConnection2IVMOTable_data *lLCConnection2IVMOTable_duplicate(struct lLCConnection2IVMOTable_data *);
int lLCConnection2IVMOTable_destroy(struct lLCConnection2IVMOTable_data **);
int lLCConnection2IVMOTable_add(struct lLCConnection2IVMOTable_data *);
int lLCConnection2IVMOTable_del(struct lLCConnection2IVMOTable_data *);
void parse_lLCConnection2IVMOTable(const char *, char *);
SNMPCallback store_lLCConnection2IVMOTable;
void refresh_lLCConnection2IVMOTable(int);
FindVarMethod var_lLCConnectionlessAckTable;
struct lLCConnectionlessAckTable_data *lLCConnectionlessAckTable_create(void);
struct lLCConnectionlessAckTable_data *lLCConnectionlessAckTable_duplicate(struct lLCConnectionlessAckTable_data *);
int lLCConnectionlessAckTable_destroy(struct lLCConnectionlessAckTable_data **);
int lLCConnectionlessAckTable_add(struct lLCConnectionlessAckTable_data *);
int lLCConnectionlessAckTable_del(struct lLCConnectionlessAckTable_data *);
void parse_lLCConnectionlessAckTable(const char *, char *);
SNMPCallback store_lLCConnectionlessAckTable;
void refresh_lLCConnectionlessAckTable(int);
FindVarMethod var_lLCConnectionlessAckIVMOTable;
struct lLCConnectionlessAckIVMOTable_data *lLCConnectionlessAckIVMOTable_create(void);
struct lLCConnectionlessAckIVMOTable_data *lLCConnectionlessAckIVMOTable_duplicate(struct lLCConnectionlessAckIVMOTable_data *);
int lLCConnectionlessAckIVMOTable_destroy(struct lLCConnectionlessAckIVMOTable_data **);
int lLCConnectionlessAckIVMOTable_add(struct lLCConnectionlessAckIVMOTable_data *);
int lLCConnectionlessAckIVMOTable_del(struct lLCConnectionlessAckIVMOTable_data *);
void parse_lLCConnectionlessAckIVMOTable(const char *, char *);
SNMPCallback store_lLCConnectionlessAckIVMOTable;
void refresh_lLCConnectionlessAckIVMOTable(int);

WriteMethod write_mACDLELocalSapNames;
WriteMethod write_mACDLEProviderEntityNames;
WriteMethod write_mACDLERowStatus;
WriteMethod write_mACRowStatus;
WriteMethod write_dLSAPSap1Address;
WriteMethod write_dLSAPUserEntityNames;
WriteMethod write_dLSAPRowStatus;
WriteMethod write_lLCDLELocalSapNames;
WriteMethod write_lLCDLEProviderEntityNames;
WriteMethod write_lLCDLERowStatus;
WriteMethod write_lLCStationLLCName;
WriteMethod write_lLCStationSupportedServicesTypes;
WriteMethod write_lLCStationType1AcknowledgeTimeoutValue;
WriteMethod write_lLCStationType1MaximumRetryCount;
WriteMethod write_lLCStationMaximumPDUN3;
WriteMethod write_lLCStationMaximumRetransmissions4;
WriteMethod write_lLCStationReceiveVariableLifetime;
WriteMethod write_lLCStationTransmitVariableLifetime;
WriteMethod write_lLCStationType3AcknowledgeTimeoutValue;
WriteMethod write_lLCStationBufferSize;
WriteMethod write_lLCStationSTRIndicator;
WriteMethod write_lLCStationVersionNumber;
WriteMethod write_rDESetupAgingEnabled;
WriteMethod write_rDESetupAgingValue;
WriteMethod write_rDESetupEnableType2Reset;
WriteMethod write_rDESetupMaximumRouteDescriptors;
WriteMethod write_rDESetupMaximumResponseTime;
WriteMethod write_rDESetupMinimumPDUSize;
WriteMethod write_rDESetupRDEHold;
WriteMethod write_rDESetupRDEReplace;
WriteMethod write_rDESetupResetOnTestEnabled;
WriteMethod write_lLCCLPMRowStatus;
WriteMethod write_lLCConnectionlessName;
WriteMethod write_lLCConnectionlessMaximumLLCInformationFieldSize;
WriteMethod write_lLCCOPMRowStatus;
WriteMethod write_lLCConnection2Name;
WriteMethod write_lLCConnection2MaximumRetransmissions;
WriteMethod write_lLCConnection2ReceivedWindowSize;
WriteMethod write_lLCConnection2SendWindowSize;
WriteMethod write_lLCConnection2AcknowledgeTimeoutValue;
WriteMethod write_lLCConnection2BusyStateTimeoutValue;
WriteMethod write_lLCConnection2PBitTimeoutValue;
WriteMethod write_lLCConnection2RejectTimeoutValue;
WriteMethod write_lLCConnection2Route;
WriteMethod write_lLCConnection2KStep;
WriteMethod write_lLCConnection2MaxSendWindowSize;
WriteMethod write_lLCConnection2OptionalTolerationIPDUs;
WriteMethod write_lLCConnection2AdministrativeState;
WriteMethod write_lLCConnection2AlarmStatus;
WriteMethod write_lLCConnection2IVMOMaximumRetransmissions;
WriteMethod write_lLCConnection2IVMOReceivedWindowSize;
WriteMethod write_lLCConnection2IVMOSendWindowSize;
WriteMethod write_lLCConnection2IVMOAcknowledgeTimeoutValue;
WriteMethod write_lLCConnection2IVMOBusyStateTimeoutValue;
WriteMethod write_lLCConnection2IVMOBitTimeoutValue;
WriteMethod write_lLCConnection2IVMORejectTimeoutValue;
WriteMethod write_lLCConnection2IVMORoute;
WriteMethod write_lLCConnection2IVMOKStep;
WriteMethod write_lLCConnection2IVMOMaxSendWindowSize;
WriteMethod write_lLCConnection2IVMOOptionalTolerationIPDUs;
WriteMethod write_lLCConnectionlessAckMaximumLLCInformationFieldSize;
WriteMethod write_lLCConnectionlessAckMaximumRetransmissions;
WriteMethod write_lLCConnectionlessAckReceiveResources;
WriteMethod write_lLCConnectionlessAckIVMOMaximumLLCInformationFieldSize;
WriteMethod write_lLCConnectionlessAckIVMOMaximumRetransmissions;
WriteMethod write_lLCConnectionlessAckIVMORowStatus;
WriteMethod write_lLCConnection2DefaultMaximumRetransmissions;
WriteMethod write_lLCConnection2DefaultReceivedWindowSize;
WriteMethod write_lLCConnection2DefaultSendWindowSize;
WriteMethod write_lLCConnection2DefaultAcknowledgeTimeoutValue;
WriteMethod write_lLCConnection2DefaultBusyStateTimeoutValue;
WriteMethod write_lLCConnection2DefaultPBitTimeoutValue;
WriteMethod write_lLCConnection2DefaultRejectTimeoutValue;
WriteMethod write_lLCConnection2DefaultRoute;
WriteMethod write_lLCConnection2DefaultKStep;
WriteMethod write_lLCConnection2DefaultMaxSendWindowSize;
WriteMethod write_lLCConnection2DefaultOptionalTolerationIPDUs;
WriteMethod write_lLCConnectionlessAckDefaultMaximumLLCInformationFieldSize;
WriteMethod write_lLCConnectionlessAckDefaultMaximumRetransmissions;
#endif				/* __LOCAL_LLCMIB_H__ */
