/*****************************************************************************

 @(#) src/snmp/m2paMIB.h

 -----------------------------------------------------------------------------

 Copyright (c) 2008-2015  Monavacon Limited <http://www.monavacon.com/>
 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; version 3 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 *****************************************************************************/

#ifndef __LOCAL_M2PAMIB_H__
#define __LOCAL_M2PAMIB_H__

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */

extern const char sa_program[];
extern int sa_fclose;			/* default close files between requests */
extern int sa_changed;			/* indication to reread MIB configuration */
extern int sa_stats_refresh;		/* indications that statistics, the mib or its tables need to be refreshed */
extern int sa_request;			/* request number for per-request actions */

/* our storage structure(s) */
struct m2paMIB_data {
	uint m2paMIB_request;
	long m2paDefaultSctpNoDelay;	/* ReadWrite */
	ulong m2paDefaultSctpMaxseg;	/* ReadWrite */
	long m2paDefaultSctpHeartbeatItvl;	/* ReadWrite */
	long m2paDefaultSctpHeartbeat;	/* ReadWrite */
	long m2paDefaultSctpRtoInitial;	/* ReadWrite */
	long m2paDefaultSctpRtoMin;	/* ReadWrite */
	long m2paDefaultSctpRtoMax;	/* ReadWrite */
	ulong m2paDefaultSctpPathMaxRetrans;	/* ReadWrite */
	long m2paDefaultSctpCookieLife;	/* ReadWrite */
	long m2paDefaultSctpCookieInc;	/* ReadWrite */
	ulong m2paDefaultSctpMaxInitRetries;	/* ReadWrite */
	ulong m2paDefaultSctpMaxBurst;	/* ReadWrite */
	ulong m2paDefaultSctpAssocMaxRetrans;	/* ReadWrite */
	long m2paDefaultSctpSackDelay;	/* ReadWrite */
	long m2paDefaultSctpLifetime;	/* ReadWrite */
};
struct m2paProtocolProfileTable_data {
	uint m2paProtocolProfileTable_request;
	uint m2paProtocolProfileTable_refs;
	uint8_t *m2paProtocolProfileId;	/* NoAccess */
	size_t m2paProtocolProfileIdLen;
	ulong m2paN1;			/* Create */
	long m2paProving;		/* Create */
	long m2paManagementProvingState;	/* Create */
	long m2paLoopDelayLower;	/* Create */
	long m2paLoopDelayUpper;	/* Create */
	ulong m2paTransmissionRateIntervalLower;	/* Create */
	ulong m2paTransmissionRateIntervalUpper;	/* Create */
	long m2paSctpNoDelay;		/* Create */
	ulong m2paSctpMaxseg;		/* Create */
	long m2paSctpHeartbeatItvl;	/* Create */
	long m2paSctpHeartbeat;		/* Create */
	long m2paSctpRtoInitial;	/* Create */
	long m2paSctpRtoMin;		/* Create */
	long m2paSctpRtoMax;		/* Create */
	ulong m2paSctpPathMaxRetrans;	/* Create */
	long m2paSctpCookieLife;	/* Create */
	long m2paSctpCookieInc;		/* Create */
	ulong m2paSctpMaxInitRetries;	/* Create */
	ulong m2paSctpMaxBurst;		/* Create */
	ulong m2paSctpAssocMaxRetrans;	/* Create */
	long m2paSctpSackDelay;		/* Create */
	long m2paSctpLifetime;		/* Create */
	long m2paTimerT1;		/* Create */
	long m2paTimerT2;		/* Create */
	long m2paTimerT2L;		/* Create */
	long m2paTimerT2H;		/* Create */
	long m2paTimerT3;		/* Create */
	long m2paTimerT4N;		/* Create */
	long m2paTimerT4E;		/* Create */
	long m2paTimerT6;		/* Create */
	long m2paTimerT7;		/* Create */
	ulong m2paTransCongThresholdAbatementL1Messages;	/* Create */
	ulong m2paTransCongThresholdAbatementL1Octets;	/* Create */
	ulong m2paTransCongThresholdOnsetL1Messages;	/* Create */
	ulong m2paTransCongThresholdOnsetL1Octets;	/* Create */
	ulong m2paProvingAttempts;	/* Create */
	ulong m2paNumberOfThresholdLevels;	/* Create */
	long m2paCongestionCounting;	/* Create */
	long m2paCongestionReportingBaseObject;	/* Create */
	long m2paTimerTx;		/* Create */
	long m2paTimerTy;		/* Create */
	ulong m2paNumberOfCongestionStates;	/* Create */
	ulong m2paInitialLevelOfCongestion;	/* Create */
	ulong m2paReceiveCongestionThresholdAbatement;	/* Create */
	ulong m2paReceiveCongestionThresholdOnset;	/* Create */
	ulong m2paReceiveCongestionThresholdDiscard;	/* Create */
	uint8_t *m2paProtocolProfileName;	/* Create */
	size_t m2paProtocolProfileNameLen;
	ulong m2paTransCongThresholdAbatementL2Messages;	/* Create */
	ulong m2paTransCongThresholdAbatementL2Octets;	/* Create */
	ulong m2paTransCongThresholdOnsetL2Messages;	/* Create */
	ulong m2paTransCongThresholdOnsetL2Octets;	/* Create */
	ulong m2paTransCongThresholdAbatementL3Messages;	/* Create */
	ulong m2paTransCongThresholdAbatementL3Octets;	/* Create */
	ulong m2paTransCongThresholdOnsetL3Messages;	/* Create */
	ulong m2paTransCongThresholdOnsetL3Octets;	/* Create */
	ulong m2paTransCongThresholdDiscardL1Messages;	/* Create */
	ulong m2paTransCongThresholdDiscardL1Octets;	/* Create */
	ulong m2paTransCongThresholdDiscardL2Messages;	/* Create */
	ulong m2paTransCongThresholdDiscardL2Octets;	/* Create */
	ulong m2paTransCongThresholdDiscardL3Messages;	/* Create */
	ulong m2paTransCongThresholdDiscardL3Octets;	/* Create */
	long m2paProtocolProfileRowStatus;	/* Create */
};

/* storage declarations */
extern struct m2paMIB_data *m2paMIBStorage;
extern struct header_complex_index *m2paProtocolProfileTableStorage;

/* enum definitions from the covered mib sections */

#define M2PAPROVING_TRUE                         1
#define M2PAPROVING_FALSE                        2

#define M2PAMANAGEMENTPROVINGSTATE_NORMAL        0
#define M2PAMANAGEMENTPROVINGSTATE_EMERGENCY     1
#define M2PAMANAGEMENTPROVINGSTATE_NEUTRAL       2

#define M2PASCTPNODELAY_TRUE                     1
#define M2PASCTPNODELAY_FALSE                    2

#define M2PASCTPHEARTBEAT_TRUE                   1
#define M2PASCTPHEARTBEAT_FALSE                  2

#define M2PACONGESTIONCOUNTING_OCTET             0
#define M2PACONGESTIONCOUNTING_MESSAGE           1
#define M2PACONGESTIONCOUNTING_BOTH              2

#define M2PACONGESTIONREPORTINGBASEOBJECT_ROUTESET 0
#define M2PACONGESTIONREPORTINGBASEOBJECT_LINKSETOFCONGESTEDROUTESET 1
#define M2PACONGESTIONREPORTINGBASEOBJECT_LINKOFCONGESTEDROUTESET 2
#define M2PACONGESTIONREPORTINGBASEOBJECT_CONGESTEDLINKOFCONGESTEDROUTE 3

#define M2PADEFAULTSCTPNODELAY_TRUE              1
#define M2PADEFAULTSCTPNODELAY_FALSE             2

#define M2PADEFAULTSCTPHEARTBEAT_TRUE            1
#define M2PADEFAULTSCTPHEARTBEAT_FALSE           2

/* notifications */

/* scalars accessible only for notify */

/* object id definitions */
extern oid m2paFullCompliance_oid[12];
extern oid m2paCompliance_oid[12];
extern oid m2paBasicCongestionCompliance_oid[12];
extern oid m2paMultipleCongestionStatesCompliance_oid[12];
extern oid m2paMultipleCongestionLevelsCompliance_oid[12];
extern oid m2paMultipleCongestionLeveslWithMessagePriorityCompliance_oid[12];
extern oid m2paObjectGroup_oid[12];
extern oid m2paBasicSS7Group_oid[12];
extern oid m2paBasicSS7TransmitCongestionPackage_oid[12];
extern oid m2paBasicSCTPGroup_oid[12];
extern oid m2paProvingPackage_oid[12];
extern oid m2paBufferMechanismPackage_oid[12];
extern oid m2paCongestionHandlingPackage_oid[12];
extern oid m2paMultipleTransmissionCongestionStatesPackage_oid[12];
extern oid m2paReceiveCongestionLevelPackage_oid[12];
extern oid m2paProtocolProfileNamePackage_oid[12];
extern oid m2paThresholdsForMultCongLevelsPackage_oid[12];
extern oid m2paThresholdsForMultCongLevelsWithPrioPackage_oid[12];

/* function prototypes */
/* trap function prototypes */

/* variable function prototypes */
void init_m2paMIB(void);
void deinit_m2paMIB(void);
int term_m2paMIB(int majorID, int minorID, void *serverarg, void *clientarg);
FindVarMethod var_m2paMIB;
void parse_m2paMIB(const char *, char *);
SNMPCallback store_m2paMIB;
void refresh_m2paMIB(int);
FindVarMethod var_m2paProtocolProfileTable;
struct m2paProtocolProfileTable_data *m2paProtocolProfileTable_create(void);
struct m2paProtocolProfileTable_data *m2paProtocolProfileTable_duplicate(struct m2paProtocolProfileTable_data *);
int m2paProtocolProfileTable_destroy(struct m2paProtocolProfileTable_data **);
int m2paProtocolProfileTable_add(struct m2paProtocolProfileTable_data *);
int m2paProtocolProfileTable_del(struct m2paProtocolProfileTable_data *);
void parse_m2paProtocolProfileTable(const char *, char *);
SNMPCallback store_m2paProtocolProfileTable;
void refresh_m2paProtocolProfileTable(int);

WriteMethod write_m2paN1;
WriteMethod write_m2paProving;
WriteMethod write_m2paManagementProvingState;
WriteMethod write_m2paLoopDelayLower;
WriteMethod write_m2paLoopDelayUpper;
WriteMethod write_m2paTransmissionRateIntervalLower;
WriteMethod write_m2paTransmissionRateIntervalUpper;
WriteMethod write_m2paSctpNoDelay;
WriteMethod write_m2paSctpMaxseg;
WriteMethod write_m2paSctpHeartbeatItvl;
WriteMethod write_m2paSctpHeartbeat;
WriteMethod write_m2paSctpRtoInitial;
WriteMethod write_m2paSctpRtoMin;
WriteMethod write_m2paSctpRtoMax;
WriteMethod write_m2paSctpPathMaxRetrans;
WriteMethod write_m2paSctpCookieLife;
WriteMethod write_m2paSctpCookieInc;
WriteMethod write_m2paSctpMaxInitRetries;
WriteMethod write_m2paSctpMaxBurst;
WriteMethod write_m2paSctpAssocMaxRetrans;
WriteMethod write_m2paSctpSackDelay;
WriteMethod write_m2paSctpLifetime;
WriteMethod write_m2paTimerT1;
WriteMethod write_m2paTimerT2;
WriteMethod write_m2paTimerT2L;
WriteMethod write_m2paTimerT2H;
WriteMethod write_m2paTimerT3;
WriteMethod write_m2paTimerT4N;
WriteMethod write_m2paTimerT4E;
WriteMethod write_m2paTimerT6;
WriteMethod write_m2paTimerT7;
WriteMethod write_m2paTransCongThresholdAbatementL1Messages;
WriteMethod write_m2paTransCongThresholdAbatementL1Octets;
WriteMethod write_m2paTransCongThresholdOnsetL1Messages;
WriteMethod write_m2paTransCongThresholdOnsetL1Octets;
WriteMethod write_m2paProvingAttempts;
WriteMethod write_m2paNumberOfThresholdLevels;
WriteMethod write_m2paCongestionCounting;
WriteMethod write_m2paCongestionReportingBaseObject;
WriteMethod write_m2paTimerTx;
WriteMethod write_m2paTimerTy;
WriteMethod write_m2paNumberOfCongestionStates;
WriteMethod write_m2paInitialLevelOfCongestion;
WriteMethod write_m2paReceiveCongestionThresholdAbatement;
WriteMethod write_m2paReceiveCongestionThresholdOnset;
WriteMethod write_m2paReceiveCongestionThresholdDiscard;
WriteMethod write_m2paProtocolProfileName;
WriteMethod write_m2paTransCongThresholdAbatementL2Messages;
WriteMethod write_m2paTransCongThresholdAbatementL2Octets;
WriteMethod write_m2paTransCongThresholdOnsetL2Messages;
WriteMethod write_m2paTransCongThresholdOnsetL2Octets;
WriteMethod write_m2paTransCongThresholdAbatementL3Messages;
WriteMethod write_m2paTransCongThresholdAbatementL3Octets;
WriteMethod write_m2paTransCongThresholdOnsetL3Messages;
WriteMethod write_m2paTransCongThresholdOnsetL3Octets;
WriteMethod write_m2paTransCongThresholdDiscardL1Messages;
WriteMethod write_m2paTransCongThresholdDiscardL1Octets;
WriteMethod write_m2paTransCongThresholdDiscardL2Messages;
WriteMethod write_m2paTransCongThresholdDiscardL2Octets;
WriteMethod write_m2paTransCongThresholdDiscardL3Messages;
WriteMethod write_m2paTransCongThresholdDiscardL3Octets;
WriteMethod write_m2paProtocolProfileRowStatus;
WriteMethod write_m2paDefaultSctpNoDelay;
WriteMethod write_m2paDefaultSctpMaxseg;
WriteMethod write_m2paDefaultSctpHeartbeatItvl;
WriteMethod write_m2paDefaultSctpHeartbeat;
WriteMethod write_m2paDefaultSctpRtoInitial;
WriteMethod write_m2paDefaultSctpRtoMin;
WriteMethod write_m2paDefaultSctpRtoMax;
WriteMethod write_m2paDefaultSctpPathMaxRetrans;
WriteMethod write_m2paDefaultSctpCookieLife;
WriteMethod write_m2paDefaultSctpCookieInc;
WriteMethod write_m2paDefaultSctpMaxInitRetries;
WriteMethod write_m2paDefaultSctpMaxBurst;
WriteMethod write_m2paDefaultSctpAssocMaxRetrans;
WriteMethod write_m2paDefaultSctpSackDelay;
WriteMethod write_m2paDefaultSctpLifetime;
#endif				/* __LOCAL_M2PAMIB_H__ */
