/*****************************************************************************

 @(#) src/snmp/megacoMIB.h

 -----------------------------------------------------------------------------

 Copyright (c) 2008-2019  Monavacon Limited <http://www.monavacon.com/>
 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; version 3 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 *****************************************************************************/

#ifndef __LOCAL_MEGACOMIB_H__
#define __LOCAL_MEGACOMIB_H__

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */

extern const char sa_program[];
extern int sa_fclose;			/* default close files between requests */
extern int sa_changed;			/* indication to reread MIB configuration */
extern int sa_stats_refresh;		/* indications that statistics, the mib or its tables need to be refreshed */
extern int sa_request;			/* request number for per-request actions */

/* our storage structure(s) */
struct megacoMIB_data {
	struct megacoMIB_data *megacoMIB_old;
	uint megacoMIB_rsvs;
	uint megacoMIB_tsts;
	uint megacoMIB_sets;
	uint megacoMIB_request;
};
struct medGwyLinkIdTable_data {
	struct medGwyLinkIdTable_data *medGwyLinkIdTable_old;
	uint medGwyLinkIdTable_rsvs;
	uint medGwyLinkIdTable_tsts;
	uint medGwyLinkIdTable_sets;
	uint medGwyLinkIdTable_request;
	uint medGwyLinkIdTable_refs;
	uint medGwyLinkIdTable_id;
	ulong medGwyGatewayId;		/* Notify */
	long medGwyNextLinkId;		/* ReadWrite */
};
struct medGwyGatewayConfigTable_data {
	struct medGwyGatewayConfigTable_data *medGwyGatewayConfigTable_old;
	uint medGwyGatewayConfigTable_rsvs;
	uint medGwyGatewayConfigTable_tsts;
	uint medGwyGatewayConfigTable_sets;
	uint medGwyGatewayConfigTable_request;
	uint medGwyGatewayConfigTable_refs;
	uint medGwyGatewayConfigTable_id;
	ulong medGwyGatewayId;		/* Notify */
	ulong medGwyGatewayLinkId;	/* NoAccess */
	uint8_t *medGwyGatewayLinkName;	/* Create */
	size_t medGwyGatewayLinkNameLen;
	uint8_t *medGwyGatewayIPAddress;	/* Create */
	size_t medGwyGatewayIPAddressLen;
	long medGwyGatewayPort;		/* Create */
	long medGwyGatewayEncodingScheme;	/* Create */
	long medGwyGatewayProtocol;	/* Create */
	long medGwyGatewaySignalingTptProtocol;	/* Create */
	long medGwyGatewayAdminStatus;	/* Create */
	long medGwyGatewayOperStatus;	/* ReadOnly */
	long medGwyGatewayLastStatusChange;	/* ReadOnly */
	long medGwyGatewayResetStatistics;	/* Create */
	long medGwyGatewayRowStatus;	/* Create */
};
struct medGwyGatewayControllerTable_data {
	struct medGwyGatewayControllerTable_data *medGwyGatewayControllerTable_old;
	uint medGwyGatewayControllerTable_rsvs;
	uint medGwyGatewayControllerTable_tsts;
	uint medGwyGatewayControllerTable_sets;
	uint medGwyGatewayControllerTable_request;
	uint medGwyGatewayControllerTable_refs;
	uint medGwyGatewayControllerTable_id;
	ulong medGwyGatewayId;		/* Notify */
	ulong medGwyGatewayLinkId;	/* NoAccess */
	ulong medGwyGatewayControllerId;	/* Notify */
	uint8_t *medGwyGatewayControllerIPAddress;	/* Create */
	size_t medGwyGatewayControllerIPAddressLen;
	long medGwyGatewayControllerPort;	/* Create */
	long medGwyGatewayControllerAdminStatus;	/* Create */
	long medGwyGatewayControllerOperStatus;	/* ReadOnly */
};
struct medGwyGatewayStatsTable_data {
	struct medGwyGatewayStatsTable_data *medGwyGatewayStatsTable_old;
	uint medGwyGatewayStatsTable_rsvs;
	uint medGwyGatewayStatsTable_tsts;
	uint medGwyGatewayStatsTable_sets;
	uint medGwyGatewayStatsTable_request;
	uint medGwyGatewayStatsTable_refs;
	uint medGwyGatewayStatsTable_id;
	ulong medGwyGatewayId;		/* Notify */
	ulong medGwyGatewayLinkId;	/* NoAccess */
	ulong medGwyGatewayNumInMessages;	/* ReadOnly */
	ulong medGwyGatewayNumInOctets;	/* ReadOnly */
	ulong medGwyGatewayNumOutMessages;	/* ReadOnly */
	ulong medGwyGatewayNumOutOctets;	/* ReadOnly */
	ulong medGwyGatewayNumErrors;	/* ReadOnly */
	ulong medGwyGatewayNumTimerRecovery;	/* ReadOnly */
	ulong medGwyGatewayTransportNumLosses;	/* ReadOnly */
	ulong medGwyGatewayTransportNumSwitchover;	/* ReadOnly */
	ulong medGwyGatewayTransportTotalNumAlarms;	/* ReadOnly */
	long medGwyGatewayTransportLastEvent;	/* ReadOnly */
	long medGwyGatewayTransportLastEventTime;	/* ReadWrite */
	long medGwyGatewayLastStatisticsReset;	/* ReadOnly */
};
struct medGwyTermIdTable_data {
	struct medGwyTermIdTable_data *medGwyTermIdTable_old;
	uint medGwyTermIdTable_rsvs;
	uint medGwyTermIdTable_tsts;
	uint medGwyTermIdTable_sets;
	uint medGwyTermIdTable_request;
	uint medGwyTermIdTable_refs;
	uint medGwyTermIdTable_id;
	ulong medGwyGatewayId;		/* Notify */
	long medGwyNextTerminationId;	/* ReadWrite */
};
struct medGwyTerminationsTable_data {
	struct medGwyTerminationsTable_data *medGwyTerminationsTable_old;
	uint medGwyTerminationsTable_rsvs;
	uint medGwyTerminationsTable_tsts;
	uint medGwyTerminationsTable_sets;
	uint medGwyTerminationsTable_request;
	uint medGwyTerminationsTable_refs;
	uint medGwyTerminationsTable_id;
	ulong medGwyGatewayId;		/* Notify */
	ulong medGwyTerminationId;	/* Notify */
	uint8_t *medGwyTerminationName;	/* Create */
	size_t medGwyTerminationNameLen;
	long medGwyTerminationAdminStatus;	/* Create */
	long medGwyTerminationOperStatus;	/* Create */
	long medGwyTerminationInterfaceIdentifier;	/* Create */
	ulong medGwyTerminationPropertyProfileId;	/* Create */
	long medGwyTerminationRowStatus;	/* Create */
};
struct medGwyPropertyProfileTable_data {
	struct medGwyPropertyProfileTable_data *medGwyPropertyProfileTable_old;
	uint medGwyPropertyProfileTable_rsvs;
	uint medGwyPropertyProfileTable_tsts;
	uint medGwyPropertyProfileTable_sets;
	uint medGwyPropertyProfileTable_request;
	uint medGwyPropertyProfileTable_refs;
	uint medGwyPropertyProfileTable_id;
	ulong medGwyGatewayId;		/* Notify */
	ulong medGwyPropertyProfileId;	/* NoAccess */
	ulong medGwyPropertyProfileIndex;	/* NoAccess */
	oid *medGwyPropertyProfileProperty;	/* Create */
	size_t medGwyPropertyProfilePropertyLen;
	long medGwyTermPropertyProfileStatus;	/* Create */
};

/* storage declarations */
extern struct megacoMIB_data *megacoMIBStorage;
extern struct header_complex_index *medGwyLinkIdTableStorage;
extern struct header_complex_index *medGwyGatewayConfigTableStorage;
extern struct header_complex_index *medGwyGatewayControllerTableStorage;
extern struct header_complex_index *medGwyGatewayStatsTableStorage;
extern struct header_complex_index *medGwyTermIdTableStorage;
extern struct header_complex_index *medGwyTerminationsTableStorage;
extern struct header_complex_index *medGwyPropertyProfileTableStorage;

/* enum definitions from the covered mib sections */

#define MEDGWYGATEWAYENCODINGSCHEME_TEXT         1
#define MEDGWYGATEWAYENCODINGSCHEME_BINARY       2

#define MEDGWYGATEWAYPROTOCOL_NOTAPPLICABLE      1
#define MEDGWYGATEWAYPROTOCOL_OTHER              2
#define MEDGWYGATEWAYPROTOCOL_DSS1IP             3
#define MEDGWYGATEWAYPROTOCOL_IPDC               4
#define MEDGWYGATEWAYPROTOCOL_MEGACOV1           5
#define MEDGWYGATEWAYPROTOCOL_MEGACOV2           6
#define MEDGWYGATEWAYPROTOCOL_MGCP               7

#define MEDGWYGATEWAYSIGNALINGTPTPROTOCOL_TCP    1
#define MEDGWYGATEWAYSIGNALINGTPTPROTOCOL_UDP    2
#define MEDGWYGATEWAYSIGNALINGTPTPROTOCOL_SCTP   3
#define MEDGWYGATEWAYSIGNALINGTPTPROTOCOL_OTHER  4

#define MEDGWYGATEWAYADMINSTATUS_UP              1
#define MEDGWYGATEWAYADMINSTATUS_DOWN            2
#define MEDGWYGATEWAYADMINSTATUS_TESTING         3

#define MEDGWYGATEWAYOPERSTATUS_UP               1
#define MEDGWYGATEWAYOPERSTATUS_DOWN             2
#define MEDGWYGATEWAYOPERSTATUS_TESTING          3
#define MEDGWYGATEWAYOPERSTATUS_UNKNOWN          4

#define MEDGWYGATEWAYRESETSTATISTICS_NOTAPPLICABLE 1
#define MEDGWYGATEWAYRESETSTATISTICS_OTHER       2
#define MEDGWYGATEWAYRESETSTATISTICS_RESET       3

#define MEDGWYGATEWAYCONTROLLERADMINSTATUS_UP    1
#define MEDGWYGATEWAYCONTROLLERADMINSTATUS_DOWN  2
#define MEDGWYGATEWAYCONTROLLERADMINSTATUS_TESTING 3

#define MEDGWYGATEWAYCONTROLLEROPERSTATUS_UP     1
#define MEDGWYGATEWAYCONTROLLEROPERSTATUS_DOWN   2
#define MEDGWYGATEWAYCONTROLLEROPERSTATUS_STANDBY 3

#define MEDGWYGATEWAYTRANSPORTLASTEVENT_NOTAPPLICABLE 1
#define MEDGWYGATEWAYTRANSPORTLASTEVENT_OTHER    2
#define MEDGWYGATEWAYTRANSPORTLASTEVENT_LINKUP   3
#define MEDGWYGATEWAYTRANSPORTLASTEVENT_LINKLOSS 4
#define MEDGWYGATEWAYTRANSPORTLASTEVENT_PERSISTENTERROR 5
#define MEDGWYGATEWAYTRANSPORTLASTEVENT_LINKSHUTDOWN 6
#define MEDGWYGATEWAYTRANSPORTLASTEVENT_SWITCHOVER 7

#define MEDGWYTERMINATIONADMINSTATUS_INSERVICE   1
#define MEDGWYTERMINATIONADMINSTATUS_OUTOFSERVICE 2
#define MEDGWYTERMINATIONADMINSTATUS_TESTING     3

#define MEDGWYTERMINATIONOPERSTATUS_UP           1
#define MEDGWYTERMINATIONOPERSTATUS_DOWN         2
#define MEDGWYTERMINATIONOPERSTATUS_TESTING      3

/* notifications */
extern oid medGwyLinkStatusChange_oid[10];
extern oid medGwyInvalidControllerAddress_oid[10];
extern oid medGwyInvalidTerminationId_oid[10];
extern oid medGwyInvalidPackageElement_oid[10];
extern oid medGwyTerminationStatusChange_oid[10];
extern oid medGwyGatewayHandoff_oid[10];
extern oid medGwyProtocolError_oid[10];

/* scalars accessible only for notify */
extern oid medGwyReceivedElement_oid[10];

/* object id definitions */
extern oid medGwyCompliance_oid[10];
extern oid medGwyConfigGroup_oid[10];
extern oid medGwyStatsGroup_oid[10];
extern oid medGwyGWControllerGroup_oid[10];
extern oid medGwyNextIdGroup_oid[10];
extern oid medGwyNotificationsGroup_oid[10];
extern oid medGwyTerminationGroup_oid[10];

/* function prototypes */
/* trap function prototypes */
extern void send_medGwyLinkStatusChange_v2trap(struct variable_list *);
extern void send_medGwyInvalidControllerAddress_v2trap(struct variable_list *);
extern void send_medGwyInvalidTerminationId_v2trap(struct variable_list *);
extern void send_medGwyInvalidPackageElement_v2trap(struct variable_list *);
extern void send_medGwyTerminationStatusChange_v2trap(struct variable_list *);
extern void send_medGwyGatewayHandoff_v2trap(struct variable_list *);
extern void send_medGwyProtocolError_v2trap(struct variable_list *);

/* variable function prototypes */
void init_megacoMIB(void);
void deinit_megacoMIB(void);
int term_megacoMIB(int majorID, int minorID, void *serverarg, void *clientarg);
FindVarMethod var_megacoMIB;
struct megacoMIB_data *megacoMIB_create(void);
struct megacoMIB_data *megacoMIB_duplicate(struct megacoMIB_data *);
int megacoMIB_destroy(struct megacoMIB_data **);
int megacoMIB_add(struct megacoMIB_data *);
void parse_megacoMIB(const char *, char *);
SNMPCallback store_megacoMIB;
void refresh_megacoMIB(int);
FindVarMethod var_medGwyLinkIdTable;
struct medGwyLinkIdTable_data *medGwyLinkIdTable_create(void);
struct medGwyLinkIdTable_data *medGwyLinkIdTable_duplicate(struct medGwyLinkIdTable_data *);
int medGwyLinkIdTable_destroy(struct medGwyLinkIdTable_data **);
int medGwyLinkIdTable_add(struct medGwyLinkIdTable_data *);
int medGwyLinkIdTable_del(struct medGwyLinkIdTable_data *);
void parse_medGwyLinkIdTable(const char *, char *);
SNMPCallback store_medGwyLinkIdTable;
void refresh_medGwyLinkIdTable(int);
FindVarMethod var_medGwyGatewayConfigTable;
struct medGwyGatewayConfigTable_data *medGwyGatewayConfigTable_create(void);
struct medGwyGatewayConfigTable_data *medGwyGatewayConfigTable_duplicate(struct medGwyGatewayConfigTable_data *);
int medGwyGatewayConfigTable_destroy(struct medGwyGatewayConfigTable_data **);
int medGwyGatewayConfigTable_add(struct medGwyGatewayConfigTable_data *);
int medGwyGatewayConfigTable_del(struct medGwyGatewayConfigTable_data *);
void parse_medGwyGatewayConfigTable(const char *, char *);
SNMPCallback store_medGwyGatewayConfigTable;
void refresh_medGwyGatewayConfigTable(int);
FindVarMethod var_medGwyGatewayControllerTable;
struct medGwyGatewayControllerTable_data *medGwyGatewayControllerTable_create(void);
struct medGwyGatewayControllerTable_data *medGwyGatewayControllerTable_duplicate(struct medGwyGatewayControllerTable_data *);
int medGwyGatewayControllerTable_destroy(struct medGwyGatewayControllerTable_data **);
int medGwyGatewayControllerTable_add(struct medGwyGatewayControllerTable_data *);
int medGwyGatewayControllerTable_del(struct medGwyGatewayControllerTable_data *);
void parse_medGwyGatewayControllerTable(const char *, char *);
SNMPCallback store_medGwyGatewayControllerTable;
void refresh_medGwyGatewayControllerTable(int);
FindVarMethod var_medGwyGatewayStatsTable;
struct medGwyGatewayStatsTable_data *medGwyGatewayStatsTable_create(void);
struct medGwyGatewayStatsTable_data *medGwyGatewayStatsTable_duplicate(struct medGwyGatewayStatsTable_data *);
int medGwyGatewayStatsTable_destroy(struct medGwyGatewayStatsTable_data **);
int medGwyGatewayStatsTable_add(struct medGwyGatewayStatsTable_data *);
int medGwyGatewayStatsTable_del(struct medGwyGatewayStatsTable_data *);
void parse_medGwyGatewayStatsTable(const char *, char *);
SNMPCallback store_medGwyGatewayStatsTable;
void refresh_medGwyGatewayStatsTable(int);
FindVarMethod var_medGwyTermIdTable;
struct medGwyTermIdTable_data *medGwyTermIdTable_create(void);
struct medGwyTermIdTable_data *medGwyTermIdTable_duplicate(struct medGwyTermIdTable_data *);
int medGwyTermIdTable_destroy(struct medGwyTermIdTable_data **);
int medGwyTermIdTable_add(struct medGwyTermIdTable_data *);
int medGwyTermIdTable_del(struct medGwyTermIdTable_data *);
void parse_medGwyTermIdTable(const char *, char *);
SNMPCallback store_medGwyTermIdTable;
void refresh_medGwyTermIdTable(int);
FindVarMethod var_medGwyTerminationsTable;
struct medGwyTerminationsTable_data *medGwyTerminationsTable_create(void);
struct medGwyTerminationsTable_data *medGwyTerminationsTable_duplicate(struct medGwyTerminationsTable_data *);
int medGwyTerminationsTable_destroy(struct medGwyTerminationsTable_data **);
int medGwyTerminationsTable_add(struct medGwyTerminationsTable_data *);
int medGwyTerminationsTable_del(struct medGwyTerminationsTable_data *);
void parse_medGwyTerminationsTable(const char *, char *);
SNMPCallback store_medGwyTerminationsTable;
void refresh_medGwyTerminationsTable(int);
FindVarMethod var_medGwyPropertyProfileTable;
struct medGwyPropertyProfileTable_data *medGwyPropertyProfileTable_create(void);
struct medGwyPropertyProfileTable_data *medGwyPropertyProfileTable_duplicate(struct medGwyPropertyProfileTable_data *);
int medGwyPropertyProfileTable_destroy(struct medGwyPropertyProfileTable_data **);
int medGwyPropertyProfileTable_add(struct medGwyPropertyProfileTable_data *);
int medGwyPropertyProfileTable_del(struct medGwyPropertyProfileTable_data *);
void parse_medGwyPropertyProfileTable(const char *, char *);
SNMPCallback store_medGwyPropertyProfileTable;
void refresh_medGwyPropertyProfileTable(int);

WriteMethod write_medGwyNextLinkId;
WriteMethod write_medGwyGatewayLinkName;
WriteMethod write_medGwyGatewayIPAddress;
WriteMethod write_medGwyGatewayPort;
WriteMethod write_medGwyGatewayEncodingScheme;
WriteMethod write_medGwyGatewayProtocol;
WriteMethod write_medGwyGatewaySignalingTptProtocol;
WriteMethod write_medGwyGatewayAdminStatus;
WriteMethod write_medGwyGatewayResetStatistics;
WriteMethod write_medGwyGatewayRowStatus;
WriteMethod write_medGwyGatewayControllerIPAddress;
WriteMethod write_medGwyGatewayControllerPort;
WriteMethod write_medGwyGatewayControllerAdminStatus;
WriteMethod write_medGwyGatewayTransportLastEventTime;
WriteMethod write_medGwyNextTerminationId;
WriteMethod write_medGwyTerminationName;
WriteMethod write_medGwyTerminationAdminStatus;
WriteMethod write_medGwyTerminationOperStatus;
WriteMethod write_medGwyTerminationInterfaceIdentifier;
WriteMethod write_medGwyTerminationPropertyProfileId;
WriteMethod write_medGwyTerminationRowStatus;
WriteMethod write_medGwyPropertyProfileProperty;
WriteMethod write_medGwyTermPropertyProfileStatus;
#endif				/* __LOCAL_MEGACOMIB_H__ */
