/*****************************************************************************

 @(#) $Id: sigtranMIB.h,v 1.1.2.2 2010-11-28 14:22:16 brian Exp $

 -----------------------------------------------------------------------------

 Copyright (c) 2008-2010  Monavacon Limited <http://www.monavacon.com/>
 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; version 3 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 -----------------------------------------------------------------------------

 Last Modified $Date: 2010-11-28 14:22:16 $ by $Author: brian $

 -----------------------------------------------------------------------------

 $Log: sigtranMIB.h,v $
 Revision 1.1.2.2  2010-11-28 14:22:16  brian
 - remove #ident, protect _XOPEN_SOURCE

 Revision 1.1.2.1  2009-06-21 11:42:34  brian
 - added files to new distro

 Revision 0.9.2.8  2009-02-18 20:18:43  brian
 - updated agents

 Revision 0.9.2.7  2009-01-19 13:31:38  brian
 - updating standalone agents

 Revision 0.9.2.6  2009-01-10 17:31:01  brian
 - agent updates

 Revision 0.9.2.5  2009-01-04 13:16:09  brian
 - updated agents

 Revision 0.9.2.4  2009-01-03 10:51:00  brian
 - updated agent

 Revision 0.9.2.3  2009-01-02 15:04:10  brian
 - updated agents

 Revision 0.9.2.2  2008-12-31 16:04:42  brian
 - updated mibs

 Revision 0.9.2.1  2008-12-27 10:01:53  brian
 - updated mibs and stubs

 *****************************************************************************/

#ifndef __LOCAL_SIGTRANMIB_H__
#define __LOCAL_SIGTRANMIB_H__

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */

extern const char sa_program[];
extern int sa_fclose;			/* default close files between requests */
extern int sa_changed;			/* indication to reread MIB configuration */
extern int sa_stats_refresh;		/* indications that statistics, the mib or its tables need to be refreshed */
extern int sa_request;			/* request number for per-request actions */

/* our storage structure(s) */
struct sigtranMIB_data {
	uint sigtranMIB_request;
	ulong sigtranSctpProfileNextIndex;	/* ReadOnly */
};
struct sigtranSctpProfileTable_data {
	uint sigtranSctpProfileTable_request;
	uint sigtranSctpProfileTable_refs;
	ulong sigtranSctpProfileIndex;	/* NoAccess */
	uint8_t *sigtranSctpProfileName;	/* Create */
	size_t sigtranSctpProfileNameLen;
	long sigtranSctpProfileNodelay;	/* Create */
	ulong sigtranSctpPayloadProtocolId;	/* Create */
	long sigtranSctpLifetime;	/* Create */
	long sigtranSctpProfileCsumType;	/* Create */
	long sigtranSctpProfileMacType;	/* Create */
	long sigtranSctpProfileValidCookieLife;	/* Create */
	long sigtranSctpProfileCookieInc;	/* Create */
	ulong sigtranSctpProfileMaxIstreams;	/* Create */
	ulong sigtranSctpProfileReqOstreams;	/* Create */
	long sigtranSctpEcn;		/* Create */
	ulong sigtranSctpAdaptationLayerInfo;	/* Create */
	ulong sigtranSctpProfileMaxInitRetries;	/* Create */
	ulong sigtranSctpProfileMaxBurst;	/* Create */
	ulong sigtranSctpProfileAssocMaxRetrans;	/* Create */
	long sigtranSctpProfileMaxSackDelay;	/* Create */
	long sigtranSctpProfileRtoMin;	/* Create */
	long sigtranSctpProfileRtoInitial;	/* Create */
	long sigtranSctpProfileRtoMax;	/* Create */
	ulong sigtranSctpProfilePathMaxRetrans;	/* Create */
	long sigtranSctpProfileHeartbeatItvl;	/* Create */
	long sigtranSctpProfileStatus;	/* Create */
};

/* storage declarations */
extern struct sigtranMIB_data *sigtranMIBStorage;
extern struct header_complex_index *sigtranSctpProfileTableStorage;

/* enum definitions from the covered mib sections */

#define SIGTRANSCTPPROFILENODELAY_TRUE           1
#define SIGTRANSCTPPROFILENODELAY_FALSE          2

#define SIGTRANSCTPPROFILECSUMTYPE_CRC32C        1
#define SIGTRANSCTPPROFILECSUMTYPE_ADLER32       2
#define SIGTRANSCTPPROFILECSUMTYPE_NONE          3
#define SIGTRANSCTPPROFILECSUMTYPE_ADAPTIVE      4
#define SIGTRANSCTPPROFILECSUMTYPE_OTHER         5

#define SIGTRANSCTPPROFILEMACTYPE_MD5            1
#define SIGTRANSCTPPROFILEMACTYPE_SHA1           2
#define SIGTRANSCTPPROFILEMACTYPE_NONE           3
#define SIGTRANSCTPPROFILEMACTYPE_OTHER          4

#define SIGTRANSCTPECN_TRUE                      1
#define SIGTRANSCTPECN_FALSE                     2

/* notifications */

/* scalars accessible only for notify */

/* object id definitions */

/* function prototypes */
/* trap function prototypes */

/* variable function prototypes */
void init_sigtranMIB(void);
void deinit_sigtranMIB(void);
int term_sigtranMIB(int majorID, int minorID, void *serverarg, void *clientarg);
FindVarMethod var_sigtranMIB;
void parse_sigtranMIB(const char *, char *);
SNMPCallback store_sigtranMIB;
void refresh_sigtranMIB(int);
FindVarMethod var_sigtranSctpProfileTable;
struct sigtranSctpProfileTable_data *sigtranSctpProfileTable_create(void);
struct sigtranSctpProfileTable_data *sigtranSctpProfileTable_duplicate(struct sigtranSctpProfileTable_data *);
int sigtranSctpProfileTable_destroy(struct sigtranSctpProfileTable_data **);
int sigtranSctpProfileTable_add(struct sigtranSctpProfileTable_data *);
int sigtranSctpProfileTable_del(struct sigtranSctpProfileTable_data *);
void parse_sigtranSctpProfileTable(const char *, char *);
SNMPCallback store_sigtranSctpProfileTable;
void refresh_sigtranSctpProfileTable(int);

WriteMethod write_sigtranSctpProfileName;
WriteMethod write_sigtranSctpProfileNodelay;
WriteMethod write_sigtranSctpPayloadProtocolId;
WriteMethod write_sigtranSctpLifetime;
WriteMethod write_sigtranSctpProfileCsumType;
WriteMethod write_sigtranSctpProfileMacType;
WriteMethod write_sigtranSctpProfileValidCookieLife;
WriteMethod write_sigtranSctpProfileCookieInc;
WriteMethod write_sigtranSctpProfileMaxIstreams;
WriteMethod write_sigtranSctpProfileReqOstreams;
WriteMethod write_sigtranSctpEcn;
WriteMethod write_sigtranSctpAdaptationLayerInfo;
WriteMethod write_sigtranSctpProfileMaxInitRetries;
WriteMethod write_sigtranSctpProfileMaxBurst;
WriteMethod write_sigtranSctpProfileAssocMaxRetrans;
WriteMethod write_sigtranSctpProfileMaxSackDelay;
WriteMethod write_sigtranSctpProfileRtoMin;
WriteMethod write_sigtranSctpProfileRtoInitial;
WriteMethod write_sigtranSctpProfileRtoMax;
WriteMethod write_sigtranSctpProfilePathMaxRetrans;
WriteMethod write_sigtranSctpProfileHeartbeatItvl;
WriteMethod write_sigtranSctpProfileStatus;
#endif				/* __LOCAL_SIGTRANMIB_H__ */
