/*****************************************************************************

 @(#) $RCSfile: ss7MIB.c,v $ $Name:  $($Revision: 1.1.2.4 $) $Date: 2011-07-18 19:42:27 $

 -----------------------------------------------------------------------------

 Copyright (c) 2008-2012  Monavacon Limited <http://www.monavacon.com/>
 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software: you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation, version 3 of the license.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 -----------------------------------------------------------------------------

 Last Modified $Date: 2011-07-18 19:42:27 $ by $Author: brian $

 -----------------------------------------------------------------------------

 $Log: ss7MIB.c,v $
 Revision 1.1.2.4  2011-07-18 19:42:27  brian
 - added documentation

 Revision 1.1.2.3  2011-05-31 09:46:12  brian
 - new distros

 Revision 1.1.2.2  2010-11-28 14:22:17  brian
 - remove #ident, protect _XOPEN_SOURCE

 Revision 1.1.2.1  2009-06-21 11:42:35  brian
 - added files to new distro

 Revision 0.9.2.13  2009-02-18 20:18:54  brian
 - updated agents

 Revision 0.9.2.12  2009-01-19 13:31:51  brian
 - updating standalone agents

 Revision 0.9.2.11  2009-01-16 20:45:01  brian
 - updating mibs and agents

 Revision 0.9.2.10  2009-01-14 14:30:07  brian
 - working up agents

 Revision 0.9.2.9  2009-01-10 17:09:22  brian
 - updated agents

 Revision 0.9.2.8  2009-01-04 13:16:06  brian
 - updated agents

 Revision 0.9.2.7  2009-01-03 10:51:07  brian
 - updated agent

 Revision 0.9.2.6  2009-01-02 15:46:44  brian
 - corrections

 Revision 0.9.2.5  2009-01-02 15:04:16  brian
 - updated agents

 Revision 0.9.2.4  2008-12-31 16:04:47  brian
 - updated mibs

 Revision 0.9.2.3  2008-12-27 15:29:48  brian
 - split MTP and MTP OM mib

 Revision 0.9.2.2  2008-12-24 13:08:26  brian
 - building ss7confd

 *****************************************************************************/

static char const ident[] = "$RCSfile: ss7MIB.c,v $ $Name:  $($Revision: 1.1.2.4 $) $Date: 2011-07-18 19:42:27 $";

/* This file was generated by mib2c and is intended for use as
   a mib module for the ucd-snmp snmpd agent. */
#include <ucd-snmp/ucd-snmp-config.h>
#include <ucd-snmp/ucd-snmp-includes.h>
#include <ucd-snmp/ucd-snmp-agent-includes.h>
#include <ucd-snmp/agent_trap.h>
#include <ucd-snmp/callback.h>
#include <ucd-snmp/snmp-tc.h>
#include <ucd-snmp/default_store.h>
#include <ucd-snmp/snmp_alarm.h>
/* The following header files are mangled in most recent net-snmp releases so
 * the versions from UCD-SNMP 4.2.5 are included here.  */
#if defined HAVE_LIBNETSNMP
#else				/* defined HAVE_LIBNETSNMP */
#endif				/* defined HAVE_LIBNETSNMP */
/* These are messed up on both. */
#include "ds_agent.h"
#ifdef HAVE_UCD_SNMP_UTIL_FUNCS_H
#include <ucd-snmp/util_funcs.h>
/* Many recent net-snmp UCD compatible headers do not declare header_generic. */
int header_generic(struct variable *, oid *, size_t *, int, size_t *, WriteMethod **);
#else				/* HAVE_UCD_SNMP_UTIL_FUNCS_H */
#include "util_funcs.h"
#endif				/* HAVE_UCD_SNMP_UTIL_FUNCS_H */
#ifdef HAVE_UCD_SNMP_HEADER_COMPLEX_H
#include <ucd-snmp/header_complex.h>
#else				/* HAVE_UCD_SNMP_HEADER_COMPLEX_H */
#include "header_complex.h"
#endif				/* HAVE_UCD_SNMP_HEADER_COMPLEX_H */
/* This one is the other way around: it is just fine for net-snmp, but
 * ucd-snmp does not provide the header file at all.  */
#ifdef HAVE_UCD_SNMP_MIB_MODULES_H
#include <ucd-snmp/mib_modules.h>
#else				/* HAVE_UCD_SNMP_MIB_MODULES_H */
#ifdef HAVE_NET_SNMP_AGENT_MIB_MODULES_H
#include <net-snmp/agent/mib_modules.h>
#else				/* HAVE_NET_SNMP_AGENT_MIB_MODULES_H */
#include "mib_modules.h"
#endif				/* HAVE_NET_SNMP_AGENT_MIB_MODULES_H */
#endif				/* HAVE_UCD_SNMP_MIB_MODULES_H */
#include <stdint.h>
#include <signal.h>
#include <sys/stat.h>		/* for struct stat, fstat() */
#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>
#include <pwd.h>		/* for getpwuid() getpwnam() */
#include <grp.h>		/* for getgrgid() getgrnam() */
#include <libgen.h>		/* for basename() */
#include <fcntl.h>		/* for O_CREAT */
#include <sys/sysctl.h>		/* for sysctl */
#include <errno.h>
#include <string.h>
#ifdef _GNU_SOURCE
#include <getopt.h>
#endif
#include "mtpMIB.h"
#include "mtpOmMIB.h"
#include "sccpMIB.h"
#include "sccpOmMIB.h"
#include "tcapMIB.h"
#include "tcapOmMIB.h"
#include "ss7MIB.h"
#define MASTER 1
#define MY_FACILITY(__pri)	(LOG_DAEMON|(__pri))
#if defined MODULE
#if defined MASTER
const char sa_program[] = "ss7MIB";
int sa_fclose = 1;			/* default close files between requests */
int sa_changed = 1;			/* indication to reread MIB configuration */
int sa_stats_refresh = 1;		/* indications that statistics, the mib or its tables need to be refreshed */
int sa_request = 1;			/* request number for per-request actions */
int sa_dump = 0;			/* default packet dump */
int sa_debug = 0;			/* default no debug */
#endif				/* defined MASTER */
#endif				/* defined MODULE */
static int my_fd = -1;			/* file descriptor for this MIB's use */
static int my_readfd = -1;		/* file descriptor for autonomnous events */
volatile int ss7MIB_refresh = 1;
volatile int ss7NetworkTable_refresh = 1;

/*
 * ss7MIB_variables_oid: object identifier for ss7MIB
 * This is the top level oid that we want to register under.  This is essentially a prefix, with the
 * suffix appearing in the variable below.
 */
oid ss7MIB_variables_oid[10] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0 };
oid ss7NetworkTable_variables_oid[14] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 2, 1, 1 };

/*
 * Oids for use in notifications defined in this MIB.
 */

/*
 * Oids accessible only for notify defined in this MIB.
 */

/*
 * Other oids defined in this MIB.
 */
oid ss7ProtocolItut_oid[14] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1 };
oid ss7ProtocolItut1980_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1, 1980 };
oid ss7ProtocolItut1984_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1, 1984 };
oid ss7ProtocolItut1988_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1, 1988 };
oid ss7ProtocolItut1992_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1, 1992 };
oid ss7ProtocolItut1996_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1, 1996 };
oid ss7ProtocolItut2000_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1, 2000 };
oid ss7ProtocolItut2004_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1, 2004 };
oid ss7ProtocolItut2008_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1, 2008 };
oid ss7ProtocolEtsi_oid[14] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2 };
oid ss7ProtocolEtsi1980_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2, 1980 };
oid ss7ProtocolEtsi1984_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2, 1984 };
oid ss7ProtocolEtsi1988_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2, 1988 };
oid ss7ProtocolEtsi1992_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2, 1992 };
oid ss7ProtocolEtsi1996_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2, 1996 };
oid ss7ProtocolEtsi2000_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2, 2000 };
oid ss7ProtocolEtsi2004_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2, 2004 };
oid ss7ProtocolEtsi2008_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2, 2008 };
oid ss7ProtocolAnsi_oid[14] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3 };
oid ss7ProtocolAnsi1980_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3, 1980 };
oid ss7ProtocolAnsi1984_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3, 1984 };
oid ss7ProtocolAnsi1988_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3, 1988 };
oid ss7ProtocolAnsi1992_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3, 1992 };
oid ss7ProtocolAnsi1996_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3, 1996 };
oid ss7ProtocolAnsi2000_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3, 2000 };
oid ss7ProtocolAnsi2004_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3, 2004 };
oid ss7ProtocolAnsi2008_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3, 2008 };
oid ss7ProtocolJttc_oid[14] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4 };
oid ss7ProtocolJttc1980_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4, 1980 };
oid ss7ProtocolJttc1984_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4, 1984 };
oid ss7ProtocolJttc1988_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4, 1988 };
oid ss7ProtocolJttc1992_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4, 1992 };
oid ss7ProtocolJttc1996_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4, 1996 };
oid ss7ProtocolJttc2000_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4, 2000 };
oid ss7ProtocolJttc2004_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4, 2004 };
oid ss7ProtocolJttc2008_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4, 2008 };
oid ss7ProtocolChin_oid[14] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5 };
oid ss7ProtocolChin1980_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5, 1980 };
oid ss7ProtocolChin1984_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5, 1984 };
oid ss7ProtocolChin1988_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5, 1988 };
oid ss7ProtocolChin1992_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5, 1992 };
oid ss7ProtocolChin1996_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5, 1996 };
oid ss7ProtocolChin2000_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5, 2000 };
oid ss7ProtocolChin2004_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5, 2004 };
oid ss7ProtocolChin2008_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5, 2008 };
oid ss7ProtocolSing_oid[14] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6 };
oid ss7ProtocolSing1980_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6, 1980 };
oid ss7ProtocolSing1984_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6, 1984 };
oid ss7ProtocolSing1988_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6, 1988 };
oid ss7ProtocolSing1992_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6, 1992 };
oid ss7ProtocolSing1996_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6, 1996 };
oid ss7ProtocolSing2000_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6, 2000 };
oid ss7ProtocolSing2004_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6, 2004 };
oid ss7ProtocolSing2008_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6, 2008 };
oid ss7ProtocolSpan_oid[14] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7 };
oid ss7ProtocolSpan1980_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7, 1980 };
oid ss7ProtocolSpan1984_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7, 1984 };
oid ss7ProtocolSpan1988_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7, 1988 };
oid ss7ProtocolSpan1992_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7, 1992 };
oid ss7ProtocolSpan1996_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7, 1996 };
oid ss7ProtocolSpan2000_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7, 2000 };
oid ss7ProtocolSpan2004_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7, 2004 };
oid ss7ProtocolSpan2008_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7, 2008 };
oid ss7ProtocolPnoc_oid[14] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8 };
oid ss7ProtocolPnoc1980_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8, 1980 };
oid ss7ProtocolPnoc1984_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8, 1984 };
oid ss7ProtocolPnoc1988_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8, 1988 };
oid ss7ProtocolPnoc1992_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8, 1992 };
oid ss7ProtocolPnoc1996_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8, 1996 };
oid ss7ProtocolPnoc2000_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8, 2000 };
oid ss7ProtocolPnoc2004_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8, 2004 };
oid ss7ProtocolPnoc2008_oid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8, 2008 };
oid ss7GeneralCompliance_oid[13] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 2, 1, 1 };
oid ss7Package_oid[13] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 2, 2, 1 };
static oid zeroDotZero_oid[2] = { 0, 0 };
static oid snmpTrapOID_oid[11] = { 1, 3, 6, 1, 6, 3, 1, 1, 4, 1, 0 };

/*
 * variable7 ss7MIB_variables: tree for ss7MIB
 * This variable defines function callbacks and type return information for the ss7MIB mib section
 */
struct variable7 ss7MIB_variables[] = {
	/* magic number, variable type, ro/rw, callback fn, L, oidsuffix */
#define   SS7NETWORKPROTOCOLVARIANT  1
	{(u_char) SS7NETWORKPROTOCOLVARIANT, ASN_OBJECT_ID, RWRITE, var_ss7NetworkTable, 5, {1, 2, 1, 1, 2}},
#define   SS7NETWORKPROTOCOLVERSION  2
	{(u_char) SS7NETWORKPROTOCOLVERSION, ASN_UNSIGNED, RWRITE, var_ss7NetworkTable, 5, {1, 2, 1, 1, 3}},
#define   SS7NETWORKPROTOCOLOPTIONS  3
	{(u_char) SS7NETWORKPROTOCOLOPTIONS, ASN_OCTET_STR, RWRITE, var_ss7NetworkTable, 5, {1, 2, 1, 1, 4}},
#define   SS7NETWORKROWSTATUS   4
	{(u_char) SS7NETWORKROWSTATUS, ASN_INTEGER, RWRITE, var_ss7NetworkTable, 5, {1, 2, 1, 1, 5}},
};

/* (L = length of the oidsuffix) */
struct ss7MIB_data *ss7MIBStorage = NULL;

/* global storage of our data, saved in and configured by header_complex() */
struct header_complex_index *ss7NetworkTableStorage = NULL;

void (*ss7MIBold_signal_handler) (int) = NULL;	/* save old signal handler just in case */
void ss7MIB_loop_handler(int);
void ss7MIB_fd_handler(int, void *);

/**
 * @fn void init_ss7MIB(void)
 * @brief ss7MIB initialization routine.
 *
 * This is called when the agent starts up.  At a minimum, registration of the MIB variables
 * structure (ss7MIB_variables) should take place here.  By default the function also
 * registers the configuration handler and configuration store callbacks.
 *
 * Additional registrations that may be considered here are calls to regsiter_readfd(),
 * register_writefd() and register_exceptfd() for hooking into the snmpd event loop, but only when
 * used as a loadable module.  By default this function establishes a single file descriptor to
 * read, or upon which to handle exceptions.  Note that the snmpd only supports a maximum of 32
 * extneral file descriptors, so these should be used sparingly.
 *
 * When running as a loadable module, it is also necessary to hook into the snmpd event loop so that
 * the current request number can be deteremined.  This is accomplished by using a trick of the
 * external_signal_scheduled and external_signal_handler mechanism which is called on each event
 * loop when external_signal_scheduled is non-zero.  This is used to increment the sa_request value
 * on each snmpd event loop interation so that calls to MIB tree functions can determine whether
 * they belong to a fresh request or not (primarily for cacheing and possibly to clean up non-polled
 * file descriptors).
 */
void
init_ss7MIB(void)
{
	(void) my_fd;
	(void) zeroDotZero_oid;
	(void) snmpTrapOID_oid;
	DEBUGMSGTL(("ss7MIB", "init_ss7MIB: initializing...  "));
	/* register ourselves with the agent to handle our mib tree */
	REGISTER_MIB("ss7MIB", ss7MIB_variables, variable7, ss7MIB_variables_oid);
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_SHUTDOWN, term_ss7MIB, NULL);
	/* register our config handler(s) to deal with registrations */
	snmpd_register_config_handler("ss7MIB", parse_ss7MIB, NULL, "HELP STRING");
	snmpd_register_config_handler("ss7NetworkTable", parse_ss7NetworkTable, NULL, "HELP STRING");

	/* we need to be called back later to store our data */
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_STORE_DATA, store_ss7MIB, NULL);
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_STORE_DATA, store_ss7NetworkTable, NULL);

	/* place any other initialization junk you need here */
	if (my_readfd >= 0) {
		register_readfd(my_readfd, ss7MIB_fd_handler, (void *) 0);
		register_exceptfd(my_readfd, ss7MIB_fd_handler, (void *) 1);
	}
	ss7MIBold_signal_handler = external_signal_handler[SIGCHLD];
	external_signal_handler[SIGCHLD] = &ss7MIB_loop_handler;
	external_signal_scheduled[SIGCHLD] = 1;
	DEBUGMSGTL(("ss7MIB", "done.\n"));
	init_mtpMIB();
	init_mtpOmMIB();
	init_sccpMIB();
	init_sccpOmMIB();
	init_tcapMIB();
	init_tcapOmMIB();
}

/**
 * @fn void deinit_ss7MIB(void)
 * @brief deinitialization routine.
 *
 * This is called before the agent is unloaded.  At a minimum, deregistration of the MIB variables
 * structure (ss7MIB_variables) should take place here.  By default, the function also
 * deregisters the the configuration file handlers for the MIB variables and table rows.
 *
 * Additional deregistrations that may be required here are calls to unregister_readfd(),
 * unregister_writefd() and unregsiter_exceptfd() for unhooking from the snmpd event loop, but only
 * when used as a loadable module.  By default if a read file descriptor exists, it is unregistered.
 */
void
deinit_ss7MIB(void)
{
	deinit_tcapOmMIB();
	deinit_tcapMIB();
	deinit_sccpOmMIB();
	deinit_sccpMIB();
	deinit_mtpOmMIB();
	deinit_mtpMIB();
	DEBUGMSGTL(("ss7MIB", "deinit_ss7MIB: deinitializating...  "));
	external_signal_handler[SIGCHLD] = ss7MIBold_signal_handler;
	if (my_readfd >= 0) {
		unregister_exceptfd(my_readfd);
		unregister_readfd(my_readfd);
		close(my_readfd);
		my_readfd = -1;
	}
	unregister_mib(ss7MIB_variables_oid, sizeof(ss7MIB_variables_oid) / sizeof(oid));
	snmpd_unregister_config_handler("ss7MIB");
	snmpd_unregister_config_handler("ss7NetworkTable");

	/* place any other de-initialization junk you need here */
	DEBUGMSGTL(("ss7MIB", "done.\n"));
}

int
term_ss7MIB(int majorID, int minorID, void *serverarg, void *clientarg)
{
	DEBUGMSGTL(("ss7MIB", "term_ss7MIB: terminating...  "));
	deinit_ss7MIB();
	DEBUGMSGTL(("ss7MIB", "done.\n"));
	return 0;
}

/**
 * @fn struct ss7MIB_data *ss7MIB_create(void)
 * @brief create a fresh data structure representing scalars in ss7MIB.
 *
 * Creates a new ss7MIB_data structure by allocating dynamic memory for the structure and
 * initializing the default values of scalars in ss7MIB.
 */
struct ss7MIB_data *
ss7MIB_create(void)
{
	struct ss7MIB_data *StorageNew = SNMP_MALLOC_STRUCT(ss7MIB_data);

	DEBUGMSGTL(("ss7MIB", "ss7MIB_create: creating scalars...  "));
	if (StorageNew != NULL) {
		/* XXX: fill in default scalar values here into StorageNew */

	}
      done:
	DEBUGMSGTL(("ss7MIB", "done.\n"));
	return (StorageNew);
	goto nomem;
      nomem:
	ss7MIB_destroy(&StorageNew);
	goto done;
}

/**
 * @fn struct ss7MIB_data *ss7MIB_duplicate(struct ss7MIB_data *thedata)
 * @param thedata the mib structure to duplicate
 * @brief duplicate a mib structure for the mib
 *
 * Duplicates the specified mib structure @param thedata and returns a pointer to the newly
 * allocated mib structure on success, or NULL on failure.
 */
struct ss7MIB_data *
ss7MIB_duplicate(struct ss7MIB_data *thedata)
{
	struct ss7MIB_data *StorageNew = SNMP_MALLOC_STRUCT(ss7MIB_data);

	DEBUGMSGTL(("ss7MIB", "ss7MIB_duplicate: duplicating mib... "));
	if (StorageNew != NULL) {
	}
      done:
	DEBUGMSGTL(("ss7MIB", "done.\n"));
	return (StorageNew);
	goto destroy;
      destroy:
	ss7MIB_destroy(&StorageNew);
	goto done;
}

/**
 * @fn int ss7MIB_destroy(struct ss7MIB_data **thedata)
 * @param thedata pointer to the data structure in ss7MIB.
 * @brief delete a scalars structure from ss7MIB.
 *
 * Frees scalars that were previously removed from ss7MIB.  Note that the strings associated
 * with octet strings, object identifiers and bit strings still attached to the structure will also
 * be freed.  The pointer that was passed in @param thedata will be set to NULL if it is not already
 * NULL.
 */
int
ss7MIB_destroy(struct ss7MIB_data **thedata)
{
	struct ss7MIB_data *StorageDel;

	DEBUGMSGTL(("ss7MIB", "ss7MIB_destroy: deleting scalars...  "));
	if ((StorageDel = *thedata) != NULL) {
		SNMP_FREE(StorageDel);
		*thedata = StorageDel;
	}
	DEBUGMSGTL(("ss7MIB", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int ss7MIB_add(struct ss7MIB_data *thedata)
 * @param thedata the structure representing ss7MIB scalars.
 * @brief adds node to the ss7MIB scalar data set.
 *
 * Adds a scalar structure to the ss7MIB data set.  Note that this function is necessary even
 * when the scalar values are not peristent.
 */
int
ss7MIB_add(struct ss7MIB_data *thedata)
{
	DEBUGMSGTL(("ss7MIB", "ss7MIB_add: adding data...  "));
	if (thedata)
		ss7MIBStorage = thedata;
	DEBUGMSGTL(("ss7MIB", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn void parse_ss7MIB(const char *token, char *line)
 * @param token token used within the configuration file.
 * @param line line from configuration file matching the token.
 * @brief parse configuration file for ss7MIB entries.
 *
 * This callback is called by UCD-SNMP when it parses a configuration file and finds a configuration
 * file line for the registsred token (in this case ss7MIB).  This routine is invoked by
 * UCD-SNMP to read the values of scalars in the MIB from the configuration file.  Note that this
 * procedure may exist regardless of the persistence of the MIB.  If there are no configured entries
 * in the configuration MIB, this function will simply not be called.
 */
void
parse_ss7MIB(const char *token, char *line)
{
	size_t tmpsize;
	struct ss7MIB_data *StorageTmp = ss7MIB_create();

	DEBUGMSGTL(("ss7MIB", "parse_ss7MIB: parsing config...  "));
	if (StorageTmp == NULL) {
		config_perror("malloc failure");
		return;
	}
	/* XXX: remove individual scalars that are not persistent */
	ss7MIB_add(StorageTmp);
	(void) tmpsize;
	DEBUGMSGTL(("ss7MIB", "done.\n"));
}

/*
 * store_ss7MIB(): stores .conf file entries needed to configure the mib.
 */
int
store_ss7MIB(int majorID, int minorID, void *serverarg, void *clientarg)
{
	char line[SNMP_MAXBUF];
	char *cptr;
	size_t tmpsize;
	struct ss7MIB_data *StorageTmp;

	DEBUGMSGTL(("ss7MIB", "store_ss7MIB: storing data...  "));
	refresh_ss7MIB(1);
	if ((StorageTmp = ss7MIBStorage) == NULL) {
		DEBUGMSGTL(("ss7MIB", "error.\n"));
		return SNMPERR_GENERR;
	}
	(void) tmpsize;
	/* XXX: comment entire section if no scalars are persistent */
	if (0) {
		memset(line, 0, sizeof(line));
		strcat(line, "ss7MIB ");
		cptr = line + strlen(line);
		(void) cptr;
		/* XXX: remove individual scalars that are not persistent */
		snmpd_store_config(line);
	}
	DEBUGMSGTL(("ss7MIB", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int check_ss7MIB(struct ss7MIB_data *StorageTmp, struct ss7MIB_data *StorageOld)
 * @param StorageTmp the data as updated
 * @param StorageOld the data previous to update
 *
 * This function is used by mibs.  It is used to check, all scalars at a time, the varbinds
 * belonging to the mib.  This function is called for the first varbind in a mib at the beginning of
 * the ACTION phase.  The COMMIT phase does not ensue unless this check passes.  This function can
 * return SNMP_ERR_NOERR or a specific SNMP error value.  Values in StorageOld are the values before
 * the varbinds on the mib were applied; the values in StorageTmp are the new values.  The function
 * is permitted to change the values in StorageTmp to correct them; however, preferences should be
 * made for setting values that were not in the varbinds.
 */
int
check_ss7MIB(struct ss7MIB_data *StorageTmp, struct ss7MIB_data *StorageOld)
{
	/* XXX: provide code to check the scalars for consistency */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int update_ss7MIB(struct ss7MIB_data *StorageTmp, struct ss7MIB_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the set operation (ACTION phase)
 *
 * This function is used by mibs.  It is used to update, all scalars at a time, the varbinds
 * belonging to the mib.  This function is called for the first varbind in a mib at the beginning of
 * the COMMIT phase.  The start of the ACTION phase performs a consistency check on the mib before
 * allowing the request to proceed to the COMMIT phase.  The COMMIT phase then arrives here with
 * consistency already checked (see check_ss7MIB()).  This function can
 * return SNMP_ERR_NOERROR or SNMP_ERR_COMMITFAILED.  Values in StorageOld are the values before the
 * varbinds on the mib were applied: the values in StorageTmp are the new values.
 */
int
update_ss7MIB(struct ss7MIB_data *StorageTmp, struct ss7MIB_data *StorageOld)
{
	/* XXX: provide code to update the row with the underlying device */
	ss7MIB_refresh = 1;
	return SNMP_ERR_NOERROR;
}

/**
 * @fn revert_ss7MIB(struct 
 * @fn void revert_ss7MIB(struct ss7MIB_data *StorageTmp, struct ss7MIB_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the undo operation (UNDO phase)
 */
void
revert_ss7MIB(struct ss7MIB_data *StorageTmp, struct ss7MIB_data *StorageOld)
{
	/* XXX: provide code to revert the row with the underlying device */
	update_ss7MIB(StorageOld, NULL);
}

/**
 * @fn void refresh_ss7MIB(int force)
 * @param force forced refresh when non-zero.
 * @brief refresh the scalar values of ss7MIB.
 *
 * Normally the values retrieved from the operating system are cached.  When the agent receives a
 * SIGPOLL from an open STREAMS configuration or administrative driver Stream, the STREAMS subsystem
 * indicates to the agent that the cache has been invalidated and that it should reread scalars and
 * tables from the STREAMS subsystem.  This function is used when the agent starts for the first
 * time, or after a SIGPOLL has been received (and a scalar has been requested).
 */
void
refresh_ss7MIB(int force)
{
	if (ss7MIBStorage == NULL) {
		struct ss7MIB_data *StorageNew;

		if ((StorageNew = ss7MIB_create()) == NULL)
			return;
		ss7MIBStorage = StorageNew;
		ss7MIB_refresh = 1;
	}
	if (!force && ss7MIB_refresh == 0)
		return;
	DEBUGMSGTL(("ss7MIB", "refresh_ss7MIB: refreshing...  "));
	/* XXX: Update scalars as required here... */
	ss7MIB_refresh = 0;
	DEBUGMSGTL(("ss7MIB", "done.\n"));
}

/**
 * @fn u_char * var_ss7MIB(struct variable *vp, oid *name, size_t *length, int exact, size_t *var_len, WriteMethod **write_method)
 * @param vp a pointer to the entry in the variables table for the requested variable.
 * @param name the object identifier for which to find.
 * @param length the length of the object identifier.
 * @param exact whether the name is exact.
 * @param var_len a pointer to the length of the representation of the object.
 * @param write_method a pointer to a write method for the object.
 * @brief locate variables in ss7MIB.
 *
 * This function returns a pointer to a memory area that is static across the request that contains
 * the UCD-SNMP representation of the scalar (so that it may be used to read from for a GET,
 * GET-NEXT or GET-BULK request).  This returned pointer may be NULL, in which case the function is
 * telling UCD-SNMP that the scalar does not exist for reading; however, if write_method is
 * overwritten with a non-NULL value, the function is telling UCD-SNMP that the scalar exists for
 * writing.  Write-only objects can be effected in this way.
 */
u_char *
var_ss7MIB(struct variable *vp, oid * name, size_t *length, int exact, size_t *var_len, WriteMethod ** write_method)
{
	struct ss7MIB_data *StorageTmp;
	u_char *rval;

	DEBUGMSGTL(("ss7MIB", "var_ss7MIB: lookup up varbind...  "));
	if (header_generic(vp, name, length, exact, var_len, write_method) == MATCH_FAILED)
		return NULL;
	/* Refresh the MIB values if required. */
	refresh_ss7MIB(0);
	if ((StorageTmp = ss7MIBStorage) == NULL) {
		DEBUGMSGTL(("ss7MIB", "no datastructure.\n"));
		return NULL;
	}
	*write_method = NULL;
	*var_len = 0;
	rval = NULL;
	/* This is where we do the value assignments for the mib results. */
	switch (vp->magic) {
	default:
		ERROR_MSG("");
	}
	if (rval)
		DEBUGMSGTL(("ss7MIB", "found.\n"));
	else
		DEBUGMSGTL(("ss7MIB", "not found.\n"));
	return (rval);
}

/**
 * @fn struct ss7NetworkTable_data *ss7NetworkTable_create(void)
 * @brief create a fresh data structure representing a new row in the ss7NetworkTable table.
 *
 * Creates a new ss7NetworkTable_data structure by allocating dynamic memory for the structure and
 * initializing the default values of columns in the table.  The row status object, if any, should
 * be set to RS_NOTREADY.
 */
struct ss7NetworkTable_data *
ss7NetworkTable_create(void)
{
	struct ss7NetworkTable_data *StorageNew = SNMP_MALLOC_STRUCT(ss7NetworkTable_data);

	DEBUGMSGTL(("ss7MIB", "ss7NetworkTable_create: creating row...  "));
	if (StorageNew != NULL) {
		/* XXX: fill in default row values here into StorageNew */
		{
			static oid tmpoid[15] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3, 2000 };
			if ((StorageNew->ss7NetworkProtocolVariant = snmp_duplicate_objid(tmpoid, 15)) == NULL)
				goto nomem;
			StorageNew->ss7NetworkProtocolVariantLen = 15;
		}
		StorageNew->ss7NetworkProtocolVersion = 2000;
		if ((StorageNew->ss7NetworkProtocolOptions = malloc(1)) == NULL)
			goto nomem;
		StorageNew->ss7NetworkProtocolOptionsLen = 0;
		StorageNew->ss7NetworkProtocolOptions[StorageNew->ss7NetworkProtocolOptionsLen] = 0;
		StorageNew->ss7NetworkRowStatus = 0;
		StorageNew->ss7NetworkRowStatus = RS_NOTREADY;
	}
      done:
	DEBUGMSGTL(("ss7MIB", "done.\n"));
	return (StorageNew);
	goto nomem;
      nomem:
	ss7NetworkTable_destroy(&StorageNew);
	goto done;
}

/**
 * @fn struct ss7NetworkTable_data *ss7NetworkTable_duplicate(struct ss7NetworkTable_data *thedata)
 * @param thedata the row structure to duplicate.
 * @brief duplicate a row structure for a table.
 *
 * Duplicates the specified row structure @param thedata and returns a pointer to the newly
 * allocated row structure on success, or NULL on failure.
 */
struct ss7NetworkTable_data *
ss7NetworkTable_duplicate(struct ss7NetworkTable_data *thedata)
{
	struct ss7NetworkTable_data *StorageNew = SNMP_MALLOC_STRUCT(ss7NetworkTable_data);

	DEBUGMSGTL(("ss7MIB", "ss7NetworkTable_duplicate: duplicating row...  "));
	if (StorageNew != NULL) {
		StorageNew->ss7NetworkTable_id = thedata->ss7NetworkTable_id;
		StorageNew->ss7NetworkId = thedata->ss7NetworkId;
		if (!(StorageNew->ss7NetworkProtocolVariant = snmp_duplicate_objid(thedata->ss7NetworkProtocolVariant, thedata->ss7NetworkProtocolVariantLen / sizeof(oid))))
			goto destroy;
		StorageNew->ss7NetworkProtocolVariantLen = thedata->ss7NetworkProtocolVariantLen;
		StorageNew->ss7NetworkProtocolVersion = thedata->ss7NetworkProtocolVersion;
		if (!(StorageNew->ss7NetworkProtocolOptions = malloc(thedata->ss7NetworkProtocolOptionsLen + 1)))
			goto destroy;
		memcpy(StorageNew->ss7NetworkProtocolOptions, thedata->ss7NetworkProtocolOptions, thedata->ss7NetworkProtocolOptionsLen);
		StorageNew->ss7NetworkProtocolOptionsLen = thedata->ss7NetworkProtocolOptionsLen;
		StorageNew->ss7NetworkProtocolOptions[StorageNew->ss7NetworkProtocolOptionsLen] = 0;
		StorageNew->ss7NetworkRowStatus = thedata->ss7NetworkRowStatus;
	}
      done:
	DEBUGMSGTL(("ss7MIB", "done.\n"));
	return (StorageNew);
	goto destroy;
      destroy:
	ss7NetworkTable_destroy(&StorageNew);
	goto done;
}

/**
 * @fn int ss7NetworkTable_destroy(struct ss7NetworkTable_data **thedata)
 * @param thedata pointer to the extracted or existing data structure in the table.
 * @brief delete a row structure from a table.
 *
 * Frees a table row that was previously removed from a table.  Note that the strings associated
 * with octet strings, object identifiers and bit strings still attached to the structure will also
 * be freed.  The pointer that was passed in @param thedata will be set to NULL if it is not already
 * NULL.
 */
int
ss7NetworkTable_destroy(struct ss7NetworkTable_data **thedata)
{
	struct ss7NetworkTable_data *StorageDel;

	DEBUGMSGTL(("ss7MIB", "ss7NetworkTable_destroy: deleting row...  "));
	if ((StorageDel = *thedata) != NULL) {
		SNMP_FREE(StorageDel->ss7NetworkProtocolVariant);
		StorageDel->ss7NetworkProtocolVariantLen = 0;
		SNMP_FREE(StorageDel->ss7NetworkProtocolOptions);
		StorageDel->ss7NetworkProtocolOptionsLen = 0;
		SNMP_FREE(StorageDel);
		*thedata = StorageDel;
	}
	DEBUGMSGTL(("ss7MIB", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int ss7NetworkTable_add(struct ss7NetworkTable_data *thedata)
 * @param thedata the structure representing the new row in the table.
 * @brief adds a row to the ss7NetworkTable table data set.
 *
 * Adds a table row structure to the ss7NetworkTable table.  Note that this function is necessary even
 * when the table rows are not peristent.  This function can be used within this MIB or other MIBs
 * by the agent to create rows within the table autonomously.
 */
int
ss7NetworkTable_add(struct ss7NetworkTable_data *thedata)
{
	struct variable_list *vars = NULL;

	DEBUGMSGTL(("ss7MIB", "ss7NetworkTable_add: adding data...  "));
	if (thedata) {
		/* add the index variables to the varbind list, which is used by header_complex to index the data */
		/* ss7NetworkId */
		snmp_varlist_add_variable(&vars, NULL, 0, ASN_INTEGER, (u_char *) &thedata->ss7NetworkId, sizeof(thedata->ss7NetworkId));
		header_complex_add_data(&ss7NetworkTableStorage, vars, thedata);
	}
	DEBUGMSGTL(("ss7MIB", "registered an entry.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int ss7NetworkTable_del(struct ss7NetworkTable_data *thedata)
 * @param thedata pointer to the extracted or existing data structure in the table.
 * @brief delete a row structure from a table.
 *
 * Deletes a table row structure from the ss7NetworkTable table but does not free it.  Note that this
 * function is necessary even when the table rows are not persistent.  This function can be used
 * within this MIB or another MIB by the agent to delete rows from the table autonomously.  The data
 * structure may either be already extracted from the data set, or the structure may still exist in
 * the data set.  This function will extract the row from the table if it has not already been
 * performed by the caller.
 */
int
ss7NetworkTable_del(struct ss7NetworkTable_data *thedata)
{
	struct ss7NetworkTable_data *StorageDel;

	DEBUGMSGTL(("ss7MIB", "ss7NetworkTable_data: deleting data...  "));
	if ((StorageDel = thedata) != NULL) {
		struct header_complex_index *hciptr;

		if ((hciptr = header_complex_find_entry(ss7NetworkTableStorage, StorageDel)) != NULL)
			header_complex_extract_entry(&ss7NetworkTableStorage, hciptr);
	}
	DEBUGMSGTL(("ss7MIB", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn void parse_ss7NetworkTable(const char *token, char *line)
 * @param token token used within the configuration file.
 * @param line line from configuration file matching the token.
 * @brief parse configuration file for ss7NetworkTable entries.
 *
 * This callback is called by UCD-SNMP when it parses a configuration file and finds a configuration
 * file line for the registsred token (in this case ss7NetworkTable).  This routine is invoked by UCD-SNMP
 * to read the values of each row in the table from the configuration file.  Note that this
 * procedure may exist regardless of the persistence of the table.  If there are no configured
 * entries in the configuration table, this function will simply not be called.
 */
void
parse_ss7NetworkTable(const char *token, char *line)
{
	size_t tmpsize;
	struct ss7NetworkTable_data *StorageTmp = ss7NetworkTable_create();

	DEBUGMSGTL(("ss7MIB", "parse_ss7NetworkTable: parsing config...  "));
	if (StorageTmp == NULL) {
		config_perror("malloc failure");
		return;
	}
	/* XXX: remove individual columns if not persistent */
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->ss7NetworkId, &tmpsize);
	SNMP_FREE(StorageTmp->ss7NetworkProtocolVariant);
	line = read_config_read_data(ASN_OBJECT_ID, line, &StorageTmp->ss7NetworkProtocolVariant, &StorageTmp->ss7NetworkProtocolVariantLen);
	if (StorageTmp->ss7NetworkProtocolVariant == NULL) {
		config_perror("invalid specification for ss7NetworkProtocolVariant");
		return;
	}
	line = read_config_read_data(ASN_UNSIGNED, line, &StorageTmp->ss7NetworkProtocolVersion, &tmpsize);
	SNMP_FREE(StorageTmp->ss7NetworkProtocolOptions);
	line = read_config_read_data(ASN_OCTET_STR, line, &StorageTmp->ss7NetworkProtocolOptions, &StorageTmp->ss7NetworkProtocolOptionsLen);
	if (StorageTmp->ss7NetworkProtocolOptions == NULL) {
		config_perror("invalid specification for ss7NetworkProtocolOptions");
		return;
	}
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->ss7NetworkRowStatus, &tmpsize);
	ss7NetworkTable_add(StorageTmp);
	(void) tmpsize;
	DEBUGMSGTL(("ss7MIB", "done.\n"));
}

/*
 * store_ss7NetworkTable(): store configuraiton file for ss7NetworkTable
 * stores .conf file entries needed to configure the mib.
 */
int
store_ss7NetworkTable(int majorID, int minorID, void *serverarg, void *clientarg)
{
	char line[SNMP_MAXBUF];
	char *cptr;
	size_t tmpsize;
	struct ss7NetworkTable_data *StorageTmp;
	struct header_complex_index *hcindex;

	DEBUGMSGTL(("ss7MIB", "store_ss7NetworkTable: storing data...  "));
	refresh_ss7NetworkTable(1);
	(void) tmpsize;
	for (hcindex = ss7NetworkTableStorage; hcindex != NULL; hcindex = hcindex->next) {
		StorageTmp = (struct ss7NetworkTable_data *) hcindex->data;
		/* XXX: comment entire section if row not persistent */
		{
			memset(line, 0, sizeof(line));
			strcat(line, "ss7NetworkTable ");
			cptr = line + strlen(line);
			(void) cptr;
			/* XXX: remove individual columns if not persistent */
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->ss7NetworkId, &tmpsize);
			cptr = read_config_store_data(ASN_OBJECT_ID, cptr, &StorageTmp->ss7NetworkProtocolVariant, &StorageTmp->ss7NetworkProtocolVariantLen);
			cptr = read_config_store_data(ASN_UNSIGNED, cptr, &StorageTmp->ss7NetworkProtocolVersion, &tmpsize);
			cptr = read_config_store_data(ASN_OCTET_STR, cptr, &StorageTmp->ss7NetworkProtocolOptions, &StorageTmp->ss7NetworkProtocolOptionsLen);
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->ss7NetworkRowStatus, &tmpsize);
			snmpd_store_config(line);
		}
	}
	DEBUGMSGTL(("ss7MIB", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int activate_ss7NetworkTable_row(struct ss7NetworkTable_data *StorageTmp)
 * @param StorageTmp the data row to activate
 * @brief commit activation of a row to the underlying device
 *
 * This function is used by tables that contain a RowStatus object.  It is used to move the row from
 * the RS_NOTINSERVICE state to the RS_ACTIVE state.  It is also used when transitioning from the
 * RS_CREATEANDGO state to the RS_ACTIVE state.  If activation fails, the function should return
 * SNMP_ERR_COMMITFAILED; otherwise, SNMP_ERR_NOERROR.
 */
int
activate_ss7NetworkTable_row(struct ss7NetworkTable_data *StorageTmp)
{
	/* XXX: provide code to activate the row with the underlying device */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int deactivate_ss7NetworkTable_row(struct ss7NetworkTable_data *StorageTmp)
 * @param StorageTmp the data row to deactivate
 * @brief commit deactivation of a row to the underlying device
 *
 * This function is used by tables that contain a RowStatus object.  It is used to move the row from
 * the RS_ACTIVE state to the RS_NOTINSERVICE state.  It is also used when transitioning from the
 * RS_ACTIVE state to the RS_DESTROY state.  If deactivation fails, the function should return
 * SNMP_ERR_COMMITFAILED; otherwise, SNMP_ERR_NOERROR.
 */
int
deactivate_ss7NetworkTable_row(struct ss7NetworkTable_data *StorageTmp)
{
	/* XXX: provide code to deactivate the row with the underlying device */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int check_ss7NetworkTable_row(struct ss7NetworkTable_data *StorageTmp, struct ss7NetworkTable_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 *
 * This function is used both by tables that do and do not contain a RowStatus object.  It is used
 * to check, row-at-a-time, the varbinds belonging to the row.  Note that this function is not used
 * when rows are created or destroyed.  This function is called for the first varbind in a row at
 * the beginning of the ACTION phase.  The start of the ACTION pahse performs this consitency check
 * on the row before allowing the request to proceed to the COMMIT phase.  This function can return
 * SNMP_ERR_NOERR or a specific SNMP error value.  Values in StorageOld are the values before the
 * varbinds on the mib were applied; the values in StorageTmp are the new values.  The function is
 * permitted to change the values in StorageTmp to correct them; however, preference should be made
 * for setting values where were not in the varbinds.
 */
int
check_ss7NetworkTable_row(struct ss7NetworkTable_data *StorageTmp, struct ss7NetworkTable_data *StorageOld)
{
	/* XXX: provide code to check the row for consistency */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int update_ss7NetworkTable_row(struct ss7NetworkTable_data *StorageTmp, struct ss7NetworkTable_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the set operation (ACTION phase) on a row
 *
 * This function is used both by tables that do and do not contain a RowStatus object.  It is used
 * to update, row-at-a-time, the varbinds belonging to the row.  Note that this function is not used
 * when rows are created or destroyed.  This function is called for the first varbind in a row at
 * the beginning of the COMMIT phase.  The start of the ACTION phase performs a consistency check on
 * the row before allowing the request to proceed to the COMMIT phase.  The COMMIT phase then
 * arrives here with consistency already checked (see check_ss7NetworkTable_row()).  This function can
 * return SNMP_ERR_NOERROR or SNMP_ERR_COMMITFAILED.  Values in StorageOld are the values before the
 * varbinds on the row were applied: the values in StorageTmp are the new values.
 */
int
update_ss7NetworkTable_row(struct ss7NetworkTable_data *StorageTmp, struct ss7NetworkTable_data *StorageOld)
{
	/* XXX: provide code to update the row with the underlying device */
	ss7NetworkTable_refresh = 1;
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int revert_ss7NetworkTable_row(struct ss7NetworkTable_data *StorageTmp, struct ss7NetworkTable_data *StorageOld)
 * @param StorageTmp the data as updated.
 * @param StorageOld the data previous to update.
 * @brief perform the undo operation (UNDO phase) on a row
 */
void
revert_ss7NetworkTable_row(struct ss7NetworkTable_data *StorageTmp, struct ss7NetworkTable_data *StorageOld)
{
	/* XXX: provide code to revert the row with the underlying device */
	update_ss7NetworkTable_row(StorageOld, NULL);
}

/**
 * @fn void refresh_ss7NetworkTable_row(struct ss7NetworkTable_data *StorageTmp, int force)
 * @param StorageTmp the data row to refresh.
 * @param force force refresh if non-zero.
 * @brief refresh the contents of the ss7NetworkTable row.
 *
 * Normally the values retrieved from the operating system are cached.  However, if a row contains
 * temporal values, such as statistics counters, gauges, timestamps, or other transient columns, it
 * may be necessary to refresh the row on some other basis, but normally only once per request.
 */
struct ss7NetworkTable_data *
refresh_ss7NetworkTable_row(struct ss7NetworkTable_data *StorageTmp, int force)
{
	if (!StorageTmp || (!force && StorageTmp->ss7NetworkTable_request == sa_request))
		return (StorageTmp);
	/* XXX: update row; delete it and return NULL if the row has disappeared */
	StorageTmp->ss7NetworkTable_request = sa_request;
	return (StorageTmp);
}

/**
 * @fn void refresh_ss7NetworkTable(int force)
 * @param force force refresh if non-zero.
 * @brief refresh the scalar values of the ss7NetworkTable.
 *
 * Normally the values retrieved from the operating system are cached.  When the agent receives a
 * SIGPOLL from an open STREAMS configuration or administrative driver Stream, the STREAMS subsystem
 * indicates to the agent that the cache has been invalidated and that it should reread scalars and
 * tables from the STREAMS subsystem.  This function is used when the agent starts for the first
 * time, or after a SIGPOLL has been received (and a row or column has been requested).
 */
void
refresh_ss7NetworkTable(int force)
{
	if (!force && ss7NetworkTable_refresh == 0)
		return;
	/* XXX: Here, update the table as required... */
	ss7NetworkTable_refresh = 0;
}

/**
 * @fn u_char *var_ss7NetworkTable(struct variable *vp, oid *name, size_t *length, int exact, size_t *var_len, WriteMethod **write_method)
 * @brief locate variables in ss7NetworkTable.
 *
 * Handle this table separately from the scalar value case.  The workings of this are basically the
 * same as for var_ss7MIB above.
 */
u_char *
var_ss7NetworkTable(struct variable *vp, oid * name, size_t *length, int exact, size_t *var_len, WriteMethod ** write_method)
{
	struct ss7NetworkTable_data *StorageTmp = NULL;
	u_char *rval;

	DEBUGMSGTL(("ss7MIB", "var_ss7NetworkTable: Entering...  \n"));
	/* Make sure that the storage data does not need to be refreshed before checking the header. */
	refresh_ss7NetworkTable(0);
	/* This assumes you have registered all your data properly with header_complex_add() somewhere before this. */
	while ((StorageTmp = header_complex(ss7NetworkTableStorage, vp, name, length, exact, var_len, write_method)))
		if ((StorageTmp = refresh_ss7NetworkTable_row(StorageTmp, 0)) || exact)
			break;
	*write_method = NULL;
	*var_len = 0;
	rval = NULL;
	/* This is where we do the value assignments for the mib results. */
	switch (vp->magic) {
	case (u_char) SS7NETWORKPROTOCOLVARIANT:	/* Create */
		*write_method = write_ss7NetworkProtocolVariant;
		if (!StorageTmp)
			break;
		*var_len = StorageTmp->ss7NetworkProtocolVariantLen * sizeof(oid);
		rval = (u_char *) StorageTmp->ss7NetworkProtocolVariant;
		break;
	case (u_char) SS7NETWORKPROTOCOLVERSION:	/* Create */
		*write_method = write_ss7NetworkProtocolVersion;
		if (!StorageTmp)
			break;
		*var_len = sizeof(StorageTmp->ss7NetworkProtocolVersion);
		rval = (u_char *) &StorageTmp->ss7NetworkProtocolVersion;
		break;
	case (u_char) SS7NETWORKPROTOCOLOPTIONS:	/* Create */
		*write_method = write_ss7NetworkProtocolOptions;
		if (!StorageTmp)
			break;
		*var_len = StorageTmp->ss7NetworkProtocolOptionsLen;
		rval = (u_char *) StorageTmp->ss7NetworkProtocolOptions;
		break;
	case (u_char) SS7NETWORKROWSTATUS:	/* Create */
		*write_method = write_ss7NetworkRowStatus;
		if (!StorageTmp)
			break;
		*var_len = sizeof(StorageTmp->ss7NetworkRowStatus);
		rval = (u_char *) &StorageTmp->ss7NetworkRowStatus;
		break;
	default:
		ERROR_MSG("");
	}
	return (rval);
}

/**
 * @fn int write_ss7NetworkProtocolVariant(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid *name, size_t name_len)
 * @param action the stage of the SET operation.
 * @param var_val pointer to the varbind value.
 * @param var_val_type the ASN type.
 * @param var_val_len the length of the varbind value.
 * @param statP static pointer.
 * @param name the varbind OID.
 * @param name_len number of elements in OID.
 * @brief Table row and column write routine.
 */
int
write_ss7NetworkProtocolVariant(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	struct ss7NetworkTable_data *StorageTmp = NULL, *StorageOld = NULL;
	size_t newlen = name_len - 15;
	oid *objid = NULL;
	int ret = SNMP_ERR_NOERROR;

	DEBUGMSGTL(("ss7MIB", "write_ss7NetworkProtocolVariant entering action=%d...  \n", action));
	if (StorageTmp == NULL)
		return SNMP_ERR_NOSUCHNAME;
	StorageTmp = header_complex(ss7NetworkTableStorage, NULL, &name[15], &newlen, 1, NULL, NULL);
	switch (action) {
	case RESERVE1:
		if (StorageTmp != NULL && statP == NULL) {
			/* have row but no column */
			switch (StorageTmp->ss7NetworkRowStatus) {
			case RS_ACTIVE:
				/* cannot create non-existent column while active */
				snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkProtocolVariant: but column non-existent\n");
				return SNMP_ERR_INCONSISTENTVALUE;
			case RS_NOTINSERVICE:
			case RS_NOTREADY:
				/* assume column can be created */
				break;
			}
		}
		if (var_val_type != ASN_OBJECT_ID) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkProtocolVariant not ASN_OBJECT_ID\n");
			return SNMP_ERR_WRONGTYPE;
		}
		if (MIN_OID_LEN * sizeof(oid) > var_val_len || var_val_len > MAX_OID_LEN * sizeof(oid)) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkProtocolVariant: bad length\n");
			return SNMP_ERR_WRONGLENGTH;
		}
		/* Note: default value ss7ProtocolAnsi2000 */
		/* one allocation for the whole row */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) == NULL)
			if (StorageTmp->ss7NetworkTable_rsvs == 0)
				if ((StorageOld = StorageTmp->ss7NetworkTable_old = ss7NetworkTable_duplicate(StorageTmp)) == NULL)
					return SNMP_ERR_RESOURCEUNAVAILABLE;
		if (StorageOld != NULL)
			StorageTmp->ss7NetworkTable_rsvs++;
		if ((objid = snmp_duplicate_objid((void *) var_val, var_val_len / sizeof(oid))) == NULL)
			return SNMP_ERR_RESOURCEUNAVAILABLE;
		SNMP_FREE(StorageTmp->ss7NetworkProtocolVariant);
		StorageTmp->ss7NetworkProtocolVariant = objid;
		StorageTmp->ss7NetworkProtocolVariantLen = var_val_len / sizeof(oid);
		/* XXX: insert code to consistency check this particular varbind, if necessary (so error codes are applied to varbinds) */
		break;
	case RESERVE2:		/* memory reseveration, final preparation... */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) != NULL) {
			/* one consistency check for the whole row */
			if (StorageTmp->ss7NetworkTable_tsts == 0)
				if ((ret = check_ss7NetworkTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->ss7NetworkTable_tsts++;
		}
		break;
	case ACTION:		/* The variable has been stored in StorageTmp->ss7NetworkProtocolVariant for you to use, and you have just been asked to do something with it.  Note that anything done 
				   here must be reversable in the UNDO case */
		if (StorageTmp == NULL)
			return SNMP_ERR_NOSUCHNAME;
		/* XXX: insert code to set this particular varbind, if necessary */
		/* one set action for the whole row */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) != NULL) {
			/* XXX: insert code to set this particular varbind, if necessary */
			if (StorageTmp->ss7NetworkTable_sets == 0)
				if ((ret = update_ss7NetworkTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->ss7NetworkTable_sets++;
		}
		break;
	case COMMIT:		/* Things are working well, so it's now safe to make the change permanently.  Make sure that anything done here can't fail! */
		/* one commit for the whole mib */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) != NULL) {
			ss7NetworkTable_destroy(&StorageTmp->ss7NetworkTable_old);
			StorageTmp->ss7NetworkTable_rsvs = 0;
			StorageTmp->ss7NetworkTable_tsts = 0;
			StorageTmp->ss7NetworkTable_sets = 0;
		}
		break;
	case UNDO:		/* Back out any changes made in the ACTION case */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) == NULL)
			break;
		/* XXX: insert code to undo any action performed on this particular varbind */
		if (--StorageTmp->ss7NetworkTable_sets == 0)
			revert_ss7NetworkTable_row(StorageTmp, StorageOld);
		/* fall through */
	case FREE:		/* Release any resources that have been allocated */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) == NULL)
			break;
		if (StorageOld->ss7NetworkProtocolVariant != NULL) {
			SNMP_FREE(StorageTmp->ss7NetworkProtocolVariant);
			StorageTmp->ss7NetworkProtocolVariant = StorageOld->ss7NetworkProtocolVariant;
			StorageTmp->ss7NetworkProtocolVariantLen = StorageOld->ss7NetworkProtocolVariantLen;
			StorageOld->ss7NetworkProtocolVariant = NULL;
			StorageOld->ss7NetworkProtocolVariantLen = 0;
		}
		if (--StorageTmp->ss7NetworkTable_rsvs == 0)
			ss7NetworkTable_destroy(&StorageTmp->ss7NetworkTable_old);
		break;
	}
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int write_ss7NetworkProtocolVersion(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid *name, size_t name_len)
 * @param action the stage of the SET operation.
 * @param var_val pointer to the varbind value.
 * @param var_val_type the ASN type.
 * @param var_val_len the length of the varbind value.
 * @param statP static pointer.
 * @param name the varbind OID.
 * @param name_len number of elements in OID.
 * @brief Table row and column write routine.
 */
int
write_ss7NetworkProtocolVersion(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	struct ss7NetworkTable_data *StorageTmp = NULL, *StorageOld = NULL;
	size_t newlen = name_len - 15;
	ulong set_value = *((ulong *) var_val);
	int ret = SNMP_ERR_NOERROR;

	DEBUGMSGTL(("ss7MIB", "write_ss7NetworkProtocolVersion entering action=%d...  \n", action));
	if (StorageTmp == NULL)
		return SNMP_ERR_NOSUCHNAME;
	StorageTmp = header_complex(ss7NetworkTableStorage, NULL, &name[15], &newlen, 1, NULL, NULL);
	switch (action) {
	case RESERVE1:
		if (StorageTmp != NULL && statP == NULL) {
			/* have row but no column */
			switch (StorageTmp->ss7NetworkRowStatus) {
			case RS_ACTIVE:
				/* cannot create non-existent column while active */
				snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkProtocolVersion: but column non-existent\n");
				return SNMP_ERR_INCONSISTENTVALUE;
			case RS_NOTINSERVICE:
			case RS_NOTREADY:
				/* assume column can be created */
				break;
			}
		}
		if (var_val_type != ASN_UNSIGNED) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkProtocolVersion not ASN_UNSIGNED\n");
			return SNMP_ERR_WRONGTYPE;
		}
		if (var_val_len > sizeof(uint32_t)) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkProtocolVersion: bad length\n");
			return SNMP_ERR_WRONGLENGTH;
		}
		/* Note: default value 2000 */
		/* Note: ranges 1984..2008 */
		if ((1984 > set_value || set_value > 2008)) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkProtocolVersion: bad value\n");
			return SNMP_ERR_WRONGVALUE;
		}
		/* one allocation for the whole row */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) == NULL)
			if (StorageTmp->ss7NetworkTable_rsvs == 0)
				if ((StorageOld = StorageTmp->ss7NetworkTable_old = ss7NetworkTable_duplicate(StorageTmp)) == NULL)
					return SNMP_ERR_RESOURCEUNAVAILABLE;
		if (StorageOld != NULL)
			StorageTmp->ss7NetworkTable_rsvs++;
		StorageTmp->ss7NetworkProtocolVersion = set_value;
		/* XXX: insert code to consistency check this particular varbind, if necessary (so error codes are applied to varbinds) */
		break;
	case RESERVE2:		/* memory reseveration, final preparation... */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) != NULL) {
			/* one consistency check for the whole row */
			if (StorageTmp->ss7NetworkTable_tsts == 0)
				if ((ret = check_ss7NetworkTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->ss7NetworkTable_tsts++;
		}
		break;
	case ACTION:		/* The variable has been stored in StorageTmp->ss7NetworkProtocolVersion for you to use, and you have just been asked to do something with it.  Note that anything done 
				   here must be reversable in the UNDO case */
		if (StorageTmp == NULL)
			return SNMP_ERR_NOSUCHNAME;
		/* XXX: insert code to set this particular varbind, if necessary */
		/* one set action for the whole row */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) != NULL) {
			/* XXX: insert code to set this particular varbind, if necessary */
			if (StorageTmp->ss7NetworkTable_sets == 0)
				if ((ret = update_ss7NetworkTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->ss7NetworkTable_sets++;
		}
		break;
	case COMMIT:		/* Things are working well, so it's now safe to make the change permanently.  Make sure that anything done here can't fail! */
		/* one commit for the whole mib */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) != NULL) {
			ss7NetworkTable_destroy(&StorageTmp->ss7NetworkTable_old);
			StorageTmp->ss7NetworkTable_rsvs = 0;
			StorageTmp->ss7NetworkTable_tsts = 0;
			StorageTmp->ss7NetworkTable_sets = 0;
		}
		break;
	case UNDO:		/* Back out any changes made in the ACTION case */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) == NULL)
			break;
		/* XXX: insert code to undo any action performed on this particular varbind */
		if (--StorageTmp->ss7NetworkTable_sets == 0)
			revert_ss7NetworkTable_row(StorageTmp, StorageOld);
		/* fall through */
	case FREE:		/* Release any resources that have been allocated */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) == NULL)
			break;
		StorageTmp->ss7NetworkProtocolVersion = StorageOld->ss7NetworkProtocolVersion;
		if (--StorageTmp->ss7NetworkTable_rsvs == 0)
			ss7NetworkTable_destroy(&StorageTmp->ss7NetworkTable_old);
		break;
	}
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int write_ss7NetworkProtocolOptions(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid *name, size_t name_len)
 * @param action the stage of the SET operation.
 * @param var_val pointer to the varbind value.
 * @param var_val_type the ASN type.
 * @param var_val_len the length of the varbind value.
 * @param statP static pointer.
 * @param name the varbind OID.
 * @param name_len number of elements in OID.
 * @brief Table row and column write routine.
 */
int
write_ss7NetworkProtocolOptions(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	struct ss7NetworkTable_data *StorageTmp = NULL, *StorageOld = NULL;
	size_t newlen = name_len - 15;
	uint8_t *string = NULL;
	int ret = SNMP_ERR_NOERROR;

	DEBUGMSGTL(("ss7MIB", "write_ss7NetworkProtocolOptions entering action=%d...  \n", action));
	if (StorageTmp == NULL)
		return SNMP_ERR_NOSUCHNAME;
	StorageTmp = header_complex(ss7NetworkTableStorage, NULL, &name[15], &newlen, 1, NULL, NULL);
	switch (action) {
	case RESERVE1:
		if (StorageTmp != NULL && statP == NULL) {
			/* have row but no column */
			switch (StorageTmp->ss7NetworkRowStatus) {
			case RS_ACTIVE:
				/* cannot create non-existent column while active */
				snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkProtocolOptions: but column non-existent\n");
				return SNMP_ERR_INCONSISTENTVALUE;
			case RS_NOTINSERVICE:
			case RS_NOTREADY:
				/* assume column can be created */
				break;
			}
		}
		if (var_val_type != ASN_OCTET_STR) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkProtocolOptions not ASN_OCTET_STR\n");
			return SNMP_ERR_WRONGTYPE;
		}
		if (var_val_len > SPRINT_MAX_LEN) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkProtocolOptions: bad length\n");
			return SNMP_ERR_WRONGLENGTH;
		}
		/* one allocation for the whole row */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) == NULL)
			if (StorageTmp->ss7NetworkTable_rsvs == 0)
				if ((StorageOld = StorageTmp->ss7NetworkTable_old = ss7NetworkTable_duplicate(StorageTmp)) == NULL)
					return SNMP_ERR_RESOURCEUNAVAILABLE;
		if (StorageOld != NULL)
			StorageTmp->ss7NetworkTable_rsvs++;
		if ((string = malloc(var_val_len + 1)) == NULL)
			return SNMP_ERR_RESOURCEUNAVAILABLE;
		memcpy((void *) string, (void *) var_val, var_val_len);
		string[var_val_len] = 0;
		SNMP_FREE(StorageTmp->ss7NetworkProtocolOptions);
		StorageTmp->ss7NetworkProtocolOptions = string;
		StorageTmp->ss7NetworkProtocolOptionsLen = var_val_len;
		/* XXX: insert code to consistency check this particular varbind, if necessary (so error codes are applied to varbinds) */
		break;
	case RESERVE2:		/* memory reseveration, final preparation... */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) != NULL) {
			/* one consistency check for the whole row */
			if (StorageTmp->ss7NetworkTable_tsts == 0)
				if ((ret = check_ss7NetworkTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->ss7NetworkTable_tsts++;
		}
		break;
	case ACTION:		/* The variable has been stored in StorageTmp->ss7NetworkProtocolOptions for you to use, and you have just been asked to do something with it.  Note that anything done 
				   here must be reversable in the UNDO case */
		if (StorageTmp == NULL)
			return SNMP_ERR_NOSUCHNAME;
		/* XXX: insert code to set this particular varbind, if necessary */
		/* one set action for the whole row */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) != NULL) {
			/* XXX: insert code to set this particular varbind, if necessary */
			if (StorageTmp->ss7NetworkTable_sets == 0)
				if ((ret = update_ss7NetworkTable_row(StorageTmp, StorageOld)) != SNMP_ERR_NOERROR)
					return (ret);
			StorageTmp->ss7NetworkTable_sets++;
		}
		break;
	case COMMIT:		/* Things are working well, so it's now safe to make the change permanently.  Make sure that anything done here can't fail! */
		/* one commit for the whole mib */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) != NULL) {
			ss7NetworkTable_destroy(&StorageTmp->ss7NetworkTable_old);
			StorageTmp->ss7NetworkTable_rsvs = 0;
			StorageTmp->ss7NetworkTable_tsts = 0;
			StorageTmp->ss7NetworkTable_sets = 0;
		}
		break;
	case UNDO:		/* Back out any changes made in the ACTION case */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) == NULL)
			break;
		/* XXX: insert code to undo any action performed on this particular varbind */
		if (--StorageTmp->ss7NetworkTable_sets == 0)
			revert_ss7NetworkTable_row(StorageTmp, StorageOld);
		/* fall through */
	case FREE:		/* Release any resources that have been allocated */
		if ((StorageOld = StorageTmp->ss7NetworkTable_old) == NULL)
			break;
		if (StorageOld->ss7NetworkProtocolOptions != NULL) {
			SNMP_FREE(StorageTmp->ss7NetworkProtocolOptions);
			StorageTmp->ss7NetworkProtocolOptions = StorageOld->ss7NetworkProtocolOptions;
			StorageTmp->ss7NetworkProtocolOptionsLen = StorageOld->ss7NetworkProtocolOptionsLen;
			StorageOld->ss7NetworkProtocolOptions = NULL;
			StorageOld->ss7NetworkProtocolOptionsLen = 0;
		}
		if (--StorageTmp->ss7NetworkTable_rsvs == 0)
			ss7NetworkTable_destroy(&StorageTmp->ss7NetworkTable_old);
		break;
	}
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int can_act_ss7NetworkTable_row(struct ss7NetworkTable_data *StorageTmp)
 * @param StorageTmp the data (as updated)
 * @brief check whether an inactive table row can be activated
 *
 * This function is used by the ACTION phase of a RowStatus object to test whether an inactive table
 * row can be activated.  Returns SNMP_ERR_NOERROR when activation is permitted; an SNMP error
 * value, otherwise.  This function might use a 'test' operation against the driver to ensure that
 * the commit phase will succeed.
 */
int
can_act_ss7NetworkTable_row(struct ss7NetworkTable_data *StorageTmp)
{
	/* XXX: provide code to check whether the new or inactive table row can be activated */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int can_deact_ss7NetworkTable_row(struct ss7NetworkTable_data *StorageTmp)
 * @param StorageTmp the data (as updated)
 * @brief check whether an active table row can be deactivated
 *
 * This function is used by the ACTION phase of a RowStatus object to test whether an active table
 * row can be deactivated.  Returns SNMP_ERR_NOERROR when deactivation is permitted; an SNMP error
 * value, otherwise.  This function might use a 'test' operation against the driver to ensure that
 * the commit phase will succeed.
 */
int
can_deact_ss7NetworkTable_row(struct ss7NetworkTable_data *StorageTmp)
{
	/* XXX: provide code to check whether the active table row can be deactivated */
	return SNMP_ERR_NOERROR;
}

/**
 * @fn int write_ss7NetworkRowStatus(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid *name, size_t name_len)
 * @param action the stage of the SET operation.
 * @param var_val pointer to the varbind value.
 * @param var_val_type the ASN type.
 * @param var_val_len the length of the varbind value.
 * @param statP static pointer.
 * @param name the varbind OID.
 * @param name_len number of elements in OID.
 * @brief Row status write routine.
 */
int
write_ss7NetworkRowStatus(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	struct ss7NetworkTable_data *StorageTmp = NULL, *StorageOld = NULL;
	static struct ss7NetworkTable_data *StorageNew, *StorageDel;
	size_t newlen = name_len - 15;
	int set_value, ret;
	static struct variable_list *vars, *vp;

	DEBUGMSGTL(("ss7MIB", "write_ss7NetworkRowStatus entering action=%d...  \n", action));
	StorageTmp = header_complex(ss7NetworkTableStorage, NULL, &name[15], &newlen, 1, NULL, NULL);
	if (var_val_type != ASN_INTEGER || var_val == NULL) {
		snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkRowStatus not ASN_INTEGER\n");
		return SNMP_ERR_WRONGTYPE;
	}
	set_value = *((long *) var_val);
	/* check legal range, and notReady is reserved for us, not a user */
	if (set_value < 1 || set_value > 6 || set_value == RS_NOTREADY) {
		snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkRowStatus: bad value\n");
		return SNMP_ERR_WRONGVALUE;
	}
	switch (action) {
	case RESERVE1:
		/* stage one: test validity */
		StorageNew = StorageDel = NULL;
		vars = vp = NULL;
		switch (set_value) {
		case RS_CREATEANDGO:
		case RS_CREATEANDWAIT:
			if (StorageTmp != NULL)
				/* cannot create existing row */
				return SNMP_ERR_INCONSISTENTVALUE;
			/* creation */
			vars = NULL;
			/* ss7NetworkId */
			if ((vp = snmp_varlist_add_variable(&vars, NULL, 0, ASN_INTEGER, NULL, 0)) == NULL) {
				snmp_free_varbind(vars);
				return SNMP_ERR_RESOURCEUNAVAILABLE;
			}
			if (header_complex_parse_oid(&(name[15]), newlen, vars) != SNMPERR_SUCCESS) {
				snmp_free_varbind(vars);
				return SNMP_ERR_INCONSISTENTNAME;
			}
			vp = vars;
			/* ss7NetworkId */
			if (vp->val_len > sizeof(int32_t)) {
				snmp_log(MY_FACILITY(LOG_NOTICE), "index ss7NetworkId: bad length\n");
				snmp_free_varbind(vars);
				return SNMP_ERR_INCONSISTENTNAME;
			}
			/* Note: ranges 1..255 */
			if ((1 > (long) *vp->val.integer || (long) *vp->val.integer > 255)) {
				snmp_log(MY_FACILITY(LOG_NOTICE), "index ss7NetworkId: bad value\n");
				snmp_free_varbind(vars);
				return SNMP_ERR_INCONSISTENTNAME;
			}
			vp = vp->next_variable;
			if ((StorageNew = ss7NetworkTable_create()) == NULL) {
				snmp_free_varbind(vars);
				return SNMP_ERR_RESOURCEUNAVAILABLE;
			}
			StorageNew->ss7NetworkTable_rsvs = 1;
			vp = vars;
			StorageNew->ss7NetworkId = (long) *vp->val.integer;
			vp = vp->next_variable;
			header_complex_add_data(&ss7NetworkTableStorage, vars, StorageNew);	/* frees vars */
			break;
		case RS_ACTIVE:
		case RS_NOTINSERVICE:
			if (StorageTmp == NULL)
				/* cannot change state of non-existent row */
				return SNMP_ERR_INCONSISTENTVALUE;
			if (StorageTmp->ss7NetworkRowStatus == RS_NOTREADY)
				/* cannot change state of row that is not ready */
				return SNMP_ERR_INCONSISTENTVALUE;
			/* XXX: interaction with row storage type needed */
			if (set_value == RS_NOTINSERVICE && StorageTmp->ss7NetworkTable_refs > 0)
				/* row is busy and cannot be moved to the RS_NOTINSERVICE state */
				return SNMP_ERR_INCONSISTENTVALUE;
			/* activate or deactivate */
			if (StorageTmp == NULL)
				return SNMP_ERR_NOSUCHNAME;
			/* one allocation for the whole row */
			if ((StorageOld = StorageTmp->ss7NetworkTable_old) == NULL)
				if (StorageTmp->ss7NetworkTable_rsvs == 0)
					if ((StorageOld = StorageTmp->ss7NetworkTable_old = ss7NetworkTable_duplicate(StorageTmp)) == NULL)
						return SNMP_ERR_RESOURCEUNAVAILABLE;
			if (StorageOld != NULL)
				StorageTmp->ss7NetworkTable_rsvs++;
			break;
		case RS_DESTROY:
			if (StorageTmp == NULL)
				/* cannot destroy non-existent row */
				return SNMP_ERR_INCONSISTENTVALUE;
			/* XXX: interaction with row storage type needed */
			if (StorageTmp->ss7NetworkTable_refs > 0)
				/* row is busy and cannot be deleted */
				return SNMP_ERR_INCONSISTENTVALUE;
			/* destroy */
			if (StorageTmp != NULL) {
				/* exists, extract it for now */
				StorageDel = StorageTmp;
				ss7NetworkTable_del(StorageDel);
			} else {
				StorageDel = NULL;
			}
			break;
		case RS_NOTREADY:
			/* management station cannot set this, only agent can */
		default:
			return SNMP_ERR_INCONSISTENTVALUE;
		}
		break;
	case RESERVE2:
		/* memory reseveration, final preparation... */
		switch (set_value) {
		case RS_CREATEANDGO:
			/* check that activation is possible */
			if ((ret = can_act_ss7NetworkTable_row(StorageNew)) != SNMP_ERR_NOERROR)
				return (ret);
			break;
		case RS_CREATEANDWAIT:
			break;
		case RS_ACTIVE:
			/* check that activation is possible */
			if (StorageTmp->ss7NetworkRowStatus != RS_ACTIVE)
				if ((ret = can_act_ss7NetworkTable_row(StorageTmp)) != SNMP_ERR_NOERROR)
					return (ret);
			break;
		case RS_NOTINSERVICE:
			/* check that deactivation is possible */
			if (StorageTmp->ss7NetworkRowStatus != RS_NOTINSERVICE)
				if ((ret = can_deact_ss7NetworkTable_row(StorageTmp)) != SNMP_ERR_NOERROR)
					return (ret);
			break;
		case RS_DESTROY:
			/* check that deactivation is possible */
			if (StorageTmp->ss7NetworkRowStatus != RS_NOTINSERVICE)
				if ((ret = can_deact_ss7NetworkTable_row(StorageTmp)) != SNMP_ERR_NOERROR)
					return (ret);
			break;
		default:
			return SNMP_ERR_WRONGVALUE;
		}
		break;
	case ACTION:
		/* The variable has been stored in StorageTmp->ss7NetworkRowStatus for you to use, and you have just been asked to do something with it.  Note that anything done here must be
		   reversable in the UNDO case */
		switch (set_value) {
		case RS_CREATEANDGO:
			/* activate with underlying device */
			if (activate_ss7NetworkTable_row(StorageNew) != SNMP_ERR_NOERROR)
				return SNMP_ERR_COMMITFAILED;
			break;
		case RS_CREATEANDWAIT:
			break;
		case RS_ACTIVE:
			/* state change already performed */
			if (StorageTmp->ss7NetworkRowStatus != RS_ACTIVE) {
				/* activate with underlying device */
				if (activate_ss7NetworkTable_row(StorageTmp) != SNMP_ERR_NOERROR)
					return SNMP_ERR_COMMITFAILED;
			}
			break;
		case RS_NOTINSERVICE:
			/* state change already performed */
			if (StorageTmp->ss7NetworkRowStatus != RS_NOTINSERVICE) {
				/* deactivate with underlying device */
				if (deactivate_ss7NetworkTable_row(StorageTmp) != SNMP_ERR_NOERROR)
					return SNMP_ERR_COMMITFAILED;
			}
			break;
		case RS_DESTROY:
			/* commit destrution to underlying device */
			if (StorageDel == NULL)
				break;
			/* deactivate with underlying device */
			if (deactivate_ss7NetworkTable_row(StorageDel) != SNMP_ERR_NOERROR)
				return SNMP_ERR_COMMITFAILED;
			break;
		default:
			return SNMP_ERR_WRONGVALUE;
		}
		break;
	case COMMIT:
		/* Things are working well, so it's now safe to make the change permanently.  Make sure that anything done here can't fail! */
		switch (set_value) {
		case RS_CREATEANDGO:
			StorageNew->ss7NetworkRowStatus = RS_ACTIVE;
			break;
		case RS_CREATEANDWAIT:
			StorageNew->ss7NetworkRowStatus = RS_NOTINSERVICE;
			break;
		case RS_ACTIVE:
		case RS_NOTINSERVICE:
			StorageNew->ss7NetworkRowStatus = set_value;
			if ((StorageOld = StorageTmp->ss7NetworkTable_old) != NULL) {
				ss7NetworkTable_destroy(&StorageTmp->ss7NetworkTable_old);
				StorageTmp->ss7NetworkTable_rsvs = 0;
				StorageTmp->ss7NetworkTable_tsts = 0;
				StorageTmp->ss7NetworkTable_sets = 0;
			}
			break;
		case RS_DESTROY:
			ss7NetworkTable_destroy(&StorageDel);
			break;
		}
		break;
	case UNDO:
		/* Back out any changes made in the ACTION case */
		switch (set_value) {
		case RS_CREATEANDGO:
			/* deactivate with underlying device */
			deactivate_ss7NetworkTable_row(StorageNew);
			break;
		case RS_CREATEANDWAIT:
			break;
		case RS_ACTIVE:
			if (StorageTmp->ss7NetworkRowStatus == RS_NOTINSERVICE)
				/* deactivate with underlying device */
				deactivate_ss7NetworkTable_row(StorageTmp);
			break;
		case RS_NOTINSERVICE:
			if (StorageTmp->ss7NetworkRowStatus == RS_ACTIVE)
				/* activate with underlying device */
				activate_ss7NetworkTable_row(StorageTmp);
			break;
		case RS_DESTROY:
			break;
		}
		/* fall through */
	case FREE:
		/* Release any resources that have been allocated */
		switch (set_value) {
		case RS_CREATEANDGO:
		case RS_CREATEANDWAIT:
			/* creation */
			if (StorageNew) {
				ss7NetworkTable_del(StorageNew);
				ss7NetworkTable_destroy(&StorageNew);
			}
			break;
		case RS_ACTIVE:
		case RS_NOTINSERVICE:
			if ((StorageOld = StorageTmp->ss7NetworkTable_old) == NULL)
				break;
			if (--StorageTmp->ss7NetworkTable_rsvs == 0)
				ss7NetworkTable_destroy(&StorageTmp->ss7NetworkTable_old);
			break;
		case RS_DESTROY:
			/* row deletion, so add it again */
			if (StorageDel)
				ss7NetworkTable_add(StorageDel);
			break;
		}
		break;
	}
	return SNMP_ERR_NOERROR;
}

/**
 * @fn void ss7MIB_loop_handler(int dummy)
 * @param sig signal number
 * @brief handle event loop interation.
 *
 * This function is registered so that, when operating as a module, snmpd will call it one per event
 * loop interation.  This function is called before the next requst is processed and after the
 * previous request is processed.  Two things are done here:  1) The file descriptor that is used to
 * synchronize the agent with (pseudo-)device drivers is closed.  (Another approach, instead of
 * closing each time, would be to restart a timer each time that a request is made (loop is
 * performed) and if it expires, close the file descriptor).  2) The request number is incremented.
 * Although a request is not generated for each loop of the snmp event loop, it is true that a new
 * request cannot be generated without performing a loop.  Therefore, the sa_request is not the
 * request number but it is a temporally unique identifier for a request.
 */
void
ss7MIB_loop_handler(int sig)
{
	DEBUGMSGTL(("ss7MIB", "ss7MIB_loop_handler: executing loop handler...  "));
	/* close files after each request */
	if (sa_fclose) {
		if (my_fd >= 0) {
			close(my_fd);
			my_fd = -1;
		}
	}
#if defined MASTER
	/* prepare for next request */
	sa_request++;
#endif				/* defined MASTER */
	if (external_signal_scheduled[sig] == 0)
		external_signal_scheduled[sig]--;
	if (ss7MIBold_signal_handler != NULL)
		(*ss7MIBold_signal_handler) (sig);
	DEBUGMSGTL(("ss7MIB", "done.\n"));
}

/**
 * @fn void ss7MIB_fd_handler(int fd, void *dummy)
 * @param fd file descriptor to read.
 * @param dummy client data passed to registration function (always NULL).
 * @brief handle read event on file descriptor.
 *
 * This read file descriptor handler is normally used for (pseudo-)device drivers that generate
 * statistical collection interval events, alarm events, or other operational measurement events, by
 * placing a message on the read queue of the "event handling" Stream.  Normally this routine
 * would adjust counts in some table or scalars, generate SNMP traps representing on-occurence
 * events, first and interval events, and alarm indications.
 */
void
ss7MIB_fd_handler(int fd, void *dummy)
{
	DEBUGMSGTL(("ss7MIB", "ss7MIB_fd_handler: executing fd handler...  "));
	/* XXX: place actions to handle my_fd here... */
	DEBUGMSGTL(("ss7MIB", "done.\n"));
	return;
}
