'\" rtp
.\" -*- nroff -*- vim: ft=nroff nocin nosi
.\"
.\" @(#) $Id: flushband.9.man,v 1.1.4.6 2008-04-29 08:33:21 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.  The author(s) will take no responsibility in it.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" -------------------------------------------------------------------------
.\"
.\" U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
.\" on behalf of the U.S. Government ("Government"), the following
.\" provisions apply to you.  If the Software is supplied by the Department
.\" of Defense ("DoD"), it is classified as "Commercial Computer Software"
.\" under paragraph 252.227-7014 of the DoD Supplement to the Federal
.\" Acquisition Regulations ("DFARS") (or any successor regulations) and the
.\" Government is acquiring only the license rights granted herein (the
.\" license rights customarily provided to non-Government users).  If the
.\" Software is supplied to any unit or agency of the Government other than
.\" DoD, it is classified as "Restricted Computer Software" and the
.\" Government's rights in the Software are defined in paragraph 52.227-19
.\" of the Federal Acquisition Regulations ("FAR") (or any successor
.\" regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
.\" NASA Supplement to the FAR (or any successor regulations).
.\"
.\" =========================================================================
.\" 
.\" Commercial licensing and support of this software is available from
.\" OpenSS7 Corporation at a fee.  See http://www.openss7.com/
.\" 
.\" =========================================================================
.\"
.\" Last Modified $Date: 2008-04-29 08:33:21 $ by $Author: brian $
.\"
.\" -------------------------------------------------------------------------
.\"
.\" $Log: flushband.9.man,v $
.\" Revision 1.1.4.6  2008-04-29 08:33:21  brian
.\" - update headers for Affero release
.\"
.\" Revision 1.1.4.5  2006/04/05 09:42:43  brian
.\" - moved .so line and updated headers
.\"
.\" =========================================================================
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database lis.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.so lis.macros
.\"
.\"
.TH FLUSHBAND 9 "@PACKAGE_DATE@" "@PACKAGE@-@VERSION@" "@PACKAGE_TITLE@ DDI/DKI"
.\"
.\"
.SH NAME
.B flushband, lis_flushband
\- flushes band \fISTREAMS\fR messages from a message queue
.\"
.\"
.SH SYNOPSIS
.PP
.B #include <sys/stream.h>
.HP 8
.BI "flushband(queue_t *" q ", unsigned char " band ", int " flag );
.\"
.\"
.SH ARGUMENTS
.PP
.TP
.I q
the queue to flush.
.TP
.I band
the queue band in the queue to flush.
.TP
.I flag
how to flush the queue band.
.\"
.\"
.SH DESCRIPTION
.PP
.BR flushband ()
is used to flush messages from a
.I STREAMS
message queue band.  It is typically
called in a
.B M_FLUSH
handling routine to flush the requested messsages from a queue band.
.PP
The arguments to
.BR flushband ()
are interpreted as follows:
.TP 8
.I q
The queue to flush.
.TP 8
.I band
The band to flush within the queue.
.TP 8
.I flag
How to flush the band within the queue.
.I flag
can be one of the following:
.RS
.TP 12
.B FLUSHDATA
Flush only data messages; do not flush the control messages from the queue
band.
.PD 0
.TP 12
.B FLUSHALL
Flush all the messages from queue band: both data messages and control
messages.
.PD
.RE
.\"
.\"
.SH RETURN
.BR flushband ()
returns
.BR void .
.\"
.\"
.SH ERRORS
.PP
If the
.I q
passed to
.BR flushband ()
is
.BR NULL ,
or the
.I q
does not point to a valid queue structure, then
.BR flushband ()
will silently fail.
.\"
.\"
.SH CONTEXT
.PP
.BR flushband ()
can be called from any context, including user context, module procedures,
callouts, callbacks, soft interrupts and interrupt service routines.
.PP
Because
.BR flushband ()
can take some time to process if there are many messages on the queue or
.I flags
is
.BR FLUSHDATA ,
.BR flushband ()
should not be called from interrupt service routines or functions with
interrupts disabled or global locks held.
.\"
.\"
.SH MP-STREAMS
.PP
.BR flushband ()
is MP-safe.
.BR flushband ()
takes a recursive write lock on the queue being flushed.  This means that calling
.BR flushband ()
on a stream that has been frozen with
.BR freezestr (9)
will not result in single-party deadlock.
.\"
.\"
.SH NOTICES
.PP
.B LiS
.[
LiS
.]
implements the call to
.BR flushq (9)
.BI flushq( q ", " band )
as a call to
.BI flushband( q ", " 0 ", " flag ).
.\"
.\"
.SH EXAMPLES
.PP
.BR flushband ()
is normally used within the
.B M_FLUSH
handling procedures for a
.I STREAMS
module or driver as follows:
.sp
.in +4
.nf
\fC\s-2\
int x_w_flush(queue_t *q, mblk_t *mp)
{
    if (*mp->b_rptr & FLUSHW) {
        if (*mp->b_rptr & FLUSHBAND)
            flushband(WR(q), mp->b_rptr[1], FLUSHALL);
        else
            flushq(WR(q), FLUSHALL);
        if (q->q_next) {
            putnext(q, mp);
            return (0);
        }
        *mp->b_rptr &= ~FLUSHW;
    }
    if (*mp->b_rptr & FLUSHR) {
        if (*mp->b_rptr & FLUSHBAND)
            flushband(RD(q), mp->b_rptr[1], FLUSHALL);
        else
            flushq(RD(q), FLUSHALL);
        if (!q->q_next) {
            qreply(q, mp);
            return (0);
        }
        *mp->b_rptr &= ~FLUSHR;
    }
    freemsg(mp);
    return (0);
}
int x_r_flush(queue_t *q, mblk_t *mp)
{
    if (*mp->b_rptr & FLUSHR) {
        if (*mp->b_rptr & FLUSHBAND)
            flushband(RD(q), mp->b_rptr[1], FLUSHALL);
        else
            flushq(RD(q), FLUSHALL);
        if (q->q_next) {
            putnext(q, mp);
            return (0);
        }
        *mp->b_rptr &= ~FLUSHR;
    }
    if (*mp->b_rptr & FLUSHW) {
        if (*mp->b_rptr & FLUSHBAND)
            flushband(WR(q), mp->b_rptr[1], FLUSHALL);
        else
            flushq(WR(q), FLUSHALL);
        if (!q->q_next) {
            qreply(q, mp);
            return (0);
        }
        *mp->b_rptr &= ~FLUSHW;
    }
    freemsg(mp);
    return (0);
}
\s+2\fR
.fi
.\"
.\"
.SH "SEE ALSO"
.PP
.BR freezestr (9),
.BR flushq (9).
.\"
.\"
.SH BUGS
.BR flushband ()
has no known bugs.
.\"
.\"
.SH COMPATIBILITY
.PP
.BR flushband ()
is compatible with
.IR "SVR 4.2 MP DDI/DKI" ,
.[
usldk
.]
and systems based on
.IR "SVR 4" ,
with the following portability considerations:
.IP \(em \w'\(em\(em'u
.B LiS
removes all messages from the queue and then rebuilds the queue one message at a
time while freeing those to be flushed.  This is a rather inefficient way to do
things, and with LiS running at higher priority than soft interrupts, bottom
halves and timeouts, all these are locked out until the flush is complete.
.IP \(em
.B LiS
empties the queue and unlocks the queue and then goes about adding messages back
onto the queue that need to remain using normal utility functions.  This means
that order is not necessarily preserved (even for messages that were on the
queue) with concurrent calls to
.BR putq (9),
.BR insq (9),
.BR appq (9),
.BR rmvq (9)
or
.BR putbq (9)
functions.
Also, queue enabling and back-enabling will not necessary be performed
correctly.
There doesn't seem to be any excuse for the
.B LiS
approach, removing messages from the queue,
.BR rmvq (9),
is no more difficult than inserting them,
.BR insq (9).
.IP \(em
.BR flushband ()
flushes normal and high priority messages when
.I band
is zero (0).
.IR AIX \(rg
.[
aixspg
.]
and
.IR UXP/V \(rg
.[
uxpspg
.]
state that a
.I band
of zero (0) will only flush ordinary messages.
.IR OSF/1 \(rg,
.[
osfspg
.]
.IR Solaris \(rg
.[
solspg
.]
and
.IR SUPER-UX \(rg
.[
suxspg
.]
state that a
.I band
of zero (0) flushes normal and high priority messages.
.IR UnixWare \(rg
.[
uw7spg
.]
states that a
.I band
of zero (0) flushes normal priority (band 0) messages.
.IR LiS ,
when
.I band
is zero (0),
will only flush normal priority messages from band zero and will leave high
priority messages on the queue.
.sp
Portable
.I STREAMS
modules and drivers should never call
.BR flushband ()
with a band of zero (0).  Portable
.I STREAMS
modules and drivers should call
.BR flushq (9)
instead.
.IP \(em
.BR flushband ()
does not clear the
.B QWANTR
flag when flushing an empty queue.  This is an indication to the
.I STREAMS
scheduler that
.BR getq (9)
read an empty queue and back-enabling has already been performed for the queue.
LiS clears the
.B QWANTR
flag when flushing an empty queue.  This means that the next call to
.BR getq (9)
for the empty queue will perform an extra back-enable.
.IP \(em
.BR flushband ()
may be called on a stream frozen with
.BR freezestr (9).
.IR "SVR 4.2 MP DDI/DKI" ,
.[
usldk
.]
.IR Solaris \(rg,
.[
solspg
.]
.IR SUPER-UX \(rg
.[
suxspg
.]
and
.IR UnixWare \(rg
.[
uw7spg
.]
do not permit
.BR flushband ()
to be called on a stream frozen with
.BR freezestr (9).
Portable
.I STREAMS
drivers and modules should not call
.BR flushband ()
on a stream frozen with
.BR freezestr (9).
.PP
For a fully functional
.I STREAMS
implementation, use
.BR "Linux Fast-STREAMS" .
.[
LfS
.]
.\"
.\"
.SH CONFORMANCE
.PP
SVR 4.2 MP DDI/DKI
.[
usldk
.]
.\"
.\"
.SH HISTORY
.PP
.BR flushband ()
first appeared in SVR 4.
.[
svr4
.]
.\"
.\"
.[
$LIST$
.]
.TI
