#!/bin/sh
#
# Shell script to run indent with Dave G's coding style
#
#ident "@(#) LiS indentlis 1.1 3/9/02"
#
OPTS="-bap -bbb -bbo -bl -bli0 -bls -ci4 -cs -i4 -l80 -lc80 -lp -npsl -nsob \
	-ss -npcs -pi4 -nss -ts8"
indent $OPTS $*
