'\" rtp
.\" vim: ft=nroff sw=4 noet nocin nosi com=b\:.\\\" fo+=tcqlorn tw=77
.\" =========================================================================
.\"
.\" @(#) $Id: getpadent.3.man,v 1.1.2.2 2011-02-07 02:18:02 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (c) 2008-2011  Monavacon Limited <http://www.monavacon.com/>
.\" Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
.\" Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to copy, distribute and/or modify this manual under
.\" the terms of the GNU Free Documentation License, Version 1.3 or any later
.\" version published by the Free Software Foundation; with no Invariant
.\" Sections, no Front-Cover Texts, and no Back-Cover Texts.  A copy of the
.\" license is included in the section entitled "GNU Free Documentation
.\" License".
.\"
.\" Permission to use, copy and distribute this manual without modification,
.\" for any purpose and without fee or royalty is hereby granted, provided
.\" that both the above copyright notice and this permission notice appears
.\" in all copies and that the name of OpenSS7 Corporation not be used in
.\" advertising or publicity pertaining to distribution of this documentation
.\" or its contents without specific, written prior permission.  OpenSS7
.\" Corporation makes no representation about the suitability of this manual
.\" for any purpose.  It is provided "as is" without express or implied
.\" warranty.
.\"
.\" Permission is granted to process this file through groff and print the
.\" results, provided the printed document carries a copying permission
.\" notice identical to this one except for the removal of this paragraph
.\" (this paragraph not being relevant to the printed manual).
.\"
.\" OPENSS7 CORPORATION DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS MANUAL
.\" INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
.\" PARTICULAR PURPOSE, NON-INFRINGEMENT, OR TITLE; THAT THE CONTENTS OF THE
.\" DOCUMENT ARE SUITABLE FOR ANY PURPOSE, OR THAT THE IMPLEMENTATION OF SUCH
.\" CONTENTS WILL NOT INFRINGE ON ANY THIRD PARTY PATENTS, COPYRIGHTS,
.\" TRADEMARKS OR OTHER RIGHTS.  IN NO EVENT SHALL OPENSS7 CORPORATION BE
.\" LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR CONSEQUENTIAL DAMAGES OR ANY
.\" DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
.\" IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
.\" OUT OF OR IN CONNECTION WITH ANY USE OF THIS DOCUMENT OR THE PERFORMANCE
.\" OR IMPLEMENTATION OF THE CONTENTS THEREOF.
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this manual
.\" page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from the
.\" use of the information contained herein.  The author(s) may not have
.\" taken the same level of care in the production of this manual, which is
.\" licensed free of charge, as they might when working professionally.  The
.\" author(s) will take no responsibility in it.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by the
.\" source, must acknowledge the copyright and authors of this work.
.\"
.\" -------------------------------------------------------------------------
.\"
.\" U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
.\" behalf of the U.S. Government ("Government"), the following provisions
.\" apply to you.  If the Software is supplied by the Department of Defense
.\" ("DoD"), it is classified as "Commercial Computer Software" under
.\" paragraph 252.227-7014 of the DoD Supplement to the Federal Acquisition
.\" Regulations ("DFARS") (or any successor regulations) and the Government
.\" is acquiring only the license rights granted herein (the license rights
.\" customarily provided to non-Government users).  If the Software is
.\" supplied to any unit or agency of the Government other than DoD, it is
.\" classified as "Restricted Computer Software" and the Government's rights
.\" in the Software are defined in paragraph 52.227-19 of the Federal
.\" Acquisition Regulations ("FAR") (or any successor regulations) or, in the
.\" cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the
.\" FAR (or any successor regulations).
.\"
.\" =========================================================================
.\" 
.\" Commercial licensing and support of this software is available from
.\" OpenSS7 Corporation at a fee.  See http://www.openss7.com/
.\" 
.\" =========================================================================
.\"
.\" Last Modified $Date: 2011-02-07 02:18:02 $ by $Author: brian $
.\"
.\" -------------------------------------------------------------------------
.\"
.\" $Log: getpadent.3.man,v $
.\" Revision 1.1.2.2  2011-02-07 02:18:02  brian
.\" - updated manual pages
.\"
.\" =========================================================================
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database openss7.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
search-truncate 40
search-ignore CGIQOSTU
.R2
.so openss7.macros
.\"
.\"
.TH GETPADENT 3 "@PACKAGE_DATE@" "@PACKAGE@-@VERSION@" "@PACKAGE_TITLE@ Library Calls"
.SH NAME
.B getpadent
\- get next entry in the X.25 PAD Hosts Database
.\"
.\"
.SH SYNOPSIS
.PP
.B #include <netx25/x25_proto.h>
.br
.B #include <netx25/xnetdb.h>
.HP
.BI "struct padent *getpadent(void);
.\"
.\"
.SH INTERFACE
.PP
X.25 Network Layer Interface (NLI).
.\"
.\"
.SH LIBRARY
.PP
X.25 Support Library,
.BR libsx25 (3).
.\"
.\"
.SH ARGUMENTS
.PP
None.
.\"
.\"
.SH DESCRIPTION
.PP
.BR getpadent ()
returns a pointer to a
.BR padent (5)
structure, which contains the next entry from the X.25 PAD Hosts Database.
If necessary,
.BR getpadent ()
opens the database.
When the database was previously opened using
.BR setpadent (3)
and not subsequently closed using
.BR endpadent (3),
it is not necessary for
.BR getpadent ()
to open the database.
When
.BR setpadent (3)
is called, or when the database has not yet been opened, the database is
rewound to the beginning of the file.
.\"
.SS FILE FORMAT
.PP
The format of the
.B @sysconfdir@/x25/padent
X.25 PAD host database file is as described in
.BR padent (5).
.\"
.\"
.\".SH NOTICES
.\".PP
.\"
.\"
.SH RETURN VALUE
.PP
Returns a pointer to an
.BR xhostent (5)
structure.
When successful,
.BR getpadent ()
returns a pointer to a
.BR padent (5)
structure, which contains the next entry from the X.25 PAD Hosts database.
A return value of
.B NULL
indicates an error.
.\"
.\"
.SH ERRORS
.PP
When unsuccessful,
.BR getpadent ()
returns a
.B NULL
pointer indicating that there are no further entries in the X.25 PAD Hosts
Database.
.\"
.\"
.SH FILES
.PP
.TP
.RB < netx25/xnetdb.h >
The
.B padent
structure is defined in the
.RB < netx25/xnetdb.h >
header file.
.TP
.B @sysconfdir@/x25/padmapconf
Contains the PAD host database defined in
.BR padent (5).
.TP
.B @libdir@/libsx25.so
The X.25 network services shared object library.
.TP
.B @libdir@/libsx25.a
The X.25 network services static library.
.\"
.\"
.SH BUGS
.PP
.BR getpadent ()
has no known bugs.
.\"
.\"
.SH SEE ALSO
.PP
.BR libsx25 (3),
.BR padent (5),
.BR endpadent (3),
.BR getpadbyaddr (3),
.BR getpadent (3),
.BR padtos (3),
.BR setpadent (3).
.\"
.\"
.SH COMPATIBILITY
.PP
.B getpadent
is compatible with
.IR AIXlink/X.25 ,
.[
aixx25
.]
.IR "HP-UX X.25/9000" ,
.[
hpuxdoc
.]
.IR "IRIS SX.25" ,
.[
sx25
.]
.IR "PT X.25" ,
.[
ptx25
.]
.IR "RadiSys WAN" ,
.[
radwan
.]
.IR "SBE X.25" ,
.[
sbex25
.]
.IR "SunLink X.25" ,
.IR "Solstice X.25" ,
.[
solx25dg
.]
and systems based on
.IR "Spider X.25" ,
with the following compatibility considerations:
.IP \(em \w'\(em\(em'u
.IR "Solaris Solstice" "\(rg " "X.25 9.2" ,
.[
solx25dg
.]
.IR "IRIX SX.25" ,
.[
sx25
.]
.IR "PT X.25" ,
.[
ptx25
.]
are consistent in their documentation of the
.B padent
structure.
.IP \(em
On
.IR UNIX \(rg
systems, these utility subroutines are part of the X.25 library,
.BR libsx25 .
.IP \(em
These subroutines are consistently described across implementations of X.25
on
.IR UNIX \(rg
and can be used portably by applications programs.
.PP
See
.BR libsx25 (3)
for additional compatibility information.
.\"
.\"
.SH CONFORMANCE
.PP
.IR "Spider X.25" .
.\"
.\"
.SH HISTORY
.PP
The PAD host subroutines first appeared in
.IR "Spider X.25" .
These subroutines are related to
.IR UNIX \(rg
.BR STREAMS (9)
implementation of X.25 PAD providers.
.\"
.\"
.SH VERSIONS
.PP
This manual page was written for the
.B @PACKAGE_TITLE@
package
.RB ( "@PACKAGE@-@VERSION@" ).
.\"
.\"
.[
$LIST$
.]
.TI
