'\" rtp
.\" vim: ft=nroff sw=4 noet nocin nosi com=b\:.\\\" fo+=tcqlorn tw=77
.\" =========================================================================
.\"
.\" @(#) $Id$
.\"
.\" =========================================================================
.\"
.\" Copyright (c) 2008-2009  Monavacon Limited <http://www.monavacon.com/>
.\" Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
.\" Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to copy, distribute and/or modify this manual
.\" under the terms of the GNU Free Documentation License, Version 1.3 or
.\" any later version published by the Free Software Foundation; with no
.\" Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
.\" copy of the license is included in the section entitled "GNU Free
.\" Documentation License".
.\"
.\" Permission to use, copy and distribute this manual without modification,
.\" for any purpose and without fee or royalty is hereby granted, provided
.\" that both the above copyright notice and this permission notice appears
.\" in all copies and that the name of OpenSS7 Corporation not be used in
.\" advertising or publicity pertaning to distribution of this documentation
.\" or its contents without specific, written prior permission.  OpenSS7
.\" Corporation makes no representation about the suitability of this manual
.\" for any purpose.  It is provided "as is" without express or implied
.\" warranty.
.\"
.\" Permission is granted to process this file through groff and print the
.\" results, provided the printed document carries a copying permission
.\" notice identical to this one except for the removal of this paragraph
.\" (this paragraph not being relevant to the printed manual).
.\"
.\" OPENSS7 CORPORATION DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS MANUAL
.\" INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
.\" PARTICULAR PURPOSE, NON-INFRINGEMENT, OR TITLE; THAT THE CONTENTS OF THE
.\" DOCUMENT ARE SUITABLE FOR ANY PURPOSE, OR THAT THE IMPLEMENTATION OF
.\" SUCH CONTENTS WILL NOT INFRINGE ON ANY THIRD PARTY PATENTS, COPYRIGHTS,
.\" TRADEMARKS OR OTHER RIGHTS.  IN NO EVENT SHALL OPENSS7 CORPORATION BE
.\" LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR CONSEQUENTIAL DAMAGES OR ANY
.\" DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER
.\" IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING
.\" OUT OF OR IN CONNECTION WITH ANY USE OF THIS DOCUMENT OR THE PERFORMANCE
.\" OR IMPLEMENTATION OF THE CONTENTS THEREOF.
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not have
.\" taken the same level of care in the production of this manual, which is
.\" licensed free of charge, as they might when working professionally.  The
.\" author(s) will take no responsibility in it.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by the
.\" source, must acknowledge the copyright and authors of this work.
.\"
.\" -------------------------------------------------------------------------
.\"
.\" U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
.\" on behalf of the U.S. Government ("Government"), the following
.\" provisions apply to you.  If the Software is supplied by the Department
.\" of Defense ("DoD"), it is classified as "Commercial Computer Software"
.\" under paragraph 252.227-7014 of the DoD Supplement to the Federal
.\" Acquisition Regulations ("DFARS") (or any successor regulations) and the
.\" Government is acquiring only the license rights granted herein (the
.\" license rights customarily provided to non-Government users).  If the
.\" Software is supplied to any unit or agency of the Government other than
.\" DoD, it is classified as "Restricted Computer Software" and the
.\" Government's rights in the Software are defined in paragraph 52.227-19
.\" of the Federal Acquisition Regulations ("FAR") (or any successor
.\" regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
.\" NASA Supplement to the FAR (or any successor regulations).
.\"
.\" =========================================================================
.\" 
.\" Commercial licensing and support of this software is available from
.\" OpenSS7 Corporation at a fee.  See http://www.openss7.com/
.\" 
.\" =========================================================================
.\"
.\" Last Modified $Date$ by $Author$
.\"
.\" -------------------------------------------------------------------------
.\"
.\" $Log$
.\" =========================================================================
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database openss7.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
search-truncate 40
search-ignore T
.R2
.so openss7.macros
.\"
.\"
.TH TESTB 9 "@PACKAGE_DATE@" "@PACKAGE@-@VERSION@" "@PACKAGE_TITLE@ DDI/DKI"
.\"
.\"
.SH NAME
.B testb
\- test if a \fISTREAMS\fR message can be allocated
.\"
.\"
.SH SYNOPSIS
.PP
.B #include <sys/stream.h>
.HP
.BI "int testb(int " size ", unsigned int " priority );
.\"
.\"
.SH ARGUMENTS
.PP
.TP \w'\fIpriority\fR\(em'u
.I size
the size of the requested data buffer.
.PD 0
.TP
.I priority
the priority of the request for a message block.
.PD
.\"
.\"
.SH INTERFACE
.PP
.IR STREAMS .
.\"
.\"
.SH DESCRIPTION
.PP
.BR testb ()
tests whether an allocation made with
.BR allocb (9)
of the size specified by
.I size
and priority specified by
.IR priority ,
will succeed or fail.
To test whether a subsequent allocation with
.BR esballoc (9)
will succeed or fail, set
.I size
to zero (0).
.PP
.I priority
can be one of the following values:
.sp
.TS
tab(:);
lblsss.
BPRI_LO:T{
requests a low priority buffer.
T}
BPRI_MED:T{
requests a medium priority buffer.
T}
BPRI_HI:T{
requests a high priority buffer.
T}
BPRI_WAITOK:T{
requests a low priority buffer and can block.
T}
.TE
.PP
If
.I priority
is other than
.BR BPRI_LO ", " BPRI_MED ", " BPRI_HI " or " BPRI_WAITOK ,
the request will be treated as
.BR BPRI_LOW .
.\"
.\"
.SH RETURN
.PP
.BR testb ()
returns true (1) if the allocate would succeed, and returns false (0) if the
allocation would fail.
.\"
.\"
.SH ERRORS
.PP
.BR testb ()
always succeeds.
.\"
.\"
.SH CONTEXT
.PP
.BR testb ()
can be called from any context, including user context, module procedures,
callouts, callbacks, soft interrupts (tasklets and bottom halves), and interrupt service routines.
.\"
.\"
.SH MP-STREAMS
.PP
.BR testb ()
is MP-safe.
.\"
.\"
.SH NOTICES
.PP
As with other post
.I SVR 3 STREAMS
.[
svr3
.]
implementations, this implementation
ignores the
.I priority
argument to
.BR testb () .
The message block
.I priority
was an
.I SVR 3
.[
svr3
.]
concept which was found not to be useful, primarily due to
priority inversion.  For a history of the
.I priority
mechanism and a discussion as to why the mechanism was abandoned in
.IR "SVR 4.2" ,
.[
svr42
.]
see
.I \*(lqThe Magic Garden Explained\*(rq
section 7.7.2.
.[
magic
.]
.PP
.BR testb ()
can only test whether the allocation would succeed at a given moment in time.
It cannot indicate what would happen immediately following return from
.BR testb ().
Therefore, the return from
.BR allocb "(9) and " esballoc (9)
must always be tested for
.BR NULL .
.\"
.\"
.SH "SEE ALSO"
.PP
.BR allocb (9),
.BR esballoc (9).
.\"
.\"
.SH BUGS
.PP
.BR testb ()
has no known bugs.
.\"
.\"
.SH COMPATIBILITY
.PP
.BR testb ()
is compatible with
.I "SVR 4.2 MP DDI/DKI"
.[
usldk
.]
and systems based on
.I SVR 4
.[
svr4spg
.]
with the following portability considerations:
.IP \(em \w'\(em\(em'u
.IR AIX \(rg
.[
aixdoc
.]
defines the first argument as
.BR "register int" .
.IP \(em
.IR AIX \(rg
and
.IR Solaris \(rg
.[
soldoc
.]
ignore the
.I priority
argument.
.IP \(em
.IR UnixWare \(rg
.[
uw7doc
.]
.IR HP-UX \(rg
.[
hpuxdoc
.]
.IR SUPER-UX \(rg
.[
suxdoc
.]
.IR OSF/1 \(rg
.[
osfdoc
.]
do not.
.IP \(em
.IR OSF/1 \(rg
adds the
.B BPRI_WAITOK
priority.
.IP \(em
.IR UXP/V \(rg
.[
uxpdoc
.]
does not document this function.
.IP \(em
Binary compatibility is not guaranteed.
.PP
See
.BR STREAMS (9)
for additional compatibility information.
.\"
.\"
.SH CONFORMANCE
.PP
.IR "SVR 4.2 MP DDI/DKI" ,
.[
usldk
.]
.\"
.\"
.SH HISTORY
.PP
.BR testb ()
appears as part of
.IR "SVR 4.0 STREAMS" .
.[
svr4spg
.]
.PP
.BR testb ()
first appeared in
.IR "SVR 3" .
.[
svr3spg
.]
.\"
.\"
.[
$LIST$
.]
.TI
