@c -*- texinfo -*- vim: ft=texinfo
@c =========================================================================
@c
@c @(#) $Id: install.texi,v 1.1.4.2 2005/03/16 13:20:23 brian Exp $
@c
@c =========================================================================
@c
@c Copyright (C) 2001-2005  OpenSS7 Corporation <www.openss7.com>
@c Copyright (C) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
@c
@c All Rights Reserved.
@c
@c Permission is granted to make and distribute verbatim copies of this
@c manual provided the copyright notice and this permission notice are
@c preserved on all copies.
@c
@c Permission is granted to copy and distribute modified versions of this
@c manual under the conditions for verbatim copying, provided that the
@c entire resulting derived work is distributed under the terms of a
@c permission notice identical to this one
@c 
@c Since the Linux kernel and libraries are constantly changing, this
@c manual page may be incorrect or out-of-date.  The author(s) assume no
@c responsibility for errors or omissions, or for damages resulting from
@c the use of the information contained herein.  The author(s) may not
@c have taken the same level of care in the production of this manual,
@c which is licensed free of charge, as they might when working
@c professionally.
@c 
@c Formatted or processed versions of this manual, if unaccompanied by
@c the source, must acknowledge the copyright and authors of this work.
@c
@c -------------------------------------------------------------------------
@c
@c U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
@c on behalf of the U.S. Government ("Government"), the following
@c provisions apply to you.  If the Software is supplied by the Department
@c of Defense ("DoD"), it is classified as "Commercial Computer Software"
@c under paragraph 252.227-7014 of the DoD Supplement to the Federal
@c Acquisition Regulations ("DFARS") (or any successor regulations) and the
@c Government is acquiring only the license rights granted herein (the
@c license rights customarily provided to non-Government users).  If the
@c Software is supplied to any unit or agency of the Government other than
@c DoD, it is classified as "Restricted Computer Software" and the
@c Government's rights in the Software are defined in paragraph 52.227-19
@c of the Federal Acquisition Regulations ("FAR") (or any success
@c regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
@c NASA Supplement to the FAR (or any successor regulations).
@c
@c =========================================================================
@c 
@c Commercial licensing and support of this software is available from
@c OpenSS7 Corporation at a fee.  See http://www.openss7.com/
@c 
@c =========================================================================
@c
@c Last Modified $Date: 2005/03/16 13:20:23 $ by $Author: brian $
@c
@c =========================================================================

@menu
* Downloading::			Downloading the package
* Configuration::		Configuration of the package
* Building::			Building the package
* Installing::			Installing the package
* Removing::			Removing the package
* Loading::			Loading the package
@end menu

@c ----------------------------------------------------------------------------
@c ----------------------------------------------------------------------------

@node Downloading
@section Downloading
@cindex downloading

The @value{PACKAGE_TITLE} package releases can be downloaded from the downloads
page of @uref{http://www.openss7.org/download.html, The OpenSS7 Project}.  The
package is available as a binary RPM (for popular architectures) a source RPM,
Debian binary DEB and source DSC, or as a tar ball.  If you are using a
browsable viewer, you can obtain the OpenSS7 release of
@command{@value{PACKAGE_NAME}} from the links in the sections that follow.

By far the easiest form for installing and using
@command{@value{PACKAGE}-@value{VERSION}} is to download and install binary RPM.
If a binary RPM is not available for your distribution,  but your distribution
supports RPM, the next best method for installing and using
@command{@value{PACKAGE}-@value{VERSION}} is to download and rebuild the source
RPM.  If your architecture does not support RPM at all, or you have special
needs (such as cross-compiling for embedded targets), the final resort method is
to download, configure, build and install from the source tarball.

@menu
* Downloading the Binary RPM::		the easiest approach
* Downloading the Debian DEB::		the easiest approach for Debian
* Downloading the Source RPM::		the next best approach
* Downloading the Debian DSC::		the next best approach for Debian
* Downloading the Tar Ball::		last resort
* Downloading from CVS::		mid-release download
@end menu

@c ----------------------------------------------------------------------------

@node Downloading the Binary RPM
@subsection Downloading the Binary RPM
@cindex downloading, binary rpms
@cindex binary rpms

To install from binary RPM, you will need several of the RPM for a complete
installation.  Binary RPM fall into two categories.  To download and install a
complete package requires the appropriate RPM from each of the two categories
below.

To install from Binary RPM, you will need all of the following kernel
indepdendent packages for your architecture, and one of the kernel-depdendent
packages from the next section.

@subsubheading Independent RPM
Independent RPM are
not dependent on the Linux kernel version.
For example, the
source package
@samp{@value{PACKAGE}-source-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm},
is not dependent on
kernel.

@noindent
All of the following kernel independent RPM are required for your architecture.
Binary RPMs listed here are for example only: additional binary RPMs are
available from the downloads site.  If your architecture is not available, you
can build binary RPM from the source RPM (see @pxref{Building from the Source
RPM}).

@table @asis
@item @uref{http://www.openss7.org/rpms/RPMS/i686/@value{PACKAGE}-dev-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm, @value{PACKAGE}-dev-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm}
The @file{@value{PACKAGE}-dev} package contains the device definitions necessary
to run applications programs developed for @value{PACKAGE_TITLE}.@footnote{Not
all distributions support the @samp{%dev} RPM macro: a case in point is the SuSE
8.0 distribution which uses an older version of @command{rpm}.  Distributions
that do not support the @samp{%dev} macro will build devices as a @samp{%post}
operation.  Note also that not all release packages contain devices.  Only
packages that provide STREAMS character device drivers need devices, and then
only when the @samp{specfs} or @samp{devfsd} is not being used.}

@item @uref{http://www.openss7.org/rpms/RPMS/i686/@value{PACKAGE}-devel-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm, @value{PACKAGE}-devel-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm}
The @file{@value{PACKAGE}-devel} package contains library archives for static
compilation, header files to develop @value{PACKAGE_TITLE} modules and drivers.
This also includes the header files and static libraries required to compile
@value{PACKAGE_TITLE} applications programs.

@item @uref{http://www.openss7.org/rpms/RPMS/i686/@value{PACKAGE}-doc-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm, @value{PACKAGE}-doc-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm}
The @file{@value{PACKAGE}-doc} package contains this manual in plaintext,
postscript, PDF and HTML forms, along with the meta-information from the
@file{@value{PACKAGE_NAME}} package.  It also contains all of the manual pages
necessary for developing @value{PACKAGE_TITLE} applications and
@value{PACKAGE_TITLE} STREAMS modules or drivers.

@item @uref{http://www.openss7.org/rpms/RPMS/i686/@value{PACKAGE}-lib-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm, @value{PACKAGE}-lib-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm}
The @file{@value{PACKAGE}-lib} package contains the run-time shared libraries
necessary to run application programs and utilities developed for the
@file{@value{PACKAGE_NAME}} package.
@ignore
@footnote{Note that not all release packages contain shared libraries, and,
therefore, not all release packages contain this package.}
@end ignore

@item @uref{http://www.openss7.org/rpms/RPMS/i686/@value{PACKAGE}-source-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm, @value{PACKAGE}-source-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm}
The @file{@value{PACKAGE}-source} package contains the source code necessary for
building the @value{PACKAGE_TITLE} release.  It includes the @command{autoconf}
configuration utilities necessary to create and distribute tarballs, rpms and
deb/dscs.
@ignore
@footnote{Note that not all releases have source RPM packages.  Release packages
that do not contain kernel modules do not generate a source RPM package.}
@end ignore

@item @uref{http://www.openss7.org/rpms/RPMS/i686/@value{PACKAGE}-util-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm, @value{PACKAGE}-util-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm}
The @file{@value{PACKAGE}-util} package provides administrative and
configuration test utilities and commands associated with the
@value{PACKAGE_TITLE} package.
@end table

@ignore
@subsubheading STREAMS-Dependent RPM
STREAMS-Dependent RPM are dependent upon the specific STREAMS package being
used, either @cite{Linux STREAMS} or @cite{Linux Fast-STREAMS}.  Packages
dependent upon @cite{Linux STREAMS} will have @file{LiS} in the package name.
Packages dependent upon @cite{Linux Fast-STREAMS} will have @file{streams} in
the package name.  Note that some STREAMS-Dependent RPM are also
Kernel-Dependent RPM as described below.

@noindent
One of the following STREAMS-Dependent packages is required for your
architecture.  If your architecture is not on the list, you can build binary RPM
from the source RPM (see @pxref{Building from the Source RPM}).

@table @asis
@item @uref{http://www.openss7.org/rpms/RPMS/i686/@value{PACKAGE}-LiS-util-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm, @value{PACKAGE}-LiS-util-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm}
The @file{@value{PACKAGE}-LiS-util} package provides administrative and
configuration test utilities and commands associated with the
@value{PACKAGE_TITLE} package.  Because this package must link a
STREAMS-specific library, it is a STREAMS-Dependent package.  Use the
@file{@value{PACKAGE}-LiS-util} package if you have LiS installed.

@item @uref{http://www.openss7.org/rpms/RPMS/i686/@value{PACKAGE}-streams-util-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm, @value{PACKAGE}-streams-util-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm}
The @file{@value{PACKAGE}-streams-util} package provides administrative and
configuration test utilities and commands associated with the
@value{PACKAGE_TITLE} package.  Because this package must link a
STREAMS-specific library, it is a STREAMS-Dependent package.  Use the
@file{@value{PACKAGE}-streams-util} package if you have streams installed.
@end table
@end ignore

@subsubheading Kernel-Dependent RPM
Kernel-Dependent RPM are dependent on specific Linux Kernel Binary RPM releases.
Packages are provided for popular released @cite{RedHat} kernels.  Packages
dependent upon @cite{RedHat} or other kernel RPM will have the @samp{_kversion}
kernel package version in the package name.

One of the following Kernel-Dependent packages is required for your architecture
and kernel version.  If your architecture or kernel version is not on the list,
you can build binary RPM from the source RPM (see @pxref{Building from the
Source RPM}).@footnote{Note that on @cite{Mandrakelinux}, unlike other RPM
kernel distributions, kernel packages for the ix86 architectures are always
placed in i586 architecture packages regardless of the true processor
architecture of the kernel package.  @command{configure} detects this and builds
the appropriate packages.}

@table @asis
@item @uref{http://www.openss7.org/rpms/RPMS/i686/@value{PACKAGE}-core-@value{_kversion}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm, @value{PACKAGE}-core-@value{_kversion}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm}
The @file{@value{PACKAGE}-core} package contains the loadable kernel modules
that depend only on the kernel.  This package is heavily tied to the kernel for
which it was compiled.  This particular package applies to kernel version
@samp{@value{_kversion}}.@footnote{Note that the @samp{_kversion} of
@samp{@value{_kversion}} is only an example.  Note also that only release
packages that contain kernel modules will contain a @file{core} subpackage.}

@item @uref{http://www.openss7.org/rpms/RPMS/i686/@value{PACKAGE}-info-@value{_kversion}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm, @value{PACKAGE}-info-@value{_kversion}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm}
The @file{@value{PACKAGE}-info} package@footnote{Note that only release packages
that contain kernel modules and that export versioned symbols will contain a
@file{info} subpackage.  Also, this subpackage is only applicable to 2.4 series
kernels and is not necessary and not built for 2.6 series kernels.} contains the
module symbol version information for the @file{core} subpackage, above.  It is
possible to load this subpackage and compile modules that use the exported
symbols without loading the actual kernel modules (from the @file{core}
subpackage above).  This package is heavily tied to the kernel for which it was
compiled.  This particular package applies to kernel version
@samp{@value{_kversion}}.@footnote{Note that the @samp{_kversion} of
@samp{@value{_kversion}} is only an example.}

@ignore
@item @uref{http://www.openss7.org/rpms/RPMS/i686/@value{PACKAGE}-LiS-core-@value{_kversion}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm, @value{PACKAGE}-LiS-core-@value{_kversion}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm}
The @file{@value{PACKAGE}-LiS-core} package contains the kernel modules that
provide the @value{PACKAGE_TITLE} STREAMS modules and drivers.  This package is
heavily tied to the STREAMS package and kernel for which it was compiled.  This
particular package applies to @file{LiS} (@cite{Linux STREAMS}) on kernel
version @samp{@value{_kversion}}.@footnote{Note that the @samp{_kversion} of
@samp{@value{_kversion}} is only an example.}

@item @uref{http://www.openss7.org/rpms/RPMS/i686/@value{PACKAGE}-streams-core-@value{_kversion}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm, @value{PACKAGE}-streams-core-@value{_kversion}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm}
The @file{@value{PACKAGE}-streams-core} package contains the kernel modules that
provide the @value{PACKAGE_TITLE} STREAMS modules and drivers.  This package is
heavily tied to the STREAMS package and kernel for which it was compiled.  This
particular package applies to @file{streams} (@cite{Linux Fast-STREAMS}) on
kernel version @samp{@value{_kversion}}.@footnote{Note that the @samp{_kversion}
of @samp{@value{_kversion}} is only an example.}

@item @uref{http://www.openss7.org/rpms/RPMS/i686/@value{PACKAGE}-LiS-info-@value{_kversion}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm, @value{PACKAGE}-LiS-info-@value{_kversion}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm}
The @file{@value{PACKAGE}-LiS-info} package@footnote{Note that only release
packages that contain kernel modules and that export versioned symbols will
contain a @file{LiS-info} subpackage.} contains the module symbol version
information for the @file{LiS-core} subpackage, above.  It is possible to load
this subpackage and compile modules that use the exported symbols without loaded
the actual kernel modules (from the @file{LiS-core} subpackage above).  This
package is heavily tied to the STREAMS package and kernel for which it was
compiled.  This particular package applies to @file{LiS} (@cite{Linux STREAMS})
on kernel version @samp{@value{_kversion}}.@footnote{Note that the
@samp{_kversion} of @samp{@value{_kversion}} is only an example.}

@item @uref{http://www.openss7.org/rpms/RPMS/i686/@value{PACKAGE}-streams-info-@value{_kversion}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm, @value{PACKAGE}-streams-info-@value{_kversion}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm}
The @file{@value{PACKAGE}-streams-info} package@footnote{Note that only release
packages that contain kernel modules and that export versioned symbols will
contain a @file{streams-info} subpackage.} contains the module symbol version
information for the @file{streams-core} subpackage, above.  It is possible to
load this subpackage and compile modules that use the exported symbols without
loaded the actual kernel modules (from the @file{streams-core} subpackage
above).  This package is heavily tied to the STREAMS package and kernel for
which it was compiled.  This particular package applies to @file{streams}
(@cite{Linux Fast-STREAMS}) on kernel version
@samp{@value{_kversion}}.@footnote{Note that the @samp{_kversion} of
@samp{@value{_kversion}} is only an example.}
@end ignore
@end table

@subsubheading Configuration and Installation
To configure, build and install the binary RPM, @xref{Configuring the Binary
RPM}.

@c ----------------------------------------------------------------------------

@node Downloading the Debian DEB
@subsection Downloading the Debian DEB
@cindex downloading, debian debs
@cindex binary debs

@subsubheading Configuration and Installation
To configure, build and install the Debian DEB, @xref{Configuring the Debian
DEB}.

@c ----------------------------------------------------------------------------

@node Downloading the Source RPM
@subsection Downloading the Source RPM
@cindex downloading, source srpm
@cindex source rpms

If you cannot obtain a binary RPM for your architecture, or would like to roll
you own binary RPM, download the following source RPM.

@table @asis
@item @uref{http://www.openss7.org/rpms/SRPMS/@value{PACKAGE}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}.src.rpm, @value{PACKAGE}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}.src.rpm}
This is the source RPM for the package.  From this source RPM it is possible to
build binary RPM for any supported architecture and for any 2.4 or 2.6 kernel.
@end table

@subsubheading Configuration
To configure the source RPM, @xref{Configuring the Source RPM}.

@c ----------------------------------------------------------------------------

@node Downloading the Debian DSC
@subsection Downloading the Debian DSC
@cindex downloading, debian dscs
@cindex source dscs

@subsubheading Configuration
To configure the source RPM, @xref{Configuring the Debian DSC}.

@c ----------------------------------------------------------------------------

@node Downloading the Tar Ball
@subsection Downloading the Tar Ball
@cindex downloading, tar ball
@cindex tar ball

For non-RPM architectures, such as @cite{NexusWare} embedded target, download
the tarball as follows:

@table @asis
@item @uref{http://www.openss7.org/@value{PACKAGE}-@value{VERSION}.tar.gz, @value{PACKAGE}-@value{VERSION}.tar.gz}
@itemx @uref{http://www.openss7.org/@value{PACKAGE}-@value{VERSION}.tar.bz2, @value{PACKAGE}-@value{VERSION}.tar.bz2}
These are the @command{tar} balls for the release.  These @command{tar} balls
contain the @command{autoconf} distribution which includes all the source
necessary for building and installing the package.  These tarballs will even
build Source RPM and Binary RPM on RPM architectures and Debian DSC and DEB on
DPKG architectures.
@end table

The tar ball may be downloaded easily with @command{wget} as follows:

@example
@cartouche
% wget http://www.openss7.org/@value{PACKAGE}-@value{VERSION}.tar.bz2
@end cartouche
@end example

@noindent
or

@example
@cartouche
% wget http://www.openss7.org/@value{PACKAGE}-@value{VERSION}.tar.gz
@end cartouche
@end example

@subsubheading  Unpacking the Archive

After downloading one of the tar balls, unpack the archive using one of the
following commands:

@example
@cartouche
% wget http://www.openss7.org/@value{PACKAGE}-@value{VERSION}.tar.gz
% tar -xzvf @value{PACKAGE}-@value{VERSION}.tar.gz
@end cartouche
@end example

@noindent
or

@example
@cartouche
% wget http://www.openss7.org/@value{PACKAGE}-@value{VERSION}.tar.bz2
% tar -xjvf @value{PACKAGE}-@value{VERSION}.tar.bz2
@end cartouche
@end example

@noindent
Either will create a subdirectory name
@file{@value{PACKAGE}-@value{VERSION}}
containing all of the files and subdirectories for the
@command{@value{PACKAGE_NAME}} package.


@subsubheading Configuration
To configure and install the tar ball, @xref{Configuring the Tar Ball}.

@c ----------------------------------------------------------------------------

@node Downloading from CVS
@subsection Downloading from CVS
@cindex checkout, cvs
@cindex cvs

If you are a subscriber or sponsor of @uref{http://www.openss7.org/, The OpenSS7
Project} with CVS archive access privileges then you can download release or
mid-release versions of the @file{@value{PACKAGE_NAME}} package from the project
CVS archive.

The @value{PACKAGE_TITLE} package is located in the @file{@value{PACKAGE}}
subdirectory of @file{/var/cvs}.  For release tag information, see
@ref{Releases}.

To access the archive from the project CVS pserver, use the following commands
to check out a version from the archive:

@example
@cartouche
% export CVSROOT='-d:pserver:@var{username}@@cvs.openss7.com:2401/var/cvs'
% cvs login
Password: *********
% cvs co -r @value{PACKAGE}_@value{VERSION} @value{PACKAGE}
% cvs logout
@end cartouche
@end example

It is, of course, possible to check out by date or by other criteria.  For more
information, see @ref{cvs(1), cvs(1), cvs(1), *manpages*, The Manual Pages}.

@subsubheading Preparing the CVS Working Directory

Although public releases of the @file{@value{PACKAGE_NAME}} package do not
require reconfiguration, creating a configurable directory from the CVS archive
requires tools not normally distributed with the other releases.

The build host requires the following GNU tools:

@itemize
@item @command{autoconf 2.59}
@item @command{automake 1.9.5}
@item @command{libtool 1.5.14}
@item @command{gettext 0.14.1}
@item @command{texinfo 4.6}
@end itemize

It should be stressed that, in particular, the @command{autoconf} and
@command{automake} must be at version releases @command{2.59} and @command{1.9}.
@emph{The versions normally distributed in mainstream GNU/Linux distributions
are, in fact, much older than these versions.}@footnote{A notable exception is
Debian.}  GNU version of these packages configured and installed to default
directories will install in @file{/usr/local/} allowing them to coexist with
distribution installed versions.

In addition, the build host requires a complete tool chain for compiling for the
target host, including kernel tools such as @command{genksyms} and others.

To generate a configuration script and the necessary scriptlets required by the
GNU autoconf system, execute the following commands on the working directory:

@example
@cartouche
% autoreconf -fiv @value{PACKAGE}
@end cartouche
@end example

@noindent
where, @file{@value{PACKAGE}} is the name of the directory to where the working
copy was checked out under the previous step.  This command generates the
@command{configure} script and other missing pieces that are normally
distributed with the release Tar Balls, SRPMs and DSCs.

Make sure that @samp{autoreconf --version} returns @samp{2.59}.  Otherwise, you
may need to perform something like the following:

@example
@cartouche
% PATH="/usr/local/bin:$PATH"
% autoreconf -fiv @value{PACKAGE}
@end cartouche
@end example

@noindent
After reconfiguring the directory, the package can then be configured and built
using the same instructions as are used for the Tar Ball, see @ref{Configuring
the Tar Ball}, and @ref{Building from the Tar Ball}.

Do note, however, that @command{make} will rebuild the documentation that is
normally released with the package.  Additional tools may be necessary for
building the documentation.

When configuring the package in a working directory and while working a
change-compile-test cycle that involves configuration macros or documentation, I
find it of great advantage to invoke the GNU @command{configure} options
@command{--enable-maintainer-mode} and @command{--enable-dependency-tracking}.
The first of these two options will add maintainer-specific targets to any
generated @file{Makefile}, and the later will invoke automatic dependency
tracking within the @file{Makefile} so rebuilds after changes to macro, source
or documentation files will be automatically rebuilt.

@c ----------------------------------------------------------------------------
@c ----------------------------------------------------------------------------

@node Configuration
@section Configuration
@cindex configuration

@menu
* Configuring the Binary RPM::		the easiest approach
* Configuring the Debian DEB::		the easiest approach for Debian
* Configuring the Source RPM::		the next best approach
* Configuring the Debian DSC::		the next best approach for Debian
* Configuring the Tar Ball::		last resort
@end menu

@c ----------------------------------------------------------------------------

@node Configuring the Binary RPM
@subsection Configuring the Binary RPM
@cindex configuring, binary rpms
@cindex binary rpms

In general the binary RPM do not require any configuration, however, during
installation it is possible to relocate some of the installation directories.
This allows some degree of customization.  Relocations that are available on the
binary RPM are as follows:

@table @file
@item @value{PACKAGE}-core-@value{_kversion}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
@cindex @value{PACKAGE}-core-@value{_kversion}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
@table @asis
@item @file{@value{_rootdir}/lib/modules/@value{_kversion}}
This relocatable directory contains the kernel modules that provide the
@value{PACKAGE_NAME} core, drivers and modules.@footnote{Note that the
@samp{_kversion} of @samp{@value{_kversion}} is only an example.}
@end table

@item @value{PACKAGE}-info-@value{_kversion}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
@cindex @value{PACKAGE}-info-@value{_kversion}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
@table @asis
@item @file{@value{_rootdir}/usr/include/@value{PACKAGE}/@value{_kversion}}
This relocatable directory contains the kernel module exported symbol
information that allows other kernel modules to be compiled against the correct
version of the @value{PACKAGE} package.@footnote{Note that the @samp{_kversion}
of @samp{@value{_kversion}} is only an example.  Also, note that the @samp{info}
subpackage is only applicable to the 2.4 kernel series.}
@end table

@item @value{PACKAGE}-dev-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
@cindex @value{PACKAGE}-dev-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
(not relocatable)

@item @value{PACKAGE}-devel-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
@cindex @value{PACKAGE}-devel-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
@table @asis
@item @file{@value{_rootdir}@value{_libdir}}
This relocatable directory contains @value{PACKAGE} libraries.
@item @file{@value{_rootdir}@value{_includedir}/@value{PACKAGE}}
This relocatable directory contains @value{PACKAGE} header files.
@end table

@item @value{PACKAGE}-doc-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
@cindex @value{PACKAGE}-doc-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
@table @asis
@item @file{@value{_rootdir}@value{_datadir}/doc}
This relocatable directory contains all package specific documentation
(including this manual).  The subdirectory in this directory is the
@file{@value{PACKAGE}-@value{VERSION}} directory.
@item @file{@value{_rootdir}@value{_infodir}}
This relocatable directory contains info files (including the info version of
this manual).
@item @file{@value{_rootdir}@value{_mandir}}
This relocatable directory contains manual pages.
@end table

@item @value{PACKAGE}-lib-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
@cindex @value{PACKAGE}-lib-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
@table @asis
@item @file{@value{_rootdir}@value{_libdir}}
This relocatable directory contains the run-time shared libraries necessary to
run applications programs and utilities developed for @value{PACKAGE_TITLE}.
@item @file{@value{_rootdir}@value{_datadir}/locale}
This relocatable directory contains the locale information for shared library
files.
@end table

@item @value{PACKAGE}-source-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
@cindex @value{PACKAGE}-source-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
@table @asis
@item @file{@value{_rootdir}@value{_prefix}/src}
This relocatable directory contains the source code.
@end table

@item @value{PACKAGE}-util-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
@cindex @value{PACKAGE}-util-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
@table @asis
@item @file{@value{_rootdir}@value{_bindir}}
This relocatable directory contains binary programs and utilities.
@item @file{@value{_rootdir}@value{_sbindir}}
This relocatable directory contains system binary programs and utilities.
@item @file{@value{_rootdir}@value{_libexecdir}}
This relocatable directory contains test programs.
@item @file{@value{_rootdir}@value{_sysconfdir}}
This relocatable directory contains init scripts and configuration information.
@end table

@end table

@subsubheading Installation
To install the binary RPM, @xref{Installing the Binary RPM}.

@c ----------------------------------------------------------------------------

@node Configuring the Debian DEB
@subsection Configuring the Debian DEB
@cindex configuring, binary debs
@cindex binary debs

@subsubheading Installation
To install the Debian DEB, @xref{Installing the Debian DEB}.

@c ----------------------------------------------------------------------------

@node Configuring the Source RPM
@subsection Configuring the Source RPM
@cindex configuring, source srpm
@cindex source rpms

When building from the source RPM (@pxref{Building from the Source RPM}), the
rebuild process uses a number of macros from the user's @file{.rpmmacros} file
as described in @ref{rpm(8), rpm(8), rpm(8), *manpages*, The Manual Pages}.

Following is an example of the @file{~/.rpmmacros} file that I use for
rebuilding RPMS:

@smallexample
@cartouche
#
# RPM macros for building rpms
#

%_topdir /usr/src/openss7.rpms

%vendor OpenSS7 Corporation
%distribution OpenSS7
%disturl http://www.openss7.org/
%packager Brian Bidulock <bidulock@@openss7.org>
%url http://www.openss7.org/

%_signature gpg
%_gpg_path /home/brian/.gnupg
%_gpg_name openss7@@openss7.org
%_gpgbin /usr/bin/gpg

%_source_payload w9.bzdio
%_binary_payload w9.bzdio

%_unpackaged_files_terminate_build 1
%_missing_doc_files_terminate_build 1
%_enable_debug_packages 1

# 
# Template for debug information sub-package.
# with our little addition of release
# 
%debug_package \
%ifnarch noarch\
%global __debug_package 1\
%package debug\
Summary: Debug information for package %@{name@}\
Group: Development/Debug\
AutoReqProv: 0\
%@{?fullrelease:Release: %@{fullrelease@}@}\
%description debug\
This package provides debug information for package %@{name@}.\
Debug information is useful when developing applications that use this\
package or when debugging this package.\
%files debug -f debugfiles.list\
%defattr(-,root,root)\
%endif\
%@{nil@}

@end cartouche
@end smallexample


When building from the source RPM (@pxref{Building from the Source RPM}), it is
possible to pass a number of additional configuration options to the
@command{rpmbuild} process.

The additional configuration options are described below.

Note that distributions that use older versions of rpm do not have the
@samp{--with} or @samp{--without} options defined.  To acheive the same effect
as:
@example
--with someparm=somearg
@end example
do:
@example
--define "_with_someparm --with-someparm=somearg"
@end example

@ignore
This is a generic description of common @command{rpmbuild} options.  Not all
@command{rpmbuild} options are applicable to all SRPMs.  Options that are kernel
module specific are only applicable to SRPMs that build kernel modules.  STREAMS
options are only applicable to SRPMs that provide or require STREAMS.
@end ignore

@table @code
@item --define "_kversion $PACKAGE_KVERSION"
@vindex PACKAGE_KVERSION
@opindex k-release
Specifies the kernel version other than the running kernel for which to build.
If @command{_kversion} is not defined when rebuilding, the environment variable
@var{PACKAGE_KVERSION} is used.  If the environment variable
@var{PACKAGE_KVERSION} is not defined, then the version of the running kernel
(i.e. discovered with @samp{uname -r}) is used as the target version for
kernel-dependent packages.  This option can also be defined in an
@file{.rpmspec} file using the macro name @samp{_kversion}.

@ignore
@item --with checks
@itemx --without checks
@opindex checks
@end ignore

@item --with autotest
@itemx --without autotest
@opindex autotest
Enable preinstall checks.  Each packages supports a number of preinstall checks
that can be performed by invoking the @samp{check} target with @command{make}.
These currently consist of checking each kernel module for unresolved kernel
symbols, checking for documentation for exported kernel module symbols, checking
for documentation for exported library symbols, checking for standard options
for build and installable programs, checking for documentation for built and
installable programs.  Normally these checks are only run in maintainer mode,
but can be enabled and disabled with this option.

@item --with k-optimize=HOW
@itemx --without k-optimize
@opindex k-optimize
Specify @samp{HOW} optimization, @var{normal}, @var{size}, @var{speed} or
@var{quick}.  @var{size} compiles kernel modules @code{-Os}, @var{speed}
compiles kernel modules @code{-O3}, and @var{quick} compiles kernel modules
@code{-O0}.  The default is @var{normal}.  Use with care.

@item --with cooked-manpages
@itemx --without cooked-manpages
@opindex cooked-manpages
Some systems do not like @command{grefer} references in manpages.@footnote{In
particular, some @cite{Debian} systems do not load the @command{groff}
extensions package and do not have @command{grefer} installed.  Although this is
an oversight on the configuration of the particular @cite{Debian} system, we
accomodate such misconfiguration with this feature.}  This option will cook
@command{soelim}, @command{refer}, @command{tbl} and @command{pic} commands from
the manpages and also strip @command{groff} comments.  The default is to leave
manpages uncooked: they are actually smaller that way.

@item --with public
@itemx --without public
@opindex public
Release public packages or private packages.  This option has no effect on the
@file{@value{PACKAGE_NAME}} package.  The default is to release public packages.

@item --with k-debug
@itemx --without k-debug
@opindex k-debug
Specifies whether kernel debugging is to be performed on the build kernel
modules.  Mutually exclusive with @code{test} and @code{safe} below.  This has
the effect of removing static and inline attributes from functions and invoking
all debugging macros in the code.  The default is to not perform kernel
debugging.

@item --with k-test
@itemx --without k-test
@opindex k-test
Specifies whether kernel testing is to be performed.  Mutually exclusive with
@code{debug} above and @code{safe} below.  This has the effect of removing
static and inline attributes from functions and invoking most debugging macros
in the code.  The default is to not perform kernel testing.

@item --with k-safe
@itemx --without k-safe
@opindex k-safe
Specifies whether kernel saftey is to be performed.  Mutually exclusive with
@code{debug} and @code{test} above.  This has the effect of invoking some more
pedantic assertion macros in the code.  The default is not to apply kernel
safety.

@item --with k-inline
@itemx --without k-inline
@opindex k-inline
Specifies whether kernel @code{inline} functions are to be place inline.  This
has the effect of adding the @command{-finline-functions} flag to @var{CFLAGS}
for compiling kernel modules.  Linux 2.4 kernels are normally compiled
@command{-O2} which does not respect the @code{inline} directive.  This compiles
kernel modules with @command{-finline-functions} to get closer to @command{-O3}
optimization.  For better optimization controls, @xref{Configuring the Tar
Ball}.

@ignore
@item --with k-modversions
@itemx --without k-modversions
@opindex k-modversions
Specifies whether kernel symbol versioning is to be applied to symbols exported
by package kernel modules.  The default is to version exported module symbols.
This package does not export symbols so this option has no effect.
@end ignore

@item --with devfs
@itemx --without devfs
Specifies whether the build is for a device filesystem daemon enabled system
with autoloading, or not.  The default is to build for devfsd autoloading when
CONFIG_DEVFS_FS is defined in the target kernel.  The @command{reuild} target
uses this option to signal to the RPM spec file that the @samp{dev} subpackage
need not be built.  This option does not appear when the package has no devices.

@item --with tools
@itemx --without tools
@opindex tools
Specifies whether user space packages are to be built.  The default is to build
user space packages.  This option can be useful when rebuilding for multiple
architectures and target kernels.  The @command{rebuild} automake target uses
this feature when rebuilding for all available architectures and kernels, to
rebuild user packages once per architecture instead of once per kernel.

@item --with modules
@itemx --without modules
@opindex modules
Specifies whether kernel modules packages are to be built.  The default is to
build kernel module packages.  This option can be useful when rebuilding for
multiple architectures and target kernels.  The @command{rebuild} automake
target uses this feature to rebuild for all available architectures and kernels.

@ignore
@item --with lis
@itemx --without lis
@opindex lis
Specifies that the package is to be rebuilt against @cite{Linux STREAMS}.  The
default is to automatically identify whether @file{LiS} or @file{streams} is
loaded on the build system and build accordingly.

@item --with lfs
@itemx --without lfs
@opindex lfs
Specifies that the package is to be rebuilt against @cite{Linux Fast-STREAMS}.
The default is to automatically identify whether @file{LiS} or @file{streams} is
loaded on the build system and build accordingly.
@end ignore
@end table

@include rpm.texi

In general, the default values of these options are sufficient for most purposes
and no options need be provided when rebuilding the Source RPMs.

@subsubheading Build
To build from the source RPM, @xref{Building from the Source RPM}.

@c ----------------------------------------------------------------------------

@node Configuring the Debian DSC
@subsection Configuring the Debian DSC
@cindex configuring, source dscs
@cindex source dscs

@c ----------------------------------------------------------------------------

@node Configuring the Tar Ball
@subsection Configuring the Tar Ball
@cindex configuring, tar ball
@cindex tar ball

All of the normal GNU @command{autoconf} configuration options and environment
variables apply.  Additional options and environment variables are provided to
tailor or customize the build and are described below.

@menu
* Configure Options::		Options to @command{configure}
* Environment Variables::	Environment variables to @command{configure}
@end menu

@c ----------------------------------------------------------------------------

@node Configure Options
@subsubsection Configure Options
@cindex configure options

@ignore
This is a generic description of common @command{configure} options.  Not all
@command{configure} options are applicable to all release packages.  Options
that are kernel module specific are only applicable to release packages that
build kernel modules.  STREAMS options are only applicable to release packages
that provide or require STREAMS.
@end ignore

Following are the additional @command{configure} options, their meaning and use:

@table @command
@ignore
@item --enable-checks
@opindex checks
@end ignore

@item --enable-autotest
@itemx --disable-autotest
@opindex autotest
Enable preinstall checks.  Each packages supports a number of preinstall checks
that can be performed by invoking the @samp{check} target with @command{make}.
These currently consist of checking each kernel module for unresolved kernel
symbols, checking for documentation for exported kernel module symbols, checking
for documentation for exported library symbols, checking for standard options
for build and installable programs, checking for documentation for built and
installable programs.  Normally these checks are only run in maintainer mode,
but can be enabled and disabled with this option.

@item --disable-compress-manpages
@opindex compress-manpages
Compress manpages with @samp{gzip -9} or @samp{bzip2 -9} or leave them
uncompressed.  The default is to compress manpages with @samp{gzip -9}
or @samp{bzip2 -9} if a single compressed manpage exists in the target
installation directory (@command{--mandir}).  This disables automatic
compression.

@item --disable-public
@opindex public
Disable public release.  Has no effect on the @file{@value{PACKAGE_NAME}} release.
No private components exist in @file{@value{PACKAGE_NAME}} releases.

@item --disable-initscripts
@opindex initscripts
Disables the installation of init scripts.
The default is to configure and install init scripts and their associated
configuration files.

@item --enable-devfs
@itemx --disable-devfs
@opindex devfs
Specifies whether the build is for a device filesystem daemon enabled system
with autoloading, or not.  The default is to build for devfsd autoloading when
CONFIG_DEVFS_FS is defined in the target kernel.  The @command{reuild} target
uses this option to signal to the RPM spec file that the @samp{dev} subpackage
need not be built.  This option does not appear when the package has no devices.

@item --enable-tools
@opindex tools
Specifies whether user space programs and libraries are to be built and
installed.  The default is to build and install user space programs and
libraries.  This option can be useful when rebuilding for multiple architectures
and target kernels, particularly under rpm.  The @command{rebuild} target uses
this feature when rebuilding RPMs for all available architectures and kernels,
to rebuild user packages once per architecture instead of once per kernel.

@item --enable-modules
@opindex modules
Specifies whether kernel modules are to be built and installed.  The default is
to build and install kernel modules.  This option can be useful when rebuilding
for multiple architectures and target kernels, particularly under rpm.  The
@command{rebuild} automake target uses this feature to rebuild for all available
architectures and kernels.
@ignore
This option has no effect if there are no kernel modules in the package.
@end ignore

@item --enable-arch
@opindex arch
Specifies whether architectural dependent package components are to be built and
installed.  This option can be useful when rebuilding for multiple architectures
and target kernels, particularly under dpkg.  The default is to configure, build
and install architecture dependent package components.
@ignore
This option has no effect if there are no architecture dependent components in
the package.
@end ignore

@item --enable-indep
@opindex indep
Specifies whether architecture independent package components are to be built
and installed.  This option can be useful when rebuilding for multiple
architectures and target kernels, particularly under dpkg.  The default is to
configure, build and install architecture independent package components.
@ignore
This options has no effect if there are no architecture independent components
in the package.
@end ignore

@item --enable-k-inline
@opindex k-inline
Enable kernel inline functions.  Most Linux kernels build without
@command{-finline-functions}.  This option adds the @command{-finline-functions}
and @command{-Winline} flags to the compilation of kernel modules.  Use with
care.
@ignore
This option has no effect if there are no kernel modules in the package.
@end ignore

@item --enable-k-safe
@opindex k-safe
Enable kernel module run-time safety checks.  Specifies whether kernel safety is
to be performed.  This option is mutually exclusive with
@command{--enable-k-test} and @command{--enable-k-debug} below.  This has the
effect of invoking some more pedantic assertion macros in the code.  The default
is not to apply kernel safety.
@ignore
This option has no effect if there are no kernel modules in the package.
@end ignore

@item --enable-k-test
@opindex k-test
Enable kernel module run-teim testing.  Specifies whether kernel testing is to
be performed.  This option is mutually exclusive with @command{--enable-k-safe}
above and @command{--enable-k-debug} below.  This has the effect of remove
@code{static} and @code{inline} attributes from functions and invoking most
non-performance affecting debugging macros in the code.  The default is not to
perform kernel testing.
@ignore
This option has no effect if there are no kernel modules in the package.
@end ignore

@item --enable-k-debug
@opindex k-debug
Enable kernel module run-time debugging.  Specifies whether kernel debugging is
to be performed.  This option is mutuallly exclusive with
@command{--enable-k-safe} and @command{--enable-k-test} above.  This has the
effect of removing @code{static} and @code{inline} attributes from functions and
invoking all debuggin macros in the code (including performance-affecting debug
macros).  The default is to not perform kernel debugging.
@ignore
This option has no effect if there are no kernel modules in the package.
@end ignore

@ignore
@itemx --disable-k-modversions
@opindex k-modversions
Disable module versions on @command{@value{PACKAGE_NAME}} symbols.  Specifies
whether kernel symbol versioning is to be used on symbols exported from built
@command{@value{PACKAGE_NAME}} modules.  The default is to provide kernel symbol
versioning on all exported symbols.
This option has no effect if there are no kernel modules in the package.
@end ignore

@item --with-gpg-user=GNUPGUSER
@opindex gpg-user
Specify the @command{gpg} @samp{GNUPGUSER} for signing RPMs and tarballs.  The
default is the content of the environment variable @var{GNUPGUSER}.  If
unspecified, the @command{gpg} program will normally use the user name of the
account invoking the @command{gpg} program.  For building source RPMs, the RPM
macro @samp{_gpg_name} will override this setting.

@item --with-gpg-home=GNUPGHOME
@opindex gpg-home
Specify the @samp{GNUPGHOME} directory for signing RPMs and tarballs.  The
default is the user's @file{~/.gpg} directory.  For building source RPMs, the
RPM macro @samp{_gpg_path} will override this setting.

@item --with-pkg-epoch=EPOCH
@opindex pkg-epoch
Specifies the epoch for the package.  This is neither used for RPM nor Debian
packages, it applies to the tarball release as a whole.  The default is the
contents of the @file{.pkgepoch} file in the source directory or, if that file
does not exist, zero (0).

@item --with-pkg-release=RELEASE
@opindex pkg-release
Specifies the release for the package.  This is neither used for RPM nor Debian
packages, it applies to the tarball release as a whole.  The default is the
contents of the @file{.pkgrelease} file in the source directory or, if that file
does not exist, one (1).  This is the number after the last point in ther
package version number.

@item --with-pkg-distdir=DIR
@opindex pkg-distdir
Specifies the distribution directory for the package.  This is used by the
maintainer for building distributions of tarballs.  This is the directory into
which archives are copied for distribution.  The default is the top build
directory.

@item --with-cooked-manpages
@opindex cooked-manpages
Convert manual pages to remove macro dependencies and @command{grefer}
references.  Some systems do not like @command{grefer} references in
manpages.@footnote{In particular, some @cite{Debian} systems do not load the
@command{groff} extensions package and do not have @command{grefer} installed.
Although this is an oversight on the configuration of the particular
@cite{Debian} system, we accomodate such misconfiguration with this feature.}
This option will cook @command{soelim}, @command{refer}, @command{tbl} and
@command{pic} commands from the manpages and also strip @command{groff}
comments.  The default is to leave manpages uncooked (they are actually smaller
that way).

@item --with-rpm-epoch=PACKAGE_EPOCH
@opindex rpm-epoch
Specify the @samp{PACKAGE_EPOCH} for the RPM spec file.  The default is to use
the RPM epoch conatined in the file @file{.rpmepoch}.

@item --with-rpm-release=PACKAGE_RPMRELEASE
@opindex rpm-release
Specify the @samp{PACKAGE_RPMRELEASE} for the RPM rspec file.  The default is to
use the RPM release contained in the file @file{.rpmrelease}.

@item --with-rpm-extra=PACKAGE_RPMEXTRA
@opindex rpm-extra
Specify the @samp{PACKAGE_RPMEXTRA} extra release information for the RPM spec
file.  The default is to use the RPM extra release information contained in the
file @file{.rpmextra}.  Otherwise, this value will be determined from automatic
detection of the RPM distribution.

@item --with-rpm-topdir=PACKAGE_RPMTOPDIR
@opindex rpm-topdir
Specify the @samp{PACKAGE_RPMTOPDIR} top directory for RPMs.  If specified
with a null @samp{PACKAGE_RPMTOPDIR}, the default directory for the RPM
distribution will be used.  If this option is not provided on the command line,
the build directory will be used as the RPM top directory as well.

@item --with-deb-epoch=EPOCH
@opindex deb-epoch

@item --with-deb-release=RELEASE
@opindex deb-release

@item --with-deb-topdir=DIR
@opindex deb-topdir

@item --with-k-release=PACKAGE_KRELEASE
@opindex k-release
Specify the @samp{PACKAGE_KRELEASE} release of the Linux kernel for which the
build is targeted.  When not cross compiling, if this option is not set, the
build will be targeted at the kernel running in the build environment (e.g.,
@samp{uname -r}).  When cross-compiling this option must be specified or the
configure script will generate an error and terminate.

@ignore
@item --with-k-prefix=K-PREFIX-DIR
@opindex k-prefix
Specify the @samp{K-PREFIX-DIR} kernel directory prefix for install.  The
default is the root directory (@file{/}) of the build machine.  This directory
is normally located by the @command{configure} script and need only be provided
for special cross-build environments or when requested by a @command{configure}
script error message.

@item --with-k-rootdir=K-ROOTDIR
@opindex k-rootdir
Specify the @samp{K-ROOTDIR} root directory for configure.  The default is the
setting of environment variable @var{DESTDIR}, and if @var{DESTDIR} is not set,
the root directory (@file{/}) of the build machine.  This directory is normally
located by the @command{configure} script and need only be provided for special
cross-build environments or when requested by a @command{configure} script error
message.
@end ignore

@item --with-k-linkage=PACKAGE_KLINKAGE
@opindex k-linkage
Specify the @samp{PACKAGE_KLINKAGE} for kernel module linkage.  This can be one
of the following:
@itemize
@item @samp{loadable}
-- loadable kernel modules
@item @samp{linkable}
-- linkable kernel objects
@end itemize
The default is to build loadable kernel modules.

@item --with-k-modules=K-MODULES-DIR
@opindex k-modules
Specify the @samp{K-MODULES-DIR} directory to which kernel modules will be
installed.  The default is based on the option @command{--with-k-release},
@command{--with-k-prefix} and @command{--with-k-rootdir}.  The default is
@file{DESTDIR}/@file{K-MODULES-DIR} which is typically
@file{@var{DESTDIR}/lib/modules/@var{PACKAGE_KRELEASE}/}.  This directory is
normally located by the @command{configure} script and need only be provided for
special cross-build environments or when requested by a @command{configure}
script error message.

@item --with-k-build=K-BUILD-DIR
@opindex k-build
Specify the @samp{K-BUILD-DIR} base kernel build directory in which configured
kernel source resides.  The default is
@file{@var{DESTDIR}/@var{K-MODULES-DIR}/build}.  This directory is normally
located by the @command{configure} script and need only be provided for special
cross-build environments or when requested by a @command{configure} script error
message.

@item --with-k-sysmap=K-SYSMAP-FILE
@opindex k-sysmap
Specify the @samp{K-SYSMAP-FILE} kernel system map file.  The default is
@file{@var{K-BUILD-DIR}/System.map}.  This file is normally located by the
@command{configure} script and need only be provided for special cross-build
environments or when requested by a @command{configure} script error message.

@item --with-k-includes=K-INCLUDES-DIR
@opindex k-includes
Specify the @samp{K-INCLUDES-DIR} include directory of the kernel for which the
build is targeted.  The default is
@file{@var{DESTDIR}/@var{K-BUILD-DIR}/include}.  This directory is normally
located by the @command{configure} script and need only be provided for special
cross-build environments or when requested by a @command{configure} script error
message.

@item --with-k-archdir=K-ARCHDIR
@opindex k-archdir
Specify the @samp{K-ARCHDIR} kernel source architecture specific directory.  The
default is @file{@var{DESTDIR}/@var{K-BUILD-DIR}/arch}.  This directory is
normally located by the @command{configure} script and need only be provided for
special cross-build environments or when requested by a @command{configure}
script error message.

@item --with-k-machdir=K-MACHDIR
@opindex k-machdir
Specify the @samp{K-MACHDIR} kernel source machine specific directory.  The
default is @file{@var{DESTDIR}/@var{K-BUILD-DIR}/@var{target_cpu}}.  This
directory is normally located by the @command{configure} script and need only be
provided for special cross-build environments or when requested by a
@command{configure} script error message.

@item --with-k-config=K-CONFIG
@opindex k-config
Specify the @samp{K-CONFIG} kernel configuration file.  The default is
@file{@var{BOOT}/config-@var{K-RELEASE}}.  This configuration file is normally
located by the @command{configure} script and need only be provided forspecial
cross-build environments or when requested by a @command{configure} script error
message.

@item --with-k-optimize=HOW
@itemx --without-k-optimize
@opindex k-optimize
Specify @samp{HOW} optimization, @var{normal}, @var{size}, @var{speed} or
@var{quick}.  @var{size} compiles kernel modules @code{-Os}, @var{speed}
compiles kernel modules @code{-O3}, and @var{quick} compiles kernel modules
@code{-O0}.  The default is @var{normal}.  Use with care.

@ignore
@item --with-lis[=LIS-DIR]
@itemx --without-lis
@opindex lis
Specify the @samp{LIS-DIR} directory in which to find LiS headers.  Also
specifies that the build is to be made against Linux STREAMS.  The default is
@file{/usr/include/LiS} if it exists, @samp{no} otherwise.  This directory is
normally located by the @command{configure} script and need only be provided for
special cross-build environments or when requested by a @command{configure}
script error message.
This option has no effect on packages that do not use the STREAMS subsystem.

@item --with-lfs[=LFS-DIR]
@itemx --without-lfs
@opindex lfs
Specify the @samp{LFS-DIR} directory in which to find LfS headers.  Also
specifies that the build is to be made against Linux Fast-STREAMS.  The default
is @file{/usr/include/streams} if it exists, @samp{no} otherwise.  This
directory is normally located by the @command{configure} script and need only be
provided for special cross-build environments or when requested by a
@command{configure} script error message.
This option has no effect on packages that do not use the STREAMS subsystem.
@end ignore

@item --with-strconf-master=STRCONF_CONFIG
@opindex strconf-master
Specify the @samp{STRCONF_CONFIG} file name to which the configuration master
file is written.  The default is @file{Config.master}.
@ignore
This option has no effect on packages that do not use the STREAMS subsystem and
the strconf scripts.
@end ignore

@item --with-base-major=STRCONF_MAJBASE
@opindex base-major
Start numbering for major devices at @samp{STRCONF_MAJBASE}.  The default is
@samp{230}.
@ignore
This option has no effect on packages that do not use the STREAMS subsystem and
the strconf scripts.
@end ignore

@end table

@include configure.texi

@c ----------------------------------------------------------------------------

@node Environment Variables
@subsubsection Environment Variables
@cindex configure environment variables

Following are additional environment variables to @command{configure}, their
meaning and use:

@vtable @var
@item GPG
GPG signature command.  This is used for signing distributions by the
maintainer.  By default, @command{configure} will search for this tool.

@item GNUPGUSER
GPG user name.  This is used for signing distributions by the maintainer.

@item GNUPGHOME
GPG home directory.  This is used for signing distributions by the maintainer.

@item GPGPASSWD
GPG password for signing.  This is used for signing distributions by the
maintainer.  This environment variable is not maintained by the
@command{configure} script and should only be used on an isolated system.

@item SOELIM
Roff source elimination command.  This is only necessary when the option
@command{--with-cooked-manpages} has been specified and @command{configure}
cannot find the proper @command{soelim} command.  By default,
@command{configure} will search for this tool.

@item REFER
Roff references command.  This is only necessary when the option
@command{--with-cooked-manpages} has been specified and @command{configure}
cannot find the proper @command{refer} command.  By default, @command{configure}
will search for this tool.

@item TBL
Roff table command.  This is only necessary when the option
@command{--with-cooked-manpages} has been specified and @command{configure}
cannot find the proper @command{tbl} command.  By default, @command{configure}
will search for this tool.

@item PIC
Roff picture command.  This is only necessary when the option
@command{--with-cooked-manpages} has been specified and @command{configure}
cannot find the proper @command{pic} command.  By default, @command{configure}
will search for this tool.

@item GZIP
Default compression options provided to @command{GZIP_CMD}.

@item GZIP_CMD
Manpages (and kernel modules) compression commands.  This is only necessary when
the option @command{--without-compressed-manpages} has @emph{not} been specified
and @command{configure} cannot find the proper @command{gzip} command.  By
default, @command{configure} will search for this tool.

@item BZIP2
Default compression options provided to @command{BZIP2_CMD}

@item BZIP2_CMD
Manpages compression commands.  This is only necessary when the option
@command{--without-compressed-manpages} has @emph{not} been specified and
@command{configure} cannot find the proper @command{bzip2} command.  By default,
@command{configure} will search for this tool.

@item MAKEWHATIS
Manpages apropros database rebuild command.  By default, @command{configure}
will search for this tool.  By default, @command{configure} will search for this
tool.

@item CHKCONFIG
Chkconfig command.  This was used for installation of init scripts.  All
pacakges now come with @command{init_install} and @command{init_remove} scripts
used to install and remove init scripts on both RPM and debian systems.

@item RPM
Rpm command.  This is only necessary for RPM builds.  By default,
@command{configure} will search for this tool.

@item RPMBUILD
Build RPM command.  This is only necessary for RPM builds.  By default,
@command{configure} will search for this tool.  @command{rpm} will be used
instead of @command{rpmbuild} only if @command{rpmbuild} cannot be found.

@item DPKG
Dpkg comand.
This command is used for building debian packages.
By default, @command{configure} will search for this tool.

@item DPKG_SOURCE
Dpkg-source command.
This command is used for building debian dsc packages.
By default, @command{configure} will search for this tool.

@item DPKG_BUILDPACKAGE
Dpkg-buildpackage command.
This command is used for building debian deb packages.
By default, @command{configure} will search for this tool.

@item DEB_BUILD_ARCH
Debian build architecture.
This variable is used for building debian packages.
The default is the autoconf build architecutre.

@item DEB_BUILD_GNU_CPU
Debian build cpu.
This variable is used for building debian packages.
The default is the autoconf build cpu.

@item DEB_BUILD_GNU_SYSTEM
Debian build os.
This variable is used for building debian packages.
The default is the autoconf build os.

@item DEB_BUILD_GNU_TYPE
Debian build alias.
This variable is used for building debian packages.
The default is the autoconf build alias.

@item DEB_HOST_ARCH
Debian host architecture.
This variable is used for building debian packages.
The default is the autoconf host architecture.

@item DEB_HOST_GNU_CPU
Debian host cpu.
This variable is used for building debian packages.
The default is the autoconf host cpu.

@item DEB_HOST_GNU_SYSTEM
Debian host os.
This variable is used for building debian packages.
The default is the autoconf host os.

@item DEB_HOST_GNU_TYPE
Debian host alias.
This variable is used for building debian packages.
The default is the autoconf host alias.

@item LDCONFIG
Configure loader command.  Command used to configure the loader when libraries
are installed.  By default, @command{configure} will search for this tool.

@item DESTDIR
Cross build root directory.  Specifies the root directory for build and
installation.  For example, for @cite{NexusWare} cross-builds, this is set to
environment variable @var{NEXUSWARE_PREFIX} on configuration to point to the
root of the cross-build tree for both configuration and installation.

@item DEPMOD
Build kernel module dependencies command.  This is used during installation of
kernel modules to a running kernel to rebuild the modules dependency database.
By default, @command{configure} will search for this tool.

@item MODPROBE
Probe kernel module dependencies command.  This is used during installation of
kernel modules to a running kernel to remove old modules.  By default,
@command{configure} will search for this tool.

@item LSMOD
List kernel modules command.  This is used during installation of kernel modules
to a running kernel to detect old modules for removal.  By default,
@command{configure} will search for this tool.

@item LSOF
List open files command.  This is used during installation of kernel modules to
a running kernel to detect old modules for removal.  Processes owning the old
kernel modules will be killed and the module removed.  If the process restarts,
the new module will be demand loaded.  By default, @command{configure} will
search for this tool.

@item GENKSYMS
Generate kernel symbols command.  This is used for generating module symbol
versions during build.  By default, @command{configure} will search for this
tool.

@item KGENKSYMS
Linux 2.6 generate kernel symbols command.  This is used for generating module
symbol version during build.  By default, @command{configure} will search for
this tool.

@item OBJDUMP
Object dumping command.  This is used for listing information about object
files.  By default, @command{configure} will search for this tool.

@item NM
Object symbol listing command.  This is used for listing information about
object files.
By default, @command{configure} will search for this tool.

@item MODPOST_CACHE
Cache file for modpost.  The version of the @command{modpost.sh} script that
ships with each package can cache information to a cache file to speed multiple
builds.  This environment variable is used to specify a cache file.

@item AUTOM4TE
Autom4te command.
This is the executable used by autotest for pre- and post-installation checks.
By default, @command{configure} will search for this tool.

@item AUTOTEST
Autotest macro build command.
This is the executable used by autotest for pre- and post-installation checks.
By default, @command{configure} will search for this tool.
@end vtable

@subsubsection Build
To build from the tar ball, @xref{Building from the Tar Ball}.

@c ----------------------------------------------------------------------------
@c ----------------------------------------------------------------------------

@node Building
@section Building
@cindex building

@menu
* Building from the Source RPM::	the next best approach
* Building from the Debian DSC::	the next best approach for Debian
* Building from the Tar Ball::		last resort
@end menu

@c ----------------------------------------------------------------------------

@node Building from the Source RPM
@subsection Building from the Source RPM
@cindex building, source srpm
@cindex source rpms

If you have downloaded the necessary source RPM (@pxref{Downloading the Source
RPM}), then the following instructions will rebuild the binary RPMs on your
system.  Once the binary RPMs are rebuilt, you may install them as described
above (@pxref{Installing the Binary RPM}).

@noindent
The source RPM is rebuilt to binary RPMs as follows:

@example
@cartouche
% wget http://www.openss7.org/rpms/SRPMS/@value{PACKAGE}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}.src.rpm
% rpmbuild --rebuild -vv @value{PACKAGE}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}.src.rpm
@end cartouche
@end example

@noindent
The rebuild process can also recognize a number of options that can be used to
tweak the resulting binaries, @xref{Configuring the Source RPM}.  These options
are provided on the @command{rpm} command line.  For example:

@example
@cartouche
% rpmbuild --rebuild -vv --target athlon-redhat-linux \ 
  --define "_kversion @value{_kversion}" \ 
  -- @value{PACKAGE}-@value{VERSION}-@value{PACKAGE_RPMRELEASE}.src.rpm
@end cartouche
@end example

@noindent
will rebuild binary RPM for the @samp{@value{_kversion}} kernel for the
@samp{athlon} architecture.
@footnote{Note that the @samp{_kversion} of @samp{@value{_kversion}} is only an example.}

@subsubheading Installation

To install the resulting binary RPM, @xref{Installing the Binary RPM}.

@c ----------------------------------------------------------------------------

@node Building from the Debian DSC
@subsection Building from the Debian DSC
@cindex building, source dscs
@cindex source dscs

@c ----------------------------------------------------------------------------

@node Building from the Tar Ball
@subsection Building from the Tar Ball
@cindex building, tar ball
@cindex tar ball

If you have downloaded the tar ball (@pxref{Downloading the Tar Ball}), then the
following instructions will rebuild the package on your system.  (Note that the
build process does not required @command{root} privilege.)

@subsubsection Native Build

Folowing is an example of a native build against the running kernel:

@example
@cartouche
% wget http://www.openss7.org/@value{PACKAGE}-@value{VERSION}.tar.bz2
% tar -xjvf @value{PACKAGE}-@value{VERSION}.tar.bz2
% pushd @value{PACKAGE}-@value{VERSION}
% ./configure
% make
% popd
@end cartouche
@end example

@subsubsection Cross-Build

Following is an example for a cross-build.  The kernel release version must
always be specified for a cross-build.@footnote{Because it @emph{is} a
cross-build, the kernel version on the build machine is unlikely to be the
kernel version of the target machine, except by coincidence.}  If you are
cross-building, specify the root for the build with environment variable
@var{DESTDIR}.  The cross-compile host must also be specified if different from
the build host.  Either the compiler and other tools must be in the usual places
where GNU @command{autoconf} can find them, or they must be specified with
declarations such as @samp{CC=/u5/NexusWare24/ppc-linux/gcc} on the
@command{configure} command line.  Look in the file @file{configure.nexusware}
in the release package for an example.

@example
@cartouche
% wget http://www.openss7.org/@value{PACKAGE}-@value{VERSION}.tar.bz2
% tar -xjvf @value{PACKAGE}-@value{VERSION}.tar.bz2
% pushd @value{PACKAGE}-@value{VERSION}
% ./configure DESTDIR="/some/other/root" \ 
	--with-k-release=2.4.18 --host sparc-linux
% make
% popd
@end cartouche
@end example

@subsubsection NexusWare Build

Additional support is provided for cross-building for the @cite{Performance
Technologies Inc.} @cite{NexusWare} embedded target for the CPC-384, CPC-388 and
CPC-396 cards.  A configuration script wrapper (@file{configure.nexusware}) is
provided to simplify the cross-build operation for these targets.  The following
steps describe the process:

@enumerate
@item Follow the normal @cite{NexusWare} instructions for rebuilding a
@file{generic} kernel and flash image as follows:  (Note that I keep my
@cite{NexusWare} build in @file{/u5/NexusWare24}.)

@example
@cartouche
% pushd /u5/NexusWare24
% source SETUP.sh
% make
% popd
@end cartouche
@end example

@item Next download, unpack
(@pxref{Downloading the Tar Ball}) and configure (@pxref{Configuring the Tar
Ball}) using the provided @file{configure.nexusware} wrapper for
@command{configure}.  This wrapper simply tells the @command{configure} script
where to find the @cite{NexusWare} sources and which @cite{NexusWare}
cross-building tools to use for a cross-compile.@footnote{Although I have not
tried it, because we use GNU @command{autoconf} for configuration, these
instructions should work equally well for the Solaris @cite{NexusWare}
cross-building environment as it does for the Linux @cite{NexusWare}
cross-building environment.}

Any of the normal @command{configure} script options (@pxref{Configuring the Tar
Ball}) can be used on the same line as @samp{./configure.nexusware}.  One of
particular interest to embedded targets is @samp{--with-k-optimize=size} to
attempt to reduce the size of the kernel modules.

@item Install as normal (@pxref{Installing the Tar Ball}), however, for embedded
targets the @command{install-strip} target should be used instead of the
@command{install} target.  The @command{install-strip} target will strip
unnecessary symbols from kernel modules and further reduce the size in the root
file system flash image.

@end enumerate

Following is what I use for configuration and installation: (My @cite{NexusWare}
tree is rooted at @file{/u5/NexusWare}.)

@example
@cartouche
% pushd /u5/NexusWare24
% source SETUP.sh
% make
% popd
% wget http://www.openss7.org/@value{PACKAGE}-@value{VERSION}.tar.bz2
% tar -xjvf @value{PACKAGE}-@value{VERSION}.tar.bz2
% pushd @value{PACKAGE}-@value{VERSION}
% ./configure.nexusware --with-k-optimize=size
% make
% make install-strip
% popd
@end cartouche
@end example

Once built and installed in the @cite{NexusWare} directory, you will have to
(currently) hand edit a @file{.spec} file to include the components you want in
the @cite{NexusWare} root file system.  If you are cross-building for
@cite{NexusWare} you should already know what that means.  Objects that you
might be interested in copying to the root file system are kernel modules that
were installed in
@file{@var{$NEXUSWARE_PREFIX}/@-lib/@-modules/@-2.4.18/@-@value{PACKAGE_LCNAME}},
libraries installed in @file{@var{$NEXUSWARE_PREFIX}/@-usr/@-lib} and utility
functions installed in @file{@var{$NEXUSWARE_PREFIX}/@-usr/@-bin} and
@file{@var{$NEXUSWARE_PREFIX}/@-usr/@-sbin} and test programs in
@file{@var{$NEXUSWARE_PREFIX}/@-usr/@-libexec}.  If you would prefer that these
programs be installed in @file{@var{$NEXUSWARE_PREFIX}/@-lib},
@file{@var{$NEXUSWARE_PREFIX}/@-bin}, @file{@var{$NEXUSWARE_PREFIX}/@-sbin} and
@file{@var{$NEXUSWARE_PREFIX}/@-libexec}, (say because you want to remote mount
the @file{/usr} directory after boot), then specify the @samp{--exec-prefix=/}
option to @samp{./configure.nexusware}.

In addition, because @cite{NexusWare} does not include an
@file{/etc/modules.conf} file by default, it will be necessary to add one or
edit your @file{rc.4} file to @command{insmod} the necessary
@file{@value{PACKAGE_NAME}} modules at boot time.

Once you have completed the necessary @file{.spec} and @file{rc.4} file entries,
you need to rebuild the @samp{generic} kernel flash image once more for these
objects to be included in the flash file system.  It is important that this
second build of the kernel image be the same as the first.

When modifying and rebuilding a @cite{NexusWare} kernel, it will be necessary to
rebuild and install @file{@value{PACKAGE_NAME}}.  Simply perform the last @samp{make
install-strip} stage or start again with @samp{./configure.nexusware}.  You can
place the unpacked tarball in
@file{@var{$NEXUSWARE_PREFIX}/usr/src/@value{PACKAGE}}, and add the following to
the top-level @cite{NexusWare} @file{Makefile} to make the build process a
single step process instead of dual pass:

@smallexample
@cartouche
all:
...
        (cd kernels/generic; $(MAKE) depend)
        (cd usr/src/pcmcia-cs-3.2.1; $(MAKE) config)
        (cd kernels/generic; $(MAKE))
        (cd usr/src/pcmcia-cs-3.2.1; $(MAKE) pti)
        (cd usr/src/pti; $(MAKE))
        (cd drivers; $(MAKE))
        (cd utility; $(MAKE))
#       uncomment for @value{PACKAGE} build
#       (cd usr/src/@value{PACKAGE}; ./configure.nexusware; $(MAKE) install-strip)
        (cd build/generic; $(MAKE))
...
@end cartouche
@end smallexample

Another, perhaps simpler approach, is to make the necessary edits to the
@cite{NexusWare} top-level @file{Makefile} and @file{.spec} and @file{rc.4}
files, download and unpack the tar ball into the @cite{NexusWare} directory, and
build the @cite{NexusWare} flash image as normal:

@example
@cartouche
% wget http://www.openss7.org/@value{PACKAGE}-@value{VERSION}.tar.bz2
% pushd /u5/NexusWare24
% source SETUP.sh
% pushd usr/src
% tar -xjvf $@{DIRSTACK[2]@}/@value{PACKAGE}-@value{VERSION}.tar.bz2
% ln -sf @value{PACKAGE}-@value{VERSION} @value{PACKAGE}
% popd
% make
% popd
@end cartouche
@end example

@c ----------------------------------------------------------------------------
@c ----------------------------------------------------------------------------

@node Installing
@section Installing
@cindex installing

@menu
* Installing the Binary RPM::		the easiest approach
* Installing the Debian DEB::		the easiest approach for Debian
* Installing the Tar Ball::		last resort
@end menu

@c ----------------------------------------------------------------------------

@node Installing the Binary RPM
@subsection Installing the Binary RPM
@cindex installing, binary rpms
@cindex binary rpms

If you have downloaded the necessary binary RPMs (@pxref{Downloading the Binary
RPM}), or have rebuilt binary RPMs using the source RPM (@pxref{Building from
the Source RPM}), then the following instructions will install the RPMs on your
system. For additional information on @command{rpm}, see @ref{rpm(8), rpm(8),
rpm(8), *manpages*, The Manual Pages}.

@example
@cartouche
% pushd RPMS/i686
% rpm -ihv @value{PACKAGE}-*-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
@end cartouche
@end example

@noindent
You must have the correct binary RPMs downloaded or built for this to be
successful.

Some of the packages are relocatable and can have final installation directories
altered with the @samp{--relocate} option to @command{rpm}, see @ref{rpm, rpm(8),
rpm(8), rpm(8), *manpages*, The Manual Pages}.  For example, the following
will relocate the documentation and info directories:

@example
@cartouche
% pushd RPMS/i686
% rpm -ihv \ 
        --relocate '/usr/share/doc=/usr/local/share/doc' \ 
        --relocate '/usr/share/info=/usr/local/share/info' \ 
        -- @value{PACKAGE}-doc-@value{VERSION}-@value{PACKAGE_RPMRELEASE}@value{PACKAGE_RPMEXTRA}.i686.rpm
@end cartouche
@end example

@noindent
The previous example will install the @file{@value{PACKAGE}-doc} package by will
relocate the documentation an info directory contents to the @file{/usr/local}
version.

@c ----------------------------------------------------------------------------

@node Installing the Debian DEB
@subsection Installing the Debian DEB
@cindex installing, binary debs
@cindex binary debs

@c ----------------------------------------------------------------------------

@node Installing the Tar Ball
@subsection Installing the Tar Ball
@cindex installing, tar ball
@cindex tar ball

After the build process (@pxref{Building from the Tar Ball}), installation only
requires execution of one of two @command{make} targets:

@table @asis
@item @samp{make install}
The @samp{install} @command{make} target will install all the components of the
package.  Root privilege is required to successfully invoke this target.

@item @samp{make install-strip}
The @samp{install-strip} @command{make} target will install all the components
of the package, but will strip unnecessary information out of the objects and
compress manual pages.  Root privilege is required to successfully invoke this
target.
@end table

@c ----------------------------------------------------------------------------
@c ----------------------------------------------------------------------------

@node Removing
@section Removing
@cindex removing

@menu
* Removing the Binary RPM::		the easiest approach
* Removing the Debian DEB::		the easiest approach for Debian
* Removing the Source RPM::		the next best approach
* Removing the Debian DSC::		the next best approach for Debian
* Removing the Tar Ball::		last resort
@end menu

@c ----------------------------------------------------------------------------

@node Removing the Binary RPM
@subsection Removing the Binary RPM
@cindex removing, binary rpms
@cindex binary rpms

To remove an installed version of the binary RPMs (whether obtained from the
OpenSS7 binary RPM releases, or whether created by the source RPM), execute the
following command:

@example
@cartouche
% rpm -evv `rpm -qa | grep '^@value{PACKAGE}-'`
@end cartouche
@end example

For more information on @command{rpm}, see @ref{rpm(8), rpm(8), rpm(8),
*manpages*, The Manual Pages}.

@c ----------------------------------------------------------------------------

@node Removing the Debian DEB
@subsection Removing the Debian DEB
@cindex removing, binary debs
@cindex binary debs

@c ----------------------------------------------------------------------------

@node Removing the Source RPM
@subsection Removing the Source RPM
@cindex removing, source srpm
@cindex source rpms

To remove all the installed binary RPM build from the source RPM, see
@ref{Removing the Binary RPM}.  Then simply remove the binary RPM package
files and source RPM file.  A command such as:

@example
@cartouche
% find / -name '@value{PACKAGE}-*.rpm' -type f -print0 | xargs --null rm -f
@end cartouche
@end example

@noindent
should remove all @file{@value{PACKAGE_NAME}} RPMs from your system.

@c ----------------------------------------------------------------------------

@node Removing the Debian DSC
@subsection Removing the Debian DSC
@cindex removing, source dscs
@cindex source dscs

@c ----------------------------------------------------------------------------

@node Removing the Tar Ball
@subsection Removing the Tar Ball
@cindex removing, tar ball
@cindex tar ball

To remove a version installed from tar ball, change to the build directory where
the package was built and use the @samp{uninstall} @command{make} target as
follows:

@example
@cartouche
% cd /usr/src/@value{PACKAGE}
% make uninstall
% cd ..
% rm -fr @value{PACKAGE}-@value{VERSION}
% rm -f @value{PACKAGE}-@value{VERSION}.tar.gz
% rm -f @value{PACKAGE}-@value{VERSION}.tar.bz2
@end cartouche
@end example

If you have inadvertently removed the build directory and, therefore, no longer
have a configured directory from which to execute @samp{make uninstall}, then
perform all of the steps for configuration and installation (@pxref{Installing
the Tar Ball}) except the final installation and then perform the steps above.

@c ----------------------------------------------------------------------------
@c ----------------------------------------------------------------------------

@node Loading
@section Loading
@cindex loading

@subsection Normal Module Loading

When @file{@value{PACKAGE_NAME}} installs, modules and drivers are normally
configured for demand loading.  The @samp{install} and @samp{install-strip}
@command{make}
@fnindex make
@fnindex make install
@fnindex make install-strip
targets will make the necessary changes to the @file{/etc/modules.conf} file and
place the modules in an appropriate place in
@file{@value{_rootdir}/lib/modules/@value{_kversion}/@value{PACKAGE_LCNAME}}.
The @samp{make install} process should have copied the kernel module files
@file{streams-*.o} to the directory
@file{@value{_rootdir}/lib/modules/@value{_kversion}/@value{PACKAGE_LCNAME}}.
This means that to load any of these modules, you can simply execute, for
example, @samp{modprobe stream-@var{somedriver}}.@footnote{Note that the
@samp{_kversion} of @samp{@value{_kversion}} is only an example.}

@subsubsection Linux STREAMS Module Loading

The @file{@value{PACKAGE}} demand load system supports both the old kerneld and
the new kmod mechanisms for demand loading kernel modules.

The convention for @file{@value{PACKAGE}} kernel loadable object files is:
@itemize @bullet
@item Their name start with "streams-".
@item They are placed in @file{/lib/modules/@value{_kversion}/streams/}, where @samp{@value{_kversion}} is an example kernel version.
@pgindex /lib/modules/@value{_kversion}/streams/
@end itemize

If your kernel has been built using the @file{kerneld} daemon, then
@file{@value{PACKAGE_NAME}} kernel modules will automatically load as soon as
the STREAMS module is pushed or the driver is opened.  The @samp{make install}
process makes the necessary changes to the
@file{@value{_rootdir}/etc/modules.conf} file.  After the install, you will see
lines like the following added to your @file{@value{_rootdir}/etc/modules.conf}
file:

@example
@cartouche
prune modules.@value{PACKAGE_LCNAME}
if -f /lib/modules/`uname -r`/modules.@value{PACKAGE_LCNAME}
include /lib/modules/`uname -r`/modules.@value{PACKAGE_LCNAME}
endif
@end cartouche
@end example

@noindent
which will provide for demand loading of the modules if they have been built and
installed for the running kernel.  The @file{/lib/modules/@command{`uname
-r`}/modules.@value{PACKAGE_LCNAME}} file looks like this:

@smallexample
@cartouche
alias char-major-245  streams-@var{some_driver}
alias char-major-246  streams-@var{other_driver}
@end cartouche
@end smallexample

Note that STREAMS modules are not listed in this file, but will be loaded by
name using @file{kerneld} if available.

@subsubsection Linux Fast-STREAMS Module Loading

@cite{Linux Fast-STREAMS} has a wider range of kernel module loading mechanisms
than is provided by @cite{LiS}.  For mechanisms used for kernel module loading
under @cite{Linux Fast-STREAMS}, @xref{Top, About This Manual, , STREAMS, Linux
Fast-STREAMS Reference Manual}.


@subsection NexusWare Module Loading
@cindex NexusWare
@cindex loading kernel modules

Under exceptional circumstances, such as a @cite{NexusWare} build, it is
necessary to hand-edit a @file{.spec} and @file{rc.4} file to load the modules
at boot time.@footnote{At some time I expect to create an
@samp{install-nexusware} target that will make the necessary modifications to
the @file{.spec} and @file{rc.4} files automatically.}

