/*
 * Note: this file originally auto-generated by mib2c using
 *       version : 1.67.2.1 $ of : mfd-interface.m2c,v $ 
 *
 * $Id:$
 */
/*
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 * ***                                                               ***
 * ***  NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE NOTE  ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THIS FILE DOES NOT CONTAIN ANY USER EDITABLE CODE.      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***       THE GENERATED CODE IS INTERNAL IMPLEMENTATION, AND      ***
 * ***                                                               ***
 * ***                                                               ***
 * ***    IS SUBJECT TO CHANGE WITHOUT WARNING IN FUTURE RELEASES.   ***
 * ***                                                               ***
 * ***                                                               ***
 * *********************************************************************
 * *********************************************************************
 * *********************************************************************
 */

/* standard Net-SNMP includes */
#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>

/* include our parent header */
#include "strModTable.h"

#include <net-snmp/agent/table_container.h>
#include <net-snmp/library/container.h>

#include "strModTable_interface.h"

#include <ctype.h>

/**********************************************************************
 **********************************************************************
 ***
 *** Table strModTable
 ***
 **********************************************************************
 **********************************************************************/
/*
 * OPENSS7-STREAMS-MIB::strModTable is subid 1 of strMod.
 * Its status is Current.
 * OID: .1.3.6.1.4.1.29591.1.1.1.1.1.1.1, length: 14
*/
typedef struct strModTable_interface_ctx_s {

        netsnmp_container *container;
        netsnmp_cache *cache;

        strModTable_registration *user_ctx;

        netsnmp_table_registration_info tbl_info;

        netsnmp_baby_steps_access_methods access_multiplexer;

} strModTable_interface_ctx;

static strModTable_interface_ctx strModTable_if_ctx;

static void _strModTable_container_init(strModTable_interface_ctx * if_ctx);
static void _strModTable_container_shutdown(strModTable_interface_ctx * if_ctx);

netsnmp_container *
strModTable_container_get(void)
{
        return strModTable_if_ctx.container;
}

strModTable_registration *
strModTable_registration_get(void)
{
        return strModTable_if_ctx.user_ctx;
}

strModTable_registration *
strModTable_registration_set(strModTable_registration * newreg)
{
        strModTable_registration *old = strModTable_if_ctx.user_ctx;

        strModTable_if_ctx.user_ctx = newreg;
        return old;
}

int
strModTable_container_size(void)
{
        return CONTAINER_SIZE(strModTable_if_ctx.container);
}

/*
 * mfd multiplexer modes
 */
static Netsnmp_Node_Handler _mfd_strModTable_pre_request;
static Netsnmp_Node_Handler _mfd_strModTable_post_request;
static Netsnmp_Node_Handler _mfd_strModTable_object_lookup;
static Netsnmp_Node_Handler _mfd_strModTable_get_values;

/**
 * @internal
 * Initialize the table strModTable 
 *    (Define its contents and how it's structured)
 */
void
_strModTable_initialize_interface(strModTable_registration * reg_ptr, u_long flags)
{
        netsnmp_baby_steps_access_methods *access_multiplexer =
            &strModTable_if_ctx.access_multiplexer;
        netsnmp_table_registration_info *tbl_info = &strModTable_if_ctx.tbl_info;
        netsnmp_handler_registration *reginfo;
        netsnmp_mib_handler *handler;
        int mfd_modes = 0;

        DEBUGMSGTL(("internal:strModTable:_strModTable_initialize_interface", "called\n"));

    /*************************************************
     *
     * save interface context for strModTable
     */
        /*
         * Setting up the table's definition
         */
        netsnmp_table_helper_add_indexes(tbl_info, ASN_UNSIGNED,
                                                /** index: strModIdnum */
                                         0);

        /*  Define the minimum and maximum accessible columns.  This
           optimizes retrival. */
        tbl_info->min_column = STRMODTABLE_MIN_COL;
        tbl_info->max_column = STRMODTABLE_MAX_COL;

        /*
         * save users context
         */
        strModTable_if_ctx.user_ctx = reg_ptr;

        /*
         * call data access initialization code
         */
        strModTable_init_data(reg_ptr);

        /*
         * set up the container
         */
        _strModTable_container_init(&strModTable_if_ctx);
        if (NULL == strModTable_if_ctx.container) {
                snmp_log(LOG_ERR, "could not initialize container for strModTable\n");
                return;
        }

        /*
         * access_multiplexer: REQUIRED wrapper for get request handling
         */
        access_multiplexer->object_lookup = _mfd_strModTable_object_lookup;
        access_multiplexer->get_values = _mfd_strModTable_get_values;

        /*
         * no wrappers yet
         */
        access_multiplexer->pre_request = _mfd_strModTable_pre_request;
        access_multiplexer->post_request = _mfd_strModTable_post_request;

    /*************************************************
     *
     * Create a registration, save our reg data, register table.
     */
        DEBUGMSGTL(("strModTable:init_strModTable",
                    "Registering strModTable as a mibs-for-dummies table.\n"));
        handler = netsnmp_baby_steps_access_multiplexer_get(access_multiplexer);
        reginfo = netsnmp_handler_registration_create("strModTable", handler,
                                                      strModTable_oid,
                                                      strModTable_oid_size,
                                                      HANDLER_CAN_BABY_STEP | HANDLER_CAN_RONLY);
        if (NULL == reginfo) {
                snmp_log(LOG_ERR, "error registering table strModTable\n");
                return;
        }
        reginfo->my_reg_void = &strModTable_if_ctx;

    /*************************************************
     *
     * set up baby steps handler, create it and inject it
     */
        if (access_multiplexer->object_lookup)
                mfd_modes |= BABY_STEP_OBJECT_LOOKUP;
        if (access_multiplexer->set_values)
                mfd_modes |= BABY_STEP_SET_VALUES;
        if (access_multiplexer->irreversible_commit)
                mfd_modes |= BABY_STEP_IRREVERSIBLE_COMMIT;
        if (access_multiplexer->object_syntax_checks)
                mfd_modes |= BABY_STEP_CHECK_OBJECT;

        if (access_multiplexer->pre_request)
                mfd_modes |= BABY_STEP_PRE_REQUEST;
        if (access_multiplexer->post_request)
                mfd_modes |= BABY_STEP_POST_REQUEST;

        if (access_multiplexer->undo_setup)
                mfd_modes |= BABY_STEP_UNDO_SETUP;
        if (access_multiplexer->undo_cleanup)
                mfd_modes |= BABY_STEP_UNDO_CLEANUP;
        if (access_multiplexer->undo_sets)
                mfd_modes |= BABY_STEP_UNDO_SETS;

        if (access_multiplexer->row_creation)
                mfd_modes |= BABY_STEP_ROW_CREATE;
        if (access_multiplexer->consistency_checks)
                mfd_modes |= BABY_STEP_CHECK_CONSISTENCY;
        if (access_multiplexer->commit)
                mfd_modes |= BABY_STEP_COMMIT;
        if (access_multiplexer->undo_commit)
                mfd_modes |= BABY_STEP_UNDO_COMMIT;

        handler = netsnmp_baby_steps_handler_get(mfd_modes);
        netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject row_merge helper with prefix rootoid_len + 2 (entry.col)
     */
        handler = netsnmp_get_row_merge_handler(reginfo->rootoid_len + 2);
        netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject container_table helper
     */
        handler =
            netsnmp_container_table_handler_get(tbl_info,
                                                strModTable_if_ctx.container,
                                                TABLE_CONTAINER_KEY_NETSNMP_INDEX);
        netsnmp_inject_handler(reginfo, handler);

    /*************************************************
     *
     * inject cache helper
     */
        if (NULL != strModTable_if_ctx.cache) {
                handler = netsnmp_cache_handler_get(strModTable_if_ctx.cache);
                netsnmp_inject_handler(reginfo, handler);
        }

        /*
         * register table
         */
        netsnmp_register_table(reginfo, tbl_info);

}                               /* _strModTable_initialize_interface */

/**
 * @internal
 * Shutdown the table strModTable
 */
void
_strModTable_shutdown_interface(strModTable_registration * reg_ptr)
{
        /*
         * shutdown the container
         */
        // _strModTable_container_shutdown(&strModTable_if_ctx);
}

void
strModTable_valid_columns_set(netsnmp_column_info *vc)
{
        strModTable_if_ctx.tbl_info.valid_columns = vc;
}                               /* strModTable_valid_columns_set */

/**
 * @internal
 * convert the index component stored in the context to an oid
 */
int
strModTable_index_to_oid(netsnmp_index * oid_idx, strModTable_mib_index * mib_idx)
{
        int err = SNMP_ERR_NOERROR;

        /*
         * temp storage for parsing indexes
         */
        /*
         * strModIdnum(1)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/h
         */
        netsnmp_variable_list var_strModIdnum;

        /*
         * set up varbinds
         */
        memset(&var_strModIdnum, 0x00, sizeof(var_strModIdnum));
        var_strModIdnum.type = ASN_UNSIGNED;

        /*
         * chain temp index varbinds together
         */
        var_strModIdnum.next_variable = NULL;

        DEBUGMSGTL(("verbose:strModTable:strModTable_index_to_oid", "called\n"));

        /* strModIdnum(1)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/h */
        snmp_set_var_value(&var_strModIdnum, (u_char *) &mib_idx->strModIdnum,
                           sizeof(mib_idx->strModIdnum));

        err = build_oid_noalloc(oid_idx->oids, oid_idx->len, &oid_idx->len,
                                NULL, 0, &var_strModIdnum);
        if (err)
                snmp_log(LOG_ERR, "error %d converting index to oid\n", err);

        /*
         * parsing may have allocated memory. free it.
         */
        snmp_reset_var_buffers(&var_strModIdnum);

        return err;
}                               /* strModTable_index_to_oid */

/**
 * extract strModTable indexes from a netsnmp_index
 *
 * @retval SNMP_ERR_NOERROR  : no error
 * @retval SNMP_ERR_GENERR   : error
 */
int
strModTable_index_from_oid(netsnmp_index * oid_idx, strModTable_mib_index * mib_idx)
{
        int err = SNMP_ERR_NOERROR;

        /*
         * temp storage for parsing indexes
         */
        /*
         * strModIdnum(1)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/a/w/e/R/d/h
         */
        netsnmp_variable_list var_strModIdnum;

        /*
         * set up varbinds
         */
        memset(&var_strModIdnum, 0x00, sizeof(var_strModIdnum));
        var_strModIdnum.type = ASN_UNSIGNED;

        /*
         * chain temp index varbinds together
         */
        var_strModIdnum.next_variable = NULL;

        DEBUGMSGTL(("verbose:strModTable:strModTable_index_from_oid", "called\n"));

        /*
         * parse the oid into the individual index components
         */
        err = parse_oid_indexes(oid_idx->oids, oid_idx->len, &var_strModIdnum);
        if (err == SNMP_ERR_NOERROR) {
                /*
                 * copy out values
                 */
                mib_idx->strModIdnum = *((u_long *) var_strModIdnum.val.string);

        }

        /*
         * parsing may have allocated memory. free it.
         */
        snmp_reset_var_buffers(&var_strModIdnum);

        return err;
}                               /* strModTable_index_from_oid */

/* *********************************************************************
 * @internal
 * allocate resources for a strModTable_rowreq_ctx
 */
strModTable_rowreq_ctx *
strModTable_allocate_rowreq_ctx(void *user_init_ctx)
{
        strModTable_rowreq_ctx *rowreq_ctx = SNMP_MALLOC_TYPEDEF(strModTable_rowreq_ctx);

        DEBUGMSGTL(("internal:strModTable:strModTable_allocate_rowreq_ctx", "called\n"));

        if (NULL == rowreq_ctx) {
                snmp_log(LOG_ERR, "Couldn't allocate memory for a " "strModTable_rowreq_ctx.\n");
        }

        rowreq_ctx->oid_idx.oids = rowreq_ctx->oid_tmp;

        rowreq_ctx->strModTable_data_list = NULL;

        /*
         * if we allocated data, call init routine
         */
        if (!(rowreq_ctx->rowreq_flags & MFD_ROW_DATA_FROM_USER)) {
                if (SNMPERR_SUCCESS != strModTable_rowreq_ctx_init(rowreq_ctx, user_init_ctx)) {
                        strModTable_release_rowreq_ctx(rowreq_ctx);
                        rowreq_ctx = NULL;
                }
        }

        return rowreq_ctx;
}                               /* strModTable_allocate_rowreq_ctx */

/*
 * @internal
 * release resources for a strModTable_rowreq_ctx
 */
void
strModTable_release_rowreq_ctx(strModTable_rowreq_ctx * rowreq_ctx)
{
        DEBUGMSGTL(("internal:strModTable:strModTable_release_rowreq_ctx", "called\n"));

        netsnmp_assert(NULL != rowreq_ctx);

        strModTable_rowreq_ctx_cleanup(rowreq_ctx);

        /*
         * free index oid pointer
         */
        if (rowreq_ctx->oid_idx.oids != rowreq_ctx->oid_tmp)
                free(rowreq_ctx->oid_idx.oids);

        SNMP_FREE(rowreq_ctx);
}                               /* strModTable_release_rowreq_ctx */

/**
 * @internal
 * wrapper
 */
static int
_mfd_strModTable_pre_request(netsnmp_mib_handler *handler,
                             netsnmp_handler_registration *reginfo,
                             netsnmp_agent_request_info *agtreq_info,
                             netsnmp_request_info *requests)
{
        int rc;

        DEBUGMSGTL(("internal:strModTable:_mfd_strModTable_pre_request", "called\n"));

        if (1 != netsnmp_row_merge_status_first(reginfo, agtreq_info)) {
                DEBUGMSGTL(("internal:strModTable", "skipping additional pre_request\n"));
                return SNMP_ERR_NOERROR;
        }

        rc = strModTable_pre_request(strModTable_if_ctx.user_ctx);
        if (MFD_SUCCESS != rc) {
                /*
                 * nothing we can do about it but log it
                 */
                DEBUGMSGTL(("strModTable", "error %d from " "strModTable_pre_request\n", rc));
                netsnmp_request_set_error_all(requests, SNMP_VALIDATE_ERR(rc));
        }

        return SNMP_ERR_NOERROR;
}                               /* _mfd_strModTable_pre_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_strModTable_post_request(netsnmp_mib_handler *handler,
                              netsnmp_handler_registration *reginfo,
                              netsnmp_agent_request_info *agtreq_info,
                              netsnmp_request_info *requests)
{
        strModTable_rowreq_ctx *rowreq_ctx = netsnmp_container_table_row_extract(requests);
        int rc, packet_rc;

        DEBUGMSGTL(("internal:strModTable:_mfd_strModTable_post_request", "called\n"));

        /*
         * release row context, if deleted
         */
        if (rowreq_ctx && (rowreq_ctx->rowreq_flags & MFD_ROW_DELETED))
                strModTable_release_rowreq_ctx(rowreq_ctx);

        /*
         * wait for last call before calling user
         */
        if (1 != netsnmp_row_merge_status_last(reginfo, agtreq_info)) {
                DEBUGMSGTL(("internal:strModTable", "waiting for last post_request\n"));
                return SNMP_ERR_NOERROR;
        }

        packet_rc = netsnmp_check_all_requests_error(agtreq_info->asp, 0);
        rc = strModTable_post_request(strModTable_if_ctx.user_ctx, packet_rc);
        if (MFD_SUCCESS != rc) {
                /*
                 * nothing we can do about it but log it
                 */
                DEBUGMSGTL(("strModTable", "error %d from " "strModTable_post_request\n", rc));
        }

        return SNMP_ERR_NOERROR;
}                               /* _mfd_strModTable_post_request */

/**
 * @internal
 * wrapper
 */
static int
_mfd_strModTable_object_lookup(netsnmp_mib_handler *handler,
                               netsnmp_handler_registration *reginfo,
                               netsnmp_agent_request_info *agtreq_info,
                               netsnmp_request_info *requests)
{
        int rc = SNMP_ERR_NOERROR;
        strModTable_rowreq_ctx *rowreq_ctx = netsnmp_container_table_row_extract(requests);

        DEBUGMSGTL(("internal:strModTable:_mfd_strModTable_object_lookup", "called\n"));

        /*
         * get our context from mfd
         * strModTable_interface_ctx *if_ctx =
         *             (strModTable_interface_ctx *)reginfo->my_reg_void;
         */

        if (NULL == rowreq_ctx) {
                rc = SNMP_ERR_NOCREATION;
        }

        if (MFD_SUCCESS != rc)
                netsnmp_request_set_error_all(requests, rc);
        else
                strModTable_row_prep(rowreq_ctx);

        return SNMP_VALIDATE_ERR(rc);
}                               /* _mfd_strModTable_object_lookup */

/***********************************************************************
 *
 * GET processing
 *
 ***********************************************************************/
/*
 * @internal
 * Retrieve the value for a particular column
 */
NETSNMP_STATIC_INLINE int
_strModTable_get_column(strModTable_rowreq_ctx * rowreq_ctx,
                        netsnmp_variable_list * var, int column)
{
        int rc = SNMPERR_SUCCESS;

        DEBUGMSGTL(("internal:strModTable:_mfd_strModTable_get_column", "called for %d\n", column));

        netsnmp_assert(NULL != rowreq_ctx);

        switch (column) {

                /* strModName(2)/StreamsModuleName/ASN_OCTET_STR/char(char)//L/A/w/e/R/d/H */
        case COLUMN_STRMODNAME:
                var->type = ASN_OCTET_STR;
                rc = strModName_get(rowreq_ctx, (char **) &var->val.string, &var->val_len);
                break;

                /* strModType(3)/INTEGER/ASN_INTEGER/long(u_long)//l/A/w/E/r/d/h */
        case COLUMN_STRMODTYPE:
                var->val_len = sizeof(u_long);
                var->type = ASN_INTEGER;
                rc = strModType_get(rowreq_ctx, (u_long *) var->val.string);
                break;

                /* strModMajor(4)/UNSIGNED32/ASN_UNSIGNED/u_long(u_long)//l/A/w/e/R/d/h */
        case COLUMN_STRMODMAJOR:
                var->val_len = sizeof(u_long);
                var->type = ASN_UNSIGNED;
                rc = strModMajor_get(rowreq_ctx, (u_long *) var->val.string);
                break;

        default:
                snmp_log(LOG_ERR, "unknown column %d in _strModTable_get_column\n", column);
                break;
        }

        return rc;
}                               /* _strModTable_get_column */

int
_mfd_strModTable_get_values(netsnmp_mib_handler *handler,
                            netsnmp_handler_registration *reginfo,
                            netsnmp_agent_request_info *agtreq_info, netsnmp_request_info *requests)
{
        strModTable_rowreq_ctx *rowreq_ctx = netsnmp_container_table_row_extract(requests);
        netsnmp_table_request_info *tri;
        u_char *old_string;
        void (*dataFreeHook) (void *);
        int rc;

        DEBUGMSGTL(("internal:strModTable:_mfd_strModTable_get_values", "called\n"));

        netsnmp_assert(NULL != rowreq_ctx);

        for (; requests; requests = requests->next) {
                /*
                 * save old pointer, so we can free it if replaced
                 */
                old_string = requests->requestvb->val.string;
                dataFreeHook = requests->requestvb->dataFreeHook;
                if (NULL == requests->requestvb->val.string) {
                        requests->requestvb->val.string = requests->requestvb->buf;
                        requests->requestvb->val_len = sizeof(requests->requestvb->buf);
                } else if (requests->requestvb->buf == requests->requestvb->val.string) {
                        if (requests->requestvb->val_len != sizeof(requests->requestvb->buf))
                                requests->requestvb->val_len = sizeof(requests->requestvb->buf);
                }

                /*
                 * get column data
                 */
                tri = netsnmp_extract_table_info(requests);
                if (NULL == tri)
                        continue;

                rc = _strModTable_get_column(rowreq_ctx, requests->requestvb, tri->colnum);
                if (rc) {
                        if (MFD_SKIP == rc) {
                                requests->requestvb->type = SNMP_NOSUCHINSTANCE;
                                rc = SNMP_ERR_NOERROR;
                        }
                } else if (NULL == requests->requestvb->val.string) {
                        snmp_log(LOG_ERR, "NULL varbind data pointer!\n");
                        rc = SNMP_ERR_GENERR;
                }
                if (rc)
                        netsnmp_request_set_error(requests, SNMP_VALIDATE_ERR(rc));

                /*
                 * if the buffer wasn't used previously for the old data (i.e. it
                 * was allcoated memory)  and the get routine replaced the pointer,
                 * we need to free the previous pointer.
                 */
                if (old_string && (old_string != requests->requestvb->buf) &&
                    (requests->requestvb->val.string != old_string)) {
                        if (dataFreeHook)
                                (*dataFreeHook) (old_string);
                        else
                                free(old_string);
                }
        }                       /* for results */

        return SNMP_ERR_NOERROR;
}                               /* _mfd_strModTable_get_values */

/***********************************************************************
 *
 * SET processing
 *
 ***********************************************************************/

/*
 * SET PROCESSING NOT APPLICABLE (per MIB or user setting)
 */
/***********************************************************************
 *
 * DATA ACCESS
 *
 ***********************************************************************/
/**
 * @internal
 * wrapper around clean up a loop reference
 */
static int
_strModTable_loop_cleanup_context(strModTable_interface_ctx * wrap_ctx,
                                  strModTable_ref_loop_ctx * ref)
{
        DEBUGMSGTL(("internal:strModTable:_strModTable_loop_cleanup_context", "called\n"));

        return strModTable_loop_cleanup_context(wrap_ctx->user_ctx, ref);
}                               /* _strModTable_loop_cleanup_context */

/**
 * @internal
 * wrapper around save position
 */
static int
_strModTable_loop_save_position(strModTable_interface_ctx * wrap_ctx,
                                strModTable_ref_loop_ctx * ref, strModTable_ref_loop_ctx * ref_copy,
                                int reuse)
{
        DEBUGMSGTL(("internal:strModTable:_strModTable_loop_save_position", "called\n"));

        return strModTable_loop_save_position(wrap_ctx->user_ctx, ref, ref_copy, reuse);
}                               /* _strModTable_loop_save_position */

/**
 * @internal
 * wrapper around user get_first to setup the index oid
 */
static int
_strModTable_loop_get_first_wrapper(strModTable_interface_ctx * wrap_ctx,
                                    strModTable_ref_loop_ctx * loop_ctx_ref,
                                    strModTable_ref_rowreq_ctx * rowreq_ctx_ref)
{
        int rc;

        DEBUGMSGTL(("internal:strModTable:_strModTable_loop_get_first_wrapper", "called\n"));

        rc = strModTable_loop_get_first(wrap_ctx->user_ctx, loop_ctx_ref, rowreq_ctx_ref);
        /*
         * convert index to OID
         */
        if (SNMPERR_SUCCESS == rc) {
                netsnmp_assert((NULL != rowreq_ctx_ref) &&
                               (rowreq_ctx_ref->rowreq_ctx->oid_idx.oids ==
                                rowreq_ctx_ref->rowreq_ctx->oid_tmp));
                rowreq_ctx_ref->rowreq_ctx->oid_idx.len =
                    sizeof(rowreq_ctx_ref->rowreq_ctx->oid_tmp);
                rc = strModTable_index_to_oid(&rowreq_ctx_ref->rowreq_ctx->oid_idx,
                                              &rowreq_ctx_ref->rowreq_ctx->tbl_idx);
                netsnmp_assert(rowreq_ctx_ref->rowreq_ctx->oid_idx.len !=
                               sizeof(rowreq_ctx_ref->rowreq_ctx->oid_tmp));
        }

        return rc;
}                               /* _strModTable_loop_get_first_wrapper */

/**
 * @internal
 * wrapper around user get_next to setup the index oid
 */
static int
_strModTable_loop_get_next_wrapper(strModTable_interface_ctx * wrap_ctx,
                                   strModTable_ref_loop_ctx * loop_ctx_ref,
                                   strModTable_ref_rowreq_ctx * rowreq_ctx_ref)
{
        int rc;

        DEBUGMSGTL(("internal:strModTable:_strModTable_loop_get_next_wrapper", "called\n"));

        rc = strModTable_loop_get_next(wrap_ctx->user_ctx, loop_ctx_ref, rowreq_ctx_ref);
        /*
         * convert index to OID
         */
        if (SNMPERR_SUCCESS == rc) {
                netsnmp_assert((NULL != rowreq_ctx_ref) &&
                               (rowreq_ctx_ref->rowreq_ctx->oid_idx.oids ==
                                rowreq_ctx_ref->rowreq_ctx->oid_tmp));
                rowreq_ctx_ref->rowreq_ctx->oid_idx.len =
                    sizeof(rowreq_ctx_ref->rowreq_ctx->oid_tmp);
                rc = strModTable_index_to_oid(&rowreq_ctx_ref->rowreq_ctx->oid_idx,
                                              &rowreq_ctx_ref->rowreq_ctx->tbl_idx);
                netsnmp_assert(rowreq_ctx_ref->rowreq_ctx->oid_idx.len !=
                               sizeof(rowreq_ctx_ref->rowreq_ctx->oid_tmp));
        }

        return rc;
}                               /* _strModTable_loop_get_next_wrapper */

/**
 * @internal
 * get data wrapper to allocate context for the user
 */
static int
_strModTable_loop_get_data_wrapper(strModTable_interface_ctx * wrap_ctx,
                                   strModTable_ref_loop_ctx * loop_ctx_ref,
                                   strModTable_ref_rowreq_ctx * rowreq_ctx_ref)
{
//    strModTable_rowreq_ctx *orig_ctx = rowreq_ctx_ref->rowreq_ctx;

        DEBUGMSGTL(("internal:strModTable:_strModTable_loop_get_data_wrapper", "called\n"));

        return strModTable_loop_get_data(wrap_ctx->user_ctx, loop_ctx_ref, rowreq_ctx_ref);
}                               /* _strModTable_loop_get_data_wrapper */

/**
 * @internal
 * initialize the iterator container with functions or wrappers
 */
void
_strModTable_container_init(strModTable_interface_ctx * if_ctx)
{
        DEBUGMSGTL(("internal:strModTable:_strModTable_container_init", "called\n"));

        if_ctx->container = netsnmp_container_iterator_get(
                                                       /** registration */
                                                                  if_ctx,
        /** compare */
                                                                  NULL,
        /** get_first */
                                                                  (Netsnmp_Iterator_Loop_Key *)
                                                                  _strModTable_loop_get_first_wrapper,
        /** get_next */
                                                                  (Netsnmp_Iterator_Loop_Key *)
                                                                  _strModTable_loop_get_next_wrapper,
        /** get_data */
                                                                  (Netsnmp_Iterator_Loop_Data *)
                                                                  _strModTable_loop_get_data_wrapper,
        /** save_pos */
                                                                  (Netsnmp_Iterator_Ctx_Dup *)
                                                                  _strModTable_loop_save_position,
        /** init_context */
                                                                  (Netsnmp_Iterator_Ctx *) NULL,
        /** cleanup_context */
                                                                  (Netsnmp_Iterator_Ctx *)
                                                                  _strModTable_loop_cleanup_context,
        /** free_user_ctx */
                                                                  NULL,
        /** sorted */
                                                                  0);
}                               /* _strModTable_container_init */

strModTable_rowreq_ctx *
strModTable_row_find_by_mib_index(strModTable_mib_index * mib_idx)
{
        strModTable_rowreq_ctx *rowreq_ctx;
        oid oid_tmp[MAX_OID_LEN];
        netsnmp_index oid_idx;
        int rc;

        /*
         * set up storage for OID
         */
        oid_idx.oids = oid_tmp;
        oid_idx.len = sizeof(oid_tmp) / sizeof(oid);

        /*
         * convert
         */
        rc = strModTable_index_to_oid(&oid_idx, mib_idx);
        if (MFD_SUCCESS != rc)
                return NULL;

        rowreq_ctx = CONTAINER_FIND(strModTable_if_ctx.container, &oid_idx);

        return rowreq_ctx;
}
