###############################################################################
#   Instructions to Make, for compilation of ISODE documentation tree
###############################################################################

###############################################################################
#
# $Header: /a/vulcan/xtel/isode/isode-master/doc/RCS/Makefile,v 8.0 91/07/17 10:28:54 isode Rel $
#
#
# $Log:	Makefile,v $
# Revision 8.0  91/07/17  10:28:54  isode
# Release 7.0
# 
# 
###############################################################################

###############################################################################
#
#				 NOTICE
#
#    Acquisition, use, and distribution of this module and related
#    materials are subject to the restrictions of a license agreement.
#    Consult the Preface in the User's Manual for the full terms of
#    this agreement.
#
###############################################################################

all clean install inst-all lint:;
