'\" rtp
.\" -*- nroff -*- vim: ft=nroff
.\"
.\" @(#) $Id: strclean.8.man,v 0.9.2.1 2004/03/04 23:15:47 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (C) 2001-2003  OpenSS7 Corporation <www.openss7.com>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" -------------------------------------------------------------------------
.\"
.\" U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
.\" on behalf of the U.S. Government ("Government"), the following
.\" provisions apply to you.  If the Software is supplied by the Department
.\" of Defense ("DoD"), it is classified as "Commercial Computer Software"
.\" under paragraph 252.227-7014 of the DoD Supplement to the Federal
.\" Acquisition Regulations ("DFARS") (or any successor regulations) and the
.\" Government is acquiring only the license rights granted herein (the
.\" license rights customarily provided to non-Government users).  If the
.\" Software is supplied to any unit or agency of the Government other than
.\" DoD, it is classified as "Restricted Computer Software" and the
.\" Government's rights in the Software are defined in paragraph 52.227-19
.\" of the Federal Acquisition Regulations ("FAR") (or any success
.\" regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
.\" NASA Supplement to the FAR (or any successor regulations).
.\"
.\" =========================================================================
.\" 
.\" Commercial licensing and support of this software is available from
.\" OpenSS7 Corporation at a fee.  See http://www.openss7.com/
.\" 
.\" =========================================================================
.\"
.\" Last Modified $Date: 2004/03/04 23:15:47 $ by $Author: brian $
.\"
.\" =========================================================================
.so streams.macros
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database streams.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.\"
.\"
.TH STRCLEAN 8 "$Date: 2004/03/04 23:15:47 $" "$Name:  $" "Linux Fast-STREAMS Administration"
.\"
.\"
.SH NAME
.B strclean
\- cleans up the \fISTREAMS\fR error logger
.\"
.\"
.SH SYNOPSIS
.PP
.HP 12
\fBstrclean \fR[\fB-d \fR[\fIdirectory\fR]] [\fB-a \fR[\fIage\fR]]
.\"
.\"
.SH DESCRIPTION
.PP
The
.B strclean
command is used to clean up the
.I STREAMS
error-logger directory on a regular basis: for example, by using the
.BR cron (8)
daemon.  By default, all files with names matching
.BI error.mm-dd
in the
.B /var/adm/streams
directory that have not been modified in the last three days are removed.
.PP
.B Note:
The
.B strclean
comman is typically run using the
.BR cron (8)
daemon on a daily or weekly basis.
.\"
.\"
.SH OPTIONS
.PP
.TP
\fR[\fB-d\fR, \fB--directory\fR \fIdirectory\fR]
Specifies a directory other than
.BR /var/adm/streams .
If not specified,
.I directory
defaults to
.BR /var/adm/streams .
.TP
\fR[\fB-a\fR, \fB--age\fR \fIage\fR]
Specifies the maximum age, in days, other than three (3), for a log file.
If not specified,
.I age
defaults to three (3).
.\"
.\"
.SH DIAGNOSTICS
.PP
.\"
.\"
.SH NOTICES
.PP
.\"
.\"
.SH EXAMPLES
.PP
.\"
.\"
.SH DEVICES
.PP
.\"
.\"
.SH FILES
.PP
.TP
.B /usr/sbin/strclean
contains the
.B strclean
command.
.\"
.TP
.BI /var/adm/streams/error. mm-dd
contains the
.I STREAMS
error log.
.\"
.SH "SEE ALSO"
.PP
.BR cron (8),
.BR strerr (8).
.\"
.\"
.SH BUGS
.PP
.\"
.\"
.SH COMPATIBILITY
.PP
.BR "SVR 4.2" ,
.BR AIX \(rg,
.BR HPUX \(rg,
.BR OSF \(rg,
.BR Solaris \(rg,
.BR UnixWare \(rg,
.BR UXP/V \(rg,
.\"
.\"
.SH CONFORMANCE
.PP
.BR "SVR 4.2" ;
.[
svr42cr
.]
.BR AIX \(rg,
.BR HPUX \(rg,
.BR OSF \(rg,
.BR Solaris \(rg,
.BR UnixWare \(rg,
.BR UXP/V \(rg,
documentation.
.\"
.\"
.SH HISTORY
.PP
.\"
.\"
.[
$LIST$
.]
.TI
