	{NET_SCTP_RTO_INITIAL, "sctp_rto_initial",
	 &sysctl_sctp_rto_initial, sizeof(int), 0644, NULL,
	 &proc_doulongvec_ms_jiffies_minmax, &sysctl_intvec, NULL,
	 &sysctl_sctp_rto_min, &sysctl_sctp_rto_max},
	{NET_SCTP_RTO_MIN, "sctp_rto_min",
	 &sysctl_sctp_rto_min, sizeof(int), 0644, NULL,
	 &proc_doulongvec_ms_jiffies_minmax, &sysctl_intvec, NULL,
	 NULL, &sysctl_sctp_rto_max},
	{NET_SCTP_RTO_MAX, "sctp_rto_max",
	 &sysctl_sctp_rto_max, sizeof(int), 0644, NULL,
	 &proc_doulongvec_ms_jiffies_minmax, &sysctl_intvec, NULL,
	 &sysctl_sctp_rto_min, NULL},
	{NET_SCTP_HEARTBEAT_ITVL, "sctp_heartbeat_itvl",
	 &sysctl_sctp_heartbeat_itvl, sizeof(int), 0644, NULL,
	 &proc_dointvec_jiffies, &sysctl_jiffies},
	{NET_SCTP_INIT_RETRIES, "sctp_init_retries",
	 &sysctl_sctp_max_init_retries, sizeof(int), 0644, NULL, &proc_dointvec},
	{NET_SCTP_VALID_COOKIE_LIFE, "sctp_valid_cookie_life",
	 &sysctl_sctp_valid_cookie_life, sizeof(int), 0644, NULL,
	 &proc_doulongvec_ms_jiffies_minmax, &sysctl_intvec, NULL,
	 NULL, NULL},
	{NET_SCTP_MAX_SACK_DELAY, "sctp_max_sack_delay",
	 &sysctl_sctp_max_sack_delay, sizeof(int), 0644, NULL,
	 &proc_doulongvec_ms_jiffies_minmax, &sysctl_intvec, NULL,
	 NULL, NULL},
	{NET_SCTP_PATH_MAX_RETRANS, "sctp_path_max_retrans",
	 &sysctl_sctp_path_max_retrans, sizeof(int), 0644, NULL, &proc_dointvec},
	{NET_SCTP_ASSOC_MAX_RETRANS, "sctp_assoc_max_retrans",
	 &sysctl_sctp_assoc_max_retrans, sizeof(int), 0644, NULL, &proc_dointvec},
	{NET_SCTP_MAC_TYPE, "sctp_mac_type",
	 &sysctl_sctp_mac_type, sizeof(int), 0644, NULL, &proc_dointvec},
	{NET_SCTP_CSUM_TYPE, "sctp_csum_type",
	 &sysctl_sctp_csum_type, sizeof(int), 0644, NULL, &proc_dointvec},
	{NET_SCTP_COOKIE_INC, "sctp_cookie_inc",
	 &sysctl_sctp_cookie_inc, sizeof(int), 0644, NULL,
	 &proc_doulongvec_ms_jiffies_minmax, &sysctl_intvec, NULL,
	 NULL, NULL},
	{NET_SCTP_THROTTLE_ITVL, "sctp_throttle_itvl",
	 &sysctl_sctp_throttle_itvl, sizeof(int), 0644, NULL,
	 &proc_doulongvec_ms_jiffies_minmax},
	{NET_SCTP_MEM, "sctp_mem",
	 &sysctl_sctp_mem, sizeof(sysctl_sctp_mem), 0644, NULL, &proc_dointvec},
	{NET_SCTP_WMEM, "sctp_wmem",
	 &sysctl_sctp_wmem, sizeof(sysctl_sctp_wmem), 0644, NULL, &proc_dointvec},
	{NET_SCTP_RMEM, "sctp_rmem",
	 &sysctl_sctp_rmem, sizeof(sysctl_sctp_rmem), 0644, NULL, &proc_dointvec},
	{NET_SCTP_MAX_ISTREAMS, "sctp_max_istreams",
	 &sysctl_sctp_max_istreams, sizeof(int), 0644, NULL, &proc_dointvec_minmax,
	 &sysctl_intvec, NULL, &min_sctp_max_istreams, NULL },
	{NET_SCTP_REQ_OSTREAMS, "sctp_req_ostreams",
	 &sysctl_sctp_req_ostreams, sizeof(int), 0644, NULL, &proc_dointvec_minmax,
	 &sysctl_intvec, NULL, &min_sctp_req_ostreams, NULL },
	{NET_SCTP_ECN, "sctp_ecn",
	 &sysctl_sctp_ecn, sizeof(int), 0644, NULL, &proc_dointvec},
	{NET_SCTP_ADAPTATION_LAYER_INFO, "sctp_adaptation_layer_info",
	 &sysctl_sctp_adaptation_layer_info, sizeof(int), 0644, NULL, &proc_dointvec},
	{NET_SCTP_PARTIAL_RELIABILITY, "sctp_partial_reliability",
	 &sysctl_sctp_partial_reliability, sizeof(int), 0644, NULL, &proc_dointvec},
	{NET_SCTP_MAX_BURST, "sctp_max_burst",
	 &sysctl_sctp_max_burst, sizeof(int), 0644, NULL, &proc_dointvec_minmax,
	 &sysctl_intvec, NULL, &min_sctp_max_burst, NULL},
