###############################################################################
#   Instructions to Make, for compilation of QUIPU scripts
###############################################################################

###############################################################################
#
# $Header: /xtel/isode/isode/others/quipu/tools/scripts/RCS/Makefile,v 9.0 1992/06/16 12:44:05 isode Rel $
#
#
# $Log: Makefile,v $
# Revision 9.0  1992/06/16  12:44:05  isode
# Release 8.0
#
# 
###############################################################################

###############################################################################
#
#				 NOTICE
#
#    Acquisition, use, and distribution of this module and related
#    materials are subject to the restrictions of a license agreement.
#    Consult the Preface in the User's Manual for the full terms of
#    this agreement.
#
###############################################################################


##################################################################
# Here it is...
##################################################################

all:;

inst-all:;

install:;

lint:;

clean:;		rm -f _*

grind:;
