'\" rtp
.\" -*- nroff -*- vim: ft=nroff
.\"
.\" @(#) $Id: fdetach.8.man,v 0.9.2.2 2004/03/04 23:15:46 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (C) 2001-2003  OpenSS7 Corporation <www.openss7.com>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" -------------------------------------------------------------------------
.\"
.\" U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
.\" on behalf of the U.S. Government ("Government"), the following
.\" provisions apply to you.  If the Software is supplied by the Department
.\" of Defense ("DoD"), it is classified as "Commercial Computer Software"
.\" under paragraph 252.227-7014 of the DoD Supplement to the Federal
.\" Acquisition Regulations ("DFARS") (or any successor regulations) and the
.\" Government is acquiring only the license rights granted herein (the
.\" license rights customarily provided to non-Government users).  If the
.\" Software is supplied to any unit or agency of the Government other than
.\" DoD, it is classified as "Restricted Computer Software" and the
.\" Government's rights in the Software are defined in paragraph 52.227-19
.\" of the Federal Acquisition Regulations ("FAR") (or any success
.\" regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
.\" NASA Supplement to the FAR (or any successor regulations).
.\"
.\" =========================================================================
.\" 
.\" Commercial licensing and support of this software is available from
.\" OpenSS7 Corporation at a fee.  See http://www.openss7.com/
.\" 
.\" =========================================================================
.\"
.\" Last Modified $Date: 2004/03/04 23:15:46 $ by $Author: brian $
.\"
.\" =========================================================================
.so streams.macros
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database streams.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.\"
.\"
.TH FDETACH 8 "$Date: 2004/03/04 23:15:46 $" "$Name:  $" "Linux Fast-STREAMS Administration"
.\"
.\"
.SH NAME
.B fdetach
\- unlink a named \fISTREAMS\fR file
.\"
.\"
.SH SYNOPSIS
.PP
.HP
\fBfdetach\fI  path\fP
.HP
\fBfdetach\fR { \fB-h\fR | \fB--help\fR }
.HP
\fBfdetach\fR { \fB-v\fR | \fB--version\fR }
.\"
.\"
.SH OPTIONS
.PP
.TP 12
.I path
the path to the file to which the
.I STREAMS
special file is attached.
.TP
.BR -h ", " --help
.TP
.BR -v ", " --version
.PP
If
.B fdetach
is executed without a
.I path
name, a short usage summary is printed.
.\"
.\"
.SH DESCRIPTION
.PP
The
.B fdetach
command detaches or disassociates a file descriptor for an open
.I STREAMS
device or pipe from its filename in the file system.  The path argument is the
path that was previously associated with the file descriptor with the
.BR fattach (3)
function.
.PP
Operations on path will subsequently affect the file system node, not the
.I STREAMS
device or pipe.  The permission and status of the node are returned to the
state that they were in before the
.I STREAMS
device or pipe was attached.  Any other paths that the
.I STREAMS
device or pipe may be attached to are not affected.
.PP
To successfully issue the
.B fdetach
command, the caller must be superuser or must be the owner of the file and
have write permission.
.\"
.\"
.SH DIAGNOSTICS
.PP
.B fdetach
returns 0 (zero) on success.  If
.B fdetach
fails, it returns 1 and prints a message to
.IR stderr .
.\"
.\"
.SH NOTICES
.PP
.B fdetach
simply calls
.BR fdetach (3)
for the specified
.IR path .
.\"
.\"
.SH "SEE ALSO"
.PP
.BR fattach (3),
.BR fdetach (3).
.\"
.\"
.SH BUGS
.PP
.B fdetach
has no known bugs.
.\"
.\"
.SH COMPATIBILITY
.PP
.B fdetach
is compatible with
.BR "SVR 4.2" ,
.[
svr42cr
.]
.BR HPUX \(rg,
.BR OSF \(rg,
.BR Solaris \(rg,
.BR UnixWare \(rg,
.BR UXP/V \(rg
and
.BR LiS ,
.[
LiS
.]
with the following considerations:
.IP \(em 4
.BR AIX \(rg
does not support the
.B fdetach
command.  However,
.BR umount (1)
may be used in its stead.
.IP \(em 4
.IP \(em 4
.IP \(em 4
.\"
.\"
.SH CONFORMANCE
.PP
.BR "SVR 4.2" ;
.[
svr42cr
.]
.BR HPUX \(rg,
.BR OSF \(rg,
.BR Solaris \(rg,
.BR UnixWare \(rg
and
.BR UXP/V \(rg
documentation.
.\"
.\"
.SH HISTORY
.PP
.BR fdetach
first appeared in
.BR "SVR 4" .
.[
svr4
.]
.\"
.\"
.[
$LIST$
.]
.TI
