'\" rtp
.\" -*- nroff -*- vim: ft=nroff
.\"
.\" @(#) $Id: recvfrom.3,v 0.9.2.1 2004/02/29 19:06:48 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (C) 2001-2003  OpenSS7 Corporation <www.openss7.com>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" -------------------------------------------------------------------------
.\"
.\" U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
.\" on behalf of the U.S. Government ("Government"), the following
.\" provisions apply to you.  If the Software is supplied by the Department
.\" of Defense ("DoD"), it is classified as "Commercial Computer Software"
.\" under paragraph 252.227-7014 of the DoD Supplement to the Federal
.\" Acquisition Regulations ("DFARS") (or any successor regulations) and the
.\" Government is acquiring only the license rights granted herein (the
.\" license rights customarily provided to non-Government users).  If the
.\" Software is supplied to any unit or agency of the Government other than
.\" DoD, it is classified as "Restricted Computer Software" and the
.\" Government's rights in the Software are defined in paragraph 52.227-19
.\" of the Federal Acquisition Regulations ("FAR") (or any success
.\" regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
.\" NASA Supplement to the FAR (or any successor regulations).
.\"
.\" =========================================================================
.\" 
.\" Commercial licensing and support of this software is available from
.\" OpenSS7 Corporation at a fee.  See http://www.openss7.com/
.\" 
.\" =========================================================================
.\"
.\" Last Modified $Date: 2004/02/29 19:06:48 $ by $Author: brian $
.\"
.\" =========================================================================
.so openss7.macros
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database openss7.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.\"
.\"
.\"
.\"
.TH RECVFROM 3 "$Date: 2004/02/29 19:06:48 $" "$Name:  $" "Linux Fast-STREAMS Sockets Library"
.SH NAME
.B recvfrom
\- receive a message from a socket
.SH SYNOPSIS
.PP
.B #include <sys/socket.h>
.HP
.BI "ssize_t recvfrom(int " socket ", void *" buffer ", size_t " length ", int " flags ", struct sockaddr *" address ", socklen_t *" address_len );
.SH DESCRIPTION
.PP
The
.BR recvfrom ()
function receives a message from a connection-mode or
connectionless-mode socket.  It is normally used with connectionless-mode
sockets because it permits the application to retrieve the source address of
received data.
.PP
The function takes the following arguments:
.TP 12
.I socket
Specifies the socket file descriptor.
.TP 12
.I buffer
Points to the buffer where the message should be stored.
.TP 12
.I length
Specifies the length in bytes of the buffer pointed to by the buffer argument.
.TP 12
.I flags
Specifies the type of message reception.  Values of this argument are formed by
logically OR'ing zero or more of the following values:
.RS
.TP 12
.B MSG_PEEK
Peeks at an incoming message.  The data is treated as unread and the next
.BR recvfrom ()
or similar function will still return this data.
.TP 12
.B MSG_OOB
Requests out-of-band data.  The significance and semantics of out-of-band data
are protocol-specific.
.TP 12
.B MSG_WAITALL
Requests that the function block until the full amount of data requested can
be returned.  The function may return a smaller amount of data if a signal is
caught, if the connection is terminated, if
.B MSG_PEEK
was specified, or if an
error is pending for the socket.
.RE
.TP 12
.I address
A null pointer, or points to a sockaddr structure in which the sending address
is to be stored.  The length and format of the address depend on the address
family of the socket.
.TP 12
.I address_len
Specifies the length of the sockaddr structure pointed to by the address
argument.
.PP
The
.BR recvfrom ()
function returns the length of the message written to the
buffer pointed to by the buffer argument.  For message-based sockets such as
.B SOCK_DGRAM
and
.BR SOCK_SEQPACKET ,
the entire message must be read in a single
operation.  If a message is too long to fit in the supplied buffer, and
.B MSG_PEEK
is not set in the flags argument, the excess bytes are discarded.  For
stream-based sockets such as
.BR SOCK_STREAM ,
message boundaries are ignored.  In
this case, data is returned to the user as soon as it becomes available, and
no data is discarded.
.PP
If the
.B MSG_WAITALL
flag is not set, data will be returned only up to the end
of the first message.
.PP
Not all protocols provide the source address for messages.  If the address
argument is not a null pointer and the protocol provides the source address of
messages, the source address of the received message is stored in the sockaddr
structure pointed to by the address argument, and the length of this address
is stored in the object pointed to by the address_len argument.
.PP
If the actual length of the address is greater than the length of the supplied
sockaddr structure, the stored address will be truncated.
.PP
If the address argument is not a null pointer and the protocol does not
provide the source address of messages, the the value stored in the object
pointed to by address is unspecified.
.PP
If no messages are available at the socket and
.B O_NONBLOCK
is not set on the
socket's file descriptor,
.BR recvfrom ()
blocks until a message arrives.  If no
messages are available at the socket and
.B O_NONBLOCK
is set on the socket's
file descriptor,
.BR recvfrom ()
fails and sets errno to
.RB [ EAGAIN "] or [" EWOULDBLOCK ].
.SH NOTES
.PP
The
.BR select (2)
and
.BR poll (2)
functions can be used to determine when data is
available to be received.
.SH CAVEATS
.PP
This system call is implemented as a
.B SIOCSOCKSYS
IOCTL.  See
.BR socksys (4)
for more information.
.SH "RETURN VALUE"
.PP
Upon successful completion,
.BR recvfrom ()
returns the length of the message in
bytes.  If no messages are available to be received and the peer has performed
an orderly shutdown,
.BR recvfrom ()
returns 0.  Otherwise the function returns -1
and sets errno to indicate the error.
.SH ERRORS
.PP
The
.BR recvfrom ()
function will fail if:
.TP 12
.RB [ EAGAIN "] or [" EWOULDBLOCK ]
The socket's file descriptor is marked
.B O_NONBLOCK
and no data is waiting to be
received; or
.B MSG_OOB
is set and no out-of-band data is available and either
the socket's file descriptor is marked
.B O_NONBLOCK
or the socket does not
support blocking to await out-of-band data.
.TP 12
.RB [ EBADF ]
The socket argument is not a valid file descriptor.
.TP 12
.RB [ ECONNRESET ]
A connection was forcibly closed by a peer.
.TP 12
.RB [ EFAULT ]
The buffer, address or address_len parameter can not be accessed or written.
.TP 12
.RB [ EINTR ]
A signal interrupted
.BR recvfrom ()
before any data was available.
.TP 12
.RB [ EINVAL ]
The
.B MSG_OOB
flag is set and no out-of-band data is available.
.TP 12
.RB [ ENOTCONN ]
A receive is attempted on a connection-mode socket that is not connected.
.TP 12
.RB [ ENOTSOCK ]
The socket argument does not refer to a socket.
.TP 12
.RB [ EOPNOTSUPP ]
The specified flags are not supported for this socket type.
.TP 12
.RB [ ETIMEDOUT ]
The connection timed out during connection establishment, or due to a
transmission timeout on active connection.
.PP
The
.BR recvfrom ()
function may fail if:
.TP 12
.RB [ EIO ]
An I/O error occurred while reading from or writing to the file system.
.TP 12
.RB [ ENOBUFS ]
Insufficient resources were available in the system to perform the operation.
.TP 12
.RB [ ENOMEM ]
Insufficient memory was available to fulfill the request.
.TP 12
.RB [ ENOSR ]
There were insufficient
.IR STREAMS (4)
resources available for the operation to
complete.
.SH "SEE ALSO"
.PP
.BR poll (2),
.BR read (2),
.BR recv (3),
.BR recvmsg (3),
.BR select (2),
.BR send (3),
.BR sendmsg (3),
.BR sendto (3),
.BR shutdown (3),
.BR socket (3),
.BR write (2),
.BR <sys/socket.h> (5).
.SH "CONFORMING TO"
.PP
The Open Group XNS Issue 5.2.
.[
xns
.]
.\"
.\"
.[
$LIST$
.]
.TA
