#!/bin/bash
#
# @(#) $RCSfile: strcompat,v $ $Name:  $($Revision: 0.9.2.11 $) $Date: 2007/08/13 23:51:40 $
# Copyright (c) 2001-2007  OpenSS7 Corporation <http://www.openss7.com>
# Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
# All Rights Reserved.
#
# Distributed by OpenSS7 Corporation.  See the bottom of this script for copying
# permissions.
#
# Redhat chkconfig init script conventions
#
# strcompat:	start and stop strcompat subsystem
# chkconfig:	2345 02 97
# lockfile:	/var/lock/subsys/strcompat
# config:	/etc/sysconfig/strcompat
# probe:	true
# hide:		false
# license:	GPL
# description:	This STREAMS init script is part of Linux Fast-STREAMS.  \
#		It is responsible for ensuring that the necessary STREAMS \
#		character devices are present in the /dev directory and \
#		that the STREAMS subsystem is configured and loaded.  It \
#		is also responsible for starting the STREAMS log and trace \
#		facilities.
#
# LSB init script conventions
#
### BEGIN INIT INFO
# Provides: strcompat
# Required-Start: streams
# Required-Stop: streams
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# X-UnitedLinux-Default-Enabled: yes
# Short-Description: start and stop strcompat subsystem
# License: GPL
# Description:	This STREAMS init script is part of Linux Fast-STREAMS.  It is
#	reponsible for ensuring that the necessary STREAMS character devices are
#	present in the /dev directory and that the compatibility subsystem is
#	configured and loaded.
### END INIT INFO

# Source init script functions library.
init_mode="standalone"
  if [ -r /etc/init.d/functions   ] ; then . /etc/init.d/functions   ; init_mode="chkconfig" ;
elif [ -r /etc/rc.status          ] ; then . /etc/rc.status          ; init_mode="insserv"   ;
elif [ -r /lib/lsb/init-functions ] ; then . /lib/lsb/init-functions ; init_mode="lsb"       ;
fi

case "$init_mode" in
    (chkconfig)
	;;
    (insserv)
	action() {
	    echo -en "$1"
	    shift 1
	    ${1+"$@"} >/dev/null
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] || rc_failed $RETVAL
	    rc_status -v
	    return $RETVAL
	}
	;;
    (lsb)
	action() {
	    echo -en "$1"
	    shift 1
	    ${1+"$@"} >/dev/null
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && log_success_msg || log_failure_msg
	    return $?
	}
	;;
    (standalone|*)
	action() {
	    echo -en "$1"
	    shift 1
	    ${1+"$@"} >/dev/null
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] && echo -e "\t...SUCCESS" || echo -e "\t....FAILED"
	    return $?
	}
	;;
esac

name='strcompat'
lockfile="/var/lock/subsys/$name"
config="/etc/sysconfig/$name"
mknod="${name}_mknod"

if [ ! -e /proc/modules ] ; then if [ "$1" = "stop" ] ; then exit 0 ; else exit 5 ; fi ; fi

if test -z "$STRCOMPAT_MKNOD" ; then
    for STRCOMPAT_MKNOD in \
	./${mknod} /sbin/${mknod} /usr/sbin/${mknod} /bin/${mknod} /usr/bin/${mknod}; do
	if [ -x $STRCOMPAT_MKNOD ] ; then
	    break
	else
	    STRCOMPAT_MKNOD=
	fi
    done
fi

# Specify defaults

[ -n "$STRCOMPAT_PRELOAD"       ] || STRCOMPAT_PRELOAD=""
[ -n "$STRCOMPAT_DRIVERS"       ] || STRCOMPAT_DRIVERS=""
[ -n "$STRCOMPAT_MODULES"       ] || STRCOMPAT_MODULES="streams-aixcompat streams-hpuxcompat streams-irixcompat streams-liscompat streams-maccompat streams-mpscompat streams-os7compat streams-osfcompat streams-suncompat streams-svr3compat streams-svr4compat streams-uw7compat"
[ -n "$STRCOMPAT_MAKEDEVICES"   ] || STRCOMPAT_MAKEDEVICES="yes"
[ -n "$STRCOMPAT_REMOVEDEVICES" ] || STRCOMPAT_REMOVEDEVICES="yes"

# Source redhat and/or debian config file
for file in $config ; do
    [ -f $file ] && . $file
done

[ -z "$STRCOMPAT_MKNOD" ] && STRCOMPAT_MAKEDEVICES="no"
[ -z "$STRCOMPAT_MKNOD" ] && STRCOMPAT_REMOVEDEVICES="no"

RETVAL=0

umask 077

function modprobe_action() {
	module=$1
	shift
	modname=$module
	case $module in
	(streams-aixcompat)
	    modname=$"AIX(R) 5L Version 5.1 Portable STREAMS Environment"
	    ;;
	(streams-hpuxcompat)
	    modname=$"HP-UX(R) 11.0i v2 STREAMS/UX"
	    ;;
	(streams-irixcompat)
	    modname=$"IRIX(R) 6.5.17"
	    ;;
	(streams-liscompat)
	    modname=$"Linux(R) STREAMS 2.18.4"
	    ;;
	(streams-maccompat)
	    modname=$"Mac(R) OS 9 Open Transport"
	    ;;
	(streams-mpscompat)
	    modname=$"MPS(R) Mentat Portable Streams"
	    ;;
	(streams-osfcompat)
	    modname=$"Digital(R) UNIX (OSF/1.2)"
	    ;;
	(streams-suncompat)
	    modname=$"Solaris(R) 9/SunOS(R) 5.9"
	    ;;
	(streams-svr3compat)
	    modname=$"UNIX(R) System V Release 3.2"
	    ;;
	(streams-svr4compat)
	    modname=$"UNIX(R) System V Release 4.2"
	    ;;
	(streams-uw7compat)
	    modname=$"UnixWare(R) 7.1.3"
	    ;;
	esac
	action $"Loading kernel module $modname:" \
	    modprobe -k -q -- $module
}

start() {
    modules=
    for module in $STRCOMPAT_PRELOAD ; do
	modules="${modules:+$modules }$module"
    done
    for module in $modules ; do
	modrex=`echo $module | sed -e 's,[-_],[-_],g'`
	if ! grep "^$modrex\>" /proc/modules >/dev/null 2>&1 ; then
	    modprobe_action \
		$module
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] || return $RETVAL
	fi
    done
    if grep '^[[:space:]]*streams[/.]' /etc/sysctl.conf >/dev/null 2>&1 ; then
	action $"Reconfiguring kernel parameters: " \
	    sysctl -e -p /etc/sysctl.conf || :
    fi
    if [ -f /etc/${name}.conf ] ; then
	action $"Configuring STREAMS parameters: " \
	    sysctl -e -p /etc/${name}.conf || :
    fi
    if [ -n "$STRCOMPAT_MKNOD" -a ":$STRCOMPAT_MAKEDEVICES" = ":yes" ] ; then
	action $"Making STREAMS devices: " \
	    $STRCOMPAT_MKNOD
	RETVAL=$?
    fi
    [ $RETVAL -eq 0 ] && touch $lockfile
    RETVAL=$?
    return $RETVAL
}

stop() {
    if [ -n "$STRCOMPAT_MKNOD" -a ":$STRCOMPAT_REMOVEDEVICES" = ":yes" ] ; then
	action $"Removing STREAMS devices: " \
	    $STRCOMPAT_MKNOD --remove
	RETVAL=$?
    fi
    modules=
    for module in $STRCOMPAT_PRELOAD $STRCOMPAT_DRIVERS $STRCOMPAT_MODULES ; do
	modules="${module}${modules:+ $modules}"
    done
    for module in $modules ; do
	modrex=`echo $module | sed -e 's,[-_],[-_],g'`
	if grep "^$modrex\>" /proc/modules >/dev/null 2>&1 ; then
	    action $"Unloading kernel module $module: " \
		modprobe -r -q -- $module
	    RETVAL=$?
	    [ $RETVAL -eq 0 ] || return $RETVAL
	fi
    done
    [ $RETVAL -eq 0 ] && rm -f -- $lockfile
    RETVAL=$?
    return $RETVAL
}

restart() {
    stop
    start
    return $?
}

reload() {
    stop
    start
    return $?
}

case "$1" in
    (start|stop|reload|restart)
	$1 || RETVAL=$?
	;;
    (status)
	LOADED='yes'
	for module in $STRCOMPAT_PRELOAD $STRCOMPAT_DRIVERS $STRCOMPAT_MODULES ; do
	    if ! grep "^$module"'[[:space:]]' /proc/modules >/dev/null 2>&1 ; then
		LOADED='no'
		break
	    fi
	done
	if [ ":$LOADED" = ":yes" ] ; then
	    if true ; then
		echo $"$name is running..."
		RETVAL=0
	    fi
	else
	    if [ -f $lockfile ] ; then
		echo $"$name is stopped but sybsys locked"
		RETVAL=2
	    else
		echo $"$name is stopped"
		RETVAL=3
	    fi
	fi
	;;
    (force-reload|try-restart|condrestart)
	[ -f $lockfile ] && restart || RETVAL=$?
	;;
    (probe)
	LOADED='yes'
	for module in $STRCOMPAT_PRELOAD $STRCOMPAT_DRIVERS $STRCOMPAT_MODULES ; do
	    if ! grep "^$module"'[[:space:]]' /proc/modules >/dev/null 2>&1 ; then
		LOADED='no'
		break
	    fi
	done
	if [ ":$LOADED" = ":yes" ] ; then
	    # loaded
	    if true ; then
		if [ ! -f $lockfile ] ; then
		    # loaded, but subsystem unlocked, need to reload
		    echo 'reload'
		else
		    # loaded and subsystem locked
		    for file in $config /etc/$name.conf ; do
			if [ -f $file -a $file -nt $lockfile ] ; then
			    # configuration file updated, need to reload
			    echo 'reload'
			    break
			fi
		    done
		fi
	    else
		# loaded, but with wrong options, need to restart
		echo 'restart'
	    fi
	else
	    # unloaded
	    if [ ! -f $lockfile ] ; then
		# subsystem unlocked, need to start
		echo 'start'
	    else
		if true ; then
		    # unloaded but subsystem locked, need to restart
		    echo 'restart'
		fi
	    fi
	fi
	# do not need to do anything
	RETVAL=$?
	;;
    (*)
	echo "Usage: $0 (start|stop|status|restart|try-restart|condrestart|force-reload|reload|probe)"
	;;
esac

[ "${0##*/}" = "$name" ] && exit $RETVAL

# =============================================================================
# 
# @(#) $RCSfile: strcompat,v $ $Name:  $($Revision: 0.9.2.11 $) $Date: 2007/08/13 23:51:40 $
#
# -----------------------------------------------------------------------------
#
# Copyright (c) 2001-2007  OpenSS7 Corporation <http://www.openss7.com/>
# Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
#
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3 of the License.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>, or write to the
# Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
#
# -----------------------------------------------------------------------------
#
# U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
# behalf of the U.S. Government ("Government"), the following provisions apply
# to you.  If the Software is supplied by the Department of Defense ("DoD"), it
# is classified as "Commercial Computer Software" under paragraph 252.227-7014
# of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
# successor regulations) and the Government is acquiring only the license rights
# granted herein (the license rights customarily provided to non-Government
# users).  If the Software is supplied to any unit or agency of the Government
# other than DoD, it is classified as "Restricted Computer Software" and the
# Government's rights in the Software are defined in paragraph 52.227-19 of the
# Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
# the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
# (or any successor regulations).
#
# -----------------------------------------------------------------------------
#
# Commercial licensing and support of this software is available from OpenSS7
# Corporation at a fee.  See http://www.openss7.com/
#
# -----------------------------------------------------------------------------
#
# Last Modified $Date: 2007/08/13 23:51:40 $ by $Author: brian $
#
# -----------------------------------------------------------------------------
#
# $Log: strcompat,v $
# Revision 0.9.2.11  2007/08/13 23:51:40  brian
# - updated to GPLv3 headers
#
# =============================================================================
# vim: ft=sh sw=4 tw=80
