'\" rt
.\" -*- nroff -*- vim: ft=nroff noautoindent nocindent nosmartindent
.\"
.\" @(#) $Id: CD_WRITE_READ_REQ.7.man,v 0.9.2.2 2004/05/12 10:14:56 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (C) 2001-2004  OpenSS7 Corporation <www.openss7.com>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" =========================================================================
.\"
.\" Modified $Date: 2004/05/12 10:14:56 $ by $Author: brian $
.\"
.\" =========================================================================
.so openss7.macros
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database openss7.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.\"
.\"
.TH CD_WRITE_READ_REQ 7 "$Date: 2004/05/12 10:14:56 $" "$Name:  $" "Communications Device Interface (CDI)"
.SH NAME
.B CD_WRITE_READ_REQ
\- write/read request
.SH SYNOPSIS
This primitive consists of one
.B M_PROTO
message block followed by one or more
.B M_DATA
message blocks.
The
.B M_PROTO
message block is structured as follows:
.sp
.nf
\fC\s-1\
.\"/*
.\" * CD_WRITE_READ_REQ, M_PROTO type
.\" */
typedef struct {
    cd_ulong cd_primitive;
    cd_unitdata_req_t cd_unitdata_req;
    cd_read_req_t cd_read_req;
} cd_write_read_req_t;
\fR\s+1
.fi
.SH DESCRIPTION
This user originated primitive requests that the provided data be transmitted
and that the output section be disabled and the intput section enabled
immediately following the transmission.
.SS Parameters
This primitive contains the following parameters:
.TP
.I cd_primitive
Specifies the primitives type.
.TP
.I cd_unitdata_req
Specifies a
.BR CD_UNITDATA_REQ (7)
primitive.  See
.BR cd_unitdata_req_t (7)
for formatting of this parameter.
.TP
.I cd_read_req
Specifies a
.BR CD_READ_REQ (7)
primitive.  See
.BR cd_read_req_t (7)
for formatting of this parameter.
.SS State
This primitive is valid in any state where the
.BR CD_UNITDATA_REQ (7)
primitive and
.BR CD_ALLOW_INPUT_REQ (7)
primitives are permitted.
.SH RESPONSE
This primitive requires the same repsonse from the CD provider as if a
.BR CD_UNITDATA_REQ (7)
primitive immediately followed by a
.BR CD_READ_REQ (7)
primitive were to be issued.
.PP
.B Unsuccessful (non-fatal errors):
When unsuccessful, this primitive requires an error acknowledgement using the
.BR CD_ERROR_ACK (7)
primitive with the error indicated.
.SH ERRORS
.PP
.B "Non-Fatal Errors:"
appropriate non-fatal errors are as follows:
.TP
.RB [ CD_BADADDRESS ]
Address was invalid.
.TP
.RB [ CD_BADADDRTYPE ]
Invalid address type.
.\".TP
.\".RB [ CD_BADDIAL ]
.\"Dial information was invalid.
.\".TP
.\".RB [ CD_BADDIALTYPE ]
.\"Invalid dial information type.
.\".TP
.\".RB [ CD_BADDISPOSAL ]
.\"Invalid disposal parameter.
.\".TP
.\".RB [ CD_BADFRAME ]
.\"Defective SDU received.
.\".TP
.\".RB [ CD_BADPPA ]
.\"Invalid PPA identifier.
.TP
.RB [ CD_BADPRIM ]
Unrecognized primitive.
.TP
.RB [ CD_DISC ]
Disconnected.
.TP
.RB [ CD_EVENT ]
Protocol-specific event occurred.
.TP
.RB [ CD_FATALERR ]
Device has become unusable.
.\".TP
.\".RB [ CD_INITFAILED ]
.\"Line initialization failed.
.TP
.RB [ CD_NOTSUPP ]
Primitive not supported by this device.
.TP
.RB [ CD_OUTSTATE ]
Primitive was issued from an invalid state.
.TP
.RB [ CD_PROTOSHORT ]
M_PROTO block too short.
.TP
.RB [ CD_READTIMEOUT ]
Read request timed out before data arrived.
.TP
.RB [ CD_SYSERR ]
UNIX system error.
.TP
.RB [ CD_WRITEFAIL ]
Unitdata request failed.
.SH FILES
<sys/cdi.h>
.SH "SEE ALSO"
.BR CD_READ_REQ (7),
.BR CD_UNITDATA_REQ (7).
.SH HISTORY
.PP
The Communications Device Interface first appeared in SVR 4.
.[
svr4
.]
.SH CONFORMANCE
.PP
This interface conforms to CDI with Gcom extensions.
.XX
.[
magic
.]
.[
advprog
.]
.[
$LIST$
.]
.TI
