'\" rtp
.\" -*- nroff -*- vim: ft=nroff nocin nosi
.\"
.\" @(#) $Id: T_INFO_ACK.7.man,v 0.9.2.5 2006/04/05 09:43:19 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (c) 2001-2006  OpenSS7 Corporation <http://www.openss7.com/>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.  The author(s) will take no responsibility in it.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" -------------------------------------------------------------------------
.\"
.\" U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
.\" on behalf of the U.S. Government ("Government"), the following
.\" provisions apply to you.  If the Software is supplied by the Department
.\" of Defense ("DoD"), it is classified as "Commercial Computer Software"
.\" under paragraph 252.227-7014 of the DoD Supplement to the Federal
.\" Acquisition Regulations ("DFARS") (or any successor regulations) and the
.\" Government is acquiring only the license rights granted herein (the
.\" license rights customarily provided to non-Government users).  If the
.\" Software is supplied to any unit or agency of the Government other than
.\" DoD, it is classified as "Restricted Computer Software" and the
.\" Government's rights in the Software are defined in paragraph 52.227-19
.\" of the Federal Acquisition Regulations ("FAR") (or any successor
.\" regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
.\" NASA Supplement to the FAR (or any successor regulations).
.\"
.\" =========================================================================
.\" 
.\" Commercial licensing and support of this software is available from
.\" OpenSS7 Corporation at a fee.  See http://www.openss7.com/
.\" 
.\" =========================================================================
.\"
.\" Last Modified $Date: 2006/04/05 09:43:19 $ by $Author: brian $
.\"
.\" -------------------------------------------------------------------------
.\"
.\" $Log: T_INFO_ACK.7.man,v $
.\" Revision 0.9.2.5  2006/04/05 09:43:19  brian
.\" - moved .so line and updated headers
.\"
.\" =========================================================================
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database strss7.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.so strss7.macros
.\"
.\"
.TH T_INFO_ACK 7 "@PACKAGE_DATE@" "@PACKAGE@-@VERSION@" "Transport Provider Interface (TPI)"
.SH NAME
.B T_INFO_ACK
\- Protocol Information Acknowledgment
.SH SYNOPSIS
This message consists of a
.B M_PCPROTO
message block formatted as follows:
.sp
.nf
\fC\s-1\
struct T_info_ack {
    t_scalar_t   PRIM_type;      /* Always T_INFO_ACK    */
    t_scalar_t   TSDU_size;      /* Max TSDU size        */
    t_scalar_t   ETSDU_size;     /* Max ETSDU size       */
    t_scalar_t   CDATA_size;     /* Connect data size    */
    t_scalar_t   DDATA_size;     /* Disconnect data size */
    t_scalar_t   ADDR_size;      /* TSAP size            */
    t_scalar_t   OPT_size;       /* Options size         */
    t_scalar_t   TIDU_size;      /* TIDU size            */
    t_scalar_t   SERV_type;      /* Service type         */
    t_scalar_t   CURRENT_state;  /* Current state        */
    t_scalar_t   PROVIDER_flag;  /* Provider flag        */
};
\fR\s+1
.fi
.SH DESCRIPTION
This primitive indicates to the transport user any relevant
protocol-dependent parameters.  It should be initiated in response to the
.BR T_INFO_REQ (7)
primitive described above.  The format of this message is one
.B M_PCPROTO
message block.
.SH PARAMETERS
The fields of this message have the following meanings:
.TP 16
.I PRIM_type
This indicates the primitive type.
.TP
.I TSDU_size
A value greater than zero specifies the maximum size of a transport
service data unit (TSDU); a value of zero specifies that the transport
provider does not support the concept of TSDU, although it does support
the sending of a data stream with no logical boundaries preserved across a
connection; a value of -1 specifies that there is no limit on the size of a
TSDU; and a value of -2 specifies that the transfer of normal data is not
supported by the transport provider.
.TP
.I ETSDU_size
A value greater than zero specifies the maximum size of an expedited
transport service data unit (ETSDU); a value of zero specifies that the
transport provider does not support the concept of ETSDU, although it
does support the sending of an expedited data stream with no logical
boundaries preserved across a connection; a value of -1 specifies that there
is no limit on the size of an ETSDU; and a value of -2 specifies that the
transfer of expedited data is not supported by the transport provider.
.TP
.I CDATA_size
A value greater than or equal to zero specifies the maximum amount of
data that may be associated with connection establishment primitives;
and a value of -2 specifies that the transport provider does not allow
data to be sent with connection establishment primitives.
.TP
.I DDATA_size
A value greater than or equal to zero specifies the maximum amount of
data that may be associated with the disconnect primitives; and a value
of -2 specifies that the transport provider does not allow data to be
sent with the disconnect primitives.
.TP
.I ADDR_size
A value greater than or equal to zero indicates the maximum size of a
transport protocol address; and a value of -2 specifies that the
transport provider does not provide user access to transport protocol
addresses.
.TP
.I OPT_size
A value greater than or equal to zero indicates the maximum number of
bytes of protocol-specific options supported by the provider; and a value
of -2 specifies that the transport provider does not support user-settable
options.
.TP
.I TIDU_size
This is the amount of user data that may be present in a single
.BR T_DATA_REQ "(7) or " T_EXDATA_REQ (7)
primitive.  This is the size of the transport protocol interface
data unit, and should not exceed the tunable system limit, if non-zero,
for the size of a STREAMS message.
.TP
.I SERV_type
This field specifies the service type supported by the transport
provider, and is one of the following:
.RS
.TP
.B T_COTS
The provider service is connection oriented with no orderly release support.
.TP
.B T_COTS_ORD
The provider service is connection oriented with orderly release support.
.TP
.B T_CLTS
The provider service is a connectionless transport service.
.RE
.TP
.I CURRENT_state
This is the current state of the transport provider.
.TP
.I PROVIDER_flag
This field specifies additional properties specific to the transport
provider and may alter the way the transport user communicates.  The
following flags may be set by the provider:
.RS
.TP
.B SENDZERO
This flag indicates that the transport provider supports the sending of
zero-length TSDUs.
.TP
.B XPG4_1
This flag indicates that the transport provider supports XPG4 semantics.
.RE
.SH RULES
The following rules apply when the type of service is
.BR T_CLTS :
.IP - 3
The ETSDU_size, CDATA_size and DDATA_size fields should be -2.
.IP -
The TSDU_size should equal the TIDU_size.
.SH MODES
Both connection-mode and connectionless-mode.
.SH ORIGINATOR
Transport provider.
.SH "SEE ALSO"
.BR T_INFO_REQ (7),
.BR T_ADDR_REQ (7),
.BR T_ADDR_ACK (7),
.BR T_CAPABILITY_REQ (7),
.BR T_CAPABILITY_ACK (7).
.SH HISTORY
.PP
The Transport Provider Interface first appeared in SVR 4.
.[
svr4
.]
.SH CONFORMANCE
.PP
This interface conforms to TPI Version 2, Draft 2.
.[
TPI Revision 2.0.0
.]
.XX
.[
magic
.]
.[
advprog
.]
.[
$LIST$
.]
.T2
