'\" rt
.\" -*- nroff -*- vim: ft=groff noautoindent nocindent nosmartindent
.\"
.\" @(#) $Id: TC_BIND_REQ.7.man,v 0.9.2.2 2005/01/26 07:58:05 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (C) 2001-2005  OpenSS7 Corporation <www.openss7.com>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" =========================================================================
.\"
.\" Modified $Date: 2005/01/26 07:58:05 $ by $Author: brian $
.\"
.\" =========================================================================
.so strss7.macros
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database strss7.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.\"
.\"
.TH TC_BIND_REQ 7 "$Date: 2005/01/26 07:58:05 $" "$Name:  $" "Transaction Component Interface (TCI)"
.SH NAME
.PP
.B TC_BIND_REQ
\- Bind Protocol Address Request
.SH SYNOPSIS
.PP
These messages consist of one
.BR M_PROTO (9)
message block formatted as follows:
.sp
.nf
\fC\s-1\
typedef struct TC_bind_req {
    ulong PRIM_type;
    ulong ADDR_length;        /* address length */
    ulong ADDR_offset;        /* address offset */
    ulong XACT_number;        /* maximum outstanding transaction reqs. */
    ulong BIND_flags;         /* bind flags */
} TC_bind_req_t;
\fR\s+1
.fi
.SH DESCRIPTION
.PP
This primitive requests that the TC provider bind a protocol address to
the
.IR stream ,
negotiate the number of transaction dialogue begin indications allowed to be outstanding by the
TC provider for the specified protocol address, and activate the
.I stream
associated with the protocol address.
.IP - 3
Note that a
.I stream
is viewed as active when the TC provider may receive and transmit TPDUs (transaction
protocol data units) associated with the
.IR stream .
.SH PARAMETERS
.PP
The fields of this message have the following meanings:
.TP 16
.I PRIM_type
indicates the primitive type.
.TP
.I ADDR_length
is the length of the protocol address to be bound to the
.IR stream .
.TP
.I ADDR_offset
is the offset from the beginning of the
.BR M_PROTO (9)
block where the protocol address begins.
Note that all lengths, offsets, and sizes in all structures refer to the number of bytes.
.TP
.I XACT_number
is the requested number of transaction dialogue begin indications allowed to be outstanding
by the TC provider for the specified protocol address.

Note that the
.I XACT_number
should be ignored by those providing a connectionless (only) transaction service.
Also note that if the number of outstanding transaction dialogue begin indications equals
.IR XACT_number ,
the TC provider need not discard further incoming transaction dialogue begin
indications, but may choose to queue them internally until the number of outstanding transaction
dialogue begin indications drops below
.IR XACT_number .
.TP
.I BIND_flags
are the options flags associated with the bind.
.PP
The proper alignment of the address in the
.BR M_PROTO (9)
message block is not guaranteed.
The address in the
.BR M_PROTO (9)
message block is however, aligned the same as it was received from the TC user.
.SH RULES
.PP
For rules governing the requests made by these primitives, see the
.BR TC_BIND_ACK (7)
primitive.
.PP
These primitives require the TC provider to generate one of the following acknowledgments
on receipt of the primitive, and the TC user must wait for the acknowledgment before
issuing any other primitives:
.TP
.B Successful
Correct acknowledgment of the primitive is indicated via the
.BR TC_BIND_ACK (7)
primitive.
.TP
.B Non-fatal errors
These errors will be indicated via the
.BR TC_ERROR_ACK (7)
primitive.
.SH ERRORS
.PP
The allowable errors are as follows:
.TP
.RB [ TCACCES ]
This indicates that the TC user did not have proper permissions for the use of the requested address.
.TP
.RB [ TCADDRBUSY ]
This indicates that the requested address is in use.
.TP
.RB [ TCBADADDR ]
This indicates that the protocol address was in an incorrect format or the address contained invalid
information.
It is not intended to indicate protocol errors.
.TP
.RB [ TCNOADDR ]
This indicates that the TC provider could not allocate an address.
.TP
.RB [ TCOUTSTATE ]
The primitive would place the transaction interface out of state.
.TP
.RB [ TCSYSERR ]
A system error has occurred and the Linux system error is indicated in the primitive.
.SH MODES
.PP
Both connection-mode and connectionless-mode.
.SH ORIGINATOR
.PP
TC user.
.SH FILES
.TP
.B <ss7/tc.h>
\- the transaction component interface header file.
.SH "SEE ALSO"
.PP
.BR tci (7),
.BR TC_BIND_ACK (7),
.BR TC_ERROR_ACK (7).
.SH HISTORY
.PP
The Transaction Component Interface first appeared in OpenSS7.
.SH CONFORMANCE
.PP
This interface conforms to TCI Revision 0.9.2, Draft 1.
.[
tci
.]
.[
$LIST$
.]
.TA

