'\" rt
.\" -*- nroff -*- vim: ft=nroff noautoindent nocindent nosmartindent
.\"
.\" @(#) $Id: TR_ADDR_REQ.7.man,v 0.9.2.2 2004/10/25 09:16:18 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (C) 2001-2004  OpenSS7 Corporation <www.openss7.com>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" =========================================================================
.\"
.\" Modified $Date: 2004/10/25 09:16:18 $ by $Author: brian $
.\"
.\" =========================================================================
.so openss7.macros
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database openss7.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.\"
.\"
.TH TR_ADDR_REQ 7 "$Date: 2004/10/25 09:16:18 $" "$Name:  $" "Transaction Interface (TRI)"
.SH NAME
.PP
.B TR_ADDR_REQ
\- Get Protocol Address Request
.SH SYNOPSIS
.PP
This message consists of a
.BR M_PCPROTO (9)
message block formatted as follows:
.sp
.nf
\fC\s-1\
typedef struct TR_addr_req {
    ulong PRIM_type;          /* Always TR_ADDR_REQ */
    ulong TRANS_id;           /* Transaction id */
} TR_addr_req_t;
\fR\s+1
.fi
.SH DESCRIPTION
.PP
This primitive requests the transaction provider to return the local and
remote protocol addresses currently associated with the transaction
endpoint.
.SH PARAMETERS
.PP
.PP
The fields of this message have the following meanings:
.TP 16
.I PRIM_type
specifies the primitive type.  Always
.BR TR_ADDR_REQ .
.TP
.I TRANS_id
specifies the transaction association identifier for which address service is requested.  If address
service is requested for local bind address, then the transaction identifier must be -1.
.PP
Note that the
.BR TR_ADDR_REQ
and
.BR TR_ADDR_ACK (7)
primitives have no effect on the
state of the transaction provider and do not appear in the state tables. 
.SH RULES
.PP
This primitive requires the transaction provider to generate one of the
following acknowledgments on receipt of the primitive and that the transaction
user wait for the acknowledgment before issuing any other primitives:
.TP
.B Successful
Acknowledgment of the primitive via
.BR TR_ADDR_ACK (7).
.TP
.B Non-fatal errors
These errors will be indicated via
.BR TR_ERROR_ACK (7).
.SH MODES
.PP
Both connection-mode and connectionless-mode.
.SH ORIGINATOR
.PP
Transaction user.
.SH "FILES"
.PP
<ss7/tr.h>
.SH "SEE ALSO"
.PP
.BR tri (7),
.BR M_PCPROTO (9),
.BR TR_ADDR_ACK (7),
.BR TR_ERROR_ACK (7).
.SH HISTORY
.PP
The Transaction Interface first appeared in OpenSS7.
.SH CONFORMANCE
.PP
This interface conforms to TRI Revision 0.9.2, Draft 1.
.[
tri
.]
.[
$LIST$
.]
.TA
