/*****************************************************************************

 @(#) $Id: cdr2MIB.h,v 0.9.2.2 2008-12-24 13:08:22 brian Exp $

 -----------------------------------------------------------------------------

 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; version 3 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 -----------------------------------------------------------------------------

 Last Modified $Date: 2008-12-24 13:08:22 $ by $Author: brian $

 -----------------------------------------------------------------------------

 $Log: cdr2MIB.h,v $
 Revision 0.9.2.2  2008-12-24 13:08:22  brian
 - building ss7confd

 *****************************************************************************/

#ifndef __LOCAL_CDR2MIB_H__
#define __LOCAL_CDR2MIB_H__

#ident "@(#) $RCSfile: cdr2MIB.h,v $ $Name:  $($Revision: 0.9.2.2 $) Copyright (c) 2001-2008 OpenSS7 Corporation."

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */
/* our storage structure(s) */
struct cdr2MIB_data {
	uint cdr2MIB_request;

};
struct callDetailDataTable_data {
	uint callDetailDataTable_request;
	char *callDetailDataId;
	size_t callDetailDataIdLen;
};
struct simpleUsageMeteringControlTable_data {
	uint simpleUsageMeteringControlTable_request;
	char *controlObjectId;
	size_t controlObjectIdLen;
	char *creationTriggerList;
	size_t creationTriggerListLen;
	long simpleUsageMeteringControlEntryStatus;
};
struct configurableSimpleUsageMeteringControlTable_data {
	uint configurableSimpleUsageMeteringControlTable_request;
	char *controlObjectId;
	size_t controlObjectIdLen;
	long samplingRate;
	char *configurationMask;
	size_t configurationMaskLen;
	long configurationRowStatus;
};
struct blockGeneratingLogTable_data {
	uint blockGeneratingLogTable_request;
	char *logId;
	size_t logIdLen;
	long blockGeneratingLogMaxBlockSize;
	long blockGeneratingLogMaxTimeInterval;
	long blockGeneratingLogStorageType;
	long blockGeneratingLogRowStatus;
};
struct fileGeneratingLogTable_data {
	uint fileGeneratingLogTable_request;
	char *logId;
	size_t logIdLen;
	char *timesOfDay;
	size_t timesOfDayLen;
	long periodicTrigger;
	long fileGeneratingLogStorageType;
	long fileGeneratingLogEntryStatus;
};
struct callDetailLogRecordTable_data {
	uint callDetailLogRecordTable_request;
	char *logId;
	size_t logIdLen;
	char *logRecordId;
	size_t logRecordIdLen;
	char *networkProviderId;
	size_t networkProviderIdLen;
	long recordType;
	char *seizureTime;
	size_t seizureTimeLen;
	char *answerTime;
	size_t answerTimeLen;
	char *partialTime;
	size_t partialTimeLen;
	char *eventTime;
	size_t eventTimeLen;
	char *callingPartyNumber;
	size_t callingPartyNumberLen;
	char *calledPartyNumber;
	size_t calledPartyNumberLen;
	char *redirectingNumber;
	size_t redirectingNumberLen;
	char *redirectionNumber;
	size_t redirectionNumberLen;
	char *originalCalledNumber;
	size_t originalCalledNumberLen;
	char *callingPartyNumberNotScreened;
	size_t callingPartyNumberNotScreenedLen;
	char *operatorSpecific1Number;
	size_t operatorSpecific1NumberLen;
	char *operatorSpecific2Number;
	size_t operatorSpecific2NumberLen;
	char *operatorSpecific3Number;
	size_t operatorSpecific3NumberLen;
	char *bearerService;
	size_t bearerServiceLen;
	long participantServiceUser;
	char *callIdentificationNumber;
	size_t callIdentificationNumberLen;
	char *supplementaryServices;
	size_t supplementaryServicesLen;
	long immediateNotificationForUsageMetering;
	char *cause;
	size_t causeLen;
	char *personalUserId;
	size_t personalUserIdLen;
	long chargedParticipant;
	char *chargedDirectoryNumber;
	size_t chargedDirectoryNumberLen;
	long percentageToBeBilled;
	char *accountCodeInput;
	size_t accountCodeInputLen;
	char *iNServiceCode;
	size_t iNServiceCodeLen;
	char *queueTimeStamp;
	size_t queueTimeStampLen;
	long queueDuration;
	char *serviceSpecificINInformation;
	size_t serviceSpecificINInformationLen;
	long partialRecordNumber;
	long partialRecordReason;
	char *exchangeInfo;
	size_t exchangeInfoLen;
	char *relatedCallNumber;
	size_t relatedCallNumberLen;
	char *cDRPurpose;
	size_t cDRPurposeLen;
	char *physicalLineCode;
	size_t physicalLineCodeLen;
	char *receivedDigits;
	size_t receivedDigitsLen;
	char *operatorSpecific1AdditionalNumber;
	size_t operatorSpecific1AdditionalNumberLen;
	char *operatorSpecific2AdditionalNumber;
	size_t operatorSpecific2AdditionalNumberLen;
	char *operatorSpecific3AdditionalNumber;
	size_t operatorSpecific3AdditionalNumberLen;
	char *callingPartyCategory;
	size_t callingPartyCategoryLen;
	long callingPartyType;
	char *chargeInformation;
	size_t chargeInformationLen;
	char *progress;
	size_t progressLen;
	char *accessDelivery;
	size_t accessDeliveryLen;
	char *trunkGroupOutgoing;
	size_t trunkGroupOutgoingLen;
	char *trunkGroupIncoming;
	size_t trunkGroupIncomingLen;
	char *fallbackBearerService;
	size_t fallbackBearerServiceLen;
	char *teleservice;
	size_t teleserviceLen;
	long conversationTime;
	long durationTimeACM;
	long durationTimeBAnswer;
	long durationTimeNoBAnswer;
	char *uUInfo;
	size_t uUInfoLen;
	char *standardExtensions;
	size_t standardExtensionsLen;
	char *recordExtensions;
	size_t recordExtensionsLen;
	char *bPartyCategory;
	size_t bPartyCategoryLen;
	long iSUPPreferred;
	long networkManagementControls;
	long glare;
	long recordId;
	long dataValidity;
	long callStatus;
	char *carrierId;
	size_t carrierIdLen;
	char *dPC;
	size_t dPCLen;
	char *oPC;
	size_t oPCLen;
};
struct configurableSimpleUsageMeteringControlR2Table_data {
	uint configurableSimpleUsageMeteringControlR2Table_request;
	char *controlObjectId;
	size_t controlObjectIdLen;
	char *configurationR2Mask;
	size_t configurationR2MaskLen;
	long configurationR2Status;
};
struct blockGeneratingLogR2Table_data {
	uint blockGeneratingLogR2Table_request;
	char *logId;
	size_t logIdLen;
	long blockGeneratingLogVersion;
};
struct callDetailLogRecordR2Table_data {
	uint callDetailLogRecordR2Table_request;
	char *logId;
	size_t logIdLen;
	char *logRecordId;
	size_t logRecordIdLen;
	struct counter64 sequenceId;
	struct counter64 zoneId;
	struct counter64 recSeqId;
	struct counter64 fileSeqId;
	char *callId;
	size_t callIdLen;
	char *lastUpdate;
	size_t lastUpdateLen;
	char *eventOrder;
	size_t eventOrderLen;
	long status;
	long callType;
	char *clngPtyNbr;
	size_t clngPtyNbrLen;
	char *chargeNbr;
	size_t chargeNbrLen;
	char *clldPtyNbr;
	size_t clldPtyNbrLen;
	long clldPtyNoa;
	char *origLnInfo;
	size_t origLnInfoLen;
	char *ingLrn;
	size_t ingLrnLen;
	char *ingCic;
	size_t ingCicLen;
	long ingCsi;
	ulong ingCceId;
	long ingTgProt;
	long ingTgType;
	ulong ingTgId;
	char *ingCallStart;
	size_t ingCallStartLen;
	ulong ingGateId;
	ulong ingCardId;
	ulong ingSpanId;
	ulong ingChanId;
	ulong ingIsdnDChan;
	ulong ingIsdnCrn;
	char *ingCreatConnCplt;
	size_t ingCreatConnCpltLen;
	char *ingAddrCplt;
	size_t ingAddrCpltLen;
	char *ingCallAns;
	size_t ingCallAnsLen;
	char *transNbr;
	size_t transNbrLen;
	char *termLrn;
	size_t termLrnLen;
	char *transCic;
	size_t transCicLen;
	char *ingCallRls;
	size_t ingCallRlsLen;
	ulong ingRlsCause;
	ulong egrCceId;
	long egrTgProt;
	long egrTgType;
	ulong egrTgId;
	char *egrCallStart;
	size_t egrCallStartLen;
	ulong egrGateId;
	ulong egrCardId;
	ulong egrSpanId;
	ulong egrChanId;
	ulong egrIsdnDChan;
	ulong egrIsdnCrn;
	char *egrCreatConnCplt;
	size_t egrCreatConnCpltLen;
	char *egrAddrCplt;
	size_t egrAddrCpltLen;
	char *egrCallAns;
	size_t egrCallAnsLen;
	char *egrCallRls;
	size_t egrCallRlsLen;
	ulong egrRlsCause;
	char *chkptFirst;
	size_t chkptFirstLen;
	char *chkptLast;
	size_t chkptLastLen;
	char *ingGateName;
	size_t ingGateNameLen;
	char *egrGateName;
	size_t egrGateNameLen;
	char *ingTgName;
	size_t ingTgNameLen;
	char *egrTgName;
	size_t egrTgNameLen;
	char *origGateIp;
	size_t origGateIpLen;
	char *termGateIp;
	size_t termGateIpLen;
	char *h323ConfId;
	size_t h323ConfIdLen;
	ulong ingCardPort;
	ulong ingCardPath;
	ulong egrCardPort;
	ulong egrCardPath;
	ulong ingTg;
	ulong egrTg;
	char *dialedNbr;
	size_t dialedNbrLen;
	long dialedNoa;
	char *redirNbr;
	size_t redirNbrLen;
	long redirNoa;
	long redirInd;
	long redirRsn;
	char *calledNbr;
	size_t calledNbrLen;
	long calledNoa;
	long redirRsnOrig;
	ulong redirCntr;
	long redirPrsntnInd;
	char *ingJuris;
	size_t ingJurisLen;
	char *egrJuris;
	size_t egrJurisLen;
	long ingTrunkBearCap;
	long egrTrunkBearCap;
	char *transNetSelCarr;
	size_t transNetSelCarrLen;
	ulong clngPtyNoa;
	char *ingRlsCauseIntrnl;
	size_t ingRlsCauseIntrnlLen;
	char *egrRlsCauseIntrnl;
	size_t egrRlsCauseIntrnlLen;
	char *egrClldNbr;
	size_t egrClldNbrLen;
	long egrClldNoa;
	char *egrCnndNbr;
	size_t egrCnndNbrLen;
	long egrCnndNoa;
	long clngPtyPrsntnInd;
	long ingIri;
	long egrOri;
	char *ingCallidExtrnl;
	size_t ingCallidExtrnlLen;
	char *egrCallidExtrnl;
	size_t egrCallidExtrnlLen;
	char *ingChargeInfo;
	size_t ingChargeInfoLen;
	char *egrChargeInfo;
	size_t egrChargeInfoLen;
	char *ingPrtlInd;
	size_t ingPrtlIndLen;
	long ingNatfwdCliblkInd;
	long ingNatfwdNtaInd;
	char *ingLastDvrtLnDigs;
	size_t ingLastDvrtLnDigsLen;
	long ingLastDvrtLnNoa;
	char *j7IngAddlPtyCat;
	size_t j7IngAddlPtyCatLen;
	char *j7IngChgAreaInfo;
	size_t j7IngChgAreaInfoLen;
	char *j7IngFwdCallInd;
	size_t j7IngFwdCallIndLen;
	char *j7EgrAddlPtyCat;
	size_t j7EgrAddlPtyCatLen;
	char *j7EgrChgAreaInfo;
	size_t j7EgrChgAreaInfoLen;
	char *j7EgrBkwCallInd;
	size_t j7EgrBkwCallIndLen;
	char *j7CarrInfoXfer;
	size_t j7CarrInfoXferLen;
	char *ingSs7GnrcParm;
	size_t ingSs7GnrcParmLen;
	char *egrSs7GnrcParm;
	size_t egrSs7GnrcParmLen;
	ulong ingPktsSent;
	ulong ingPktsRcvd;
	ulong ingPktsLost;
	ulong ingPktsXfer;
	ulong ingJitter;
	ulong ingLtncy;
	ulong egrPktsSent;
	ulong egrPktsRcvd;
	ulong egrPktsLost;
	ulong egrPktsXfer;
	ulong egrJitter;
	ulong egrLtncy;
	ulong ingCrctId;
	ulong egrCrctId;
	ulong ingCodec;
	ulong egrCodec;
	ulong ingLocGateId;
	ulong egrLocGateId;
	char *ingCasCrctSzr;
	size_t ingCasCrctSzrLen;
	char *egrCasCrctSzr;
	size_t egrCasCrctSzrLen;
	char *ingZz;
	size_t ingZzLen;
	char *egrZz;
	size_t egrZzLen;
	char *ingCtryAddrType;
	size_t ingCtryAddrTypeLen;
	char *egrCtryAddrType;
	size_t egrCtryAddrTypeLen;
	ulong ingPartition;
	ulong egrPartition;
	ulong ingClngPtyCat;
	ulong ingRlsCauseLctn;
	ulong egrRlsCauseLctn;
	ulong clldPtyCat;
	ulong callDuration;
	ulong ingRlsDrctn;
	ulong egrRlsDrctn;
	char *ingAnsLctim;
	size_t ingAnsLctimLen;
	char *egrAnsLctim;
	size_t egrAnsLctimLen;
	ulong ingHlcChrsId;
	ulong egrHlcChrsId;
	ulong ingLlcXferCap;
	ulong egrLlcXferCap;
	char *routeList;
	size_t routeListLen;
	ulong ingPointCode;
	ulong egrPointCode;
};

/* storage declarations */
extern struct cdr2MIB_data *cdr2MIBStorage;
extern struct header_complex_index *callDetailDataTableStorage;
extern struct header_complex_index *simpleUsageMeteringControlTableStorage;
extern struct header_complex_index *configurableSimpleUsageMeteringControlTableStorage;
extern struct header_complex_index *blockGeneratingLogTableStorage;
extern struct header_complex_index *fileGeneratingLogTableStorage;
extern struct header_complex_index *callDetailLogRecordTableStorage;
extern struct header_complex_index *configurableSimpleUsageMeteringControlR2TableStorage;
extern struct header_complex_index *blockGeneratingLogR2TableStorage;
extern struct header_complex_index *callDetailLogRecordR2TableStorage;

/* enum definitions from the covered mib sections */

#define CREATIONTRIGGERLIST_SEIZURE              0
#define CREATIONTRIGGERLIST_FIRSTDIGITRECEIVED   1
#define CREATIONTRIGGERLIST_ACMRECEIVED          2
#define CREATIONTRIGGERLIST_ANMRECEIVED          3
#define CREATIONTRIGGERLIST_SUPPLEMENTARYSERVICEINVOCATION 4
#define CREATIONTRIGGERLIST_SUPPLEMENTARYSERVICEINPUT 5

#define CONFIGURATIONMASK_EXCHANGEINFO           0
#define CONFIGURATIONMASK_RELATEDCALLNUMBER      1
#define CONFIGURATIONMASK_ADDITIONALPARTICIPANTINFO 2
#define CONFIGURATIONMASK_CALLINGPARTYCATEGORY   3
#define CONFIGURATIONMASK_CALLINGPARTYTYPE       4
#define CONFIGURATIONMASK_PROGRESS               5
#define CONFIGURATIONMASK_ACCESSDELIVERY         6
#define CONFIGURATIONMASK_TRUNKGROUPOUTGOING     7
#define CONFIGURATIONMASK_TRUNKGROUPINCOMING     8
#define CONFIGURATIONMASK_TELESERVICE            9
#define CONFIGURATIONMASK_STANDARDEXTENSIONS     10
#define CONFIGURATIONMASK_RECORDEXTENSIONS       11
#define CONFIGURATIONMASK_BPARTYCATEGORY         12
#define CONFIGURATIONMASK_ISUPPREFFERRED         13
#define CONFIGURATIONMASK_NETWORKMANAGEMENTCONTROLS 14
#define CONFIGURATIONMASK_GLARE                  15

#define RECORDTYPE_CALL                          0
#define RECORDTYPE_SUPPLSERVICEINPUTRECORD       1

#define PARTICIPANTSERVICEUSER_CALLINGPARTYNUMBER 0
#define PARTICIPANTSERVICEUSER_CALLEDPARTYNUMBER 1
#define PARTICIPANTSERVICEUSER_REDIRECTINGNUMBER 2
#define PARTICIPANTSERVICEUSER_REDIRECTIONNUMBER 3
#define PARTICIPANTSERVICEUSER_ORIGINALCALLEDNUMBER 4
#define PARTICIPANTSERVICEUSER_CALLINGPARTYNUMBERNOTSCREENED 5
#define PARTICIPANTSERVICEUSER_OPERATORSPECIFIC1NUMBER 6
#define PARTICIPANTSERVICEUSER_OPERATORSPECIFIC2NUMBER 7
#define PARTICIPANTSERVICEUSER_OPERATORSPECIFIC3NUMBER 8
#define PARTICIPANTSERVICEUSER_OPERATOR          9
#define PARTICIPANTSERVICEUSER_UNKNOWN           10

#define IMMEDIATENOTIFICATIONFORUSAGEMETERING_TRUE 1
#define IMMEDIATENOTIFICATIONFORUSAGEMETERING_FALSE 2

#define CHARGEDPARTICIPANT_CALLINGPARTYNUMBER    0
#define CHARGEDPARTICIPANT_CALLEDPARTYNUMBER     1
#define CHARGEDPARTICIPANT_REDIRECTINGNUMBER     2
#define CHARGEDPARTICIPANT_REDIRECTIONNUMBER     3
#define CHARGEDPARTICIPANT_ORIGINALCALLEDNUMBER  4
#define CHARGEDPARTICIPANT_CALLINGPARTYNUMBERNOTSCREENED 5
#define CHARGEDPARTICIPANT_OPERATORSPECIFIC1NUMBER 6
#define CHARGEDPARTICIPANT_OPERATORSPECIFIC2NUMBER 7
#define CHARGEDPARTICIPANT_OPERATORSPECIFIC3NUMBER 8
#define CHARGEDPARTICIPANT_OPERATOR              9
#define CHARGEDPARTICIPANT_UNKNOWN               10

#define PARTIALRECORDREASON_TIMELIMIT            0
#define PARTIALRECORDREASON_SERVICECHANGE        1
#define PARTIALRECORDREASON_OVERFLOW             2
#define PARTIALRECORDREASON_NETWORKINTERNALREASONS 3
#define PARTIALRECORDREASON_LASTCDR              4
#define PARTIALRECORDREASON_TIMECHANGE           5

#define CDRPURPOSE_USAGEMETERING                 0
#define CDRPURPOSE_ANALYSIS                      1

#define CALLINGPARTYTYPE_ANALOGUE                0
#define CALLINGPARTYTYPE_CUSTOMERLINK            1
#define CALLINGPARTYTYPE_BASICACCESS             2
#define CALLINGPARTYTYPE_PRIMARYRATEACCESS       3

#define ACCESSDELIVERY_SETUPMESSAGEGENERATED     0

#define ISUPPREFERRED_PREFERRED                  0
#define ISUPPREFERRED_NOTREQUIRED                1
#define ISUPPREFERRED_REQUIRED                   2
#define ISUPPREFERRED_NOTAPPLICABLE              3

#define NETWORKMANAGEMENTCONTROLS_ACC            0
#define NETWORKMANAGEMENTCONTROLS_ADC            1
#define NETWORKMANAGEMENTCONTROLS_CANCELFROM     2
#define NETWORKMANAGEMENTCONTROLS_CANCELREROUTED 3
#define NETWORKMANAGEMENTCONTROLS_CANCELTO       4
#define NETWORKMANAGEMENTCONTROLS_DESTINATIONCODECONTROL 5
#define NETWORKMANAGEMENTCONTROLS_SCR            6
#define NETWORKMANAGEMENTCONTROLS_SKIP           7
#define NETWORKMANAGEMENTCONTROLS_TARFROM        8
#define NETWORKMANAGEMENTCONTROLS_TARTO          9

#define GLARE_ABSENT                             0
#define GLARE_PRESENT                            1

#define DATAVALIDITY_POSSIBLEDUPLICATED          0
#define DATAVALIDITY_REQUIREDDATAMISSING         1
#define DATAVALIDITY_OTHER                       2

#define CALLSTATUS_ANSWERED                      0
#define CALLSTATUS_NOTANSWERED                   1

#define CONFIGURATIONR2MASK_NONE                 0

#define BLOCKGENERATINGLOGVERSION_VERSION1       1
#define BLOCKGENERATINGLOGVERSION_VERSION2       2

/* function prototypes */
void init_cdr2MIB(void);
void deinit_cdr2MIB(void);
int term_cdr2MIB(int majorID, int minorID, void *serverarg, void *clientarg);
FindVarMethod var_cdr2MIB;
void parse_cdr2MIB(const char *, char *);
SNMPCallback store_cdr2MIB;
void refresh_cdr2MIB(void);
FindVarMethod var_callDetailDataTable;
void parse_callDetailDataTable(const char *, char *);
SNMPCallback store_callDetailDataTable;
void refresh_callDetailDataTable(void);
FindVarMethod var_simpleUsageMeteringControlTable;
void parse_simpleUsageMeteringControlTable(const char *, char *);
SNMPCallback store_simpleUsageMeteringControlTable;
void refresh_simpleUsageMeteringControlTable(void);
FindVarMethod var_configurableSimpleUsageMeteringControlTable;
void parse_configurableSimpleUsageMeteringControlTable(const char *, char *);
SNMPCallback store_configurableSimpleUsageMeteringControlTable;
void refresh_configurableSimpleUsageMeteringControlTable(void);
FindVarMethod var_blockGeneratingLogTable;
void parse_blockGeneratingLogTable(const char *, char *);
SNMPCallback store_blockGeneratingLogTable;
void refresh_blockGeneratingLogTable(void);
FindVarMethod var_fileGeneratingLogTable;
void parse_fileGeneratingLogTable(const char *, char *);
SNMPCallback store_fileGeneratingLogTable;
void refresh_fileGeneratingLogTable(void);
FindVarMethod var_callDetailLogRecordTable;
void parse_callDetailLogRecordTable(const char *, char *);
SNMPCallback store_callDetailLogRecordTable;
void refresh_callDetailLogRecordTable(void);
FindVarMethod var_configurableSimpleUsageMeteringControlR2Table;
void parse_configurableSimpleUsageMeteringControlR2Table(const char *, char *);
SNMPCallback store_configurableSimpleUsageMeteringControlR2Table;
void refresh_configurableSimpleUsageMeteringControlR2Table(void);
FindVarMethod var_blockGeneratingLogR2Table;
void parse_blockGeneratingLogR2Table(const char *, char *);
SNMPCallback store_blockGeneratingLogR2Table;
void refresh_blockGeneratingLogR2Table(void);
FindVarMethod var_callDetailLogRecordR2Table;
void parse_callDetailLogRecordR2Table(const char *, char *);
SNMPCallback store_callDetailLogRecordR2Table;
void refresh_callDetailLogRecordR2Table(void);

WriteMethod write_creationTriggerList;
WriteMethod write_simpleUsageMeteringControlEntryStatus;
WriteMethod write_samplingRate;
WriteMethod write_configurationMask;
WriteMethod write_configurationRowStatus;
WriteMethod write_blockGeneratingLogMaxBlockSize;
WriteMethod write_blockGeneratingLogMaxTimeInterval;
WriteMethod write_blockGeneratingLogStorageType;
WriteMethod write_blockGeneratingLogRowStatus;
WriteMethod write_timesOfDay;
WriteMethod write_periodicTrigger;
WriteMethod write_fileGeneratingLogStorageType;
WriteMethod write_fileGeneratingLogEntryStatus;
WriteMethod write_configurationR2Mask;
WriteMethod write_configurationR2Status;
WriteMethod write_blockGeneratingLogVersion;

#endif				/* __LOCAL_CDR2MIB_H__ */
