/*****************************************************************************

 @(#) $Id: mtpMIB.h,v 0.9.2.4 2008-12-31 16:04:46 brian Exp $

 -----------------------------------------------------------------------------

 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; version 3 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 -----------------------------------------------------------------------------

 Last Modified $Date: 2008-12-31 16:04:46 $ by $Author: brian $

 -----------------------------------------------------------------------------

 $Log: mtpMIB.h,v $
 Revision 0.9.2.4  2008-12-31 16:04:46  brian
 - updated mibs

 Revision 0.9.2.3  2008-12-27 15:29:46  brian
 - split MTP and MTP OM mib

 Revision 0.9.2.2  2008-12-24 13:08:23  brian
 - building ss7confd

 *****************************************************************************/

#ifndef __LOCAL_MTPMIB_H__
#define __LOCAL_MTPMIB_H__

#ident "@(#) $RCSfile: mtpMIB.h,v $ $Name:  $($Revision: 0.9.2.4 $) Copyright (c) 2001-2008 OpenSS7 Corporation."

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */
/* our storage structure(s) */
struct mtpMIB_data {
	uint mtpMIB_request;
	int32_t mtpM2paDefaultSctpNoDelay;
	uint32_t mtpM2paDefaultSctpMaxseg;
	uint32_t mtpM2paDefaultSctpHeartbeatItvl;
	int32_t mtpM2paDefaultSctpHeartbeat;
	uint32_t mtpM2paDefaultSctpRtoInitial;
	uint32_t mtpM2paDefaultSctpRtoMin;
	uint32_t mtpM2paDefaultSctpRtoMax;
	uint32_t mtpM2paDefaultSctpPathMaxRetrans;
	uint32_t mtpM2paDefaultSctpCookieLife;
	uint32_t mtpM2paDefaultSctpCookieInc;
	uint32_t mtpM2paDefaultSctpMaxInitRetries;
	uint32_t mtpM2paDefaultSctpMaxBurst;
	uint32_t mtpM2paDefaultSctpAssocMaxRetrans;
	uint32_t mtpM2paDefaultSctpSackDelay;
	uint32_t mtpM2paDefaultSctpLifetime;
};
struct mtpSapTable_data {
	uint mtpSapTable_request;
	uint mtpSapTable_refs;
	uint32_t mtpSapId;
	uint32_t mtpSap2Address;
	int32_t mtpSapUserPart;
	int32_t mtpSapUserPartStatus;
	oid *mtpSapUserEntityNames;
	int mtpSapUserEntityNamesLen;
	oid *mtpSapProviderEntityNames;
	int mtpSapProviderEntityNamesLen;
	int32_t mtpSapUsageState;
	oid *mtpSapAsaProfilePointer;
	int mtpSapAsaProfilePointerLen;
	uint8_t *mtpSapName;
	int mtpSapNameLen;
	int32_t mtpSapLongMessageSupported;
	int32_t mtpSapRowStatus;
};
struct mtpMsTable_data {
	uint mtpMsTable_request;
	uint mtpMsTable_refs;
	uint32_t mtpMsId;
	uint8_t *mtpMsName;
	int mtpMsNameLen;
	uint8_t *mtpMsAlarmStatus;
	int mtpMsAlarmStatusLen;
	int32_t mtpMsOperationalState;
	int32_t mtpMsUsageState;
	uint8_t *mtpMsManagedElementType;
	int mtpMsManagedElementTypeLen;
	uint8_t *mtpMsModelCode;
	int mtpMsModelCodeLen;
	uint8_t *mtpMsVendorName;
	int mtpMsVendorNameLen;
	uint8_t *mtpMsUserLabel;
	int mtpMsUserLabelLen;
	uint8_t *mtpMsVersion;
	int mtpMsVersionLen;
	oid *mtpMsAsaProfilePointer;
	int mtpMsAsaProfilePointerLen;
	uint8_t *mtpMsNetworkElementAliases;
	int mtpMsNetworkElementAliasesLen;
	int32_t mtpMsStatus;
};
struct mtpNaTable_data {
	uint mtpNaTable_request;
	uint mtpNaTable_refs;
	int32_t mtpNaId;
	oid *mtpNaProtocolVariant;
	int mtpNaProtocolVariantLen;
	int32_t mtpNaProtocolYear;
	uint8_t *mtpNaProtocolOptions;
	int mtpNaProtocolOptionsLen;
	int32_t mtpNaNetworkIndicator;
	uint8_t *mtpNaPointCodeFormat;
	int mtpNaPointCodeFormatLen;
	int32_t mtpNaSlsLength;
	uint8_t *mtpNaSpDefault;
	int mtpNaSpDefaultLen;
	uint8_t *mtpNaName;
	int mtpNaNameLen;
	int32_t mtpNaRowStatus;
};
struct mtpGsTable_data {
	uint mtpGsTable_request;
	uint mtpGsTable_refs;
	uint32_t mtpSpId;
	uint32_t mtpGsId;
	int32_t mtpGsAdministrativeState;
	int32_t mtpGsTreatmentOfOutsideRanges;
	int32_t mtpGsListMode;
	int32_t mtpGsScreeningByLinkSetOrByOpc;
	int32_t mtpGsGetScreenedOpcsOrLinkSetsByDpc;
	uint8_t *mtpGsName;
	int mtpGsNameLen;
	int32_t mtpGsRowStatus;
};
struct mtpGsLineTable_data {
	uint mtpGsLineTable_request;
	uint mtpGsLineTable_refs;
	uint32_t mtpSpId;
	uint32_t mtpGsId;
	uint32_t mtpGsLineId;
	oid *mtpGsLineObject;
	int mtpGsLineObjectLen;
	uint32_t mtpGsLineContent;
	int32_t mtpGsLineRowStatus;
};
struct mtpGsLineContentTable_data {
	uint mtpGsLineContentTable_request;
	uint mtpGsLineContentTable_refs;
	uint32_t mtpSpId;
	uint32_t mtpGsId;
	uint32_t mtpGsLineId;
	uint32_t mtpGsLineContentId;
	uint8_t *mtpGsLineContentDesignatedDPCFirst;
	int mtpGsLineContentDesignatedDPCFirstLen;
	uint8_t *mtpGsLineContentDesignatedDPCLast;
	int mtpGsLineContentDesignatedDPCLastLen;
	uint8_t *mtpGsLineContentSiMask;
	int mtpGsLineContentSiMaskLen;
	int32_t mtpGsLineContentMessageTreatment;
	uint8_t *mtpGsLineContentComment;
	int mtpGsLineContentCommentLen;
	int32_t mtpGsLineContentRowStatus;
};
struct mtpSpProfileTable_data {
	uint mtpSpProfileTable_request;
	uint mtpSpProfileTable_refs;
	uint8_t *mtpSpProfileId;
	int mtpSpProfileIdLen;
	int32_t mtpSpProfileTimerT1R;
	int32_t mtpSpProfileTimerT2;
	int32_t mtpSpProfileTimerT4;
	int32_t mtpSpProfileTimerT5;
	int32_t mtpSpProfileTimerT7;
	int32_t mtpSpProfileTimerT11;
	int32_t mtpSpProfileTimerT12;
	int32_t mtpSpProfileTimerT13;
	int32_t mtpSpProfileTimerT14;
	int32_t mtpSpProfileTimerT15;
	int32_t mtpSpProfileTimerT16;
	int32_t mtpSpProfileTimerT18I;
	int32_t mtpSpProfileTimerT19I;
	int32_t mtpSpProfileTimerT20I;
	int32_t mtpSpProfileTimerT21I;
	int32_t mtpSpProfileTimerT22I;
	int32_t mtpSpProfileTimerT23I;
	int32_t mtpSpProfileTimerT20A;
	int32_t mtpSpProfileTimerT21A;
	int32_t mtpSpProfileTimerT22A;
	int32_t mtpSpProfileTimerT23A;
	int32_t mtpSpProfileTimerT24A;
	int32_t mtpSpProfileTimerT26A;
	int32_t mtpSpProfileTimerT27A;
	int32_t mtpSpProfileTimerT1T;
	int32_t mtpSpProfileTimerT2T;
	uint8_t *mtpSpProfileName;
	int mtpSpProfileNameLen;
	uint8_t *mtpSpRsDefault;
	int mtpSpRsDefaultLen;
	uint8_t *mtpSpLsDefault;
	int mtpSpLsDefaultLen;
	int32_t mtpSpProfileRowStatus;
};
struct mtpSpTable_data {
	uint mtpSpTable_request;
	uint mtpSpTable_refs;
	uint32_t mtpMsId;
	uint32_t mtpSpId;
	uint8_t *mtpSpPointCode;
	int mtpSpPointCodeLen;
	int32_t mtpSpType;
	int32_t mtpSpOperationalState;
	uint8_t *mtpSpProceduralStatus;
	int mtpSpProceduralStatusLen;
	uint8_t *mtpSpAvailabilityStatus;
	int mtpSpAvailabilityStatusLen;
	uint8_t *mtpSpVersion;
	int mtpSpVersionLen;
	int32_t mtpSpNetworkIndicator;
	uint8_t *mtpSpName;
	int mtpSpNameLen;
	int32_t mtpSpMtpT1;
	int32_t mtpSpMtpT2;
	int32_t mtpSpMtpT3;
	int32_t mtpSpMtpT4;
	int32_t mtpSpMtpT5;
	int32_t mtpSpMtpT6;
	int32_t mtpSpMtpT7;
	int32_t mtpSpMtpT8;
	int32_t mtpSpMtpT10;
	int32_t mtpSpMtpT11;
	int32_t mtpSpMtpT12;
	int32_t mtpSpMtpT13;
	int32_t mtpSpMtpT14;
	int32_t mtpSpMtpT15;
	int32_t mtpSpMtpT16;
	int32_t mtpSpMtpT17;
	int32_t mtpSpMtpT19A;
	int32_t mtpSpMtpT31A;
	int32_t mtpSpMtpT32A;
	int32_t mtpSpMtpT33A;
	int32_t mtpSpMtpT34A;
	int32_t mtpSpMtpT18I;
	int32_t mtpSpMtpT19I;
	int32_t mtpSpMtpT20I;
	int32_t mtpSpMtpT21I;
	int32_t mtpSpMtpT22I;
	int32_t mtpSpMtpT23I;
	int32_t mtpSpMtpT20A;
	int32_t mtpSpMtpT21A;
	int32_t mtpSpMtpT24I;
	int32_t mtpSpMtpT1T;
	int32_t mtpSpMtpT2T;
	int32_t mtpSpMtpT1S;
	uint8_t *mtpSpProfilePointer;
	int mtpSpProfilePointerLen;
	uint8_t *mtpSpNaPointer;
	int mtpSpNaPointerLen;
	uint8_t *mtpSpFlags;
	int mtpSpFlagsLen;
	uint8_t *mtpSpUsers;
	int mtpSpUsersLen;
	uint8_t *mtpSpAlarmStatus;
	int mtpSpAlarmStatusLen;
	int32_t mtpSpRowStatus;
};
struct mtpL3Table_data {
	uint mtpL3Table_request;
	uint mtpL3Table_refs;
	uint8_t *mtpL3Id;
	int mtpL3IdLen;
	int32_t mtpL3AdministrativeState;
	int32_t mtpL3OperationalState;
	int32_t mtpL3UsageState;
	uint8_t *mtpL3ProceduralStatus;
	int mtpL3ProceduralStatusLen;
	oid *mtpL3AsaProfilePointer;
	int mtpL3AsaProfilePointerLen;
	uint8_t *mtpL3Name;
	int mtpL3NameLen;
	int32_t mtpL3RowStatus;
};
struct mtpRsProfileTable_data {
	uint mtpRsProfileTable_request;
	uint mtpRsProfileTable_refs;
	uint8_t *mtpRsProfileId;
	int mtpRsProfileIdLen;
	uint8_t *mtpRsProfileName;
	int mtpRsProfileNameLen;
	int32_t mtpRsProfileTimerT8;
	int32_t mtpRsProfileTimerT11;
	int32_t mtpRsProfileTimerT15;
	int32_t mtpRsProfileTimerT16;
	int32_t mtpRsProfileTimerT18A;
	uint8_t *mtpRsProfileRtDefault;
	int mtpRsProfileRtDefaultLen;
	int32_t mtpRsProfileRowStatus;
};
struct mtpRsTable_data {
	uint mtpRsTable_request;
	uint mtpRsTable_refs;
	uint32_t mtpSpId;
	uint32_t mtpRsId;
	uint8_t *mtpRsDest;
	int mtpRsDestLen;
	uint8_t *mtpRsFlags;
	int mtpRsFlagsLen;
	int32_t mtpRsAdministrativeState;
	int32_t mtpRsOperationalState;
	oid *mtpRsAsaProfilePointer;
	int mtpRsAsaProfilePointerLen;
	int32_t mtpRsCongestedState;
	int32_t mtpRsCongestionLevel;
	uint8_t *mtpRsLoadsharingInformation;
	int mtpRsLoadsharingInformationLen;
	oid *mtpRsLoadsharingObject;
	int mtpRsLoadsharingObjectLen;
	uint8_t *mtpRsRemoteExchangeLabel;
	int mtpRsRemoteExchangeLabelLen;
	uint8_t *mtpRsName;
	int mtpRsNameLen;
	uint8_t *mtpRsProfile;
	int mtpRsProfileLen;
	uint8_t *mtpRsAlarmStatus;
	int mtpRsAlarmStatusLen;
	int32_t mtpRsRowStatus;
};
struct mtpRtProfileTable_data {
	uint mtpRtProfileTable_request;
	uint mtpRtProfileTable_refs;
	uint8_t *mtpRtProfileId;
	int mtpRtProfileIdLen;
	int32_t mtpRtProfileTimerT6;
	int32_t mtpRtProfileTimerT10;
	int32_t mtpRtProfileRowStatus;
};
struct mtpRtTable_data {
	uint mtpRtTable_request;
	uint mtpRtTable_refs;
	uint32_t mtpSpId;
	uint32_t mtpRsId;
	uint32_t mtpRtId;
	uint8_t *mtpRtLsPointer;
	int mtpRtLsPointerLen;
	int32_t mtpRtAdministrativeState;
	int32_t mtpRtOperationalState;
	uint8_t *mtpRtAvailabilityStatus;
	int mtpRtAvailabilityStatusLen;
	uint32_t mtpRtInClsLoadsharingAlgorithm;
	uint32_t mtpRtFixedPriority;
	uint32_t mtpRtFlexiblePriority;
	int32_t mtpRtPriorityMode;
	uint8_t *mtpRtLoadsharingInformation;
	int mtpRtLoadsharingInformationLen;
	oid *mtpRtLoadsharingObject;
	int mtpRtLoadsharingObjectLen;
	uint8_t *mtpRtName;
	int mtpRtNameLen;
	uint8_t *mtpRtSlsList;
	int mtpRtSlsListLen;
	int32_t mtpRtUsageState;
	uint32_t mtpRtRlSlot;
	uint8_t *mtpRtProfile;
	int mtpRtProfileLen;
	int32_t mtpRtRowStatus;
};
struct mtpRtLsaTable_data {
	uint mtpRtLsaTable_request;
	uint mtpRtLsaTable_refs;
	uint32_t mtpSpId;
	uint32_t mtpRsId;
	uint32_t mtpRtId;
	uint32_t mtpRtLsaSlsCode;
	uint32_t mtpRtLsaNormalSlCode;
	uint8_t *mtpRtLsaAlternativeSlCodeList;
	int mtpRtLsaAlternativeSlCodeListLen;
};
struct mtpLsProfileTable_data {
	uint mtpLsProfileTable_request;
	uint mtpLsProfileTable_refs;
	uint8_t *mtpLsProfileId;
	int mtpLsProfileIdLen;
	int32_t mtpLsProfileTimerT6;
	int32_t mtpLsProfileTimerT8;
	int32_t mtpLsProfileTimerT10;
	int32_t mtpLsProfileTimerT7;
	int32_t mtpLsProfileTimerT19I;
	int32_t mtpLsProfileTimerT21I;
	int32_t mtpLsProfileTimerT25A;
	int32_t mtpLsProfileTimerT28A;
	int32_t mtpLsProfileTimerT29A;
	int32_t mtpLsProfileTimerT30A;
	uint8_t *mtpLsProfileName;
	int mtpLsProfileNameLen;
	uint8_t *mtpLsProfileSlDefault;
	int mtpLsProfileSlDefaultLen;
	int32_t mtpLsProfileRowStatus;
};
struct mtpLsTable_data {
	uint mtpLsTable_request;
	uint mtpLsTable_refs;
	uint32_t mtpSpId;
	uint32_t mtpLsId;
	uint8_t *mtpLsAdjPc;
	int mtpLsAdjPcLen;
	uint8_t *mtpLsRsId;
	int mtpLsRsIdLen;
	uint32_t mtpLsMaxCapacity;
	uint32_t mtpLsCurrentCapacity;
	int32_t mtpLsCongestionControlMethod;
	int32_t mtpLsUsageState;
	int32_t mtpLsOperationalState;
	uint8_t *mtpLsAvailabilityStatus;
	int mtpLsAvailabilityStatusLen;
	int32_t mtpLsPeriodicLinkTestFlag;
	int32_t mtpLsPeriodicLinkTestFail;
	int32_t mtpLsAdministrativeState;
	oid *mtpLsInLsLoadShareAlgorithm;
	int mtpLsInLsLoadShareAlgorithmLen;
	uint8_t *mtpLsProfilePointer;
	int mtpLsProfilePointerLen;
	uint32_t mtpLsNumberOfNormallyActiveSignLinks;
	uint8_t *mtpLsName;
	int mtpLsNameLen;
	oid *mtpLsAsaProfilePointer;
	int mtpLsAsaProfilePointerLen;
	uint8_t *mtpLsAlarmStatus;
	int mtpLsAlarmStatusLen;
	int32_t mtpLsRowStatus;
};
struct mtpSlL3ProfileTable_data {
	uint mtpSlL3ProfileTable_request;
	uint mtpSlL3ProfileTable_refs;
	uint8_t *mtpSlL3ProfileId;
	int mtpSlL3ProfileIdLen;
	int32_t mtpSlL3ProfileTimerT1;
	int32_t mtpSlL3ProfileTimerT3;
	int32_t mtpSlL3ProfileTimerT17;
	int32_t mtpSlL3ProfileTimerT24I;
	uint8_t *mtpSlL3ProfileName;
	int mtpSlL3ProfileNameLen;
	int32_t mtpSlL3ProfileTimerT2;
	int32_t mtpSlL3ProfileTimerT4;
	int32_t mtpSlL3ProfileTimerT5;
	int32_t mtpSlL3ProfileTimerT12;
	int32_t mtpSlL3ProfileTimerT13;
	int32_t mtpSlL3ProfileTimerT14;
	int32_t mtpSlL3ProfileTimerT19A;
	int32_t mtpSlL3ProfileTimerT20A;
	int32_t mtpSlL3ProfileTimerT21A;
	int32_t mtpSlL3ProfileTimerT22I;
	int32_t mtpSlL3ProfileTimerT23I;
	int32_t mtpSlL3ProfileTimerT31A;
	int32_t mtpSlL3ProfileTimerT32A;
	int32_t mtpSlL3ProfileTimerT33A;
	int32_t mtpSlL3ProfileTimerT34A;
	int32_t mtpSlL3ProfileTimerT1T;
	int32_t mtpSlL3ProfileTimerT2T;
	int32_t mtpSlL3ProfileTimerT1S;
	uint8_t *mtpSlL3ProfileL2Default;
	int mtpSlL3ProfileL2DefaultLen;
	int32_t mtpSlL3ProfileRowStatus;
};
struct mtpSlL2ProfileTable_data {
	uint mtpSlL2ProfileTable_request;
	uint mtpSlL2ProfileTable_refs;
	uint8_t *mtpSlL2ProfileId;
	int mtpSlL2ProfileIdLen;
	int32_t mtpSlL2ProfileErrorCorrectionMethod;
	int32_t mtpSlL2ProfileTransmissionRate;
	int32_t mtpSlL2ProfileTimerT1;
	int32_t mtpSlL2ProfileTimerT2;
	int32_t mtpSlL2ProfileTimerT2L;
	int32_t mtpSlL2ProfileTimerT2H;
	int32_t mtpSlL2ProfileTimerT3;
	int32_t mtpSlL2ProfileTimerT4N;
	int32_t mtpSlL2ProfileTimerT4E;
	int32_t mtpSlL2ProfileTimerT5;
	int32_t mtpSlL2ProfileTimerT6;
	int32_t mtpSlL2ProfileTimerT7;
	uint32_t mtpSlL2ProfileTbOnset1;
	uint32_t mtpSlL2ProfileTbAbate1;
	uint32_t mtpSlL2ProfileNumberOfThresholdLevels;
	int32_t mtpSlL2ProfileCongestionCounting;
	int32_t mtpSlL2ProfileCongestionReportingBaseObject;
	uint32_t mtpSlL2ProfileLoopDelay;
	uint8_t *mtpSlL2ProfileName;
	int mtpSlL2ProfileNameLen;
	uint32_t mtpSlL2ProfileTbOnset2;
	uint32_t mtpSlL2ProfileTbAbate2;
	uint32_t mtpSlL2ProfileTbOnset3;
	uint32_t mtpSlL2ProfileTbAbate3;
	uint32_t mtpSlL2ProfileTbDiscard1;
	uint32_t mtpSlL2ProfileTbDiscard2;
	uint32_t mtpSlL2ProfileTbDiscard3;
	int32_t mtpSlL2ProfileTimerTx;
	int32_t mtpSlL2ProfileTimerTy;
	uint32_t mtpSlL2ProfileNumberOfCongestionStates;
	uint32_t mtpSlL2ProfileInitialLevelOfCongestion;
	uint32_t mtpSlL2ProfileMaxMSUsRetransN1;
	uint32_t mtpSlL2ProfileMaxOctRetransN2;
	uint32_t mtpSlL2ProfileReceiveCongestionThresholdOnset;
	uint32_t mtpSlL2ProfileReceiveCongestionThresholdAbate;
	uint32_t mtpSlL2ProfileReceiveCongestionThresholdDiscard;
	uint32_t mtpSlL2ProfileM;
	int32_t mtpSlL2ProfileRowStatus;
};
struct mtpSlTable_data {
	uint mtpSlTable_request;
	uint mtpSlTable_refs;
	uint32_t mtpSpId;
	uint32_t mtpLsId;
	uint32_t mtpSlSlCode;
	uint8_t *mtpSlSlsCodeCurrentList;
	int mtpSlSlsCodeCurrentListLen;
	uint32_t mtpSlMaxCapacitySL;
	uint32_t mtpSlCurrentCapacitySL;
	uint8_t *mtpSlLinkTpStatus;
	int mtpSlLinkTpStatusLen;
	int32_t mtpSlAdministrativeState;
	int32_t mtpSlOperationalState;
	int32_t mtpSlUsageState;
	uint8_t *mtpSlProceduralStatus;
	int mtpSlProceduralStatusLen;
	uint8_t *mtpSlMtpL2ProtocolProfilePointer;
	int mtpSlMtpL2ProtocolProfilePointerLen;
	oid *mtpSlSignTermPointer;
	int mtpSlSignTermPointerLen;
	oid *mtpSlSignDataLinkTpPointer;
	int mtpSlSignDataLinkTpPointerLen;
	int32_t mtpSlLocalInhibit;
	int32_t mtpSlLocalUninhibit;
	int32_t mtpSlReplaceSt;
	oid *mtpSlAsaProfilePointer;
	int mtpSlAsaProfilePointerLen;
	int32_t mtpSlCongestionLevel;
	uint32_t mtpSlRelatedLinkGroupNumber;
	uint32_t mtpSlSdlList;
	int32_t mtpSlTest;
	uint8_t *mtpSlName;
	int mtpSlNameLen;
	uint32_t mtpSlSdtList;
	uint8_t *mtpSlSlsCodeNormalList;
	int mtpSlSlsCodeNormalListLen;
	uint8_t *mtpSlL3ProfilePointer;
	int mtpSlL3ProfilePointerLen;
	uint8_t *mtpSlAlarmStatus;
	int mtpSlAlarmStatusLen;
	int32_t mtpSlRowStatus;
};
struct mtpSlSdlListTable_data {
	uint mtpSlSdlListTable_request;
	uint mtpSlSdlListTable_refs;
	uint32_t mtpSpId;
	uint32_t mtpLsId;
	uint32_t mtpSlSlCode;
	uint32_t mtpSlSdlListId;
	oid *mtpSlSdlListPointer;
	int mtpSlSdlListPointerLen;
	int32_t mtpSlSdlListRowStatus;
};
struct mtpSlSdtListTable_data {
	uint mtpSlSdtListTable_request;
	uint mtpSlSdtListTable_refs;
	uint32_t mtpSpId;
	uint32_t mtpLsId;
	uint32_t mtpSlSlCode;
	uint32_t mtpSlSdtListId;
	oid *mtpSlSdtListPointer;
	int mtpSlSdtListPointerLen;
	int32_t mtpSlSdtListRowStatus;
};
struct mtpNbTable_data {
	uint mtpNbTable_request;
	uint mtpNbTable_refs;
	uint8_t *mtpSdtProfileId;
	int mtpSdtProfileIdLen;
	int32_t mtpNbTransmissionRate;
	uint32_t mtpNbTimerT8;
	uint32_t mtpNbTin;
	uint32_t mtpNbTie;
	uint32_t mtpNbT;
	uint32_t mtpNbD;
	uint32_t mtpNbTe;
	uint32_t mtpNbDe;
	uint32_t mtpNbUe;
	uint32_t mtpNbN;
	uint32_t mtpNbm;
	uint32_t mtpNbb;
	int32_t mtpNbf;
	int32_t mtpNbRowStatus;
};
struct mtpSaalTable_data {
	uint mtpSaalTable_request;
	uint mtpSaalTable_refs;
	uint8_t *mtpSdtProfileId;
	int mtpSdtProfileIdLen;
	int32_t mtpSaalBufferRelease;
	uint32_t mtpSaalMaxCc;
	uint32_t mtpSaalMaxNrp;
	uint32_t mtpSaalMaxInformationFieldLength;
	uint32_t mtpSaalMaxLengthSscopUuField;
	uint32_t mtpSaalMaxPd;
	uint32_t mtpSaalMaxSscopCreditToPeer;
	uint32_t mtpSaalMaxStat;
	uint32_t mtpSaalN1;
	int32_t mtpSaalNniLayerManagementProvingState;
	int32_t mtpSaalNniLayerManagementTimerNoCredit;
	int32_t mtpSaalNniLayerManagementTimerRepeatSrec;
	int32_t mtpSaalNniTimerT1;
	int32_t mtpSaalNniTimerT2;
	int32_t mtpSaalNniTimerT3;
	int32_t mtpSaalSscopTimerCc;
	int32_t mtpSaalSscopTimerIdle;
	int32_t mtpSaalSscopTimerKeepAlive;
	int32_t mtpSaalSscopTimerNoResponse;
	int32_t mtpSaalSscopTimerPoll;
	uint32_t mtpSaalTransmissionRateIntervalLower;
	uint32_t mtpSaalTransmissionRateIntervalUpper;
	uint32_t mtpSaalEgressTransmissionRateIntervalLower;
	uint32_t mtpSaalEgressTransmissionRateIntervalUpper;
	int32_t mtpSaalPollAfterRetransmission;
	int32_t mtpSaalRowStatus;
};
struct mtpM2paTable_data {
	uint mtpM2paTable_request;
	uint mtpM2paTable_refs;
	uint8_t *mtpSdtProfileId;
	int mtpSdtProfileIdLen;
	uint32_t mtpM2paN1;
	int32_t mtpM2paProving;
	int32_t mtpM2paManagementProvingState;
	uint32_t mtpM2paLoopDelayLower;
	uint32_t mtpM2paLoopDelayUpper;
	uint32_t mtpM2paTransmissionRateIntervalLower;
	uint32_t mtpM2paTransmissionRateIntervalUpper;
	int32_t mtpM2paSctpNoDelay;
	uint32_t mtpM2paSctpMaxseg;
	uint32_t mtpM2paSctpHeartbeatItvl;
	int32_t mtpM2paSctpHeartbeat;
	uint32_t mtpM2paSctpRtoInitial;
	uint32_t mtpM2paSctpRtoMin;
	uint32_t mtpM2paSctpRtoMax;
	uint32_t mtpM2paSctpPathMaxRetrans;
	uint32_t mtpM2paSctpCookieLife;
	uint32_t mtpM2paSctpCookieInc;
	uint32_t mtpM2paSctpMaxInitRetries;
	uint32_t mtpM2paSctpMaxBurst;
	uint32_t mtpM2paSctpAssocMaxRetrans;
	uint32_t mtpM2paSctpSackDelay;
	uint32_t mtpM2paSctpLifetime;
	uint32_t mtpM2paProvingAttempts;
	int32_t mtpM2paRowStatus;
};
struct mtpSdtTable_data {
	uint mtpSdtTable_request;
	uint mtpSdtTable_refs;
	uint32_t mtpSdtId;
	int32_t mtpSdtAdministrativeState;
	int32_t mtpSdtOperationalState;
	int32_t mtpSdtUsageState;
	uint8_t *mtpSdtProceduralStatus;
	int mtpSdtProceduralStatusLen;
	uint8_t *mtpSdtAvailabilityStatus;
	int mtpSdtAvailabilityStatusLen;
	oid *mtpSdtEquipmentPointer;
	int mtpSdtEquipmentPointerLen;
	uint8_t *mtpSdtName;
	int mtpSdtNameLen;
	oid *mtpSdtProfilePointer;
	int mtpSdtProfilePointerLen;
	int32_t mtpSdtRowStatus;
};
struct mtpSdlTable_data {
	uint mtpSdlTable_request;
	uint mtpSdlTable_refs;
	uint32_t mtpSdlId;
	uint8_t *mtpSdlAdjPc;
	int mtpSdlAdjPcLen;
	int32_t mtpSdlTransmissionRate;
	uint32_t mtpSdlLoopDelay;
	int32_t mtpSdlOperationalState;
	oid *mtpSdlEquipmentPointer;
	int mtpSdlEquipmentPointerLen;
	int32_t mtpSdlCIC;
	uint8_t *mtpSdlName;
	int mtpSdlNameLen;
	uint8_t *mtpSdlStmChannel;
	int mtpSdlStmChannelLen;
	oid *mtpSdlVcTTpPointer;
	int mtpSdlVcTTpPointerLen;
	int32_t mtpSdlRowStatus;
};

/* storage declarations */
extern struct mtpMIB_data *mtpMIBStorage;
extern struct header_complex_index *mtpSapTableStorage;
extern struct header_complex_index *mtpMsTableStorage;
extern struct header_complex_index *mtpNaTableStorage;
extern struct header_complex_index *mtpGsTableStorage;
extern struct header_complex_index *mtpGsLineTableStorage;
extern struct header_complex_index *mtpGsLineContentTableStorage;
extern struct header_complex_index *mtpSpProfileTableStorage;
extern struct header_complex_index *mtpSpTableStorage;
extern struct header_complex_index *mtpL3TableStorage;
extern struct header_complex_index *mtpRsProfileTableStorage;
extern struct header_complex_index *mtpRsTableStorage;
extern struct header_complex_index *mtpRtProfileTableStorage;
extern struct header_complex_index *mtpRtTableStorage;
extern struct header_complex_index *mtpRtLsaTableStorage;
extern struct header_complex_index *mtpLsProfileTableStorage;
extern struct header_complex_index *mtpLsTableStorage;
extern struct header_complex_index *mtpSlL3ProfileTableStorage;
extern struct header_complex_index *mtpSlL2ProfileTableStorage;
extern struct header_complex_index *mtpSlTableStorage;
extern struct header_complex_index *mtpSlSdlListTableStorage;
extern struct header_complex_index *mtpSlSdtListTableStorage;
extern struct header_complex_index *mtpNbTableStorage;
extern struct header_complex_index *mtpSaalTableStorage;
extern struct header_complex_index *mtpM2paTableStorage;
extern struct header_complex_index *mtpSdtTableStorage;
extern struct header_complex_index *mtpSdlTableStorage;

/* enum definitions from the covered mib sections */

#define MTPSAPUSERPART_SNMM                      0
#define MTPSAPUSERPART_SNTM                      1
#define MTPSAPUSERPART_SNSM                      2
#define MTPSAPUSERPART_SCCP                      3
#define MTPSAPUSERPART_TUP                       4
#define MTPSAPUSERPART_ISUP                      5
#define MTPSAPUSERPART_DUP1                      6
#define MTPSAPUSERPART_DUP2                      7
#define MTPSAPUSERPART_MTUP                      8
#define MTPSAPUSERPART_BISUP                     9
#define MTPSAPUSERPART_SIUP                      10
#define MTPSAPUSERPART_USER11                    11
#define MTPSAPUSERPART_USER12                    12
#define MTPSAPUSERPART_USER13                    13
#define MTPSAPUSERPART_USER14                    14
#define MTPSAPUSERPART_USER15                    15

#define MTPSAPUSERPARTSTATUS_UNKNOWN             0
#define MTPSAPUSERPARTSTATUS_INACCESSIBLE        1
#define MTPSAPUSERPARTSTATUS_UNEQUIPPED          2

#define MTPSAPUSAGESTATE_IDLE                    0
#define MTPSAPUSAGESTATE_ACTIVE                  1
#define MTPSAPUSAGESTATE_BUSY                    2

#define MTPSAPLONGMESSAGESUPPORTED_TRUE          1
#define MTPSAPLONGMESSAGESUPPORTED_FALSE         2

#define MTPMSALARMSTATUS_UNDERREPAIR             0
#define MTPMSALARMSTATUS_CRITICAL                1
#define MTPMSALARMSTATUS_MAJOR                   2
#define MTPMSALARMSTATUS_MINOR                   3
#define MTPMSALARMSTATUS_ALARMOUTSTANDING        4

#define MTPMSOPERATIONALSTATE_DISABLED           0
#define MTPMSOPERATIONALSTATE_ENABLED            1

#define MTPMSUSAGESTATE_IDLE                     0
#define MTPMSUSAGESTATE_ACTIVE                   1
#define MTPMSUSAGESTATE_BUSY                     2

#define MTPNAPROTOCOLYEAR_Y1980                  1980
#define MTPNAPROTOCOLYEAR_Y1984                  1984
#define MTPNAPROTOCOLYEAR_Y1988                  1988
#define MTPNAPROTOCOLYEAR_Y1992                  1992
#define MTPNAPROTOCOLYEAR_Y1996                  1996
#define MTPNAPROTOCOLYEAR_Y2000                  2000
#define MTPNAPROTOCOLYEAR_Y2004                  2004
#define MTPNAPROTOCOLYEAR_Y2008                  2008

#define MTPNAPROTOCOLOPTIONS_MTPFCONGINT         0
#define MTPNAPROTOCOLOPTIONS_MTPFCONGLEV         1
#define MTPNAPROTOCOLOPTIONS_MTPFCONGSTA         2
#define MTPNAPROTOCOLOPTIONS_MTPFTFRBASIC        3
#define MTPNAPROTOCOLOPTIONS_MTPFTFRBCAST        4
#define MTPNAPROTOCOLOPTIONS_MTPFTFRRESP         5
#define MTPNAPROTOCOLOPTIONS_MTPFTFRCONG         6
#define MTPNAPROTOCOLOPTIONS_MTPFLINKOSC         7
#define MTPNAPROTOCOLOPTIONS_MTPFLINKOSCA        8
#define MTPNAPROTOCOLOPTIONS_MTPFLINKOSCB        9
#define MTPNAPROTOCOLOPTIONS_MTPFPCALIAS         10
#define MTPNAPROTOCOLOPTIONS_MTPFCLUSTER         11
#define MTPNAPROTOCOLOPTIONS_MTPFSNSM            12
#define MTPNAPROTOCOLOPTIONS_MTPFGWS             13
#define MTPNAPROTOCOLOPTIONS_MTPFEGWS            14
#define MTPNAPROTOCOLOPTIONS_MTPFBGWS            15
#define MTPNAPROTOCOLOPTIONS_MTPFLINKPCR         16
#define MTPNAPROTOCOLOPTIONS_MTPFLINKHSL         17
#define MTPNAPROTOCOLOPTIONS_MTPFLINKHSLBSN      18
#define MTPNAPROTOCOLOPTIONS_MTPFLINKHSLESN      19
#define MTPNAPROTOCOLOPTIONS_MTPFLINKSAAL        20
#define MTPNAPROTOCOLOPTIONS_MTPFLINKM2PA        21
#define MTPNAPROTOCOLOPTIONS_MTPFLINKPROVING     22
#define MTPNAPROTOCOLOPTIONS_MTPFLINKSDLALLOC    23
#define MTPNAPROTOCOLOPTIONS_MTPFLINKSTALLOC     24
#define MTPNAPROTOCOLOPTIONS_MTPFSNTMFAIL        25

#define MTPNANETWORKINDICATOR_INTERNATIONALNETWORK1 0
#define MTPNANETWORKINDICATOR_INTERNATIONALNETWORK2 1
#define MTPNANETWORKINDICATOR_NATIONALNETWORK1   2
#define MTPNANETWORKINDICATOR_NATIONALNETWORK2   3

#define MTPNASLSLENGTH_SLS4BITS                  4
#define MTPNASLSLENGTH_SLS5BITS                  5
#define MTPNASLSLENGTH_SLS8BITS                  8

#define MTPGSADMINISTRATIVESTATE_LOCKED          0
#define MTPGSADMINISTRATIVESTATE_UNLOCKED        1
#define MTPGSADMINISTRATIVESTATE_SHUTTINGDOWN    2

#define MTPGSTREATMENTOFOUTSIDERANGES_NORMAL     0
#define MTPGSTREATMENTOFOUTSIDERANGES_DISCARD    1
#define MTPGSTREATMENTOFOUTSIDERANGES_PROHIBIT   2
#define MTPGSTREATMENTOFOUTSIDERANGES_UNEQUIPPED 3
#define MTPGSTREATMENTOFOUTSIDERANGES_INACCESSIBLE 4
#define MTPGSTREATMENTOFOUTSIDERANGES_CONGEST    5

#define MTPGSLISTMODE_TRUE                       1
#define MTPGSLISTMODE_FALSE                      2

#define MTPGSSCREENINGBYLINKSETORBYOPC_BYOPC     0
#define MTPGSSCREENINGBYLINKSETORBYOPC_BYINCOMINGLINKSET 1
#define MTPGSSCREENINGBYLINKSETORBYOPC_BYOUTGOINGLINKSET 2

#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_SUCCESS 0
#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_UNSUCCESSFUL 1
#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_NOTPERFORMED 2
#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_LINKALREADYINHIBITED 3
#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_LINKNOTINHIBITED 4
#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_WRONGCLASSREFERENCED 5
#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_SIGNTERMNONEXISTING 6
#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_SIGNTERMALREADYREFERENCED 7
#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_WRONGSIGNLINKTPSTATUS 8

#define MTPGSLINECONTENTSIMASK_SNMM              0
#define MTPGSLINECONTENTSIMASK_SNTM              1
#define MTPGSLINECONTENTSIMASK_SNSM              2
#define MTPGSLINECONTENTSIMASK_SCCP              3
#define MTPGSLINECONTENTSIMASK_TUP               4
#define MTPGSLINECONTENTSIMASK_ISUP              5
#define MTPGSLINECONTENTSIMASK_DUP1              6
#define MTPGSLINECONTENTSIMASK_DUP2              7
#define MTPGSLINECONTENTSIMASK_MTUP              8
#define MTPGSLINECONTENTSIMASK_BISUP             9
#define MTPGSLINECONTENTSIMASK_SIUP              10
#define MTPGSLINECONTENTSIMASK_USER11            11
#define MTPGSLINECONTENTSIMASK_USER12            12
#define MTPGSLINECONTENTSIMASK_USER13            13
#define MTPGSLINECONTENTSIMASK_USER14            14
#define MTPGSLINECONTENTSIMASK_USER15            15

#define MTPGSLINECONTENTMESSAGETREATMENT_NORMAL  0
#define MTPGSLINECONTENTMESSAGETREATMENT_DISCARD 1
#define MTPGSLINECONTENTMESSAGETREATMENT_PROHIBIT 2
#define MTPGSLINECONTENTMESSAGETREATMENT_UNEQUIPPED 3
#define MTPGSLINECONTENTMESSAGETREATMENT_INACCESSIBLE 4
#define MTPGSLINECONTENTMESSAGETREATMENT_CONGEST 5

#define MTPSPTYPE_SEP                            0
#define MTPSPTYPE_STEP                           1
#define MTPSPTYPE_STP                            2

#define MTPSPOPERATIONALSTATE_DISABLED           0
#define MTPSPOPERATIONALSTATE_ENABLED            1

#define MTPSPPROCEDURALSTATUS_INITIALIZATIONREQUIRED 0
#define MTPSPPROCEDURALSTATUS_NOTINITIALIZED     1
#define MTPSPPROCEDURALSTATUS_INITIALIZING       2
#define MTPSPPROCEDURALSTATUS_REPORTING          3
#define MTPSPPROCEDURALSTATUS_TERMINATING        4

#define MTPSPAVAILABILITYSTATUS_INTEST           0
#define MTPSPAVAILABILITYSTATUS_FAILED           1
#define MTPSPAVAILABILITYSTATUS_POWEROFF         2
#define MTPSPAVAILABILITYSTATUS_OFFLINE          3
#define MTPSPAVAILABILITYSTATUS_OFFDUTY          4
#define MTPSPAVAILABILITYSTATUS_DEPENDENCY       5
#define MTPSPAVAILABILITYSTATUS_DEGRADED         6
#define MTPSPAVAILABILITYSTATUS_NOTINSTALLED     7
#define MTPSPAVAILABILITYSTATUS_LOGFULL          8

#define MTPSPNETWORKINDICATOR_INTERNATIONALNETWORK1 0
#define MTPSPNETWORKINDICATOR_INTERNATIONALNETWORK2 1
#define MTPSPNETWORKINDICATOR_NATIONALNETWORK1   2
#define MTPSPNETWORKINDICATOR_NATIONALNETWORK2   3

#define MTPSPFLAGS_SPFCLUSTER                    0
#define MTPSPFLAGS_SPFXFERFUNC                   1
#define MTPSPFLAGS_SPFSECURITY                   2
#define MTPSPFLAGS_SPFLOSCPROCA                  3
#define MTPSPFLAGS_SPFLOSCPROCB                  4

#define MTPSPUSERS_SNMM                          0
#define MTPSPUSERS_SNTM                          1
#define MTPSPUSERS_SNSM                          2
#define MTPSPUSERS_SCCP                          3
#define MTPSPUSERS_TUP                           4
#define MTPSPUSERS_ISUP                          5
#define MTPSPUSERS_DUP1                          6
#define MTPSPUSERS_DUP2                          7
#define MTPSPUSERS_MTUP                          8
#define MTPSPUSERS_BISUP                         9
#define MTPSPUSERS_SIUP                          10
#define MTPSPUSERS_USER11                        11
#define MTPSPUSERS_USER12                        12
#define MTPSPUSERS_USER13                        13
#define MTPSPUSERS_USER14                        14
#define MTPSPUSERS_USER15                        15

#define MTPSPALARMSTATUS_UNDERREPAIR             0
#define MTPSPALARMSTATUS_CRITICAL                1
#define MTPSPALARMSTATUS_MAJOR                   2
#define MTPSPALARMSTATUS_MINOR                   3
#define MTPSPALARMSTATUS_ALARMOUTSTANDING        4

#define MTPL3ADMINISTRATIVESTATE_LOCKED          0
#define MTPL3ADMINISTRATIVESTATE_UNLOCKED        1
#define MTPL3ADMINISTRATIVESTATE_SHUTTINGDOWN    2

#define MTPL3OPERATIONALSTATE_DISABLED           0
#define MTPL3OPERATIONALSTATE_ENABLED            1

#define MTPL3USAGESTATE_IDLE                     0
#define MTPL3USAGESTATE_ACTIVE                   1
#define MTPL3USAGESTATE_BUSY                     2

#define MTPL3PROCEDURALSTATUS_INITIALIZATIONREQUIRED 0
#define MTPL3PROCEDURALSTATUS_NOTINITIALIZED     1
#define MTPL3PROCEDURALSTATUS_INITIALIZING       2
#define MTPL3PROCEDURALSTATUS_REPORTING          3
#define MTPL3PROCEDURALSTATUS_TERMINATING        4

#define MTPRSFLAGS_RSFCLUSTER                    0
#define MTPRSFLAGS_RSFXFERFUNC                   1
#define MTPRSFLAGS_RSFSECURITY                   2
#define MTPRSFLAGS_RSFADJACENT                   3

#define MTPRSADMINISTRATIVESTATE_LOCKED          0
#define MTPRSADMINISTRATIVESTATE_UNLOCKED        1
#define MTPRSADMINISTRATIVESTATE_SHUTTINGDOWN    2

#define MTPRSOPERATIONALSTATE_DISABLED           0
#define MTPRSOPERATIONALSTATE_ENABLED            1

#define MTPRSCONGESTEDSTATE_NOTCONGESTED         0
#define MTPRSCONGESTEDSTATE_CONGESTED            1

#define MTPRSCONGESTIONLEVEL_NONE                0
#define MTPRSCONGESTIONLEVEL_CONGESTIONLEVEL1    1
#define MTPRSCONGESTIONLEVEL_CONGESTIONLEVEL2    2
#define MTPRSCONGESTIONLEVEL_CONGESTIONLEVEL3    3

#define MTPRSALARMSTATUS_UNDERREPAIR             0
#define MTPRSALARMSTATUS_CRITICAL                1
#define MTPRSALARMSTATUS_MAJOR                   2
#define MTPRSALARMSTATUS_MINOR                   3
#define MTPRSALARMSTATUS_ALARMOUTSTANDING        4

#define MTPRTADMINISTRATIVESTATE_LOCKED          0
#define MTPRTADMINISTRATIVESTATE_UNLOCKED        1
#define MTPRTADMINISTRATIVESTATE_SHUTTINGDOWN    2

#define MTPRTOPERATIONALSTATE_DISABLED           0
#define MTPRTOPERATIONALSTATE_ENABLED            1

#define MTPRTAVAILABILITYSTATUS_INTEST           0
#define MTPRTAVAILABILITYSTATUS_FAILED           1
#define MTPRTAVAILABILITYSTATUS_POWEROFF         2
#define MTPRTAVAILABILITYSTATUS_OFFLINE          3
#define MTPRTAVAILABILITYSTATUS_OFFDUTY          4
#define MTPRTAVAILABILITYSTATUS_DEPENDENCY       5
#define MTPRTAVAILABILITYSTATUS_DEGRADED         6
#define MTPRTAVAILABILITYSTATUS_NOTINSTALLED     7
#define MTPRTAVAILABILITYSTATUS_LOGFULL          8

#define MTPRTPRIORITYMODE_INSERT                 0
#define MTPRTPRIORITYMODE_EQUAL                  1
#define MTPRTPRIORITYMODE_EXCHANGESINGLE         2
#define MTPRTPRIORITYMODE_EXCHANGEGROUP          3

#define MTPRTUSAGESTATE_IDLE                     0
#define MTPRTUSAGESTATE_ACTIVE                   1
#define MTPRTUSAGESTATE_BUSY                     2

#define MTPLSCONGESTIONCONTROLMETHOD_UNKNOWN     0
#define MTPLSCONGESTIONCONTROLMETHOD_CCMQ704INTERNATIONAL 1
#define MTPLSCONGESTIONCONTROLMETHOD_CCMQ704NATIONALWITHPRIO 2
#define MTPLSCONGESTIONCONTROLMETHOD_CCMQ704NATIONALNOPRIOBUFFERMECHANISM 3
#define MTPLSCONGESTIONCONTROLMETHOD_CCMQ704NATIONALNOPRIOTIMERMECHANISM 4

#define MTPLSUSAGESTATE_IDLE                     0
#define MTPLSUSAGESTATE_ACTIVE                   1
#define MTPLSUSAGESTATE_BUSY                     2

#define MTPLSOPERATIONALSTATE_DISABLED           0
#define MTPLSOPERATIONALSTATE_ENABLED            1

#define MTPLSAVAILABILITYSTATUS_INTEST           0
#define MTPLSAVAILABILITYSTATUS_FAILED           1
#define MTPLSAVAILABILITYSTATUS_POWEROFF         2
#define MTPLSAVAILABILITYSTATUS_OFFLINE          3
#define MTPLSAVAILABILITYSTATUS_OFFDUTY          4
#define MTPLSAVAILABILITYSTATUS_DEPENDENCY       5
#define MTPLSAVAILABILITYSTATUS_DEGRADED         6
#define MTPLSAVAILABILITYSTATUS_NOTINSTALLED     7
#define MTPLSAVAILABILITYSTATUS_LOGFULL          8

#define MTPLSPERIODICLINKTESTFLAG_ON             0
#define MTPLSPERIODICLINKTESTFLAG_OFF            1

#define MTPLSPERIODICLINKTESTFAIL_TRUE           1
#define MTPLSPERIODICLINKTESTFAIL_FALSE          2

#define MTPLSADMINISTRATIVESTATE_LOCKED          0
#define MTPLSADMINISTRATIVESTATE_UNLOCKED        1
#define MTPLSADMINISTRATIVESTATE_SHUTTINGDOWN    2

#define MTPLSALARMSTATUS_UNDERREPAIR             0
#define MTPLSALARMSTATUS_CRITICAL                1
#define MTPLSALARMSTATUS_MAJOR                   2
#define MTPLSALARMSTATUS_MINOR                   3
#define MTPLSALARMSTATUS_ALARMOUTSTANDING        4

#define MTPSLL2PROFILEERRORCORRECTIONMETHOD_BASICRETR 0
#define MTPSLL2PROFILEERRORCORRECTIONMETHOD_PREVCYCLRETR 1

#define MTPSLL2PROFILETRANSMISSIONRATE_KBITS4POINT8 0
#define MTPSLL2PROFILETRANSMISSIONRATE_KBITS56   1
#define MTPSLL2PROFILETRANSMISSIONRATE_KBITS64   2
#define MTPSLL2PROFILETRANSMISSIONRATE_KBITS1544 3
#define MTPSLL2PROFILETRANSMISSIONRATE_KBITS2048 4

#define MTPSLL2PROFILECONGESTIONCOUNTING_OCTET   0
#define MTPSLL2PROFILECONGESTIONCOUNTING_MESSAGE 1

#define MTPSLL2PROFILECONGESTIONREPORTINGBASEOBJECT_ROUTESET 0
#define MTPSLL2PROFILECONGESTIONREPORTINGBASEOBJECT_LINKSETOFCONGESTEDROUTESET 1
#define MTPSLL2PROFILECONGESTIONREPORTINGBASEOBJECT_LINKOFCONGESTEDROUTESET 2
#define MTPSLL2PROFILECONGESTIONREPORTINGBASEOBJECT_CONGESTEDLINKOFCONGESTEDROUTE 3

#define MTPSLLINKTPSTATUS_LOCALBLOCKED           0
#define MTPSLLINKTPSTATUS_REMOTEBLOCKED          1
#define MTPSLLINKTPSTATUS_LOCALINHIBITED         2
#define MTPSLLINKTPSTATUS_REMOTEINHIBITED        3
#define MTPSLLINKTPSTATUS_FAILED                 4
#define MTPSLLINKTPSTATUS_DEACTIVATED            5

#define MTPSLADMINISTRATIVESTATE_LOCKED          0
#define MTPSLADMINISTRATIVESTATE_UNLOCKED        1
#define MTPSLADMINISTRATIVESTATE_SHUTTINGDOWN    2

#define MTPSLOPERATIONALSTATE_DISABLED           0
#define MTPSLOPERATIONALSTATE_ENABLED            1

#define MTPSLUSAGESTATE_IDLE                     0
#define MTPSLUSAGESTATE_ACTIVE                   1
#define MTPSLUSAGESTATE_BUSY                     2

#define MTPSLPROCEDURALSTATUS_INITIALIZATIONREQUIRED 0
#define MTPSLPROCEDURALSTATUS_NOTINITIALIZED     1
#define MTPSLPROCEDURALSTATUS_INITIALIZING       2
#define MTPSLPROCEDURALSTATUS_REPORTING          3
#define MTPSLPROCEDURALSTATUS_TERMINATING        4

#define MTPSLLOCALINHIBIT_SUCCESS                0
#define MTPSLLOCALINHIBIT_UNSUCCESSFUL           1
#define MTPSLLOCALINHIBIT_NOTPERFORMED           2
#define MTPSLLOCALINHIBIT_LINKALREADYINHIBITED   3
#define MTPSLLOCALINHIBIT_LINKNOTINHIBITED       4
#define MTPSLLOCALINHIBIT_WRONGCLASSREFERENCED   5
#define MTPSLLOCALINHIBIT_SIGNTERMNONEXISTING    6
#define MTPSLLOCALINHIBIT_SIGNTERMALREADYREFERENCED 7
#define MTPSLLOCALINHIBIT_WRONGSIGNLINKTPSTATUS  8

#define MTPSLLOCALUNINHIBIT_SUCCESS              0
#define MTPSLLOCALUNINHIBIT_UNSUCCESSFUL         1
#define MTPSLLOCALUNINHIBIT_NOTPERFORMED         2
#define MTPSLLOCALUNINHIBIT_LINKALREADYINHIBITED 3
#define MTPSLLOCALUNINHIBIT_LINKNOTINHIBITED     4
#define MTPSLLOCALUNINHIBIT_WRONGCLASSREFERENCED 5
#define MTPSLLOCALUNINHIBIT_SIGNTERMNONEXISTING  6
#define MTPSLLOCALUNINHIBIT_SIGNTERMALREADYREFERENCED 7
#define MTPSLLOCALUNINHIBIT_WRONGSIGNLINKTPSTATUS 8

#define MTPSLREPLACEST_SUCCESS                   0
#define MTPSLREPLACEST_UNSUCCESSFUL              1
#define MTPSLREPLACEST_NOTPERFORMED              2
#define MTPSLREPLACEST_LINKALREADYINHIBITED      3
#define MTPSLREPLACEST_LINKNOTINHIBITED          4
#define MTPSLREPLACEST_WRONGCLASSREFERENCED      5
#define MTPSLREPLACEST_SIGNTERMNONEXISTING       6
#define MTPSLREPLACEST_SIGNTERMALREADYREFERENCED 7
#define MTPSLREPLACEST_WRONGSIGNLINKTPSTATUS     8

#define MTPSLCONGESTIONLEVEL_NONE                0
#define MTPSLCONGESTIONLEVEL_CONGESTIONLEVEL1    1
#define MTPSLCONGESTIONLEVEL_CONGESTIONLEVEL2    2
#define MTPSLCONGESTIONLEVEL_CONGESTIONLEVEL3    3

#define MTPSLTEST_SUCCESS                        0
#define MTPSLTEST_UNSUCCESSFUL                   1
#define MTPSLTEST_NOTPERFORMED                   2
#define MTPSLTEST_LINKALREADYINHIBITED           3
#define MTPSLTEST_LINKNOTINHIBITED               4
#define MTPSLTEST_WRONGCLASSREFERENCED           5
#define MTPSLTEST_SIGNTERMNONEXISTING            6
#define MTPSLTEST_SIGNTERMALREADYREFERENCED      7
#define MTPSLTEST_WRONGSIGNLINKTPSTATUS          8

#define MTPSLALARMSTATUS_UNDERREPAIR             0
#define MTPSLALARMSTATUS_CRITICAL                1
#define MTPSLALARMSTATUS_MAJOR                   2
#define MTPSLALARMSTATUS_MINOR                   3
#define MTPSLALARMSTATUS_ALARMOUTSTANDING        4

#define MTPNBTRANSMISSIONRATE_KBITS4POINT8       0
#define MTPNBTRANSMISSIONRATE_KBITS56            1
#define MTPNBTRANSMISSIONRATE_KBITS64            2
#define MTPNBTRANSMISSIONRATE_KBITS1544          3
#define MTPNBTRANSMISSIONRATE_KBITS2048          4

#define MTPNBF_ONE                               0
#define MTPNBF_SHARED                            1
#define MTPNBF_TWO                               2
#define MTPNBF_THREE                             3
#define MTPNBF_FOUR                              4
#define MTPNBF_FIVE                              5
#define MTPNBF_SIX                               6

#define MTPSAALBUFFERRELEASE_TRUE                1
#define MTPSAALBUFFERRELEASE_FALSE               2

#define MTPSAALNNILAYERMANAGEMENTPROVINGSTATE_NORMAL 0
#define MTPSAALNNILAYERMANAGEMENTPROVINGSTATE_EMERGENCY 1
#define MTPSAALNNILAYERMANAGEMENTPROVINGSTATE_NEUTRAL 2

#define MTPSAALPOLLAFTERRETRANSMISSION_TRUE      1
#define MTPSAALPOLLAFTERRETRANSMISSION_FALSE     2

#define MTPM2PAPROVING_TRUE                      1
#define MTPM2PAPROVING_FALSE                     2

#define MTPM2PAMANAGEMENTPROVINGSTATE_NORMAL     0
#define MTPM2PAMANAGEMENTPROVINGSTATE_EMERGENCY  1
#define MTPM2PAMANAGEMENTPROVINGSTATE_NEUTRAL    2

#define MTPM2PASCTPNODELAY_TRUE                  1
#define MTPM2PASCTPNODELAY_FALSE                 2

#define MTPM2PASCTPHEARTBEAT_TRUE                1
#define MTPM2PASCTPHEARTBEAT_FALSE               2

#define MTPSDTADMINISTRATIVESTATE_LOCKED         0
#define MTPSDTADMINISTRATIVESTATE_UNLOCKED       1
#define MTPSDTADMINISTRATIVESTATE_SHUTTINGDOWN   2

#define MTPSDTOPERATIONALSTATE_DISABLED          0
#define MTPSDTOPERATIONALSTATE_ENABLED           1

#define MTPSDTUSAGESTATE_IDLE                    0
#define MTPSDTUSAGESTATE_ACTIVE                  1
#define MTPSDTUSAGESTATE_BUSY                    2

#define MTPSDTPROCEDURALSTATUS_INITIALIZATIONREQUIRED 0
#define MTPSDTPROCEDURALSTATUS_NOTINITIALIZED    1
#define MTPSDTPROCEDURALSTATUS_INITIALIZING      2
#define MTPSDTPROCEDURALSTATUS_REPORTING         3
#define MTPSDTPROCEDURALSTATUS_TERMINATING       4

#define MTPSDTAVAILABILITYSTATUS_INTEST          0
#define MTPSDTAVAILABILITYSTATUS_FAILED          1
#define MTPSDTAVAILABILITYSTATUS_POWEROFF        2
#define MTPSDTAVAILABILITYSTATUS_OFFLINE         3
#define MTPSDTAVAILABILITYSTATUS_OFFDUTY         4
#define MTPSDTAVAILABILITYSTATUS_DEPENDENCY      5
#define MTPSDTAVAILABILITYSTATUS_DEGRADED        6
#define MTPSDTAVAILABILITYSTATUS_NOTINSTALLED    7
#define MTPSDTAVAILABILITYSTATUS_LOGFULL         8

#define MTPSDLTRANSMISSIONRATE_KBITS4POINT8      0
#define MTPSDLTRANSMISSIONRATE_KBITS56           1
#define MTPSDLTRANSMISSIONRATE_KBITS64           2
#define MTPSDLTRANSMISSIONRATE_KBITS1544         3
#define MTPSDLTRANSMISSIONRATE_KBITS2048         4

#define MTPSDLOPERATIONALSTATE_DISABLED          0
#define MTPSDLOPERATIONALSTATE_ENABLED           1

#define MTPM2PADEFAULTSCTPNODELAY_TRUE           1
#define MTPM2PADEFAULTSCTPNODELAY_FALSE          2

#define MTPM2PADEFAULTSCTPHEARTBEAT_TRUE         1
#define MTPM2PADEFAULTSCTPHEARTBEAT_FALSE        2

/* function prototypes */
void init_mtpMIB(void);
void deinit_mtpMIB(void);
int term_mtpMIB(int majorID, int minorID, void *serverarg, void *clientarg);
FindVarMethod var_mtpMIB;
void parse_mtpMIB(const char *, char *);
SNMPCallback store_mtpMIB;
void refresh_mtpMIB(void);
FindVarMethod var_mtpSapTable;
int mtpSapTable_add(struct mtpSapTable_data *);
int mtpSapTable_del(struct mtpSapTable_data **);
void parse_mtpSapTable(const char *, char *);
SNMPCallback store_mtpSapTable;
void refresh_mtpSapTable(void);
FindVarMethod var_mtpMsTable;
int mtpMsTable_add(struct mtpMsTable_data *);
int mtpMsTable_del(struct mtpMsTable_data **);
void parse_mtpMsTable(const char *, char *);
SNMPCallback store_mtpMsTable;
void refresh_mtpMsTable(void);
FindVarMethod var_mtpNaTable;
int mtpNaTable_add(struct mtpNaTable_data *);
int mtpNaTable_del(struct mtpNaTable_data **);
void parse_mtpNaTable(const char *, char *);
SNMPCallback store_mtpNaTable;
void refresh_mtpNaTable(void);
FindVarMethod var_mtpGsTable;
int mtpGsTable_add(struct mtpGsTable_data *);
int mtpGsTable_del(struct mtpGsTable_data **);
void parse_mtpGsTable(const char *, char *);
SNMPCallback store_mtpGsTable;
void refresh_mtpGsTable(void);
FindVarMethod var_mtpGsLineTable;
int mtpGsLineTable_add(struct mtpGsLineTable_data *);
int mtpGsLineTable_del(struct mtpGsLineTable_data **);
void parse_mtpGsLineTable(const char *, char *);
SNMPCallback store_mtpGsLineTable;
void refresh_mtpGsLineTable(void);
FindVarMethod var_mtpGsLineContentTable;
int mtpGsLineContentTable_add(struct mtpGsLineContentTable_data *);
int mtpGsLineContentTable_del(struct mtpGsLineContentTable_data **);
void parse_mtpGsLineContentTable(const char *, char *);
SNMPCallback store_mtpGsLineContentTable;
void refresh_mtpGsLineContentTable(void);
FindVarMethod var_mtpSpProfileTable;
int mtpSpProfileTable_add(struct mtpSpProfileTable_data *);
int mtpSpProfileTable_del(struct mtpSpProfileTable_data **);
void parse_mtpSpProfileTable(const char *, char *);
SNMPCallback store_mtpSpProfileTable;
void refresh_mtpSpProfileTable(void);
FindVarMethod var_mtpSpTable;
int mtpSpTable_add(struct mtpSpTable_data *);
int mtpSpTable_del(struct mtpSpTable_data **);
void parse_mtpSpTable(const char *, char *);
SNMPCallback store_mtpSpTable;
void refresh_mtpSpTable(void);
FindVarMethod var_mtpL3Table;
int mtpL3Table_add(struct mtpL3Table_data *);
int mtpL3Table_del(struct mtpL3Table_data **);
void parse_mtpL3Table(const char *, char *);
SNMPCallback store_mtpL3Table;
void refresh_mtpL3Table(void);
FindVarMethod var_mtpRsProfileTable;
int mtpRsProfileTable_add(struct mtpRsProfileTable_data *);
int mtpRsProfileTable_del(struct mtpRsProfileTable_data **);
void parse_mtpRsProfileTable(const char *, char *);
SNMPCallback store_mtpRsProfileTable;
void refresh_mtpRsProfileTable(void);
FindVarMethod var_mtpRsTable;
int mtpRsTable_add(struct mtpRsTable_data *);
int mtpRsTable_del(struct mtpRsTable_data **);
void parse_mtpRsTable(const char *, char *);
SNMPCallback store_mtpRsTable;
void refresh_mtpRsTable(void);
FindVarMethod var_mtpRtProfileTable;
int mtpRtProfileTable_add(struct mtpRtProfileTable_data *);
int mtpRtProfileTable_del(struct mtpRtProfileTable_data **);
void parse_mtpRtProfileTable(const char *, char *);
SNMPCallback store_mtpRtProfileTable;
void refresh_mtpRtProfileTable(void);
FindVarMethod var_mtpRtTable;
int mtpRtTable_add(struct mtpRtTable_data *);
int mtpRtTable_del(struct mtpRtTable_data **);
void parse_mtpRtTable(const char *, char *);
SNMPCallback store_mtpRtTable;
void refresh_mtpRtTable(void);
FindVarMethod var_mtpRtLsaTable;
int mtpRtLsaTable_add(struct mtpRtLsaTable_data *);
int mtpRtLsaTable_del(struct mtpRtLsaTable_data **);
void parse_mtpRtLsaTable(const char *, char *);
SNMPCallback store_mtpRtLsaTable;
void refresh_mtpRtLsaTable(void);
FindVarMethod var_mtpLsProfileTable;
int mtpLsProfileTable_add(struct mtpLsProfileTable_data *);
int mtpLsProfileTable_del(struct mtpLsProfileTable_data **);
void parse_mtpLsProfileTable(const char *, char *);
SNMPCallback store_mtpLsProfileTable;
void refresh_mtpLsProfileTable(void);
FindVarMethod var_mtpLsTable;
int mtpLsTable_add(struct mtpLsTable_data *);
int mtpLsTable_del(struct mtpLsTable_data **);
void parse_mtpLsTable(const char *, char *);
SNMPCallback store_mtpLsTable;
void refresh_mtpLsTable(void);
FindVarMethod var_mtpSlL3ProfileTable;
int mtpSlL3ProfileTable_add(struct mtpSlL3ProfileTable_data *);
int mtpSlL3ProfileTable_del(struct mtpSlL3ProfileTable_data **);
void parse_mtpSlL3ProfileTable(const char *, char *);
SNMPCallback store_mtpSlL3ProfileTable;
void refresh_mtpSlL3ProfileTable(void);
FindVarMethod var_mtpSlL2ProfileTable;
int mtpSlL2ProfileTable_add(struct mtpSlL2ProfileTable_data *);
int mtpSlL2ProfileTable_del(struct mtpSlL2ProfileTable_data **);
void parse_mtpSlL2ProfileTable(const char *, char *);
SNMPCallback store_mtpSlL2ProfileTable;
void refresh_mtpSlL2ProfileTable(void);
FindVarMethod var_mtpSlTable;
int mtpSlTable_add(struct mtpSlTable_data *);
int mtpSlTable_del(struct mtpSlTable_data **);
void parse_mtpSlTable(const char *, char *);
SNMPCallback store_mtpSlTable;
void refresh_mtpSlTable(void);
FindVarMethod var_mtpSlSdlListTable;
int mtpSlSdlListTable_add(struct mtpSlSdlListTable_data *);
int mtpSlSdlListTable_del(struct mtpSlSdlListTable_data **);
void parse_mtpSlSdlListTable(const char *, char *);
SNMPCallback store_mtpSlSdlListTable;
void refresh_mtpSlSdlListTable(void);
FindVarMethod var_mtpSlSdtListTable;
int mtpSlSdtListTable_add(struct mtpSlSdtListTable_data *);
int mtpSlSdtListTable_del(struct mtpSlSdtListTable_data **);
void parse_mtpSlSdtListTable(const char *, char *);
SNMPCallback store_mtpSlSdtListTable;
void refresh_mtpSlSdtListTable(void);
FindVarMethod var_mtpNbTable;
int mtpNbTable_add(struct mtpNbTable_data *);
int mtpNbTable_del(struct mtpNbTable_data **);
void parse_mtpNbTable(const char *, char *);
SNMPCallback store_mtpNbTable;
void refresh_mtpNbTable(void);
FindVarMethod var_mtpSaalTable;
int mtpSaalTable_add(struct mtpSaalTable_data *);
int mtpSaalTable_del(struct mtpSaalTable_data **);
void parse_mtpSaalTable(const char *, char *);
SNMPCallback store_mtpSaalTable;
void refresh_mtpSaalTable(void);
FindVarMethod var_mtpM2paTable;
int mtpM2paTable_add(struct mtpM2paTable_data *);
int mtpM2paTable_del(struct mtpM2paTable_data **);
void parse_mtpM2paTable(const char *, char *);
SNMPCallback store_mtpM2paTable;
void refresh_mtpM2paTable(void);
FindVarMethod var_mtpSdtTable;
int mtpSdtTable_add(struct mtpSdtTable_data *);
int mtpSdtTable_del(struct mtpSdtTable_data **);
void parse_mtpSdtTable(const char *, char *);
SNMPCallback store_mtpSdtTable;
void refresh_mtpSdtTable(void);
FindVarMethod var_mtpSdlTable;
int mtpSdlTable_add(struct mtpSdlTable_data *);
int mtpSdlTable_del(struct mtpSdlTable_data **);
void parse_mtpSdlTable(const char *, char *);
SNMPCallback store_mtpSdlTable;
void refresh_mtpSdlTable(void);

WriteMethod write_mtpSapUserPart;
WriteMethod write_mtpSapUserPartStatus;
WriteMethod write_mtpSapProviderEntityNames;
WriteMethod write_mtpSapAsaProfilePointer;
WriteMethod write_mtpSapName;
WriteMethod write_mtpSapLongMessageSupported;
WriteMethod write_mtpSapRowStatus;
WriteMethod write_mtpMsName;
WriteMethod write_mtpMsAlarmStatus;
WriteMethod write_mtpMsManagedElementType;
WriteMethod write_mtpMsModelCode;
WriteMethod write_mtpMsVendorName;
WriteMethod write_mtpMsUserLabel;
WriteMethod write_mtpMsVersion;
WriteMethod write_mtpMsAsaProfilePointer;
WriteMethod write_mtpMsNetworkElementAliases;
WriteMethod write_mtpMsStatus;
WriteMethod write_mtpNaProtocolVariant;
WriteMethod write_mtpNaProtocolYear;
WriteMethod write_mtpNaProtocolOptions;
WriteMethod write_mtpNaNetworkIndicator;
WriteMethod write_mtpNaPointCodeFormat;
WriteMethod write_mtpNaSlsLength;
WriteMethod write_mtpNaSpDefault;
WriteMethod write_mtpNaName;
WriteMethod write_mtpNaRowStatus;
WriteMethod write_mtpGsAdministrativeState;
WriteMethod write_mtpGsTreatmentOfOutsideRanges;
WriteMethod write_mtpGsListMode;
WriteMethod write_mtpGsScreeningByLinkSetOrByOpc;
WriteMethod write_mtpGsGetScreenedOpcsOrLinkSetsByDpc;
WriteMethod write_mtpGsName;
WriteMethod write_mtpGsRowStatus;
WriteMethod write_mtpGsLineObject;
WriteMethod write_mtpGsLineContent;
WriteMethod write_mtpGsLineRowStatus;
WriteMethod write_mtpGsLineContentDesignatedDPCFirst;
WriteMethod write_mtpGsLineContentDesignatedDPCLast;
WriteMethod write_mtpGsLineContentSiMask;
WriteMethod write_mtpGsLineContentMessageTreatment;
WriteMethod write_mtpGsLineContentComment;
WriteMethod write_mtpGsLineContentRowStatus;
WriteMethod write_mtpSpProfileTimerT1R;
WriteMethod write_mtpSpProfileTimerT2;
WriteMethod write_mtpSpProfileTimerT4;
WriteMethod write_mtpSpProfileTimerT5;
WriteMethod write_mtpSpProfileTimerT7;
WriteMethod write_mtpSpProfileTimerT11;
WriteMethod write_mtpSpProfileTimerT12;
WriteMethod write_mtpSpProfileTimerT13;
WriteMethod write_mtpSpProfileTimerT14;
WriteMethod write_mtpSpProfileTimerT15;
WriteMethod write_mtpSpProfileTimerT16;
WriteMethod write_mtpSpProfileTimerT18I;
WriteMethod write_mtpSpProfileTimerT19I;
WriteMethod write_mtpSpProfileTimerT20I;
WriteMethod write_mtpSpProfileTimerT21I;
WriteMethod write_mtpSpProfileTimerT22I;
WriteMethod write_mtpSpProfileTimerT23I;
WriteMethod write_mtpSpProfileTimerT20A;
WriteMethod write_mtpSpProfileTimerT21A;
WriteMethod write_mtpSpProfileTimerT22A;
WriteMethod write_mtpSpProfileTimerT23A;
WriteMethod write_mtpSpProfileTimerT24A;
WriteMethod write_mtpSpProfileTimerT26A;
WriteMethod write_mtpSpProfileTimerT27A;
WriteMethod write_mtpSpProfileTimerT1T;
WriteMethod write_mtpSpProfileTimerT2T;
WriteMethod write_mtpSpProfileName;
WriteMethod write_mtpSpProfileRowStatus;
WriteMethod write_mtpSpPointCode;
WriteMethod write_mtpSpType;
WriteMethod write_mtpSpVersion;
WriteMethod write_mtpSpNetworkIndicator;
WriteMethod write_mtpSpName;
WriteMethod write_mtpSpMtpT1;
WriteMethod write_mtpSpMtpT2;
WriteMethod write_mtpSpMtpT3;
WriteMethod write_mtpSpMtpT4;
WriteMethod write_mtpSpMtpT5;
WriteMethod write_mtpSpMtpT6;
WriteMethod write_mtpSpMtpT7;
WriteMethod write_mtpSpMtpT8;
WriteMethod write_mtpSpMtpT10;
WriteMethod write_mtpSpMtpT11;
WriteMethod write_mtpSpMtpT12;
WriteMethod write_mtpSpMtpT13;
WriteMethod write_mtpSpMtpT14;
WriteMethod write_mtpSpMtpT15;
WriteMethod write_mtpSpMtpT16;
WriteMethod write_mtpSpMtpT17;
WriteMethod write_mtpSpMtpT19A;
WriteMethod write_mtpSpMtpT31A;
WriteMethod write_mtpSpMtpT32A;
WriteMethod write_mtpSpMtpT33A;
WriteMethod write_mtpSpMtpT34A;
WriteMethod write_mtpSpMtpT18I;
WriteMethod write_mtpSpMtpT19I;
WriteMethod write_mtpSpMtpT20I;
WriteMethod write_mtpSpMtpT21I;
WriteMethod write_mtpSpMtpT22I;
WriteMethod write_mtpSpMtpT23I;
WriteMethod write_mtpSpMtpT20A;
WriteMethod write_mtpSpMtpT21A;
WriteMethod write_mtpSpMtpT24I;
WriteMethod write_mtpSpMtpT1T;
WriteMethod write_mtpSpMtpT2T;
WriteMethod write_mtpSpMtpT1S;
WriteMethod write_mtpSpProfilePointer;
WriteMethod write_mtpSpNaPointer;
WriteMethod write_mtpSpFlags;
WriteMethod write_mtpSpUsers;
WriteMethod write_mtpSpAlarmStatus;
WriteMethod write_mtpSpRowStatus;
WriteMethod write_mtpL3AdministrativeState;
WriteMethod write_mtpL3AsaProfilePointer;
WriteMethod write_mtpL3Name;
WriteMethod write_mtpL3RowStatus;
WriteMethod write_mtpRsProfileName;
WriteMethod write_mtpRsProfileTimerT8;
WriteMethod write_mtpRsProfileTimerT11;
WriteMethod write_mtpRsProfileTimerT15;
WriteMethod write_mtpRsProfileTimerT16;
WriteMethod write_mtpRsProfileTimerT18A;
WriteMethod write_mtpRsProfileRtDefault;
WriteMethod write_mtpRsProfileRowStatus;
WriteMethod write_mtpRsDest;
WriteMethod write_mtpRsFlags;
WriteMethod write_mtpRsAdministrativeState;
WriteMethod write_mtpRsAsaProfilePointer;
WriteMethod write_mtpRsLoadsharingInformation;
WriteMethod write_mtpRsLoadsharingObject;
WriteMethod write_mtpRsRemoteExchangeLabel;
WriteMethod write_mtpRsName;
WriteMethod write_mtpRsProfile;
WriteMethod write_mtpRsAlarmStatus;
WriteMethod write_mtpRsRowStatus;
WriteMethod write_mtpRtProfileTimerT6;
WriteMethod write_mtpRtProfileTimerT10;
WriteMethod write_mtpRtProfileRowStatus;
WriteMethod write_mtpRtLsPointer;
WriteMethod write_mtpRtAdministrativeState;
WriteMethod write_mtpRtInClsLoadsharingAlgorithm;
WriteMethod write_mtpRtFixedPriority;
WriteMethod write_mtpRtFlexiblePriority;
WriteMethod write_mtpRtPriorityMode;
WriteMethod write_mtpRtLoadsharingInformation;
WriteMethod write_mtpRtLoadsharingObject;
WriteMethod write_mtpRtName;
WriteMethod write_mtpRtSlsList;
WriteMethod write_mtpRtRlSlot;
WriteMethod write_mtpRtProfile;
WriteMethod write_mtpRtRowStatus;
WriteMethod write_mtpRtLsaNormalSlCode;
WriteMethod write_mtpRtLsaAlternativeSlCodeList;
WriteMethod write_mtpLsProfileTimerT6;
WriteMethod write_mtpLsProfileTimerT8;
WriteMethod write_mtpLsProfileTimerT10;
WriteMethod write_mtpLsProfileTimerT7;
WriteMethod write_mtpLsProfileTimerT19I;
WriteMethod write_mtpLsProfileTimerT21I;
WriteMethod write_mtpLsProfileTimerT25A;
WriteMethod write_mtpLsProfileTimerT28A;
WriteMethod write_mtpLsProfileTimerT29A;
WriteMethod write_mtpLsProfileTimerT30A;
WriteMethod write_mtpLsProfileName;
WriteMethod write_mtpLsProfileSlDefault;
WriteMethod write_mtpLsProfileRowStatus;
WriteMethod write_mtpLsAdjPc;
WriteMethod write_mtpLsRsId;
WriteMethod write_mtpLsMaxCapacity;
WriteMethod write_mtpLsCongestionControlMethod;
WriteMethod write_mtpLsPeriodicLinkTestFlag;
WriteMethod write_mtpLsPeriodicLinkTestFail;
WriteMethod write_mtpLsAdministrativeState;
WriteMethod write_mtpLsInLsLoadShareAlgorithm;
WriteMethod write_mtpLsProfilePointer;
WriteMethod write_mtpLsNumberOfNormallyActiveSignLinks;
WriteMethod write_mtpLsName;
WriteMethod write_mtpLsAsaProfilePointer;
WriteMethod write_mtpLsAlarmStatus;
WriteMethod write_mtpLsRowStatus;
WriteMethod write_mtpSlL3ProfileTimerT1;
WriteMethod write_mtpSlL3ProfileTimerT3;
WriteMethod write_mtpSlL3ProfileTimerT17;
WriteMethod write_mtpSlL3ProfileTimerT24I;
WriteMethod write_mtpSlL3ProfileName;
WriteMethod write_mtpSlL3ProfileTimerT2;
WriteMethod write_mtpSlL3ProfileTimerT4;
WriteMethod write_mtpSlL3ProfileTimerT5;
WriteMethod write_mtpSlL3ProfileTimerT12;
WriteMethod write_mtpSlL3ProfileTimerT13;
WriteMethod write_mtpSlL3ProfileTimerT14;
WriteMethod write_mtpSlL3ProfileTimerT19A;
WriteMethod write_mtpSlL3ProfileTimerT20A;
WriteMethod write_mtpSlL3ProfileTimerT21A;
WriteMethod write_mtpSlL3ProfileTimerT22I;
WriteMethod write_mtpSlL3ProfileTimerT23I;
WriteMethod write_mtpSlL3ProfileTimerT31A;
WriteMethod write_mtpSlL3ProfileTimerT32A;
WriteMethod write_mtpSlL3ProfileTimerT33A;
WriteMethod write_mtpSlL3ProfileTimerT34A;
WriteMethod write_mtpSlL3ProfileTimerT1T;
WriteMethod write_mtpSlL3ProfileTimerT2T;
WriteMethod write_mtpSlL3ProfileTimerT1S;
WriteMethod write_mtpSlL3ProfileL2Default;
WriteMethod write_mtpSlL3ProfileRowStatus;
WriteMethod write_mtpSlL2ProfileErrorCorrectionMethod;
WriteMethod write_mtpSlL2ProfileTransmissionRate;
WriteMethod write_mtpSlL2ProfileTimerT1;
WriteMethod write_mtpSlL2ProfileTimerT2;
WriteMethod write_mtpSlL2ProfileTimerT2L;
WriteMethod write_mtpSlL2ProfileTimerT2H;
WriteMethod write_mtpSlL2ProfileTimerT3;
WriteMethod write_mtpSlL2ProfileTimerT4N;
WriteMethod write_mtpSlL2ProfileTimerT4E;
WriteMethod write_mtpSlL2ProfileTimerT5;
WriteMethod write_mtpSlL2ProfileTimerT6;
WriteMethod write_mtpSlL2ProfileTimerT7;
WriteMethod write_mtpSlL2ProfileTbOnset1;
WriteMethod write_mtpSlL2ProfileTbAbate1;
WriteMethod write_mtpSlL2ProfileNumberOfThresholdLevels;
WriteMethod write_mtpSlL2ProfileCongestionCounting;
WriteMethod write_mtpSlL2ProfileCongestionReportingBaseObject;
WriteMethod write_mtpSlL2ProfileLoopDelay;
WriteMethod write_mtpSlL2ProfileName;
WriteMethod write_mtpSlL2ProfileTbOnset2;
WriteMethod write_mtpSlL2ProfileTbAbate2;
WriteMethod write_mtpSlL2ProfileTbOnset3;
WriteMethod write_mtpSlL2ProfileTbAbate3;
WriteMethod write_mtpSlL2ProfileTbDiscard1;
WriteMethod write_mtpSlL2ProfileTbDiscard2;
WriteMethod write_mtpSlL2ProfileTbDiscard3;
WriteMethod write_mtpSlL2ProfileTimerTx;
WriteMethod write_mtpSlL2ProfileTimerTy;
WriteMethod write_mtpSlL2ProfileNumberOfCongestionStates;
WriteMethod write_mtpSlL2ProfileInitialLevelOfCongestion;
WriteMethod write_mtpSlL2ProfileMaxMSUsRetransN1;
WriteMethod write_mtpSlL2ProfileMaxOctRetransN2;
WriteMethod write_mtpSlL2ProfileReceiveCongestionThresholdOnset;
WriteMethod write_mtpSlL2ProfileReceiveCongestionThresholdAbate;
WriteMethod write_mtpSlL2ProfileReceiveCongestionThresholdDiscard;
WriteMethod write_mtpSlL2ProfileM;
WriteMethod write_mtpSlL2ProfileRowStatus;
WriteMethod write_mtpSlSlsCodeCurrentList;
WriteMethod write_mtpSlMaxCapacitySL;
WriteMethod write_mtpSlAdministrativeState;
WriteMethod write_mtpSlMtpL2ProtocolProfilePointer;
WriteMethod write_mtpSlSignTermPointer;
WriteMethod write_mtpSlSignDataLinkTpPointer;
WriteMethod write_mtpSlLocalInhibit;
WriteMethod write_mtpSlLocalUninhibit;
WriteMethod write_mtpSlReplaceSt;
WriteMethod write_mtpSlAsaProfilePointer;
WriteMethod write_mtpSlRelatedLinkGroupNumber;
WriteMethod write_mtpSlSdlList;
WriteMethod write_mtpSlTest;
WriteMethod write_mtpSlName;
WriteMethod write_mtpSlSdtList;
WriteMethod write_mtpSlSlsCodeNormalList;
WriteMethod write_mtpSlL3ProfilePointer;
WriteMethod write_mtpSlAlarmStatus;
WriteMethod write_mtpSlRowStatus;
WriteMethod write_mtpSlSdlListPointer;
WriteMethod write_mtpSlSdlListRowStatus;
WriteMethod write_mtpSlSdtListPointer;
WriteMethod write_mtpSlSdtListRowStatus;
WriteMethod write_mtpNbTransmissionRate;
WriteMethod write_mtpNbTimerT8;
WriteMethod write_mtpNbTin;
WriteMethod write_mtpNbTie;
WriteMethod write_mtpNbT;
WriteMethod write_mtpNbD;
WriteMethod write_mtpNbTe;
WriteMethod write_mtpNbDe;
WriteMethod write_mtpNbUe;
WriteMethod write_mtpNbN;
WriteMethod write_mtpNbm;
WriteMethod write_mtpNbb;
WriteMethod write_mtpNbf;
WriteMethod write_mtpNbRowStatus;
WriteMethod write_mtpSaalBufferRelease;
WriteMethod write_mtpSaalMaxCc;
WriteMethod write_mtpSaalMaxNrp;
WriteMethod write_mtpSaalMaxInformationFieldLength;
WriteMethod write_mtpSaalMaxLengthSscopUuField;
WriteMethod write_mtpSaalMaxPd;
WriteMethod write_mtpSaalMaxSscopCreditToPeer;
WriteMethod write_mtpSaalMaxStat;
WriteMethod write_mtpSaalN1;
WriteMethod write_mtpSaalNniLayerManagementProvingState;
WriteMethod write_mtpSaalNniLayerManagementTimerNoCredit;
WriteMethod write_mtpSaalNniLayerManagementTimerRepeatSrec;
WriteMethod write_mtpSaalNniTimerT1;
WriteMethod write_mtpSaalNniTimerT2;
WriteMethod write_mtpSaalNniTimerT3;
WriteMethod write_mtpSaalSscopTimerCc;
WriteMethod write_mtpSaalSscopTimerIdle;
WriteMethod write_mtpSaalSscopTimerKeepAlive;
WriteMethod write_mtpSaalSscopTimerNoResponse;
WriteMethod write_mtpSaalSscopTimerPoll;
WriteMethod write_mtpSaalTransmissionRateIntervalLower;
WriteMethod write_mtpSaalTransmissionRateIntervalUpper;
WriteMethod write_mtpSaalEgressTransmissionRateIntervalLower;
WriteMethod write_mtpSaalEgressTransmissionRateIntervalUpper;
WriteMethod write_mtpSaalPollAfterRetransmission;
WriteMethod write_mtpSaalRowStatus;
WriteMethod write_mtpM2paN1;
WriteMethod write_mtpM2paProving;
WriteMethod write_mtpM2paManagementProvingState;
WriteMethod write_mtpM2paLoopDelayLower;
WriteMethod write_mtpM2paLoopDelayUpper;
WriteMethod write_mtpM2paTransmissionRateIntervalLower;
WriteMethod write_mtpM2paTransmissionRateIntervalUpper;
WriteMethod write_mtpM2paSctpNoDelay;
WriteMethod write_mtpM2paSctpMaxseg;
WriteMethod write_mtpM2paSctpHeartbeatItvl;
WriteMethod write_mtpM2paSctpHeartbeat;
WriteMethod write_mtpM2paSctpRtoInitial;
WriteMethod write_mtpM2paSctpRtoMin;
WriteMethod write_mtpM2paSctpRtoMax;
WriteMethod write_mtpM2paSctpPathMaxRetrans;
WriteMethod write_mtpM2paSctpCookieLife;
WriteMethod write_mtpM2paSctpCookieInc;
WriteMethod write_mtpM2paSctpMaxInitRetries;
WriteMethod write_mtpM2paSctpMaxBurst;
WriteMethod write_mtpM2paSctpAssocMaxRetrans;
WriteMethod write_mtpM2paSctpSackDelay;
WriteMethod write_mtpM2paSctpLifetime;
WriteMethod write_mtpM2paProvingAttempts;
WriteMethod write_mtpM2paRowStatus;
WriteMethod write_mtpSdtAdministrativeState;
WriteMethod write_mtpSdtEquipmentPointer;
WriteMethod write_mtpSdtName;
WriteMethod write_mtpSdtProfilePointer;
WriteMethod write_mtpSdtRowStatus;
WriteMethod write_mtpSdlAdjPc;
WriteMethod write_mtpSdlTransmissionRate;
WriteMethod write_mtpSdlLoopDelay;
WriteMethod write_mtpSdlOperationalState;
WriteMethod write_mtpSdlEquipmentPointer;
WriteMethod write_mtpSdlCIC;
WriteMethod write_mtpSdlName;
WriteMethod write_mtpSdlStmChannel;
WriteMethod write_mtpSdlVcTTpPointer;
WriteMethod write_mtpSdlRowStatus;
WriteMethod write_mtpM2paDefaultSctpNoDelay;
WriteMethod write_mtpM2paDefaultSctpMaxseg;
WriteMethod write_mtpM2paDefaultSctpHeartbeatItvl;
WriteMethod write_mtpM2paDefaultSctpHeartbeat;
WriteMethod write_mtpM2paDefaultSctpRtoInitial;
WriteMethod write_mtpM2paDefaultSctpRtoMin;
WriteMethod write_mtpM2paDefaultSctpRtoMax;
WriteMethod write_mtpM2paDefaultSctpPathMaxRetrans;
WriteMethod write_mtpM2paDefaultSctpCookieLife;
WriteMethod write_mtpM2paDefaultSctpCookieInc;
WriteMethod write_mtpM2paDefaultSctpMaxInitRetries;
WriteMethod write_mtpM2paDefaultSctpMaxBurst;
WriteMethod write_mtpM2paDefaultSctpAssocMaxRetrans;
WriteMethod write_mtpM2paDefaultSctpSackDelay;
WriteMethod write_mtpM2paDefaultSctpLifetime;
#endif				/* __LOCAL_MTPMIB_H__ */
