/*****************************************************************************

 @(#) $Id: mtpMIB2.h,v 0.9.2.2 2008-12-24 13:08:25 brian Exp $

 -----------------------------------------------------------------------------

 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; version 3 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 -----------------------------------------------------------------------------

 Last Modified $Date: 2008-12-24 13:08:25 $ by $Author: brian $

 -----------------------------------------------------------------------------

 $Log: mtpMIB2.h,v $
 Revision 0.9.2.2  2008-12-24 13:08:25  brian
 - building ss7confd

 *****************************************************************************/

#ifndef __LOCAL_MTPMIB2_H__
#define __LOCAL_MTPMIB2_H__

#ident "@(#) $RCSfile: mtpMIB2.h,v $ $Name:  $($Revision: 0.9.2.2 $) Copyright (c) 2001-2008 OpenSS7 Corporation."

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */
/* our storage structure(s) */
struct mtpMIB2_data {
	uint mtpMIB2_request;

	long mtpM2paDefaultSctpNoDelay;
	ulong mtpM2paDefaultSctpMaxseg;
	ulong mtpM2paDefaultSctpHeartbeatItvl;
	long mtpM2paDefaultSctpHeartbeat;
	ulong mtpM2paDefaultSctpRtoInitial;
	ulong mtpM2paDefaultSctpRtoMin;
	ulong mtpM2paDefaultSctpRtoMax;
	ulong mtpM2paDefaultSctpPathMaxRetrans;
	ulong mtpM2paDefaultSctpCookieLife;
	ulong mtpM2paDefaultSctpCookieInc;
	ulong mtpM2paDefaultSctpMaxInitRetries;
	ulong mtpM2paDefaultSctpMaxBurst;
	ulong mtpM2paDefaultSctpAssocMaxRetrans;
	ulong mtpM2paDefaultSctpSackDelay;
	ulong mtpM2paDefaultSctpLifetime;
};
struct mtpSapTable_data {
	uint mtpSapTable_request;
	ulong mtpSapId;
	ulong mtpSap2Address;
	long mtpSapUserPart;
	long mtpSapUserPartStatus;
	oid *mtpSapUserEntityNames;
	size_t mtpSapUserEntityNamesLen;
	oid *mtpSapProviderEntityNames;
	size_t mtpSapProviderEntityNamesLen;
	long mtpSapUsageState;
	oid *mtpSapAsaProfilePointer;
	size_t mtpSapAsaProfilePointerLen;
	char *mtpSapName;
	size_t mtpSapNameLen;
	long mtpSapLongMessageSupported;
	long mtpSapRowStatus;
};
struct ss7NetworkTable_data {
	uint ss7NetworkTable_request;
	ulong ss7NetworkId;
	long ss7NetworkProtocolStandard;
	ulong ss7NetworkProtocolYear;
	long ss7NetworkIndicator;
	long ss7NetworkPointCodeFormat;
	long ss7NetworkStatus;
};
struct mtpMsTable_data {
	uint mtpMsTable_request;
	ulong mtpMsId;
	char *mtpMsName;
	size_t mtpMsNameLen;
	char *mtpMsAlarmStatus;
	size_t mtpMsAlarmStatusLen;
	long mtpMsOperationalState;
	long mtpMsUsageState;
	char *mtpMsManagedElementType;
	size_t mtpMsManagedElementTypeLen;
	char *mtpMsModelCode;
	size_t mtpMsModelCodeLen;
	char *mtpMsVendorName;
	size_t mtpMsVendorNameLen;
	char *mtpMsUserLabel;
	size_t mtpMsUserLabelLen;
	char *mtpMsVersion;
	size_t mtpMsVersionLen;
	oid *mtpMsAsaProfilePointer;
	size_t mtpMsAsaProfilePointerLen;
	char *mtpMsNetworkElementAliases;
	size_t mtpMsNetworkElementAliasesLen;
	long mtpMsStatus;
};
struct mtpNaTable_data {
	uint mtpNaTable_request;
	long mtpNaId;
	oid *mtpNaProtocolVariant;
	size_t mtpNaProtocolVariantLen;
	long mtpNaProtocolYear;
	char *mtpNaProtocolOptions;
	size_t mtpNaProtocolOptionsLen;
	long mtpNaNetworkIndicator;
	char *mtpNaPointCodeFormat;
	size_t mtpNaPointCodeFormatLen;
	long mtpNaSlsLength;
	char *mtpNaSpDefault;
	size_t mtpNaSpDefaultLen;
	char *mtpNaName;
	size_t mtpNaNameLen;
	long mtpNaRowStatus;
};
struct mtpGsTable_data {
	uint mtpGsTable_request;
	ulong mtpSpId;
	ulong mtpGsId;
	long mtpGsAdministrativeState;
	long mtpGsTreatmentOfOutsideRanges;
	long mtpGsListMode;
	long mtpGsScreeningByLinkSetOrByOpc;
	long mtpGsGetScreenedOpcsOrLinkSetsByDpc;
	char *mtpGsName;
	size_t mtpGsNameLen;
	long mtpGsRowStatus;
};
struct mtpGsLineTable_data {
	uint mtpGsLineTable_request;
	ulong mtpSpId;
	ulong mtpGsId;
	ulong mtpGsLineId;
	oid *mtpGsLineObject;
	size_t mtpGsLineObjectLen;
	ulong mtpGsLineContent;
	long mtpGsLineRowStatus;
};
struct mtpGsLineContentTable_data {
	uint mtpGsLineContentTable_request;
	ulong mtpSpId;
	ulong mtpGsId;
	ulong mtpGsLineId;
	ulong mtpGsLineContentId;
	char *mtpGsLineContentDesignatedDPCFirst;
	size_t mtpGsLineContentDesignatedDPCFirstLen;
	char *mtpGsLineContentDesignatedDPCLast;
	size_t mtpGsLineContentDesignatedDPCLastLen;
	char *mtpGsLineContentSiMask;
	size_t mtpGsLineContentSiMaskLen;
	long mtpGsLineContentMessageTreatment;
	char *mtpGsLineContentComment;
	size_t mtpGsLineContentCommentLen;
	long mtpGsLineContentRowStatus;
};
struct mtpSpProfileTable_data {
	uint mtpSpProfileTable_request;
	char *mtpSpProfileId;
	size_t mtpSpProfileIdLen;
	long mtpSpProfileTimerT1R;
	long mtpSpProfileTimerT2;
	long mtpSpProfileTimerT4;
	long mtpSpProfileTimerT5;
	long mtpSpProfileTimerT7;
	long mtpSpProfileTimerT11;
	long mtpSpProfileTimerT12;
	long mtpSpProfileTimerT13;
	long mtpSpProfileTimerT14;
	long mtpSpProfileTimerT15;
	long mtpSpProfileTimerT16;
	long mtpSpProfileTimerT18I;
	long mtpSpProfileTimerT19I;
	long mtpSpProfileTimerT20I;
	long mtpSpProfileTimerT21I;
	long mtpSpProfileTimerT22I;
	long mtpSpProfileTimerT23I;
	long mtpSpProfileTimerT20A;
	long mtpSpProfileTimerT21A;
	long mtpSpProfileTimerT22A;
	long mtpSpProfileTimerT23A;
	long mtpSpProfileTimerT24A;
	long mtpSpProfileTimerT26A;
	long mtpSpProfileTimerT27A;
	long mtpSpProfileTimerT1T;
	long mtpSpProfileTimerT2T;
	char *mtpSpProfileName;
	size_t mtpSpProfileNameLen;
	char *mtpSpRsDefault;
	size_t mtpSpRsDefaultLen;
	char *mtpSpLsDefault;
	size_t mtpSpLsDefaultLen;
	long mtpSpProfileRowStatus;
};
struct mtpSpTable_data {
	uint mtpSpTable_request;
	ulong mtpMsId;
	ulong mtpSpId;
	char *mtpSpPointCode;
	size_t mtpSpPointCodeLen;
	long mtpSpType;
	long mtpSpOperationalState;
	char *mtpSpProceduralStatus;
	size_t mtpSpProceduralStatusLen;
	char *mtpSpAvailabilityStatus;
	size_t mtpSpAvailabilityStatusLen;
	char *mtpSpVersion;
	size_t mtpSpVersionLen;
	long mtpSpNetworkIndicator;
	char *mtpSpName;
	size_t mtpSpNameLen;
	long mtpSpMtpT1;
	long mtpSpMtpT2;
	long mtpSpMtpT3;
	long mtpSpMtpT4;
	long mtpSpMtpT5;
	long mtpSpMtpT6;
	long mtpSpMtpT7;
	long mtpSpMtpT8;
	long mtpSpMtpT10;
	long mtpSpMtpT11;
	long mtpSpMtpT12;
	long mtpSpMtpT13;
	long mtpSpMtpT14;
	long mtpSpMtpT15;
	long mtpSpMtpT16;
	long mtpSpMtpT17;
	long mtpSpMtpT19A;
	long mtpSpMtpT31A;
	long mtpSpMtpT32A;
	long mtpSpMtpT33A;
	long mtpSpMtpT34A;
	long mtpSpMtpT18I;
	long mtpSpMtpT19I;
	long mtpSpMtpT20I;
	long mtpSpMtpT21I;
	long mtpSpMtpT22I;
	long mtpSpMtpT23I;
	long mtpSpMtpT20A;
	long mtpSpMtpT21A;
	long mtpSpMtpT24I;
	long mtpSpMtpT1T;
	long mtpSpMtpT2T;
	long mtpSpMtpT1S;
	char *mtpSpProfilePointer;
	size_t mtpSpProfilePointerLen;
	char *mtpSpNaPointer;
	size_t mtpSpNaPointerLen;
	char *mtpSpFlags;
	size_t mtpSpFlagsLen;
	char *mtpSpUsers;
	size_t mtpSpUsersLen;
	char *mtpSpAlarmStatus;
	size_t mtpSpAlarmStatusLen;
	long mtpSpRowStatus;
};
struct mtpSpStatsTable_data {
	uint mtpSpStatsTable_request;
	ulong mtpMsId;
	ulong mtpSpId;
	long mtpSpStatsRowStatus;
};
struct mtpSpCurrentTable_data {
	uint mtpSpCurrentTable_request;
	ulong mtpSpId;
	long mtpSpCurrentValidIntervals;
	long mtpSpCurrentTimeDiscontinuity;
	long mtpSpCurrentDiscardedMSUs;
	long mtpSpCurrentReceivedTFCstatus0;
	long mtpSpCurrentReceivedTFCstatus1;
	long mtpSpCurrentReceivedTFCstatus2;
	long mtpSpCurrentOctetsXferred;
};
struct mtpSpInt5minTable_data {
	uint mtpSpInt5minTable_request;
	ulong mtpSpId;
	ulong mtpSpInt5minInterval;
	long mtpSpInt5minTimeStamp;
	long mtpSpInt5minDiscardedMSUs;
	long mtpSpInt5minReceivedTFCstatus0;
	long mtpSpInt5minReceivedTFCstatus1;
	long mtpSpInt5minReceivedTFCstatus2;
	long mtpSpInt5minOctetsXferred;
};
struct mtpSpInt15minTable_data {
	uint mtpSpInt15minTable_request;
	ulong mtpSpId;
	ulong mtpSpInt15minInterval;
	long mtpSpInt15minTimeStamp;
	long mtpSpInt15minDiscardedMSUs;
	long mtpSpInt15minReceivedTFCstatus0;
	long mtpSpInt15minReceivedTFCstatus1;
	long mtpSpInt15minReceivedTFCstatus2;
	long mtpSpInt15minOctetsXferred;
};
struct mtpSpSiTable_data {
	uint mtpSpSiTable_request;
	ulong mtpSpId;
	ulong mtpSpSiCode;
	long mtpSpSiValidIntervals;
	long mtpSpSiTimeDiscontinuity;
	long mtpSpSiTransmittedUPUnavailable;
	long mtpSpSiReceivedUPUnavailable;
	long mtpSpSiHandledOctetsSIO;
	long mtpSpSiStatus;
};
struct mtpSpSiInt5minTable_data {
	uint mtpSpSiInt5minTable_request;
	ulong mtpSpId;
	ulong mtpSpSiCode;
	ulong mtpSpSiInt5minInterval;
	long mtpSpSiInt5minTimeStamp;
	long mtpSpSiInt5minTransmittedUPUnavailable;
	long mtpSpSiInt5minReceivedUPUnavailable;
	long mtpSpSiInt5minHandledOctetsSIO;
};
struct mtpSpSiInt15minTable_data {
	uint mtpSpSiInt15minTable_request;
	ulong mtpSpId;
	ulong mtpSpSiCode;
	ulong mtpSpSiInt15minInterval;
	long mtpSpSiInt15minTimeStamp;
	long mtpSpSiInt15minTransmittedUPUnavailable;
	long mtpSpSiInt15minReceivedUPUnavailable;
	long mtpSpSiInt15minHandledOctetsSIO;
};
struct mtpSpStudyTable_data {
	uint mtpSpStudyTable_request;
	ulong mtpSpStudyId;
	long mtpSpStudyValidIntervals;
	long mtpSpStudyTimeDiscontinuity;
	long mtpSpStudyHandledOctetsOpcDpcSio;
	long mtpSpStudyHandledMSUsOpcDpcSio;
	long mtpSpStudyStatus;
};
struct mtpSpStudyInt5minTable_data {
	uint mtpSpStudyInt5minTable_request;
	ulong mtpSpStudyId;
	ulong mtpSpStudyInt5minInterval;
	long mtpSpStudyInt5minTimeStamp;
	long mtpSpStudyInt5minHandledOctetsOpcDpcSio;
	long mtpSpStudyInt5minHandledMSUsOpcDpcSio;
};
struct mtpSpStudyInt15minTable_data {
	uint mtpSpStudyInt15minTable_request;
	ulong mtpSpStudyId;
	ulong mtpSpStudyInt15minInterval;
	long mtpSpStudyInt15minInterval;
	long mtpSpStudyInt15minHandledOctetsOpcDpcSio;
	long mtpSpStudyInt15minHandledMSUsOpcDpcSio;
};
struct mtpSpStudyMapTable_data {
	uint mtpSpStudyMapTable_request;
	ulong mtpSpId;
	ulong mtpRsId;
	ulong mtpRsId;
	ulong mtpSpSiCode;
	ulong mtpSpStudyId;
	long mtpSpStudyMapStatus;
};
struct mtpL3Table_data {
	uint mtpL3Table_request;
	char *mtpL3Id;
	size_t mtpL3IdLen;
	long mtpL3AdministrativeState;
	long mtpL3OperationalState;
	long mtpL3UsageState;
	char *mtpL3ProceduralStatus;
	size_t mtpL3ProceduralStatusLen;
	oid *mtpL3AsaProfilePointer;
	size_t mtpL3AsaProfilePointerLen;
	char *mtpL3Name;
	size_t mtpL3NameLen;
	long mtpL3RowStatus;
};
struct mtpRsProfileTable_data {
	uint mtpRsProfileTable_request;
	char *mtpRsProfileId;
	size_t mtpRsProfileIdLen;
	char *mtpRsProfileName;
	size_t mtpRsProfileNameLen;
	long mtpRsProfileTimerT8;
	long mtpRsProfileTimerT11;
	long mtpRsProfileTimerT15;
	long mtpRsProfileTimerT16;
	long mtpRsProfileTimerT18A;
	char *mtpRsProfileRtDefault;
	size_t mtpRsProfileRtDefaultLen;
	long mtpRsProfileRowStatus;
};
struct mtpRsTable_data {
	uint mtpRsTable_request;
	ulong mtpSpId;
	ulong mtpRsId;
	char *mtpRsDest;
	size_t mtpRsDestLen;
	char *mtpRsFlags;
	size_t mtpRsFlagsLen;
	long mtpRsAdministrativeState;
	long mtpRsOperationalState;
	oid *mtpRsAsaProfilePointer;
	size_t mtpRsAsaProfilePointerLen;
	long mtpRsCongestedState;
	long mtpRsCongestionLevel;
	char *mtpRsLoadsharingInformation;
	size_t mtpRsLoadsharingInformationLen;
	oid *mtpRsLoadsharingObject;
	size_t mtpRsLoadsharingObjectLen;
	char *mtpRsRemoteExchangeLabel;
	size_t mtpRsRemoteExchangeLabelLen;
	char *mtpRsName;
	size_t mtpRsNameLen;
	char *mtpRsProfile;
	size_t mtpRsProfileLen;
	char *mtpRsAlarmStatus;
	size_t mtpRsAlarmStatusLen;
	long mtpRsRowStatus;
};
struct mtpRsStatsTable_data {
	uint mtpRsStatsTable_request;
	ulong mtpSpId;
	ulong mtpRsId;
	long mtpRsStatsStatus;
};
struct mtpRsCurrentTable_data {
	uint mtpRsCurrentTable_request;
	ulong mtpRsId;
	long mtpRsCurrentValidIntervals;
	long mtpRsCurrentTimeDiscontinuity;
	long mtpRsCurrentReceivedOctetsOPC;
	long mtpRsCurrentTransmittedOctetsDPC;
	long mtpRsCurrentReceivedMSUsOpc;
	long mtpRsCurrentTransmittedMSUsDpc;
	long mtpRsCurrentRouteSetUnavailable;
	long mtpRsCurrentRouteSetUnavailableDuration;
};
struct mtpRsInt5minTable_data {
	uint mtpRsInt5minTable_request;
	ulong mtpRsId;
	ulong mtpRsInt5minInterval;
	long mtpRsInt5minTimeStamp;
	long mtpRsInt5minReceivedOctetsOPC;
	long mtpRsInt5minTransmittedOctetsDPC;
	long mtpRsInt5minReceivedMSUsOpc;
	long mtpRsInt5minTransmittedMSUsDpc;
	long mtpRsInt5minRouteSetUnavailable;
	long mtpRsInt5minRouteSetUnavailableDuration;
};
struct mtpRsInt15minTable_data {
	uint mtpRsInt15minTable_request;
	ulong mtpRsId;
	ulong mtpRsInt15minInterval;
	long mtpRsInt15minTimeStamp;
	long mtpRsInt15minReceivedOctetsOPC;
	long mtpRsInt15minTransmittedOctetsDPC;
	long mtpRsInt15minReceivedMSUsOpc;
	long mtpRsInt15minTransmittedMSUsDpc;
	long mtpRsInt15minRouteSetUnavailable;
	long mtpRsInt15minRouteSetUnavailableDuration;
};
struct mtpRsSiTable_data {
	uint mtpRsSiTable_request;
	ulong mtpRsSiCode;
	long mtpRsSiValidIntervals;
	long mtpRsSiTimeDiscontinuity;
	long mtpRsSiReceivedOctetsOpcSio;
	long mtpRsSiTransmittedOctetsDpcSio;
	long mtpRsSiReceivedMSUsOpcSio;
	long mtpRsSiTransmittedMSUsDpcSio;
	long mtpRsSiStatus;
};
struct mtpRsSiInt5minTable_data {
	uint mtpRsSiInt5minTable_request;
	ulong mtpRsSiCode;
	ulong mtpRsSiInt5minInterval;
	long mtpRsSiInt5minTimeStamp;
	long mtpRsSiInt5minTimeStamp;
	long mtpRsSiInt5minTransmittedOctetsDpcSio;
	long mtpRsSiInt5minReceivedMSUsOpcSio;
	long mtpRsSiInt5minTransmittedMSUsDpcSio;
};
struct mtpRsSiInt15minTable_data {
	uint mtpRsSiInt15minTable_request;
	ulong mtpRsSiCode;
	ulong mtpRsSiInt15minInterval;
	long mtpRsSiInt15minTimeStamp;
	long mtpRsSiInt15minReceivedOctetsOpcSio;
	long mtpRsSiInt15minTransmittedOctetsDpcSio;
	long mtpRsSiInt15minReceivedMSUsOpcSio;
	long mtpRsSiInt15minTransmittedMSUsDpcSio;
};
struct mtpRtProfileTable_data {
	uint mtpRtProfileTable_request;
	char *mtpRtProfileId;
	size_t mtpRtProfileIdLen;
	long mtpRtProfileTimerT6;
	long mtpRtProfileTimerT10;
	long mtpRtProfileRowStatus;
};
struct mtpRtTable_data {
	uint mtpRtTable_request;
	ulong mtpSpId;
	ulong mtpRsId;
	ulong mtpRtId;
	char *mtpRtLsPointer;
	size_t mtpRtLsPointerLen;
	long mtpRtAdministrativeState;
	long mtpRtOperationalState;
	char *mtpRtAvailabilityStatus;
	size_t mtpRtAvailabilityStatusLen;
	ulong mtpRtInClsLoadsharingAlgorithm;
	ulong mtpRtFixedPriority;
	ulong mtpRtFlexiblePriority;
	long mtpRtPriorityMode;
	char *mtpRtLoadsharingInformation;
	size_t mtpRtLoadsharingInformationLen;
	oid *mtpRtLoadsharingObject;
	size_t mtpRtLoadsharingObjectLen;
	char *mtpRtName;
	size_t mtpRtNameLen;
	char *mtpRtSlsList;
	size_t mtpRtSlsListLen;
	long mtpRtUsageState;
	ulong mtpRtRlSlot;
	char *mtpRtProfile;
	size_t mtpRtProfileLen;
	long mtpRtRowStatus;
};
struct mtpRtLsaTable_data {
	uint mtpRtLsaTable_request;
	ulong mtpSpId;
	ulong mtpRsId;
	ulong mtpRtId;
	ulong mtpRtLsaSlsCode;
	ulong mtpRtLsaNormalSlCode;
	char *mtpRtLsaAlternativeSlCodeList;
	size_t mtpRtLsaAlternativeSlCodeListLen;
};
struct mtpLsProfileTable_data {
	uint mtpLsProfileTable_request;
	char *mtpLsProfileId;
	size_t mtpLsProfileIdLen;
	long mtpLsProfileTimerT6;
	long mtpLsProfileTimerT8;
	long mtpLsProfileTimerT10;
	long mtpLsProfileTimerT7;
	long mtpLsProfileTimerT19I;
	long mtpLsProfileTimerT21I;
	long mtpLsProfileTimerT25A;
	long mtpLsProfileTimerT28A;
	long mtpLsProfileTimerT29A;
	long mtpLsProfileTimerT30A;
	char *mtpLsProfileName;
	size_t mtpLsProfileNameLen;
	char *mtpLsProfileSlDefault;
	size_t mtpLsProfileSlDefaultLen;
	long mtpLsProfileRowStatus;
};
struct mtpLsTable_data {
	uint mtpLsTable_request;
	ulong mtpSpId;
	ulong mtpLsId;
	char *mtpLsAdjPc;
	size_t mtpLsAdjPcLen;
	char *mtpLsRsId;
	size_t mtpLsRsIdLen;
	ulong mtpLsMaxCapacity;
	ulong mtpLsCurrentCapacity;
	long mtpLsCongestionControlMethod;
	long mtpLsUsageState;
	long mtpLsOperationalState;
	char *mtpLsAvailabilityStatus;
	size_t mtpLsAvailabilityStatusLen;
	long mtpLsPeriodicLinkTestFlag;
	long mtpLsPeriodicLinkTestFail;
	long mtpLsAdministrativeState;
	oid *mtpLsInLsLoadShareAlgorithm;
	size_t mtpLsInLsLoadShareAlgorithmLen;
	char *mtpLsProfilePointer;
	size_t mtpLsProfilePointerLen;
	ulong mtpLsNumberOfNormallyActiveSignLinks;
	char *mtpLsName;
	size_t mtpLsNameLen;
	oid *mtpLsAsaProfilePointer;
	size_t mtpLsAsaProfilePointerLen;
	char *mtpLsAlarmStatus;
	size_t mtpLsAlarmStatusLen;
	long mtpLsRowStatus;
};
struct mtpLsStatsTable_data {
	uint mtpLsStatsTable_request;
	ulong mtpSpId;
	ulong mtpLsId;
	long mtpLsStatsStatus;
};
struct mtpLsCurrentTable_data {
	uint mtpLsCurrentTable_request;
	ulong mtpLsId;
	long mtpLsCurrentValidIntervals;
	long mtpLsCurrentTimeDiscontinuity;
	long mtpLsCurrentAdjacentInaccessibleEvents;
	long mtpLsCurrentAdjacentInaccessibleDuration;
	long mtpLsCurrentSlsUnavailable;
};
struct mtpLsInt5minTable_data {
	uint mtpLsInt5minTable_request;
	ulong mtpLsId;
	ulong mtpLsInt5minInterval;
	ulong mtpLsInt5minInterval;
	ulong mtpLsInt5minInterval;
	ulong mtpLsInt5minInterval;
	ulong mtpLsInt5minInterval;
};
struct mtpLsInt15minTable_data {
	uint mtpLsInt15minTable_request;
	ulong mtpLsId;
	ulong mtpLsInt15minInterval;
	long mtpLsInt15minTimeStamp;
	long mtpLsInt15minAdjacentInaccessibleEvents;
	long mtpLsInt15minAdjacentInaccessibleDuration;
	long mtpLsInt15minSlsUnavailable;
};
struct mtpSlL3ProfileTable_data {
	uint mtpSlL3ProfileTable_request;
	char *mtpSlL3ProfileId;
	size_t mtpSlL3ProfileIdLen;
	long mtpSlL3ProfileTimerT1;
	long mtpSlL3ProfileTimerT3;
	long mtpSlL3ProfileTimerT17;
	long mtpSlL3ProfileTimerT24I;
	char *mtpSlL3ProfileName;
	size_t mtpSlL3ProfileNameLen;
	long mtpSlL3ProfileTimerT2;
	long mtpSlL3ProfileTimerT4;
	long mtpSlL3ProfileTimerT5;
	long mtpSlL3ProfileTimerT12;
	long mtpSlL3ProfileTimerT13;
	long mtpSlL3ProfileTimerT14;
	long mtpSlL3ProfileTimerT19A;
	long mtpSlL3ProfileTimerT20A;
	long mtpSlL3ProfileTimerT21A;
	long mtpSlL3ProfileTimerT22I;
	long mtpSlL3ProfileTimerT23I;
	long mtpSlL3ProfileTimerT31A;
	long mtpSlL3ProfileTimerT32A;
	long mtpSlL3ProfileTimerT33A;
	long mtpSlL3ProfileTimerT34A;
	long mtpSlL3ProfileTimerT1T;
	long mtpSlL3ProfileTimerT2T;
	long mtpSlL3ProfileTimerT1S;
	char *mtpSlL3ProfileL2Default;
	size_t mtpSlL3ProfileL2DefaultLen;
	long mtpSlL3ProfileRowStatus;
};
struct mtpSlL2ProfileTable_data {
	uint mtpSlL2ProfileTable_request;
	char *mtpSlL2ProfileId;
	size_t mtpSlL2ProfileIdLen;
	long mtpSlL2ProfileErrorCorrectionMethod;
	long mtpSlL2ProfileTransmissionRate;
	long mtpSlL2ProfileTimerT1;
	long mtpSlL2ProfileTimerT2;
	long mtpSlL2ProfileTimerT2L;
	long mtpSlL2ProfileTimerT2H;
	long mtpSlL2ProfileTimerT3;
	long mtpSlL2ProfileTimerT4N;
	long mtpSlL2ProfileTimerT4E;
	long mtpSlL2ProfileTimerT5;
	long mtpSlL2ProfileTimerT6;
	long mtpSlL2ProfileTimerT7;
	ulong mtpSlL2ProfileTbOnset1;
	ulong mtpSlL2ProfileTbAbate1;
	ulong mtpSlL2ProfileNumberOfThresholdLevels;
	long mtpSlL2ProfileCongestionCounting;
	long mtpSlL2ProfileCongestionReportingBaseObject;
	ulong mtpSlL2ProfileLoopDelay;
	char *mtpSlL2ProfileName;
	size_t mtpSlL2ProfileNameLen;
	ulong mtpSlL2ProfileTbOnset2;
	ulong mtpSlL2ProfileTbAbate2;
	ulong mtpSlL2ProfileTbOnset3;
	ulong mtpSlL2ProfileTbAbate3;
	ulong mtpSlL2ProfileTbDiscard1;
	ulong mtpSlL2ProfileTbDiscard2;
	ulong mtpSlL2ProfileTbDiscard3;
	long mtpSlL2ProfileTimerTx;
	long mtpSlL2ProfileTimerTy;
	ulong mtpSlL2ProfileNumberOfCongestionStates;
	ulong mtpSlL2ProfileInitialLevelOfCongestion;
	ulong mtpSlL2ProfileMaxMSUsRetransN1;
	ulong mtpSlL2ProfileMaxOctRetransN2;
	ulong mtpSlL2ProfileReceiveCongestionThresholdOnset;
	ulong mtpSlL2ProfileReceiveCongestionThresholdAbate;
	ulong mtpSlL2ProfileReceiveCongestionThresholdDiscard;
	ulong mtpSlL2ProfileM;
	long mtpSlL2ProfileRowStatus;
};
struct mtpSlTable_data {
	uint mtpSlTable_request;
	ulong mtpSpId;
	ulong mtpLsId;
	ulong mtpSlSlCode;
	char *mtpSlSlsCodeCurrentList;
	size_t mtpSlSlsCodeCurrentListLen;
	ulong mtpSlMaxCapacitySL;
	ulong mtpSlCurrentCapacitySL;
	char *mtpSlLinkTpStatus;
	size_t mtpSlLinkTpStatusLen;
	long mtpSlAdministrativeState;
	long mtpSlOperationalState;
	long mtpSlUsageState;
	char *mtpSlProceduralStatus;
	size_t mtpSlProceduralStatusLen;
	char *mtpSlMtpL2ProtocolProfilePointer;
	size_t mtpSlMtpL2ProtocolProfilePointerLen;
	oid *mtpSlSignTermPointer;
	size_t mtpSlSignTermPointerLen;
	oid *mtpSlSignDataLinkTpPointer;
	size_t mtpSlSignDataLinkTpPointerLen;
	long mtpSlLocalInhibit;
	long mtpSlLocalUninhibit;
	long mtpSlReplaceSt;
	oid *mtpSlAsaProfilePointer;
	size_t mtpSlAsaProfilePointerLen;
	long mtpSlCongestionLevel;
	ulong mtpSlRelatedLinkGroupNumber;
	ulong mtpSlSdlList;
	long mtpSlTest;
	char *mtpSlName;
	size_t mtpSlNameLen;
	ulong mtpSlSdtList;
	char *mtpSlSlsCodeNormalList;
	size_t mtpSlSlsCodeNormalListLen;
	char *mtpSlL3ProfilePointer;
	size_t mtpSlL3ProfilePointerLen;
	char *mtpSlAlarmStatus;
	size_t mtpSlAlarmStatusLen;
	long mtpSlRowStatus;
};
struct mtpSlSdlListTable_data {
	uint mtpSlSdlListTable_request;
	ulong mtpSpId;
	ulong mtpLsId;
	ulong mtpSlSlCode;
	ulong mtpSlSdlListId;
	oid *mtpSlSdlListPointer;
	size_t mtpSlSdlListPointerLen;
	long mtpSlSdlListRowStatus;
};
struct mtpSlSdtListTable_data {
	uint mtpSlSdtListTable_request;
	ulong mtpSpId;
	ulong mtpLsId;
	ulong mtpSlSlCode;
	ulong mtpSlSdtListId;
	oid *mtpSlSdtListPointer;
	size_t mtpSlSdtListPointerLen;
	long mtpSlSdtListRowStatus;
};
struct mtpSlStatsTable_data {
	uint mtpSlStatsTable_request;
	ulong mtpSpId;
	ulong mtpLsId;
	ulong mtpSlSlCode;
	long mtpSlStatsDurInService;
	long mtpSlStatsFailAlignOrProving;
	long mtpSlStatsNacksReceived;
	long mtpSlStatsDurUnavail;
	long mtpSlStatsDurUnavailFailed;
	long mtpSlStatsDurUnavailRpo;
	long mtpSlStatsSibsSent;
	long mtpSlStatsTranSioSifOctets;
	long mtpSlStatsRetransOctets;
	long mtpSlStatsTranMsus;
	long mtpSlStatsRecvSioSifOctets;
	long mtpSlStatsRecvMsus;
	long mtpSlStatsCongOnsetInd0;
	long mtpSlStatsCongOnsetInd1;
	long mtpSlStatsCongOnsetInd2;
	long mtpSlStatsCongOnsetInd3;
	long mtpSlStatsDurCongStatus0;
	long mtpSlStatsDurCongStatus1;
	long mtpSlStatsDurCongStatus2;
	long mtpSlStatsDurCongStatus3;
	long mtpSlStatsCongDiscdInd0;
	long mtpSlStatsCongDiscdInd1;
	long mtpSlStatsCongDiscdInd2;
	long mtpSlStatsCongDiscdInd3;
};
struct mtpSlL3CurrentTable_data {
	uint mtpSlL3CurrentTable_request;
	ulong mtpSpId;
	ulong mtpLsId;
	ulong mtpSlSlCode;
	long mtpSlL3CurrentValidIntervals;
	long mtpSlL3CurrentTimeDiscontinuity;
	long mtpSlL3CurrentSlUnavailabilityDuration;
	long mtpSlL3CurrentSlLocalInhibition;
	long mtpSlL3CurrentSlRemoteInhibition;
	long mtpSlL3CurrentSlFailed;
	long mtpSlL3CurrentSlRemoteProcOutage;
	long mtpSlL3CurrentLocalMgmtInhibit;
	long mtpSlL3CurrentLocalMgmtUninhibit;
	long mtpSlL3CurrentLocalBusy;
	long mtpSlL3CurrentSlCongestedStarts;
	long mtpSlL3CurrentSlCongestedDuration;
	long mtpSlL3CurrentSlCongestionStops;
	long mtpSlL3CurrentDiscardedMSUs;
	long mtpSlL3CurrentCongestionEventsMSULoss;
	long mtpSlL3CurrentChangeovers;
	long mtpSlL3CurrentChangebacks;
	long mtpSlL3CurrentRestorations;
};
struct mtpSlL3Int5minTable_data {
	uint mtpSlL3Int5minTable_request;
	ulong mtpSpId;
	ulong mtpLsId;
	ulong mtpSlSlCode;
	ulong mtpSlL3Int5minInterval;
	long mtpSlL3Int5minTimeStamp;
	long mtpSlL3Int5minSlUnavailabilityDuration;
	long mtpSlL3Int5minSlLocalInhibition;
	long mtpSlL3Int5minSlRemoteInhibition;
	long mtpSlL3Int5minSlFailed;
	long mtpSlL3Int5minSlRemoteProcOutage;
	long mtpSlL3Int5minLocalMgmtInhibit;
	long mtpSlL3Int5minLocalMgmtUninhibit;
	long mtpSlL3Int5minLocalBusy;
	long mtpSlL3Int5minSlCongestedStarts;
	long mtpSlL3Int5minSlCongestedDuration;
	long mtpSlL3Int5minSlCongestionStops;
	long mtpSlL3Int5minDiscardedMSUs;
	long mtpSlL3Int5minCongestionEventsMSULoss;
	long mtpSlL3Int5minChangeovers;
	long mtpSlL3Int5minChangebacks;
	long mtpSlL3Int5minRestorations;
};
struct mtpSlL3Int15minTable_data {
	uint mtpSlL3Int15minTable_request;
	ulong mtpSpId;
	ulong mtpLsId;
	ulong mtpSlSlCode;
	ulong mtpSlL3Int15minInterval;
	long mtpSlL3Int15minTimeStamp;
	long mtpSlL3Int15minSlUnavailabilityDuration;
	long mtpSlL3Int15minSlLocalInhibition;
	long mtpSlL3Int15minSlRemoteInhibition;
	long mtpSlL3Int15minSlFailed;
	long mtpSlL3Int15minSlRemoteProcOutage;
	long mtpSlL3Int15minLocalMgmtInhibit;
	long mtpSlL3Int15minLocalMgmtUninhibit;
	long mtpSlL3Int15minLocalBusy;
	long mtpSlL3Int15minSlCongestedStarts;
	long mtpSlL3Int15minSlCongestedDuration;
	long mtpSlL3Int15minSlCongestionStops;
	long mtpSlL3Int15minDiscardedMSUs;
	long mtpSlL3Int15minCongestionEventsMSULoss;
	long mtpSlL3Int15minChangeovers;
	long mtpSlL3Int15minChangebacks;
	long mtpSlL3Int15minRestorations;
};
struct mtpSlL2CurrentTable_data {
	uint mtpSlL2CurrentTable_request;
	ulong mtpSpId;
	ulong mtpLsId;
	ulong mtpSlSlCode;
	long mtpSlL2CurrentValidIntervals;
	long mtpSlL2CurrentTimeDiscontinuity;
	long mtpSlL2CurrentSlInServiceDuration;
	long mtpSlL2CurrentSlAlignment;
	long mtpSlL2CurrentSignUnitsReceived;
	long mtpSlL2CurrentNegAckReceived;
	long mtpSlL2CurrentTransmittedOctetsSIFSIO;
	long mtpSlL2CurrentRetransmittedOctets;
	long mtpSlL2CurrentTransmittedMSUs;
	long mtpSlL2CurrentReceivedOctetsSIFSIO;
	long mtpSlL2CurrentReceivedMSUs;
};
struct mtpSlL2Int5minTable_data {
	uint mtpSlL2Int5minTable_request;
	ulong mtpSpId;
	ulong mtpLsId;
	ulong mtpSlSlCode;
	ulong mtpSlL2Int5minInterval;
	long mtpSlL2Int5minTimestamp;
	long mtpSlL2Int5minSlInServiceDuration;
	long mtpSlL2Int5minSlAlignment;
	long mtpSlL2Int5minSignUnitsReceived;
	long mtpSlL2Int5minNegAckReceived;
	long mtpSlL2Int5minTransmittedOctetsSIFSIO;
	long mtpSlL2Int5minRetransmittedOctets;
	long mtpSlL2Int5minTransmittedMSUs;
	long mtpSlL2Int5minReceivedOctetsSIFSIO;
	long mtpSlL2Int5minReceivedMSUs;
};
struct mtpSlL2Int15minTable_data {
	uint mtpSlL2Int15minTable_request;
	ulong mtpSpId;
	ulong mtpLsId;
	ulong mtpSlSlCode;
	ulong mtpSlL2Int15minInterval;
	long mtpSlL2Int15minTimestamp;
	long mtpSlL2Int15minSlInServiceDuration;
	long mtpSlL2Int15minSlAlignment;
	long mtpSlL2Int15minSignUnitsReceived;
	long mtpSlL2Int15minNegAckReceived;
	long mtpSlL2Int15minTransmittedOctetsSIFSIO;
	long mtpSlL2Int15minRetransmittedOctets;
	long mtpSlL2Int15minTransmittedMSUs;
	long mtpSlL2Int15minReceivedOctetsSIFSIO;
	long mtpSlL2Int15minReceivedMSUs;
};
struct mtpNbTable_data {
	uint mtpNbTable_request;
	char *mtpSdtProfileId;
	size_t mtpSdtProfileIdLen;
	long mtpNbTransmissionRate;
	ulong mtpNbTimerT8;
	ulong mtpNbTin;
	ulong mtpNbTie;
	ulong mtpNbT;
	ulong mtpNbD;
	ulong mtpNbTe;
	ulong mtpNbDe;
	ulong mtpNbUe;
	ulong mtpNbN;
	ulong mtpNbm;
	ulong mtpNbb;
	long mtpNbf;
	long mtpNbRowStatus;
};
struct mtpSaalTable_data {
	uint mtpSaalTable_request;
	char *mtpSdtProfileId;
	size_t mtpSdtProfileIdLen;
	long mtpSaalBufferRelease;
	ulong mtpSaalMaxCc;
	ulong mtpSaalMaxNrp;
	ulong mtpSaalMaxInformationFieldLength;
	ulong mtpSaalMaxLengthSscopUuField;
	ulong mtpSaalMaxPd;
	ulong mtpSaalMaxSscopCreditToPeer;
	ulong mtpSaalMaxStat;
	ulong mtpSaalN1;
	long mtpSaalNniLayerManagementProvingState;
	long mtpSaalNniLayerManagementTimerNoCredit;
	long mtpSaalNniLayerManagementTimerRepeatSrec;
	long mtpSaalNniTimerT1;
	long mtpSaalNniTimerT2;
	long mtpSaalNniTimerT3;
	long mtpSaalSscopTimerCc;
	long mtpSaalSscopTimerIdle;
	long mtpSaalSscopTimerKeepAlive;
	long mtpSaalSscopTimerNoResponse;
	long mtpSaalSscopTimerPoll;
	ulong mtpSaalTransmissionRateIntervalLower;
	ulong mtpSaalTransmissionRateIntervalUpper;
	ulong mtpSaalEgressTransmissionRateIntervalLower;
	ulong mtpSaalEgressTransmissionRateIntervalUpper;
	long mtpSaalPollAfterRetransmission;
	long mtpSaalRowStatus;
};
struct mtpM2paTable_data {
	uint mtpM2paTable_request;
	char *mtpSdtProfileId;
	size_t mtpSdtProfileIdLen;
	ulong mtpM2paN1;
	long mtpM2paProving;
	long mtpM2paManagementProvingState;
	ulong mtpM2paLoopDelayLower;
	ulong mtpM2paLoopDelayUpper;
	ulong mtpM2paTransmissionRateIntervalLower;
	ulong mtpM2paTransmissionRateIntervalUpper;
	long mtpM2paSctpNoDelay;
	ulong mtpM2paSctpMaxseg;
	ulong mtpM2paSctpHeartbeatItvl;
	long mtpM2paSctpHeartbeat;
	ulong mtpM2paSctpRtoInitial;
	ulong mtpM2paSctpRtoMin;
	ulong mtpM2paSctpRtoMax;
	ulong mtpM2paSctpPathMaxRetrans;
	ulong mtpM2paSctpCookieLife;
	ulong mtpM2paSctpCookieInc;
	ulong mtpM2paSctpMaxInitRetries;
	ulong mtpM2paSctpMaxBurst;
	ulong mtpM2paSctpAssocMaxRetrans;
	ulong mtpM2paSctpSackDelay;
	ulong mtpM2paSctpLifetime;
	ulong mtpM2paProvingAttempts;
	long mtpM2paRowStatus;
};
struct mtpSdtTable_data {
	uint mtpSdtTable_request;
	ulong mtpSdtId;
	long mtpSdtAdministrativeState;
	long mtpSdtOperationalState;
	long mtpSdtUsageState;
	char *mtpSdtProceduralStatus;
	size_t mtpSdtProceduralStatusLen;
	char *mtpSdtAvailabilityStatus;
	size_t mtpSdtAvailabilityStatusLen;
	oid *mtpSdtEquipmentPointer;
	size_t mtpSdtEquipmentPointerLen;
	char *mtpSdtName;
	size_t mtpSdtNameLen;
	oid *mtpSdtProfilePointer;
	size_t mtpSdtProfilePointerLen;
	long mtpSdtRowStatus;
};
struct mtpSdtStatsTable_data {
	uint mtpSdtStatsTable_request;
	ulong mtpSdtId;
	long mtpSdtStatsTxBytes;
	long mtpSdtStatsTxSus;
	long mtpSdtStatsTxSusRepeated;
	long mtpSdtStatsTxUnderruns;
	long mtpSdtStatsTxAborts;
	long mtpSdtStatsTxBufferOverflows;
	long mtpSdtStatsTxSusInError;
	long mtpSdtStatsRxBytes;
	long mtpSdtStatsRxSusCompressed;
	long mtpSdtStatsRxOverruns;
	long mtpSdtStatsRxAborts;
	long mtpSdtStatsRxBufferOverflows;
	long mtpSdtStatsRxSusInError;
	long mtpSdtStatsRxSyncTransitions;
	long mtpSdtStatsRxBitsOctetCounted;
	long mtpSdtStatsRxCrcErrors;
	long mtpSdtStatsRxFrameErrors;
	long mtpSdtStatsRxFrameOverflows;
	long mtpSdtStatsRxFrameTooLong;
	long mtpSdtStatsRxFrameTooShort;
	long mtpSdtStatsRxResidueErrors;
	long mtpSdtStatsCarrierCtsLost;
	long mtpSdtStatsCarrierDcdLost;
	long mtpSdtStatsCarrierLost;
};
struct mtpSdlTable_data {
	uint mtpSdlTable_request;
	ulong mtpSdlId;
	char *mtpSdlAdjPc;
	size_t mtpSdlAdjPcLen;
	long mtpSdlTransmissionRate;
	ulong mtpSdlLoopDelay;
	long mtpSdlOperationalState;
	oid *mtpSdlEquipmentPointer;
	size_t mtpSdlEquipmentPointerLen;
	long mtpSdlCIC;
	char *mtpSdlName;
	size_t mtpSdlNameLen;
	char *mtpSdlStmChannel;
	size_t mtpSdlStmChannelLen;
	oid *mtpSdlVcTTpPointer;
	size_t mtpSdlVcTTpPointerLen;
	long mtpSdlRowStatus;
};
struct mtpSdlStatsTable_data {
	uint mtpSdlStatsTable_request;
	ulong mtpSdlId;
	long mtpSdlStatsRxOctets;
	long mtpSdlStatsTxOctets;
	long mtpSdlStatsRXOverruns;
	long mtpSdlStatsTxUnderruns;
	long mtpSdlStatsRxBufferOverflows;
	long mtpSdlStatsTxBufferOverflows;
	long mtpSdlStatsLeadCtsLost;
	long mtpSdlStatsLeadDcdLost;
	long mtpSdlStatsCarrierLost;
	long mtpSdlStatsBipolarViolations;
};

/* storage declarations */
extern struct mtpMIB2_data *mtpMIB2Storage;
extern struct header_complex_index *mtpSapTableStorage;
extern struct header_complex_index *ss7NetworkTableStorage;
extern struct header_complex_index *mtpMsTableStorage;
extern struct header_complex_index *mtpNaTableStorage;
extern struct header_complex_index *mtpGsTableStorage;
extern struct header_complex_index *mtpGsLineTableStorage;
extern struct header_complex_index *mtpGsLineContentTableStorage;
extern struct header_complex_index *mtpSpProfileTableStorage;
extern struct header_complex_index *mtpSpTableStorage;
extern struct header_complex_index *mtpSpStatsTableStorage;
extern struct header_complex_index *mtpSpCurrentTableStorage;
extern struct header_complex_index *mtpSpInt5minTableStorage;
extern struct header_complex_index *mtpSpInt15minTableStorage;
extern struct header_complex_index *mtpSpSiTableStorage;
extern struct header_complex_index *mtpSpSiInt5minTableStorage;
extern struct header_complex_index *mtpSpSiInt15minTableStorage;
extern struct header_complex_index *mtpSpStudyTableStorage;
extern struct header_complex_index *mtpSpStudyInt5minTableStorage;
extern struct header_complex_index *mtpSpStudyInt15minTableStorage;
extern struct header_complex_index *mtpSpStudyMapTableStorage;
extern struct header_complex_index *mtpL3TableStorage;
extern struct header_complex_index *mtpRsProfileTableStorage;
extern struct header_complex_index *mtpRsTableStorage;
extern struct header_complex_index *mtpRsStatsTableStorage;
extern struct header_complex_index *mtpRsCurrentTableStorage;
extern struct header_complex_index *mtpRsInt5minTableStorage;
extern struct header_complex_index *mtpRsInt15minTableStorage;
extern struct header_complex_index *mtpRsSiTableStorage;
extern struct header_complex_index *mtpRsSiInt5minTableStorage;
extern struct header_complex_index *mtpRsSiInt15minTableStorage;
extern struct header_complex_index *mtpRtProfileTableStorage;
extern struct header_complex_index *mtpRtTableStorage;
extern struct header_complex_index *mtpRtLsaTableStorage;
extern struct header_complex_index *mtpLsProfileTableStorage;
extern struct header_complex_index *mtpLsTableStorage;
extern struct header_complex_index *mtpLsStatsTableStorage;
extern struct header_complex_index *mtpLsCurrentTableStorage;
extern struct header_complex_index *mtpLsInt5minTableStorage;
extern struct header_complex_index *mtpLsInt15minTableStorage;
extern struct header_complex_index *mtpSlL3ProfileTableStorage;
extern struct header_complex_index *mtpSlL2ProfileTableStorage;
extern struct header_complex_index *mtpSlTableStorage;
extern struct header_complex_index *mtpSlSdlListTableStorage;
extern struct header_complex_index *mtpSlSdtListTableStorage;
extern struct header_complex_index *mtpSlStatsTableStorage;
extern struct header_complex_index *mtpSlL3CurrentTableStorage;
extern struct header_complex_index *mtpSlL3Int5minTableStorage;
extern struct header_complex_index *mtpSlL3Int15minTableStorage;
extern struct header_complex_index *mtpSlL2CurrentTableStorage;
extern struct header_complex_index *mtpSlL2Int5minTableStorage;
extern struct header_complex_index *mtpSlL2Int15minTableStorage;
extern struct header_complex_index *mtpNbTableStorage;
extern struct header_complex_index *mtpSaalTableStorage;
extern struct header_complex_index *mtpM2paTableStorage;
extern struct header_complex_index *mtpSdtTableStorage;
extern struct header_complex_index *mtpSdtStatsTableStorage;
extern struct header_complex_index *mtpSdlTableStorage;
extern struct header_complex_index *mtpSdlStatsTableStorage;

/* enum definitions from the covered mib sections */

#define MTPSAPUSERPART_SNMM                      0
#define MTPSAPUSERPART_SNTM                      1
#define MTPSAPUSERPART_SNSM                      2
#define MTPSAPUSERPART_SCCP                      3
#define MTPSAPUSERPART_TUP                       4
#define MTPSAPUSERPART_ISUP                      5
#define MTPSAPUSERPART_DUP1                      6
#define MTPSAPUSERPART_DUP2                      7
#define MTPSAPUSERPART_MTUP                      8
#define MTPSAPUSERPART_BISUP                     9
#define MTPSAPUSERPART_SIUP                      10
#define MTPSAPUSERPART_USER11                    11
#define MTPSAPUSERPART_USER12                    12
#define MTPSAPUSERPART_USER13                    13
#define MTPSAPUSERPART_USER14                    14
#define MTPSAPUSERPART_USER15                    15

#define MTPSAPUSERPARTSTATUS_UNKNOWN             0
#define MTPSAPUSERPARTSTATUS_INACCESSIBLE        1
#define MTPSAPUSERPARTSTATUS_UNEQUIPPED          2

#define MTPSAPUSAGESTATE_IDLE                    0
#define MTPSAPUSAGESTATE_ACTIVE                  1
#define MTPSAPUSAGESTATE_BUSY                    2

#define MTPSAPLONGMESSAGESUPPORTED_TRUE          1
#define MTPSAPLONGMESSAGESUPPORTED_FALSE         2

#define SS7NETWORKPROTOCOLSTANDARD_ITUT          1
#define SS7NETWORKPROTOCOLSTANDARD_ETSI          2
#define SS7NETWORKPROTOCOLSTANDARD_ANSI          3
#define SS7NETWORKPROTOCOLSTANDARD_JTTC          4
#define SS7NETWORKPROTOCOLSTANDARD_PNOC          5

#define SS7NETWORKINDICATOR_INTERNATIONAL        0
#define SS7NETWORKINDICATOR_NATIONAL             1

#define SS7NETWORKPOINTCODEFORMAT_PC383          0
#define SS7NETWORKPOINTCODEFORMAT_PC888          1

#define MTPMSALARMSTATUS_UNDERREPAIR             0
#define MTPMSALARMSTATUS_CRITICAL                1
#define MTPMSALARMSTATUS_MAJOR                   2
#define MTPMSALARMSTATUS_MINOR                   3
#define MTPMSALARMSTATUS_ALARMOUTSTANDING        4

#define MTPMSOPERATIONALSTATE_DISABLED           0
#define MTPMSOPERATIONALSTATE_ENABLED            1

#define MTPMSUSAGESTATE_IDLE                     0
#define MTPMSUSAGESTATE_ACTIVE                   1
#define MTPMSUSAGESTATE_BUSY                     2

#define MTPNAPROTOCOLYEAR_Y1980                  1980
#define MTPNAPROTOCOLYEAR_Y1984                  1984
#define MTPNAPROTOCOLYEAR_Y1988                  1988
#define MTPNAPROTOCOLYEAR_Y1992                  1992
#define MTPNAPROTOCOLYEAR_Y1996                  1996
#define MTPNAPROTOCOLYEAR_Y2000                  2000
#define MTPNAPROTOCOLYEAR_Y2004                  2004
#define MTPNAPROTOCOLYEAR_Y2008                  2008

#define MTPNAPROTOCOLOPTIONS_MTPFCONGINT         0
#define MTPNAPROTOCOLOPTIONS_MTPFCONGLEV         1
#define MTPNAPROTOCOLOPTIONS_MTPFCONGSTA         2
#define MTPNAPROTOCOLOPTIONS_MTPFTFRBASIC        3
#define MTPNAPROTOCOLOPTIONS_MTPFTFRBCAST        4
#define MTPNAPROTOCOLOPTIONS_MTPFTFRRESP         5
#define MTPNAPROTOCOLOPTIONS_MTPFTFRCONG         6
#define MTPNAPROTOCOLOPTIONS_MTPFLINKOSC         7
#define MTPNAPROTOCOLOPTIONS_MTPFLINKOSCA        8
#define MTPNAPROTOCOLOPTIONS_MTPFLINKOSCB        9
#define MTPNAPROTOCOLOPTIONS_MTPFPCALIAS         10
#define MTPNAPROTOCOLOPTIONS_MTPFCLUSTER         11
#define MTPNAPROTOCOLOPTIONS_MTPFSNSM            12
#define MTPNAPROTOCOLOPTIONS_MTPFGWS             13
#define MTPNAPROTOCOLOPTIONS_MTPFEGWS            14
#define MTPNAPROTOCOLOPTIONS_MTPFBGWS            15
#define MTPNAPROTOCOLOPTIONS_MTPFLINKPCR         16
#define MTPNAPROTOCOLOPTIONS_MTPFLINKHSL         17
#define MTPNAPROTOCOLOPTIONS_MTPFLINKHSLBSN      18
#define MTPNAPROTOCOLOPTIONS_MTPFLINKHSLESN      19
#define MTPNAPROTOCOLOPTIONS_MTPFLINKSAAL        20
#define MTPNAPROTOCOLOPTIONS_MTPFLINKM2PA        21
#define MTPNAPROTOCOLOPTIONS_MTPFLINKPROVING     22
#define MTPNAPROTOCOLOPTIONS_MTPFLINKSDLALLOC    23
#define MTPNAPROTOCOLOPTIONS_MTPFLINKSTALLOC     24
#define MTPNAPROTOCOLOPTIONS_MTPFSNTMFAIL        25

#define MTPNANETWORKINDICATOR_INTERNATIONALNETWORK1 0
#define MTPNANETWORKINDICATOR_INTERNATIONALNETWORK2 1
#define MTPNANETWORKINDICATOR_NATIONALNETWORK1   2
#define MTPNANETWORKINDICATOR_NATIONALNETWORK2   3

#define MTPNASLSLENGTH_SLS4BITS                  4
#define MTPNASLSLENGTH_SLS5BITS                  5
#define MTPNASLSLENGTH_SLS8BITS                  8

#define MTPGSADMINISTRATIVESTATE_LOCKED          0
#define MTPGSADMINISTRATIVESTATE_UNLOCKED        1
#define MTPGSADMINISTRATIVESTATE_SHUTTINGDOWN    2

#define MTPGSTREATMENTOFOUTSIDERANGES_NORMAL     0
#define MTPGSTREATMENTOFOUTSIDERANGES_DISCARD    1
#define MTPGSTREATMENTOFOUTSIDERANGES_PROHIBIT   2
#define MTPGSTREATMENTOFOUTSIDERANGES_UNEQUIPPED 3
#define MTPGSTREATMENTOFOUTSIDERANGES_INACCESSIBLE 4
#define MTPGSTREATMENTOFOUTSIDERANGES_CONGEST    5

#define MTPGSLISTMODE_TRUE                       1
#define MTPGSLISTMODE_FALSE                      2

#define MTPGSSCREENINGBYLINKSETORBYOPC_BYOPC     0
#define MTPGSSCREENINGBYLINKSETORBYOPC_BYINCOMINGLINKSET 1
#define MTPGSSCREENINGBYLINKSETORBYOPC_BYOUTGOINGLINKSET 2

#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_SUCCESS 0
#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_UNSUCCESSFUL 1
#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_NOTPERFORMED 2
#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_LINKALREADYINHIBITED 3
#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_LINKNOTINHIBITED 4
#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_WRONGCLASSREFERENCED 5
#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_SIGNTERMNONEXISTING 6
#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_SIGNTERMALREADYREFERENCED 7
#define MTPGSGETSCREENEDOPCSORLINKSETSBYDPC_WRONGSIGNLINKTPSTATUS 8

#define MTPGSLINECONTENTSIMASK_SNMM              0
#define MTPGSLINECONTENTSIMASK_SNTM              1
#define MTPGSLINECONTENTSIMASK_SNSM              2
#define MTPGSLINECONTENTSIMASK_SCCP              3
#define MTPGSLINECONTENTSIMASK_TUP               4
#define MTPGSLINECONTENTSIMASK_ISUP              5
#define MTPGSLINECONTENTSIMASK_DUP1              6
#define MTPGSLINECONTENTSIMASK_DUP2              7
#define MTPGSLINECONTENTSIMASK_MTUP              8
#define MTPGSLINECONTENTSIMASK_BISUP             9
#define MTPGSLINECONTENTSIMASK_SIUP              10
#define MTPGSLINECONTENTSIMASK_USER11            11
#define MTPGSLINECONTENTSIMASK_USER12            12
#define MTPGSLINECONTENTSIMASK_USER13            13
#define MTPGSLINECONTENTSIMASK_USER14            14
#define MTPGSLINECONTENTSIMASK_USER15            15

#define MTPGSLINECONTENTMESSAGETREATMENT_NORMAL  0
#define MTPGSLINECONTENTMESSAGETREATMENT_DISCARD 1
#define MTPGSLINECONTENTMESSAGETREATMENT_PROHIBIT 2
#define MTPGSLINECONTENTMESSAGETREATMENT_UNEQUIPPED 3
#define MTPGSLINECONTENTMESSAGETREATMENT_INACCESSIBLE 4
#define MTPGSLINECONTENTMESSAGETREATMENT_CONGEST 5

#define MTPSPTYPE_SEP                            0
#define MTPSPTYPE_STEP                           1
#define MTPSPTYPE_STP                            2

#define MTPSPOPERATIONALSTATE_DISABLED           0
#define MTPSPOPERATIONALSTATE_ENABLED            1

#define MTPSPPROCEDURALSTATUS_INITIALIZATIONREQUIRED 0
#define MTPSPPROCEDURALSTATUS_NOTINITIALIZED     1
#define MTPSPPROCEDURALSTATUS_INITIALIZING       2
#define MTPSPPROCEDURALSTATUS_REPORTING          3
#define MTPSPPROCEDURALSTATUS_TERMINATING        4

#define MTPSPAVAILABILITYSTATUS_INTEST           0
#define MTPSPAVAILABILITYSTATUS_FAILED           1
#define MTPSPAVAILABILITYSTATUS_POWEROFF         2
#define MTPSPAVAILABILITYSTATUS_OFFLINE          3
#define MTPSPAVAILABILITYSTATUS_OFFDUTY          4
#define MTPSPAVAILABILITYSTATUS_DEPENDENCY       5
#define MTPSPAVAILABILITYSTATUS_DEGRADED         6
#define MTPSPAVAILABILITYSTATUS_NOTINSTALLED     7
#define MTPSPAVAILABILITYSTATUS_LOGFULL          8

#define MTPSPNETWORKINDICATOR_INTERNATIONALNETWORK1 0
#define MTPSPNETWORKINDICATOR_INTERNATIONALNETWORK2 1
#define MTPSPNETWORKINDICATOR_NATIONALNETWORK1   2
#define MTPSPNETWORKINDICATOR_NATIONALNETWORK2   3

#define MTPSPFLAGS_SPFCLUSTER                    0
#define MTPSPFLAGS_SPFXFERFUNC                   1
#define MTPSPFLAGS_SPFSECURITY                   2
#define MTPSPFLAGS_SPFLOSCPROCA                  3
#define MTPSPFLAGS_SPFLOSCPROCB                  4

#define MTPSPUSERS_SNMM                          0
#define MTPSPUSERS_SNTM                          1
#define MTPSPUSERS_SNSM                          2
#define MTPSPUSERS_SCCP                          3
#define MTPSPUSERS_TUP                           4
#define MTPSPUSERS_ISUP                          5
#define MTPSPUSERS_DUP1                          6
#define MTPSPUSERS_DUP2                          7
#define MTPSPUSERS_MTUP                          8
#define MTPSPUSERS_BISUP                         9
#define MTPSPUSERS_SIUP                          10
#define MTPSPUSERS_USER11                        11
#define MTPSPUSERS_USER12                        12
#define MTPSPUSERS_USER13                        13
#define MTPSPUSERS_USER14                        14
#define MTPSPUSERS_USER15                        15

#define MTPSPALARMSTATUS_UNDERREPAIR             0
#define MTPSPALARMSTATUS_CRITICAL                1
#define MTPSPALARMSTATUS_MAJOR                   2
#define MTPSPALARMSTATUS_MINOR                   3
#define MTPSPALARMSTATUS_ALARMOUTSTANDING        4

#define MTPL3ADMINISTRATIVESTATE_LOCKED          0
#define MTPL3ADMINISTRATIVESTATE_UNLOCKED        1
#define MTPL3ADMINISTRATIVESTATE_SHUTTINGDOWN    2

#define MTPL3OPERATIONALSTATE_DISABLED           0
#define MTPL3OPERATIONALSTATE_ENABLED            1

#define MTPL3USAGESTATE_IDLE                     0
#define MTPL3USAGESTATE_ACTIVE                   1
#define MTPL3USAGESTATE_BUSY                     2

#define MTPL3PROCEDURALSTATUS_INITIALIZATIONREQUIRED 0
#define MTPL3PROCEDURALSTATUS_NOTINITIALIZED     1
#define MTPL3PROCEDURALSTATUS_INITIALIZING       2
#define MTPL3PROCEDURALSTATUS_REPORTING          3
#define MTPL3PROCEDURALSTATUS_TERMINATING        4

#define MTPRSFLAGS_RSFCLUSTER                    0
#define MTPRSFLAGS_RSFXFERFUNC                   1
#define MTPRSFLAGS_RSFSECURITY                   2
#define MTPRSFLAGS_RSFADJACENT                   3

#define MTPRSADMINISTRATIVESTATE_LOCKED          0
#define MTPRSADMINISTRATIVESTATE_UNLOCKED        1
#define MTPRSADMINISTRATIVESTATE_SHUTTINGDOWN    2

#define MTPRSOPERATIONALSTATE_DISABLED           0
#define MTPRSOPERATIONALSTATE_ENABLED            1

#define MTPRSCONGESTEDSTATE_NOTCONGESTED         0
#define MTPRSCONGESTEDSTATE_CONGESTED            1

#define MTPRSCONGESTIONLEVEL_NONE                0
#define MTPRSCONGESTIONLEVEL_CONGESTIONLEVEL1    1
#define MTPRSCONGESTIONLEVEL_CONGESTIONLEVEL2    2
#define MTPRSCONGESTIONLEVEL_CONGESTIONLEVEL3    3

#define MTPRSALARMSTATUS_UNDERREPAIR             0
#define MTPRSALARMSTATUS_CRITICAL                1
#define MTPRSALARMSTATUS_MAJOR                   2
#define MTPRSALARMSTATUS_MINOR                   3
#define MTPRSALARMSTATUS_ALARMOUTSTANDING        4

#define MTPRTADMINISTRATIVESTATE_LOCKED          0
#define MTPRTADMINISTRATIVESTATE_UNLOCKED        1
#define MTPRTADMINISTRATIVESTATE_SHUTTINGDOWN    2

#define MTPRTOPERATIONALSTATE_DISABLED           0
#define MTPRTOPERATIONALSTATE_ENABLED            1

#define MTPRTAVAILABILITYSTATUS_INTEST           0
#define MTPRTAVAILABILITYSTATUS_FAILED           1
#define MTPRTAVAILABILITYSTATUS_POWEROFF         2
#define MTPRTAVAILABILITYSTATUS_OFFLINE          3
#define MTPRTAVAILABILITYSTATUS_OFFDUTY          4
#define MTPRTAVAILABILITYSTATUS_DEPENDENCY       5
#define MTPRTAVAILABILITYSTATUS_DEGRADED         6
#define MTPRTAVAILABILITYSTATUS_NOTINSTALLED     7
#define MTPRTAVAILABILITYSTATUS_LOGFULL          8

#define MTPRTPRIORITYMODE_INSERT                 0
#define MTPRTPRIORITYMODE_EQUAL                  1
#define MTPRTPRIORITYMODE_EXCHANGESINGLE         2
#define MTPRTPRIORITYMODE_EXCHANGEGROUP          3

#define MTPRTUSAGESTATE_IDLE                     0
#define MTPRTUSAGESTATE_ACTIVE                   1
#define MTPRTUSAGESTATE_BUSY                     2

#define MTPLSCONGESTIONCONTROLMETHOD_UNKNOWN     0
#define MTPLSCONGESTIONCONTROLMETHOD_CCMQ704INTERNATIONAL 1
#define MTPLSCONGESTIONCONTROLMETHOD_CCMQ704NATIONALWITHPRIO 2
#define MTPLSCONGESTIONCONTROLMETHOD_CCMQ704NATIONALNOPRIOBUFFERMECHANISM 3
#define MTPLSCONGESTIONCONTROLMETHOD_CCMQ704NATIONALNOPRIOTIMERMECHANISM 4

#define MTPLSUSAGESTATE_IDLE                     0
#define MTPLSUSAGESTATE_ACTIVE                   1
#define MTPLSUSAGESTATE_BUSY                     2

#define MTPLSOPERATIONALSTATE_DISABLED           0
#define MTPLSOPERATIONALSTATE_ENABLED            1

#define MTPLSAVAILABILITYSTATUS_INTEST           0
#define MTPLSAVAILABILITYSTATUS_FAILED           1
#define MTPLSAVAILABILITYSTATUS_POWEROFF         2
#define MTPLSAVAILABILITYSTATUS_OFFLINE          3
#define MTPLSAVAILABILITYSTATUS_OFFDUTY          4
#define MTPLSAVAILABILITYSTATUS_DEPENDENCY       5
#define MTPLSAVAILABILITYSTATUS_DEGRADED         6
#define MTPLSAVAILABILITYSTATUS_NOTINSTALLED     7
#define MTPLSAVAILABILITYSTATUS_LOGFULL          8

#define MTPLSPERIODICLINKTESTFLAG_ON             0
#define MTPLSPERIODICLINKTESTFLAG_OFF            1

#define MTPLSPERIODICLINKTESTFAIL_TRUE           1
#define MTPLSPERIODICLINKTESTFAIL_FALSE          2

#define MTPLSADMINISTRATIVESTATE_LOCKED          0
#define MTPLSADMINISTRATIVESTATE_UNLOCKED        1
#define MTPLSADMINISTRATIVESTATE_SHUTTINGDOWN    2

#define MTPLSALARMSTATUS_UNDERREPAIR             0
#define MTPLSALARMSTATUS_CRITICAL                1
#define MTPLSALARMSTATUS_MAJOR                   2
#define MTPLSALARMSTATUS_MINOR                   3
#define MTPLSALARMSTATUS_ALARMOUTSTANDING        4

#define MTPSLL2PROFILEERRORCORRECTIONMETHOD_BASICRETR 0
#define MTPSLL2PROFILEERRORCORRECTIONMETHOD_PREVCYCLRETR 1

#define MTPSLL2PROFILETRANSMISSIONRATE_KBITS4POINT8 0
#define MTPSLL2PROFILETRANSMISSIONRATE_KBITS56   1
#define MTPSLL2PROFILETRANSMISSIONRATE_KBITS64   2
#define MTPSLL2PROFILETRANSMISSIONRATE_KBITS1544 3
#define MTPSLL2PROFILETRANSMISSIONRATE_KBITS2048 4

#define MTPSLL2PROFILECONGESTIONCOUNTING_OCTET   0
#define MTPSLL2PROFILECONGESTIONCOUNTING_MESSAGE 1

#define MTPSLL2PROFILECONGESTIONREPORTINGBASEOBJECT_ROUTESET 0
#define MTPSLL2PROFILECONGESTIONREPORTINGBASEOBJECT_LINKSETOFCONGESTEDROUTESET 1
#define MTPSLL2PROFILECONGESTIONREPORTINGBASEOBJECT_LINKOFCONGESTEDROUTESET 2
#define MTPSLL2PROFILECONGESTIONREPORTINGBASEOBJECT_CONGESTEDLINKOFCONGESTEDROUTE 3

#define MTPSLLINKTPSTATUS_LOCALBLOCKED           0
#define MTPSLLINKTPSTATUS_REMOTEBLOCKED          1
#define MTPSLLINKTPSTATUS_LOCALINHIBITED         2
#define MTPSLLINKTPSTATUS_REMOTEINHIBITED        3
#define MTPSLLINKTPSTATUS_FAILED                 4
#define MTPSLLINKTPSTATUS_DEACTIVATED            5

#define MTPSLADMINISTRATIVESTATE_LOCKED          0
#define MTPSLADMINISTRATIVESTATE_UNLOCKED        1
#define MTPSLADMINISTRATIVESTATE_SHUTTINGDOWN    2

#define MTPSLOPERATIONALSTATE_DISABLED           0
#define MTPSLOPERATIONALSTATE_ENABLED            1

#define MTPSLUSAGESTATE_IDLE                     0
#define MTPSLUSAGESTATE_ACTIVE                   1
#define MTPSLUSAGESTATE_BUSY                     2

#define MTPSLPROCEDURALSTATUS_INITIALIZATIONREQUIRED 0
#define MTPSLPROCEDURALSTATUS_NOTINITIALIZED     1
#define MTPSLPROCEDURALSTATUS_INITIALIZING       2
#define MTPSLPROCEDURALSTATUS_REPORTING          3
#define MTPSLPROCEDURALSTATUS_TERMINATING        4

#define MTPSLLOCALINHIBIT_SUCCESS                0
#define MTPSLLOCALINHIBIT_UNSUCCESSFUL           1
#define MTPSLLOCALINHIBIT_NOTPERFORMED           2
#define MTPSLLOCALINHIBIT_LINKALREADYINHIBITED   3
#define MTPSLLOCALINHIBIT_LINKNOTINHIBITED       4
#define MTPSLLOCALINHIBIT_WRONGCLASSREFERENCED   5
#define MTPSLLOCALINHIBIT_SIGNTERMNONEXISTING    6
#define MTPSLLOCALINHIBIT_SIGNTERMALREADYREFERENCED 7
#define MTPSLLOCALINHIBIT_WRONGSIGNLINKTPSTATUS  8

#define MTPSLLOCALUNINHIBIT_SUCCESS              0
#define MTPSLLOCALUNINHIBIT_UNSUCCESSFUL         1
#define MTPSLLOCALUNINHIBIT_NOTPERFORMED         2
#define MTPSLLOCALUNINHIBIT_LINKALREADYINHIBITED 3
#define MTPSLLOCALUNINHIBIT_LINKNOTINHIBITED     4
#define MTPSLLOCALUNINHIBIT_WRONGCLASSREFERENCED 5
#define MTPSLLOCALUNINHIBIT_SIGNTERMNONEXISTING  6
#define MTPSLLOCALUNINHIBIT_SIGNTERMALREADYREFERENCED 7
#define MTPSLLOCALUNINHIBIT_WRONGSIGNLINKTPSTATUS 8

#define MTPSLREPLACEST_SUCCESS                   0
#define MTPSLREPLACEST_UNSUCCESSFUL              1
#define MTPSLREPLACEST_NOTPERFORMED              2
#define MTPSLREPLACEST_LINKALREADYINHIBITED      3
#define MTPSLREPLACEST_LINKNOTINHIBITED          4
#define MTPSLREPLACEST_WRONGCLASSREFERENCED      5
#define MTPSLREPLACEST_SIGNTERMNONEXISTING       6
#define MTPSLREPLACEST_SIGNTERMALREADYREFERENCED 7
#define MTPSLREPLACEST_WRONGSIGNLINKTPSTATUS     8

#define MTPSLCONGESTIONLEVEL_NONE                0
#define MTPSLCONGESTIONLEVEL_CONGESTIONLEVEL1    1
#define MTPSLCONGESTIONLEVEL_CONGESTIONLEVEL2    2
#define MTPSLCONGESTIONLEVEL_CONGESTIONLEVEL3    3

#define MTPSLTEST_SUCCESS                        0
#define MTPSLTEST_UNSUCCESSFUL                   1
#define MTPSLTEST_NOTPERFORMED                   2
#define MTPSLTEST_LINKALREADYINHIBITED           3
#define MTPSLTEST_LINKNOTINHIBITED               4
#define MTPSLTEST_WRONGCLASSREFERENCED           5
#define MTPSLTEST_SIGNTERMNONEXISTING            6
#define MTPSLTEST_SIGNTERMALREADYREFERENCED      7
#define MTPSLTEST_WRONGSIGNLINKTPSTATUS          8

#define MTPSLALARMSTATUS_UNDERREPAIR             0
#define MTPSLALARMSTATUS_CRITICAL                1
#define MTPSLALARMSTATUS_MAJOR                   2
#define MTPSLALARMSTATUS_MINOR                   3
#define MTPSLALARMSTATUS_ALARMOUTSTANDING        4

#define MTPNBTRANSMISSIONRATE_KBITS4POINT8       0
#define MTPNBTRANSMISSIONRATE_KBITS56            1
#define MTPNBTRANSMISSIONRATE_KBITS64            2
#define MTPNBTRANSMISSIONRATE_KBITS1544          3
#define MTPNBTRANSMISSIONRATE_KBITS2048          4

#define MTPNBF_ONE                               0
#define MTPNBF_SHARED                            1
#define MTPNBF_TWO                               2
#define MTPNBF_THREE                             3
#define MTPNBF_FOUR                              4
#define MTPNBF_FIVE                              5
#define MTPNBF_SIX                               6

#define MTPSAALBUFFERRELEASE_TRUE                1
#define MTPSAALBUFFERRELEASE_FALSE               2

#define MTPSAALNNILAYERMANAGEMENTPROVINGSTATE_NORMAL 0
#define MTPSAALNNILAYERMANAGEMENTPROVINGSTATE_EMERGENCY 1
#define MTPSAALNNILAYERMANAGEMENTPROVINGSTATE_NEUTRAL 2

#define MTPSAALPOLLAFTERRETRANSMISSION_TRUE      1
#define MTPSAALPOLLAFTERRETRANSMISSION_FALSE     2

#define MTPM2PAPROVING_TRUE                      1
#define MTPM2PAPROVING_FALSE                     2

#define MTPM2PAMANAGEMENTPROVINGSTATE_NORMAL     0
#define MTPM2PAMANAGEMENTPROVINGSTATE_EMERGENCY  1
#define MTPM2PAMANAGEMENTPROVINGSTATE_NEUTRAL    2

#define MTPM2PASCTPNODELAY_TRUE                  1
#define MTPM2PASCTPNODELAY_FALSE                 2

#define MTPM2PASCTPHEARTBEAT_TRUE                1
#define MTPM2PASCTPHEARTBEAT_FALSE               2

#define MTPSDTADMINISTRATIVESTATE_LOCKED         0
#define MTPSDTADMINISTRATIVESTATE_UNLOCKED       1
#define MTPSDTADMINISTRATIVESTATE_SHUTTINGDOWN   2

#define MTPSDTOPERATIONALSTATE_DISABLED          0
#define MTPSDTOPERATIONALSTATE_ENABLED           1

#define MTPSDTUSAGESTATE_IDLE                    0
#define MTPSDTUSAGESTATE_ACTIVE                  1
#define MTPSDTUSAGESTATE_BUSY                    2

#define MTPSDTPROCEDURALSTATUS_INITIALIZATIONREQUIRED 0
#define MTPSDTPROCEDURALSTATUS_NOTINITIALIZED    1
#define MTPSDTPROCEDURALSTATUS_INITIALIZING      2
#define MTPSDTPROCEDURALSTATUS_REPORTING         3
#define MTPSDTPROCEDURALSTATUS_TERMINATING       4

#define MTPSDTAVAILABILITYSTATUS_INTEST          0
#define MTPSDTAVAILABILITYSTATUS_FAILED          1
#define MTPSDTAVAILABILITYSTATUS_POWEROFF        2
#define MTPSDTAVAILABILITYSTATUS_OFFLINE         3
#define MTPSDTAVAILABILITYSTATUS_OFFDUTY         4
#define MTPSDTAVAILABILITYSTATUS_DEPENDENCY      5
#define MTPSDTAVAILABILITYSTATUS_DEGRADED        6
#define MTPSDTAVAILABILITYSTATUS_NOTINSTALLED    7
#define MTPSDTAVAILABILITYSTATUS_LOGFULL         8

#define MTPSDLTRANSMISSIONRATE_KBITS4POINT8      0
#define MTPSDLTRANSMISSIONRATE_KBITS56           1
#define MTPSDLTRANSMISSIONRATE_KBITS64           2
#define MTPSDLTRANSMISSIONRATE_KBITS1544         3
#define MTPSDLTRANSMISSIONRATE_KBITS2048         4

#define MTPSDLOPERATIONALSTATE_DISABLED          0
#define MTPSDLOPERATIONALSTATE_ENABLED           1

#define MTPM2PADEFAULTSCTPNODELAY_TRUE           1
#define MTPM2PADEFAULTSCTPNODELAY_FALSE          2

#define MTPM2PADEFAULTSCTPHEARTBEAT_TRUE         1
#define MTPM2PADEFAULTSCTPHEARTBEAT_FALSE        2

/* function prototypes */
void init_mtpMIB2(void);
void deinit_mtpMIB2(void);
int term_mtpMIB2(int majorID, int minorID, void *serverarg, void *clientarg);
FindVarMethod var_mtpMIB2;
void parse_mtpMIB2(const char *, char *);
SNMPCallback store_mtpMIB2;
void refresh_mtpMIB2(void);
FindVarMethod var_mtpSapTable;
void parse_mtpSapTable(const char *, char *);
SNMPCallback store_mtpSapTable;
void refresh_mtpSapTable(void);
FindVarMethod var_ss7NetworkTable;
void parse_ss7NetworkTable(const char *, char *);
SNMPCallback store_ss7NetworkTable;
void refresh_ss7NetworkTable(void);
FindVarMethod var_mtpMsTable;
void parse_mtpMsTable(const char *, char *);
SNMPCallback store_mtpMsTable;
void refresh_mtpMsTable(void);
FindVarMethod var_mtpNaTable;
void parse_mtpNaTable(const char *, char *);
SNMPCallback store_mtpNaTable;
void refresh_mtpNaTable(void);
FindVarMethod var_mtpGsTable;
void parse_mtpGsTable(const char *, char *);
SNMPCallback store_mtpGsTable;
void refresh_mtpGsTable(void);
FindVarMethod var_mtpGsLineTable;
void parse_mtpGsLineTable(const char *, char *);
SNMPCallback store_mtpGsLineTable;
void refresh_mtpGsLineTable(void);
FindVarMethod var_mtpGsLineContentTable;
void parse_mtpGsLineContentTable(const char *, char *);
SNMPCallback store_mtpGsLineContentTable;
void refresh_mtpGsLineContentTable(void);
FindVarMethod var_mtpSpProfileTable;
void parse_mtpSpProfileTable(const char *, char *);
SNMPCallback store_mtpSpProfileTable;
void refresh_mtpSpProfileTable(void);
FindVarMethod var_mtpSpTable;
void parse_mtpSpTable(const char *, char *);
SNMPCallback store_mtpSpTable;
void refresh_mtpSpTable(void);
FindVarMethod var_mtpSpStatsTable;
void parse_mtpSpStatsTable(const char *, char *);
SNMPCallback store_mtpSpStatsTable;
void refresh_mtpSpStatsTable(void);
FindVarMethod var_mtpSpCurrentTable;
void parse_mtpSpCurrentTable(const char *, char *);
SNMPCallback store_mtpSpCurrentTable;
void refresh_mtpSpCurrentTable(void);
FindVarMethod var_mtpSpInt5minTable;
void parse_mtpSpInt5minTable(const char *, char *);
SNMPCallback store_mtpSpInt5minTable;
void refresh_mtpSpInt5minTable(void);
FindVarMethod var_mtpSpInt15minTable;
void parse_mtpSpInt15minTable(const char *, char *);
SNMPCallback store_mtpSpInt15minTable;
void refresh_mtpSpInt15minTable(void);
FindVarMethod var_mtpSpSiTable;
void parse_mtpSpSiTable(const char *, char *);
SNMPCallback store_mtpSpSiTable;
void refresh_mtpSpSiTable(void);
FindVarMethod var_mtpSpSiInt5minTable;
void parse_mtpSpSiInt5minTable(const char *, char *);
SNMPCallback store_mtpSpSiInt5minTable;
void refresh_mtpSpSiInt5minTable(void);
FindVarMethod var_mtpSpSiInt15minTable;
void parse_mtpSpSiInt15minTable(const char *, char *);
SNMPCallback store_mtpSpSiInt15minTable;
void refresh_mtpSpSiInt15minTable(void);
FindVarMethod var_mtpSpStudyTable;
void parse_mtpSpStudyTable(const char *, char *);
SNMPCallback store_mtpSpStudyTable;
void refresh_mtpSpStudyTable(void);
FindVarMethod var_mtpSpStudyInt5minTable;
void parse_mtpSpStudyInt5minTable(const char *, char *);
SNMPCallback store_mtpSpStudyInt5minTable;
void refresh_mtpSpStudyInt5minTable(void);
FindVarMethod var_mtpSpStudyInt15minTable;
void parse_mtpSpStudyInt15minTable(const char *, char *);
SNMPCallback store_mtpSpStudyInt15minTable;
void refresh_mtpSpStudyInt15minTable(void);
FindVarMethod var_mtpSpStudyMapTable;
void parse_mtpSpStudyMapTable(const char *, char *);
SNMPCallback store_mtpSpStudyMapTable;
void refresh_mtpSpStudyMapTable(void);
FindVarMethod var_mtpL3Table;
void parse_mtpL3Table(const char *, char *);
SNMPCallback store_mtpL3Table;
void refresh_mtpL3Table(void);
FindVarMethod var_mtpRsProfileTable;
void parse_mtpRsProfileTable(const char *, char *);
SNMPCallback store_mtpRsProfileTable;
void refresh_mtpRsProfileTable(void);
FindVarMethod var_mtpRsTable;
void parse_mtpRsTable(const char *, char *);
SNMPCallback store_mtpRsTable;
void refresh_mtpRsTable(void);
FindVarMethod var_mtpRsStatsTable;
void parse_mtpRsStatsTable(const char *, char *);
SNMPCallback store_mtpRsStatsTable;
void refresh_mtpRsStatsTable(void);
FindVarMethod var_mtpRsCurrentTable;
void parse_mtpRsCurrentTable(const char *, char *);
SNMPCallback store_mtpRsCurrentTable;
void refresh_mtpRsCurrentTable(void);
FindVarMethod var_mtpRsInt5minTable;
void parse_mtpRsInt5minTable(const char *, char *);
SNMPCallback store_mtpRsInt5minTable;
void refresh_mtpRsInt5minTable(void);
FindVarMethod var_mtpRsInt15minTable;
void parse_mtpRsInt15minTable(const char *, char *);
SNMPCallback store_mtpRsInt15minTable;
void refresh_mtpRsInt15minTable(void);
FindVarMethod var_mtpRsSiTable;
void parse_mtpRsSiTable(const char *, char *);
SNMPCallback store_mtpRsSiTable;
void refresh_mtpRsSiTable(void);
FindVarMethod var_mtpRsSiInt5minTable;
void parse_mtpRsSiInt5minTable(const char *, char *);
SNMPCallback store_mtpRsSiInt5minTable;
void refresh_mtpRsSiInt5minTable(void);
FindVarMethod var_mtpRsSiInt15minTable;
void parse_mtpRsSiInt15minTable(const char *, char *);
SNMPCallback store_mtpRsSiInt15minTable;
void refresh_mtpRsSiInt15minTable(void);
FindVarMethod var_mtpRtProfileTable;
void parse_mtpRtProfileTable(const char *, char *);
SNMPCallback store_mtpRtProfileTable;
void refresh_mtpRtProfileTable(void);
FindVarMethod var_mtpRtTable;
void parse_mtpRtTable(const char *, char *);
SNMPCallback store_mtpRtTable;
void refresh_mtpRtTable(void);
FindVarMethod var_mtpRtLsaTable;
void parse_mtpRtLsaTable(const char *, char *);
SNMPCallback store_mtpRtLsaTable;
void refresh_mtpRtLsaTable(void);
FindVarMethod var_mtpLsProfileTable;
void parse_mtpLsProfileTable(const char *, char *);
SNMPCallback store_mtpLsProfileTable;
void refresh_mtpLsProfileTable(void);
FindVarMethod var_mtpLsTable;
void parse_mtpLsTable(const char *, char *);
SNMPCallback store_mtpLsTable;
void refresh_mtpLsTable(void);
FindVarMethod var_mtpLsStatsTable;
void parse_mtpLsStatsTable(const char *, char *);
SNMPCallback store_mtpLsStatsTable;
void refresh_mtpLsStatsTable(void);
FindVarMethod var_mtpLsCurrentTable;
void parse_mtpLsCurrentTable(const char *, char *);
SNMPCallback store_mtpLsCurrentTable;
void refresh_mtpLsCurrentTable(void);
FindVarMethod var_mtpLsInt5minTable;
void parse_mtpLsInt5minTable(const char *, char *);
SNMPCallback store_mtpLsInt5minTable;
void refresh_mtpLsInt5minTable(void);
FindVarMethod var_mtpLsInt15minTable;
void parse_mtpLsInt15minTable(const char *, char *);
SNMPCallback store_mtpLsInt15minTable;
void refresh_mtpLsInt15minTable(void);
FindVarMethod var_mtpSlL3ProfileTable;
void parse_mtpSlL3ProfileTable(const char *, char *);
SNMPCallback store_mtpSlL3ProfileTable;
void refresh_mtpSlL3ProfileTable(void);
FindVarMethod var_mtpSlL2ProfileTable;
void parse_mtpSlL2ProfileTable(const char *, char *);
SNMPCallback store_mtpSlL2ProfileTable;
void refresh_mtpSlL2ProfileTable(void);
FindVarMethod var_mtpSlTable;
void parse_mtpSlTable(const char *, char *);
SNMPCallback store_mtpSlTable;
void refresh_mtpSlTable(void);
FindVarMethod var_mtpSlSdlListTable;
void parse_mtpSlSdlListTable(const char *, char *);
SNMPCallback store_mtpSlSdlListTable;
void refresh_mtpSlSdlListTable(void);
FindVarMethod var_mtpSlSdtListTable;
void parse_mtpSlSdtListTable(const char *, char *);
SNMPCallback store_mtpSlSdtListTable;
void refresh_mtpSlSdtListTable(void);
FindVarMethod var_mtpSlStatsTable;
void parse_mtpSlStatsTable(const char *, char *);
SNMPCallback store_mtpSlStatsTable;
void refresh_mtpSlStatsTable(void);
FindVarMethod var_mtpSlL3CurrentTable;
void parse_mtpSlL3CurrentTable(const char *, char *);
SNMPCallback store_mtpSlL3CurrentTable;
void refresh_mtpSlL3CurrentTable(void);
FindVarMethod var_mtpSlL3Int5minTable;
void parse_mtpSlL3Int5minTable(const char *, char *);
SNMPCallback store_mtpSlL3Int5minTable;
void refresh_mtpSlL3Int5minTable(void);
FindVarMethod var_mtpSlL3Int15minTable;
void parse_mtpSlL3Int15minTable(const char *, char *);
SNMPCallback store_mtpSlL3Int15minTable;
void refresh_mtpSlL3Int15minTable(void);
FindVarMethod var_mtpSlL2CurrentTable;
void parse_mtpSlL2CurrentTable(const char *, char *);
SNMPCallback store_mtpSlL2CurrentTable;
void refresh_mtpSlL2CurrentTable(void);
FindVarMethod var_mtpSlL2Int5minTable;
void parse_mtpSlL2Int5minTable(const char *, char *);
SNMPCallback store_mtpSlL2Int5minTable;
void refresh_mtpSlL2Int5minTable(void);
FindVarMethod var_mtpSlL2Int15minTable;
void parse_mtpSlL2Int15minTable(const char *, char *);
SNMPCallback store_mtpSlL2Int15minTable;
void refresh_mtpSlL2Int15minTable(void);
FindVarMethod var_mtpNbTable;
void parse_mtpNbTable(const char *, char *);
SNMPCallback store_mtpNbTable;
void refresh_mtpNbTable(void);
FindVarMethod var_mtpSaalTable;
void parse_mtpSaalTable(const char *, char *);
SNMPCallback store_mtpSaalTable;
void refresh_mtpSaalTable(void);
FindVarMethod var_mtpM2paTable;
void parse_mtpM2paTable(const char *, char *);
SNMPCallback store_mtpM2paTable;
void refresh_mtpM2paTable(void);
FindVarMethod var_mtpSdtTable;
void parse_mtpSdtTable(const char *, char *);
SNMPCallback store_mtpSdtTable;
void refresh_mtpSdtTable(void);
FindVarMethod var_mtpSdtStatsTable;
void parse_mtpSdtStatsTable(const char *, char *);
SNMPCallback store_mtpSdtStatsTable;
void refresh_mtpSdtStatsTable(void);
FindVarMethod var_mtpSdlTable;
void parse_mtpSdlTable(const char *, char *);
SNMPCallback store_mtpSdlTable;
void refresh_mtpSdlTable(void);
FindVarMethod var_mtpSdlStatsTable;
void parse_mtpSdlStatsTable(const char *, char *);
SNMPCallback store_mtpSdlStatsTable;
void refresh_mtpSdlStatsTable(void);

WriteMethod write_mtpSapUserPart;
WriteMethod write_mtpSapUserPartStatus;
WriteMethod write_mtpSapProviderEntityNames;
WriteMethod write_mtpSapAsaProfilePointer;
WriteMethod write_mtpSapName;
WriteMethod write_mtpSapLongMessageSupported;
WriteMethod write_mtpSapRowStatus;
WriteMethod write_ss7NetworkProtocolStandard;
WriteMethod write_ss7NetworkProtocolYear;
WriteMethod write_ss7NetworkIndicator;
WriteMethod write_ss7NetworkStatus;
WriteMethod write_mtpMsName;
WriteMethod write_mtpMsAlarmStatus;
WriteMethod write_mtpMsManagedElementType;
WriteMethod write_mtpMsModelCode;
WriteMethod write_mtpMsVendorName;
WriteMethod write_mtpMsUserLabel;
WriteMethod write_mtpMsVersion;
WriteMethod write_mtpMsAsaProfilePointer;
WriteMethod write_mtpMsNetworkElementAliases;
WriteMethod write_mtpMsStatus;
WriteMethod write_mtpNaProtocolVariant;
WriteMethod write_mtpNaProtocolYear;
WriteMethod write_mtpNaProtocolOptions;
WriteMethod write_mtpNaNetworkIndicator;
WriteMethod write_mtpNaPointCodeFormat;
WriteMethod write_mtpNaSlsLength;
WriteMethod write_mtpNaSpDefault;
WriteMethod write_mtpNaName;
WriteMethod write_mtpNaRowStatus;
WriteMethod write_mtpGsAdministrativeState;
WriteMethod write_mtpGsTreatmentOfOutsideRanges;
WriteMethod write_mtpGsListMode;
WriteMethod write_mtpGsScreeningByLinkSetOrByOpc;
WriteMethod write_mtpGsGetScreenedOpcsOrLinkSetsByDpc;
WriteMethod write_mtpGsName;
WriteMethod write_mtpGsRowStatus;
WriteMethod write_mtpGsLineObject;
WriteMethod write_mtpGsLineContent;
WriteMethod write_mtpGsLineRowStatus;
WriteMethod write_mtpGsLineContentDesignatedDPCFirst;
WriteMethod write_mtpGsLineContentDesignatedDPCLast;
WriteMethod write_mtpGsLineContentSiMask;
WriteMethod write_mtpGsLineContentMessageTreatment;
WriteMethod write_mtpGsLineContentComment;
WriteMethod write_mtpGsLineContentRowStatus;
WriteMethod write_mtpSpProfileTimerT1R;
WriteMethod write_mtpSpProfileTimerT2;
WriteMethod write_mtpSpProfileTimerT4;
WriteMethod write_mtpSpProfileTimerT5;
WriteMethod write_mtpSpProfileTimerT7;
WriteMethod write_mtpSpProfileTimerT11;
WriteMethod write_mtpSpProfileTimerT12;
WriteMethod write_mtpSpProfileTimerT13;
WriteMethod write_mtpSpProfileTimerT14;
WriteMethod write_mtpSpProfileTimerT15;
WriteMethod write_mtpSpProfileTimerT16;
WriteMethod write_mtpSpProfileTimerT18I;
WriteMethod write_mtpSpProfileTimerT19I;
WriteMethod write_mtpSpProfileTimerT20I;
WriteMethod write_mtpSpProfileTimerT21I;
WriteMethod write_mtpSpProfileTimerT22I;
WriteMethod write_mtpSpProfileTimerT23I;
WriteMethod write_mtpSpProfileTimerT20A;
WriteMethod write_mtpSpProfileTimerT21A;
WriteMethod write_mtpSpProfileTimerT22A;
WriteMethod write_mtpSpProfileTimerT23A;
WriteMethod write_mtpSpProfileTimerT24A;
WriteMethod write_mtpSpProfileTimerT26A;
WriteMethod write_mtpSpProfileTimerT27A;
WriteMethod write_mtpSpProfileTimerT1T;
WriteMethod write_mtpSpProfileTimerT2T;
WriteMethod write_mtpSpProfileName;
WriteMethod write_mtpSpProfileRowStatus;
WriteMethod write_mtpSpPointCode;
WriteMethod write_mtpSpType;
WriteMethod write_mtpSpVersion;
WriteMethod write_mtpSpNetworkIndicator;
WriteMethod write_mtpSpName;
WriteMethod write_mtpSpMtpT1;
WriteMethod write_mtpSpMtpT2;
WriteMethod write_mtpSpMtpT3;
WriteMethod write_mtpSpMtpT4;
WriteMethod write_mtpSpMtpT5;
WriteMethod write_mtpSpMtpT6;
WriteMethod write_mtpSpMtpT7;
WriteMethod write_mtpSpMtpT8;
WriteMethod write_mtpSpMtpT10;
WriteMethod write_mtpSpMtpT11;
WriteMethod write_mtpSpMtpT12;
WriteMethod write_mtpSpMtpT13;
WriteMethod write_mtpSpMtpT14;
WriteMethod write_mtpSpMtpT15;
WriteMethod write_mtpSpMtpT16;
WriteMethod write_mtpSpMtpT17;
WriteMethod write_mtpSpMtpT19A;
WriteMethod write_mtpSpMtpT31A;
WriteMethod write_mtpSpMtpT32A;
WriteMethod write_mtpSpMtpT33A;
WriteMethod write_mtpSpMtpT34A;
WriteMethod write_mtpSpMtpT18I;
WriteMethod write_mtpSpMtpT19I;
WriteMethod write_mtpSpMtpT20I;
WriteMethod write_mtpSpMtpT21I;
WriteMethod write_mtpSpMtpT22I;
WriteMethod write_mtpSpMtpT23I;
WriteMethod write_mtpSpMtpT20A;
WriteMethod write_mtpSpMtpT21A;
WriteMethod write_mtpSpMtpT24I;
WriteMethod write_mtpSpMtpT1T;
WriteMethod write_mtpSpMtpT2T;
WriteMethod write_mtpSpMtpT1S;
WriteMethod write_mtpSpProfilePointer;
WriteMethod write_mtpSpNaPointer;
WriteMethod write_mtpSpFlags;
WriteMethod write_mtpSpUsers;
WriteMethod write_mtpSpAlarmStatus;
WriteMethod write_mtpSpRowStatus;
WriteMethod write_mtpSpStatsRowStatus;
WriteMethod write_mtpSpSiStatus;
WriteMethod write_mtpSpStudyStatus;
WriteMethod write_mtpSpStudyMapStatus;
WriteMethod write_mtpL3AdministrativeState;
WriteMethod write_mtpL3AsaProfilePointer;
WriteMethod write_mtpL3Name;
WriteMethod write_mtpL3RowStatus;
WriteMethod write_mtpRsProfileName;
WriteMethod write_mtpRsProfileTimerT8;
WriteMethod write_mtpRsProfileTimerT11;
WriteMethod write_mtpRsProfileTimerT15;
WriteMethod write_mtpRsProfileTimerT16;
WriteMethod write_mtpRsProfileTimerT18A;
WriteMethod write_mtpRsProfileRtDefault;
WriteMethod write_mtpRsProfileRowStatus;
WriteMethod write_mtpRsDest;
WriteMethod write_mtpRsFlags;
WriteMethod write_mtpRsAdministrativeState;
WriteMethod write_mtpRsAsaProfilePointer;
WriteMethod write_mtpRsLoadsharingInformation;
WriteMethod write_mtpRsLoadsharingObject;
WriteMethod write_mtpRsRemoteExchangeLabel;
WriteMethod write_mtpRsName;
WriteMethod write_mtpRsProfile;
WriteMethod write_mtpRsAlarmStatus;
WriteMethod write_mtpRsRowStatus;
WriteMethod write_mtpRsStatsStatus;
WriteMethod write_mtpRsCurrentValidIntervals;
WriteMethod write_mtpRsCurrentTimeDiscontinuity;
WriteMethod write_mtpRsCurrentReceivedOctetsOPC;
WriteMethod write_mtpRsCurrentTransmittedOctetsDPC;
WriteMethod write_mtpRsCurrentReceivedMSUsOpc;
WriteMethod write_mtpRsCurrentTransmittedMSUsDpc;
WriteMethod write_mtpRsCurrentRouteSetUnavailable;
WriteMethod write_mtpRsCurrentRouteSetUnavailableDuration;
WriteMethod write_mtpRsSiValidIntervals;
WriteMethod write_mtpRsSiTimeDiscontinuity;
WriteMethod write_mtpRsSiReceivedOctetsOpcSio;
WriteMethod write_mtpRsSiTransmittedOctetsDpcSio;
WriteMethod write_mtpRsSiReceivedMSUsOpcSio;
WriteMethod write_mtpRsSiTransmittedMSUsDpcSio;
WriteMethod write_mtpRsSiStatus;
WriteMethod write_mtpRtProfileTimerT6;
WriteMethod write_mtpRtProfileTimerT10;
WriteMethod write_mtpRtProfileRowStatus;
WriteMethod write_mtpRtLsPointer;
WriteMethod write_mtpRtAdministrativeState;
WriteMethod write_mtpRtInClsLoadsharingAlgorithm;
WriteMethod write_mtpRtFixedPriority;
WriteMethod write_mtpRtFlexiblePriority;
WriteMethod write_mtpRtPriorityMode;
WriteMethod write_mtpRtLoadsharingInformation;
WriteMethod write_mtpRtLoadsharingObject;
WriteMethod write_mtpRtName;
WriteMethod write_mtpRtSlsList;
WriteMethod write_mtpRtRlSlot;
WriteMethod write_mtpRtProfile;
WriteMethod write_mtpRtRowStatus;
WriteMethod write_mtpRtLsaNormalSlCode;
WriteMethod write_mtpRtLsaAlternativeSlCodeList;
WriteMethod write_mtpLsProfileTimerT6;
WriteMethod write_mtpLsProfileTimerT8;
WriteMethod write_mtpLsProfileTimerT10;
WriteMethod write_mtpLsProfileTimerT7;
WriteMethod write_mtpLsProfileTimerT19I;
WriteMethod write_mtpLsProfileTimerT21I;
WriteMethod write_mtpLsProfileTimerT25A;
WriteMethod write_mtpLsProfileTimerT28A;
WriteMethod write_mtpLsProfileTimerT29A;
WriteMethod write_mtpLsProfileTimerT30A;
WriteMethod write_mtpLsProfileName;
WriteMethod write_mtpLsProfileSlDefault;
WriteMethod write_mtpLsProfileRowStatus;
WriteMethod write_mtpLsAdjPc;
WriteMethod write_mtpLsRsId;
WriteMethod write_mtpLsMaxCapacity;
WriteMethod write_mtpLsCongestionControlMethod;
WriteMethod write_mtpLsPeriodicLinkTestFlag;
WriteMethod write_mtpLsPeriodicLinkTestFail;
WriteMethod write_mtpLsAdministrativeState;
WriteMethod write_mtpLsInLsLoadShareAlgorithm;
WriteMethod write_mtpLsProfilePointer;
WriteMethod write_mtpLsNumberOfNormallyActiveSignLinks;
WriteMethod write_mtpLsName;
WriteMethod write_mtpLsAsaProfilePointer;
WriteMethod write_mtpLsAlarmStatus;
WriteMethod write_mtpLsRowStatus;
WriteMethod write_mtpLsStatsStatus;
WriteMethod write_mtpLsCurrentValidIntervals;
WriteMethod write_mtpLsCurrentTimeDiscontinuity;
WriteMethod write_mtpLsCurrentAdjacentInaccessibleEvents;
WriteMethod write_mtpLsCurrentAdjacentInaccessibleDuration;
WriteMethod write_mtpLsCurrentSlsUnavailable;
WriteMethod write_mtpSlL3ProfileTimerT1;
WriteMethod write_mtpSlL3ProfileTimerT3;
WriteMethod write_mtpSlL3ProfileTimerT17;
WriteMethod write_mtpSlL3ProfileTimerT24I;
WriteMethod write_mtpSlL3ProfileName;
WriteMethod write_mtpSlL3ProfileTimerT2;
WriteMethod write_mtpSlL3ProfileTimerT4;
WriteMethod write_mtpSlL3ProfileTimerT5;
WriteMethod write_mtpSlL3ProfileTimerT12;
WriteMethod write_mtpSlL3ProfileTimerT13;
WriteMethod write_mtpSlL3ProfileTimerT14;
WriteMethod write_mtpSlL3ProfileTimerT19A;
WriteMethod write_mtpSlL3ProfileTimerT20A;
WriteMethod write_mtpSlL3ProfileTimerT21A;
WriteMethod write_mtpSlL3ProfileTimerT22I;
WriteMethod write_mtpSlL3ProfileTimerT23I;
WriteMethod write_mtpSlL3ProfileTimerT31A;
WriteMethod write_mtpSlL3ProfileTimerT32A;
WriteMethod write_mtpSlL3ProfileTimerT33A;
WriteMethod write_mtpSlL3ProfileTimerT34A;
WriteMethod write_mtpSlL3ProfileTimerT1T;
WriteMethod write_mtpSlL3ProfileTimerT2T;
WriteMethod write_mtpSlL3ProfileTimerT1S;
WriteMethod write_mtpSlL3ProfileL2Default;
WriteMethod write_mtpSlL3ProfileRowStatus;
WriteMethod write_mtpSlL2ProfileErrorCorrectionMethod;
WriteMethod write_mtpSlL2ProfileTransmissionRate;
WriteMethod write_mtpSlL2ProfileTimerT1;
WriteMethod write_mtpSlL2ProfileTimerT2;
WriteMethod write_mtpSlL2ProfileTimerT2L;
WriteMethod write_mtpSlL2ProfileTimerT2H;
WriteMethod write_mtpSlL2ProfileTimerT3;
WriteMethod write_mtpSlL2ProfileTimerT4N;
WriteMethod write_mtpSlL2ProfileTimerT4E;
WriteMethod write_mtpSlL2ProfileTimerT5;
WriteMethod write_mtpSlL2ProfileTimerT6;
WriteMethod write_mtpSlL2ProfileTimerT7;
WriteMethod write_mtpSlL2ProfileTbOnset1;
WriteMethod write_mtpSlL2ProfileTbAbate1;
WriteMethod write_mtpSlL2ProfileNumberOfThresholdLevels;
WriteMethod write_mtpSlL2ProfileCongestionCounting;
WriteMethod write_mtpSlL2ProfileCongestionReportingBaseObject;
WriteMethod write_mtpSlL2ProfileLoopDelay;
WriteMethod write_mtpSlL2ProfileName;
WriteMethod write_mtpSlL2ProfileTbOnset2;
WriteMethod write_mtpSlL2ProfileTbAbate2;
WriteMethod write_mtpSlL2ProfileTbOnset3;
WriteMethod write_mtpSlL2ProfileTbAbate3;
WriteMethod write_mtpSlL2ProfileTbDiscard1;
WriteMethod write_mtpSlL2ProfileTbDiscard2;
WriteMethod write_mtpSlL2ProfileTbDiscard3;
WriteMethod write_mtpSlL2ProfileTimerTx;
WriteMethod write_mtpSlL2ProfileTimerTy;
WriteMethod write_mtpSlL2ProfileNumberOfCongestionStates;
WriteMethod write_mtpSlL2ProfileInitialLevelOfCongestion;
WriteMethod write_mtpSlL2ProfileMaxMSUsRetransN1;
WriteMethod write_mtpSlL2ProfileMaxOctRetransN2;
WriteMethod write_mtpSlL2ProfileReceiveCongestionThresholdOnset;
WriteMethod write_mtpSlL2ProfileReceiveCongestionThresholdAbate;
WriteMethod write_mtpSlL2ProfileReceiveCongestionThresholdDiscard;
WriteMethod write_mtpSlL2ProfileM;
WriteMethod write_mtpSlL2ProfileRowStatus;
WriteMethod write_mtpSlSlsCodeCurrentList;
WriteMethod write_mtpSlMaxCapacitySL;
WriteMethod write_mtpSlAdministrativeState;
WriteMethod write_mtpSlMtpL2ProtocolProfilePointer;
WriteMethod write_mtpSlSignTermPointer;
WriteMethod write_mtpSlSignDataLinkTpPointer;
WriteMethod write_mtpSlLocalInhibit;
WriteMethod write_mtpSlLocalUninhibit;
WriteMethod write_mtpSlReplaceSt;
WriteMethod write_mtpSlAsaProfilePointer;
WriteMethod write_mtpSlRelatedLinkGroupNumber;
WriteMethod write_mtpSlSdlList;
WriteMethod write_mtpSlTest;
WriteMethod write_mtpSlName;
WriteMethod write_mtpSlSdtList;
WriteMethod write_mtpSlSlsCodeNormalList;
WriteMethod write_mtpSlL3ProfilePointer;
WriteMethod write_mtpSlAlarmStatus;
WriteMethod write_mtpSlRowStatus;
WriteMethod write_mtpSlSdlListPointer;
WriteMethod write_mtpSlSdlListRowStatus;
WriteMethod write_mtpSlSdtListPointer;
WriteMethod write_mtpSlSdtListRowStatus;
WriteMethod write_mtpNbTransmissionRate;
WriteMethod write_mtpNbTimerT8;
WriteMethod write_mtpNbTin;
WriteMethod write_mtpNbTie;
WriteMethod write_mtpNbT;
WriteMethod write_mtpNbD;
WriteMethod write_mtpNbTe;
WriteMethod write_mtpNbDe;
WriteMethod write_mtpNbUe;
WriteMethod write_mtpNbN;
WriteMethod write_mtpNbm;
WriteMethod write_mtpNbb;
WriteMethod write_mtpNbf;
WriteMethod write_mtpNbRowStatus;
WriteMethod write_mtpSaalBufferRelease;
WriteMethod write_mtpSaalMaxCc;
WriteMethod write_mtpSaalMaxNrp;
WriteMethod write_mtpSaalMaxInformationFieldLength;
WriteMethod write_mtpSaalMaxLengthSscopUuField;
WriteMethod write_mtpSaalMaxPd;
WriteMethod write_mtpSaalMaxSscopCreditToPeer;
WriteMethod write_mtpSaalMaxStat;
WriteMethod write_mtpSaalN1;
WriteMethod write_mtpSaalNniLayerManagementProvingState;
WriteMethod write_mtpSaalNniLayerManagementTimerNoCredit;
WriteMethod write_mtpSaalNniLayerManagementTimerRepeatSrec;
WriteMethod write_mtpSaalNniTimerT1;
WriteMethod write_mtpSaalNniTimerT2;
WriteMethod write_mtpSaalNniTimerT3;
WriteMethod write_mtpSaalSscopTimerCc;
WriteMethod write_mtpSaalSscopTimerIdle;
WriteMethod write_mtpSaalSscopTimerKeepAlive;
WriteMethod write_mtpSaalSscopTimerNoResponse;
WriteMethod write_mtpSaalSscopTimerPoll;
WriteMethod write_mtpSaalTransmissionRateIntervalLower;
WriteMethod write_mtpSaalTransmissionRateIntervalUpper;
WriteMethod write_mtpSaalEgressTransmissionRateIntervalLower;
WriteMethod write_mtpSaalEgressTransmissionRateIntervalUpper;
WriteMethod write_mtpSaalPollAfterRetransmission;
WriteMethod write_mtpSaalRowStatus;
WriteMethod write_mtpM2paN1;
WriteMethod write_mtpM2paProving;
WriteMethod write_mtpM2paManagementProvingState;
WriteMethod write_mtpM2paLoopDelayLower;
WriteMethod write_mtpM2paLoopDelayUpper;
WriteMethod write_mtpM2paTransmissionRateIntervalLower;
WriteMethod write_mtpM2paTransmissionRateIntervalUpper;
WriteMethod write_mtpM2paSctpNoDelay;
WriteMethod write_mtpM2paSctpMaxseg;
WriteMethod write_mtpM2paSctpHeartbeatItvl;
WriteMethod write_mtpM2paSctpHeartbeat;
WriteMethod write_mtpM2paSctpRtoInitial;
WriteMethod write_mtpM2paSctpRtoMin;
WriteMethod write_mtpM2paSctpRtoMax;
WriteMethod write_mtpM2paSctpPathMaxRetrans;
WriteMethod write_mtpM2paSctpCookieLife;
WriteMethod write_mtpM2paSctpCookieInc;
WriteMethod write_mtpM2paSctpMaxInitRetries;
WriteMethod write_mtpM2paSctpMaxBurst;
WriteMethod write_mtpM2paSctpAssocMaxRetrans;
WriteMethod write_mtpM2paSctpSackDelay;
WriteMethod write_mtpM2paSctpLifetime;
WriteMethod write_mtpM2paProvingAttempts;
WriteMethod write_mtpM2paRowStatus;
WriteMethod write_mtpSdtAdministrativeState;
WriteMethod write_mtpSdtEquipmentPointer;
WriteMethod write_mtpSdtName;
WriteMethod write_mtpSdtProfilePointer;
WriteMethod write_mtpSdtRowStatus;
WriteMethod write_mtpSdlAdjPc;
WriteMethod write_mtpSdlTransmissionRate;
WriteMethod write_mtpSdlLoopDelay;
WriteMethod write_mtpSdlOperationalState;
WriteMethod write_mtpSdlEquipmentPointer;
WriteMethod write_mtpSdlCIC;
WriteMethod write_mtpSdlName;
WriteMethod write_mtpSdlStmChannel;
WriteMethod write_mtpSdlVcTTpPointer;
WriteMethod write_mtpSdlRowStatus;
WriteMethod write_mtpM2paDefaultSctpNoDelay;
WriteMethod write_mtpM2paDefaultSctpMaxseg;
WriteMethod write_mtpM2paDefaultSctpHeartbeatItvl;
WriteMethod write_mtpM2paDefaultSctpHeartbeat;
WriteMethod write_mtpM2paDefaultSctpRtoInitial;
WriteMethod write_mtpM2paDefaultSctpRtoMin;
WriteMethod write_mtpM2paDefaultSctpRtoMax;
WriteMethod write_mtpM2paDefaultSctpPathMaxRetrans;
WriteMethod write_mtpM2paDefaultSctpCookieLife;
WriteMethod write_mtpM2paDefaultSctpCookieInc;
WriteMethod write_mtpM2paDefaultSctpMaxInitRetries;
WriteMethod write_mtpM2paDefaultSctpMaxBurst;
WriteMethod write_mtpM2paDefaultSctpAssocMaxRetrans;
WriteMethod write_mtpM2paDefaultSctpSackDelay;
WriteMethod write_mtpM2paDefaultSctpLifetime;

#endif				/* __LOCAL_MTPMIB2_H__ */
