/*****************************************************************************

 @(#) $Id: mtpOmMIB.h,v 0.9.2.10 2009-01-19 13:31:47 brian Exp $

 -----------------------------------------------------------------------------

 Copyright (c) 2008-2009  Monavacon Limited <http://www.monavacon.com/>
 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; version 3 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 -----------------------------------------------------------------------------

 Last Modified $Date: 2009-01-19 13:31:47 $ by $Author: brian $

 -----------------------------------------------------------------------------

 $Log: mtpOmMIB.h,v $
 Revision 0.9.2.10  2009-01-19 13:31:47  brian
 - updating standalone agents

 Revision 0.9.2.9  2009-01-14 14:30:04  brian
 - working up agents

 Revision 0.9.2.8  2009-01-10 17:09:19  brian
 - updated agents

 Revision 0.9.2.7  2009-01-04 13:16:04  brian
 - updated agents

 Revision 0.9.2.6  2009-01-03 10:51:05  brian
 - updated agent

 Revision 0.9.2.5  2009-01-02 15:04:14  brian
 - updated agents

 Revision 0.9.2.4  2008-12-31 16:04:46  brian
 - updated mibs

 Revision 0.9.2.3  2008-12-27 15:29:47  brian
 - split MTP and MTP OM mib

 Revision 0.9.2.2  2008-12-24 13:08:25  brian
 - building ss7confd

 *****************************************************************************/

#ifndef __LOCAL_MTPOMMIB_H__
#define __LOCAL_MTPOMMIB_H__

#ident "@(#) $RCSfile: mtpOmMIB.h,v $ $Name:  $($Revision: 0.9.2.10 $) Copyright (c) 2008-2009 Monavacon Limited."

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */

#undef MASTER
extern const char sa_program[];
extern int sa_fclose;			/* default close files between requests */
extern int sa_changed;			/* indication to reread MIB configuration */
extern int sa_stats_refresh;		/* indications that statistics, the mib or its tables need to be refreshed */
extern int sa_request;			/* request number for per-request actions */

/* our storage structure(s) */
struct mtpOmMIB_data {
	uint mtpOmMIB_request;
	oid *mtpOm1stAndIntervalActivate;	/* WriteOnly */
	size_t mtpOm1stAndIntervalActivateLen;
	oid *mtpOm1stAndIntervalDeactivate;	/* WriteOnly */
	size_t mtpOm1stAndIntervalDeactivateLen;
	oid *mtpOm5MinActivate;		/* WriteOnly */
	size_t mtpOm5MinActivateLen;
	oid *mtpOm5MinDeaActivate;	/* WriteOnly */
	size_t mtpOm5MinDeaActivateLen;
	oid *mtpOm15MinActivate;	/* WriteOnly */
	size_t mtpOm15MinActivateLen;
	oid *mtpOm15MinDeaActivate;	/* WriteOnly */
	size_t mtpOm15MinDeaActivateLen;
	long mtpOmDiscontinuityTime;	/* ReadOnly */
	long mtpOmTimeStamp;		/* ReadOnly */
	ulong mtpOm5MinMaxIntervals;	/* ReadWrite */
	ulong mtpOm15MinMaxIntervals;	/* ReadWrite */
};
struct mtpOmSpTable_data {
	uint mtpOmSpTable_request;
	uint mtpOmSpTable_refs;
	ulong mtpSpId;			/* NoAccess */
	long mtpOmSpValidIntervals;	/* ReadOnly */
	long mtpOmSpTimeDiscontinuity;	/* ReadOnly */
	long mtpOmSpDiscardedMSUs;	/* ReadOnly */
	long mtpOmSpReceivedTFCstatus0;	/* ReadOnly */
	long mtpOmSpReceivedTFCstatus1;	/* ReadOnly */
	long mtpOmSpReceivedTFCstatus2;	/* ReadOnly */
	long mtpOmSpOctetsXferred;	/* ReadOnly */
};
struct mtpOmSpInt5minTable_data {
	uint mtpOmSpInt5minTable_request;
	uint mtpOmSpInt5minTable_refs;
	ulong mtpSpId;			/* NoAccess */
	ulong mtpOmSpInt5minInterval;	/* NoAccess */
	long mtpOmSpInt5minTimeStamp;	/* ReadOnly */
	long mtpOmSpInt5minDiscardedMSUs;	/* ReadOnly */
	long mtpOmSpInt5minReceivedTFCstatus0;	/* ReadOnly */
	long mtpOmSpInt5minReceivedTFCstatus1;	/* ReadOnly */
	long mtpOmSpInt5minReceivedTFCstatus2;	/* ReadOnly */
	long mtpOmSpInt5minOctetsXferred;	/* ReadOnly */
};
struct mtpOmSpInt15minTable_data {
	uint mtpOmSpInt15minTable_request;
	uint mtpOmSpInt15minTable_refs;
	ulong mtpSpId;			/* NoAccess */
	ulong mtpOmSpInt15minInterval;	/* NoAccess */
	long mtpOmSpInt15minTimeStamp;	/* ReadOnly */
	long mtpOmSpInt15minDiscardedMSUs;	/* ReadOnly */
	long mtpOmSpInt15minReceivedTFCstatus0;	/* ReadOnly */
	long mtpOmSpInt15minReceivedTFCstatus1;	/* ReadOnly */
	long mtpOmSpInt15minReceivedTFCstatus2;	/* ReadOnly */
	long mtpOmSpInt15minOctetsXferred;	/* ReadOnly */
};
struct mtpOmSpSiTable_data {
	uint mtpOmSpSiTable_request;
	uint mtpOmSpSiTable_refs;
	ulong mtpSpId;			/* NoAccess */
	long mtpOmSpSiCode;		/* NoAccess */
	long mtpOmSpSiValidIntervals;	/* ReadOnly */
	long mtpOmSpSiTimeDiscontinuity;	/* ReadOnly */
	long mtpOmSpSiTransmittedUPUnavailable;	/* ReadOnly */
	long mtpOmSpSiReceivedUPUnavailable;	/* ReadOnly */
	long mtpOmSpSiHandledOctetsSIO;	/* ReadOnly */
	long mtpOmSpSiStatus;		/* Create */
};
struct mtpOmSpSiInt5minTable_data {
	uint mtpOmSpSiInt5minTable_request;
	uint mtpOmSpSiInt5minTable_refs;
	ulong mtpSpId;			/* NoAccess */
	long mtpOmSpSiCode;		/* NoAccess */
	ulong mtpOmSpSiInt5minInterval;	/* NoAccess */
	long mtpOmSpSiInt5minTimeStamp;	/* ReadOnly */
	long mtpOmSpSiInt5minTransmittedUPUnavailable;	/* ReadOnly */
	long mtpOmSpSiInt5minReceivedUPUnavailable;	/* ReadOnly */
	long mtpOmSpSiInt5minHandledOctetsSIO;	/* ReadOnly */
};
struct mtpOmSpSiInt15minTable_data {
	uint mtpOmSpSiInt15minTable_request;
	uint mtpOmSpSiInt15minTable_refs;
	ulong mtpSpId;			/* NoAccess */
	long mtpOmSpSiCode;		/* NoAccess */
	ulong mtpOmSpSiInt15minInterval;	/* NoAccess */
	long mtpOmSpSiInt15minTimeStamp;	/* ReadOnly */
	long mtpOmSpSiInt15minTransmittedUPUnavailable;	/* ReadOnly */
	long mtpOmSpSiInt15minReceivedUPUnavailable;	/* ReadOnly */
	long mtpOmSpSiInt15minHandledOctetsSIO;	/* ReadOnly */
};
struct mtpOmSpStudyTable_data {
	uint mtpOmSpStudyTable_request;
	uint mtpOmSpStudyTable_refs;
	ulong mtpOmSpStudyId;		/* NoAccess */
	long mtpOmSpStudyValidIntervals;	/* ReadOnly */
	long mtpOmSpStudyTimeDiscontinuity;	/* ReadOnly */
	long mtpOmSpStudyHandledOctetsOpcDpcSio;	/* ReadOnly */
	long mtpOmSpStudyHandledMSUsOpcDpcSio;	/* ReadOnly */
	long mtpOmSpStudyStatus;	/* Create */
};
struct mtpOmSpStudyInt5minTable_data {
	uint mtpOmSpStudyInt5minTable_request;
	uint mtpOmSpStudyInt5minTable_refs;
	ulong mtpOmSpStudyId;		/* NoAccess */
	ulong mtpOmSpStudyInt5minInterval;	/* NoAccess */
	long mtpOmSpStudyInt5minTimeStamp;	/* ReadOnly */
	long mtpOmSpStudyInt5minHandledOctetsOpcDpcSio;	/* ReadOnly */
	long mtpOmSpStudyInt5minHandledMSUsOpcDpcSio;	/* ReadOnly */
};
struct mtpOmSpStudyInt15minTable_data {
	uint mtpOmSpStudyInt15minTable_request;
	uint mtpOmSpStudyInt15minTable_refs;
	ulong mtpOmSpStudyId;		/* NoAccess */
	ulong mtpOmSpStudyInt15minInterval;	/* NoAccess */
	long mtpOmSpStudyInt15minTimeStamp;	/* ReadOnly */
	long mtpOmSpStudyInt15minHandledOctetsOpcDpcSio;	/* ReadOnly */
	long mtpOmSpStudyInt15minHandledMSUsOpcDpcSio;	/* ReadOnly */
};
struct mtpOmSpStudyMapTable_data {
	uint mtpOmSpStudyMapTable_request;
	uint mtpOmSpStudyMapTable_refs;
	ulong mtpSpId;			/* NoAccess */
	long mtpOmSpSiCode;		/* NoAccess */
	ulong mtpOmSpStudyId;		/* NoAccess */
	ulong mtpOmOpcRsId;		/* NoAccess */
	ulong mtpOmDpcRsId;		/* NoAccess */
	long mtpOmSpStudyMapStatus;	/* Create */
};
struct mtpOmRsTable_data {
	uint mtpOmRsTable_request;
	uint mtpOmRsTable_refs;
	ulong mtpSpId;			/* NoAccess */
	ulong mtpRsId;			/* NoAccess */
	long mtpOmRsValidIntervals;	/* ReadOnly */
	long mtpOmRsTimeDiscontinuity;	/* ReadOnly */
	long mtpOmRsReceivedOctetsOPC;	/* ReadOnly */
	long mtpOmRsTransmittedOctetsDPC;	/* ReadOnly */
	long mtpOmRsReceivedMSUsOpc;	/* ReadOnly */
	long mtpOmRsTransmittedMSUsDpc;	/* ReadOnly */
	long mtpOmRsRouteSetUnavailable;	/* ReadOnly */
	long mtpOmRsRouteSetUnavailableDuration;	/* ReadOnly */
};
struct mtpOmRsInt5minTable_data {
	uint mtpOmRsInt5minTable_request;
	uint mtpOmRsInt5minTable_refs;
	ulong mtpSpId;			/* NoAccess */
	ulong mtpRsId;			/* NoAccess */
	ulong mtpOmRsInt5minInterval;	/* NoAccess */
	long mtpOmRsInt5minTimeStamp;	/* ReadOnly */
	long mtpOmRsInt5minReceivedOctetsOPC;	/* ReadOnly */
	long mtpOmRsInt5minTransmittedOctetsDPC;	/* ReadOnly */
	long mtpOmRsInt5minReceivedMSUsOpc;	/* ReadOnly */
	long mtpOmRsInt5minTransmittedMSUsDpc;	/* ReadOnly */
	long mtpOmRsInt5minRouteSetUnavailable;	/* ReadOnly */
	long mtpOmRsInt5minRouteSetUnavailableDuration;	/* ReadOnly */
};
struct mtpOmRsInt15minTable_data {
	uint mtpOmRsInt15minTable_request;
	uint mtpOmRsInt15minTable_refs;
	ulong mtpSpId;			/* NoAccess */
	ulong mtpRsId;			/* NoAccess */
	ulong mtpOmRsInt15minInterval;	/* NoAccess */
	long mtpOmRsInt15minTimeStamp;	/* ReadOnly */
	long mtpOmRsInt15minReceivedOctetsOPC;	/* ReadOnly */
	long mtpOmRsInt15minTransmittedOctetsDPC;	/* ReadOnly */
	long mtpOmRsInt15minReceivedMSUsOpc;	/* ReadOnly */
	long mtpOmRsInt15minTransmittedMSUsDpc;	/* ReadOnly */
	long mtpOmRsInt15minRouteSetUnavailable;	/* ReadOnly */
	long mtpOmRsInt15minRouteSetUnavailableDuration;	/* ReadOnly */
};
struct mtpOmRsSiTable_data {
	uint mtpOmRsSiTable_request;
	uint mtpOmRsSiTable_refs;
	ulong mtpSpId;			/* NoAccess */
	ulong mtpRsId;			/* NoAccess */
	long mtpOmRsSiCode;		/* NoAccess */
	long mtpOmRsSiValidIntervals;	/* Create */
	long mtpOmRsSiTimeDiscontinuity;	/* Create */
	long mtpOmRsSiReceivedOctetsOpcSio;	/* ReadOnly */
	long mtpOmRsSiTransmittedOctetsDpcSio;	/* ReadOnly */
	long mtpOmRsSiReceivedMSUsOpcSio;	/* ReadOnly */
	long mtpOmRsSiTransmittedMSUsDpcSio;	/* ReadOnly */
	long mtpOmRsSiStatus;		/* ReadOnly */
};
struct mtpOmRsSiInt5minTable_data {
	uint mtpOmRsSiInt5minTable_request;
	uint mtpOmRsSiInt5minTable_refs;
	ulong mtpSpId;			/* NoAccess */
	ulong mtpRsId;			/* NoAccess */
	long mtpOmRsSiCode;		/* NoAccess */
	ulong mtpOmRsSiInt5minInterval;	/* NoAccess */
	long mtpOmRsSiInt5minTimeStamp;	/* ReadOnly */
	long mtpOmRsSiInt5minReceivedOctetsOpcSio;	/* ReadOnly */
	long mtpOmRsSiInt5minTransmittedOctetsDpcSio;	/* ReadOnly */
	long mtpOmRsSiInt5minReceivedMSUsOpcSio;	/* ReadOnly */
	long mtpOmRsSiInt5minTransmittedMSUsDpcSio;	/* ReadOnly */
};
struct mtpOmRsSiInt15minTable_data {
	uint mtpOmRsSiInt15minTable_request;
	uint mtpOmRsSiInt15minTable_refs;
	ulong mtpSpId;			/* NoAccess */
	ulong mtpRsId;			/* NoAccess */
	long mtpOmRsSiCode;		/* NoAccess */
	ulong mtpOmRsSiInt15minInterval;	/* NoAccess */
	long mtpOmRsSiInt15minTimeStamp;	/* ReadOnly */
	long mtpOmRsSiInt15minReceivedOctetsOpcSio;	/* ReadOnly */
	long mtpOmRsSiInt15minTransmittedOctetsDpcSio;	/* ReadOnly */
	long mtpOmRsSiInt15minReceivedMSUsOpcSio;	/* ReadOnly */
	long mtpOmRsSiInt15minTransmittedMSUsDpcSio;	/* ReadOnly */
};
struct mtpOmLsTable_data {
	uint mtpOmLsTable_request;
	uint mtpOmLsTable_refs;
	ulong mtpSpId;			/* NoAccess */
	ulong mtpLsId;			/* NoAccess */
	long mtpOmLsValidIntervals;	/* ReadOnly */
	long mtpOmLsTimeDiscontinuity;	/* ReadOnly */
	long mtpOmLsAdjacentInaccessibleEvents;	/* ReadOnly */
	long mtpOmLsAdjacentInaccessibleDuration;	/* ReadOnly */
	long mtpOmLsSlsUnavailable;	/* ReadOnly */
};
struct mtpOmLsInt5minTable_data {
	uint mtpOmLsInt5minTable_request;
	uint mtpOmLsInt5minTable_refs;
	ulong mtpSpId;			/* NoAccess */
	ulong mtpLsId;			/* NoAccess */
	ulong mtpOmLsInt5minInterval;	/* NoAccess */
	long mtpOmLsInt5minTimeStamp;	/* ReadOnly */
	long mtpOmLsInt5minAdjacentInaccessibleEvents;	/* ReadOnly */
	long mtpOmLsInt5minAdjacentInaccessibleDuration;	/* ReadOnly */
	long mtpOmLsInt5minSlsUnavailable;	/* ReadOnly */
};
struct mtpOmLsInt15minTable_data {
	uint mtpOmLsInt15minTable_request;
	uint mtpOmLsInt15minTable_refs;
	ulong mtpSpId;			/* NoAccess */
	ulong mtpLsId;			/* NoAccess */
	ulong mtpOmLsInt15minInterval;	/* NoAccess */
	long mtpOmLsInt15minTimeStamp;	/* ReadOnly */
	long mtpOmLsInt15minAdjacentInaccessibleEvents;	/* ReadOnly */
	long mtpOmLsInt15minAdjacentInaccessibleDuration;	/* ReadOnly */
	long mtpOmLsInt15minSlsUnavailable;	/* ReadOnly */
};
struct mtpOmSlStatsTable_data {
	uint mtpOmSlStatsTable_request;
	uint mtpOmSlStatsTable_refs;
	ulong mtpMsId;			/* NoAccess */
	ulong mtpSpId;			/* NoAccess */
	ulong mtpLsId;			/* NoAccess */
	ulong mtpSlId;			/* NoAccess */
	long mtpOmSlStatsDurInService;	/* ReadOnly */
	long mtpOmSlStatsFailAlignOrProving;	/* ReadOnly */
	long mtpOmSlStatsNacksReceived;	/* ReadOnly */
	long mtpOmSlStatsDurUnavail;	/* ReadOnly */
	long mtpOmSlStatsDurUnavailFailed;	/* ReadOnly */
	long mtpOmSlStatsDurUnavailRpo;	/* ReadOnly */
	long mtpOmSlStatsSibsSent;	/* ReadOnly */
	long mtpOmSlStatsTranSioSifOctets;	/* ReadOnly */
	long mtpOmSlStatsRetransOctets;	/* ReadOnly */
	long mtpOmSlStatsTranMsus;	/* ReadOnly */
	long mtpOmSlStatsRecvSioSifOctets;	/* ReadOnly */
	long mtpOmSlStatsRecvMsus;	/* ReadOnly */
	long mtpOmSlStatsCongOnsetInd0;	/* ReadOnly */
	long mtpOmSlStatsCongOnsetInd1;	/* ReadOnly */
	long mtpOmSlStatsCongOnsetInd2;	/* ReadOnly */
	long mtpOmSlStatsCongOnsetInd3;	/* ReadOnly */
	long mtpOmSlStatsDurCongStatus0;	/* ReadOnly */
	long mtpOmSlStatsDurCongStatus1;	/* ReadOnly */
	long mtpOmSlStatsDurCongStatus2;	/* ReadOnly */
	long mtpOmSlStatsDurCongStatus3;	/* ReadOnly */
	long mtpOmSlStatsCongDiscdInd0;	/* ReadOnly */
	long mtpOmSlStatsCongDiscdInd1;	/* ReadOnly */
	long mtpOmSlStatsCongDiscdInd2;	/* ReadOnly */
	long mtpOmSlStatsCongDiscdInd3;	/* ReadOnly */
};
struct mtpOmSlL3Table_data {
	uint mtpOmSlL3Table_request;
	uint mtpOmSlL3Table_refs;
	ulong mtpSpId;			/* NoAccess */
	ulong mtpLsId;			/* NoAccess */
	long mtpSlSlCode;		/* NoAccess */
	long mtpOmSlL3ValidIntervals;	/* ReadOnly */
	long mtpOmSlL3TimeDiscontinuity;	/* ReadOnly */
	long mtpOmSlL3SlUnavailabilityDuration;	/* ReadOnly */
	long mtpOmSlL3SlLocalInhibition;	/* ReadOnly */
	long mtpOmSlL3SlRemoteInhibition;	/* ReadOnly */
	long mtpOmSlL3SlFailed;		/* ReadOnly */
	long mtpOmSlL3SlRemoteProcOutage;	/* ReadOnly */
	long mtpOmSlL3LocalMgmtInhibit;	/* ReadOnly */
	long mtpOmSlL3LocalMgmtUninhibit;	/* ReadOnly */
	long mtpOmSlL3LocalBusy;	/* ReadOnly */
	long mtpOmSlL3SlCongestedStarts;	/* ReadOnly */
	long mtpOmSlL3SlCongestedDuration;	/* ReadOnly */
	long mtpOmSlL3SlCongestionStops;	/* ReadOnly */
	long mtpOmSlL3DiscardedMSUs;	/* ReadOnly */
	long mtpOmSlL3CongestionEventsMSULoss;	/* ReadOnly */
	long mtpOmSlL3Changeovers;	/* ReadOnly */
	long mtpOmSlL3Changebacks;	/* ReadOnly */
	long mtpOmSlL3Restorations;	/* ReadOnly */
};
struct mtpOmSlL3Int5minTable_data {
	uint mtpOmSlL3Int5minTable_request;
	uint mtpOmSlL3Int5minTable_refs;
	ulong mtpSpId;			/* NoAccess */
	ulong mtpLsId;			/* NoAccess */
	long mtpSlSlCode;		/* NoAccess */
	ulong mtpOmSlL3Int5minInterval;	/* NoAccess */
	long mtpOmSlL3Int5minTimeStamp;	/* ReadOnly */
	long mtpOmSlL3Int5minSlUnavailabilityDuration;	/* ReadOnly */
	long mtpOmSlL3Int5minSlLocalInhibition;	/* ReadOnly */
	long mtpOmSlL3Int5minSlRemoteInhibition;	/* ReadOnly */
	long mtpOmSlL3Int5minSlFailed;	/* ReadOnly */
	long mtpOmSlL3Int5minSlRemoteProcOutage;	/* ReadOnly */
	long mtpOmSlL3Int5minLocalMgmtInhibit;	/* ReadOnly */
	long mtpOmSlL3Int5minLocalMgmtUninhibit;	/* ReadOnly */
	long mtpOmSlL3Int5minLocalBusy;	/* ReadOnly */
	long mtpOmSlL3Int5minSlCongestedStarts;	/* ReadOnly */
	long mtpOmSlL3Int5minSlCongestedDuration;	/* ReadOnly */
	long mtpOmSlL3Int5minSlCongestionStops;	/* ReadOnly */
	long mtpOmSlL3Int5minDiscardedMSUs;	/* ReadOnly */
	long mtpOmSlL3Int5minCongestionEventsMSULoss;	/* ReadOnly */
	long mtpOmSlL3Int5minChangeovers;	/* ReadOnly */
	long mtpOmSlL3Int5minChangebacks;	/* ReadOnly */
	long mtpOmSlL3Int5minRestorations;	/* ReadOnly */
};
struct mtpOmSlL3Int15minTable_data {
	uint mtpOmSlL3Int15minTable_request;
	uint mtpOmSlL3Int15minTable_refs;
	ulong mtpSpId;			/* NoAccess */
	ulong mtpLsId;			/* NoAccess */
	long mtpSlSlCode;		/* NoAccess */
	ulong mtpOmSlL3Int15minInterval;	/* NoAccess */
	long mtpOmSlL3Int15minTimeStamp;	/* ReadOnly */
	long mtpOmSlL3Int15minSlUnavailabilityDuration;	/* ReadOnly */
	long mtpOmSlL3Int15minSlLocalInhibition;	/* ReadOnly */
	long mtpOmSlL3Int15minSlRemoteInhibition;	/* ReadOnly */
	long mtpOmSlL3Int15minSlFailed;	/* ReadOnly */
	long mtpOmSlL3Int15minSlRemoteProcOutage;	/* ReadOnly */
	long mtpOmSlL3Int15minLocalMgmtInhibit;	/* ReadOnly */
	long mtpOmSlL3Int15minLocalMgmtUninhibit;	/* ReadOnly */
	long mtpOmSlL3Int15minLocalBusy;	/* ReadOnly */
	long mtpOmSlL3Int15minSlCongestedStarts;	/* ReadOnly */
	long mtpOmSlL3Int15minSlCongestedDuration;	/* ReadOnly */
	long mtpOmSlL3Int15minSlCongestionStops;	/* ReadOnly */
	long mtpOmSlL3Int15minDiscardedMSUs;	/* ReadOnly */
	long mtpOmSlL3Int15minCongestionEventsMSULoss;	/* ReadOnly */
	long mtpOmSlL3Int15minChangeovers;	/* ReadOnly */
	long mtpOmSlL3Int15minChangebacks;	/* ReadOnly */
	long mtpOmSlL3Int15minRestorations;	/* ReadOnly */
};
struct mtpOmSlL2Table_data {
	uint mtpOmSlL2Table_request;
	uint mtpOmSlL2Table_refs;
	ulong mtpSpId;			/* NoAccess */
	ulong mtpLsId;			/* NoAccess */
	long mtpSlSlCode;		/* NoAccess */
	long mtpOmSlL2ValidIntervals;	/* ReadOnly */
	long mtpOmSlL2TimeDiscontinuity;	/* ReadOnly */
	long mtpOmSlL2SlInServiceDuration;	/* ReadOnly */
	long mtpOmSlL2SlAlignment;	/* ReadOnly */
	long mtpOmSlL2SignUnitsReceived;	/* ReadOnly */
	long mtpOmSlL2NegAckReceived;	/* ReadOnly */
	long mtpOmSlL2TransmittedOctetsSIFSIO;	/* ReadOnly */
	long mtpOmSlL2RetransmittedOctets;	/* ReadOnly */
	long mtpOmSlL2TransmittedMSUs;	/* ReadOnly */
	long mtpOmSlL2ReceivedOctetsSIFSIO;	/* ReadOnly */
	long mtpOmSlL2ReceivedMSUs;	/* ReadOnly */
};
struct mtpOmSlL2Int5minTable_data {
	uint mtpOmSlL2Int5minTable_request;
	uint mtpOmSlL2Int5minTable_refs;
	ulong mtpSpId;			/* NoAccess */
	ulong mtpLsId;			/* NoAccess */
	long mtpSlSlCode;		/* NoAccess */
	ulong mtpOmSlL2Int5minInterval;	/* NoAccess */
	long mtpOmSlL2Int5minTimestamp;	/* ReadOnly */
	long mtpOmSlL2Int5minSlInServiceDuration;	/* ReadOnly */
	long mtpOmSlL2Int5minSlAlignment;	/* ReadOnly */
	long mtpOmSlL2Int5minSignUnitsReceived;	/* ReadOnly */
	long mtpOmSlL2Int5minNegAckReceived;	/* ReadOnly */
	long mtpOmSlL2Int5minTransmittedOctetsSIFSIO;	/* ReadOnly */
	long mtpOmSlL2Int5minRetransmittedOctets;	/* ReadOnly */
	long mtpOmSlL2Int5minTransmittedMSUs;	/* ReadOnly */
	long mtpOmSlL2Int5minReceivedOctetsSIFSIO;	/* ReadOnly */
	long mtpOmSlL2Int5minReceivedMSUs;	/* ReadOnly */
};
struct mtpOmSlL2Int15minTable_data {
	uint mtpOmSlL2Int15minTable_request;
	uint mtpOmSlL2Int15minTable_refs;
	ulong mtpSpId;			/* NoAccess */
	ulong mtpLsId;			/* NoAccess */
	long mtpSlSlCode;		/* NoAccess */
	ulong mtpOmSlL2Int15minInterval;	/* NoAccess */
	long mtpOmSlL2Int15minTimestamp;	/* ReadOnly */
	long mtpOmSlL2Int15minSlInServiceDuration;	/* ReadOnly */
	long mtpOmSlL2Int15minSlAlignment;	/* ReadOnly */
	long mtpOmSlL2Int15minSignUnitsReceived;	/* ReadOnly */
	long mtpOmSlL2Int15minNegAckReceived;	/* ReadOnly */
	long mtpOmSlL2Int15minTransmittedOctetsSIFSIO;	/* ReadOnly */
	long mtpOmSlL2Int15minRetransmittedOctets;	/* ReadOnly */
	long mtpOmSlL2Int15minTransmittedMSUs;	/* ReadOnly */
	long mtpOmSlL2Int15minReceivedOctetsSIFSIO;	/* ReadOnly */
	long mtpOmSlL2Int15minReceivedMSUs;	/* ReadOnly */
};
struct mtpOmSdtStatsTable_data {
	uint mtpOmSdtStatsTable_request;
	uint mtpOmSdtStatsTable_refs;
	ulong mtpMsId;			/* NoAccess */
	ulong mtpSdtId;			/* NoAccess */
	long mtpOmSdtStatsTxBytes;	/* ReadOnly */
	long mtpOmSdtStatsTxSus;	/* ReadOnly */
	long mtpOmSdtStatsTxSusRepeated;	/* ReadOnly */
	long mtpOmSdtStatsTxUnderruns;	/* ReadOnly */
	long mtpOmSdtStatsTxAborts;	/* ReadOnly */
	long mtpOmSdtStatsTxBufferOverflows;	/* ReadOnly */
	long mtpOmSdtStatsTxSusInError;	/* ReadOnly */
	long mtpOmSdtStatsRxBytes;	/* ReadOnly */
	long mtpOmSdtStatsRxSusCompressed;	/* ReadOnly */
	long mtpOmSdtStatsRxOverruns;	/* ReadOnly */
	long mtpOmSdtStatsRxAborts;	/* ReadOnly */
	long mtpOmSdtStatsRxBufferOverflows;	/* ReadOnly */
	long mtpOmSdtStatsRxSusInError;	/* ReadOnly */
	long mtpOmSdtStatsRxSyncTransitions;	/* ReadOnly */
	long mtpOmSdtStatsRxBitsOctetCounted;	/* ReadOnly */
	long mtpOmSdtStatsRxCrcErrors;	/* ReadOnly */
	long mtpOmSdtStatsRxFrameErrors;	/* ReadOnly */
	long mtpOmSdtStatsRxFrameOverflows;	/* ReadOnly */
	long mtpOmSdtStatsRxFrameTooLong;	/* ReadOnly */
	long mtpOmSdtStatsRxFrameTooShort;	/* ReadOnly */
	long mtpOmSdtStatsRxResidueErrors;	/* ReadOnly */
	long mtpOmSdtStatsCarrierCtsLost;	/* ReadOnly */
	long mtpOmSdtStatsCarrierDcdLost;	/* ReadOnly */
	long mtpOmSdtStatsCarrierLost;	/* ReadOnly */
};
struct mtpOmSdlStatsTable_data {
	uint mtpOmSdlStatsTable_request;
	uint mtpOmSdlStatsTable_refs;
	ulong mtpMsId;			/* NoAccess */
	ulong mtpSpId;			/* NoAccess */
	uint8_t *mtpSdlId;		/* NoAccess */
	size_t mtpSdlIdLen;
	long mtpOmSdlStatsRxOctets;	/* ReadOnly */
	long mtpOmSdlStatsTxOctets;	/* ReadOnly */
	long mtpOmSdlStatsRXOverruns;	/* ReadOnly */
	long mtpOmSdlStatsTxUnderruns;	/* ReadOnly */
	long mtpOmSdlStatsRxBufferOverflows;	/* ReadOnly */
	long mtpOmSdlStatsTxBufferOverflows;	/* ReadOnly */
	long mtpOmSdlStatsLeadCtsLost;	/* ReadOnly */
	long mtpOmSdlStatsLeadDcdLost;	/* ReadOnly */
	long mtpOmSdlStatsCarrierLost;	/* ReadOnly */
	long mtpOmSdlStatsBipolarViolations;	/* ReadOnly */
};

/* storage declarations */
extern struct mtpOmMIB_data *mtpOmMIBStorage;
extern struct header_complex_index *mtpOmSpTableStorage;
extern struct header_complex_index *mtpOmSpInt5minTableStorage;
extern struct header_complex_index *mtpOmSpInt15minTableStorage;
extern struct header_complex_index *mtpOmSpSiTableStorage;
extern struct header_complex_index *mtpOmSpSiInt5minTableStorage;
extern struct header_complex_index *mtpOmSpSiInt15minTableStorage;
extern struct header_complex_index *mtpOmSpStudyTableStorage;
extern struct header_complex_index *mtpOmSpStudyInt5minTableStorage;
extern struct header_complex_index *mtpOmSpStudyInt15minTableStorage;
extern struct header_complex_index *mtpOmSpStudyMapTableStorage;
extern struct header_complex_index *mtpOmRsTableStorage;
extern struct header_complex_index *mtpOmRsInt5minTableStorage;
extern struct header_complex_index *mtpOmRsInt15minTableStorage;
extern struct header_complex_index *mtpOmRsSiTableStorage;
extern struct header_complex_index *mtpOmRsSiInt5minTableStorage;
extern struct header_complex_index *mtpOmRsSiInt15minTableStorage;
extern struct header_complex_index *mtpOmLsTableStorage;
extern struct header_complex_index *mtpOmLsInt5minTableStorage;
extern struct header_complex_index *mtpOmLsInt15minTableStorage;
extern struct header_complex_index *mtpOmSlStatsTableStorage;
extern struct header_complex_index *mtpOmSlL3TableStorage;
extern struct header_complex_index *mtpOmSlL3Int5minTableStorage;
extern struct header_complex_index *mtpOmSlL3Int15minTableStorage;
extern struct header_complex_index *mtpOmSlL2TableStorage;
extern struct header_complex_index *mtpOmSlL2Int5minTableStorage;
extern struct header_complex_index *mtpOmSlL2Int15minTableStorage;
extern struct header_complex_index *mtpOmSdtStatsTableStorage;
extern struct header_complex_index *mtpOmSdlStatsTableStorage;

/* enum definitions from the covered mib sections */

#define MTPOMSPSICODE_SNMM                       0
#define MTPOMSPSICODE_SNTM                       1
#define MTPOMSPSICODE_SNSM                       2
#define MTPOMSPSICODE_SCCP                       3
#define MTPOMSPSICODE_TUP                        4
#define MTPOMSPSICODE_ISUP                       5
#define MTPOMSPSICODE_DUP1                       6
#define MTPOMSPSICODE_DUP2                       7
#define MTPOMSPSICODE_MTUP                       8
#define MTPOMSPSICODE_BISUP                      9
#define MTPOMSPSICODE_SIUP                       10
#define MTPOMSPSICODE_SPNEUP                     11
#define MTPOMSPSICODE_STC                        12
#define MTPOMSPSICODE_USER13                     13
#define MTPOMSPSICODE_USER14                     14
#define MTPOMSPSICODE_USER15                     15

#define MTPOMSPSICODE_SNMM                       0
#define MTPOMSPSICODE_SNTM                       1
#define MTPOMSPSICODE_SNSM                       2
#define MTPOMSPSICODE_SCCP                       3
#define MTPOMSPSICODE_TUP                        4
#define MTPOMSPSICODE_ISUP                       5
#define MTPOMSPSICODE_DUP1                       6
#define MTPOMSPSICODE_DUP2                       7
#define MTPOMSPSICODE_MTUP                       8
#define MTPOMSPSICODE_BISUP                      9
#define MTPOMSPSICODE_SIUP                       10
#define MTPOMSPSICODE_SPNEUP                     11
#define MTPOMSPSICODE_STC                        12
#define MTPOMSPSICODE_USER13                     13
#define MTPOMSPSICODE_USER14                     14
#define MTPOMSPSICODE_USER15                     15

#define MTPOMSPSICODE_SNMM                       0
#define MTPOMSPSICODE_SNTM                       1
#define MTPOMSPSICODE_SNSM                       2
#define MTPOMSPSICODE_SCCP                       3
#define MTPOMSPSICODE_TUP                        4
#define MTPOMSPSICODE_ISUP                       5
#define MTPOMSPSICODE_DUP1                       6
#define MTPOMSPSICODE_DUP2                       7
#define MTPOMSPSICODE_MTUP                       8
#define MTPOMSPSICODE_BISUP                      9
#define MTPOMSPSICODE_SIUP                       10
#define MTPOMSPSICODE_SPNEUP                     11
#define MTPOMSPSICODE_STC                        12
#define MTPOMSPSICODE_USER13                     13
#define MTPOMSPSICODE_USER14                     14
#define MTPOMSPSICODE_USER15                     15

#define MTPOMSPSICODE_SNMM                       0
#define MTPOMSPSICODE_SNTM                       1
#define MTPOMSPSICODE_SNSM                       2
#define MTPOMSPSICODE_SCCP                       3
#define MTPOMSPSICODE_TUP                        4
#define MTPOMSPSICODE_ISUP                       5
#define MTPOMSPSICODE_DUP1                       6
#define MTPOMSPSICODE_DUP2                       7
#define MTPOMSPSICODE_MTUP                       8
#define MTPOMSPSICODE_BISUP                      9
#define MTPOMSPSICODE_SIUP                       10
#define MTPOMSPSICODE_SPNEUP                     11
#define MTPOMSPSICODE_STC                        12
#define MTPOMSPSICODE_USER13                     13
#define MTPOMSPSICODE_USER14                     14
#define MTPOMSPSICODE_USER15                     15

#define MTPOMRSSICODE_SNMM                       0
#define MTPOMRSSICODE_SNTM                       1
#define MTPOMRSSICODE_SNSM                       2
#define MTPOMRSSICODE_SCCP                       3
#define MTPOMRSSICODE_TUP                        4
#define MTPOMRSSICODE_ISUP                       5
#define MTPOMRSSICODE_DUP1                       6
#define MTPOMRSSICODE_DUP2                       7
#define MTPOMRSSICODE_MTUP                       8
#define MTPOMRSSICODE_BISUP                      9
#define MTPOMRSSICODE_SIUP                       10
#define MTPOMRSSICODE_SPNEUP                     11
#define MTPOMRSSICODE_STC                        12
#define MTPOMRSSICODE_USER13                     13
#define MTPOMRSSICODE_USER14                     14
#define MTPOMRSSICODE_USER15                     15

#define MTPOMRSSICODE_SNMM                       0
#define MTPOMRSSICODE_SNTM                       1
#define MTPOMRSSICODE_SNSM                       2
#define MTPOMRSSICODE_SCCP                       3
#define MTPOMRSSICODE_TUP                        4
#define MTPOMRSSICODE_ISUP                       5
#define MTPOMRSSICODE_DUP1                       6
#define MTPOMRSSICODE_DUP2                       7
#define MTPOMRSSICODE_MTUP                       8
#define MTPOMRSSICODE_BISUP                      9
#define MTPOMRSSICODE_SIUP                       10
#define MTPOMRSSICODE_SPNEUP                     11
#define MTPOMRSSICODE_STC                        12
#define MTPOMRSSICODE_USER13                     13
#define MTPOMRSSICODE_USER14                     14
#define MTPOMRSSICODE_USER15                     15

#define MTPOMRSSICODE_SNMM                       0
#define MTPOMRSSICODE_SNTM                       1
#define MTPOMRSSICODE_SNSM                       2
#define MTPOMRSSICODE_SCCP                       3
#define MTPOMRSSICODE_TUP                        4
#define MTPOMRSSICODE_ISUP                       5
#define MTPOMRSSICODE_DUP1                       6
#define MTPOMRSSICODE_DUP2                       7
#define MTPOMRSSICODE_MTUP                       8
#define MTPOMRSSICODE_BISUP                      9
#define MTPOMRSSICODE_SIUP                       10
#define MTPOMRSSICODE_SPNEUP                     11
#define MTPOMRSSICODE_STC                        12
#define MTPOMRSSICODE_USER13                     13
#define MTPOMRSSICODE_USER14                     14
#define MTPOMRSSICODE_USER15                     15

/* notifications */

/* scalars accessible only for notify */

/* object id definitions */

/* function prototypes */
/* trap function prototypes */

/* variable function prototypes */
void init_mtpOmMIB(void);
void deinit_mtpOmMIB(void);
int term_mtpOmMIB(int majorID, int minorID, void *serverarg, void *clientarg);
FindVarMethod var_mtpOmMIB;
void parse_mtpOmMIB(const char *, char *);
SNMPCallback store_mtpOmMIB;
void refresh_mtpOmMIB(int);
FindVarMethod var_mtpOmSpTable;
struct mtpOmSpTable_data *mtpOmSpTable_create(void);
struct mtpOmSpTable_data *mtpOmSpTable_duplicate(struct mtpOmSpTable_data *);
int mtpOmSpTable_destroy(struct mtpOmSpTable_data **);
int mtpOmSpTable_add(struct mtpOmSpTable_data *);
int mtpOmSpTable_del(struct mtpOmSpTable_data *);
void parse_mtpOmSpTable(const char *, char *);
SNMPCallback store_mtpOmSpTable;
void refresh_mtpOmSpTable(int);
FindVarMethod var_mtpOmSpInt5minTable;
struct mtpOmSpInt5minTable_data *mtpOmSpInt5minTable_create(void);
struct mtpOmSpInt5minTable_data *mtpOmSpInt5minTable_duplicate(struct mtpOmSpInt5minTable_data *);
int mtpOmSpInt5minTable_destroy(struct mtpOmSpInt5minTable_data **);
int mtpOmSpInt5minTable_add(struct mtpOmSpInt5minTable_data *);
int mtpOmSpInt5minTable_del(struct mtpOmSpInt5minTable_data *);
void parse_mtpOmSpInt5minTable(const char *, char *);
SNMPCallback store_mtpOmSpInt5minTable;
void refresh_mtpOmSpInt5minTable(int);
FindVarMethod var_mtpOmSpInt15minTable;
struct mtpOmSpInt15minTable_data *mtpOmSpInt15minTable_create(void);
struct mtpOmSpInt15minTable_data *mtpOmSpInt15minTable_duplicate(struct mtpOmSpInt15minTable_data *);
int mtpOmSpInt15minTable_destroy(struct mtpOmSpInt15minTable_data **);
int mtpOmSpInt15minTable_add(struct mtpOmSpInt15minTable_data *);
int mtpOmSpInt15minTable_del(struct mtpOmSpInt15minTable_data *);
void parse_mtpOmSpInt15minTable(const char *, char *);
SNMPCallback store_mtpOmSpInt15minTable;
void refresh_mtpOmSpInt15minTable(int);
FindVarMethod var_mtpOmSpSiTable;
struct mtpOmSpSiTable_data *mtpOmSpSiTable_create(void);
struct mtpOmSpSiTable_data *mtpOmSpSiTable_duplicate(struct mtpOmSpSiTable_data *);
int mtpOmSpSiTable_destroy(struct mtpOmSpSiTable_data **);
int mtpOmSpSiTable_add(struct mtpOmSpSiTable_data *);
int mtpOmSpSiTable_del(struct mtpOmSpSiTable_data *);
void parse_mtpOmSpSiTable(const char *, char *);
SNMPCallback store_mtpOmSpSiTable;
void refresh_mtpOmSpSiTable(int);
FindVarMethod var_mtpOmSpSiInt5minTable;
struct mtpOmSpSiInt5minTable_data *mtpOmSpSiInt5minTable_create(void);
struct mtpOmSpSiInt5minTable_data *mtpOmSpSiInt5minTable_duplicate(struct mtpOmSpSiInt5minTable_data *);
int mtpOmSpSiInt5minTable_destroy(struct mtpOmSpSiInt5minTable_data **);
int mtpOmSpSiInt5minTable_add(struct mtpOmSpSiInt5minTable_data *);
int mtpOmSpSiInt5minTable_del(struct mtpOmSpSiInt5minTable_data *);
void parse_mtpOmSpSiInt5minTable(const char *, char *);
SNMPCallback store_mtpOmSpSiInt5minTable;
void refresh_mtpOmSpSiInt5minTable(int);
FindVarMethod var_mtpOmSpSiInt15minTable;
struct mtpOmSpSiInt15minTable_data *mtpOmSpSiInt15minTable_create(void);
struct mtpOmSpSiInt15minTable_data *mtpOmSpSiInt15minTable_duplicate(struct mtpOmSpSiInt15minTable_data *);
int mtpOmSpSiInt15minTable_destroy(struct mtpOmSpSiInt15minTable_data **);
int mtpOmSpSiInt15minTable_add(struct mtpOmSpSiInt15minTable_data *);
int mtpOmSpSiInt15minTable_del(struct mtpOmSpSiInt15minTable_data *);
void parse_mtpOmSpSiInt15minTable(const char *, char *);
SNMPCallback store_mtpOmSpSiInt15minTable;
void refresh_mtpOmSpSiInt15minTable(int);
FindVarMethod var_mtpOmSpStudyTable;
struct mtpOmSpStudyTable_data *mtpOmSpStudyTable_create(void);
struct mtpOmSpStudyTable_data *mtpOmSpStudyTable_duplicate(struct mtpOmSpStudyTable_data *);
int mtpOmSpStudyTable_destroy(struct mtpOmSpStudyTable_data **);
int mtpOmSpStudyTable_add(struct mtpOmSpStudyTable_data *);
int mtpOmSpStudyTable_del(struct mtpOmSpStudyTable_data *);
void parse_mtpOmSpStudyTable(const char *, char *);
SNMPCallback store_mtpOmSpStudyTable;
void refresh_mtpOmSpStudyTable(int);
FindVarMethod var_mtpOmSpStudyInt5minTable;
struct mtpOmSpStudyInt5minTable_data *mtpOmSpStudyInt5minTable_create(void);
struct mtpOmSpStudyInt5minTable_data *mtpOmSpStudyInt5minTable_duplicate(struct mtpOmSpStudyInt5minTable_data *);
int mtpOmSpStudyInt5minTable_destroy(struct mtpOmSpStudyInt5minTable_data **);
int mtpOmSpStudyInt5minTable_add(struct mtpOmSpStudyInt5minTable_data *);
int mtpOmSpStudyInt5minTable_del(struct mtpOmSpStudyInt5minTable_data *);
void parse_mtpOmSpStudyInt5minTable(const char *, char *);
SNMPCallback store_mtpOmSpStudyInt5minTable;
void refresh_mtpOmSpStudyInt5minTable(int);
FindVarMethod var_mtpOmSpStudyInt15minTable;
struct mtpOmSpStudyInt15minTable_data *mtpOmSpStudyInt15minTable_create(void);
struct mtpOmSpStudyInt15minTable_data *mtpOmSpStudyInt15minTable_duplicate(struct mtpOmSpStudyInt15minTable_data *);
int mtpOmSpStudyInt15minTable_destroy(struct mtpOmSpStudyInt15minTable_data **);
int mtpOmSpStudyInt15minTable_add(struct mtpOmSpStudyInt15minTable_data *);
int mtpOmSpStudyInt15minTable_del(struct mtpOmSpStudyInt15minTable_data *);
void parse_mtpOmSpStudyInt15minTable(const char *, char *);
SNMPCallback store_mtpOmSpStudyInt15minTable;
void refresh_mtpOmSpStudyInt15minTable(int);
FindVarMethod var_mtpOmSpStudyMapTable;
struct mtpOmSpStudyMapTable_data *mtpOmSpStudyMapTable_create(void);
struct mtpOmSpStudyMapTable_data *mtpOmSpStudyMapTable_duplicate(struct mtpOmSpStudyMapTable_data *);
int mtpOmSpStudyMapTable_destroy(struct mtpOmSpStudyMapTable_data **);
int mtpOmSpStudyMapTable_add(struct mtpOmSpStudyMapTable_data *);
int mtpOmSpStudyMapTable_del(struct mtpOmSpStudyMapTable_data *);
void parse_mtpOmSpStudyMapTable(const char *, char *);
SNMPCallback store_mtpOmSpStudyMapTable;
void refresh_mtpOmSpStudyMapTable(int);
FindVarMethod var_mtpOmRsTable;
struct mtpOmRsTable_data *mtpOmRsTable_create(void);
struct mtpOmRsTable_data *mtpOmRsTable_duplicate(struct mtpOmRsTable_data *);
int mtpOmRsTable_destroy(struct mtpOmRsTable_data **);
int mtpOmRsTable_add(struct mtpOmRsTable_data *);
int mtpOmRsTable_del(struct mtpOmRsTable_data *);
void parse_mtpOmRsTable(const char *, char *);
SNMPCallback store_mtpOmRsTable;
void refresh_mtpOmRsTable(int);
FindVarMethod var_mtpOmRsInt5minTable;
struct mtpOmRsInt5minTable_data *mtpOmRsInt5minTable_create(void);
struct mtpOmRsInt5minTable_data *mtpOmRsInt5minTable_duplicate(struct mtpOmRsInt5minTable_data *);
int mtpOmRsInt5minTable_destroy(struct mtpOmRsInt5minTable_data **);
int mtpOmRsInt5minTable_add(struct mtpOmRsInt5minTable_data *);
int mtpOmRsInt5minTable_del(struct mtpOmRsInt5minTable_data *);
void parse_mtpOmRsInt5minTable(const char *, char *);
SNMPCallback store_mtpOmRsInt5minTable;
void refresh_mtpOmRsInt5minTable(int);
FindVarMethod var_mtpOmRsInt15minTable;
struct mtpOmRsInt15minTable_data *mtpOmRsInt15minTable_create(void);
struct mtpOmRsInt15minTable_data *mtpOmRsInt15minTable_duplicate(struct mtpOmRsInt15minTable_data *);
int mtpOmRsInt15minTable_destroy(struct mtpOmRsInt15minTable_data **);
int mtpOmRsInt15minTable_add(struct mtpOmRsInt15minTable_data *);
int mtpOmRsInt15minTable_del(struct mtpOmRsInt15minTable_data *);
void parse_mtpOmRsInt15minTable(const char *, char *);
SNMPCallback store_mtpOmRsInt15minTable;
void refresh_mtpOmRsInt15minTable(int);
FindVarMethod var_mtpOmRsSiTable;
struct mtpOmRsSiTable_data *mtpOmRsSiTable_create(void);
struct mtpOmRsSiTable_data *mtpOmRsSiTable_duplicate(struct mtpOmRsSiTable_data *);
int mtpOmRsSiTable_destroy(struct mtpOmRsSiTable_data **);
int mtpOmRsSiTable_add(struct mtpOmRsSiTable_data *);
int mtpOmRsSiTable_del(struct mtpOmRsSiTable_data *);
void parse_mtpOmRsSiTable(const char *, char *);
SNMPCallback store_mtpOmRsSiTable;
void refresh_mtpOmRsSiTable(int);
FindVarMethod var_mtpOmRsSiInt5minTable;
struct mtpOmRsSiInt5minTable_data *mtpOmRsSiInt5minTable_create(void);
struct mtpOmRsSiInt5minTable_data *mtpOmRsSiInt5minTable_duplicate(struct mtpOmRsSiInt5minTable_data *);
int mtpOmRsSiInt5minTable_destroy(struct mtpOmRsSiInt5minTable_data **);
int mtpOmRsSiInt5minTable_add(struct mtpOmRsSiInt5minTable_data *);
int mtpOmRsSiInt5minTable_del(struct mtpOmRsSiInt5minTable_data *);
void parse_mtpOmRsSiInt5minTable(const char *, char *);
SNMPCallback store_mtpOmRsSiInt5minTable;
void refresh_mtpOmRsSiInt5minTable(int);
FindVarMethod var_mtpOmRsSiInt15minTable;
struct mtpOmRsSiInt15minTable_data *mtpOmRsSiInt15minTable_create(void);
struct mtpOmRsSiInt15minTable_data *mtpOmRsSiInt15minTable_duplicate(struct mtpOmRsSiInt15minTable_data *);
int mtpOmRsSiInt15minTable_destroy(struct mtpOmRsSiInt15minTable_data **);
int mtpOmRsSiInt15minTable_add(struct mtpOmRsSiInt15minTable_data *);
int mtpOmRsSiInt15minTable_del(struct mtpOmRsSiInt15minTable_data *);
void parse_mtpOmRsSiInt15minTable(const char *, char *);
SNMPCallback store_mtpOmRsSiInt15minTable;
void refresh_mtpOmRsSiInt15minTable(int);
FindVarMethod var_mtpOmLsTable;
struct mtpOmLsTable_data *mtpOmLsTable_create(void);
struct mtpOmLsTable_data *mtpOmLsTable_duplicate(struct mtpOmLsTable_data *);
int mtpOmLsTable_destroy(struct mtpOmLsTable_data **);
int mtpOmLsTable_add(struct mtpOmLsTable_data *);
int mtpOmLsTable_del(struct mtpOmLsTable_data *);
void parse_mtpOmLsTable(const char *, char *);
SNMPCallback store_mtpOmLsTable;
void refresh_mtpOmLsTable(int);
FindVarMethod var_mtpOmLsInt5minTable;
struct mtpOmLsInt5minTable_data *mtpOmLsInt5minTable_create(void);
struct mtpOmLsInt5minTable_data *mtpOmLsInt5minTable_duplicate(struct mtpOmLsInt5minTable_data *);
int mtpOmLsInt5minTable_destroy(struct mtpOmLsInt5minTable_data **);
int mtpOmLsInt5minTable_add(struct mtpOmLsInt5minTable_data *);
int mtpOmLsInt5minTable_del(struct mtpOmLsInt5minTable_data *);
void parse_mtpOmLsInt5minTable(const char *, char *);
SNMPCallback store_mtpOmLsInt5minTable;
void refresh_mtpOmLsInt5minTable(int);
FindVarMethod var_mtpOmLsInt15minTable;
struct mtpOmLsInt15minTable_data *mtpOmLsInt15minTable_create(void);
struct mtpOmLsInt15minTable_data *mtpOmLsInt15minTable_duplicate(struct mtpOmLsInt15minTable_data *);
int mtpOmLsInt15minTable_destroy(struct mtpOmLsInt15minTable_data **);
int mtpOmLsInt15minTable_add(struct mtpOmLsInt15minTable_data *);
int mtpOmLsInt15minTable_del(struct mtpOmLsInt15minTable_data *);
void parse_mtpOmLsInt15minTable(const char *, char *);
SNMPCallback store_mtpOmLsInt15minTable;
void refresh_mtpOmLsInt15minTable(int);
FindVarMethod var_mtpOmSlStatsTable;
struct mtpOmSlStatsTable_data *mtpOmSlStatsTable_create(void);
struct mtpOmSlStatsTable_data *mtpOmSlStatsTable_duplicate(struct mtpOmSlStatsTable_data *);
int mtpOmSlStatsTable_destroy(struct mtpOmSlStatsTable_data **);
int mtpOmSlStatsTable_add(struct mtpOmSlStatsTable_data *);
int mtpOmSlStatsTable_del(struct mtpOmSlStatsTable_data *);
void parse_mtpOmSlStatsTable(const char *, char *);
SNMPCallback store_mtpOmSlStatsTable;
void refresh_mtpOmSlStatsTable(int);
FindVarMethod var_mtpOmSlL3Table;
struct mtpOmSlL3Table_data *mtpOmSlL3Table_create(void);
struct mtpOmSlL3Table_data *mtpOmSlL3Table_duplicate(struct mtpOmSlL3Table_data *);
int mtpOmSlL3Table_destroy(struct mtpOmSlL3Table_data **);
int mtpOmSlL3Table_add(struct mtpOmSlL3Table_data *);
int mtpOmSlL3Table_del(struct mtpOmSlL3Table_data *);
void parse_mtpOmSlL3Table(const char *, char *);
SNMPCallback store_mtpOmSlL3Table;
void refresh_mtpOmSlL3Table(int);
FindVarMethod var_mtpOmSlL3Int5minTable;
struct mtpOmSlL3Int5minTable_data *mtpOmSlL3Int5minTable_create(void);
struct mtpOmSlL3Int5minTable_data *mtpOmSlL3Int5minTable_duplicate(struct mtpOmSlL3Int5minTable_data *);
int mtpOmSlL3Int5minTable_destroy(struct mtpOmSlL3Int5minTable_data **);
int mtpOmSlL3Int5minTable_add(struct mtpOmSlL3Int5minTable_data *);
int mtpOmSlL3Int5minTable_del(struct mtpOmSlL3Int5minTable_data *);
void parse_mtpOmSlL3Int5minTable(const char *, char *);
SNMPCallback store_mtpOmSlL3Int5minTable;
void refresh_mtpOmSlL3Int5minTable(int);
FindVarMethod var_mtpOmSlL3Int15minTable;
struct mtpOmSlL3Int15minTable_data *mtpOmSlL3Int15minTable_create(void);
struct mtpOmSlL3Int15minTable_data *mtpOmSlL3Int15minTable_duplicate(struct mtpOmSlL3Int15minTable_data *);
int mtpOmSlL3Int15minTable_destroy(struct mtpOmSlL3Int15minTable_data **);
int mtpOmSlL3Int15minTable_add(struct mtpOmSlL3Int15minTable_data *);
int mtpOmSlL3Int15minTable_del(struct mtpOmSlL3Int15minTable_data *);
void parse_mtpOmSlL3Int15minTable(const char *, char *);
SNMPCallback store_mtpOmSlL3Int15minTable;
void refresh_mtpOmSlL3Int15minTable(int);
FindVarMethod var_mtpOmSlL2Table;
struct mtpOmSlL2Table_data *mtpOmSlL2Table_create(void);
struct mtpOmSlL2Table_data *mtpOmSlL2Table_duplicate(struct mtpOmSlL2Table_data *);
int mtpOmSlL2Table_destroy(struct mtpOmSlL2Table_data **);
int mtpOmSlL2Table_add(struct mtpOmSlL2Table_data *);
int mtpOmSlL2Table_del(struct mtpOmSlL2Table_data *);
void parse_mtpOmSlL2Table(const char *, char *);
SNMPCallback store_mtpOmSlL2Table;
void refresh_mtpOmSlL2Table(int);
FindVarMethod var_mtpOmSlL2Int5minTable;
struct mtpOmSlL2Int5minTable_data *mtpOmSlL2Int5minTable_create(void);
struct mtpOmSlL2Int5minTable_data *mtpOmSlL2Int5minTable_duplicate(struct mtpOmSlL2Int5minTable_data *);
int mtpOmSlL2Int5minTable_destroy(struct mtpOmSlL2Int5minTable_data **);
int mtpOmSlL2Int5minTable_add(struct mtpOmSlL2Int5minTable_data *);
int mtpOmSlL2Int5minTable_del(struct mtpOmSlL2Int5minTable_data *);
void parse_mtpOmSlL2Int5minTable(const char *, char *);
SNMPCallback store_mtpOmSlL2Int5minTable;
void refresh_mtpOmSlL2Int5minTable(int);
FindVarMethod var_mtpOmSlL2Int15minTable;
struct mtpOmSlL2Int15minTable_data *mtpOmSlL2Int15minTable_create(void);
struct mtpOmSlL2Int15minTable_data *mtpOmSlL2Int15minTable_duplicate(struct mtpOmSlL2Int15minTable_data *);
int mtpOmSlL2Int15minTable_destroy(struct mtpOmSlL2Int15minTable_data **);
int mtpOmSlL2Int15minTable_add(struct mtpOmSlL2Int15minTable_data *);
int mtpOmSlL2Int15minTable_del(struct mtpOmSlL2Int15minTable_data *);
void parse_mtpOmSlL2Int15minTable(const char *, char *);
SNMPCallback store_mtpOmSlL2Int15minTable;
void refresh_mtpOmSlL2Int15minTable(int);
FindVarMethod var_mtpOmSdtStatsTable;
struct mtpOmSdtStatsTable_data *mtpOmSdtStatsTable_create(void);
struct mtpOmSdtStatsTable_data *mtpOmSdtStatsTable_duplicate(struct mtpOmSdtStatsTable_data *);
int mtpOmSdtStatsTable_destroy(struct mtpOmSdtStatsTable_data **);
int mtpOmSdtStatsTable_add(struct mtpOmSdtStatsTable_data *);
int mtpOmSdtStatsTable_del(struct mtpOmSdtStatsTable_data *);
void parse_mtpOmSdtStatsTable(const char *, char *);
SNMPCallback store_mtpOmSdtStatsTable;
void refresh_mtpOmSdtStatsTable(int);
FindVarMethod var_mtpOmSdlStatsTable;
struct mtpOmSdlStatsTable_data *mtpOmSdlStatsTable_create(void);
struct mtpOmSdlStatsTable_data *mtpOmSdlStatsTable_duplicate(struct mtpOmSdlStatsTable_data *);
int mtpOmSdlStatsTable_destroy(struct mtpOmSdlStatsTable_data **);
int mtpOmSdlStatsTable_add(struct mtpOmSdlStatsTable_data *);
int mtpOmSdlStatsTable_del(struct mtpOmSdlStatsTable_data *);
void parse_mtpOmSdlStatsTable(const char *, char *);
SNMPCallback store_mtpOmSdlStatsTable;
void refresh_mtpOmSdlStatsTable(int);

WriteMethod write_mtpOmSpSiStatus;
WriteMethod write_mtpOmSpStudyStatus;
WriteMethod write_mtpOmSpStudyMapStatus;
WriteMethod write_mtpOmRsSiValidIntervals;
WriteMethod write_mtpOmRsSiTimeDiscontinuity;
WriteMethod write_mtpOm1stAndIntervalActivate;
WriteMethod write_mtpOm1stAndIntervalDeactivate;
WriteMethod write_mtpOm5MinActivate;
WriteMethod write_mtpOm5MinDeaActivate;
WriteMethod write_mtpOm15MinActivate;
WriteMethod write_mtpOm15MinDeaActivate;
WriteMethod write_mtpOm5MinMaxIntervals;
WriteMethod write_mtpOm15MinMaxIntervals;
#endif				/* __LOCAL_MTPOMMIB_H__ */
