/*****************************************************************************

 @(#) $Id: sccpMIB.h,v 0.9.2.9 2009-01-16 20:44:59 brian Exp $

 -----------------------------------------------------------------------------

 Copyright (c) 2008-2009  Monavacon Limited <http://www.monavacon.com/>
 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; version 3 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 -----------------------------------------------------------------------------

 Last Modified $Date: 2009-01-16 20:44:59 $ by $Author: brian $

 -----------------------------------------------------------------------------

 $Log: sccpMIB.h,v $
 Revision 0.9.2.9  2009-01-16 20:44:59  brian
 - updating mibs and agents

 Revision 0.9.2.8  2009-01-14 14:30:05  brian
 - working up agents

 Revision 0.9.2.7  2009-01-10 17:09:20  brian
 - updated agents

 Revision 0.9.2.6  2009-01-04 13:16:05  brian
 - updated agents

 Revision 0.9.2.5  2009-01-03 10:51:06  brian
 - updated agent

 Revision 0.9.2.4  2009-01-02 15:04:15  brian
 - updated agents

 Revision 0.9.2.3  2008-12-31 16:04:47  brian
 - updated mibs

 Revision 0.9.2.2  2008-12-24 13:08:25  brian
 - building ss7confd

 *****************************************************************************/

#ifndef __LOCAL_SCCPMIB_H__
#define __LOCAL_SCCPMIB_H__

#ident "@(#) $RCSfile: sccpMIB.h,v $ $Name:  $($Revision: 0.9.2.9 $) Copyright (c) 2008-2009 Monavacon Limited."

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */
/* our storage structure(s) */
struct sccpMIB_data {
	uint sccpMIB_request;
};
struct sccpNetworkEntityTable_data {
	uint sccpNetworkEntityTable_request;
	uint sccpNetworkEntityTable_refs;
	ulong sccpNetworkEntityId;	/* NoAccess */
	uint8_t *sccpNetworkEntityAlarmStatus;	/* Create */
	size_t sccpNetworkEntityAlarmStatusLen;
	ulong sccpCommunicationsEntityId;	/* NoAccess */
	uint8_t *sccpLocalSapNames;	/* NoAccess */
	size_t sccpLocalSapNamesLen;
	uint8_t *sccpNetworkEntityTitles;	/* NoAccess */
	size_t sccpNetworkEntityTitlesLen;
	uint8_t *sccpSystemTypes;	/* ReadOnly */
	size_t sccpSystemTypesLen;
	oid *sccpVersion;		/* Create */
	size_t sccpVersionLen;
	long sccpLUDTandLUDTSSupported;	/* Create */
	long sccpCoordChangeTimer;	/* Create */
	long sccpIgnoreSSTTimer;	/* Create */
	long sccpMaxStatInfoTimer;	/* Create */
	uint8_t *sccpNetworkEntityName;	/* Create */
	size_t sccpNetworkEntityNameLen;
	long sccpRowStatus;		/* Create */
};
struct sccpSapNameTable_data {
	uint sccpSapNameTable_request;
	uint sccpSapNameTable_refs;
	ulong sccpNetworkEntityId;	/* NoAccess */
	ulong sccpSapId;		/* NoAccess */
	long sccpSapNameRowStatus;	/* Create */
};
struct sccpAccessPointTable_data {
	uint sccpAccessPointTable_request;
	uint sccpAccessPointTable_refs;
	ulong sccpNetworkEntityId;	/* NoAccess */
	ulong sccpSapId;		/* NoAccess */
	uint8_t *sccpAccessPointAlarmStatus;	/* Create */
	size_t sccpAccessPointAlarmStatusLen;
	uint8_t *sccpSap2Address;	/* Create */
	size_t sccpSap2AddressLen;
	uint8_t *sccpUserEntityNames;	/* Create */
	size_t sccpUserEntityNamesLen;
	uint8_t *sccpProviderEntityNames;	/* Create */
	size_t sccpProviderEntityNamesLen;
	uint8_t *sccpAvailabilityStatus;	/* ReadOnly */
	size_t sccpAvailabilityStatusLen;
	ulong sccpConcernedAreaPointer;	/* Create */
	ulong sccpLinkagePointer;	/* Create */
	long sccpSsAvailableAfterSpRestart;	/* Create */
	uint8_t *sccpAccessPointName;	/* Create */
	size_t sccpAccessPointNameLen;
	long sccpAccessPointRowStatus;	/* Create */
};
struct sccpLinkageTable_data {
	uint sccpLinkageTable_request;
	uint sccpLinkageTable_refs;
	ulong sccpNetworkEntityId;	/* NoAccess */
	ulong sccpLinkageId;		/* NoAccess */
	uint8_t *sccpOperationalProtocols;	/* ReadOnly */
	size_t sccpOperationalProtocolsLen;
	oid *sccpSnSAP;			/* ReadOnly */
	size_t sccpSnSAPLen;
	long sccpAttackTimerValue;	/* Create */
	long sccpDecayTimerValue;	/* Create */
	long sccpNrOfRestrictionLevels;	/* Create */
	long sccpNrOfSubLevels;		/* Create */
	long sccpCLS;			/* Create */
	long sccpCongestionTimerValue;	/* Create */
	long sccpp;			/* Create */
	uint8_t *sccpImportanceLevelCR;	/* Create */
	size_t sccpImportanceLevelCRLen;
	uint8_t *sccpImportanceLevelCC;	/* Create */
	size_t sccpImportanceLevelCCLen;
	uint8_t *sccpImportanceLevelCREF;	/* Create */
	size_t sccpImportanceLevelCREFLen;
	uint8_t *sccpImportanceLevelDT1;	/* Create */
	size_t sccpImportanceLevelDT1Len;
	uint8_t *sccpImportanceLevelDT2;	/* Create */
	size_t sccpImportanceLevelDT2Len;
	uint8_t *sccpImportanceLevelAK;	/* Create */
	size_t sccpImportanceLevelAKLen;
	uint8_t *sccpImportanceLevelIT;	/* Create */
	size_t sccpImportanceLevelITLen;
	uint8_t *sccpImportanceLevelED;	/* Create */
	size_t sccpImportanceLevelEDLen;
	uint8_t *sccpImportanceLevelEA;	/* Create */
	size_t sccpImportanceLevelEALen;
	uint8_t *sccpImportanceLevelRSR;	/* Create */
	size_t sccpImportanceLevelRSRLen;
	uint8_t *sccpImportanceLevelRSC;	/* Create */
	size_t sccpImportanceLevelRSCLen;
	uint8_t *sccpImportanceLevelERR;	/* Create */
	size_t sccpImportanceLevelERRLen;
	uint8_t *sccpImportanceLevelRLC;	/* Create */
	size_t sccpImportanceLevelRLCLen;
	uint8_t *sccpImportanceLevelRLSD;	/* Create */
	size_t sccpImportanceLevelRLSDLen;
	uint8_t *sccpImportanceLevelUDT;	/* Create */
	size_t sccpImportanceLevelUDTLen;
	uint8_t *sccpImportanceLevelUDTS;	/* Create */
	size_t sccpImportanceLevelUDTSLen;
	uint8_t *sccpImportanceLevelXUDT;	/* Create */
	size_t sccpImportanceLevelXUDTLen;
	uint8_t *sccpImportanceLevelXUDTS;	/* Create */
	size_t sccpImportanceLevelXUDTSLen;
	uint8_t *sccpImportanceLevelLUDT;	/* Create */
	size_t sccpImportanceLevelLUDTLen;
	uint8_t *sccpImportanceLevelLUDTS;	/* Create */
	size_t sccpImportanceLevelLUDTSLen;
	long sccpRLM;			/* Create */
	long sccpRSLM;			/* Create */
	uint8_t *sccpLinkageConcernedAreaPointer;	/* Create */
	size_t sccpLinkageConcernedAreaPointerLen;
	long sccpLowerLimitForSegmentation;	/* Create */
	long sccpUpperLimitForSegmentation;	/* Create */
	uint8_t *sccpLinkageName;	/* Create */
	size_t sccpLinkageNameLen;
	long sccpLinkageRowStatus;	/* Create */
};
struct sccpSclcTable_data {
	uint sccpSclcTable_request;
	uint sccpSclcTable_refs;
	ulong sccpNetworkEntityId;	/* NoAccess */
	uint8_t *sccpSclcAlarmStatus;	/* Create */
	size_t sccpSclcAlarmStatusLen;
	uint8_t *sccpClProtocolMachineId;	/* NoAccess */
	size_t sccpClProtocolMachineIdLen;
	long sccpSclcOperationalState;	/* ReadOnly */
	long sccpTotalRemoteSAPs;	/* ReadOnly */
	long sccpSclcAdministrativeState;	/* Create */
	uint8_t *sccpSclcSupportedProtocols;	/* ReadOnly */
	size_t sccpSclcSupportedProtocolsLen;
	long sccpSclcOperationalSystemType;	/* Create */
	long sccpInitialValueReassTimer;	/* Create */
	uint8_t *sccpSclcName;		/* Create */
	size_t sccpSclcNameLen;
	long sccpSclcRowStatus;		/* Create */
};
struct sccpScocTable_data {
	uint sccpScocTable_request;
	uint sccpScocTable_refs;
	ulong sccpNetworkEntityId;	/* NoAccess */
	uint8_t *sccpCoProtocolMachineId;	/* Create */
	size_t sccpCoProtocolMachineIdLen;
	long sccpScocOperationalState;	/* ReadOnly */
	long sccpScocAdministrativeState;	/* Create */
	long sccpScocOperationalSystemType;	/* Create */
	uint8_t *sccpScocSupportedProtocols;	/* ReadOnly */
	size_t sccpScocSupportedProtocolsLen;
	uint8_t *sccpScocName;		/* Create */
	size_t sccpScocNameLen;
	long sccpScocRowStatus;		/* Create */
};
struct sccpScrcTable_data {
	uint sccpScrcTable_request;
	uint sccpScrcTable_refs;
	ulong sccpNetworkEntityId;	/* NoAccess */
	uint8_t *sccpScrcId;		/* Create */
	size_t sccpScrcIdLen;
	uint8_t *sccpScrcAlarmStatus;	/* Create */
	size_t sccpScrcAlarmStatusLen;
	uint8_t *sccpScrcName;		/* Create */
	size_t sccpScrcNameLen;
	long sccpScrcRowStatus;		/* Create */
};
struct sccpEntitySetTable_data {
	uint sccpEntitySetTable_request;
	uint sccpEntitySetTable_refs;
	ulong sccpNetworkEntityId;	/* NoAccess */
	uint8_t *sccpEntitySetId;	/* NoAccess */
	size_t sccpEntitySetIdLen;
	long sccpSharingMode;		/* Create */
	oid *sccpLoadSharingAlgPointer;	/* Create */
	size_t sccpLoadSharingAlgPointerLen;
	uint8_t *sccpEntitySetName;	/* Create */
	size_t sccpEntitySetNameLen;
	long sccpEntitySetType;		/* Create */
	uint8_t *sccpEntitySetSsn;	/* Create */
	size_t sccpEntitySetSsnLen;
	long sccpEntitySetRowStatus;	/* Create */
};
struct sccpEntitySetSapTable_data {
	uint sccpEntitySetSapTable_request;
	uint sccpEntitySetSapTable_refs;
	ulong sccpNetworkEntityId;	/* NoAccess */
	uint8_t *sccpEntitySetId;	/* NoAccess */
	size_t sccpEntitySetIdLen;
	uint8_t *sccpEntitySetSapId;	/* NoAccess */
	size_t sccpEntitySetSapIdLen;
	long sccpEntitySetSapType;	/* Create */
	oid *sccpEntitySetSapPointer;	/* Create */
	size_t sccpEntitySetSapPointerLen;
	long sccpEntitySetSapRowStatus;	/* Create */
};
struct sccpConcernedAreaTable_data {
	uint sccpConcernedAreaTable_request;
	uint sccpConcernedAreaTable_refs;
	ulong sccpNetworkEntityId;	/* NoAccess */
	uint8_t *sccpConcernedAreaId;	/* NoAccess */
	size_t sccpConcernedAreaIdLen;
	long sccpConcernedAreaRowStatus;	/* NoAccess */
};
struct sccpRemoteSCCPTable_data {
	uint sccpRemoteSCCPTable_request;
	uint sccpRemoteSCCPTable_refs;
	ulong sccpNetworkEntityId;	/* NoAccess */
	uint8_t *sccpConcernedAreaId;	/* NoAccess */
	size_t sccpConcernedAreaIdLen;
	uint8_t *sccpRemoteSCCPId;	/* NoAccess */
	size_t sccpRemoteSCCPIdLen;
	oid *sccpRemoteSCCPMTPAccessPoint;	/* Create */
	size_t sccpRemoteSCCPMTPAccessPointLen;
	uint8_t *sccpRemoteSCCPName;	/* Create */
	size_t sccpRemoteSCCPNameLen;
	long sccpRemoteSCCPRowStatus;	/* Create */
};
struct sccpGtConversionRuleTable_data {
	uint sccpGtConversionRuleTable_request;
	uint sccpGtConversionRuleTable_refs;
	ulong sccpNetworkEntityId;	/* NoAccess */
	uint8_t *sccpGtConversionRuleId;	/* NoAccess */
	size_t sccpGtConversionRuleIdLen;
	long sccpGtNewEncodingScheme;	/* Create */
	long sccpGtNewNatureOfAddress;	/* Create */
	long sccpGtNewNumberingPlan;	/* Create */
	long sccpGtNewTranslationType;	/* Create */
	uint8_t *sccpGtConversionRuleName;	/* Create */
	size_t sccpGtConversionRuleNameLen;
	long sccpGtConversionRuleRowStatus;	/* Create */
};
struct sccpAddressInfoTable_data {
	uint sccpAddressInfoTable_request;
	uint sccpAddressInfoTable_refs;
	ulong sccpNetworkEntityId;	/* NoAccess */
	uint8_t *sccpGtConversionRuleId;	/* NoAccess */
	size_t sccpGtConversionRuleIdLen;
	uint8_t *sccpAddressInfoOperationId;	/* NoAccess */
	size_t sccpAddressInfoOperationIdLen;
	long sccpAddressInfoOperation;	/* Create */
	long sccpAddressInfoAddressElement;	/* Create */
	long sccpAddressInfoNrOfAddressElements;	/* Create */
	long sccpAddressInfoRowStatus;	/* Create */
};
struct sccpGtTranslatorTable_data {
	uint sccpGtTranslatorTable_request;
	uint sccpGtTranslatorTable_refs;
	ulong sccpNetworkEntityId;	/* NoAccess */
	uint8_t *sccpGtTranslatorId;	/* NoAccess */
	size_t sccpGtTranslatorIdLen;
	long sccpGtIndicator;		/* Create */
	long sccpGtNatureOfAddress;	/* Create */
	long sccpGtNumberingPlan;	/* Create */
	long sccpGtTranslationType;	/* Create */
	long sccpGtTranslatorAdministrativeState;	/* Create */
	uint8_t *sccpGtTranslatorName;	/* Create */
	size_t sccpGtTranslatorNameLen;
	long sccpGtTranslatorRowStatus;	/* Create */
};
struct sccpGtRuleTable_data {
	uint sccpGtRuleTable_request;
	uint sccpGtRuleTable_refs;
	ulong sccpNetworkEntityId;	/* NoAccess */
	uint8_t *sccpGtTranslatorId;	/* NoAccess */
	size_t sccpGtTranslatorIdLen;
	uint8_t *sccpGtRuleId;		/* NoAccess */
	size_t sccpGtRuleIdLen;
	long sccpGtRuleAdministrativeState;	/* Create */
	uint8_t *sccpGtAddressInformation;	/* Create */
	size_t sccpGtAddressInformationLen;
	uint8_t *sccpGtConvRulePointer;	/* Create */
	size_t sccpGtConvRulePointerLen;
	long sccpGtEncodingScheme;	/* Create */
	uint8_t *sccpEntitySetPointer;	/* Create */
	size_t sccpEntitySetPointerLen;
	uint8_t *sccpGtRuleName;	/* Create */
	size_t sccpGtRuleNameLen;
	long sccpGtRuleRowStatus;	/* Create */
};
struct sccpSrvtTable_data {
	uint sccpSrvtTable_request;
	uint sccpSrvtTable_refs;
	ulong sccpNetworkEntityId;	/* NoAccess */
	uint8_t *sccpRouteTestId;	/* NoAccess */
	size_t sccpRouteTestIdLen;
	long sccpDSRVT;			/* Create */
	long sccpNSRVT;			/* Create */
	uint8_t *sccpSrvtName;		/* Create */
	size_t sccpSrvtNameLen;
	long sccpAdministrativeState;	/* Create */
	long sccpOperationalState;	/* ReadOnly */
	uint8_t *sccpProceduralStatus;	/* ReadOnly */
	size_t sccpProceduralStatusLen;
	long sccpTraceRequested;	/* Create */
	long sccpThreshold;		/* Create */
	long sccpMtpBackwardRoutingRequested;	/* Create */
	uint8_t *sccpOriginalGT;	/* Create */
	size_t sccpOriginalGTLen;
	uint8_t *sccpInfoRequest;	/* Create */
	size_t sccpInfoRequestLen;
	uint8_t *sccpReturnUnknownParams;	/* Create */
	size_t sccpReturnUnknownParamsLen;
	long sccpRouteTestRowStatus;	/* Create */
};

/* storage declarations */
extern struct sccpMIB_data *sccpMIBStorage;
extern struct header_complex_index *sccpNetworkEntityTableStorage;
extern struct header_complex_index *sccpSapNameTableStorage;
extern struct header_complex_index *sccpAccessPointTableStorage;
extern struct header_complex_index *sccpLinkageTableStorage;
extern struct header_complex_index *sccpSclcTableStorage;
extern struct header_complex_index *sccpScocTableStorage;
extern struct header_complex_index *sccpScrcTableStorage;
extern struct header_complex_index *sccpEntitySetTableStorage;
extern struct header_complex_index *sccpEntitySetSapTableStorage;
extern struct header_complex_index *sccpConcernedAreaTableStorage;
extern struct header_complex_index *sccpRemoteSCCPTableStorage;
extern struct header_complex_index *sccpGtConversionRuleTableStorage;
extern struct header_complex_index *sccpAddressInfoTableStorage;
extern struct header_complex_index *sccpGtTranslatorTableStorage;
extern struct header_complex_index *sccpGtRuleTableStorage;
extern struct header_complex_index *sccpSrvtTableStorage;

/* enum definitions from the covered mib sections */

#define SCCPNETWORKENTITYALARMSTATUS_UNDERREPAIR 0
#define SCCPNETWORKENTITYALARMSTATUS_CRITICAL    1
#define SCCPNETWORKENTITYALARMSTATUS_MAJOR       2
#define SCCPNETWORKENTITYALARMSTATUS_MINOR       3
#define SCCPNETWORKENTITYALARMSTATUS_ALARMOUTSTANDING 4

#define SCCPSYSTEMTYPES_ES                       0
#define SCCPSYSTEMTYPES_IS                       1

#define SCCPLUDTANDLUDTSSUPPORTED_TRUE           1
#define SCCPLUDTANDLUDTSSUPPORTED_FALSE          2

#define SCCPACCESSPOINTALARMSTATUS_UNDERREPAIR   0
#define SCCPACCESSPOINTALARMSTATUS_CRITICAL      1
#define SCCPACCESSPOINTALARMSTATUS_MAJOR         2
#define SCCPACCESSPOINTALARMSTATUS_MINOR         3
#define SCCPACCESSPOINTALARMSTATUS_ALARMOUTSTANDING 4

#define SCCPAVAILABILITYSTATUS_INTEST            0
#define SCCPAVAILABILITYSTATUS_FAILED            1
#define SCCPAVAILABILITYSTATUS_POWEROFF          2
#define SCCPAVAILABILITYSTATUS_OFFLINE           3
#define SCCPAVAILABILITYSTATUS_OFFDUTY           4
#define SCCPAVAILABILITYSTATUS_DEPENDENCY        5
#define SCCPAVAILABILITYSTATUS_DEGRADED          6
#define SCCPAVAILABILITYSTATUS_NOTINSTALLED      7
#define SCCPAVAILABILITYSTATUS_LOGFULL           8

#define SCCPSSAVAILABLEAFTERSPRESTART_TRUE       1
#define SCCPSSAVAILABLEAFTERSPRESTART_FALSE      2

#define SCCPOPERATIONALPROTOCOLS_CLASS0          0
#define SCCPOPERATIONALPROTOCOLS_CLASS1          1
#define SCCPOPERATIONALPROTOCOLS_CLASS2          2
#define SCCPOPERATIONALPROTOCOLS_CLASS3          3

#define SCCPSCLCALARMSTATUS_UNDERREPAIR          0
#define SCCPSCLCALARMSTATUS_CRITICAL             1
#define SCCPSCLCALARMSTATUS_MAJOR                2
#define SCCPSCLCALARMSTATUS_MINOR                3
#define SCCPSCLCALARMSTATUS_ALARMOUTSTANDING     4

#define SCCPSCLCOPERATIONALSTATE_DISABLED        0
#define SCCPSCLCOPERATIONALSTATE_ENABLED         1

#define SCCPSCLCADMINISTRATIVESTATE_LOCKED       0
#define SCCPSCLCADMINISTRATIVESTATE_UNLOCKED     1
#define SCCPSCLCADMINISTRATIVESTATE_SHUTTINGDOWN 2

#define SCCPSCLCSUPPORTEDPROTOCOLS_CLASS0        0
#define SCCPSCLCSUPPORTEDPROTOCOLS_CLASS1        1
#define SCCPSCLCSUPPORTEDPROTOCOLS_CLASS2        2
#define SCCPSCLCSUPPORTEDPROTOCOLS_CLASS3        3

#define SCCPSCLCOPERATIONALSYSTEMTYPE_ES         0
#define SCCPSCLCOPERATIONALSYSTEMTYPE_IS         1

#define SCCPSCOCOPERATIONALSTATE_DISABLED        0
#define SCCPSCOCOPERATIONALSTATE_ENABLED         1

#define SCCPSCOCADMINISTRATIVESTATE_LOCKED       0
#define SCCPSCOCADMINISTRATIVESTATE_UNLOCKED     1
#define SCCPSCOCADMINISTRATIVESTATE_SHUTTINGDOWN 2

#define SCCPSCOCOPERATIONALSYSTEMTYPE_ES         0
#define SCCPSCOCOPERATIONALSYSTEMTYPE_IS         1

#define SCCPSCOCSUPPORTEDPROTOCOLS_CLASS0        0
#define SCCPSCOCSUPPORTEDPROTOCOLS_CLASS1        1
#define SCCPSCOCSUPPORTEDPROTOCOLS_CLASS2        2
#define SCCPSCOCSUPPORTEDPROTOCOLS_CLASS3        3

#define SCCPSCRCALARMSTATUS_UNDERREPAIR          0
#define SCCPSCRCALARMSTATUS_CRITICAL             1
#define SCCPSCRCALARMSTATUS_MAJOR                2
#define SCCPSCRCALARMSTATUS_MINOR                3
#define SCCPSCRCALARMSTATUS_ALARMOUTSTANDING     4

#define SCCPSHARINGMODE_SOLITARY                 0
#define SCCPSHARINGMODE_DUPLIDOMINANT            1
#define SCCPSHARINGMODE_DUPLIREPLACEMENT         2
#define SCCPSHARINGMODE_DUPLILOADSHARED          3

#define SCCPENTITYSETTYPE_ENDNODEENTITYSETWITHOUTSSN 2
#define SCCPENTITYSETTYPE_ENDNODEENTITYSETWITHSSN 3
#define SCCPENTITYSETTYPE_RELAYNODEENTITYSET     7

#define SCCPENTITYSETSAPTYPE_EQUAL               0
#define SCCPENTITYSETSAPTYPE_PRIMARY             1
#define SCCPENTITYSETSAPTYPE_BACKUP              2

#define SCCPGTNEWENCODINGSCHEME_UNKNOWN          0
#define SCCPGTNEWENCODINGSCHEME_BCDODD           1
#define SCCPGTNEWENCODINGSCHEME_BCDEVEN          2
#define SCCPGTNEWENCODINGSCHEME_NATIONALSPECIFIC 3
#define SCCPGTNEWENCODINGSCHEME_NOTUSEDORNOOVERWITE 256

#define SCCPGTNEWNATUREOFADDRESS_UNKNOWN         0
#define SCCPGTNEWNATUREOFADDRESS_ISDNTNP         1
#define SCCPGTNEWNATUREOFADDRESS_GENERICNUMBERINGPLAN 2
#define SCCPGTNEWNATUREOFADDRESS_DNP             3
#define SCCPGTNEWNATUREOFADDRESS_TNP             4
#define SCCPGTNEWNATUREOFADDRESS_MMNP            5
#define SCCPGTNEWNATUREOFADDRESS_LMNP            6
#define SCCPGTNEWNATUREOFADDRESS_ISDNMNP         7
#define SCCPGTNEWNATUREOFADDRESS_PRIVATENUMBERINGPLAN 14
#define SCCPGTNEWNATUREOFADDRESS_NOTUSEDORNOOVERWITE 256

#define SCCPGTNEWNUMBERINGPLAN_UNKNOWN           0
#define SCCPGTNEWNUMBERINGPLAN_SUBSCRIBER        1
#define SCCPGTNEWNUMBERINGPLAN_NATIONAL          3
#define SCCPGTNEWNUMBERINGPLAN_INTERNATIONAL     4
#define SCCPGTNEWNUMBERINGPLAN_NOTUSEDORNOOVERWRITE 256

#define SCCPGTNEWTRANSLATIONTYPE_UNKNOWN         0
#define SCCPGTNEWTRANSLATIONTYPE_ITCC            1
#define SCCPGTNEWTRANSLATIONTYPE_GENERICNUMBERINGPLAN 14
#define SCCPGTNEWTRANSLATIONTYPE_IEESS           17
#define SCCPGTNEWTRANSLATIONTYPE_NOTUSEDORNOOVERWRITE 256

#define SCCPADDRESSINFOOPERATION_INSERT          0
#define SCCPADDRESSINFOOPERATION_REPLACE         1
#define SCCPADDRESSINFOOPERATION_PASSTRANSPARENTLY 2
#define SCCPADDRESSINFOOPERATION_DELETE          3
#define SCCPADDRESSINFOOPERATION_STOP            4
#define SCCPADDRESSINFOOPERATION_COPYREMAIN      5

#define SCCPGTINDICATOR_NOGLOBALTITLE            0
#define SCCPGTINDICATOR_NOAONLY                  1
#define SCCPGTINDICATOR_TTONLY                   2
#define SCCPGTINDICATOR_TT_NP_ES                 3
#define SCCPGTINDICATOR_TT_NP_ES_NOA             4

#define SCCPGTNATUREOFADDRESS_UNKNOWN            0
#define SCCPGTNATUREOFADDRESS_ISDNTNP            1
#define SCCPGTNATUREOFADDRESS_GENERICNUMBERINGPLAN 2
#define SCCPGTNATUREOFADDRESS_DNP                3
#define SCCPGTNATUREOFADDRESS_TNP                4
#define SCCPGTNATUREOFADDRESS_MMNP               5
#define SCCPGTNATUREOFADDRESS_LMNP               6
#define SCCPGTNATUREOFADDRESS_ISDNMNP            7
#define SCCPGTNATUREOFADDRESS_PRIVATENUMBERINGPLAN 14
#define SCCPGTNATUREOFADDRESS_NOTUSEDORNOOVERWITE 256

#define SCCPGTNUMBERINGPLAN_UNKNOWN              0
#define SCCPGTNUMBERINGPLAN_SUBSCRIBER           1
#define SCCPGTNUMBERINGPLAN_NATIONAL             3
#define SCCPGTNUMBERINGPLAN_INTERNATIONAL        4
#define SCCPGTNUMBERINGPLAN_NOTUSEDORNOOVERWRITE 256

#define SCCPGTTRANSLATIONTYPE_UNKNOWN            0
#define SCCPGTTRANSLATIONTYPE_ITCC               1
#define SCCPGTTRANSLATIONTYPE_GENERICNUMBERINGPLAN 14
#define SCCPGTTRANSLATIONTYPE_IEESS              17
#define SCCPGTTRANSLATIONTYPE_NOTUSEDORNOOVERWRITE 256

#define SCCPGTTRANSLATORADMINISTRATIVESTATE_LOCKED 0
#define SCCPGTTRANSLATORADMINISTRATIVESTATE_UNLOCKED 1
#define SCCPGTTRANSLATORADMINISTRATIVESTATE_SHUTTINGDOWN 2

#define SCCPGTRULEADMINISTRATIVESTATE_LOCKED     0
#define SCCPGTRULEADMINISTRATIVESTATE_UNLOCKED   1
#define SCCPGTRULEADMINISTRATIVESTATE_SHUTTINGDOWN 2

#define SCCPGTENCODINGSCHEME_UNKNOWN             0
#define SCCPGTENCODINGSCHEME_BCDODD              1
#define SCCPGTENCODINGSCHEME_BCDEVEN             2
#define SCCPGTENCODINGSCHEME_NATIONALSPECIFIC    3
#define SCCPGTENCODINGSCHEME_NOTUSEDORNOOVERWITE 256

#define SCCPADMINISTRATIVESTATE_LOCKED           0
#define SCCPADMINISTRATIVESTATE_UNLOCKED         1
#define SCCPADMINISTRATIVESTATE_SHUTTINGDOWN     2

#define SCCPOPERATIONALSTATE_DISABLED            0
#define SCCPOPERATIONALSTATE_ENABLED             1

#define SCCPPROCEDURALSTATUS_INITIALIZATIONREQUIRED 0
#define SCCPPROCEDURALSTATUS_NOTINITIALIZED      1
#define SCCPPROCEDURALSTATUS_INITIALIZING        2
#define SCCPPROCEDURALSTATUS_REPORTING           3
#define SCCPPROCEDURALSTATUS_TERMINATING         4

#define SCCPTRACEREQUESTED_TRUE                  1
#define SCCPTRACEREQUESTED_FALSE                 2

#define SCCPMTPBACKWARDROUTINGREQUESTED_TRUE     1
#define SCCPMTPBACKWARDROUTINGREQUESTED_FALSE    2

#define SCCPINFOREQUEST_POINTCODE                0
#define SCCPINFOREQUEST_POINTCODELIST            1
#define SCCPINFOREQUEST_ROUTEPRIORITYLIST        2

#define SCCPRETURNUNKNOWNPARAMS_TAG15            0
#define SCCPRETURNUNKNOWNPARAMS_TAG16            1

#define FAILURETYPE_DETECTEDLOOP                 0
#define FAILURETYPE_EXCESSIVELENGTHROUTE         1
#define FAILURETYPE_UNKNOWNDESTINATION           2
#define FAILURETYPE_ROUTEINACCESIBLE             3
#define FAILURETYPE_PROCESSINGFAILURE            4
#define FAILURETYPE_UNKNOWNINITIATINGSP          5
#define FAILURETYPE_TIMEREXPIRED                 6
#define FAILURETYPE_WRONGSP                      7
#define FAILURETYPE_INCORRECTTRANSLATION_PRIMARY 8
#define FAILURETYPE_INCORRECTTRANSLATION_SECONDARY 9
#define FAILURETYPE_INCORRECTTRANSLATION_INTERMEDIATE 10
#define FAILURETYPE_NOTPRIMARYDESTINATION        11
#define FAILURETYPE_NOTSECONDARYDESTINATION      12
#define FAILURETYPE_NOTRECOGNIZEDPRIMARY         13
#define FAILURETYPE_NOTRECOGNIZEDSECONDARY       14
#define FAILURETYPE_ROUTINGPROBLEM               15
#define FAILURETYPE_MAXNRSRVTTESTSALREADY        16
#define FAILURETYPE_INDIRECTROUTE                17

/* notifications */
extern oid sccpRouteTestResult_oid[12];

/* scalars accessible only for notify */
extern oid failureType_oid[13];
extern oid traceSent_oid[13];
extern oid pointCodeList_oid[13];
extern oid routePriorityList_oid[13];
extern oid copyData_oid[13];
extern oid congestionLevel_oid[13];
extern oid globalTitle_oid[13];

/* object id definitions */
extern oid sccpLoadSharingRoundRobin_oid[13];
extern oid sccpLoadSharingSlsSplitting_oid[13];
extern oid sccpMIBCompliance_oid[13];
extern oid sccpNetworkEntityGroup_oid[13];
extern oid sccpSapNameGroup_oid[13];
extern oid sccpAccessPointGroup_oid[13];
extern oid sccpRemoteSAPGroup_oid[13];
extern oid sccpAvailableAfterSpRestartPackage_oid[13];
extern oid sccpLinkageGroup_oid[13];
extern oid sccpSclcGroup_oid[13];
extern oid sccpScocGroup_oid[13];
extern oid sccpScrcGroup_oid[13];
extern oid sccpEntitySetGroup_oid[13];
extern oid sccpConcernedAreaGroup_oid[13];
extern oid sccpRemoteSCCPGroup_oid[13];
extern oid sccpGtTranslatorGroup_oid[13];
extern oid sccpSrvtGroup_oid[13];
extern oid sccpLocalSccpLinkagePackage_oid[13];
extern oid sccpCongestionPackage_oid[13];
extern oid sccpAddressInfoConversionRulePackage_oid[13];
extern oid sccpCommonLanguageNameGroup_oid[13];

/* function prototypes */
/* trap function prototypes */
extern void send_sccpRouteTestResult_v2trap(struct variable_list *);

/* variable function prototypes */
void init_sccpMIB(void);
void deinit_sccpMIB(void);
int term_sccpMIB(int majorID, int minorID, void *serverarg, void *clientarg);
FindVarMethod var_sccpMIB;
void parse_sccpMIB(const char *, char *);
SNMPCallback store_sccpMIB;
void refresh_sccpMIB(int);
FindVarMethod var_sccpNetworkEntityTable;
struct sccpNetworkEntityTable_data *sccpNetworkEntityTable_create(void);
struct sccpNetworkEntityTable_data *sccpNetworkEntityTable_duplicate(struct sccpNetworkEntityTable_data *);
int sccpNetworkEntityTable_destroy(struct sccpNetworkEntityTable_data **);
int sccpNetworkEntityTable_add(struct sccpNetworkEntityTable_data *);
int sccpNetworkEntityTable_del(struct sccpNetworkEntityTable_data *);
void parse_sccpNetworkEntityTable(const char *, char *);
SNMPCallback store_sccpNetworkEntityTable;
void refresh_sccpNetworkEntityTable(int);
FindVarMethod var_sccpSapNameTable;
struct sccpSapNameTable_data *sccpSapNameTable_create(void);
struct sccpSapNameTable_data *sccpSapNameTable_duplicate(struct sccpSapNameTable_data *);
int sccpSapNameTable_destroy(struct sccpSapNameTable_data **);
int sccpSapNameTable_add(struct sccpSapNameTable_data *);
int sccpSapNameTable_del(struct sccpSapNameTable_data *);
void parse_sccpSapNameTable(const char *, char *);
SNMPCallback store_sccpSapNameTable;
void refresh_sccpSapNameTable(int);
FindVarMethod var_sccpAccessPointTable;
struct sccpAccessPointTable_data *sccpAccessPointTable_create(void);
struct sccpAccessPointTable_data *sccpAccessPointTable_duplicate(struct sccpAccessPointTable_data *);
int sccpAccessPointTable_destroy(struct sccpAccessPointTable_data **);
int sccpAccessPointTable_add(struct sccpAccessPointTable_data *);
int sccpAccessPointTable_del(struct sccpAccessPointTable_data *);
void parse_sccpAccessPointTable(const char *, char *);
SNMPCallback store_sccpAccessPointTable;
void refresh_sccpAccessPointTable(int);
FindVarMethod var_sccpLinkageTable;
struct sccpLinkageTable_data *sccpLinkageTable_create(void);
struct sccpLinkageTable_data *sccpLinkageTable_duplicate(struct sccpLinkageTable_data *);
int sccpLinkageTable_destroy(struct sccpLinkageTable_data **);
int sccpLinkageTable_add(struct sccpLinkageTable_data *);
int sccpLinkageTable_del(struct sccpLinkageTable_data *);
void parse_sccpLinkageTable(const char *, char *);
SNMPCallback store_sccpLinkageTable;
void refresh_sccpLinkageTable(int);
FindVarMethod var_sccpSclcTable;
struct sccpSclcTable_data *sccpSclcTable_create(void);
struct sccpSclcTable_data *sccpSclcTable_duplicate(struct sccpSclcTable_data *);
int sccpSclcTable_destroy(struct sccpSclcTable_data **);
int sccpSclcTable_add(struct sccpSclcTable_data *);
int sccpSclcTable_del(struct sccpSclcTable_data *);
void parse_sccpSclcTable(const char *, char *);
SNMPCallback store_sccpSclcTable;
void refresh_sccpSclcTable(int);
FindVarMethod var_sccpScocTable;
struct sccpScocTable_data *sccpScocTable_create(void);
struct sccpScocTable_data *sccpScocTable_duplicate(struct sccpScocTable_data *);
int sccpScocTable_destroy(struct sccpScocTable_data **);
int sccpScocTable_add(struct sccpScocTable_data *);
int sccpScocTable_del(struct sccpScocTable_data *);
void parse_sccpScocTable(const char *, char *);
SNMPCallback store_sccpScocTable;
void refresh_sccpScocTable(int);
FindVarMethod var_sccpScrcTable;
struct sccpScrcTable_data *sccpScrcTable_create(void);
struct sccpScrcTable_data *sccpScrcTable_duplicate(struct sccpScrcTable_data *);
int sccpScrcTable_destroy(struct sccpScrcTable_data **);
int sccpScrcTable_add(struct sccpScrcTable_data *);
int sccpScrcTable_del(struct sccpScrcTable_data *);
void parse_sccpScrcTable(const char *, char *);
SNMPCallback store_sccpScrcTable;
void refresh_sccpScrcTable(int);
FindVarMethod var_sccpEntitySetTable;
struct sccpEntitySetTable_data *sccpEntitySetTable_create(void);
struct sccpEntitySetTable_data *sccpEntitySetTable_duplicate(struct sccpEntitySetTable_data *);
int sccpEntitySetTable_destroy(struct sccpEntitySetTable_data **);
int sccpEntitySetTable_add(struct sccpEntitySetTable_data *);
int sccpEntitySetTable_del(struct sccpEntitySetTable_data *);
void parse_sccpEntitySetTable(const char *, char *);
SNMPCallback store_sccpEntitySetTable;
void refresh_sccpEntitySetTable(int);
FindVarMethod var_sccpEntitySetSapTable;
struct sccpEntitySetSapTable_data *sccpEntitySetSapTable_create(void);
struct sccpEntitySetSapTable_data *sccpEntitySetSapTable_duplicate(struct sccpEntitySetSapTable_data *);
int sccpEntitySetSapTable_destroy(struct sccpEntitySetSapTable_data **);
int sccpEntitySetSapTable_add(struct sccpEntitySetSapTable_data *);
int sccpEntitySetSapTable_del(struct sccpEntitySetSapTable_data *);
void parse_sccpEntitySetSapTable(const char *, char *);
SNMPCallback store_sccpEntitySetSapTable;
void refresh_sccpEntitySetSapTable(int);
FindVarMethod var_sccpConcernedAreaTable;
struct sccpConcernedAreaTable_data *sccpConcernedAreaTable_create(void);
struct sccpConcernedAreaTable_data *sccpConcernedAreaTable_duplicate(struct sccpConcernedAreaTable_data *);
int sccpConcernedAreaTable_destroy(struct sccpConcernedAreaTable_data **);
int sccpConcernedAreaTable_add(struct sccpConcernedAreaTable_data *);
int sccpConcernedAreaTable_del(struct sccpConcernedAreaTable_data *);
void parse_sccpConcernedAreaTable(const char *, char *);
SNMPCallback store_sccpConcernedAreaTable;
void refresh_sccpConcernedAreaTable(int);
FindVarMethod var_sccpRemoteSCCPTable;
struct sccpRemoteSCCPTable_data *sccpRemoteSCCPTable_create(void);
struct sccpRemoteSCCPTable_data *sccpRemoteSCCPTable_duplicate(struct sccpRemoteSCCPTable_data *);
int sccpRemoteSCCPTable_destroy(struct sccpRemoteSCCPTable_data **);
int sccpRemoteSCCPTable_add(struct sccpRemoteSCCPTable_data *);
int sccpRemoteSCCPTable_del(struct sccpRemoteSCCPTable_data *);
void parse_sccpRemoteSCCPTable(const char *, char *);
SNMPCallback store_sccpRemoteSCCPTable;
void refresh_sccpRemoteSCCPTable(int);
FindVarMethod var_sccpGtConversionRuleTable;
struct sccpGtConversionRuleTable_data *sccpGtConversionRuleTable_create(void);
struct sccpGtConversionRuleTable_data *sccpGtConversionRuleTable_duplicate(struct sccpGtConversionRuleTable_data *);
int sccpGtConversionRuleTable_destroy(struct sccpGtConversionRuleTable_data **);
int sccpGtConversionRuleTable_add(struct sccpGtConversionRuleTable_data *);
int sccpGtConversionRuleTable_del(struct sccpGtConversionRuleTable_data *);
void parse_sccpGtConversionRuleTable(const char *, char *);
SNMPCallback store_sccpGtConversionRuleTable;
void refresh_sccpGtConversionRuleTable(int);
FindVarMethod var_sccpAddressInfoTable;
struct sccpAddressInfoTable_data *sccpAddressInfoTable_create(void);
struct sccpAddressInfoTable_data *sccpAddressInfoTable_duplicate(struct sccpAddressInfoTable_data *);
int sccpAddressInfoTable_destroy(struct sccpAddressInfoTable_data **);
int sccpAddressInfoTable_add(struct sccpAddressInfoTable_data *);
int sccpAddressInfoTable_del(struct sccpAddressInfoTable_data *);
void parse_sccpAddressInfoTable(const char *, char *);
SNMPCallback store_sccpAddressInfoTable;
void refresh_sccpAddressInfoTable(int);
FindVarMethod var_sccpGtTranslatorTable;
struct sccpGtTranslatorTable_data *sccpGtTranslatorTable_create(void);
struct sccpGtTranslatorTable_data *sccpGtTranslatorTable_duplicate(struct sccpGtTranslatorTable_data *);
int sccpGtTranslatorTable_destroy(struct sccpGtTranslatorTable_data **);
int sccpGtTranslatorTable_add(struct sccpGtTranslatorTable_data *);
int sccpGtTranslatorTable_del(struct sccpGtTranslatorTable_data *);
void parse_sccpGtTranslatorTable(const char *, char *);
SNMPCallback store_sccpGtTranslatorTable;
void refresh_sccpGtTranslatorTable(int);
FindVarMethod var_sccpGtRuleTable;
struct sccpGtRuleTable_data *sccpGtRuleTable_create(void);
struct sccpGtRuleTable_data *sccpGtRuleTable_duplicate(struct sccpGtRuleTable_data *);
int sccpGtRuleTable_destroy(struct sccpGtRuleTable_data **);
int sccpGtRuleTable_add(struct sccpGtRuleTable_data *);
int sccpGtRuleTable_del(struct sccpGtRuleTable_data *);
void parse_sccpGtRuleTable(const char *, char *);
SNMPCallback store_sccpGtRuleTable;
void refresh_sccpGtRuleTable(int);
FindVarMethod var_sccpSrvtTable;
struct sccpSrvtTable_data *sccpSrvtTable_create(void);
struct sccpSrvtTable_data *sccpSrvtTable_duplicate(struct sccpSrvtTable_data *);
int sccpSrvtTable_destroy(struct sccpSrvtTable_data **);
int sccpSrvtTable_add(struct sccpSrvtTable_data *);
int sccpSrvtTable_del(struct sccpSrvtTable_data *);
void parse_sccpSrvtTable(const char *, char *);
SNMPCallback store_sccpSrvtTable;
void refresh_sccpSrvtTable(int);

WriteMethod write_sccpNetworkEntityAlarmStatus;
WriteMethod write_sccpVersion;
WriteMethod write_sccpLUDTandLUDTSSupported;
WriteMethod write_sccpCoordChangeTimer;
WriteMethod write_sccpIgnoreSSTTimer;
WriteMethod write_sccpMaxStatInfoTimer;
WriteMethod write_sccpNetworkEntityName;
WriteMethod write_sccpRowStatus;
WriteMethod write_sccpSapNameRowStatus;
WriteMethod write_sccpAccessPointAlarmStatus;
WriteMethod write_sccpSap2Address;
WriteMethod write_sccpUserEntityNames;
WriteMethod write_sccpProviderEntityNames;
WriteMethod write_sccpConcernedAreaPointer;
WriteMethod write_sccpLinkagePointer;
WriteMethod write_sccpSsAvailableAfterSpRestart;
WriteMethod write_sccpAccessPointName;
WriteMethod write_sccpAccessPointRowStatus;
WriteMethod write_sccpAttackTimerValue;
WriteMethod write_sccpDecayTimerValue;
WriteMethod write_sccpNrOfRestrictionLevels;
WriteMethod write_sccpNrOfSubLevels;
WriteMethod write_sccpCLS;
WriteMethod write_sccpCongestionTimerValue;
WriteMethod write_sccpp;
WriteMethod write_sccpImportanceLevelCR;
WriteMethod write_sccpImportanceLevelCC;
WriteMethod write_sccpImportanceLevelCREF;
WriteMethod write_sccpImportanceLevelDT1;
WriteMethod write_sccpImportanceLevelDT2;
WriteMethod write_sccpImportanceLevelAK;
WriteMethod write_sccpImportanceLevelIT;
WriteMethod write_sccpImportanceLevelED;
WriteMethod write_sccpImportanceLevelEA;
WriteMethod write_sccpImportanceLevelRSR;
WriteMethod write_sccpImportanceLevelRSC;
WriteMethod write_sccpImportanceLevelERR;
WriteMethod write_sccpImportanceLevelRLC;
WriteMethod write_sccpImportanceLevelRLSD;
WriteMethod write_sccpImportanceLevelUDT;
WriteMethod write_sccpImportanceLevelUDTS;
WriteMethod write_sccpImportanceLevelXUDT;
WriteMethod write_sccpImportanceLevelXUDTS;
WriteMethod write_sccpImportanceLevelLUDT;
WriteMethod write_sccpImportanceLevelLUDTS;
WriteMethod write_sccpRLM;
WriteMethod write_sccpRSLM;
WriteMethod write_sccpLinkageConcernedAreaPointer;
WriteMethod write_sccpLowerLimitForSegmentation;
WriteMethod write_sccpUpperLimitForSegmentation;
WriteMethod write_sccpLinkageName;
WriteMethod write_sccpLinkageRowStatus;
WriteMethod write_sccpSclcAlarmStatus;
WriteMethod write_sccpSclcAdministrativeState;
WriteMethod write_sccpSclcOperationalSystemType;
WriteMethod write_sccpInitialValueReassTimer;
WriteMethod write_sccpSclcName;
WriteMethod write_sccpSclcRowStatus;
WriteMethod write_sccpCoProtocolMachineId;
WriteMethod write_sccpScocAdministrativeState;
WriteMethod write_sccpScocOperationalSystemType;
WriteMethod write_sccpScocName;
WriteMethod write_sccpScocRowStatus;
WriteMethod write_sccpScrcId;
WriteMethod write_sccpScrcAlarmStatus;
WriteMethod write_sccpScrcName;
WriteMethod write_sccpScrcRowStatus;
WriteMethod write_sccpSharingMode;
WriteMethod write_sccpLoadSharingAlgPointer;
WriteMethod write_sccpEntitySetName;
WriteMethod write_sccpEntitySetType;
WriteMethod write_sccpEntitySetSsn;
WriteMethod write_sccpEntitySetRowStatus;
WriteMethod write_sccpEntitySetSapType;
WriteMethod write_sccpEntitySetSapPointer;
WriteMethod write_sccpEntitySetSapRowStatus;
WriteMethod write_sccpRemoteSCCPMTPAccessPoint;
WriteMethod write_sccpRemoteSCCPName;
WriteMethod write_sccpRemoteSCCPRowStatus;
WriteMethod write_sccpGtNewEncodingScheme;
WriteMethod write_sccpGtNewNatureOfAddress;
WriteMethod write_sccpGtNewNumberingPlan;
WriteMethod write_sccpGtNewTranslationType;
WriteMethod write_sccpGtConversionRuleName;
WriteMethod write_sccpGtConversionRuleRowStatus;
WriteMethod write_sccpAddressInfoOperation;
WriteMethod write_sccpAddressInfoAddressElement;
WriteMethod write_sccpAddressInfoNrOfAddressElements;
WriteMethod write_sccpAddressInfoRowStatus;
WriteMethod write_sccpGtIndicator;
WriteMethod write_sccpGtNatureOfAddress;
WriteMethod write_sccpGtNumberingPlan;
WriteMethod write_sccpGtTranslationType;
WriteMethod write_sccpGtTranslatorAdministrativeState;
WriteMethod write_sccpGtTranslatorName;
WriteMethod write_sccpGtTranslatorRowStatus;
WriteMethod write_sccpGtRuleAdministrativeState;
WriteMethod write_sccpGtAddressInformation;
WriteMethod write_sccpGtConvRulePointer;
WriteMethod write_sccpGtEncodingScheme;
WriteMethod write_sccpEntitySetPointer;
WriteMethod write_sccpGtRuleName;
WriteMethod write_sccpGtRuleRowStatus;
WriteMethod write_sccpDSRVT;
WriteMethod write_sccpNSRVT;
WriteMethod write_sccpSrvtName;
WriteMethod write_sccpAdministrativeState;
WriteMethod write_sccpTraceRequested;
WriteMethod write_sccpThreshold;
WriteMethod write_sccpMtpBackwardRoutingRequested;
WriteMethod write_sccpOriginalGT;
WriteMethod write_sccpInfoRequest;
WriteMethod write_sccpReturnUnknownParams;
WriteMethod write_sccpRouteTestRowStatus;
#endif				/* __LOCAL_SCCPMIB_H__ */
