/*****************************************************************************

 @(#) $RCSfile: ss7MIB.c,v $ $Name:  $($Revision: 0.9.2.4 $) $Date: 2008-12-31 16:04:47 $

 -----------------------------------------------------------------------------

 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software: you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation, version 3 of the license.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 -----------------------------------------------------------------------------

 Last Modified $Date: 2008-12-31 16:04:47 $ by $Author: brian $

 -----------------------------------------------------------------------------

 $Log: ss7MIB.c,v $
 Revision 0.9.2.4  2008-12-31 16:04:47  brian
 - updated mibs

 Revision 0.9.2.3  2008-12-27 15:29:48  brian
 - split MTP and MTP OM mib

 Revision 0.9.2.2  2008-12-24 13:08:26  brian
 - building ss7confd

 *****************************************************************************/

#ident "@(#) $RCSfile: ss7MIB.c,v $ $Name:  $($Revision: 0.9.2.4 $) $Date: 2008-12-31 16:04:47 $"

static char const ident[] = "$RCSfile: ss7MIB.c,v $ $Name:  $($Revision: 0.9.2.4 $) $Date: 2008-12-31 16:04:47 $";

/* This file was generated by mib2c and is intended for use as
   a mib module for the ucd-snmp snmpd agent. */
#include <ucd-snmp/ucd-snmp-config.h>
#include <ucd-snmp/ucd-snmp-includes.h>
#include <ucd-snmp/ucd-snmp-agent-includes.h>
#include <ucd-snmp/callback.h>
#include <ucd-snmp/snmp-tc.h>
#include <ucd-snmp/default_store.h>
#include <ucd-snmp/snmp_alarm.h>
/* The following header files are mangled in most recent net-snmp releases so
 * the versions from UCD-SNMP 4.2.5 are included here.  */
#if defined HAVE_LIBNETSNMP
#else				/* defined HAVE_LIBNETSNMP */
#endif				/* defined HAVE_LIBNETSNMP */
/* These are messed up on both. */
#include "ds_agent.h"
#ifdef HAVE_UCD_SNMP_UTIL_FUNCS_H
#include <ucd-snmp/util_funcs.h>
/* Many recent net-snmp UCD compatible headers do not declard header_generic. */
int header_generic(struct variable *, oid *, size_t *, int, size_t *, WriteMethod **);
#else				/* HAVE_UCD_SNMP_UTIL_FUNCS_H */
#include "util_funcs.h"
#endif				/* HAVE_UCD_SNMP_UTIL_FUNCS_H */
#ifdef HAVE_UCD_SNMP_HEADER_COMPLEX_H
#include <ucd-snmp/header_complex.h>
#else				/* HAVE_UCD_SNMP_HEADER_COMPLEX_H */
#include "header_complex.h"
#endif				/* HAVE_UCD_SNMP_HEADER_COMPLEX_H */
/* This one is the other way around: it is just fine for net-snmp, but
 * ucd-snmp does not provide the header file at all.  */
#ifdef HAVE_UCD_SNMP_MIB_MODULES_H
#include <ucd-snmp/mib_modules.h>
#else				/* HAVE_UCD_SNMP_MIB_MODULES_H */
#ifdef HAVE_NET_SNMP_AGENT_MIB_MODULES_H
#include <net-snmp/agent/mib_modules.h>
#else				/* HAVE_NET_SNMP_AGENT_MIB_MODULES_H */
#include "mib_modules.h"
#endif				/* HAVE_NET_SNMP_AGENT_MIB_MODULES_H */
#endif				/* HAVE_UCD_SNMP_MIB_MODULES_H */
#include <stdint.h>
#include <signal.h>
#include <sys/stat.h>		/* for struct stat, fstat() */
#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>
#include <pwd.h>		/* for getpwuid() getpwnam() */
#include <grp.h>		/* for getgrgid() getgrnam() */
#include <libgen.h>		/* for basename() */
#include <fcntl.h>		/* for O_CREAT */
#include <sys/sysctl.h>		/* for sysctl */
#include <errno.h>
#include <string.h>
#ifdef _GNU_SOURCE
#include <getopt.h>
#endif
#include "ss7MIB.h"
const char sa_program[] = "ss7mib";

#define MY_FACILITY(__pri)	(LOG_DAEMON|(__pri))
#if !defined MODULE
int sa_dump = 0;			/* default packet dump */
int sa_debug = 0;			/* default no debug */
int sa_nomead = 1;			/* default daemon mode */
int sa_output = 1;			/* default normal output */
int sa_agentx = 1;			/* default agentx mode */
int sa_alarms = 1;			/* default application alarms */
int sa_fclose = 1;			/* default close files between requests */
int sa_logaddr = 0;			/* log addresses */
int sa_logfillog = 0;			/* log to sa_logfile */
int sa_logstderr = 0;			/* log to standard error */
int sa_logstdout = 0;			/* log to standard output */
int sa_logsyslog = 0;			/* log to system logs */
int sa_logcallog = 0;			/* log to callback logs */
int sa_appendlog = 0;			/* append to log file without truncating */
char sa_logfile[256] = "/var/log/ss7mib.log";
char sa_pidfile[256] = "/var/run/ss7mib.pid";
char sa_sysctlf[256] = "/etc/ss7mib.conf";
int allow_severity = LOG_ERR;
int deny_severity = LOG_ERR;

/* file stream for log file */
FILE *stdlog = NULL;

/* file descriptor for MIB use */
int sa_fd = 0;

/* indication to reread MIB configuration */
int sa_changed = 1;

/* indications that statistics, the mib or its tables need to be refreshed */
int sa_stats_refresh = 1;
#else				/* !defined MODULE */
#endif				/* !defined MODULE */
/* request number for per-request actions */
int sa_request = 1;
volatile int ss7MIB_refresh = 1;
volatile int ss7NetworkTable_refresh = 1;

/*
 * ss7MIB_variables_oid: object identifier for ss7MIB
 * This is the top level oid that we want to register under.  This is essentially a prefix, with the
 * suffix appearing in the variable below.
 */
oid ss7MIB_variables_oid[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0 };
oid ss7NetworkTable_variables_oid[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 2, 1, 1 };

oid ss7ProtocolItut[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1 };
oid ss7ProtocolItut1980[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1, 1980 };
oid ss7ProtocolItut1984[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1, 1984 };
oid ss7ProtocolItut1988[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1, 1988 };
oid ss7ProtocolItut1992[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1, 1992 };
oid ss7ProtocolItut1996[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1, 1996 };
oid ss7ProtocolItut2000[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1, 2000 };
oid ss7ProtocolItut2004[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1, 2004 };
oid ss7ProtocolItut2008[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 1, 2008 };

oid ss7ProtocolEtsi[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2 };
oid ss7ProtocolEtsi1980[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2, 1980 };
oid ss7ProtocolEtsi1984[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2, 1984 };
oid ss7ProtocolEtsi1988[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2, 1988 };
oid ss7ProtocolEtsi1992[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2, 1992 };
oid ss7ProtocolEtsi1996[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2, 1996 };
oid ss7ProtocolEtsi2000[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2, 2000 };
oid ss7ProtocolEtsi2004[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2, 2004 };
oid ss7ProtocolEtsi2008[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 2, 2008 };

oid ss7ProtocolAnsi[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3 };
oid ss7ProtocolAnsi1980[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3, 1980 };
oid ss7ProtocolAnsi1984[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3, 1984 };
oid ss7ProtocolAnsi1988[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3, 1988 };
oid ss7ProtocolAnsi1992[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3, 1992 };
oid ss7ProtocolAnsi1996[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3, 1996 };
oid ss7ProtocolAnsi2000[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3, 2000 };
oid ss7ProtocolAnsi2004[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3, 2004 };
oid ss7ProtocolAnsi2008[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 3, 2008 };

oid ss7ProtocolJttc[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4 };
oid ss7ProtocolJttc1980[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4, 1980 };
oid ss7ProtocolJttc1984[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4, 1984 };
oid ss7ProtocolJttc1988[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4, 1988 };
oid ss7ProtocolJttc1992[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4, 1992 };
oid ss7ProtocolJttc1996[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4, 1996 };
oid ss7ProtocolJttc2000[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4, 2000 };
oid ss7ProtocolJttc2004[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4, 2004 };
oid ss7ProtocolJttc2008[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 4, 2008 };

oid ss7ProtocolChin[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5 };
oid ss7ProtocolChin1980[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5, 1980 };
oid ss7ProtocolChin1984[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5, 1984 };
oid ss7ProtocolChin1988[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5, 1988 };
oid ss7ProtocolChin1992[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5, 1992 };
oid ss7ProtocolChin1996[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5, 1996 };
oid ss7ProtocolChin2000[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5, 2000 };
oid ss7ProtocolChin2004[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5, 2004 };
oid ss7ProtocolChin2008[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 5, 2008 };

oid ss7ProtocolSing[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6 };
oid ss7ProtocolSing1980[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6, 1980 };
oid ss7ProtocolSing1984[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6, 1984 };
oid ss7ProtocolSing1988[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6, 1988 };
oid ss7ProtocolSing1992[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6, 1992 };
oid ss7ProtocolSing1996[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6, 1996 };
oid ss7ProtocolSing2000[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6, 2000 };
oid ss7ProtocolSing2004[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6, 2004 };
oid ss7ProtocolSing2008[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 6, 2008 };

oid ss7ProtocolSpan[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7 };
oid ss7ProtocolSpan1980[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7, 1980 };
oid ss7ProtocolSpan1984[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7, 1984 };
oid ss7ProtocolSpan1988[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7, 1988 };
oid ss7ProtocolSpan1992[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7, 1992 };
oid ss7ProtocolSpan1996[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7, 1996 };
oid ss7ProtocolSpan2000[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7, 2000 };
oid ss7ProtocolSpan2004[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7, 2004 };
oid ss7ProtocolSpan2008[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 7, 2008 };

oid ss7ProtocolPnoc[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8 };
oid ss7ProtocolPnoc1980[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8, 1980 };
oid ss7ProtocolPnoc1984[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8, 1984 };
oid ss7ProtocolPnoc1988[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8, 1988 };
oid ss7ProtocolPnoc1992[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8, 1992 };
oid ss7ProtocolPnoc1996[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8, 1996 };
oid ss7ProtocolPnoc2000[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8, 2000 };
oid ss7ProtocolPnoc2004[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8, 2004 };
oid ss7ProtocolPnoc2008[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 751, 0, 1, 4, 1, 8, 2008 };

/*
 * variable7 ss7MIB_variables: tree for ss7MIB
 * This variable defines function callbacks and type return information for the ss7MIB mib section
 */
struct variable7 ss7MIB_variables[] = {
	/* magic number, variable type, ro/rw, callback fn, L, oidsuffix */
#define   SS7NETWORKPROTOCOLVARIANT  (4 % 256)
	{SS7NETWORKPROTOCOLVARIANT, ASN_OBJECT_ID, RWRITE, var_ss7NetworkTable, 5, {1, 2, 1, 1, 2}},
#define   SS7NETWORKPROTOCOLVERSION  (5 % 256)
	{SS7NETWORKPROTOCOLVERSION, ASN_UNSIGNED, RWRITE, var_ss7NetworkTable, 5, {1, 2, 1, 1, 3}},
#define   SS7NETWORKPROTOCOLOPTIONS  (6 % 256)
	{SS7NETWORKPROTOCOLOPTIONS, ASN_OCTET_STR, RWRITE, var_ss7NetworkTable, 5, {1, 2, 1, 1, 4}},
#define   SS7NETWORKROWSTATUS   (7 % 256)
	{SS7NETWORKROWSTATUS, ASN_INTEGER, RWRITE, var_ss7NetworkTable, 5, {1, 2, 1, 1, 5}},
};

/* (L = length of the oidsuffix) */
struct ss7MIB_data *ss7MIBStorage = NULL;

/* global storage of our data, saved in and configured by header_complex() */
struct header_complex_index *ss7NetworkTableStorage = NULL;

/*
 * init_ss7MIB(): Initialization routine.
 * This is called when the agent starts up.  At a minimum, registration of your variables should
 * take place here.
 */
void
init_ss7MIB(void)
{
	DEBUGMSGTL(("ss7MIB", "initializing...  "));
	/* register ourselves with the agent to handle our mib tree */
	REGISTER_MIB("ss7MIB", ss7MIB_variables, variable7, ss7MIB_variables_oid);
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_SHUTDOWN, term_ss7MIB, NULL);
	/* register our config handler(s) to deal with registrations */
	snmpd_register_config_handler("ss7MIB", parse_ss7MIB, NULL, "HELP STRING");
	snmpd_register_config_handler("ss7NetworkTable", parse_ss7NetworkTable, NULL, "HELP STRING");

	/* we need to be called back later to store our data */
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_STORE_DATA, store_ss7MIB, NULL);
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_STORE_DATA, store_ss7NetworkTable, NULL);

	/* place any other initialization junk you need here */
	DEBUGMSGTL(("ss7MIB", "done.\n"));
}

/*
 * deinit_ss7MIB(): Deinitialization routine.
 * This is called before the agent is unloaded.  At a minimum, deregistration of your variables
 * should take place here.
 */
void
deinit_ss7MIB(void)
{
	DEBUGMSGTL(("ss7MIB", "deinitializating...  "));
	unregister_mib(ss7MIB_variables_oid, sizeof(ss7MIB_variables_oid) / sizeof(oid));
	snmpd_unregister_config_handler("ss7MIB");
	snmpd_unregister_config_handler("ss7NetworkTable");

	/* place any other de-initialization junk you need here */
	DEBUGMSGTL(("ss7MIB", "done.\n"));
}

int
term_ss7MIB(int majorID, int minorID, void *serverarg, void *clientarg)
{
	deinit_ss7MIB();
	return 0;
}

/*
 * ss7MIB_add(): adds a structure node for scalars
 */
int
ss7MIB_add(struct ss7MIB_data *thedata)
{
	DEBUGMSGTL(("ss7MIB", "adding data...  "));
	ss7MIBStorage = thedata;
	DEBUGMSGTL(("ss7MIB", "done.\n"));
	return SNMPERR_SUCCESS;
}

/*
 * parse_ss7MIB(): parses .conf file entries needed to configure the mib.
 */
void
parse_ss7MIB(const char *token, char *line)
{
	size_t tmpsize;
	struct ss7MIB_data *StorageTmp = SNMP_MALLOC_STRUCT(ss7MIB_data);

	DEBUGMSGTL(("ss7MIB", "parsing config...  "));
	if (StorageTmp == NULL) {
		config_perror("malloc failure");
		return;
	}

	ss7MIB_add(StorageTmp);
	(void) tmpsize;
	DEBUGMSGTL(("ss7MIB", "done.\n"));
}

/*
 * store_ss7MIB(): stores .conf file entries needed to configure the mib.
 */
int
store_ss7MIB(int majorID, int minorID, void *serverarg, void *clientarg)
{
	char line[SNMP_MAXBUF];
	char *cptr;
	size_t tmpsize;
	struct ss7MIB_data *StorageTmp;

	DEBUGMSGTL(("ss7MIB", "storing data...  "));
	refresh_ss7MIB();
	if ((StorageTmp = ss7MIBStorage) == NULL) {
		DEBUGMSGTL(("ss7MIB", "error.\n"));
		return SNMPERR_GENERR;
	}
	(void) tmpsize;
	/* XXX: if (StorageTmp->ss7MIBStorageType == ST_NONVOLATILE) */
	{
		memset(line, 0, sizeof(line));
		strcat(line, "ss7MIB ");
		cptr = line + strlen(line);

		snmpd_store_config(line);
	}
	DEBUGMSGTL(("ss7MIB", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * refresh_ss7MIB: refresh ss7MIB scalars
 *
 * Normally, the values retrieved from the operating system are cached.  When the agent receives a
 * SIGPOLL from an open STREAMS configuration or administrative driver Stream, the STREAMS subsystem
 * indicates to the agent that the cache has been invalidated and that it should reread scalars and
 * tables from the STREAMS susbystem.  This function is used when the agent starts for the first
 * time, or after a SIGPOLL has been received (and a scalar has been requested).
 */
void
refresh_ss7MIB(void)
{
	if (ss7MIBStorage == NULL) {
		struct ss7MIB_data *StorageNew;

		if ((StorageNew = SNMP_MALLOC_STRUCT(ss7MIB_data)) == NULL)
			return;
		/* Update scalar defaults as required here... */
		ss7MIBStorage = StorageNew;
		ss7MIB_refresh = 1;
	}
	if (ss7MIB_refresh == 0)
		return;
	ss7MIB_refresh = 0;
	/* Update scalars as required here... */
}

/*
 * var_ss7MIB(): locate variables in ss7MIB
 *
 * This function is called every time the agent gets a request for a scalar variable that might be
 * found within your mib section registered above.  It is up to you to do the right thing and return
 * the correct value.  You should also correct the value of "var_len" if necessary.
 *
 * Please see the documentation for more information about writing module extensions, and check out
 * the examples in the examples and mibII directories.
 */
u_char *
var_ss7MIB(struct variable *vp, oid * name, size_t *length, int exact, size_t *var_len, WriteMethod ** write_method)
{
	struct ss7MIB_data *StorageTmp;

	if (header_generic(vp, name, length, exact, var_len, write_method) == MATCH_FAILED)
		return NULL;
	/* Refresh the MIB values if required. */
	refresh_ss7MIB();
	if ((StorageTmp = ss7MIBStorage) == NULL)
		return NULL;
	/* This is where we do the value assignments for the mib results. */
	switch (vp->magic) {

	default:
		ERROR_MSG("");
	}
	return NULL;
}

/*
 * ss7NetworkTable_add(): adds a structure node to our data set
 */
int
ss7NetworkTable_add(struct ss7NetworkTable_data *thedata)
{
	struct variable_list *vars = NULL;

	DEBUGMSGTL(("ss7NetworkTable", "adding data...  "));
	/* add the index variables to the varbind list, which is used by header_complex to index
	   the data */
	/* ss7NetworkId */
	snmp_varlist_add_variable(&vars, NULL, 0, ASN_INTEGER, (u_char *) &thedata->ss7NetworkId, sizeof(thedata->ss7NetworkId));
	header_complex_add_data(&ss7NetworkTableStorage, vars, thedata);
	DEBUGMSGTL(("ss7NetworkTable", "registered an entry\n"));
	DEBUGMSGTL(("ss7NetworkTable", "done.\n"));
	return SNMPERR_SUCCESS;
}

/*
 * ss7NetworkTable_del(): delete a structure
 */
int
ss7NetworkTable_del(struct ss7NetworkTable_data **thedata)
{
	struct ss7NetworkTable_data *StorageDel;

	DEBUGMSGTL(("ss7NetworkTable", "deleting data...  "));
	if ((StorageDel = *thedata) != NULL) {
		SNMP_FREE(StorageDel->ss7NetworkProtocolVariant);
		StorageDel->ss7NetworkProtocolVariantLen = 0;
		SNMP_FREE(StorageDel->ss7NetworkProtocolOptions);
		StorageDel->ss7NetworkProtocolOptionsLen = 0;
		SNMP_FREE(StorageDel);
		*thedata = StorageDel;
	}
	DEBUGMSGTL(("ss7NetworkTable", "done.\n"));
	return SNMPERR_SUCCESS;
}

/*
 * parse_ss7NetworkTable(): parse configuration file for ss7NetworkTable
 * parses .conf file entries needed to configure the mib.
 */
void
parse_ss7NetworkTable(const char *token, char *line)
{
	size_t tmpsize;
	struct ss7NetworkTable_data *StorageTmp = SNMP_MALLOC_STRUCT(ss7NetworkTable_data);

	DEBUGMSGTL(("ss7NetworkTable", "parsing config...  "));
	if (StorageTmp == NULL) {
		config_perror("malloc failure");
		return;
	}
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->ss7NetworkId, &tmpsize);
	line = read_config_read_data(ASN_OBJECT_ID, line, &StorageTmp->ss7NetworkProtocolVariant, &tmpsize);
	StorageTmp->ss7NetworkProtocolVariantLen = tmpsize;
	if (StorageTmp->ss7NetworkProtocolVariant == NULL) {
		config_perror("invalid specification for ss7NetworkProtocolVariant");
		return;
	}
	line = read_config_read_data(ASN_UNSIGNED, line, &StorageTmp->ss7NetworkProtocolVersion, &tmpsize);
	line = read_config_read_data(ASN_OCTET_STR, line, &StorageTmp->ss7NetworkProtocolOptions, &tmpsize);
	StorageTmp->ss7NetworkProtocolOptionsLen = tmpsize;
	if (StorageTmp->ss7NetworkProtocolOptions == NULL) {
		config_perror("invalid specification for ss7NetworkProtocolOptions");
		return;
	}
	line = read_config_read_data(ASN_INTEGER, line, &StorageTmp->ss7NetworkRowStatus, &tmpsize);
	ss7NetworkTable_add(StorageTmp);
	(void) tmpsize;
	DEBUGMSGTL(("ss7NetworkTable", "done.\n"));
}

/*
 * store_ss7NetworkTable(): store configuraiton file for ss7NetworkTable
 * stores .conf file entries needed to configure the mib.
 */
int
store_ss7NetworkTable(int majorID, int minorID, void *serverarg, void *clientarg)
{
	char line[SNMP_MAXBUF];
	char *cptr;
	size_t tmpsize;
	struct ss7NetworkTable_data *StorageTmp;
	struct header_complex_index *hcindex;

	DEBUGMSGTL(("ss7NetworkTable", "storing data...  "));
	refresh_ss7NetworkTable();
	(void) tmpsize;
	for (hcindex = ss7NetworkTableStorage; hcindex != NULL; hcindex = hcindex->next) {
		StorageTmp = (struct ss7NetworkTable_data *) hcindex->data;
		/* XXX: if (StorageTmp->ss7NetworkTableStorageType == ST_NONVOLATILE) */
		{
			memset(line, 0, sizeof(line));
			strcat(line, "ss7NetworkTable ");
			cptr = line + strlen(line);
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->ss7NetworkId, &tmpsize);
			tmpsize = StorageTmp->ss7NetworkProtocolVariantLen;
			cptr = read_config_store_data(ASN_OBJECT_ID, cptr, &StorageTmp->ss7NetworkProtocolVariant, &tmpsize);
			cptr = read_config_store_data(ASN_UNSIGNED, cptr, &StorageTmp->ss7NetworkProtocolVersion, &tmpsize);
			tmpsize = StorageTmp->ss7NetworkProtocolOptionsLen;
			cptr = read_config_store_data(ASN_OCTET_STR, cptr, &StorageTmp->ss7NetworkProtocolOptions, &tmpsize);
			cptr = read_config_store_data(ASN_INTEGER, cptr, &StorageTmp->ss7NetworkRowStatus, &tmpsize);
			snmpd_store_config(line);
		}
	}
	DEBUGMSGTL(("ss7NetworkTable", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * refresh_ss7NetworkTable(): refresh ss7NetworkTable
 *
 * Normally the values retrieved from the operating system are cached.  When the agent receives a
 * SIGPOLL from an open STREAMS configuration or administrative driver Stream, the STREAMS subsystem
 * indicates to the agent that the cache has been invalidated and that it should reread tables from
 * the STREAMS subsystem.  This function is used when the agent start for the first time, or after a
 * SIGPOLL has been received (and a row or column has been requested).
 */
void
refresh_ss7NetworkTable(void)
{
	if (ss7NetworkTable_refresh == 0)
		return;
	ss7NetworkTable_refresh = 0;
	/* Here, update the table as required... */
}

/**
 * refresh_ss7NetworkTable_row(): refresh ss7NetworkTable row
 *
 * Normally the values retrieved from the operating system are cached.  However, if a row contains
 * temporal values, such as statistics counters, gauges, timestamps, or other transient columns, it
 * may be necessary to refresh the row on some other basis, but normally only once per request.
 */
void
refresh_ss7NetworkTable_row(struct ss7NetworkTable_data *StorageTmp)
{
	if (StorageTmp->ss7NetworkTable_request == sa_request)
		return;
	StorageTmp->ss7NetworkTable_request = sa_request;
}

/*
 * var_ss7NetworkTable(): locate variables in ss7NetworkTable
 * Handle this table separately from the scalar value case.  The workings of this are basically the
 * same as for var_ss7MIB above.
 */
u_char *
var_ss7NetworkTable(struct variable *vp, oid * name, size_t *length, int exact, size_t *var_len, WriteMethod ** write_method)
{
	struct ss7NetworkTable_data *StorageTmp = NULL;

	DEBUGMSGTL(("ss7MIB", "var_ss7NetworkTable: Entering...  \n"));
	/* Make sure that the storage data does not need to be refreshed before checking the
	   header. */
	refresh_ss7NetworkTable();
	/* This assumes you have registered all your data properly with header_complex_add()
	   somewhere before this. */
	if ((StorageTmp = header_complex(ss7NetworkTableStorage, vp, name, length, exact, var_len, write_method)) == NULL)
		return NULL;
	refresh_ss7NetworkTable_row(StorageTmp);
	/* This is where we do the value assignments for the mib results. */
	switch (vp->magic) {
	case SS7NETWORKPROTOCOLVARIANT:
		*write_method = write_ss7NetworkProtocolVariant;
		*var_len = StorageTmp->ss7NetworkProtocolVariantLen;
		return (u_char *) StorageTmp->ss7NetworkProtocolVariant;
	case SS7NETWORKPROTOCOLVERSION:
		*write_method = write_ss7NetworkProtocolVersion;
		*var_len = sizeof(StorageTmp->ss7NetworkProtocolVersion);
		return (u_char *) &StorageTmp->ss7NetworkProtocolVersion;
	case SS7NETWORKPROTOCOLOPTIONS:
		*write_method = write_ss7NetworkProtocolOptions;
		*var_len = StorageTmp->ss7NetworkProtocolOptionsLen;
		return (u_char *) StorageTmp->ss7NetworkProtocolOptions;
	case SS7NETWORKROWSTATUS:
		*write_method = write_ss7NetworkRowStatus;
		*var_len = sizeof(StorageTmp->ss7NetworkRowStatus);
		return (u_char *) &StorageTmp->ss7NetworkRowStatus;
	default:
		ERROR_MSG("");
	}
	return NULL;
}

int
write_ss7NetworkProtocolVariant(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	static oid *old_value;
	struct ss7NetworkTable_data *StorageTmp = NULL;
	size_t newlen = name_len - (sizeof(ss7MIB_variables_oid) / sizeof(oid) + 6 - 1);
	static size_t old_length = 0;
	static oid *objid = NULL;

	DEBUGMSGTL(("ss7MIB", "write_ss7NetworkProtocolVariant entering action=%d...  \n", action));
	if ((StorageTmp = header_complex(ss7NetworkTableStorage, NULL, &name[sizeof(ss7MIB_variables_oid) / sizeof(oid) + 6 - 1], &newlen, 1, NULL, NULL)) == NULL)
		return SNMP_ERR_NOSUCHNAME;	/* remove if you support creation here */
	switch (action) {
	case RESERVE1:
		if (var_val_type != ASN_OBJECT_ID) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkProtocolVariant not ASN_OBJECT_ID\n");
			return SNMP_ERR_WRONGTYPE;
		}
		/* Note: ranges 14..15 */
		if (MIN_OID_LEN * sizeof(oid) > var_val_len || var_val_len > MAX_OID_LEN * sizeof(oid) || ((14 * sizeof(oid) > var_val_len || var_val_len > 15 * sizeof(oid)))) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkProtocolVariant: bad length\n");
			return SNMP_ERR_WRONGLENGTH;
		}
		/* Note: default value { ss7ProtocoAnsi2000 } */
		break;
	case RESERVE2:		/* memory reseveration, final preparation... */
		if ((objid = snmp_duplicate_objid((void *) var_val, var_val_len / sizeof(oid))) == NULL)
			return SNMP_ERR_RESOURCEUNAVAILABLE;
		break;
	case FREE:		/* Release any resources that have been allocated */
		SNMP_FREE(objid);
		break;
	case ACTION:		/* The variable has been stored in objid for you to use, and you
				   have just been asked to do something with it.  Note that
				   anything done here must be reversable in the UNDO case */
		old_value = StorageTmp->ss7NetworkProtocolVariant;
		old_length = StorageTmp->ss7NetworkProtocolVariantLen;
		StorageTmp->ss7NetworkProtocolVariant = objid;
		StorageTmp->ss7NetworkProtocolVariantLen = var_val_len / sizeof(oid);
		break;
	case UNDO:		/* Back out any changes made in the ACTION case */
		StorageTmp->ss7NetworkProtocolVariant = old_value;
		StorageTmp->ss7NetworkProtocolVariantLen = old_length;
		break;
	case COMMIT:		/* Things are working well, so it's now safe to make the change
				   permanently.  Make sure that anything done here can't fail! */
		SNMP_FREE(old_value);
		old_length = 0;
		objid = NULL;
		break;
	}
	return SNMP_ERR_NOERROR;
}

int
write_ss7NetworkProtocolVersion(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	static uint32_t old_value;
	struct ss7NetworkTable_data *StorageTmp = NULL;
	size_t newlen = name_len - (sizeof(ss7MIB_variables_oid) / sizeof(oid) + 6 - 1);
	ulong set_value = *((ulong *) var_val);

	DEBUGMSGTL(("ss7MIB", "write_ss7NetworkProtocolVersion entering action=%d...  \n", action));
	if ((StorageTmp = header_complex(ss7NetworkTableStorage, NULL, &name[sizeof(ss7MIB_variables_oid) / sizeof(oid) + 6 - 1], &newlen, 1, NULL, NULL)) == NULL)
		return SNMP_ERR_NOSUCHNAME;	/* remove if you support creation here */
	switch (action) {
	case RESERVE1:
		if (var_val_type != ASN_UNSIGNED) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkProtocolVersion not ASN_UNSIGNED\n");
			return SNMP_ERR_WRONGTYPE;
		}
		if (var_val_len > sizeof(uint32_t)) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkProtocolVersion: bad length\n");
			return SNMP_ERR_WRONGLENGTH;
		}
		/* Note: default value 2000 */
		/* Note: ranges 1984..2008 */
		if ((1984 > set_value || set_value > 2008)) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkProtocolVersion: bad value\n");
			return SNMP_ERR_WRONGVALUE;
		}
		break;
	case RESERVE2:		/* memory reseveration, final preparation... */
		break;
	case FREE:		/* Release any resources that have been allocated */
		break;
	case ACTION:		/* The variable has been stored in set_value for you to use, and
				   you have just been asked to do something with it.  Note that
				   anything done here must be reversable in the UNDO case */
		old_value = StorageTmp->ss7NetworkProtocolVersion;
		StorageTmp->ss7NetworkProtocolVersion = set_value;
		break;
	case UNDO:		/* Back out any changes made in the ACTION case */
		StorageTmp->ss7NetworkProtocolVersion = old_value;
		break;
	case COMMIT:		/* Things are working well, so it's now safe to make the change
				   permanently.  Make sure that anything done here can't fail! */
		break;
	}
	return SNMP_ERR_NOERROR;
}

int
write_ss7NetworkProtocolOptions(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	static uint8_t *old_value;
	struct ss7NetworkTable_data *StorageTmp = NULL;
	size_t newlen = name_len - (sizeof(ss7MIB_variables_oid) / sizeof(oid) + 6 - 1);
	static size_t old_length = 0;
	static uint8_t *string = NULL;

	DEBUGMSGTL(("ss7MIB", "write_ss7NetworkProtocolOptions entering action=%d...  \n", action));
	if ((StorageTmp = header_complex(ss7NetworkTableStorage, NULL, &name[sizeof(ss7MIB_variables_oid) / sizeof(oid) + 6 - 1], &newlen, 1, NULL, NULL)) == NULL)
		return SNMP_ERR_NOSUCHNAME;	/* remove if you support creation here */
	switch (action) {
	case RESERVE1:
		if (var_val_type != ASN_OCTET_STR) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkProtocolOptions not ASN_OCTET_STR\n");
			return SNMP_ERR_WRONGTYPE;
		}
		if (var_val_len > SPRINT_MAX_LEN) {
			snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkProtocolOptions: bad length\n");
			return SNMP_ERR_WRONGLENGTH;
		}
		break;
	case RESERVE2:		/* memory reseveration, final preparation... */
		if ((string = malloc(var_val_len)) == NULL)
			return SNMP_ERR_RESOURCEUNAVAILABLE;
		memcpy((void *) string, (void *) var_val, var_val_len);
		break;
	case FREE:		/* Release any resources that have been allocated */
		SNMP_FREE(string);
		break;
	case ACTION:		/* The variable has been stored in string for you to use, and you
				   have just been asked to do something with it.  Note that
				   anything done here must be reversable in the UNDO case */
		old_value = StorageTmp->ss7NetworkProtocolOptions;
		old_length = StorageTmp->ss7NetworkProtocolOptionsLen;
		StorageTmp->ss7NetworkProtocolOptions = string;
		StorageTmp->ss7NetworkProtocolOptionsLen = var_val_len;
		break;
	case UNDO:		/* Back out any changes made in the ACTION case */
		StorageTmp->ss7NetworkProtocolOptions = old_value;
		StorageTmp->ss7NetworkProtocolOptionsLen = old_length;
		break;
	case COMMIT:		/* Things are working well, so it's now safe to make the change
				   permanently.  Make sure that anything done here can't fail! */
		SNMP_FREE(old_value);
		old_length = 0;
		string = NULL;
		break;
	}
	return SNMP_ERR_NOERROR;
}

int
write_ss7NetworkRowStatus(int action, u_char *var_val, u_char var_val_type, size_t var_val_len, u_char *statP, oid * name, size_t name_len)
{
	struct ss7NetworkTable_data *StorageTmp = NULL;
	static struct ss7NetworkTable_data *StorageNew, *StorageDel;
	size_t newlen = name_len - (sizeof(ss7NetworkTable_variables_oid) / sizeof(oid) + 3 - 1);
	static int old_value;
	int set_value;
	static struct variable_list *vars, *vp;
	struct header_complex_index *hciptr;

	StorageTmp = header_complex(ss7NetworkTableStorage, NULL, &name[sizeof(ss7NetworkTable_variables_oid) / sizeof(oid) + 3 - 1], &newlen, 1, NULL, NULL);
	if (var_val_type != ASN_INTEGER || var_val == NULL) {
		snmp_log(MY_FACILITY(LOG_NOTICE), "write to ss7NetworkRowStatus not ASN_INTEGER\n");
		return SNMP_ERR_WRONGTYPE;
	}
	set_value = *((int *) var_val);
	/* check legal range, and notReady is reserved for us, not a user */
	if (set_value < 1 || set_value > 6 || set_value == RS_NOTREADY)
		return SNMP_ERR_INCONSISTENTVALUE;
	switch (action) {
	case RESERVE1:
		/* stage one: test validity */
		switch (set_value) {
		case RS_CREATEANDGO:
		case RS_CREATEANDWAIT:
			if (StorageTmp != NULL)
				/* cannot create existing row */
				return SNMP_ERR_INCONSISTENTVALUE;
			break;
		case RS_ACTIVE:
		case RS_NOTINSERVICE:
			if (StorageTmp == NULL)
				/* cannot change state of non-existent row */
				return SNMP_ERR_INCONSISTENTVALUE;
			if (StorageTmp->ss7NetworkRowStatus == RS_NOTREADY)
				/* cannot change state of row that is not ready */
				return SNMP_ERR_INCONSISTENTVALUE;
			/* XXX: interaction with row storage type needed */
			if (set_value == RS_NOTINSERVICE && StorageTmp->ss7NetworkTable_refs > 0)
				/* row is busy and cannot be moved to the RS_NOTINSERVICE state */
				return SNMP_ERR_INCONSISTENTVALUE;
			break;
		case RS_DESTROY:
			/* destroying existent or non-existent row is ok */
			if (StorageTmp == NULL)
				break;
			/* XXX: interaction with row storage type needed */
			if (StorageTmp->ss7NetworkTable_refs > 0)
				/* row is busy and cannot be deleted */
				return SNMP_ERR_INCONSISTENTVALUE;
			break;
		case RS_NOTREADY:
			/* management station cannot set this, only agent can */
		default:
			return SNMP_ERR_INCONSISTENTVALUE;
		}
		break;
	case RESERVE2:
		/* memory reseveration, final preparation... */
		switch (set_value) {
		case RS_CREATEANDGO:
		case RS_CREATEANDWAIT:
			/* creation */
			vars = NULL;
			/* ss7NetworkId */
			snmp_varlist_add_variable(&vars, NULL, 0, ASN_INTEGER, NULL, 0);
			if (header_complex_parse_oid(&(name[sizeof(ss7NetworkTable_variables_oid) / sizeof(oid) + 2]), newlen, vars) != SNMPERR_SUCCESS) {
				/* XXX: free, zero vars */
				return SNMP_ERR_INCONSISTENTNAME;
			}
			vp = vars;
			if ((StorageNew = SNMP_MALLOC_STRUCT(ss7NetworkTable_data)) == NULL) {
				/* XXX: free, zero vars */
				return SNMP_ERR_RESOURCEUNAVAILABLE;
			}
			StorageNew->ss7NetworkId = *vp->val.integer;
			vp = vp->next_variable;
			/* XXX: fill in default row values here into StorageNew */
			/* StorageNew->ss7NetworkProtocolVariant = { ss7ProtocoAnsi2000 }; */
			StorageNew->ss7NetworkProtocolVersion = 2000;
			StorageNew->ss7NetworkRowStatus = RS_NOTREADY;
			/* XXX: free, zero vars, no longer needed? */
			break;
		}
		break;
	case FREE:
		/* Release any resources that have been allocated */
		switch (set_value) {
		case RS_CREATEANDGO:
		case RS_CREATEANDWAIT:
			/* creation */
			ss7NetworkTable_del(&StorageNew);
			/* XXX: free, zero vars */
			break;
		}
		break;
	case ACTION:
		/* The variable has been stored in set_value for you to use, and you have just been 
		   asked to do something with it.  Note that anything done here must be reversable
		   in the UNDO case */
		switch (set_value) {
		case RS_CREATEANDGO:
		case RS_CREATEANDWAIT:
			/* row creation, so add it */
			ss7NetworkTable_add(StorageNew);
			break;
		case RS_ACTIVE:
		case RS_NOTINSERVICE:
			/* set the flag? */
			old_value = StorageTmp->ss7NetworkRowStatus;
			StorageTmp->ss7NetworkRowStatus = set_value;
			break;
		case RS_DESTROY:
			/* destroy */
			if (StorageTmp != NULL) {
				/* exists, extract it for now */
				hciptr = header_complex_find_entry(ss7NetworkTableStorage, StorageTmp);
				StorageDel = header_complex_extract_entry(&ss7NetworkTableStorage, hciptr);
			} else {
				StorageDel = NULL;
			}
			break;
		}
		break;
	case UNDO:
		/* Back out any changes made in the ACTION case */
		switch (set_value) {
		case RS_CREATEANDGO:
		case RS_CREATEANDWAIT:
			/* row creation, so remove it again */
			hciptr = header_complex_find_entry(ss7NetworkTableStorage, StorageNew);
			header_complex_extract_entry(&ss7NetworkTableStorage, hciptr);
			break;
		case RS_ACTIVE:
		case RS_NOTINSERVICE:
			/* restore state */
			StorageTmp->ss7NetworkRowStatus = old_value;
			break;
		case RS_DESTROY:
			/* row deletion, so add it again */
			ss7NetworkTable_add(StorageDel);
			break;
		}
		break;
	case COMMIT:
		/* Things are working well, so it's now safe to make the change permanently.  Make
		   sure that anything done here can't fail! */
		switch (set_value) {
		case RS_CREATEANDGO:
			/* row creation, set final state */
			/* XXX: check if row is ready, otherwise leave at RS_NOTREADY */
			StorageTmp->ss7NetworkRowStatus = RS_ACTIVE;
			break;
		case RS_CREATEANDWAIT:
			/* row creation, set final state */
			/* XXX: check if row is ready, otherwise leave at RS_NOTREADY */
			StorageTmp->ss7NetworkRowStatus = RS_NOTINSERVICE;
			break;
		case RS_ACTIVE:
		case RS_NOTINSERVICE:
			/* state change already performed */
			break;
		case RS_DESTROY:
			/* row deletion, free it its dead */
			ss7NetworkTable_del(&StorageDel);
			/* ss7NetworkTable_del() can handle NULL pointers. */
			break;
		}
		break;
	}
	return SNMP_ERR_NOERROR;
}

#if !defined MODULE
static void
sa_version(int argc, char *argv[])
{
	if (!sa_output && !sa_debug)
		return;
	fprintf(stdout, "\
%2$s\n\
Copyright (c) 2001-2008  OpenSS7 Corporation.  All Rights Reserved.\n\
Distributed under Affero GPL Version 3, included here by reference.\n\
See `%1$s --copying' for copying permissions.\n\
", argv[0], ident);
}
static void
sa_usage(int argc, char *argv[])
{
	if (!sa_output && !sa_debug)
		return;
	fprintf(stderr, "\
Usage:\n\
    %1$s [general-options] [options] [arguments]\n\
    %1$s {-H|--help-directives}\n\
    %1$s {-h|--help}\n\
    %1$s {-V|--version}\n\
    %1$s {-C|--copying}\n\
", argv[0]);
}
static void
sa_help(int argc, char *argv[])
{
	if (!sa_output && !sa_debug)
		return;
	fprintf(stdout, "\
Usage:\n\
    %1$s [general-options] [options] [arguments]\n\
    %1$s {-h|--help}\n\
    %1$s {-V|--version}\n\
    %1$s {-C|--copying}\n\
Arguments:\n\
    None.\n\
Options:\n\
    -a, --log-addresses\n\
        log addresses of connecting management stations.\n\
    -A, --append\n\
        append to logfiles without truncating.\n\
    -c, --config-file CONFIGFILE\n\
        use configuration file CONFIGFILE.\n\
    -C, --config-only\n\
        only load configuration given by -c option.\n\
    -d, --dump\n\
        dump sent and received PDUs.\n\
    -D, --debug [LEVEL]\n\
        set debugging verbosity to LEVEL.\n\
    -D, --debug-tokens [TOKEN[,TOKEN]*]\n\
        debug specified TOKEN's.\n\
    -f, --dont-fork\n\
        run in the foreground.\n\
    -g, --gid, --groupid GID\n\
        become group GID after listening.\n\
    -h, --help, -?, --?\n\
        print usage information and exit.\n\
    -H, --help-directives\n\
        print config directives and exit.\n\
    -I, --initialize [-]MODULE[,MODULE]*\n\
        initialize (or not, '-') these MODULE's.\n\
    -k, --keep-open\n\
        keep system files open between requests.\n\
    -l, --log-file [LOGFILE]\n\
        log to log file name LOGFILE.  [default: /var/log/ss7mib.log]\n\
    -L, --log-stderr\n\
        log to controlling terminal standard error.\n\
    -m, --mibs [+]MIB[,MIB]*\n\
        load these (additional '+') MIBs.\n\
    -M, --master\n\
        run as SNMP master instead of AgentX sub-agent.\n\
    -M, --mibdirs [+]MIBDIR[:MIBDIR]*\n\
        search these (additional, '+') colon separated directories for MIBs.\n\
    -n, --nodaemon\n\
        run in the foreground.\n\
    -n, --name NAME\n\
        use NAME for configuration file base.  [default: ss7mib]\n\
    -p, --port PORTNUM\n\
        listen on port number PORTNUM.  [default: 161]\n\
    -p, --pidfile PIDFILE\n\
        write daemon pid to PIDFILE.  [default: /var/run/ss7mib.pid]\n\
    -P, --pidfile PIDFILE\n\
        write daemon pid to PIDFILE.  [default: /var/run/ss7mib.pid]\n\
    -q, --quiet\n\
        suppress normal output.\n\
    -q, --quick\n\
        abbreviate output for machine readability.\n\
    -r, --noroot\n\
        do not require root privilege.\n\
    -s, --log-syslog\n\
        log to system logs.\n\
    -S, --sysctl-file FILENAME\n\
        write sysctl config file FILENAME.  [default: /etc/streams.conf]\n\
    -t, --agent-alarms\n\
        agent blocks {SIGALARM}.\n\
    -T, --transport [TRANSPORT]\n\
        default transport TRANSPORT.  [default: udp]\n\
    -u, --uid, --userid UID\n\
        become user UID after listening.\n\
    -U, --dont-remove-pidfile\n\
        do not remove PIDFILE when shutting down.\n\
    -v, --version\n\
        print version information and exit.\n\
    -V, --verbose [LEVEL]\n\
        be verbose to LEVEL.  [default: 1]\n\
    -x, --agentx-socket [SOCKET]\n\
        master AgentX on SOCKET.  [default: /var/agentx/master]\n\
    -X, --agentx\n\
        run as AgentX sub-agent instead of master (the default).\n\
    -y, --copying\n\
        print copying information and exit.\n\
", argv[0]);
}
static void
sa_copying(int argc, char *argv[])
{
	if (!sa_output && !sa_debug)
		return;
	fprintf(stdout, "\
--------------------------------------------------------------------------------\n\
%1$s\n\
--------------------------------------------------------------------------------\n\
Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com>\n\
Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>\n\
\n\
All Rights Reserved.\n\
--------------------------------------------------------------------------------\n\
This program is free software; you can  redistribute  it and/or modify  it under\n\
the terms of the GNU Affero General Public License as published by the Free\n\
Software Foundation; Version 3 of the License.\n\
\n\
This program is distributed in the hope that it will  be useful, but WITHOUT ANY\n\
WARRANTY; without even  the implied warranty of MERCHANTABILITY or FITNESS FOR A\n\
PARTICULAR PURPOSE.  See the GNU Affero General Public License for more details.\n\
\n\
You should have received a copy of the GNU  Affero  General Public License along\n\
with this program.   If not, see <http://www.gnu.org/licenses/>, or write to the\n\
Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.\n\
--------------------------------------------------------------------------------\n\
U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on behalf\n\
of the U.S. Government (\"Government\"), the following provisions apply to you. If\n\
the Software is supplied by the  Department of Defense (\"DoD\"), it is classified\n\
as \"Commercial  Computer  Software\"  under  paragraph  252.227-7014  of the  DoD\n\
Supplement  to the  Federal Acquisition Regulations  (\"DFARS\") (or any successor\n\
regulations) and the  Government  is acquiring  only the  license rights granted\n\
herein (the license rights customarily provided to non-Government users). If the\n\
Software is supplied to any unit or agency of the Government  other than DoD, it\n\
is  classified as  \"Restricted Computer Software\" and the Government's rights in\n\
the Software  are defined  in  paragraph 52.227-19  of the  Federal  Acquisition\n\
Regulations (\"FAR\")  (or any successor regulations) or, in the cases of NASA, in\n\
paragraph  18.52.227-86 of  the  NASA  Supplement  to the FAR (or any  successor\n\
regulations).\n\
--------------------------------------------------------------------------------\n\
Commercial  licensing  and  support of this  software is  available from OpenSS7\n\
Corporation at a fee.  See http://www.openss7.com/\n\
--------------------------------------------------------------------------------\n\
", ident);
}

void
sa_help_directives(int argc, char *argv[])
{
	ds_set_boolean(DS_APPLICATION_ID, DS_AGENT_NO_ROOT_ACCESS, 1);
	init_agent("ss7MIB");
	// init_mib_modules();
	init_mib();
	init_snmp("ss7MIB");
	snmp_log(MY_FACILITY(LOG_INFO), "Configuration directives understood:\n");
	/* Unfortunately, read_config_print_usage() uses snmp_log(), meaning that it can only be
	   writen to standard error and not standard output. */
	read_config_print_usage("    ");
}
static int
sa_sig_register(int signum, RETSIGTYPE(*handler) (int))
{
	sigset_t mask;
	struct sigaction act;

	act.sa_handler = handler ? handler : SIG_DFL;
	act.sa_flags = handler ? SA_RESTART : 0;
	sigemptyset(&act.sa_mask);
	if (sigaction(signum, &act, NULL))
		return (-1);
	sigemptyset(&mask);
	sigaddset(&mask, signum);
	sigprocmask(handler ? SIG_UNBLOCK : SIG_BLOCK, &mask, NULL);
	return (0);
}
static int sa_alm_signal = 0;
static int sa_pol_signal = 0;
static int sa_hup_signal = 0;
static int sa_int_signal = 0;
static int sa_trm_signal = 0;
static int sa_alm_handle = 0;
void
sa_alm_callback(uint req, void *arg)
{
	if (req == sa_alm_handle)
		sa_alm_handle = 0;
	sa_alm_signal = 1;
	return;
}

static RETSIGTYPE
sa_alm_handler(int signum)
{
	sa_alm_signal = 1;
	return (RETSIGTYPE) (0);
}
static void
sa_snmp_alm_handler(uint reg, void *clientarg)
{
	sa_alm_signal = 1;
	return;
}
static int
sa_alm_catch(void)
{
	if (sa_alarms)
		return sa_sig_register(SIGALRM, &sa_alm_handler);
	return (-1);
}
static int
sa_alm_block(void)
{
	if (sa_alarms)
		return sa_sig_register(SIGALRM, NULL);
	if (sa_alm_handle) {
		uint handle = sa_alm_handle;

		sa_alm_handle = 0;
		snmp_alarm_unregister(handle);
	}
	return (0);
}
static int
sa_alm_action(void)
{
	sa_alm_signal = 0;
	return (0);
}

static RETSIGTYPE
sa_pol_handler(int signum)
{
	sa_pol_signal = 1;
	return (RETSIGTYPE) (0);
}
static int
sa_pol_catch(void)
{
	return sa_sig_register(SIGPOLL, &sa_pol_handler);
}
static int
sa_pol_block(void)
{
	return sa_sig_register(SIGPOLL, NULL);
}

/*
 * Both the sc(4) module and sad(4) driver issue an M_PCSIG message with
 * SIGPOLL to the stream head whenever the STREAMS configuration or autopush
 * configuration changes, indicating to the agent which has the sc(4) or
 * sad(4) Stream open that it is necessary to reread information from the
 * kernel.  This fact is merely recorded, as this information is not read each
 * time that a configuration change occurs, but only after a request from some
 * portion of that information occurs. This condition is also set when the
 * sc(4) and sad(4) Streams are first opened. The SIGPOLL will also deliver in
 * siginfo the file descriptor issuing the signal, so we could distiguish
 * between sc(4) and sad(4) signals, but since one can be pushed over the
 * other, there is little point in distinguishing.
 *
 * sc(4) or sad(4) also should be modified to provide the general streams
 * statistics supported here; even though they are available through the /proc
 * filesystem on Linux Fast-STREAMS.
 */
static int
sa_pol_action(void)
{
	sa_pol_signal = 0;
	snmp_log(MY_FACILITY(LOG_INFO), "%s: Caught SIGPOLL, will re-read data structures", sa_program);
	sa_changed = 1;
	return (0);
}

static RETSIGTYPE
sa_hup_handler(int signum)
{
	sa_hup_signal = 1;
	return (RETSIGTYPE) (0);
}
static int
sa_hup_catch(void)
{
	if (sa_agentx)
		return sa_sig_register(SIGHUP, &sa_hup_handler);
	return (-1);
}
static int
sa_hup_block(void)
{
	return sa_sig_register(SIGHUP, NULL);
}
static int
sa_hup_action(void)
{
	/* There are several times that we might be sent a SIGHUP.  We might be sent a SIGHUP by
	   logrotate asking us to close and reopen our log files. */
	sa_hup_signal = 0;
	snmp_log(MY_FACILITY(LOG_WARNING), "Caught SIGHUP, reopening files.");
	if (sa_output > 1)
		snmp_log(MY_FACILITY(LOG_NOTICE), "Reopening output file %s", sa_logfile);
	if (sa_logfillog != 0) {
		fflush(stdlog);
		fclose(stdlog);
		snmp_disable_filelog();
		if ((stdlog = freopen(sa_logfile, sa_appendlog ? "a" : "w", stdlog)) == NULL) {
			/* I hope we have another log sink. */
			snmp_log(MY_FACILITY(LOG_ERR), "%s", strerror(errno));
			snmp_log(MY_FACILITY(LOG_ERR), "Could not reopen log file %s", sa_logfile);
		}
		snmp_enable_filelog(sa_logfile, sa_appendlog);
	}
	return (0);
}

static RETSIGTYPE
sa_int_handler(int signum)
{
	sa_int_signal = 1;
	return (RETSIGTYPE) (0);
}
static int
sa_int_catch(void)
{
	return sa_sig_register(SIGINT, &sa_int_handler);
}
static int
sa_int_block(void)
{
	return sa_sig_register(SIGINT, NULL);
}
static void sa_exit(int retval);
static int
sa_int_action(void)
{
	sa_int_signal = 0;
	snmp_log(MY_FACILITY(LOG_WARNING), "%s: Caught SIGINT, shutting down", sa_program);
	sa_exit(0);
	return (0);		/* should be no return */
}

static RETSIGTYPE
sa_trm_handler(int signum)
{
	sa_trm_signal = 1;
	return (RETSIGTYPE) (0);
}
static int
sa_trm_catch(void)
{
	return sa_sig_register(SIGTERM, &sa_trm_handler);
}
static int
sa_trm_block(void)
{
	return sa_sig_register(SIGTERM, NULL);
}
static void sa_exit(int retval);
static int
sa_trm_action(void)
{
	sa_trm_signal = 0;
	snmp_log(MY_FACILITY(LOG_WARNING), "%s: Caught SIGTERM, shutting down", sa_program);
	sa_exit(0);
	return (0);		/* should be no return */
}
static void
sa_sig_catch(void)
{
	sa_alm_catch();
	sa_pol_catch();
	sa_hup_catch();
	sa_int_catch();
	sa_trm_catch();
}
static void
sa_sig_block(void)
{
	sa_alm_block();
	sa_pol_block();
	sa_hup_block();
	sa_int_block();
	sa_trm_block();
}

int
sa_start_timer(long duration)
{
	if (sa_alarms) {
		struct itimerval setting = {
			{0, 0},
			{duration / 1000, (duration % 1000) * 1000}
		};
		if (sa_alm_catch())
			return (-1);
		if (setitimer(ITIMER_REAL, &setting, NULL))
			return (-1);
		sa_alm_signal = 0;
		return (0);
	} else {
#if defined NETSNMP_DS_APPLICATION_ID
		struct timeval setting = {
			duration / 1000, (duration % 1000) * 1000
		};
		sa_alm_handle = snmp_alarm_register_hr(setting, 0, sa_snmp_alm_handler, NULL);
#else
		sa_alm_handle = snmp_alarm_register((duration + 999) / 1000, 0, sa_snmp_alm_handler, NULL);
#endif
		return (sa_alm_handle ? 0 : -1);
	}
}
static void
sa_exit(int retval)
{
	if (retval)
		snmp_log(MY_FACILITY(LOG_ERR), "%s: Exiting %d", sa_program, retval);
	else
		snmp_log(MY_FACILITY(LOG_NOTICE), "%s: Exiting %d", sa_program, retval);
	fflush(stdout);
	fflush(stderr);
	sa_sig_block();
	closelog();
	exit(retval);
}
static void
sa_init_logging(int argc, char *argv[])
{
	static char progname[256];

	/* The purpose of this function is to bring logging up before forking (and while still in
	   the foreground) so that we can use the snmp_log() function before and during forking if
	   necessary.  Note that the default configuration for snmp_log() is to send all logs to
	   standard error. */
	strncpy(progname, basename(argv[0]), sizeof(progname));
	snmp_disable_log();
	if (sa_logfillog) {
		snmp_enable_filelog(sa_logfile, sa_appendlog);
	}
	if (sa_logstderr | sa_logstdout) {
#if defined LOG_PERROR
		/* Note that when we have Linux LOG_PERROR, and logs go both to syslog and stderr,
		   it is better to use the LOG_PERROR than to use snmp_log()'s print to stderr, as
		   the former is better formated. */
		if (!sa_logsyslog)
			snmp_enable_stderrlog();
#else				/* defined LOG_PERROR */
		snmp_enable_stderrlog();
#endif				/* defined LOG_PERROR */
	}
	if (sa_logsyslog) {
#if !defined HAVE_SNMP_ENABLE_SYSLOG_IDENT
		snmp_enable_syslog();
#else				/* !defined HAVE_SNMP_ENABLE_SYSLOG_IDENT */
		snmp_enable_syslog_ident("ss7MIB", LOG_DAEMON);
#endif				/* !defined HAVE_SNMP_ENABLE_SYSLOG_IDENT */
		/* Note that the way that snmp sets up the logger is not really the way we want it,
		   so close the log and reopen it the way we want. */
		closelog();
#if defined LOG_PERROR
		openlog("ss7MIB", LOG_PID | LOG_CONS | LOG_NDELAY | (sa_logstderr ? LOG_PERROR : 0), MY_FACILITY(0));
#else				/* defined LOG_PERROR */
		openlog("ss7MIB", LOG_PID | LOG_CONS | LOG_NDELAY, MY_FACILITY(0));
#endif				/* defined LOG_PERROR */
	}
	if (sa_logcallog) {
		snmp_enable_calllog();
	}
}
static void
sa_enter(int argc, char *argv[])
{
	if (sa_nomead) {
		pid_t pid;

		if ((pid = fork()) < 0) {
			perror(argv[0]);
			exit(2);
		} else if (pid != 0) {
			/* parent exits */
			exit(0);
		}
		setsid();	/* become a session leader */
		/* fork once more for SVR4 */
		if ((pid = fork()) < 0) {
			perror(argv[0]);
			exit(2);
		} else if (pid != 0) {
			/* parent responsible for writing pid file */
			if (sa_nomead || sa_pidfile[0] != '\0') {
				FILE *pidf;

				/* initialize default filename */
				if (sa_pidfile[0] == '\0')
					snprintf(sa_pidfile, sizeof(sa_pidfile), "/var/run/%s.pid", sa_program);
				if (sa_output > 1) {
					snmp_log(MY_FACILITY(LOG_NOTICE), "%s: Writing daemon pid to file %s", sa_program, sa_pidfile);
				}
				if ((pidf = fopen(sa_pidfile, "w+"))) {
					fprintf(pidf, "%d", (int) pid);
					fflush(pidf);
					fclose(pidf);
				} else {
					snmp_log(MY_FACILITY(LOG_ERR), "%s: %m", sa_program);
					snmp_log(MY_FACILITY(LOG_ERR), "%s: Could not write pid to file %s", sa_program, sa_pidfile);
					sa_exit(2);
					/* no return */
				}
			}
			/* parent exits */
			exit(0);
		}
		/* child continues */
		/* release current directory */
		if (chdir("/") < 0) {
			perror(argv[0]);
			exit(2);
		}
		umask(0);	/* clear file creation mask */
		/* rearrange file streams */
		fclose(stdin);
	}
	/* continue as foreground or background */
	sa_init_logging(argc, argv);
	sa_sig_catch();
	snmp_log(MY_FACILITY(LOG_NOTICE), "%s: Startup complete.", sa_program);
}
static void
sa_mloop(int argc, char *argv[])
{
	if (sa_agentx) {
		if (sa_debug)
			snmp_log(MY_FACILITY(LOG_DEBUG), "%s: running as AgentX client\n", argv[0]);
		/* run as an AgentX client */
		ds_set_boolean(DS_APPLICATION_ID, DS_AGENT_ROLE, 1);
	} else {
		if (sa_debug)
			snmp_log(MY_FACILITY(LOG_DEBUG), "%s: running as SNMP master agent\n", argv[0]);
		/* run as SNMP master */
		ds_set_boolean(DS_APPLICATION_ID, DS_AGENT_ROLE, 0);
	}
	if (sa_alarms) {
		if (sa_debug)
			snmp_log(MY_FACILITY(LOG_DEBUG), "%s: using application alarms\n", argv[0]);
		/* use application alarms */
		ds_set_boolean(DS_LIBRARY_ID, DS_LIB_ALARM_DONT_USE_SIG, 1);
	}
	/* initialize agent */
	init_agent("ss7MIB");
	/* initialize MIB */
	init_ss7MIB();
	init_x400pMIB();
	init_mtpMIB();
	init_mtpOmMIB();
	init_sccpMIB();
	init_sccpOmMIB();
	init_tcapMIB();
	init_tcapOmMIB();
	/* initialize SNMP */
	init_snmp("ss7MIB");
	if (!sa_agentx) {
		if (sa_debug)
			snmp_log(MY_FACILITY(LOG_DEBUG), "%s: running as SNMP master\n", argv[0]);
#if !defined NETSNMP_DS_APPLICATION_ID
		init_master_agent(710, NULL, NULL);
#else
		init_master_agent();
#endif
	}
	for (;;) {
		int retval;

		/* to use select or poll you need to use the snmp_select_info() to obtain the fd of
		   the agentx socket and add it to the fdset. */
		/* note that SIGALRM is used by snmp: use the snmp_alarm() api instead */
#if 0
		if (snmp_select() == 0) {
			if (sa_alarms == 0)
				run_alarms();
		}
#endif
		retval = agent_check_and_process(1);	/* 0 == don't block */
		if (retval == 0) {
			/* alarm occurred, alarm conditions checked */
		} else if (retval == -1) {
			/* error (or signal) ocurred */
			if (sa_alm_signal) {
				sa_alm_action();
			}
			if (sa_pol_signal) {
				sa_pol_action();
			}
			if (sa_hup_signal) {
				sa_hup_action();
			}
			if (sa_int_signal) {
				if (sa_debug)
					snmp_log(MY_FACILITY(LOG_DEBUG), "%s: shutting down\n", argv[0]);
				snmp_shutdown("ss7MIB");
				sa_int_action();	/* no return */
			}
			if (sa_trm_signal) {
				if (sa_debug)
					snmp_log(MY_FACILITY(LOG_DEBUG), "%s: shutting down\n", argv[0]);
				snmp_shutdown("ss7MIB");
				sa_trm_action();	/* no return */
			}
		} else if (retval > 0) {
			/* processed packets */
			if (sa_fclose) {
				/* close files after each request */
				if (sa_fd != 0) {
					int fd = sa_fd;

					sa_fd = 0;
					close(fd);
				}
			}
			sa_stats_refresh = 1;
			sa_request++;
		}
	}
	if (sa_debug)
		snmp_log(MY_FACILITY(LOG_DEBUG), "%s: shutting down\n", argv[0]);
	snmp_shutdown("ss7MIB");
}

int
main(int argc, char *argv[])
{
	for (;;) {
		int c, val, fd;
		char *cptr;
		struct passwd *pw;
		struct group *gr;
		struct stat st;

#if defined _GNU_SOURCE
		int option_index = 0;
                /* *INDENT-OFF* */
                static struct option long_options[] = {
                        {"log-addresses",	no_argument,		NULL, 'a'},
                        {"append",		no_argument,		NULL, 'A'},
                        {"config-file",		required_argument,	NULL, 'c'},
                        {"no-configs",		no_argument,		NULL, 'C'},
                        {"dump",		no_argument,		NULL, 'd'},
                        {"debug",		optional_argument,	NULL, 'D'},
                        {"debug-tokens",	optional_argument,	NULL, 'D'},
                        {"dont-fork",		no_argument,		NULL, 'f'},
                        {"gid",			required_argument,	NULL, 'g'},
                        {"groupid",		required_argument,	NULL, 'g'},
                        {"help",		no_argument,		NULL, 'h'},
                        {"?",			no_argument,		NULL, 'h'},
                        {"help-directives",	no_argument,		NULL, 'H'},
                        {"initialize",		required_argument,	NULL, 'I'},
                        {"init-modules",	required_argument,	NULL, 'I'},
                        {"keep-open",		no_argument,		NULL, 'k'},
                        {"log-file",		optional_argument,	NULL, 'l'},
                        {"logfile",		optional_argument,	NULL, 'l'},
                        {"Lf",			optional_argument,	NULL, 'l'},
                        {"LF",			required_argument,	NULL, 'l'},
                        {"log-stderr",		no_argument,		NULL, 'L'},
                        {"Le",			no_argument,		NULL, 'L'},
                        {"LE",			required_argument,	NULL, 'L'},
                        {"mibs",		required_argument,	NULL, 'm'},
                        {"master",		no_argument,		NULL, 'M'},
                        {"mibdirs",		required_argument,	NULL, 'M'},
                        {"nodaemon",		no_argument,		NULL, 'n'},
                        {"name",		required_argument,	NULL, 'n'},
                        {"dry-run",		no_argument,		NULL, 'N'},
                        {"log-stdout",		no_argument,		NULL, 'o'},
                        {"Lo",			no_argument,		NULL, 'o'},
                        {"LO",			required_argument,	NULL, 'o'},
                        {"port",		required_argument,	NULL, 'p'},
                        {"pidfile",		required_argument,	NULL, 'P'},
                        {"quiet",		no_argument,		NULL, 'q'},
                        {"quick",		no_argument,		NULL, 'q'},
                        {"noroot",		no_argument,		NULL, 'r'},
                        {"log-syslog",		no_argument,		NULL, 's'},
                        {"Ls",			no_argument,		NULL, 's'},
                        {"LS",			required_argument,	NULL, 's'},
                        {"syslog",		no_argument,		NULL, 's'},
                        {"sysctl-file",		required_argument,	NULL, 'S'},
                        {"agent-alarms",	no_argument,		NULL, 't'},
                        {"transport",		optional_argument,	NULL, 'T'},
                        {"uid",			required_argument,	NULL, 'u'},
                        {"userid",		required_argument,	NULL, 'u'},
                        {"dont-remove-pidfile",	no_argument,		NULL, 'U'},
                        {"leave-pidfile",	no_argument,		NULL, 'U'},
                        {"version",		no_argument,		NULL, 'v'},
                        {"verbose",		optional_argument,	NULL, 'V'},
                        {"agentx-socket",	required_argument,	NULL, 'x'},
                        {"agentx",		no_argument,		NULL, 'X'},
                        {"copying",		no_argument,		NULL, 'y'},
#if 0
                        {"directory",		required_argument,	NULL, 'd'},
                        {"basename",		required_argument,	NULL, 'b'},
                        {"outfile",		required_argument,	NULL, 'o'},
                        {"errfile",		required_argument,	NULL, 'e'},
#endif
                        { 0, }
                };
                /* *INDENT-ON* */

		c = getopt_long_only(argc, argv, ":aAc:CdD::fg:hHI:kl::L::m:M::n::o::p:P:qrs::S:tT::u:UvV::x:Xy", long_options, &option_index);
#else				/* defined _GNU_SOURCE */
		c = getopt(argc, argv, ":aAc:CdD::fg:hHI:kl::L::m:M::n::o::p:P:qrs::S:tT::u:UvV::x:Xy");
#endif				/* defined _GNU_SOURCE */
		if (c == -1) {
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: done options processing\n", argv[0]);
			break;
		}
		switch (c) {
		case 0:
			goto bad_usage;
		case 'a':	/* -a, --log-addresses */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: logging addresses\n", argv[0]);
			sa_logaddr++;
			break;
		case 'A':	/* -A, --append */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: will not truncate logfile\n", argv[0]);
#if defined NETSNMP_DS_LIB_APPEND_LOGFILES
			ds_set_boolean(DS_LIBRARY_ID, NETSNMP_DS_LIB_APPEND_LOGFILES, 1);
#endif				/* defined NETSNMP_DS_LIB_APPEND_LOGFILES */
			sa_appendlog = 1;
			break;
		case 'c':	/* -c, --config-file CONFIGFILE */
			if (optarg == NULL)
				goto bad_option;
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: using configuration file %s\n", argv[0], optarg);
			ds_set_string(DS_LIBRARY_ID, DS_LIB_OPTIONALCONFIG, optarg);
			break;
		case 'C':	/* -C, --no-configs */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: not reading default config files\n", argv[0]);
			ds_set_boolean(DS_LIBRARY_ID, DS_LIB_DONT_READ_CONFIGS, 1);
			break;
		case 'd':	/* -d, --dump */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: setting packet dump\n", argv[0]);
			sa_dump = 1;
			// snmp_set_dump_packet(sa_dump);
			ds_set_boolean(DS_LIBRARY_ID, DS_LIB_DUMP_PACKET, sa_dump);
			ds_set_boolean(DS_APPLICATION_ID, DS_AGENT_VERBOSE, sa_dump);
			break;
		case 'D':	/* -D, --debug [LEVEL], --debug-tokens [TOKENS] */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: increasing debug verbosity\n", argv[0]);
			if (optarg == NULL) {
				/* no option: must be -D, --debug */
				sa_debug++;
				if (sa_debug)
					snmp_log(MY_FACILITY(LOG_DEBUG), "%s: debug level is now %d\n", argv[0], sa_debug);
				if (sa_debug)
					snmp_log(MY_FACILITY(LOG_DEBUG), "%s: debugging all tokens\n", argv[0]);
				if (sa_debug)
					debug_register_tokens("ALL");
			} else {
				cptr = optarg;
				if ((val = strtol(optarg, &cptr, 0)) < 0)
					goto bad_option;
				if (*cptr == '\0') {
					/* it is just a number, must be -D, --debug [LEVEL] */
					sa_debug = val;
					if (sa_debug)
						snmp_log(MY_FACILITY(LOG_DEBUG), "%s: debug level is now %d\n", argv[0], sa_debug);
				} else {
					/* not a number, must be -D, --debug-tokens TOKENS */
					if (sa_debug)
						snmp_log(MY_FACILITY(LOG_DEBUG), "%s: debugging tokens %s\n", argv[0], optarg);
					debug_register_tokens(optarg);
				}
			}
			break;
		case 'f':	/* -f, --dont-fork */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: suppressing daemon mode\n", argv[0]);
			sa_nomead = 0;
			break;
		case 'u':	/* -u, --uid, --userid UID */
			cptr = optarg;
			if ((val = strtol(optarg, &cptr, 0)) < 0)
				goto bad_option;
			/* UID can be name or number */
			if ((pw = (*cptr == '\0') ? getpwuid((uid_t) val) : getpwnam(optarg)) == NULL)
				goto bad_option;
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: will run as uid %s(%d)\n", argv[0], pw->pw_name, pw->pw_uid);
			ds_set_int(DS_APPLICATION_ID, DS_AGENT_USERID, pw->pw_uid);
			break;
		case 'g':	/* -g, --gid, --groupdid GID */
			cptr = optarg;
			if ((val = strtol(optarg, &cptr, 0)) < 0)
				goto bad_option;
			/* GID can be name or number */
			if ((gr = (*cptr == '\0') ? getgrgid((gid_t) val) : getgrnam(optarg)) == NULL)
				goto bad_option;
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: will run as gid %s(%d)\n", argv[0], gr->gr_name, gr->gr_gid);
			ds_set_int(DS_APPLICATION_ID, DS_AGENT_GROUPID, gr->gr_gid);
			break;
		case 'h':	/* -h, --help, -?, --? */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: printing help message\n", argv[0]);
			sa_help(argc, argv);
			exit(0);
		case 'H':	/* -H, --help-directives */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: printing config directives\n", argv[0]);
			sa_help_directives(argc, argv);
			exit(0);
		case 'I':	/* -I, --init-modules, --initialize MODULE[{,| |:}MODULE]* */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: will initialize modules: %s\n", argv[0], optarg);
			add_to_init_list(optarg);
			break;
		case 'k':	/* -k, --keep-open */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: keeping files open\n", argv[0]);
			sa_fclose = 0;
			break;
		case 'l':	/* -l, --log-file, --logfile, -Lf, -LF p1[-p2] [LOGFILE] */
			if (optarg != NULL)
				strncpy(sa_logfile, optarg, sizeof(sa_logfile));
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: will log to file %s\n", argv[0], sa_logfile);
			sa_logfillog = 1;
			break;
		case 'L':	/* -L, --log-stderr, -Le, -LE p1[-p2] */
			/* Note that the recent NET-SNMP version of this option is far more
			   complicated: -Le is the same as the old version of the option; -Lf
			   LOGFILE is like the -l option; -Ls is like the -s option; -Lo logs
			   messages to standard output; -LX p1[-p2] [LOGFILE], where X = E, F, S or
			   O, logs priority p1 and above to X, or p1 thru p2 to X. */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: logging to standard error\n", argv[0]);
			sa_logstderr = 1;
			break;
		case 'm':	/* -m, --mibs MIBS */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: using MIBS %s\n", argv[0], optarg);
			break;
		case 'M':	/* -M, --master or -M, --mibdirs MIBDIRS */
			if (optarg) {
				/* -M, --mibdirs MIBDIRS */
				if (sa_debug)
					snmp_log(MY_FACILITY(LOG_DEBUG), "%s: using MIBDIRS %s\n", argv[0], optarg);
			} else {
				/* -M, --master */
				if (sa_debug)
					snmp_log(MY_FACILITY(LOG_DEBUG), "%s: setting SNMP master\n", argv[0]);
				sa_agentx = 0;
				ds_set_boolean(DS_APPLICATION_ID, DS_AGENT_ROLE, 0);
			}
			break;
		case 'n':	/* -n, --nodaemon or -n, --name NAME */
			if (optarg) {
				/* -n, --name NAME */
				if (sa_debug)
					snmp_log(MY_FACILITY(LOG_DEBUG), "%s: using name %s\n", argv[0], optarg);
				ds_set_string(DS_APPLICATION_ID, DS_AGENT_PROGNAME, optarg);
			} else {
				/* -n, --nodaemon */
				if (sa_debug)
					snmp_log(MY_FACILITY(LOG_DEBUG), "%s: suppressing deamon mode\n", argv[0]);
				sa_nomead = 0;
				ds_set_string(DS_APPLICATION_ID, DS_AGENT_PROGNAME, basename(argv[0]));
			}
			break;
		case 'N':	/* -N, --dry-run */
#if defined NETSNMP_DS_AGENT_QUIT_IMMEDIATELY
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: setting for dry-runs startup\n", argv[0]);
			ds_set_boolean(DS_APPLICATION_ID, NETSNMP_DS_AGENT_QUIT_IMMEDIATELY, 1);
			break;
#else				/* defined NETSNMP_DS_AGENT_QUIT_IMMEDIATELY */
			snmp_log(MY_FACILITY(LOG_DEBUG), "%s: -N option not supported\n", argv[0]);
			goto bad_option;
#endif				/* defined NETSNMP_DS_AGENT_QUIT_IMMEDIATELY */
		case 'o':	/* -o, --log-stdout, -Lo, -LO p1[-p2] */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: logging to stdout\n", argv[0]);
			sa_logstdout = 1;
			break;
		case 'p':	/* -p, --port PORTNUM or -p, --pidfile PIDFILE */
			cptr = optarg;
			if ((val = strtol(optarg, &cptr, 0)) < 0 || val > 16383)
				goto bad_option;
			if (*cptr == '\0') {
				char buf[4096];

				/* -p, --port PORTNUM */
				if ((cptr = ds_get_string(DS_APPLICATION_ID, DS_AGENT_PORTS)))
					snprintf(buf, sizeof(buf), "%s,%s", cptr, optarg);
				else
					strncpy(buf, optarg, sizeof(buf));
				ds_set_string(DS_APPLICATION_ID, DS_AGENT_PORTS, buf);
				break;
			}
			/* fall through */
		case 'P':	/* -p, -P, --pidfile PIDFILE */
			if (optarg) {
				/* either it exists */
				if (stat(optarg, &st) == -1) {
					/* or we can create it */
					if ((fd = open(optarg, O_CREAT, 0600)) == -1) {
						perror(argv[0]);
						goto bad_option;
					}
					close(fd);
				}
				if (sa_debug)
					snmp_log(MY_FACILITY(LOG_DEBUG), "%s: setting pid file to %s\n", argv[0], optarg);
				strncpy(sa_pidfile, optarg, sizeof(sa_pidfile));
			}
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: using pidfile %s\n", argv[0], sa_pidfile);
			break;
		case 'q':	/* -q, --quiet, --quick */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: suppressing normal output\n", argv[0]);
			sa_debug = 0;
			sa_output = 0;
			ds_set_boolean(DS_APPLICATION_ID, DS_AGENT_VERBOSE, 0);
			// snmp_set_quick_print();
			ds_set_boolean(DS_LIBRARY_ID, DS_LIB_QUICK_PRINT, 1);
			break;
		case 'r':	/* -r, --noroot */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: setting for non-root access\n", argv[0]);
			ds_set_boolean(DS_APPLICATION_ID, DS_AGENT_NO_ROOT_ACCESS, 1);
			break;
		case 's':	/* -s, --log-syslog, -Ls, -LS p1[-p2] */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: logging to system logs\n", argv[0]);
			sa_logsyslog = 1;
			break;
		case 'S':	/* -S, -sysctl-file FILENAME */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: using %s for backing\n", argv[0], optarg);
			strncpy(sa_sysctlf, optarg, sizeof(sa_sysctlf));
			break;
		case 't':	/* -t, --agent-alarms */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: setting agent alarms\n", argv[0]);
			sa_alarms = 0;
			ds_set_boolean(DS_LIBRARY_ID, DS_LIB_ALARM_DONT_USE_SIG, 1);
			break;
		case 'T':	/* -T, --transport [TRANSPORT] */
			if (optarg == NULL)
				goto udp_transport;
			if (!strcasecmp("TCP", optarg)) {
				if (sa_debug)
					snmp_log(MY_FACILITY(LOG_DEBUG), "%s: setting default transport to TCP\n", argv[0]);
				val = ds_get_int(DS_APPLICATION_ID, DS_AGENT_FLAGS);
				val |= SNMP_FLAGS_STREAM_SOCKET;
				ds_set_int(DS_APPLICATION_ID, DS_AGENT_FLAGS, val);
			} else if (!strcasecmp("UDP", optarg)) {
			      udp_transport:
				if (sa_debug)
					snmp_log(MY_FACILITY(LOG_DEBUG), "%s: setting default transport to UDP\n", argv[0]);
				val = ds_get_int(DS_APPLICATION_ID, DS_AGENT_FLAGS);
				val &= ~SNMP_FLAGS_STREAM_SOCKET;
				ds_set_int(DS_APPLICATION_ID, DS_AGENT_FLAGS, val);
			} else
				goto bad_option;
			break;
		case 'U':
#if defined NETSNMP_DS_AGENT_LEAVE_PIDFILE
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: will leave pidfile after shutdown\n", argv[0]);
			ds_set_boolean(DS_APPLICATION_ID, NETSNMP_DS_AGENT_LEAVE_PIDFILE, 1);
#else
			snmp_log(MY_FACILITY(LOG_DEBUG), "%s: -U option not supported\n");
			goto bad_option;
#endif				/* defined NETSNMP_DS_AGENT_LEAVE_PIDFILE */
			break;
		case 'v':	/* -v, --version */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: printing version message\n", argv[0]);
			sa_version(argc, argv);
			exit(0);
		case 'V':	/* -V, --verbose [LEVEL] */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: increasing output verbosity\n", argv[0]);
			if (optarg == NULL) {
				sa_output++;
			} else {
				if ((val = strtol(optarg, NULL, 0)) < 0)
					goto bad_option;
				sa_output = val;
			}
			if (sa_output > 1)
				ds_set_boolean(DS_APPLICATION_ID, DS_AGENT_VERBOSE, 1);
			else
				ds_set_boolean(DS_APPLICATION_ID, DS_AGENT_VERBOSE, 0);
			break;
		case 'x':	/* -x, --agentx-socket SOCKET */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: setting AgentX socket to %s\n", argv[0], optarg);
			ds_set_string(DS_APPLICATION_ID, DS_AGENT_X_SOCKET, optarg);
			// ds_set_boolean(DS_APPLICATION_ID, DS_AGENT_AGENTX_MASTER, 1);
			break;
		case 'X':	/* -X, --agentx */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: setting AgentX sub-agent\n", argv[0]);
			sa_agentx = 1;
			ds_set_boolean(DS_APPLICATION_ID, DS_AGENT_ROLE, 1);
			break;
		case 'y':	/* -y, --copying */
			if (sa_debug)
				snmp_log(MY_FACILITY(LOG_DEBUG), "%s: printing copying message\n", argv[0]);
			sa_copying(argc, argv);
			exit(0);
		case '?':
		case ':':
		default:
		      bad_option:
			optind--;
			goto bad_nonopt;
		      bad_nonopt:
			if (sa_output || sa_debug) {
				if (optind < argc) {
					fprintf(stderr, "%s: syntax error near '", argv[0]);
					while (optind < argc)
						fprintf(stderr, "%s ", argv[optind++]);
					fprintf(stderr, "'\n");
				} else {
					fprintf(stderr, "%s: missing option or argument", argv[0]);
					fprintf(stderr, "\n");
				}
				fflush(stderr);
			      bad_usage:
				sa_usage(argc, argv);
			}
			exit(2);
		}
	}
	if (optind < argc) {
		if (sa_debug)
			snmp_log(MY_FACILITY(LOG_DEBUG), "%s: excess non-option arguments\n", argv[0]);
		goto bad_nonopt;
	}
	sa_enter(argc, argv);	/* daemonize if necessary */
	sa_mloop(argc, argv);	/* execute main loop */
	exit(0);
}
#endif				/* !defined MODULE */
