/*****************************************************************************

 @(#) $Id: ss7MIB.h,v 0.9.2.10 2009-01-19 13:31:51 brian Exp $

 -----------------------------------------------------------------------------

 Copyright (c) 2008-2009  Monavacon Limited <http://www.monavacon.com/>
 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; version 3 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 -----------------------------------------------------------------------------

 Last Modified $Date: 2009-01-19 13:31:51 $ by $Author: brian $

 -----------------------------------------------------------------------------

 $Log: ss7MIB.h,v $
 Revision 0.9.2.10  2009-01-19 13:31:51  brian
 - updating standalone agents

 Revision 0.9.2.9  2009-01-16 20:45:01  brian
 - updating mibs and agents

 Revision 0.9.2.8  2009-01-14 14:30:07  brian
 - working up agents

 Revision 0.9.2.7  2009-01-10 17:09:22  brian
 - updated agents

 Revision 0.9.2.6  2009-01-04 13:16:06  brian
 - updated agents

 Revision 0.9.2.5  2009-01-03 10:51:07  brian
 - updated agent

 Revision 0.9.2.4  2009-01-02 15:04:16  brian
 - updated agents

 Revision 0.9.2.3  2008-12-31 16:04:47  brian
 - updated mibs

 Revision 0.9.2.2  2008-12-24 13:08:26  brian
 - building ss7confd

 *****************************************************************************/

#ifndef __LOCAL_SS7MIB_H__
#define __LOCAL_SS7MIB_H__

#ident "@(#) $RCSfile: ss7MIB.h,v $ $Name:  $($Revision: 0.9.2.10 $) Copyright (c) 2008-2009 Monavacon Limited."

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */

#define MASTER 1
extern const char sa_program[];
extern int sa_fclose;			/* default close files between requests */
extern int sa_changed;			/* indication to reread MIB configuration */
extern int sa_stats_refresh;		/* indications that statistics, the mib or its tables need to be refreshed */
extern int sa_request;			/* request number for per-request actions */

/* our storage structure(s) */
struct ss7MIB_data {
	uint ss7MIB_request;
};
struct ss7NetworkTable_data {
	uint ss7NetworkTable_request;
	uint ss7NetworkTable_refs;
	long ss7NetworkId;		/* NoAccess */
	oid *ss7NetworkProtocolVariant;	/* Create */
	size_t ss7NetworkProtocolVariantLen;
	ulong ss7NetworkProtocolVersion;	/* Create */
	uint8_t *ss7NetworkProtocolOptions;	/* Create */
	size_t ss7NetworkProtocolOptionsLen;
	long ss7NetworkRowStatus;	/* Create */
};

/* storage declarations */
extern struct ss7MIB_data *ss7MIBStorage;
extern struct header_complex_index *ss7NetworkTableStorage;

/* enum definitions from the covered mib sections */

/* notifications */

/* scalars accessible only for notify */

/* object id definitions */
extern oid ss7ProtocolItut_oid[14];
extern oid ss7ProtocolItut1980_oid[15];
extern oid ss7ProtocolItut1984_oid[15];
extern oid ss7ProtocolItut1988_oid[15];
extern oid ss7ProtocolItut1992_oid[15];
extern oid ss7ProtocolItut1996_oid[15];
extern oid ss7ProtocolItut2000_oid[15];
extern oid ss7ProtocolItut2004_oid[15];
extern oid ss7ProtocolItut2008_oid[15];
extern oid ss7ProtocolEtsi_oid[14];
extern oid ss7ProtocolEtsi1980_oid[15];
extern oid ss7ProtocolEtsi1984_oid[15];
extern oid ss7ProtocolEtsi1988_oid[15];
extern oid ss7ProtocolEtsi1992_oid[15];
extern oid ss7ProtocolEtsi1996_oid[15];
extern oid ss7ProtocolEtsi2000_oid[15];
extern oid ss7ProtocolEtsi2004_oid[15];
extern oid ss7ProtocolEtsi2008_oid[15];
extern oid ss7ProtocolAnsi_oid[14];
extern oid ss7ProtocolAnsi1980_oid[15];
extern oid ss7ProtocolAnsi1984_oid[15];
extern oid ss7ProtocolAnsi1988_oid[15];
extern oid ss7ProtocolAnsi1992_oid[15];
extern oid ss7ProtocolAnsi1996_oid[15];
extern oid ss7ProtocolAnsi2000_oid[15];
extern oid ss7ProtocolAnsi2004_oid[15];
extern oid ss7ProtocolAnsi2008_oid[15];
extern oid ss7ProtocolJttc_oid[14];
extern oid ss7ProtocolJttc1980_oid[15];
extern oid ss7ProtocolJttc1984_oid[15];
extern oid ss7ProtocolJttc1988_oid[15];
extern oid ss7ProtocolJttc1992_oid[15];
extern oid ss7ProtocolJttc1996_oid[15];
extern oid ss7ProtocolJttc2000_oid[15];
extern oid ss7ProtocolJttc2004_oid[15];
extern oid ss7ProtocolJttc2008_oid[15];
extern oid ss7ProtocolChin_oid[14];
extern oid ss7ProtocolChin1980_oid[15];
extern oid ss7ProtocolChin1984_oid[15];
extern oid ss7ProtocolChin1988_oid[15];
extern oid ss7ProtocolChin1992_oid[15];
extern oid ss7ProtocolChin1996_oid[15];
extern oid ss7ProtocolChin2000_oid[15];
extern oid ss7ProtocolChin2004_oid[15];
extern oid ss7ProtocolChin2008_oid[15];
extern oid ss7ProtocolSing_oid[14];
extern oid ss7ProtocolSing1980_oid[15];
extern oid ss7ProtocolSing1984_oid[15];
extern oid ss7ProtocolSing1988_oid[15];
extern oid ss7ProtocolSing1992_oid[15];
extern oid ss7ProtocolSing1996_oid[15];
extern oid ss7ProtocolSing2000_oid[15];
extern oid ss7ProtocolSing2004_oid[15];
extern oid ss7ProtocolSing2008_oid[15];
extern oid ss7ProtocolSpan_oid[14];
extern oid ss7ProtocolSpan1980_oid[15];
extern oid ss7ProtocolSpan1984_oid[15];
extern oid ss7ProtocolSpan1988_oid[15];
extern oid ss7ProtocolSpan1992_oid[15];
extern oid ss7ProtocolSpan1996_oid[15];
extern oid ss7ProtocolSpan2000_oid[15];
extern oid ss7ProtocolSpan2004_oid[15];
extern oid ss7ProtocolSpan2008_oid[15];
extern oid ss7ProtocolPnoc_oid[14];
extern oid ss7ProtocolPnoc1980_oid[15];
extern oid ss7ProtocolPnoc1984_oid[15];
extern oid ss7ProtocolPnoc1988_oid[15];
extern oid ss7ProtocolPnoc1992_oid[15];
extern oid ss7ProtocolPnoc1996_oid[15];
extern oid ss7ProtocolPnoc2000_oid[15];
extern oid ss7ProtocolPnoc2004_oid[15];
extern oid ss7ProtocolPnoc2008_oid[15];

/* function prototypes */
/* trap function prototypes */

/* variable function prototypes */
void init_ss7MIB(void);
void deinit_ss7MIB(void);
int term_ss7MIB(int majorID, int minorID, void *serverarg, void *clientarg);
FindVarMethod var_ss7MIB;
void parse_ss7MIB(const char *, char *);
SNMPCallback store_ss7MIB;
void refresh_ss7MIB(int);
FindVarMethod var_ss7NetworkTable;
struct ss7NetworkTable_data *ss7NetworkTable_create(void);
struct ss7NetworkTable_data *ss7NetworkTable_duplicate(struct ss7NetworkTable_data *);
int ss7NetworkTable_destroy(struct ss7NetworkTable_data **);
int ss7NetworkTable_add(struct ss7NetworkTable_data *);
int ss7NetworkTable_del(struct ss7NetworkTable_data *);
void parse_ss7NetworkTable(const char *, char *);
SNMPCallback store_ss7NetworkTable;
void refresh_ss7NetworkTable(int);

WriteMethod write_ss7NetworkProtocolVariant;
WriteMethod write_ss7NetworkProtocolVersion;
WriteMethod write_ss7NetworkProtocolOptions;
WriteMethod write_ss7NetworkRowStatus;

#include "mxMIB.h"
#include "x400pMIB.h"
#include "mtpMIB.h"
#include "mtpOmMIB.h"
#include "sccpMIB.h"
#include "sccpOmMIB.h"
#include "tcapMIB.h"
#include "tcapOmMIB.h"

#endif				/* __LOCAL_SS7MIB_H__ */
