/*****************************************************************************

 @(#) $Id: ss7OmMIB.h,v 0.9.2.4 2009-01-04 13:16:06 brian Exp $

 -----------------------------------------------------------------------------

 Copyright (c) 2008-2009  Monavacom Limited <http://www.monavacom.com/>
 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; version 3 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 -----------------------------------------------------------------------------

 Last Modified $Date: 2009-01-04 13:16:06 $ by $Author: brian $

 -----------------------------------------------------------------------------

 $Log: ss7OmMIB.h,v $
 Revision 0.9.2.4  2009-01-04 13:16:06  brian
 - updated agents

 Revision 0.9.2.3  2009-01-02 15:04:16  brian
 - updated agents

 Revision 0.9.2.2  2008-12-24 13:08:26  brian
 - building ss7confd

 *****************************************************************************/

#ifndef __LOCAL_SS7OMMIB_H__
#define __LOCAL_SS7OMMIB_H__

#ident "@(#) $RCSfile: ss7OmMIB.h,v $ $Name:  $($Revision: 0.9.2.4 $) Copyright (c) 2008-2009 Monavacom Limited."

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */
/* our storage structure(s) */
struct ss7OmMIB_data {
	uint ss7OmMIB_request;
};

/* storage declarations */
extern struct ss7OmMIB_data *ss7OmMIBStorage;

/* enum definitions from the covered mib sections */

/* notifications */
extern oid mtpRestarting_oid[11];
extern oid ss7OnOccEvent_oid[11];

/* scalars accessible only for notify */
extern oid pointCode_oid[12];

/* object id definitions */

/* function prototypes */
/* trap function prototypes */
extern void send_mtpRestarting_v2trap(struct variable_list *);
extern void send_ss7OnOccEvent_v2trap(struct variable_list *);

/* variable function prototypes */
void init_ss7OmMIB(void);
void deinit_ss7OmMIB(void);
int term_ss7OmMIB(int majorID, int minorID, void *serverarg, void *clientarg);
FindVarMethod var_ss7OmMIB;
void parse_ss7OmMIB(const char *, char *);
SNMPCallback store_ss7OmMIB;
void refresh_ss7OmMIB(void);

#endif				/* __LOCAL_SS7OMMIB_H__ */
