/*****************************************************************************

 @(#) $RCSfile: ss7OmMIB.c,v $ $Name:  $($Revision: 0.9.2.4 $) $Date: 2009-01-02 15:04:16 $

 -----------------------------------------------------------------------------

 Copyright (c) 2008-2009  Monavacom Limited <http://www.monavacom.com/>
 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software: you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation, version 3 of the license.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 -----------------------------------------------------------------------------

 Last Modified $Date: 2009-01-02 15:04:16 $ by $Author: brian $

 -----------------------------------------------------------------------------

 $Log: ss7OmMIB.c,v $
 Revision 0.9.2.4  2009-01-02 15:04:16  brian
 - updated agents

 Revision 0.9.2.3  2008-12-31 16:04:47  brian
 - updated mibs

 Revision 0.9.2.2  2008-12-24 13:08:26  brian
 - building ss7confd

 *****************************************************************************/

#ident "@(#) $RCSfile: ss7OmMIB.c,v $ $Name:  $($Revision: 0.9.2.4 $) $Date: 2009-01-02 15:04:16 $"

static char const ident[] = "$RCSfile: ss7OmMIB.c,v $ $Name:  $($Revision: 0.9.2.4 $) $Date: 2009-01-02 15:04:16 $";

/* This file was generated by mib2c and is intended for use as
   a mib module for the ucd-snmp snmpd agent. */
#include <ucd-snmp/ucd-snmp-config.h>
#include <ucd-snmp/ucd-snmp-includes.h>
#include <ucd-snmp/ucd-snmp-agent-includes.h>
#include <ucd-snmp/callback.h>
#include <ucd-snmp/snmp-tc.h>
#include <ucd-snmp/default_store.h>
#include <ucd-snmp/snmp_alarm.h>
/* The following header files are mangled in most recent net-snmp releases so
 * the versions from UCD-SNMP 4.2.5 are included here.  */
#if defined HAVE_LIBNETSNMP
#else				/* defined HAVE_LIBNETSNMP */
#endif				/* defined HAVE_LIBNETSNMP */
/* These are messed up on both. */
#include "ds_agent.h"
#ifdef HAVE_UCD_SNMP_UTIL_FUNCS_H
#include <ucd-snmp/util_funcs.h>
/* Many recent net-snmp UCD compatible headers do not declard header_generic. */
int header_generic(struct variable *, oid *, size_t *, int, size_t *, WriteMethod **);
#else				/* HAVE_UCD_SNMP_UTIL_FUNCS_H */
#include "util_funcs.h"
#endif				/* HAVE_UCD_SNMP_UTIL_FUNCS_H */
#ifdef HAVE_UCD_SNMP_HEADER_COMPLEX_H
#include <ucd-snmp/header_complex.h>
#else				/* HAVE_UCD_SNMP_HEADER_COMPLEX_H */
#include "header_complex.h"
#endif				/* HAVE_UCD_SNMP_HEADER_COMPLEX_H */
/* This one is the other way around: it is just fine for net-snmp, but
 * ucd-snmp does not provide the header file at all.  */
#ifdef HAVE_UCD_SNMP_MIB_MODULES_H
#include <ucd-snmp/mib_modules.h>
#else				/* HAVE_UCD_SNMP_MIB_MODULES_H */
#ifdef HAVE_NET_SNMP_AGENT_MIB_MODULES_H
#include <net-snmp/agent/mib_modules.h>
#else				/* HAVE_NET_SNMP_AGENT_MIB_MODULES_H */
#include "mib_modules.h"
#endif				/* HAVE_NET_SNMP_AGENT_MIB_MODULES_H */
#endif				/* HAVE_UCD_SNMP_MIB_MODULES_H */
#include <stdint.h>
#include <signal.h>
#include <sys/stat.h>		/* for struct stat, fstat() */
#include <sys/types.h>
#include <unistd.h>
#include <stdlib.h>
#include <pwd.h>		/* for getpwuid() getpwnam() */
#include <grp.h>		/* for getgrgid() getgrnam() */
#include <libgen.h>		/* for basename() */
#include <fcntl.h>		/* for O_CREAT */
#include <sys/sysctl.h>		/* for sysctl */
#include <errno.h>
#include <string.h>
#ifdef _GNU_SOURCE
#include <getopt.h>
#endif
#include "ss7OmMIB.h"
extern const char sa_program[];

#define MY_FACILITY(__pri)	(LOG_DAEMON|(__pri))
#if !defined MODULE
extern int sa_dump;			/* default packet dump */
extern int sa_debug;			/* default no debug */
extern int sa_nomead;			/* default daemon mode */
extern int sa_output;			/* default normal output */
extern int sa_agentx;			/* default agentx mode */
extern int sa_alarms;			/* default application alarms */
extern int sa_fclose;			/* default close files between requests */
extern int sa_logaddr;			/* log addresses */
extern int sa_logfillog;		/* log to sa_logfile */
extern int sa_logstderr;		/* log to standard error */
extern int sa_logstdout;		/* log to standard output */
extern int sa_logsyslog;		/* log to system logs */
extern int sa_logcallog;		/* log to callback logs */
extern int sa_appendlog;		/* append to log file without truncating */
extern char sa_logfile[256];
extern char sa_pidfile[256];
extern char sa_sysctlf[256];

/* file stream for log file */
extern FILE *stdlog;

/* file descriptor for MIB use */
extern int sa_fd;

/* indication to reread MIB configuration */
extern int sa_changed;

/* indications that statistics, the mib or its tables need to be refreshed */
extern int sa_stats_refresh;
#endif				/* !defined MODULE */
/* request number for per-request actions */
extern int sa_request;
volatile int ss7OmMIB_refresh = 1;

/*
 * ss7OmMIB_variables_oid: object identifier for ss7OmMIB
 * This is the top level oid that we want to register under.  This is essentially a prefix, with the
 * suffix appearing in the variable below.
 */
oid ss7OmMIB_variables_oid[] = { 1, 3, 6, 1, 4, 1, 29591, 17, 752, 0 };

/*
 * Oids for use in notifications defined in this MIB.
 */
oid mtpRestarting_oid[11] = { 1, 3, 6, 1, 4, 1, 29591, 17, 752, 0, 0 };
oid ss7OnOccEvent_oid[11] = { 1, 3, 6, 1, 4, 1, 29591, 17, 752, 0, 0 };

/*
 * Oids accessible only for notify defined in this MIB.
 */
oid pointCode_oid[12] = { 1, 3, 6, 1, 4, 1, 29591, 17, 752, 0, 1, 3 };

/*
 * Other oids defined in this MIB.
 */

/*
 * variable4 ss7OmMIB_variables: tree for ss7OmMIB
 * This variable defines function callbacks and type return information for the ss7OmMIB mib section
 */
struct variable4 ss7OmMIB_variables[] = {
	/* magic number, variable type, ro/rw, callback fn, L, oidsuffix */

};

/* (L = length of the oidsuffix) */
struct ss7OmMIB_data *ss7OmMIBStorage = NULL;

/* global storage of our data, saved in and configured by header_complex() */

/*
 * init_ss7OmMIB(): Initialization routine.
 * This is called when the agent starts up.  At a minimum, registration of your variables should
 * take place here.
 */
void
init_ss7OmMIB(void)
{
	DEBUGMSGTL(("ss7OmMIB", "initializing...  "));
	/* register ourselves with the agent to handle our mib tree */
	REGISTER_MIB("ss7OmMIB", ss7OmMIB_variables, variable4, ss7OmMIB_variables_oid);
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_SHUTDOWN, term_ss7OmMIB, NULL);
	/* register our config handler(s) to deal with registrations */
	snmpd_register_config_handler("ss7OmMIB", parse_ss7OmMIB, NULL, "HELP STRING");
	/* we need to be called back later to store our data */
	snmp_register_callback(SNMP_CALLBACK_LIBRARY, SNMP_CALLBACK_STORE_DATA, store_ss7OmMIB, NULL);
	/* place any other initialization junk you need here */
	DEBUGMSGTL(("ss7OmMIB", "done.\n"));
}

/*
 * deinit_ss7OmMIB(): Deinitialization routine.
 * This is called before the agent is unloaded.  At a minimum, deregistration of your variables
 * should take place here.
 */
void
deinit_ss7OmMIB(void)
{
	DEBUGMSGTL(("ss7OmMIB", "deinitializating...  "));
	unregister_mib(ss7OmMIB_variables_oid, sizeof(ss7OmMIB_variables_oid) / sizeof(oid));
	snmpd_unregister_config_handler("ss7OmMIB");
	/* place any other de-initialization junk you need here */
	DEBUGMSGTL(("ss7OmMIB", "done.\n"));
}

int
term_ss7OmMIB(int majorID, int minorID, void *serverarg, void *clientarg)
{
	deinit_ss7OmMIB();
	return 0;
}

/**
 * @fn struct ss7OmMIB_data *ss7OmMIB_create(void)
 * @brief create a fresh data structure representing scalars in ss7OmMIB.
 * Creates a new ss7OmMIB_data structure by allocating dynamic memory for the structure and
 * initializing the default values of scalars in ss7OmMIB.
 */
struct ss7OmMIB_data *
ss7OmMIB_create(void)
{
	struct ss7OmMIB_data *StorageNew = SNMP_MALLOC_STRUCT(ss7OmMIB_data);

	DBUGMSGTL(("ss7OmMIB", "creating scalars...  "));
	if (StorageNew != NULL) {
		/* XXX: fill in default scalar values here into StorageNew */

	}
	DEBUGMSGTL(("ss7OmMIB", "done.\n"));
	return (StorageNew);
}

/**
 * @fn int ss7OmMIB_destroy(struct ss7OmMIB_data **thedata)
 * @brief delete a scalars structure from ss7OmMIB.
 * @param thedata pointer to the data structure in ss7OmMIB.
 * Frees scalars that were previously removed from ss7OmMIB.  Note that the strings associated
 * with octet strings, object identifiers and bit strings still attached to the structure will also
 * be freed.  The pointer that was passed in  thedata will be set to NULL if it is not already
 * NULL.
 */
int
ss7OmMIB_destroy(struct ss7OmMIB_data **thedata)
{
	struct ss7OmMIB_data *StorageDel;

	DEBUGMSGTL(("ss7OmMIB", "deleting scalars...  "));
	if ((StorageDel = *thedata) != NULL) {
		SNMP_FREE(StorageDel->pointCode);
		StorageDel->pointCodeLen = 0;
		SNMP_FREE(StorageDel);
		*thedata = StorageDel;
	}
	DEBUGMSGTL(("ss7OmMIB", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn int ss7OmMIB_add(struct ss7OmMIB_data *thedata)
 * @param thedata the structure representing ss7OmMIB scalars.
 * @brief adds node to the ss7OmMIB scalar data set.
 * Adds a scalar structure to the ss7OmMIB data set.  Note that this function is necessary even
 * when the scalar values are not peristent.
 */
int
ss7OmMIB_add(struct ss7OmMIB_data *thedata)
{
	DEBUGMSGTL(("ss7OmMIB", "adding data...  "));
	ss7OmMIBStorage = thedata;
	DEBUGMSGTL(("ss7OmMIB", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn void parse_ss7OmMIB(const char *token, char *line)
 * @param token token used within the configuration file.
 * @param line line from configuration file matching the token.
 * @brief parse configuration file for ss7OmMIB entries.
 * This callback is called by UCD-SNMP when it prases a configuration file and finds a configuration
 * file line for the registsred token (in this case ss7OmMIB).  This routine is invoked by
 * UCD-SNMP to read the values of scalars in the MIB from the configuration file.  Note that this
 * procedure may exist regardless of the persistence of the MIB.  If there are no configured entries
 * in the configuration MIB, this function will simply not be called.
 */
void
parse_ss7OmMIB(const char *token, char *line)
{
	size_t tmpsize;
	struct ss7OmMIB_data *StorageTmp = ss7OmMIB_create();

	DEBUGMSGTL(("ss7OmMIB", "parsing config...  "));
	if (StorageTmp == NULL) {
		config_perror("malloc failure");
		return;
	}
	/* XXX: remove individual scalars that are not persistent */
	ss7OmMIB_add(StorageTmp);
	(void) tmpsize;
	DEBUGMSGTL(("ss7OmMIB", "done.\n"));
}

/*
 * store_ss7OmMIB(): stores .conf file entries needed to configure the mib.
 */
int
store_ss7OmMIB(int majorID, int minorID, void *serverarg, void *clientarg)
{
	char line[SNMP_MAXBUF];
	char *cptr;
	size_t tmpsize;
	struct ss7OmMIB_data *StorageTmp;

	DEBUGMSGTL(("ss7OmMIB", "storing data...  "));
	refresh_ss7OmMIB();
	if ((StorageTmp = ss7OmMIBStorage) == NULL) {
		DEBUGMSGTL(("ss7OmMIB", "error.\n"));
		return SNMPERR_GENERR;
	}
	(void) tmpsize;
	/* XXX: comment entire section if no scalars are persistent */
	{
		memset(line, 0, sizeof(line));
		strcat(line, "ss7OmMIB ");
		cptr = line + strlen(line);
		/* XXX: remove individual scalars that are not persistent */
		snmpd_store_config(line);
	}
	DEBUGMSGTL(("ss7OmMIB", "done.\n"));
	return SNMPERR_SUCCESS;
}

/**
 * @fn void refresh_ss7OmMIB(void)
 * @brief refresh the scalar values of ss7OmMIB.
 * Normally the values retrieved from the operating system are cached.  When the agent receives a
 * SIGPOLL from an open STREAMS configuration or administrative driver Stream, the STREAMS subsystem
 * indicates to the agent that the cache has been invalidated and that it should reread scalars and
 * tables from the STREAMS subsystem.  This function is used when the agent starts for the first
 * time, or after a SIGPOLL has been received (and a scalar has been requested).
 */
void
refresh_ss7OmMIB(void)
{
	if (ss7OmMIBStorage == NULL) {
		struct ss7OmMIB_data *StorageNew;

		if ((StorageNew = ss7OmMIB_create()) == NULL)
			return;
		ss7OmMIBStorage = StorageNew;
		ss7OmMIB_refresh = 1;
	}
	if (ss7OmMIB_refresh == 0)
		return;
	ss7OmMIB_refresh = 0;
	/* XXX: Update scalars as required here... */
}

/**
* @fn u_char * var_ss7OmMIB(struct variable *vp, oid *name, size_t *length, int exact, size_t *var_len, WriteMethod **write_method)
* @param vp a pointer to the entry in the variables table for the requested variable.
* @param name the object identifier for which to find.
* @param length the length of the object identifier.
* @param exact whether the name is exact.
* @param var_len a pointer to the length of the representation of the object.
* @param write_method a pointer to a write method for the object.
* @brief locate variables in ss7OmMIB.
* This function returns a pointer to a memory area that is static across the request that contains
* the UCD-SNMP representation of the scalar (so that it may be used to read from for a GET,
* GET-NEXT or GET-BULK request).  This returned pointer may be NULL, in which case the function is
* telling UCD-SNMP that the scalar does not exist for reading; however, if write_method is
* overwritten with a non-NULL value, the function is telling UCD-SNMP that the scalar exists for
* writing.  Write-only objects can be effected in this way.
*/
u_char *
var_ss7OmMIB(struct variable *vp, oid * name, size_t *length, int exact, size_t *var_len, WriteMethod ** write_method)
{
	struct ss7OmMIB_data *StorageTmp;

	if (header_generic(vp, name, length, exact, var_len, write_method) == MATCH_FAILED)
		return NULL;
	/* Refresh the MIB values if required. */
	refresh_ss7OmMIB();
	if ((StorageTmp = ss7OmMIBStorage) == NULL)
		return NULL;
	/* This is where we do the value assignments for the mib results. */
	switch (vp->magic) {
	default:
		ERROR_MSG("");
	}
	return NULL;
}
