/*****************************************************************************

 @(#) $Id: tcapOmMIB.h,v 0.9.2.2 2009-01-02 15:04:16 brian Exp $

 -----------------------------------------------------------------------------

 Copyright (c) 2008-2009  Monavacom Limited <http://www.monavacom.com/>
 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; version 3 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 -----------------------------------------------------------------------------

 Last Modified $Date: 2009-01-02 15:04:16 $ by $Author: brian $

 -----------------------------------------------------------------------------

 $Log: tcapOmMIB.h,v $
 Revision 0.9.2.2  2009-01-02 15:04:16  brian
 - updated agents

 Revision 0.9.2.1  2008-12-31 16:09:08  brian
 - added new mibs

 *****************************************************************************/

#ifndef __LOCAL_TCAPOMMIB_H__
#define __LOCAL_TCAPOMMIB_H__

#ident "@(#) $RCSfile: tcapOmMIB.h,v $ $Name:  $($Revision: 0.9.2.2 $) Copyright (c) 2008-2009 Monavacom Limited."

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */
/* our storage structure(s) */
struct tcapOmMIB_data {
	uint tcapOmMIB_request;
	oid *tcapOm1stAndIntervalActivate;
	size_t tcapOm1stAndIntervalActivateLen;
	oid *tcapOm1stAndIntervalDeactivate;
	size_t tcapOm1stAndIntervalDeactivateLen;
	oid *tcapOm5MinActivate;
	size_t tcapOm5MinActivateLen;
	oid *tcapOm5MinDeaActivate;
	size_t tcapOm5MinDeaActivateLen;
	oid *tcapOm15MinActivate;
	size_t tcapOm15MinActivateLen;
	oid *tcapOm15MinDeaActivate;
	size_t tcapOm15MinDeaActivateLen;
	long tcapOmDiscontinuityTime;
	long tcapOmTimeStamp;
	ulong tcapOm5MinMaxIntervals;
	ulong tcapOm15MinMaxIntervals;
};
struct tcapOmNodeTable_data {
	uint tcapOmNodeTable_request;
	uint tcapOmNodeTable_refs;
	ulong sccpNetworkEntityId;
	long tcapOmNodeMessagesSent;
	long tcapOmNodeMessagesRecv;
	long tcapOmNodeComponentsSent;
	long tcapOmNodeComponentsRecv;
	long tcapOmNode5minValidIntervals;
	long tcapOmNode15minValidIntervals;
};
struct tcapOmNodeCurrentTable_data {
	uint tcapOmNodeCurrentTable_request;
	uint tcapOmNodeCurrentTable_refs;
	ulong sccpNetworkEntityId;
	long tcapOmNodeCurrentMessagesSent;
	long tcapOmNodeCurrentMessagesRecv;
	long tcapOmNodeCurrentComponentsSent;
	long tcapOmNodeCurrentComponentsRecv;
};
struct tcapOmNode5minIntTable_data {
	uint tcapOmNode5minIntTable_request;
	uint tcapOmNode5minIntTable_refs;
	ulong sccpNetworkEntityId;
	long tcapOmInterval;
	long tcapOmNode5minIntMessagesSent;
	long tcapOmNode5minIntMessagesRecv;
	long tcapOmNode5minIntComponentsSent;
	long tcapOmNode5minIntComponentsRecv;
};
struct tcapOmNode15minIntTable_data {
	uint tcapOmNode15minIntTable_request;
	uint tcapOmNode15minIntTable_refs;
	ulong sccpNetworkEntityId;
	long tcapOmInterval;
	long tcapOmNode15minIntMessagesSent;
	long tcapOmNode15minIntMessagesRecv;
	long tcapOmNode15minIntComponentsSent;
	long tcapOmNode15minIntComponentsRecv;
};
struct tcapOmMsgsTable_data {
	uint tcapOmMsgsTable_request;
	uint tcapOmMsgsTable_refs;
	ulong sccpNetworkEntityId;
	ulong tcapOmMessageType;
	long tcapOmMsgsMessagesSent;
	long tcapOmMsgsMessagesRecv;
	long tcapOmMsgs5minValidIntervals;
	long tcapOmMsgs15minValidIntervals;
};
struct tcapOmMsgsCurrentTable_data {
	uint tcapOmMsgsCurrentTable_request;
	uint tcapOmMsgsCurrentTable_refs;
	ulong sccpNetworkEntityId;
	ulong tcapOmMessageType;
	long tcapOmMsgsCurrentMessagesSent;
	long tcapOmMsgsCurrentMessagesRecv;
};
struct tcapOmMsgs5minIntTable_data {
	uint tcapOmMsgs5minIntTable_request;
	uint tcapOmMsgs5minIntTable_refs;
	ulong sccpNetworkEntityId;
	ulong tcapOmMessageType;
	long tcapOmInterval;
	long tcapOmMsgs5minIntMessagesSent;
	long tcapOmMsgs5minIntMessagesRecv;
};
struct tcapOmMsgs15minIntTable_data {
	uint tcapOmMsgs15minIntTable_request;
	uint tcapOmMsgs15minIntTable_refs;
	ulong sccpNetworkEntityId;
	ulong tcapOmMessageType;
	long tcapOmInterval;
	long tcapOmMsgs15minIntMessagesSent;
	long tcapOmMsgs15minIntMessagesRecv;
};
struct tcapOmAETable_data {
	uint tcapOmAETable_request;
	uint tcapOmAETable_refs;
	ulong tcapApplicationEntityId;
	long tcapOmAEMeasurementDeleted;
	long tcapOmAENewTransactions;
	long tcapOmAEMeanOpenTransactions;
	long tcapOmAENotUsed;
	long tcapOmAECummulativeMeanDuration;
	long tcapOmAEMaximumOpenTranactions;
	long tcapOmAEThresholdExceeded;
	long tcapOmAE5minValidIntervals;
	long tcapOmAE15minValidIntervals;
};
struct tcapOmAECurrentTable_data {
	uint tcapOmAECurrentTable_request;
	uint tcapOmAECurrentTable_refs;
	ulong tcapApplicationEntityId;
	long tcapOmAECurrentMeasurementDeleted;
	long tcapOmAECurrentNewTransactions;
	long tcapOmAECurrentMeanOpenTransactions;
	long tcapOmAECurrentNotUsed;
	long tcapOmAECurrentCummulativeMeanDuration;
	long tcapOmAECurrentMaximumOpenTranactions;
	long tcapOmAECurrentThresholdExceeded;
};
struct tcapOmAE5minIntTable_data {
	uint tcapOmAE5minIntTable_request;
	uint tcapOmAE5minIntTable_refs;
	ulong tcapApplicationEntityId;
	long tcapOmInterval;
	long tcapOmAE5minIntMeasurementDeleted;
	long tcapOmAE5minIntNewTransactions;
	long tcapOmAE5minIntMeanOpenTransactions;
	long tcapOmAE5minIntNotUsed;
	long tcapOmAE5minIntCummulativeMeanDuration;
	long tcapOmAE5minIntMaximumOpenTranactions;
	long tcapOmAE5minIntThresholdExceeded;
};
struct tcapOmAE15minIntTable_data {
	uint tcapOmAE15minIntTable_request;
	uint tcapOmAE15minIntTable_refs;
	ulong tcapApplicationEntityId;
	long tcapOmInterval;
	long tcapOmAE15minIntMeasurementDeleted;
	long tcapOmAE15minIntNewTransactions;
	long tcapOmAE15minIntMeanOpenTransactions;
	long tcapOmAE15minIntNotUsed;
	long tcapOmAE15minIntCummulativeMeanDuration;
	long tcapOmAE15minIntMaximumOpenTranactions;
	long tcapOmAE15minIntThresholdExceeded;
};
struct tcapOmTcTable_data {
	uint tcapOmTcTable_request;
	uint tcapOmTcTable_refs;
	ulong tcapApplicationEntityId;
	long tcapOmTcPabortRecvUnrecTid;
	long tcapOmTcPabortRecvResourceLim;
	long tcapOmTcRejectRecvResourceLim;
	long tcapOmTcPabortSentUnrecTid;
	long tcapOmTcPabortSentResourceLim;
	long tcapOmTcRejectSentResourceLim;
	long tcapOmTcTcUserCancel;
	long tcapOmTcMessagesDiscarded;
	long tcapOmTcNotUsed;
	long tcapOmTcPabortsReceived;
	long tcapOmTcTcUserRejectsReceived;
	long tcapOmTcTpErrors;
	long tcapOmTc5minValidIntervals;
	long tcapOmTc15minValidIntervals;
};
struct tcapOmTcCurrentTable_data {
	uint tcapOmTcCurrentTable_request;
	uint tcapOmTcCurrentTable_refs;
	ulong tcapApplicationEntityId;
	long tcapOmTcCurrentPabortRecvUnrecTid;
	long tcapOmTcCurrentPabortRecvResourceLim;
	long tcapOmTcCurrentRejectRecvResourceLim;
	long tcapOmTcCurrentPabortSentUnrecTid;
	long tcapOmTcCurrentPabortSentResourceLim;
	long tcapOmTcCurrentRejectSentResourceLim;
	long tcapOmTcCurrentTcUserCancel;
	long tcapOmTcCurrentMessagesDiscarded;
	long tcapOmTcCurrentNotUsed;
	long tcapOmTcCurrentPabortsReceived;
	long tcapOmTcCurrentTcUserRejectsReceived;
	long tcapOmTcCurrentTpErrors;
};
struct tcapOmTc5minIntTable_data {
	uint tcapOmTc5minIntTable_request;
	uint tcapOmTc5minIntTable_refs;
	ulong tcapApplicationEntityId;
	long tcapOmInterval;
	long tcapOmTc5minIntPabortRecvUnrecTid;
	long tcapOmTc5minIntPabortRecvResourceLim;
	long tcapOmTc5minIntRejectRecvResourceLim;
	long tcapOmTc5minIntPabortSentUnrecTid;
	long tcapOmTc5minIntPabortSentResourceLim;
	long tcapOmTc5minIntRejectSentResourceLim;
	long tcapOmTc5minIntTcUserCancel;
	long tcapOmTc5minIntMessagesDiscarded;
	long tcapOmTc5minIntNotUsed;
	long tcapOmTc5minIntPabortsReceived;
	long tcapOmTc5minIntTcUserRejectsReceived;
	long tcapOmTc5minIntTpErrors;
};
struct tcapOmTc15minIntTable_data {
	uint tcapOmTc15minIntTable_request;
	uint tcapOmTc15minIntTable_refs;
	ulong tcapApplicationEntityId;
	long tcapOmInterval;
	long tcapOmTc15minIntPabortRecvUnrecTid;
	long tcapOmTc15minIntPabortRecvResourceLim;
	long tcapOmTc15minIntRejectRecvResourceLim;
	long tcapOmTc15minIntPabortSentUnrecTid;
	long tcapOmTc15minIntPabortSentResourceLim;
	long tcapOmTc15minIntRejectSentResourceLim;
	long tcapOmTc15minIntTcUserCancel;
	long tcapOmTc15minIntMessagesDiscarded;
	long tcapOmTc15minIntNotUsed;
	long tcapOmTc15minIntPabortsReceived;
	long tcapOmTc15minIntTcUserRejectsReceived;
	long tcapOmTc15minIntTpErrors;
};
struct tcapOmDevelRecvTable_data {
	uint tcapOmDevelRecvTable_request;
	uint tcapOmDevelRecvTable_refs;
	ulong tcapApplicationEntityId;
	long tcapOmDevelRecvPabortMessageType;
	long tcapOmDevelRecvPabortIncorrectTp;
	long tcapOmDevelRecvPabortBadTp;
	long tcapOmDevelRecvRejectUnrecComp;
	long tcapOmDevelRecvRejectMistypeComp;
	long tcapOmDevelRecvRejectBadCompStruct;
	long tcapOmDevelRecvRejectUnrecLinkId;
	long tcapOmDevelRecvRejectUnrecIdRetRes;
	long tcapOmDevelRecvRejectUnexpRetRes;
	long tcapOmDevelRecvRejectUnrecIdRetErr;
	long tcapOmDevelRecvRejectUnexpRetErr;
	long tcapOmDevelRecvUsrRejDupInvokeId;
	long tcapOmDevelRecvUsrRejUnrecOper;
	long tcapOmDevelRecvUsrRejParmInvoke;
	long tcapOmDevelRecvUsrRejReleasing;
	long tcapOmDevelRecvUsrRejUnexpLinkResp;
	long tcapOmDevelRecvUsrRejUnexpLinkOper;
	long tcapOmDevelRecvUsrRejUnrecError;
	long tcapOmDevelRecvUsrRejUnexpError;
	long tcapOmDevelRecvUsrRejParmRetResult;
	long tcapOmDevelRecvUsrRejParmRetError;
	long tcapOmDevelRecv5minValidIntervals;
	long tcapOmDevelRecv15minValidIntervals;
};
struct tcapOmDevelRecvCurrentTable_data {
	uint tcapOmDevelRecvCurrentTable_request;
	uint tcapOmDevelRecvCurrentTable_refs;
	ulong tcapApplicationEntityId;
	long tcapOmDevelRecvCurrentPabortMessageType;
	long tcapOmDevelRecvCurrentPabortIncorrectTp;
	long tcapOmDevelRecvCurrentPabortBadTp;
	long tcapOmDevelRecvCurrentRejectUnrecComp;
	long tcapOmDevelRecvCurrentRejectMistypeComp;
	long tcapOmDevelRecvCurrentRejectBadCompStruct;
	long tcapOmDevelRecvCurrentRejectUnrecLinkId;
	long tcapOmDevelRecvCurrentRejectUnrecIdRetRes;
	long tcapOmDevelRecvCurrentRejectUnexpRetRes;
	long tcapOmDevelRecvCurrentRejectUnrecIdRetErr;
	long tcapOmDevelRecvCurrentRejectUnexpRetErr;
	long tcapOmDevelRecvCurrentUsrRejDupInvokeId;
	long tcapOmDevelRecvCurrentUsrRejUnrecOper;
	long tcapOmDevelRecvCurrentUsrRejParmInvoke;
	long tcapOmDevelRecvCurrentUsrRejReleasing;
	long tcapOmDevelRecvCurrentUsrRejUnexpLinkResp;
	long tcapOmDevelRecvCurrentUsrRejUnexpLinkOper;
	long tcapOmDevelRecvCurrentUsrRejUnrecError;
	long tcapOmDevelRecvCurrentUsrRejUnexpError;
	long tcapOmDevelRecvCurrentUsrRejParmRetResult;
	long tcapOmDevelRecvCurrentUsrRejParmRetError;
};
struct tcapOmDevelRecv5minIntTable_data {
	uint tcapOmDevelRecv5minIntTable_request;
	uint tcapOmDevelRecv5minIntTable_refs;
	ulong tcapApplicationEntityId;
	long tcapOmInterval;
	long tcapOmDevelRecv5minIntPabortMessageType;
	long tcapOmDevelRecv5minIntPabortIncorrectTp;
	long tcapOmDevelRecv5minIntPabortBadTp;
	long tcapOmDevelRecv5minIntRejectUnrecComp;
	long tcapOmDevelRecv5minIntRejectMistypeComp;
	long tcapOmDevelRecv5minIntRejectBadCompStruct;
	long tcapOmDevelRecv5minIntRejectUnrecLinkId;
	long tcapOmDevelRecv5minIntRejectUnrecIdRetRes;
	long tcapOmDevelRecv5minIntRejectUnexpRetRes;
	long tcapOmDevelRecv5minIntRejectUnrecIdRetErr;
	long tcapOmDevelRecv5minIntRejectUnexpRetErr;
	long tcapOmDevelRecv5minIntUsrRejDupInvokeId;
	long tcapOmDevelRecv5minIntUsrRejUnrecOper;
	long tcapOmDevelRecv5minIntUsrRejParmInvoke;
	long tcapOmDevelRecv5minIntUsrRejReleasing;
	long tcapOmDevelRecv5minIntUsrRejUnexpLinkResp;
	long tcapOmDevelRecv5minIntUsrRejUnexpLinkOper;
	long tcapOmDevelRecv5minIntUsrRejUnrecError;
	long tcapOmDevelRecv5minIntUsrRejUnexpError;
	long tcapOmDevelRecv5minIntUsrRejParmRetResult;
	long tcapOmDevelRecv5minIntUsrRejParmRetError;
};
struct tcapOmDevelRecv15minIntTable_data {
	uint tcapOmDevelRecv15minIntTable_request;
	uint tcapOmDevelRecv15minIntTable_refs;
	ulong tcapApplicationEntityId;
	long tcapOmInterval;
	long tcapOmDevelRecv15minIntPabortMessageType;
	long tcapOmDevelRecv15minIntPabortIncorrectTp;
	long tcapOmDevelRecv15minIntPabortBadTp;
	long tcapOmDevelRecv15minIntRejectUnrecComp;
	long tcapOmDevelRecv15minIntRejectMistypeComp;
	long tcapOmDevelRecv15minIntRejectBadCompStruct;
	long tcapOmDevelRecv15minIntRejectUnrecLinkId;
	long tcapOmDevelRecv15minIntRejectUnrecIdRetRes;
	long tcapOmDevelRecv15minIntRejectUnexpRetRes;
	long tcapOmDevelRecv15minIntRejectUnrecIdRetErr;
	long tcapOmDevelRecv15minIntRejectUnexpRetErr;
	long tcapOmDevelRecv15minIntUsrRejDupInvokeId;
	long tcapOmDevelRecv15minIntUsrRejUnrecOper;
	long tcapOmDevelRecv15minIntUsrRejParmInvoke;
	long tcapOmDevelRecv15minIntUsrRejReleasing;
	long tcapOmDevelRecv15minIntUsrRejUnexpLinkResp;
	long tcapOmDevelRecv15minIntUsrRejUnexpLinkOper;
	long tcapOmDevelRecv15minIntUsrRejUnrecError;
	long tcapOmDevelRecv15minIntUsrRejUnexpError;
	long tcapOmDevelRecv15minIntUsrRejParmRetResult;
	long tcapOmDevelRecv15minIntUsrRejParmRetError;
};
struct tcapOmDevelSentTable_data {
	uint tcapOmDevelSentTable_request;
	uint tcapOmDevelSentTable_refs;
	ulong tcapTcUserId;
	long tcapOmDevelSentPabortMessageType;
	long tcapOmDevelSentPabortIncorrectTp;
	long tcapOmDevelSentPabortBadTp;
	long tcapOmDevelSentRejectUnrecComp;
	long tcapOmDevelSentRejectMistypeComp;
	long tcapOmDevelSentRejectBadCompStruct;
	long tcapOmDevelSentRejectUnrecLinkId;
	long tcapOmDevelSentRejectUnrecIdRetRes;
	long tcapOmDevelSentRejectUnexpRetRes;
	long tcapOmDevelSentRejectUnrecIdRetErr;
	long tcapOmDevelSentRejectUnexpRetErr;
	long tcapOmDevelSentUsrRejDupInvokeId;
	long tcapOmDevelSentUsrRejUnrecOper;
	long tcapOmDevelSentUsrRejParmInvoke;
	long tcapOmDevelSentUsrRejReleasing;
	long tcapOmDevelSentUsrRejUnexpLinkResp;
	long tcapOmDevelSentUsrRejUnexpLinkOper;
	long tcapOmDevelSentUsrRejUnrecError;
	long tcapOmDevelSentUsrRejUnexpError;
	long tcapOmDevelSentUsrRejParmRetResult;
	long tcapOmDevelSentUsrRejParmRetError;
	long tcapOmDevelSent5minValidIntervals;
	long tcapOmDevelSent15minValidIntervals;
};
struct tcapOmDevelSentCurrentTable_data {
	uint tcapOmDevelSentCurrentTable_request;
	uint tcapOmDevelSentCurrentTable_refs;
	ulong tcapTcUserId;
	long tcapOmDevelSentCurrentPabortMessageType;
	long tcapOmDevelSentCurrentPabortIncorrectTp;
	long tcapOmDevelSentCurrentPabortBadTp;
	long tcapOmDevelSentCurrentRejectUnrecComp;
	long tcapOmDevelSentCurrentRejectMistypeComp;
	long tcapOmDevelSentCurrentRejectBadCompStruct;
	long tcapOmDevelSentCurrentRejectUnrecLinkId;
	long tcapOmDevelSentCurrentRejectUnrecIdRetRes;
	long tcapOmDevelSentCurrentRejectUnexpRetRes;
	long tcapOmDevelSentCurrentRejectUnrecIdRetErr;
	long tcapOmDevelSentCurrentRejectUnexpRetErr;
	long tcapOmDevelSentCurrentUsrRejDupInvokeId;
	long tcapOmDevelSentCurrentUsrRejUnrecOper;
	long tcapOmDevelSentCurrentUsrRejParmInvoke;
	long tcapOmDevelSentCurrentUsrRejReleasing;
	long tcapOmDevelSentCurrentUsrRejUnexpLinkResp;
	long tcapOmDevelSentCurrentUsrRejUnexpLinkOper;
	long tcapOmDevelSentCurrentUsrRejUnrecError;
	long tcapOmDevelSentCurrentUsrRejUnexpError;
	long tcapOmDevelSentCurrentUsrRejParmRetResult;
	long tcapOmDevelSentCurrentUsrRejParmRetError;
};
struct tcapOmDevelSent5minIntTable_data {
	uint tcapOmDevelSent5minIntTable_request;
	uint tcapOmDevelSent5minIntTable_refs;
	ulong tcapTcUserId;
	long tcapOmInterval;
	long tcapOmDevelSent5minIntPabortMessageType;
	long tcapOmDevelSent5minIntPabortIncorrectTp;
	long tcapOmDevelSent5minIntPabortBadTp;
	long tcapOmDevelSent5minIntRejectUnrecComp;
	long tcapOmDevelSent5minIntRejectMistypeComp;
	long tcapOmDevelSent5minIntRejectBadCompStruct;
	long tcapOmDevelSent5minIntRejectUnrecLinkId;
	long tcapOmDevelSent5minIntRejectUnrecIdRetRes;
	long tcapOmDevelSent5minIntRejectUnexpRetRes;
	long tcapOmDevelSent5minIntRejectUnrecIdRetErr;
	long tcapOmDevelSent5minIntRejectUnexpRetErr;
	long tcapOmDevelSent5minIntUsrRejDupInvokeId;
	long tcapOmDevelSent5minIntUsrRejUnrecOper;
	long tcapOmDevelSent5minIntUsrRejParmInvoke;
	long tcapOmDevelSent5minIntUsrRejReleasing;
	long tcapOmDevelSent5minIntUsrRejUnexpLinkResp;
	long tcapOmDevelSent5minIntUsrRejUnexpLinkOper;
	long tcapOmDevelSent5minIntUsrRejUnrecError;
	long tcapOmDevelSent5minIntUsrRejUnexpError;
	long tcapOmDevelSent5minIntUsrRejParmRetResult;
	long tcapOmDevelSent5minIntUsrRejParmRetError;
};
struct tcapOmDevelSent15minIntTable_data {
	uint tcapOmDevelSent15minIntTable_request;
	uint tcapOmDevelSent15minIntTable_refs;
	ulong tcapTcUserId;
	long tcapOmInterval;
	long tcapOmDevelSent15minIntPabortMessageType;
	long tcapOmDevelSent15minIntPabortIncorrectTp;
	long tcapOmDevelSent15minIntPabortBadTp;
	long tcapOmDevelSent15minIntRejectUnrecComp;
	long tcapOmDevelSent15minIntRejectMistypeComp;
	long tcapOmDevelSent15minIntRejectBadCompStruct;
	long tcapOmDevelSent15minIntRejectUnrecLinkId;
	long tcapOmDevelSent15minIntRejectUnrecIdRetRes;
	long tcapOmDevelSent15minIntRejectUnexpRetRes;
	long tcapOmDevelSent15minIntRejectUnrecIdRetErr;
	long tcapOmDevelSent15minIntRejectUnexpRetErr;
	long tcapOmDevelSent15minIntUsrRejDupInvokeId;
	long tcapOmDevelSent15minIntUsrRejUnrecOper;
	long tcapOmDevelSent15minIntUsrRejParmInvoke;
	long tcapOmDevelSent15minIntUsrRejReleasing;
	long tcapOmDevelSent15minIntUsrRejUnexpLinkResp;
	long tcapOmDevelSent15minIntUsrRejUnexpLinkOper;
	long tcapOmDevelSent15minIntUsrRejUnrecError;
	long tcapOmDevelSent15minIntUsrRejUnexpError;
	long tcapOmDevelSent15minIntUsrRejParmRetResult;
	long tcapOmDevelSent15minIntUsrRejParmRetError;
};

/* storage declarations */
extern struct tcapOmMIB_data *tcapOmMIBStorage;
extern struct header_complex_index *tcapOmNodeTableStorage;
extern struct header_complex_index *tcapOmNodeCurrentTableStorage;
extern struct header_complex_index *tcapOmNode5minIntTableStorage;
extern struct header_complex_index *tcapOmNode15minIntTableStorage;
extern struct header_complex_index *tcapOmMsgsTableStorage;
extern struct header_complex_index *tcapOmMsgsCurrentTableStorage;
extern struct header_complex_index *tcapOmMsgs5minIntTableStorage;
extern struct header_complex_index *tcapOmMsgs15minIntTableStorage;
extern struct header_complex_index *tcapOmAETableStorage;
extern struct header_complex_index *tcapOmAECurrentTableStorage;
extern struct header_complex_index *tcapOmAE5minIntTableStorage;
extern struct header_complex_index *tcapOmAE15minIntTableStorage;
extern struct header_complex_index *tcapOmTcTableStorage;
extern struct header_complex_index *tcapOmTcCurrentTableStorage;
extern struct header_complex_index *tcapOmTc5minIntTableStorage;
extern struct header_complex_index *tcapOmTc15minIntTableStorage;
extern struct header_complex_index *tcapOmDevelRecvTableStorage;
extern struct header_complex_index *tcapOmDevelRecvCurrentTableStorage;
extern struct header_complex_index *tcapOmDevelRecv5minIntTableStorage;
extern struct header_complex_index *tcapOmDevelRecv15minIntTableStorage;
extern struct header_complex_index *tcapOmDevelSentTableStorage;
extern struct header_complex_index *tcapOmDevelSentCurrentTableStorage;
extern struct header_complex_index *tcapOmDevelSent5minIntTableStorage;
extern struct header_complex_index *tcapOmDevelSent15minIntTableStorage;

/* enum definitions from the covered mib sections */

/* notifications */

/* scalars accessible only for notify */
extern oid tcapOmMessageType_oid[12];

/* object id definitions */

/* function prototypes */
void init_tcapOmMIB(void);
void deinit_tcapOmMIB(void);
int term_tcapOmMIB(int majorID, int minorID, void *serverarg, void *clientarg);
FindVarMethod var_tcapOmMIB;
void parse_tcapOmMIB(const char *, char *);
SNMPCallback store_tcapOmMIB;
void refresh_tcapOmMIB(void);
FindVarMethod var_tcapOmNodeTable;
struct tcapOmNodeTable_data *tcapOmNodeTable_create(void);
int tcapOmNodeTable_destroy(struct tcapOmNodeTable_data **);
int tcapOmNodeTable_add(struct tcapOmNodeTable_data *);
int tcapOmNodeTable_del(struct tcapOmNodeTable_data *);
void parse_tcapOmNodeTable(const char *, char *);
SNMPCallback store_tcapOmNodeTable;
void refresh_tcapOmNodeTable(void);
FindVarMethod var_tcapOmNodeCurrentTable;
struct tcapOmNodeCurrentTable_data *tcapOmNodeCurrentTable_create(void);
int tcapOmNodeCurrentTable_destroy(struct tcapOmNodeCurrentTable_data **);
int tcapOmNodeCurrentTable_add(struct tcapOmNodeCurrentTable_data *);
int tcapOmNodeCurrentTable_del(struct tcapOmNodeCurrentTable_data *);
void parse_tcapOmNodeCurrentTable(const char *, char *);
SNMPCallback store_tcapOmNodeCurrentTable;
void refresh_tcapOmNodeCurrentTable(void);
FindVarMethod var_tcapOmNode5minIntTable;
struct tcapOmNode5minIntTable_data *tcapOmNode5minIntTable_create(void);
int tcapOmNode5minIntTable_destroy(struct tcapOmNode5minIntTable_data **);
int tcapOmNode5minIntTable_add(struct tcapOmNode5minIntTable_data *);
int tcapOmNode5minIntTable_del(struct tcapOmNode5minIntTable_data *);
void parse_tcapOmNode5minIntTable(const char *, char *);
SNMPCallback store_tcapOmNode5minIntTable;
void refresh_tcapOmNode5minIntTable(void);
FindVarMethod var_tcapOmNode15minIntTable;
struct tcapOmNode15minIntTable_data *tcapOmNode15minIntTable_create(void);
int tcapOmNode15minIntTable_destroy(struct tcapOmNode15minIntTable_data **);
int tcapOmNode15minIntTable_add(struct tcapOmNode15minIntTable_data *);
int tcapOmNode15minIntTable_del(struct tcapOmNode15minIntTable_data *);
void parse_tcapOmNode15minIntTable(const char *, char *);
SNMPCallback store_tcapOmNode15minIntTable;
void refresh_tcapOmNode15minIntTable(void);
FindVarMethod var_tcapOmMsgsTable;
struct tcapOmMsgsTable_data *tcapOmMsgsTable_create(void);
int tcapOmMsgsTable_destroy(struct tcapOmMsgsTable_data **);
int tcapOmMsgsTable_add(struct tcapOmMsgsTable_data *);
int tcapOmMsgsTable_del(struct tcapOmMsgsTable_data *);
void parse_tcapOmMsgsTable(const char *, char *);
SNMPCallback store_tcapOmMsgsTable;
void refresh_tcapOmMsgsTable(void);
FindVarMethod var_tcapOmMsgsCurrentTable;
struct tcapOmMsgsCurrentTable_data *tcapOmMsgsCurrentTable_create(void);
int tcapOmMsgsCurrentTable_destroy(struct tcapOmMsgsCurrentTable_data **);
int tcapOmMsgsCurrentTable_add(struct tcapOmMsgsCurrentTable_data *);
int tcapOmMsgsCurrentTable_del(struct tcapOmMsgsCurrentTable_data *);
void parse_tcapOmMsgsCurrentTable(const char *, char *);
SNMPCallback store_tcapOmMsgsCurrentTable;
void refresh_tcapOmMsgsCurrentTable(void);
FindVarMethod var_tcapOmMsgs5minIntTable;
struct tcapOmMsgs5minIntTable_data *tcapOmMsgs5minIntTable_create(void);
int tcapOmMsgs5minIntTable_destroy(struct tcapOmMsgs5minIntTable_data **);
int tcapOmMsgs5minIntTable_add(struct tcapOmMsgs5minIntTable_data *);
int tcapOmMsgs5minIntTable_del(struct tcapOmMsgs5minIntTable_data *);
void parse_tcapOmMsgs5minIntTable(const char *, char *);
SNMPCallback store_tcapOmMsgs5minIntTable;
void refresh_tcapOmMsgs5minIntTable(void);
FindVarMethod var_tcapOmMsgs15minIntTable;
struct tcapOmMsgs15minIntTable_data *tcapOmMsgs15minIntTable_create(void);
int tcapOmMsgs15minIntTable_destroy(struct tcapOmMsgs15minIntTable_data **);
int tcapOmMsgs15minIntTable_add(struct tcapOmMsgs15minIntTable_data *);
int tcapOmMsgs15minIntTable_del(struct tcapOmMsgs15minIntTable_data *);
void parse_tcapOmMsgs15minIntTable(const char *, char *);
SNMPCallback store_tcapOmMsgs15minIntTable;
void refresh_tcapOmMsgs15minIntTable(void);
FindVarMethod var_tcapOmAETable;
struct tcapOmAETable_data *tcapOmAETable_create(void);
int tcapOmAETable_destroy(struct tcapOmAETable_data **);
int tcapOmAETable_add(struct tcapOmAETable_data *);
int tcapOmAETable_del(struct tcapOmAETable_data *);
void parse_tcapOmAETable(const char *, char *);
SNMPCallback store_tcapOmAETable;
void refresh_tcapOmAETable(void);
FindVarMethod var_tcapOmAECurrentTable;
struct tcapOmAECurrentTable_data *tcapOmAECurrentTable_create(void);
int tcapOmAECurrentTable_destroy(struct tcapOmAECurrentTable_data **);
int tcapOmAECurrentTable_add(struct tcapOmAECurrentTable_data *);
int tcapOmAECurrentTable_del(struct tcapOmAECurrentTable_data *);
void parse_tcapOmAECurrentTable(const char *, char *);
SNMPCallback store_tcapOmAECurrentTable;
void refresh_tcapOmAECurrentTable(void);
FindVarMethod var_tcapOmAE5minIntTable;
struct tcapOmAE5minIntTable_data *tcapOmAE5minIntTable_create(void);
int tcapOmAE5minIntTable_destroy(struct tcapOmAE5minIntTable_data **);
int tcapOmAE5minIntTable_add(struct tcapOmAE5minIntTable_data *);
int tcapOmAE5minIntTable_del(struct tcapOmAE5minIntTable_data *);
void parse_tcapOmAE5minIntTable(const char *, char *);
SNMPCallback store_tcapOmAE5minIntTable;
void refresh_tcapOmAE5minIntTable(void);
FindVarMethod var_tcapOmAE15minIntTable;
struct tcapOmAE15minIntTable_data *tcapOmAE15minIntTable_create(void);
int tcapOmAE15minIntTable_destroy(struct tcapOmAE15minIntTable_data **);
int tcapOmAE15minIntTable_add(struct tcapOmAE15minIntTable_data *);
int tcapOmAE15minIntTable_del(struct tcapOmAE15minIntTable_data *);
void parse_tcapOmAE15minIntTable(const char *, char *);
SNMPCallback store_tcapOmAE15minIntTable;
void refresh_tcapOmAE15minIntTable(void);
FindVarMethod var_tcapOmTcTable;
struct tcapOmTcTable_data *tcapOmTcTable_create(void);
int tcapOmTcTable_destroy(struct tcapOmTcTable_data **);
int tcapOmTcTable_add(struct tcapOmTcTable_data *);
int tcapOmTcTable_del(struct tcapOmTcTable_data *);
void parse_tcapOmTcTable(const char *, char *);
SNMPCallback store_tcapOmTcTable;
void refresh_tcapOmTcTable(void);
FindVarMethod var_tcapOmTcCurrentTable;
struct tcapOmTcCurrentTable_data *tcapOmTcCurrentTable_create(void);
int tcapOmTcCurrentTable_destroy(struct tcapOmTcCurrentTable_data **);
int tcapOmTcCurrentTable_add(struct tcapOmTcCurrentTable_data *);
int tcapOmTcCurrentTable_del(struct tcapOmTcCurrentTable_data *);
void parse_tcapOmTcCurrentTable(const char *, char *);
SNMPCallback store_tcapOmTcCurrentTable;
void refresh_tcapOmTcCurrentTable(void);
FindVarMethod var_tcapOmTc5minIntTable;
struct tcapOmTc5minIntTable_data *tcapOmTc5minIntTable_create(void);
int tcapOmTc5minIntTable_destroy(struct tcapOmTc5minIntTable_data **);
int tcapOmTc5minIntTable_add(struct tcapOmTc5minIntTable_data *);
int tcapOmTc5minIntTable_del(struct tcapOmTc5minIntTable_data *);
void parse_tcapOmTc5minIntTable(const char *, char *);
SNMPCallback store_tcapOmTc5minIntTable;
void refresh_tcapOmTc5minIntTable(void);
FindVarMethod var_tcapOmTc15minIntTable;
struct tcapOmTc15minIntTable_data *tcapOmTc15minIntTable_create(void);
int tcapOmTc15minIntTable_destroy(struct tcapOmTc15minIntTable_data **);
int tcapOmTc15minIntTable_add(struct tcapOmTc15minIntTable_data *);
int tcapOmTc15minIntTable_del(struct tcapOmTc15minIntTable_data *);
void parse_tcapOmTc15minIntTable(const char *, char *);
SNMPCallback store_tcapOmTc15minIntTable;
void refresh_tcapOmTc15minIntTable(void);
FindVarMethod var_tcapOmDevelRecvTable;
struct tcapOmDevelRecvTable_data *tcapOmDevelRecvTable_create(void);
int tcapOmDevelRecvTable_destroy(struct tcapOmDevelRecvTable_data **);
int tcapOmDevelRecvTable_add(struct tcapOmDevelRecvTable_data *);
int tcapOmDevelRecvTable_del(struct tcapOmDevelRecvTable_data *);
void parse_tcapOmDevelRecvTable(const char *, char *);
SNMPCallback store_tcapOmDevelRecvTable;
void refresh_tcapOmDevelRecvTable(void);
FindVarMethod var_tcapOmDevelRecvCurrentTable;
struct tcapOmDevelRecvCurrentTable_data *tcapOmDevelRecvCurrentTable_create(void);
int tcapOmDevelRecvCurrentTable_destroy(struct tcapOmDevelRecvCurrentTable_data **);
int tcapOmDevelRecvCurrentTable_add(struct tcapOmDevelRecvCurrentTable_data *);
int tcapOmDevelRecvCurrentTable_del(struct tcapOmDevelRecvCurrentTable_data *);
void parse_tcapOmDevelRecvCurrentTable(const char *, char *);
SNMPCallback store_tcapOmDevelRecvCurrentTable;
void refresh_tcapOmDevelRecvCurrentTable(void);
FindVarMethod var_tcapOmDevelRecv5minIntTable;
struct tcapOmDevelRecv5minIntTable_data *tcapOmDevelRecv5minIntTable_create(void);
int tcapOmDevelRecv5minIntTable_destroy(struct tcapOmDevelRecv5minIntTable_data **);
int tcapOmDevelRecv5minIntTable_add(struct tcapOmDevelRecv5minIntTable_data *);
int tcapOmDevelRecv5minIntTable_del(struct tcapOmDevelRecv5minIntTable_data *);
void parse_tcapOmDevelRecv5minIntTable(const char *, char *);
SNMPCallback store_tcapOmDevelRecv5minIntTable;
void refresh_tcapOmDevelRecv5minIntTable(void);
FindVarMethod var_tcapOmDevelRecv15minIntTable;
struct tcapOmDevelRecv15minIntTable_data *tcapOmDevelRecv15minIntTable_create(void);
int tcapOmDevelRecv15minIntTable_destroy(struct tcapOmDevelRecv15minIntTable_data **);
int tcapOmDevelRecv15minIntTable_add(struct tcapOmDevelRecv15minIntTable_data *);
int tcapOmDevelRecv15minIntTable_del(struct tcapOmDevelRecv15minIntTable_data *);
void parse_tcapOmDevelRecv15minIntTable(const char *, char *);
SNMPCallback store_tcapOmDevelRecv15minIntTable;
void refresh_tcapOmDevelRecv15minIntTable(void);
FindVarMethod var_tcapOmDevelSentTable;
struct tcapOmDevelSentTable_data *tcapOmDevelSentTable_create(void);
int tcapOmDevelSentTable_destroy(struct tcapOmDevelSentTable_data **);
int tcapOmDevelSentTable_add(struct tcapOmDevelSentTable_data *);
int tcapOmDevelSentTable_del(struct tcapOmDevelSentTable_data *);
void parse_tcapOmDevelSentTable(const char *, char *);
SNMPCallback store_tcapOmDevelSentTable;
void refresh_tcapOmDevelSentTable(void);
FindVarMethod var_tcapOmDevelSentCurrentTable;
struct tcapOmDevelSentCurrentTable_data *tcapOmDevelSentCurrentTable_create(void);
int tcapOmDevelSentCurrentTable_destroy(struct tcapOmDevelSentCurrentTable_data **);
int tcapOmDevelSentCurrentTable_add(struct tcapOmDevelSentCurrentTable_data *);
int tcapOmDevelSentCurrentTable_del(struct tcapOmDevelSentCurrentTable_data *);
void parse_tcapOmDevelSentCurrentTable(const char *, char *);
SNMPCallback store_tcapOmDevelSentCurrentTable;
void refresh_tcapOmDevelSentCurrentTable(void);
FindVarMethod var_tcapOmDevelSent5minIntTable;
struct tcapOmDevelSent5minIntTable_data *tcapOmDevelSent5minIntTable_create(void);
int tcapOmDevelSent5minIntTable_destroy(struct tcapOmDevelSent5minIntTable_data **);
int tcapOmDevelSent5minIntTable_add(struct tcapOmDevelSent5minIntTable_data *);
int tcapOmDevelSent5minIntTable_del(struct tcapOmDevelSent5minIntTable_data *);
void parse_tcapOmDevelSent5minIntTable(const char *, char *);
SNMPCallback store_tcapOmDevelSent5minIntTable;
void refresh_tcapOmDevelSent5minIntTable(void);
FindVarMethod var_tcapOmDevelSent15minIntTable;
struct tcapOmDevelSent15minIntTable_data *tcapOmDevelSent15minIntTable_create(void);
int tcapOmDevelSent15minIntTable_destroy(struct tcapOmDevelSent15minIntTable_data **);
int tcapOmDevelSent15minIntTable_add(struct tcapOmDevelSent15minIntTable_data *);
int tcapOmDevelSent15minIntTable_del(struct tcapOmDevelSent15minIntTable_data *);
void parse_tcapOmDevelSent15minIntTable(const char *, char *);
SNMPCallback store_tcapOmDevelSent15minIntTable;
void refresh_tcapOmDevelSent15minIntTable(void);

WriteMethod write_tcapOm1stAndIntervalActivate;
WriteMethod write_tcapOm1stAndIntervalDeactivate;
WriteMethod write_tcapOm5MinActivate;
WriteMethod write_tcapOm5MinDeaActivate;
WriteMethod write_tcapOm15MinActivate;
WriteMethod write_tcapOm15MinDeaActivate;
WriteMethod write_tcapOm5MinMaxIntervals;
WriteMethod write_tcapOm15MinMaxIntervals;
#endif				/* __LOCAL_TCAPOMMIB_H__ */
