#ifndef __LOCAL_TCAPMIB_H__
#define __LOCAL_TCAPMIB_H__

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */

/* our storage structure(s) */

struct tcapMIB_data {
	unsigned int tcapMIB_request;
};

/* enum definitions from the covered mib sections */

/* function prototypes */

void init_tcapMIB(void);
void deinit_tcapMIB(void);
int term_tcapMIB(int majorID, int minorID, void *serverarg, void *clientarg);

FindVarMethod var_tcapMIB;
void parse_tcapMIB(const char *, char *);
SNMPCallback store_tcapMIB;
void refresh_tcapMIB(void);

#endif				/* __LOCAL_TCAPMIB_H__ */

