/*****************************************************************************

 @(#) $Id: tcapOmMIB.h,v 0.9.2.1 2008-12-31 16:09:08 brian Exp $

 -----------------------------------------------------------------------------

 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; version 3 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 -----------------------------------------------------------------------------

 Last Modified $Date: 2008-12-31 16:09:08 $ by $Author: brian $

 -----------------------------------------------------------------------------

 $Log: tcapOmMIB.h,v $
 Revision 0.9.2.1  2008-12-31 16:09:08  brian
 - added new mibs

 *****************************************************************************/

#ifndef __LOCAL_TCAPOMMIB_H__
#define __LOCAL_TCAPOMMIB_H__

#ident "@(#) $RCSfile: tcapOmMIB.h,v $ $Name: OpenSS7-0_9_2 $($Revision: 0.9.2.1 $) Copyright (c) 2001-2008 OpenSS7 Corporation."

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */
/* our storage structure(s) */
struct tcapOmMIB_data {
	uint tcapOmMIB_request;

	oid *tcapOm1stAndIntervalActivate;
	int tcapOm1stAndIntervalActivateLen;
	oid *tcapOm1stAndIntervalDeactivate;
	int tcapOm1stAndIntervalDeactivateLen;
	oid *tcapOm5MinActivate;
	int tcapOm5MinActivateLen;
	oid *tcapOm5MinDeaActivate;
	int tcapOm5MinDeaActivateLen;
	oid *tcapOm15MinActivate;
	int tcapOm15MinActivateLen;
	oid *tcapOm15MinDeaActivate;
	int tcapOm15MinDeaActivateLen;
	int32_t tcapOmInterval;
	int32_t tcapOmDiscontinuityTime;
	int32_t tcapOmTimeStamp;
	uint32_t tcapOm5MinMaxIntervals;
	uint32_t tcapOm15MinMaxIntervals;
};
struct tcapOmNodeTable_data {
	uint tcapOmNodeTable_request;
	uint tcapOmNodeTable_refs;
	uint32_t sccpNetworkEntityId;
	int32_t tcapOmNodeMessagesSent;
	int32_t tcapOmNodeMessagesRecv;
	int32_t tcapOmNodeComponentsSent;
	int32_t tcapOmNodeComponentsRecv;
	int32_t tcapOmNode5minValidIntervals;
	int32_t tcapOmNode15minValidIntervals;
};
struct tcapOmNodeCurrentTable_data {
	uint tcapOmNodeCurrentTable_request;
	uint tcapOmNodeCurrentTable_refs;
	uint32_t sccpNetworkEntityId;
	int32_t tcapOmNodeCurrentMessagesSent;
	int32_t tcapOmNodeCurrentMessagesRecv;
	int32_t tcapOmNodeCurrentComponentsSent;
	int32_t tcapOmNodeCurrentComponentsRecv;
};
struct tcapOmNode5minIntTable_data {
	uint tcapOmNode5minIntTable_request;
	uint tcapOmNode5minIntTable_refs;
	uint32_t sccpNetworkEntityId;
	int32_t tcapOmInterval;
	int32_t tcapOmNode5minIntMessagesSent;
	int32_t tcapOmNode5minIntMessagesRecv;
	int32_t tcapOmNode5minIntComponentsSent;
	int32_t tcapOmNode5minIntComponentsRecv;
};
struct tcapOmNode15minIntTable_data {
	uint tcapOmNode15minIntTable_request;
	uint tcapOmNode15minIntTable_refs;
	uint32_t sccpNetworkEntityId;
	int32_t tcapOmInterval;
	int32_t tcapOmNode15minIntMessagesSent;
	int32_t tcapOmNode15minIntMessagesRecv;
	int32_t tcapOmNode15minIntComponentsSent;
	int32_t tcapOmNode15minIntComponentsRecv;
};
struct tcapOmMsgsTable_data {
	uint tcapOmMsgsTable_request;
	uint tcapOmMsgsTable_refs;
	uint32_t sccpNetworkEntityId;
	int32_t tcapOmMsgsMessagesSent;
	int32_t tcapOmMsgsMessagesRecv;
	int32_t tcapOmMsgs5minValidIntervals;
	int32_t tcapOmMsgs15minValidIntervals;
};
struct tcapOmMsgsCurrentTable_data {
	uint tcapOmMsgsCurrentTable_request;
	uint tcapOmMsgsCurrentTable_refs;
	uint32_t sccpNetworkEntityId;
	int32_t tcapOmMsgsCurrentMessagesSent;
	int32_t tcapOmMsgsCurrentMessagesRecv;
};
struct tcapOmMsgs5minIntTable_data {
	uint tcapOmMsgs5minIntTable_request;
	uint tcapOmMsgs5minIntTable_refs;
	uint32_t sccpNetworkEntityId;
	int32_t tcapOmInterval;
	int32_t tcapOmMsgs5minIntMessagesSent;
	int32_t tcapOmMsgs5minIntMessagesRecv;
};
struct tcapOmMsgs15minIntTable_data {
	uint tcapOmMsgs15minIntTable_request;
	uint tcapOmMsgs15minIntTable_refs;
	uint32_t sccpNetworkEntityId;
	int32_t tcapOmInterval;
	int32_t tcapOmMsgs15minIntMessagesSent;
	int32_t tcapOmMsgs15minIntMessagesRecv;
};
struct tcapOmAETable_data {
	uint tcapOmAETable_request;
	uint tcapOmAETable_refs;
	uint32_t tcapApplicationEntityId;
	int32_t tcapOmAEMeasurementDeleted;
	int32_t tcapOmAENewTransactions;
	int32_t tcapOmAEMeanOpenTransactions;
	int32_t tcapOmAENotUsed;
	int32_t tcapOmAECummulativeMeanDuration;
	int32_t tcapOmAEMaximumOpenTranactions;
	int32_t tcapOmAEThresholdExceeded;
	int32_t tcapOmAE5minValidIntervals;
	int32_t tcapOmAE15minValidIntervals;
};
struct tcapOmAECurrentTable_data {
	uint tcapOmAECurrentTable_request;
	uint tcapOmAECurrentTable_refs;
	uint32_t tcapApplicationEntityId;
	int32_t tcapOmAECurrentMeasurementDeleted;
	int32_t tcapOmAECurrentNewTransactions;
	int32_t tcapOmAECurrentMeanOpenTransactions;
	int32_t tcapOmAECurrentNotUsed;
	int32_t tcapOmAECurrentCummulativeMeanDuration;
	int32_t tcapOmAECurrentMaximumOpenTranactions;
	int32_t tcapOmAECurrentThresholdExceeded;
};
struct tcapOmAE5minIntTable_data {
	uint tcapOmAE5minIntTable_request;
	uint tcapOmAE5minIntTable_refs;
	uint32_t tcapApplicationEntityId;
	int32_t tcapOmInterval;
	int32_t tcapOmAE5minIntMeasurementDeleted;
	int32_t tcapOmAE5minIntNewTransactions;
	int32_t tcapOmAE5minIntMeanOpenTransactions;
	int32_t tcapOmAE5minIntNotUsed;
	int32_t tcapOmAE5minIntCummulativeMeanDuration;
	int32_t tcapOmAE5minIntMaximumOpenTranactions;
	int32_t tcapOmAE5minIntThresholdExceeded;
};
struct tcapOmAE15minIntTable_data {
	uint tcapOmAE15minIntTable_request;
	uint tcapOmAE15minIntTable_refs;
	uint32_t tcapApplicationEntityId;
	int32_t tcapOmInterval;
	int32_t tcapOmAE15minIntMeasurementDeleted;
	int32_t tcapOmAE15minIntNewTransactions;
	int32_t tcapOmAE15minIntMeanOpenTransactions;
	int32_t tcapOmAE15minIntNotUsed;
	int32_t tcapOmAE15minIntCummulativeMeanDuration;
	int32_t tcapOmAE15minIntMaximumOpenTranactions;
	int32_t tcapOmAE15minIntThresholdExceeded;
};
struct tcapOmTcTable_data {
	uint tcapOmTcTable_request;
	uint tcapOmTcTable_refs;
	uint32_t tcapApplicationEntityId;
	int32_t tcapOmTcPabortRecvUnrecTid;
	int32_t tcapOmTcPabortRecvResourceLim;
	int32_t tcapOmTcRejectRecvResourceLim;
	int32_t tcapOmTcPabortSentUnrecTid;
	int32_t tcapOmTcPabortSentResourceLim;
	int32_t tcapOmTcRejectSentResourceLim;
	int32_t tcapOmTcTcUserCancel;
	int32_t tcapOmTcMessagesDiscarded;
	int32_t tcapOmTcNotUsed;
	int32_t tcapOmTcPabortsReceived;
	int32_t tcapOmTcTcUserRejectsReceived;
	int32_t tcapOmTcTpErrors;
	int32_t tcapOmTc5minValidIntervals;
	int32_t tcapOmTc15minValidIntervals;
};
struct tcapOmTcCurrentTable_data {
	uint tcapOmTcCurrentTable_request;
	uint tcapOmTcCurrentTable_refs;
	uint32_t tcapApplicationEntityId;
	int32_t tcapOmTcCurrentPabortRecvUnrecTid;
	int32_t tcapOmTcCurrentPabortRecvResourceLim;
	int32_t tcapOmTcCurrentRejectRecvResourceLim;
	int32_t tcapOmTcCurrentPabortSentUnrecTid;
	int32_t tcapOmTcCurrentPabortSentResourceLim;
	int32_t tcapOmTcCurrentRejectSentResourceLim;
	int32_t tcapOmTcCurrentTcUserCancel;
	int32_t tcapOmTcCurrentMessagesDiscarded;
	int32_t tcapOmTcCurrentNotUsed;
	int32_t tcapOmTcCurrentPabortsReceived;
	int32_t tcapOmTcCurrentTcUserRejectsReceived;
	int32_t tcapOmTcCurrentTpErrors;
};
struct tcapOmTc5minIntTable_data {
	uint tcapOmTc5minIntTable_request;
	uint tcapOmTc5minIntTable_refs;
	uint32_t tcapApplicationEntityId;
	int32_t tcapOmInterval;
	int32_t tcapOmTc5minIntPabortRecvUnrecTid;
	int32_t tcapOmTc5minIntPabortRecvResourceLim;
	int32_t tcapOmTc5minIntRejectRecvResourceLim;
	int32_t tcapOmTc5minIntPabortSentUnrecTid;
	int32_t tcapOmTc5minIntPabortSentResourceLim;
	int32_t tcapOmTc5minIntRejectSentResourceLim;
	int32_t tcapOmTc5minIntTcUserCancel;
	int32_t tcapOmTc5minIntMessagesDiscarded;
	int32_t tcapOmTc5minIntNotUsed;
	int32_t tcapOmTc5minIntPabortsReceived;
	int32_t tcapOmTc5minIntTcUserRejectsReceived;
	int32_t tcapOmTc5minIntTpErrors;
};
struct tcapOmTc15minIntTable_data {
	uint tcapOmTc15minIntTable_request;
	uint tcapOmTc15minIntTable_refs;
	uint32_t tcapApplicationEntityId;
	int32_t tcapOmInterval;
	int32_t tcapOmTc15minIntPabortRecvUnrecTid;
	int32_t tcapOmTc15minIntPabortRecvResourceLim;
	int32_t tcapOmTc15minIntRejectRecvResourceLim;
	int32_t tcapOmTc15minIntPabortSentUnrecTid;
	int32_t tcapOmTc15minIntPabortSentResourceLim;
	int32_t tcapOmTc15minIntRejectSentResourceLim;
	int32_t tcapOmTc15minIntTcUserCancel;
	int32_t tcapOmTc15minIntMessagesDiscarded;
	int32_t tcapOmTc15minIntNotUsed;
	int32_t tcapOmTc15minIntPabortsReceived;
	int32_t tcapOmTc15minIntTcUserRejectsReceived;
	int32_t tcapOmTc15minIntTpErrors;
};
struct tcapOmDevelRecvTable_data {
	uint tcapOmDevelRecvTable_request;
	uint tcapOmDevelRecvTable_refs;
	uint32_t tcapApplicationEntityId;
	int32_t tcapOmDevelRecvPabortMessageType;
	int32_t tcapOmDevelRecvPabortIncorrectTp;
	int32_t tcapOmDevelRecvPabortBadTp;
	int32_t tcapOmDevelRecvRejectUnrecComp;
	int32_t tcapOmDevelRecvRejectMistypeComp;
	int32_t tcapOmDevelRecvRejectBadCompStruct;
	int32_t tcapOmDevelRecvRejectUnrecLinkId;
	int32_t tcapOmDevelRecvRejectUnrecIdRetRes;
	int32_t tcapOmDevelRecvRejectUnexpRetRes;
	int32_t tcapOmDevelRecvRejectUnrecIdRetErr;
	int32_t tcapOmDevelRecvRejectUnexpRetErr;
	int32_t tcapOmDevelRecvUsrRejDupInvokeId;
	int32_t tcapOmDevelRecvUsrRejUnrecOper;
	int32_t tcapOmDevelRecvUsrRejParmInvoke;
	int32_t tcapOmDevelRecvUsrRejReleasing;
	int32_t tcapOmDevelRecvUsrRejUnexpLinkResp;
	int32_t tcapOmDevelRecvUsrRejUnexpLinkOper;
	int32_t tcapOmDevelRecvUsrRejUnrecError;
	int32_t tcapOmDevelRecvUsrRejUnexpError;
	int32_t tcapOmDevelRecvUsrRejParmRetResult;
	int32_t tcapOmDevelRecvUsrRejParmRetError;
	int32_t tcapOmDevelRecv5minValidIntervals;
	int32_t tcapOmDevelRecv15minValidIntervals;
};
struct tcapOmDevelRecvCurrentTable_data {
	uint tcapOmDevelRecvCurrentTable_request;
	uint tcapOmDevelRecvCurrentTable_refs;
	uint32_t tcapApplicationEntityId;
	int32_t tcapOmDevelRecvCurrentPabortMessageType;
	int32_t tcapOmDevelRecvCurrentPabortIncorrectTp;
	int32_t tcapOmDevelRecvCurrentPabortBadTp;
	int32_t tcapOmDevelRecvCurrentRejectUnrecComp;
	int32_t tcapOmDevelRecvCurrentRejectMistypeComp;
	int32_t tcapOmDevelRecvCurrentRejectBadCompStruct;
	int32_t tcapOmDevelRecvCurrentRejectUnrecLinkId;
	int32_t tcapOmDevelRecvCurrentRejectUnrecIdRetRes;
	int32_t tcapOmDevelRecvCurrentRejectUnexpRetRes;
	int32_t tcapOmDevelRecvCurrentRejectUnrecIdRetErr;
	int32_t tcapOmDevelRecvCurrentRejectUnexpRetErr;
	int32_t tcapOmDevelRecvCurrentUsrRejDupInvokeId;
	int32_t tcapOmDevelRecvCurrentUsrRejUnrecOper;
	int32_t tcapOmDevelRecvCurrentUsrRejParmInvoke;
	int32_t tcapOmDevelRecvCurrentUsrRejReleasing;
	int32_t tcapOmDevelRecvCurrentUsrRejUnexpLinkResp;
	int32_t tcapOmDevelRecvCurrentUsrRejUnexpLinkOper;
	int32_t tcapOmDevelRecvCurrentUsrRejUnrecError;
	int32_t tcapOmDevelRecvCurrentUsrRejUnexpError;
	int32_t tcapOmDevelRecvCurrentUsrRejParmRetResult;
	int32_t tcapOmDevelRecvCurrentUsrRejParmRetError;
};
struct tcapOmDevelRecv5minIntTable_data {
	uint tcapOmDevelRecv5minIntTable_request;
	uint tcapOmDevelRecv5minIntTable_refs;
	uint32_t tcapApplicationEntityId;
	int32_t tcapOmInterval;
	int32_t tcapOmDevelRecv5minIntPabortMessageType;
	int32_t tcapOmDevelRecv5minIntPabortIncorrectTp;
	int32_t tcapOmDevelRecv5minIntPabortBadTp;
	int32_t tcapOmDevelRecv5minIntRejectUnrecComp;
	int32_t tcapOmDevelRecv5minIntRejectMistypeComp;
	int32_t tcapOmDevelRecv5minIntRejectBadCompStruct;
	int32_t tcapOmDevelRecv5minIntRejectUnrecLinkId;
	int32_t tcapOmDevelRecv5minIntRejectUnrecIdRetRes;
	int32_t tcapOmDevelRecv5minIntRejectUnexpRetRes;
	int32_t tcapOmDevelRecv5minIntRejectUnrecIdRetErr;
	int32_t tcapOmDevelRecv5minIntRejectUnexpRetErr;
	int32_t tcapOmDevelRecv5minIntUsrRejDupInvokeId;
	int32_t tcapOmDevelRecv5minIntUsrRejUnrecOper;
	int32_t tcapOmDevelRecv5minIntUsrRejParmInvoke;
	int32_t tcapOmDevelRecv5minIntUsrRejReleasing;
	int32_t tcapOmDevelRecv5minIntUsrRejUnexpLinkResp;
	int32_t tcapOmDevelRecv5minIntUsrRejUnexpLinkOper;
	int32_t tcapOmDevelRecv5minIntUsrRejUnrecError;
	int32_t tcapOmDevelRecv5minIntUsrRejUnexpError;
	int32_t tcapOmDevelRecv5minIntUsrRejParmRetResult;
	int32_t tcapOmDevelRecv5minIntUsrRejParmRetError;
};
struct tcapOmDevelRecv15minIntTable_data {
	uint tcapOmDevelRecv15minIntTable_request;
	uint tcapOmDevelRecv15minIntTable_refs;
	uint32_t tcapApplicationEntityId;
	int32_t tcapOmInterval;
	int32_t tcapOmDevelRecv15minIntPabortMessageType;
	int32_t tcapOmDevelRecv15minIntPabortIncorrectTp;
	int32_t tcapOmDevelRecv15minIntPabortBadTp;
	int32_t tcapOmDevelRecv15minIntRejectUnrecComp;
	int32_t tcapOmDevelRecv15minIntRejectMistypeComp;
	int32_t tcapOmDevelRecv15minIntRejectBadCompStruct;
	int32_t tcapOmDevelRecv15minIntRejectUnrecLinkId;
	int32_t tcapOmDevelRecv15minIntRejectUnrecIdRetRes;
	int32_t tcapOmDevelRecv15minIntRejectUnexpRetRes;
	int32_t tcapOmDevelRecv15minIntRejectUnrecIdRetErr;
	int32_t tcapOmDevelRecv15minIntRejectUnexpRetErr;
	int32_t tcapOmDevelRecv15minIntUsrRejDupInvokeId;
	int32_t tcapOmDevelRecv15minIntUsrRejUnrecOper;
	int32_t tcapOmDevelRecv15minIntUsrRejParmInvoke;
	int32_t tcapOmDevelRecv15minIntUsrRejReleasing;
	int32_t tcapOmDevelRecv15minIntUsrRejUnexpLinkResp;
	int32_t tcapOmDevelRecv15minIntUsrRejUnexpLinkOper;
	int32_t tcapOmDevelRecv15minIntUsrRejUnrecError;
	int32_t tcapOmDevelRecv15minIntUsrRejUnexpError;
	int32_t tcapOmDevelRecv15minIntUsrRejParmRetResult;
	int32_t tcapOmDevelRecv15minIntUsrRejParmRetError;
};
struct tcapOmDevelSentTable_data {
	uint tcapOmDevelSentTable_request;
	uint tcapOmDevelSentTable_refs;
	uint32_t tcapTcUserId;
	int32_t tcapOmDevelSentPabortMessageType;
	int32_t tcapOmDevelSentPabortIncorrectTp;
	int32_t tcapOmDevelSentPabortBadTp;
	int32_t tcapOmDevelSentRejectUnrecComp;
	int32_t tcapOmDevelSentRejectMistypeComp;
	int32_t tcapOmDevelSentRejectBadCompStruct;
	int32_t tcapOmDevelSentRejectUnrecLinkId;
	int32_t tcapOmDevelSentRejectUnrecIdRetRes;
	int32_t tcapOmDevelSentRejectUnexpRetRes;
	int32_t tcapOmDevelSentRejectUnrecIdRetErr;
	int32_t tcapOmDevelSentRejectUnexpRetErr;
	int32_t tcapOmDevelSentUsrRejDupInvokeId;
	int32_t tcapOmDevelSentUsrRejUnrecOper;
	int32_t tcapOmDevelSentUsrRejParmInvoke;
	int32_t tcapOmDevelSentUsrRejReleasing;
	int32_t tcapOmDevelSentUsrRejUnexpLinkResp;
	int32_t tcapOmDevelSentUsrRejUnexpLinkOper;
	int32_t tcapOmDevelSentUsrRejUnrecError;
	int32_t tcapOmDevelSentUsrRejUnexpError;
	int32_t tcapOmDevelSentUsrRejParmRetResult;
	int32_t tcapOmDevelSentUsrRejParmRetError;
	int32_t tcapOmDevelSent5minValidIntervals;
	int32_t tcapOmDevelSent15minValidIntervals;
};
struct tcapOmDevelSentCurrentTable_data {
	uint tcapOmDevelSentCurrentTable_request;
	uint tcapOmDevelSentCurrentTable_refs;
	uint32_t tcapTcUserId;
	int32_t tcapOmDevelSentCurrentPabortMessageType;
	int32_t tcapOmDevelSentCurrentPabortIncorrectTp;
	int32_t tcapOmDevelSentCurrentPabortBadTp;
	int32_t tcapOmDevelSentCurrentRejectUnrecComp;
	int32_t tcapOmDevelSentCurrentRejectMistypeComp;
	int32_t tcapOmDevelSentCurrentRejectBadCompStruct;
	int32_t tcapOmDevelSentCurrentRejectUnrecLinkId;
	int32_t tcapOmDevelSentCurrentRejectUnrecIdRetRes;
	int32_t tcapOmDevelSentCurrentRejectUnexpRetRes;
	int32_t tcapOmDevelSentCurrentRejectUnrecIdRetErr;
	int32_t tcapOmDevelSentCurrentRejectUnexpRetErr;
	int32_t tcapOmDevelSentCurrentUsrRejDupInvokeId;
	int32_t tcapOmDevelSentCurrentUsrRejUnrecOper;
	int32_t tcapOmDevelSentCurrentUsrRejParmInvoke;
	int32_t tcapOmDevelSentCurrentUsrRejReleasing;
	int32_t tcapOmDevelSentCurrentUsrRejUnexpLinkResp;
	int32_t tcapOmDevelSentCurrentUsrRejUnexpLinkOper;
	int32_t tcapOmDevelSentCurrentUsrRejUnrecError;
	int32_t tcapOmDevelSentCurrentUsrRejUnexpError;
	int32_t tcapOmDevelSentCurrentUsrRejParmRetResult;
	int32_t tcapOmDevelSentCurrentUsrRejParmRetError;
};
struct tcapOmDevelSent5minIntTable_data {
	uint tcapOmDevelSent5minIntTable_request;
	uint tcapOmDevelSent5minIntTable_refs;
	uint32_t tcapTcUserId;
	int32_t tcapOmInterval;
	int32_t tcapOmDevelSent5minIntPabortMessageType;
	int32_t tcapOmDevelSent5minIntPabortIncorrectTp;
	int32_t tcapOmDevelSent5minIntPabortBadTp;
	int32_t tcapOmDevelSent5minIntRejectUnrecComp;
	int32_t tcapOmDevelSent5minIntRejectMistypeComp;
	int32_t tcapOmDevelSent5minIntRejectBadCompStruct;
	int32_t tcapOmDevelSent5minIntRejectUnrecLinkId;
	int32_t tcapOmDevelSent5minIntRejectUnrecIdRetRes;
	int32_t tcapOmDevelSent5minIntRejectUnexpRetRes;
	int32_t tcapOmDevelSent5minIntRejectUnrecIdRetErr;
	int32_t tcapOmDevelSent5minIntRejectUnexpRetErr;
	int32_t tcapOmDevelSent5minIntUsrRejDupInvokeId;
	int32_t tcapOmDevelSent5minIntUsrRejUnrecOper;
	int32_t tcapOmDevelSent5minIntUsrRejParmInvoke;
	int32_t tcapOmDevelSent5minIntUsrRejReleasing;
	int32_t tcapOmDevelSent5minIntUsrRejUnexpLinkResp;
	int32_t tcapOmDevelSent5minIntUsrRejUnexpLinkOper;
	int32_t tcapOmDevelSent5minIntUsrRejUnrecError;
	int32_t tcapOmDevelSent5minIntUsrRejUnexpError;
	int32_t tcapOmDevelSent5minIntUsrRejParmRetResult;
	int32_t tcapOmDevelSent5minIntUsrRejParmRetError;
};
struct tcapOmDevelSent15minIntTable_data {
	uint tcapOmDevelSent15minIntTable_request;
	uint tcapOmDevelSent15minIntTable_refs;
	uint32_t tcapTcUserId;
	int32_t tcapOmInterval;
	int32_t tcapOmDevelSent15minIntPabortMessageType;
	int32_t tcapOmDevelSent15minIntPabortIncorrectTp;
	int32_t tcapOmDevelSent15minIntPabortBadTp;
	int32_t tcapOmDevelSent15minIntRejectUnrecComp;
	int32_t tcapOmDevelSent15minIntRejectMistypeComp;
	int32_t tcapOmDevelSent15minIntRejectBadCompStruct;
	int32_t tcapOmDevelSent15minIntRejectUnrecLinkId;
	int32_t tcapOmDevelSent15minIntRejectUnrecIdRetRes;
	int32_t tcapOmDevelSent15minIntRejectUnexpRetRes;
	int32_t tcapOmDevelSent15minIntRejectUnrecIdRetErr;
	int32_t tcapOmDevelSent15minIntRejectUnexpRetErr;
	int32_t tcapOmDevelSent15minIntUsrRejDupInvokeId;
	int32_t tcapOmDevelSent15minIntUsrRejUnrecOper;
	int32_t tcapOmDevelSent15minIntUsrRejParmInvoke;
	int32_t tcapOmDevelSent15minIntUsrRejReleasing;
	int32_t tcapOmDevelSent15minIntUsrRejUnexpLinkResp;
	int32_t tcapOmDevelSent15minIntUsrRejUnexpLinkOper;
	int32_t tcapOmDevelSent15minIntUsrRejUnrecError;
	int32_t tcapOmDevelSent15minIntUsrRejUnexpError;
	int32_t tcapOmDevelSent15minIntUsrRejParmRetResult;
	int32_t tcapOmDevelSent15minIntUsrRejParmRetError;
};

/* storage declarations */
extern struct tcapOmMIB_data *tcapOmMIBStorage;
extern struct header_complex_index *tcapOmNodeTableStorage;
extern struct header_complex_index *tcapOmNodeCurrentTableStorage;
extern struct header_complex_index *tcapOmNode5minIntTableStorage;
extern struct header_complex_index *tcapOmNode15minIntTableStorage;
extern struct header_complex_index *tcapOmMsgsTableStorage;
extern struct header_complex_index *tcapOmMsgsCurrentTableStorage;
extern struct header_complex_index *tcapOmMsgs5minIntTableStorage;
extern struct header_complex_index *tcapOmMsgs15minIntTableStorage;
extern struct header_complex_index *tcapOmAETableStorage;
extern struct header_complex_index *tcapOmAECurrentTableStorage;
extern struct header_complex_index *tcapOmAE5minIntTableStorage;
extern struct header_complex_index *tcapOmAE15minIntTableStorage;
extern struct header_complex_index *tcapOmTcTableStorage;
extern struct header_complex_index *tcapOmTcCurrentTableStorage;
extern struct header_complex_index *tcapOmTc5minIntTableStorage;
extern struct header_complex_index *tcapOmTc15minIntTableStorage;
extern struct header_complex_index *tcapOmDevelRecvTableStorage;
extern struct header_complex_index *tcapOmDevelRecvCurrentTableStorage;
extern struct header_complex_index *tcapOmDevelRecv5minIntTableStorage;
extern struct header_complex_index *tcapOmDevelRecv15minIntTableStorage;
extern struct header_complex_index *tcapOmDevelSentTableStorage;
extern struct header_complex_index *tcapOmDevelSentCurrentTableStorage;
extern struct header_complex_index *tcapOmDevelSent5minIntTableStorage;
extern struct header_complex_index *tcapOmDevelSent15minIntTableStorage;

/* enum definitions from the covered mib sections */

/* function prototypes */
void init_tcapOmMIB(void);
void deinit_tcapOmMIB(void);
int term_tcapOmMIB(int majorID, int minorID, void *serverarg, void *clientarg);
FindVarMethod var_tcapOmMIB;
void parse_tcapOmMIB(const char *, char *);
SNMPCallback store_tcapOmMIB;
void refresh_tcapOmMIB(void);
FindVarMethod var_tcapOmNodeTable;
int tcapOmNodeTable_add(struct tcapOmNodeTable_data *);
int tcapOmNodeTable_del(struct tcapOmNodeTable_data **);
void parse_tcapOmNodeTable(const char *, char *);
SNMPCallback store_tcapOmNodeTable;
void refresh_tcapOmNodeTable(void);
FindVarMethod var_tcapOmNodeCurrentTable;
int tcapOmNodeCurrentTable_add(struct tcapOmNodeCurrentTable_data *);
int tcapOmNodeCurrentTable_del(struct tcapOmNodeCurrentTable_data **);
void parse_tcapOmNodeCurrentTable(const char *, char *);
SNMPCallback store_tcapOmNodeCurrentTable;
void refresh_tcapOmNodeCurrentTable(void);
FindVarMethod var_tcapOmNode5minIntTable;
int tcapOmNode5minIntTable_add(struct tcapOmNode5minIntTable_data *);
int tcapOmNode5minIntTable_del(struct tcapOmNode5minIntTable_data **);
void parse_tcapOmNode5minIntTable(const char *, char *);
SNMPCallback store_tcapOmNode5minIntTable;
void refresh_tcapOmNode5minIntTable(void);
FindVarMethod var_tcapOmNode15minIntTable;
int tcapOmNode15minIntTable_add(struct tcapOmNode15minIntTable_data *);
int tcapOmNode15minIntTable_del(struct tcapOmNode15minIntTable_data **);
void parse_tcapOmNode15minIntTable(const char *, char *);
SNMPCallback store_tcapOmNode15minIntTable;
void refresh_tcapOmNode15minIntTable(void);
FindVarMethod var_tcapOmMsgsTable;
int tcapOmMsgsTable_add(struct tcapOmMsgsTable_data *);
int tcapOmMsgsTable_del(struct tcapOmMsgsTable_data **);
void parse_tcapOmMsgsTable(const char *, char *);
SNMPCallback store_tcapOmMsgsTable;
void refresh_tcapOmMsgsTable(void);
FindVarMethod var_tcapOmMsgsCurrentTable;
int tcapOmMsgsCurrentTable_add(struct tcapOmMsgsCurrentTable_data *);
int tcapOmMsgsCurrentTable_del(struct tcapOmMsgsCurrentTable_data **);
void parse_tcapOmMsgsCurrentTable(const char *, char *);
SNMPCallback store_tcapOmMsgsCurrentTable;
void refresh_tcapOmMsgsCurrentTable(void);
FindVarMethod var_tcapOmMsgs5minIntTable;
int tcapOmMsgs5minIntTable_add(struct tcapOmMsgs5minIntTable_data *);
int tcapOmMsgs5minIntTable_del(struct tcapOmMsgs5minIntTable_data **);
void parse_tcapOmMsgs5minIntTable(const char *, char *);
SNMPCallback store_tcapOmMsgs5minIntTable;
void refresh_tcapOmMsgs5minIntTable(void);
FindVarMethod var_tcapOmMsgs15minIntTable;
int tcapOmMsgs15minIntTable_add(struct tcapOmMsgs15minIntTable_data *);
int tcapOmMsgs15minIntTable_del(struct tcapOmMsgs15minIntTable_data **);
void parse_tcapOmMsgs15minIntTable(const char *, char *);
SNMPCallback store_tcapOmMsgs15minIntTable;
void refresh_tcapOmMsgs15minIntTable(void);
FindVarMethod var_tcapOmAETable;
int tcapOmAETable_add(struct tcapOmAETable_data *);
int tcapOmAETable_del(struct tcapOmAETable_data **);
void parse_tcapOmAETable(const char *, char *);
SNMPCallback store_tcapOmAETable;
void refresh_tcapOmAETable(void);
FindVarMethod var_tcapOmAECurrentTable;
int tcapOmAECurrentTable_add(struct tcapOmAECurrentTable_data *);
int tcapOmAECurrentTable_del(struct tcapOmAECurrentTable_data **);
void parse_tcapOmAECurrentTable(const char *, char *);
SNMPCallback store_tcapOmAECurrentTable;
void refresh_tcapOmAECurrentTable(void);
FindVarMethod var_tcapOmAE5minIntTable;
int tcapOmAE5minIntTable_add(struct tcapOmAE5minIntTable_data *);
int tcapOmAE5minIntTable_del(struct tcapOmAE5minIntTable_data **);
void parse_tcapOmAE5minIntTable(const char *, char *);
SNMPCallback store_tcapOmAE5minIntTable;
void refresh_tcapOmAE5minIntTable(void);
FindVarMethod var_tcapOmAE15minIntTable;
int tcapOmAE15minIntTable_add(struct tcapOmAE15minIntTable_data *);
int tcapOmAE15minIntTable_del(struct tcapOmAE15minIntTable_data **);
void parse_tcapOmAE15minIntTable(const char *, char *);
SNMPCallback store_tcapOmAE15minIntTable;
void refresh_tcapOmAE15minIntTable(void);
FindVarMethod var_tcapOmTcTable;
int tcapOmTcTable_add(struct tcapOmTcTable_data *);
int tcapOmTcTable_del(struct tcapOmTcTable_data **);
void parse_tcapOmTcTable(const char *, char *);
SNMPCallback store_tcapOmTcTable;
void refresh_tcapOmTcTable(void);
FindVarMethod var_tcapOmTcCurrentTable;
int tcapOmTcCurrentTable_add(struct tcapOmTcCurrentTable_data *);
int tcapOmTcCurrentTable_del(struct tcapOmTcCurrentTable_data **);
void parse_tcapOmTcCurrentTable(const char *, char *);
SNMPCallback store_tcapOmTcCurrentTable;
void refresh_tcapOmTcCurrentTable(void);
FindVarMethod var_tcapOmTc5minIntTable;
int tcapOmTc5minIntTable_add(struct tcapOmTc5minIntTable_data *);
int tcapOmTc5minIntTable_del(struct tcapOmTc5minIntTable_data **);
void parse_tcapOmTc5minIntTable(const char *, char *);
SNMPCallback store_tcapOmTc5minIntTable;
void refresh_tcapOmTc5minIntTable(void);
FindVarMethod var_tcapOmTc15minIntTable;
int tcapOmTc15minIntTable_add(struct tcapOmTc15minIntTable_data *);
int tcapOmTc15minIntTable_del(struct tcapOmTc15minIntTable_data **);
void parse_tcapOmTc15minIntTable(const char *, char *);
SNMPCallback store_tcapOmTc15minIntTable;
void refresh_tcapOmTc15minIntTable(void);
FindVarMethod var_tcapOmDevelRecvTable;
int tcapOmDevelRecvTable_add(struct tcapOmDevelRecvTable_data *);
int tcapOmDevelRecvTable_del(struct tcapOmDevelRecvTable_data **);
void parse_tcapOmDevelRecvTable(const char *, char *);
SNMPCallback store_tcapOmDevelRecvTable;
void refresh_tcapOmDevelRecvTable(void);
FindVarMethod var_tcapOmDevelRecvCurrentTable;
int tcapOmDevelRecvCurrentTable_add(struct tcapOmDevelRecvCurrentTable_data *);
int tcapOmDevelRecvCurrentTable_del(struct tcapOmDevelRecvCurrentTable_data **);
void parse_tcapOmDevelRecvCurrentTable(const char *, char *);
SNMPCallback store_tcapOmDevelRecvCurrentTable;
void refresh_tcapOmDevelRecvCurrentTable(void);
FindVarMethod var_tcapOmDevelRecv5minIntTable;
int tcapOmDevelRecv5minIntTable_add(struct tcapOmDevelRecv5minIntTable_data *);
int tcapOmDevelRecv5minIntTable_del(struct tcapOmDevelRecv5minIntTable_data **);
void parse_tcapOmDevelRecv5minIntTable(const char *, char *);
SNMPCallback store_tcapOmDevelRecv5minIntTable;
void refresh_tcapOmDevelRecv5minIntTable(void);
FindVarMethod var_tcapOmDevelRecv15minIntTable;
int tcapOmDevelRecv15minIntTable_add(struct tcapOmDevelRecv15minIntTable_data *);
int tcapOmDevelRecv15minIntTable_del(struct tcapOmDevelRecv15minIntTable_data **);
void parse_tcapOmDevelRecv15minIntTable(const char *, char *);
SNMPCallback store_tcapOmDevelRecv15minIntTable;
void refresh_tcapOmDevelRecv15minIntTable(void);
FindVarMethod var_tcapOmDevelSentTable;
int tcapOmDevelSentTable_add(struct tcapOmDevelSentTable_data *);
int tcapOmDevelSentTable_del(struct tcapOmDevelSentTable_data **);
void parse_tcapOmDevelSentTable(const char *, char *);
SNMPCallback store_tcapOmDevelSentTable;
void refresh_tcapOmDevelSentTable(void);
FindVarMethod var_tcapOmDevelSentCurrentTable;
int tcapOmDevelSentCurrentTable_add(struct tcapOmDevelSentCurrentTable_data *);
int tcapOmDevelSentCurrentTable_del(struct tcapOmDevelSentCurrentTable_data **);
void parse_tcapOmDevelSentCurrentTable(const char *, char *);
SNMPCallback store_tcapOmDevelSentCurrentTable;
void refresh_tcapOmDevelSentCurrentTable(void);
FindVarMethod var_tcapOmDevelSent5minIntTable;
int tcapOmDevelSent5minIntTable_add(struct tcapOmDevelSent5minIntTable_data *);
int tcapOmDevelSent5minIntTable_del(struct tcapOmDevelSent5minIntTable_data **);
void parse_tcapOmDevelSent5minIntTable(const char *, char *);
SNMPCallback store_tcapOmDevelSent5minIntTable;
void refresh_tcapOmDevelSent5minIntTable(void);
FindVarMethod var_tcapOmDevelSent15minIntTable;
int tcapOmDevelSent15minIntTable_add(struct tcapOmDevelSent15minIntTable_data *);
int tcapOmDevelSent15minIntTable_del(struct tcapOmDevelSent15minIntTable_data **);
void parse_tcapOmDevelSent15minIntTable(const char *, char *);
SNMPCallback store_tcapOmDevelSent15minIntTable;
void refresh_tcapOmDevelSent15minIntTable(void);

WriteMethod write_tcapOm1stAndIntervalActivate;
WriteMethod write_tcapOm1stAndIntervalDeactivate;
WriteMethod write_tcapOm5MinActivate;
WriteMethod write_tcapOm5MinDeaActivate;
WriteMethod write_tcapOm15MinActivate;
WriteMethod write_tcapOm15MinDeaActivate;
WriteMethod write_tcapOm5MinMaxIntervals;
WriteMethod write_tcapOm15MinMaxIntervals;

#endif				/* __LOCAL_TCAPOMMIB_H__ */
