#!/bin/bash
echo '.so man9/irixcompat.9.man' > man9/btod.9.man
echo '.so man9/svr4compat.9.man' > man9/btop.9.man
echo '.so man9/svr4compat.9.man' > man9/btopr.9.man
echo '.so man9/svr4compat.9.man' > man9/buf_breakup.9.man
echo '.so man9/uw7compat.9.man' > man9/call_demon.9.man
echo '.so man9/svr4compat.9.man' > man9/clrbuf.9.man
echo '.so man9/uw7compat.9.man' > man9/cm_abort_trans.9.man
echo '.so man9/svr4compat.9.man' > man9/cm_addval.9.man
echo '.so man9/svr4compat.9.man' > man9/cm_AT_putconf.9.man
echo '.so man9/uw7compat.9.man' > man9/cm_begin_trans.9.man
echo '.so man9/uw7compat.9.man' > man9/cm_delkey.9.man
echo '.so man9/svr4compat.9.man' > man9/cm_delval.9.man
echo '.so man9/svr4compat.9.man' > man9/cm_devconfig_size.9.man
echo '.so man9/uw7compat.9.man' > man9/cm_end_trans.9.man
echo '.so man9/svr4compat.9.man' > man9/cm_getbrdkey.9.man
echo '.so man9/svr4compat.9.man' > man9/cm_getnbrd.9.man
echo '.so man9/svr4compat.9.man' > man9/cm_getval.9.man
echo '.so man9/svr4compat.9.man' > man9/cm_getversion.9.man
echo '.so man9/svr4compat.9.man' > man9/cm_intr_attach.9.man
echo '.so man9/svr4compat.9.man' > man9/cm_intr_detach.9.man
echo '.so man9/uw7compat.9.man' > man9/cm_newkey.9.man
echo '.so man9/uw7compat.9.man' > man9/cm_read_devconfig16.9.man
echo '.so man9/uw7compat.9.man' > man9/cm_read_devconfig32.9.man
echo '.so man9/uw7compat.9.man' > man9/cm_read_devconfig8.9.man
echo '.so man9/svr4compat.9.man' > man9/cm_read_devconfig.9.man
echo '.so man9/uw7compat.9.man' > man9/cm_write_devconfig16.9.man
echo '.so man9/uw7compat.9.man' > man9/cm_write_devconfig32.9.man
echo '.so man9/uw7compat.9.man' > man9/cm_write_devconfig8.9.man
echo '.so man9/svr4compat.9.man' > man9/cm_write_devconfig.9.man
echo '.so man9/irixcompat.9.man' > man9/cpsema.9.man
echo '.so man9/suncompat.9.man' > man9/cv_broadcast.9.man
echo '.so man9/suncompat.9.man' > man9/cv_destroy.9.man
echo '.so man9/suncompat.9.man' > man9/cv_init.9.man
echo '.so man9/irixcompat.9.man' > man9/cvsema.9.man
echo '.so man9/suncompat.9.man' > man9/cv_signal.9.man
echo '.so man9/suncompat.9.man' > man9/cv_timedwait.9.man
echo '.so man9/suncompat.9.man' > man9/cv_timedwait_sig.9.man
echo '.so man9/suncompat.9.man' > man9/cv_wait.9.man
echo '.so man9/suncompat.9.man' > man9/cv_wait_sig.9.man
echo '.so man9/suncompat.9.man' > man9/ddi_device_acc_attr.9.man
echo '.so man9/suncompat.9.man' > man9/ddi_idevice_cookie.9.man
echo '.so man9/suncompat.9.man' > man9/ddi_umem_iosetup.9.man
echo '.so man9/uw7compat.9.man' > man9/devmem_mapin.9.man
echo '.so man9/uw7compat.9.man' > man9/devmem_mapout.9.man
echo '.so man9/uw7compat.9.man' > man9/devmem_ppid.9.man
echo '.so man9/uw7compat.9.man' > man9/devmem_size.9.man
echo '.so man9/irixcompat.9.man' > man9/dki_dcache_inval.9.man
echo '.so man9/irixcompat.9.man' > man9/dki_dcache_wb.9.man
echo '.so man9/irixcompat.9.man' > man9/dki_dcache_wbinval.9.man
echo '.so man9/svr4compat.9.man' > man9/dma_cascade.9.man
echo '.so man9/svr4compat.9.man' > man9/dma_disable.9.man
echo '.so man9/svr4compat.9.man' > man9/dma_enable.9.man
echo '.so man9/svr4compat.9.man' > man9/dma_free_buf.9.man
echo '.so man9/svr4compat.9.man' > man9/dma_free_cb.9.man
echo '.so man9/svr4compat.9.man' > man9/dma_get_best_mode.9.man
echo '.so man9/svr4compat.9.man' > man9/dma_get_buf.9.man
echo '.so man9/svr4compat.9.man' > man9/dma_get_cb.9.man
echo '.so man9/irixcompat.9.man' > man9/dma_map.9.man
echo '.so man9/irixcompat.9.man' > man9/dma_mapaddr.9.man
echo '.so man9/irixcompat.9.man' > man9/dma_mapalloc.9.man
echo '.so man9/irixcompat.9.man' > man9/dma_mapbp.9.man
echo '.so man9/irixcompat.9.man' > man9/dma_mapfree.9.man
echo '.so man9/svr4compat.9.man' > man9/dma_pageio.9.man
echo '.so man9/svr4compat.9.man' > man9/dma_physreq.9.man
echo '.so man9/svr4compat.9.man' > man9/dma_prog.9.man
echo '.so man9/svr4compat.9.man' > man9/dma_stop.9.man
echo '.so man9/svr4compat.9.man' > man9/dma_swsetup.9.man
echo '.so man9/svr4compat.9.man' > man9/dma_swstart.9.man
echo '.so man9/uw7compat.9.man' > man9/do_biostart.9.man
echo '.so man9/uw7compat.9.man' > man9/do_devinfo.9.man
echo '.so man9/uw7compat.9.man' > man9/do_drvctl.9.man
echo '.so man9/uw7compat.9.man' > man9/do_ioctl.9.man
echo '.so man9/uw7compat.9.man' > man9/drv_attach.9.man
echo '.so man9/uw7compat.9.man' > man9/drv_callback.9.man
echo '.so man9/uw7compat.9.man' > man9/drv_close.9.man
echo '.so man9/uw7compat.9.man' > man9/drv_detach.9.man
echo '.so man9/svr4compat.9.man' > man9/drv_gethardware.9.man
echo '.so man9/svr4compat.9.man' > man9/drv_mmap.9.man
echo '.so man9/svr4compat.9.man' > man9/drv_munmap.9.man
echo '.so man9/uw7compat.9.man' > man9/drv_open.9.man
echo '.so man9/svr4compat.9.man' > man9/drv_setparm.9.man
echo '.so man9/uw7compat.9.man' > man9/drv_shutdown.9.man
echo '.so man9/irixcompat.9.man' > man9/eisa_dma_disable.9.man
echo '.so man9/irixcompat.9.man' > man9/eisa_dma_enable.9.man
echo '.so man9/irixcompat.9.man' > man9/eisa_dma_free_buf.9.man
echo '.so man9/irixcompat.9.man' > man9/eisa_dma_free_cb.9.man
echo '.so man9/irixcompat.9.man' > man9/eisa_dma_get_buf.9.man
echo '.so man9/irixcompat.9.man' > man9/eisa_dma_get_cb.9.man
echo '.so man9/irixcompat.9.man' > man9/eisa_dma_prog.9.man
echo '.so man9/irixcompat.9.man' > man9/eisa_dma_stop.9.man
echo '.so man9/irixcompat.9.man' > man9/eisa_dma_swstart.9.man
echo '.so man9/uw7compat.9.man' > man9/eisa_parse_devconfig.9.man
echo '.so man9/irixcompat.9.man' > man9/fasthzto.9.man
echo '.so man9/irixcompat.9.man' > man9/fast_itimeout.9.man
echo '.so man9/irixcompat.9.man' > man9/flushbus.9.man
echo '.so man9/svr4compat.9.man' > man9/freerbuf.9.man
echo '.so man9/irixcompat.9.man' > man9/freesema.9.man
echo '.so man9/irixcompat.9.man' > man9/fubyte.9.man
echo '.so man9/irixcompat.9.man' > man9/fuword.9.man
echo '.so man9/svr4compat.9.man' > man9/geteblk.9.man
echo '.so man9/svr4compat.9.man' > man9/geterror.9.man
echo '.so man9/svr4compat.9.man' > man9/getnextpg.9.man
echo '.so man9/svr4compat.9.man' > man9/getpl.9.man
echo '.so man9/svr4compat.9.man' > man9/getrbuf.9.man
echo '.so man9/svr4compat.9.man' > man9/hat_getkpfnum.9.man
echo '.so man9/svr4compat.9.man' > man9/hat_getppfnum.9.man
echo '.so man9/irixcompat.9.man' > man9/hwcpin.9.man
echo '.so man9/irixcompat.9.man' > man9/hwcpout.9.man
echo '.so man9/uw7compat.9.man' > man9/ifstats_attach.9.man
echo '.so man9/uw7compat.9.man' > man9/ifstats_detach.9.man
echo '.so man9/svr4compat.9.man' > man9/inb.9.man
echo '.so man9/irixcompat.9.man' > man9/initnsema.9.man
echo '.so man9/irixcompat.9.man' > man9/initnsema_mutex.9.man
echo '.so man9/svr4compat.9.man' > man9/inl.9.man
echo '.so man9/svr4compat.9.man' > man9/inw.9.man
echo '.so man9/svr4compat.9.man' > man9/iobitmapctl.9.man
echo '.so man9/suncompat.9.man' > man9/IOC_CONVERT_FROM.9.man
echo '.so man9/irixcompat.9.man' > man9/ip26_enable_ucmem.9.man
echo '.so man9/irixcompat.9.man' > man9/ip26_return_ucmem.9.man
echo '.so man9/irixcompat.9.man' > man9/kern_calloc.9.man
echo '.so man9/irixcompat.9.man' > man9/kern_free.9.man
echo '.so man9/irixcompat.9.man' > man9/kern_malloc.9.man
echo '.so man9/uw7compat.9.man' > man9/kmem_alloc_phys.9.man
echo '.so man9/svr4compat.9.man' > man9/KS_HOLD0LOCKS.9.man
echo '.so man9/uw7compat.9.man' > man9/kthread_exit.9.man
echo '.so man9/uw7compat.9.man' > man9/kthread_spawn.9.man
echo '.so man9/uw7compat.9.man' > man9/kthread_wait.9.man
echo '.so man9/irixcompat.9.man' > man9/kvtophys.9.man
echo '.so man9/svr4compat.9.man' > man9/kvtoppid.9.man
echo '.so man9/irixcompat.9.man' > man9/LOCK_DESTROY.9.man
echo '.so man9/irixcompat.9.man' > man9/LOCK_INIT.9.man
echo '.so man9/osfcompat.9.man' > man9/MALLOC.9.man
echo '.so man9/svr4compat.9.man' > man9/met_ds_alloc_stats.9.man
echo '.so man9/svr4compat.9.man' > man9/met_ds_dealloc_stats.9.man
echo '.so man9/svr4compat.9.man' > man9/met_ds_dequeued.9.man
echo '.so man9/svr4compat.9.man' > man9/met_ds_hist_stats.9.man
echo '.so man9/svr4compat.9.man' > man9/met_ds_iodone.9.man
echo '.so man9/svr4compat.9.man' > man9/met_ds_queued.9.man
echo '.so man9/svr4compat.9.man' > man9/mod_drvattach.9.man
echo '.so man9/svr4compat.9.man' > man9/mod_drvdetach.9.man
echo '.so man9/hpuxcompat.9.man' > man9/msgppullup.9.man
echo '.so man9/suncompat.9.man' > man9/mutex.9.man
echo '.so man9/irixcompat.9.man' > man9/MUTEX_ALLOC.9.man
echo '.so man9/irixcompat.9.man' > man9/MUTEX_DEALLOC.9.man
echo '.so man9/irixcompat.9.man' > man9/MUTEX_DESTROY.9.man
echo '.so man9/suncompat.9.man' > man9/mutex_destroy.9.man
echo '.so man9/suncompat.9.man' > man9/mutex_enter.9.man
echo '.so man9/suncompat.9.man' > man9/mutex_exit.9.man
echo '.so man9/irixcompat.9.man' > man9/MUTEX_INIT.9.man
echo '.so man9/suncompat.9.man' > man9/mutex_init.9.man
echo '.so man9/irixcompat.9.man' > man9/MUTEX_LOCK.9.man
echo '.so man9/irixcompat.9.man' > man9/MUTEX_MINE.9.man
echo '.so man9/irixcompat.9.man' > man9/MUTEX_OWNED.9.man
echo '.so man9/suncompat.9.man' > man9/mutex_owned.9.man
echo '.so man9/suncompat.9.man' > man9/mutex_tryenter.9.man
echo '.so man9/irixcompat.9.man' > man9/MUTEX_TRYLOCK.9.man
echo '.so man9/irixcompat.9.man' > man9/MUTEX_UNLOCK.9.man
echo '.so man9/svr4compat.9.man' > man9/ngeteblk.9.man
echo '.so man9/uw7compat.9.man' > man9/numtos.9.man
echo '.so man9/svr4compat.9.man' > man9/outb.9.man
echo '.so man9/svr4compat.9.man' > man9/outl.9.man
echo '.so man9/svr4compat.9.man' > man9/outw.9.man
echo '.so man9/svr4compat.9.man' > man9/ovbcopy.9.man
echo '.so man9/irixcompat.9.man' > man9/pciio_dmaaddr_drain.9.man
echo '.so man9/irixcompat.9.man' > man9/pciio_dma_dev_get.9.man
echo '.so man9/irixcompat.9.man' > man9/pciio_dmalist_drain.9.man
echo '.so man9/svr4compat.9.man' > man9/phalloc.9.man
echo '.so man9/svr4compat.9.man' > man9/phfree.9.man
echo '.so man9/svr4compat.9.man' > man9/physiock.9.man
echo '.so man9/svr4compat.9.man' > man9/physmap.9.man
echo '.so man9/svr4compat.9.man' > man9/physmap_free.9.man
echo '.so man9/svr4compat.9.man' > man9/phystoppid.9.man
echo '.so man9/irixcompat.9.man' > man9/pio_andb_rmw.9.man
echo '.so man9/irixcompat.9.man' > man9/pio_andh_rmw.9.man
echo '.so man9/irixcompat.9.man' > man9/pio_andw_rmw.9.man
echo '.so man9/irixcompat.9.man' > man9/pio_badaddr.9.man
echo '.so man9/irixcompat.9.man' > man9/pio_badaddr_val.9.man
echo '.so man9/irixcompat.9.man' > man9/pio_bcopyin.9.man
echo '.so man9/irixcompat.9.man' > man9/pio_bcopyout.9.man
echo '.so man9/irixcompat.9.man' > man9/pio_mapaddr.9.man
echo '.so man9/irixcompat.9.man' > man9/pio_mapalloc.9.man
echo '.so man9/irixcompat.9.man' > man9/pio_mapfree.9.man
echo '.so man9/irixcompat.9.man' > man9/pio_orb_rmw.9.man
echo '.so man9/irixcompat.9.man' > man9/pio_orh_rmw.9.man
echo '.so man9/irixcompat.9.man' > man9/pio_orw_rmw.9.man
echo '.so man9/irixcompat.9.man' > man9/pio_wbadaddr.9.man
echo '.so man9/irixcompat.9.man' > man9/pio_wbadaddr_val.9.man
echo '.so man9/svr4compat.9.man' > man9/pollwakeup.9.man
echo '.so man9/svr4compat.9.man' > man9/pptophys.9.man
echo '.so man9/svr4compat.9.man' > man9/proc_ref.9.man
echo '.so man9/svr4compat.9.man' > man9/proc_signal.9.man
echo '.so man9/svr4compat.9.man' > man9/proc_unref.9.man
echo '.so man9/svr4compat.9.man' > man9/proc_valid.9.man
echo '.so man9/irixcompat.9.man' > man9/psema.9.man
echo '.so man9/svr4compat.9.man' > man9/psignal.9.man
echo '.so man9/svr4compat.9.man' > man9/ptob.9.man
echo '.so man9/svr4compat.9.man' > man9/rdma_filter.9.man
echo '.so man9/svr4compat.9.man' > man9/repinsb.9.man
echo '.so man9/svr4compat.9.man' > man9/repinsd.9.man
echo '.so man9/svr4compat.9.man' > man9/repinsw.9.man
echo '.so man9/svr4compat.9.man' > man9/repoutsb.9.man
echo '.so man9/svr4compat.9.man' > man9/repoutsd.9.man
echo '.so man9/svr4compat.9.man' > man9/repoutsw.9.man
echo '.so man9/irixcompat.9.man' > man9/RW_DESTROY.9.man
echo '.so man9/suncompat.9.man' > man9/rw_destroy.9.man
echo '.so man9/suncompat.9.man' > man9/rw_downgrade.9.man
echo '.so man9/suncompat.9.man' > man9/rw_enter.9.man
echo '.so man9/suncompat.9.man' > man9/rw_exit.9.man
echo '.so man9/irixcompat.9.man' > man9/RW_INIT.9.man
echo '.so man9/suncompat.9.man' > man9/rw_init.9.man
echo '.so man9/suncompat.9.man' > man9/rwlock.9.man
echo '.so man9/suncompat.9.man' > man9/rw_read_locked.9.man
echo '.so man9/suncompat.9.man' > man9/rw_tryenter.9.man
echo '.so man9/suncompat.9.man' > man9/rw_tryupgrade.9.man
echo '.so man9/uw7compat.9.man' > man9/scgth_free.9.man
echo '.so man9/irixcompat.9.man' > man9/scsi_alloc.9.man
echo '.so man9/irixcompat.9.man' > man9/scsi_command.9.man
echo '.so man9/irixcompat.9.man' > man9/scsi_free.9.man
echo '.so man9/irixcompat.9.man' > man9/scsi_info.9.man
echo '.so man9/suncompat.9.man' > man9/sema_destroy.9.man
echo '.so man9/suncompat.9.man' > man9/sema_init.9.man
echo '.so man9/suncompat.9.man' > man9/sema_p.9.man
echo '.so man9/suncompat.9.man' > man9/semaphore.9.man
echo '.so man9/suncompat.9.man' > man9/sema_p_sig.9.man
echo '.so man9/suncompat.9.man' > man9/sema_tryp.9.man
echo '.so man9/suncompat.9.man' > man9/sema_v.9.man
echo '.so man9/irixcompat.9.man' > man9/sgset.9.man
echo '.so man9/irixcompat.9.man' > man9/SLEEP_DESTROY.9.man
echo '.so man9/irixcompat.9.man' > man9/SLEEP_INIT.9.man
echo '.so man9/irixcompat.9.man' > man9/subyte.9.man
echo '.so man9/irixcompat.9.man' > man9/suword.9.man
echo '.so man9/irixcompat.9.man' > man9/SV_DESTROY.9.man
echo '.so man9/irixcompat.9.man' > man9/SV_INIT.9.man
echo '.so man9/suncompat.9.man' > man9/swab.9.man
echo '.so man9/uw7compat.9.man' > man9/TICKS.9.man
echo '.so man9/uw7compat.9.man' > man9/TICKS_BETWEEN.9.man
echo '.so man9/uw7compat.9.man' > man9/TICKS_FARFUTURE.9.man
echo '.so man9/uw7compat.9.man' > man9/TICKS_FARPAST.9.man
echo '.so man9/uw7compat.9.man' > man9/TICKS_LATER.9.man
echo '.so man9/uw7compat.9.man' > man9/TICKS_SINCE.9.man
echo '.so man9/uw7compat.9.man' > man9/uiobuf.9.man
echo '.so man9/svr4compat.9.man' > man9/uiomove.9.man
echo '.so man9/irixcompat.9.man' > man9/uiophysio.9.man
echo '.so man9/irixcompat.9.man' > man9/undma.9.man
echo '.so man9/svr4compat.9.man' > man9/ureadc.9.man
echo '.so man9/irixcompat.9.man' > man9/userdma.9.man
echo '.so man9/svr4compat.9.man' > man9/uwritec.9.man
echo '.so man9/irixcompat.9.man' > man9/valusema.9.man
echo '.so man9/irixcompat.9.man' > man9/v_getaddr.9.man
echo '.so man9/irixcompat.9.man' > man9/v_gethandle.9.man
echo '.so man9/irixcompat.9.man' > man9/v_getlen.9.man
echo '.so man9/irixcompat.9.man' > man9/v_mapphys.9.man
echo '.so man9/irixcompat.9.man' > man9/vme_adapter.9.man
echo '.so man9/irixcompat.9.man' > man9/vme_ivec_alloc.9.man
echo '.so man9/irixcompat.9.man' > man9/vme_ivec_free.9.man
echo '.so man9/irixcompat.9.man' > man9/vme_ivec_set.9.man
echo '.so man9/irixcompat.9.man' > man9/vsema.9.man
echo '.so man9/irixcompat.9.man' > man9/wbadaddr.9.man
echo '.so man9/irixcompat.9.man' > man9/wbadaddr_val.9.man
