'\" rtp
.\" -*- nroff -*- vim: ft=nroff nocin nosi
.\"
.\" @(#) $Id: DLC_ALTER.4.man,v 0.9.2.1 2008-05-25 12:46:53 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.  The author(s) will take no responsibility in it.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" -------------------------------------------------------------------------
.\"
.\" U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
.\" on behalf of the U.S. Government ("Government"), the following
.\" provisions apply to you.  If the Software is supplied by the Department
.\" of Defense ("DoD"), it is classified as "Commercial Computer Software"
.\" under paragraph 252.227-7014 of the DoD Supplement to the Federal
.\" Acquisition Regulations ("DFARS") (or any successor regulations) and the
.\" Government is acquiring only the license rights granted herein (the
.\" license rights customarily provided to non-Government users).  If the
.\" Software is supplied to any unit or agency of the Government other than
.\" DoD, it is classified as "Restricted Computer Software" and the
.\" Government's rights in the Software are defined in paragraph 52.227-19
.\" of the Federal Acquisition Regulations ("FAR") (or any successor
.\" regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
.\" NASA Supplement to the FAR (or any successor regulations).
.\"
.\" =========================================================================
.\" 
.\" Commercial licensing and support of this software is available from
.\" OpenSS7 Corporation at a fee.  See http://www.openss7.com/
.\" 
.\" =========================================================================
.\"
.\" Last Modified $Date: 2008-05-25 12:46:53 $ by $Author: brian $
.\"
.\" -------------------------------------------------------------------------
.\"
.\" $Log: DLC_ALTER.4.man,v $
.\" Revision 0.9.2.1  2008-05-25 12:46:53  brian
.\" - added manual pages, libraries, utilities and drivers
.\"
.\" =========================================================================
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database strxns.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.so strxns.macros
.\"
.\"
.TH DL_ALTER 4 "@PACKAGE_DATE@" "@PACKAGE@-@VERSION@" "@PACKAGE_TITLE@ Devices"
.\"
.\"
.SH NAME
.B DL_ALTER
\- add a functional address
.\"
.\"
.SH INTERFACE
Generic Data Link Control (GLDC),
.IR AIX \(rg-specific.
.[
aixdlpi
.]
.\"
.\"
.SH SYNOPSIS
.PP
.B #include <sys/stropts.h>
.br
.B #include <sys/dlpi_ioctl.h>
.HP
.BI "int " retval " = ioctl(" dlpi_stream ", " cmd ", " arg );
.\"
.\"
.SH DESCRIPTION
.PP
The
.B DL_ALTER
input-output control alters link station (LS) configuration parameters.
.PP
The argument to the
.B DLC_ADDR_FUNC_ADDR
input-output control is a pointer to a
.B dlc_alter_arg
structure, formatted as follows:
.PP
.nf
\f(CW\s-1\
struct dlc_alter_arg {
    uint32_t gdlc_sap_corr;
    uint32_t gdlc_ls_corr;
    uint32_t flags;
    uint32_t repoll_time;
    uint32_t ack_time;
    uint32_t inact_time;
    uint32_t force_time;
    uint32_t maxif;
    uint32_t xmit_wind;
    uint32_t max_repoll;
    uint32_t routing_len;
    uint8_t routing[DLC_MAX_ROUT];
    uint32_t result_flags;
};
\s+1\fP
.fi
.PP
The
.B dlc_alter_arg
structure contains the following members:
.TP
.I gdlc_sap_corr
Specifies the generic data link control (GDLC) service access point (SAP)
correlator of the LS to alter.
.TP
.I gdlc_ls_corr
Specifies the generic data link control (GDLC) link station (LS) correlator of
the LS to alter.
.TP
.I flags
Specifies the alteration flags.  The following flags are supported:
.RS
.TP
.B DLC_ALT_RTO
Alter
repoll timeout
when set.
Alters the length of time the LS waits for a response before repolling the
remote station.
When specified, the
repoll timeout
value specified in the LS configuration is overridden by the value supplied in
the
repoll timeout
field of the
.B DLC_ALTER
command.  This new value remains in effect until another value is specified or
the LS is halted.
.TP
.B DLC_ALT_AKT
Alter
acknowledgement timeout
when set.
Alters the length of time the LS delays the transmission of an acknowledgement
for a received I-frame.
When specified, the
acknowledgement timeout
value specified in the LS configuration is overridden by the value supplied in
the
acknowledgement timeout
field of the
.BR DLC_ALTER
command.  This new value remains in effect until another value is specified or
the LS is halted.
.TP
.B DLC_ALT_ITO
Alter
inactivity timeout
when set.
Alters the maximum length of time allowed without link receive activity from the
remote station.
When specified, the
inactivity timeout
value specified in the LS configuration is overridden by the value supplied in
the
inactivity timeout
field of the
.BR DLC_ALTER
command.  This new value remains in effect until another value is specified or
the LS is halted.
.TP
.B DLC_ALT_FHT
Alter
force halt timeout
when set.
Alters the period to wait for a normal disconnection before forcing the halt LS
to occur.
When specified, the
force halt timeout
value specified in the LS configuration is overridden by the value supplied in
the
force halt timeout
field of the
.BR DLC_ALTER
command.  This new value remains in effect until another value is specified or
the LS is halted.
.TP
.B DLC_ALT_MIF
Alter
maximum I-field length
when set.
Alters the value for the maximum length of transmit or receive data in one
I-field.  If received data exceeds this length, a buffer overflow indication is
set by GDLC in the receive extension.
When specified, the
maximum I-field length
value specified in the LS configuration is overridden by the value supplied in
the
maximum I-field length
field of the
.BR DLC_ALTER
command.  This new value remains in effect until another value is specified or
the LS is halted.
.TP
.B DLC_ALT_XWIN
Alter
transmit window count
when set.
Alters the maximum number of information frames that can be sent in one transmit
burst.
When specified, the
transmit window count
value specified in the LS configuration is overridden by the value supplied in
the
transmit window count
field of the
.BR DLC_ALTER
command.  This new value remains in effect until another value is specified or
the LS is halted.
.TP
.B DLC_ALT_MXR
Alter
maximum repoll count
when set.
Alters the maximum number of retries for an acknowledged command frame, or in
the case of an I-frame timeout, the number of times the nonresponding remote LS
will be polled with a supervisory command frame.
When specified, the
maximum repoll count
value specified in the LS configuration is overridden by the value supplied in
the
maximum repoll count
field of the
.BR DLC_ALTER
command.  This new value remains in effect until another value is specified or
the LS is halted.
.TP
.B DLC_ALT_RTE
Alter
routing length and routing data
when set.
Alters the route that subsequent transmit packets take when transferring data
across a local area network bridge.
When specified, the
routing length and routing data
values specified in the LS configuration is overridden by the value supplied in
the
routing length and routing data
fields of the
.BR DLC_ALTER
command.  This new value remains in effect until another value is specified or
the LS is halted.
.TP
.B DLC_ALT_SM1
Set primary SDLC Control mode.
Sets the local station to a primary station in NDM (Normal Disconnect Mode),
waiting for a command from PU service to write an XID or TEST, or a command to
contact the secondary for NRM (Normal Responsive Mode) data phase.  This control
can only be issued if not already in NRM (Normal Responsive Mode), and no XID,
TEST or SNRM is ni progress.  This flag cannot be set if the
.BR DLC_ALT_SM2
flag is set.
.TP
.B DLC_ALT_SM2
Set secondary SDLC Control mode.
Sets the local station to a secondary station in NDM (Normal Disconnect Mode),
waiting for XID, TEST, or SNRM from the primary station.  This control can only
be issued if not already in NRM, and no XID, TEST, or SNRM is in progress.  This
flag cannot be set if the
.BR DLC_ALT_SM1
flag is set.
.TP
.B DLC_ALT_IT1
Set notification for inactivity timeout mode.
Inactivity does not cause the LS to be halted, but notifies the user of
inactivity without termination.
.TP
.B DLC_ALT_IT2
Set automatic halt for inactivity timeout mode.
Inativity causes the LS to be halted.
.RE
.TP
.I repoll_time
When the
.B DLC_ALT_RTO
flag is set, this field specifies the new value of the LS
repoll timeout value.
This is the length of time the LS waits for a response before repolling the
remote station.
This is the
\*(lqP-bit timer\*(rq
from ISO/IEC 8802-2.
.[
iso/iec 8802-2 : 1998
.]
This is the \*(lqTimer T1\*(rq from ISO/IEC 7776
.[
iso/iec 7776 : 1995
.]
and X.25 LAPB.
.[
x25
.]
.TP
.I ack_time
When the
.B DLC_ALT_AKT
flag is set, this field specifies the new value of the LS
acknowledgement timeout value.
This is the length of time the LS delays the transmission of an acknowledgement
for a received I-frame.
This is the
\*(lqAcknowledgement timer\*(rq
from ISO/IEC 8802-2.
.[
iso/iec 8802-2 : 1998
.]
This is the \*(lqParameter T2\*(rq from ISO/IEC 7776
.[
iso/iec 7776 : 1995
.]
and X.25 LAPB.
.[
x25
.]
.TP
.I inact_time
When the
.B DLC_ALT_ITO
flag is set, this field specifies the new value of the LS
inactivity timeout value.
This is the maximum length of time allowed without link receive activity from the
remote station.
This is the \*(lqParameter T4\*(rq from ISO/IEC 7776
.[
iso/iec 7776 : 1995
.]
and X.25 LAPB.
.[
x25
.]
.TP
.I force_time
When the
.B DLC_ALT_FHT
flag is set, this field specifies the new value of the LS
force halt timeout value.
This is the period to wait for a normal disconnection before forcing the halt LS
to occur.
This is the \*(lqTimer T3\*(rq from ISO/IEC 7776
.[
iso/iec 7776 : 1995
.]
and X.25 LAPB.
.[
x25
.]
.TP
.I maxif
When the
.B DLC_ALT_MIF
flag is set, this field specifies the new value of the LS
maximum I-field size.
This is the value for the maximum length of transmit or receive data in one
I-field.  If received data exceeds this length, a buffer overflow indication is
set by GDLC in the receive extension.
GDLC does not allow this value to exceed the capacity of
the receive buffer and only increases the internal value to the allowed maximum.
It is the
\*(lqMaximum number of octets in an I PDU, N1\*(rq
from ISO/IEC 8802-2.
.[
iso/iec 8802-2 : 1998
.]
This is the \*(lqMaximum number of bits in an I frame N1\*(rq from ISO/IEC 7776
.[
iso/iec 7776 : 1995
.]
and X.25 LAPB.
.[
x25
.]
.TP
.I xmit_wind
When the
.B DLC_ALT_XWIN
flag is set, this field specifies the new value of the LS
transmit window count value.
This is the maximum number of information frames that can be sent in one transmit
burst.
It is the
\*(lqTransmit window size, k\*(rq
from ISO/IEC 8802-2.
.[
iso/iec 8802-2 : 1998
.]
This is the \*(lqMaximum numberof outstanding I frames k\*(rq from ISO/IEC 7776
.[
iso/iec 7776 : 1995
.]
and X.25 LAPB.
.[
x25
.]
.TP
.I max_repoll
When the
.B DLC_ALT_MXR
flag is set, this field specifies the new value of the LS
maximum repoll count value.
This is the maximum number of retries for an acknowledged command frame, or in
the case of an I-frame timeout, the number of times the nonresponding remote LS
will be polled with a supervisory command frame.
It is the
\*(lqMaximum number of transmissions, N2\*(rq
from ISO/IEC 8802-2.
.[
iso/iec 8802-2 : 1998
.]
This is the \*(lqMaximum number of attempts to complete a transmission N2\*(rq from ISO/IEC 7776
.[
iso/iec 7776 : 1995
.]
and X.25 LAPB.
.[
x25
.]
.TP
.I routing_len
When the
.B DLC_ALT_RTE
flag is set, this field specifies the new value of the LS
routing field length.
This is the route that subsequent transmit packets take when transferring data
across a local area network bridge.
.TP
.I routing
When the
.B DLC_ALT_RTE
flag is set, this field specifies the new value of the LS
routing data.
.TP
.I result_flags
Returns the following result indicators at the completion of the alter
input-output control operation, depending upon the command:
.RS
.TP
.B DLC_MSS_RES
Indicates that the mode is set to secondary.  When set, this bit indicates that
the station mode has been set to secondary as a result of the user issuing an
.B DLC_ALTER
(set mode secondary) command.
.TP
.B DLC_MSSF_RES
Indicates that the mode set to secondary was unsuccessful.  When set, this bit
indicates that the station mode has not been set to secondary as a result of the
user issuing an
.B DLC_ALTER
(set mode secondary) command.  This occurs whenever an
SDLC LS is alreay in data phase or a SDLC primary command sequence has not yet
completed.
.TP
.B DLC_MSP_RES
Indicates that the mode is set to primary.  When set, this bit indicates that
the station mode has been set to primary as a result of the user inssuing an
.B DLC_ALTER
(set mode primary) command.
.TP
.B DLC_MSPF_RES
Indicatest that the mode set primary was unsuccessful.  When set, this bit
indicates that the station mode has not been set to primary as a result of the
user issuing an
.B DLC_ALTER
(set mode primary) command.  This occurs whenever an SDLC LS is already in data
phase.
.RE
.PP
The protocol-dependent area allows additional fields to be provided by a
specific protocol type.  Corresponding flags may be necessary to support
additional fields.  This optional data area must directly follow (or append to)
the end of the
.B dlc_alter_arg
structure.
.\"
.\"
.SH RETURN
.PP
Upon success, the input-output control returns zero (0).  Upon failure, the
input-output control returnes minus one (-1) and sets
.BR errno (3)
to an appropriate error code.
.\"
.\"
.SH ERRORS
.PP
When the input-output control fails, it returns minus one (-1) and set the
.BR errno (3)
to an appropriate error code.  In addition to the reasons given in
.BR ioctl (2s),
this input-output control can fail because of the following:
.TP \w'[\fBEDEADLK\fP]\(em'u
.RB [ EINVAL ]
A parameter of the input-output control is invalid.
.TP
.RB [ EFAULT ]
A memory extent exceeds the callers valid address space.
.TP
.RB [ EPROTO ]
A rule of the interface protocol was violated.
.TP
.RB [ EAGAIN ]
The operation could not be immediately processed.
.TP
.RB [ ENOBUFS ]
There were insufficient message buffers to complete the operation.
.TP
.RB [ ENOSR ]
There were insufficient STREAMS resources to complete the operation.
.TP
.RB [ ENOMEM ]
There was insufficient memory to complete the operation.
.TP
.RB [ EDEADLK ]
A deadlock condition was detected and avoided.
.\"
.\"
.SH NOTICES
.PP
Note that
.IR AIX \(rg
terminology for GDLC conflict with that of LLC
.[
iso/iec 8802-2 : 1998
.]
and LAPB.
.[
iso7776
.]
Under IEEE terminology, a link station is associated with the MAC entity or a
point-to-point data link endpoint, and one or more service access points (SAP)
are associated with the one link station.  LLC Type 2 supporting link stations
can have associated with them zero or more connections that represent a
connection between a local MAC address and a remote MAC address, a local SAP
and a remote SAP.  LAPB link stations can have associated with them 1
connection that represents a connection between the local and remote stations.
LAPD
.[
q921
.]
link stations can have associated with them one or more connections that
represent a connection associated with a local and remote SAP (TEI).
LAPF
.[
q922
.]
link stations can have associated with them one or more connections that
represent a connection associated with a local and remote SAP (DLCI).
.PP
.IR AIX \(rg
terminology in the GDLC documentation refers to this latter connection,
confusingly, as a link station (LS).
The
.IR AIX \(rg
GDLC service access point (SAP) is really a Physical Point of Attachment (PPA) and
DLSAP combination under the DLPI,
.[
dlpi revision 2.0.0
.]
and the
.IR AIX \(rg
GDLC link station (LS) is really a connection identifier.
It may be helpful to think of a GDLC link station (LS) as an identifier of a
local and remote link station combination for a given DLSAP.
.PP
.B DL_ALTER
is an
.IR AIX \(rg-specific
input-output control.
It might be necessary to define C preprocessor symbol
.B _AIX_SOURCE
before including the
.RB < sys/dlpi.h >,
.RB < sys/dlpi_ext.h >,
or
.RB < sys/dlpi_ioctl.h >
header files to expose the definitions, structures and declarations associated
with the input-output control.
.\"
.\"
.SH SEE ALSO
.PP
.BR dlpi_ioctl (4),
.BR dlpi (7),
.BR STREAMS (9).
.\"
.\"
.SH COMPATIBILITY
.PP
The
.B DL_ALTER
input-output control is compatible with
.IR AIX \(rg,
.[
aixdoc
.]
and implementations based on
.IR AIX \(rg,
with the following portability considerations:
.IP \(em \w'\(em\(em'u
.B DL_ALTER
is an
.IR AIX \(rg-specific
input-output control that is not part of the DLPI standard.
.[
dlpi revision 2.0.0
.]
It should not be used by portable DLPI programs.
.IP \(em
Missing from ISO/IEC 8802-2
.[
iso/iec 8802-2 : 1998
.]
is the following:
.RS
.IP "\*(lqMinimum number of octets in a PDU\*(rq
.PD 0
.IP "\*(lqReceive window size, RW\*(rq
.IP "\*(lqReject timer\*(rq
.IP "\*(lqBusy-state timer\*(rq
.PD
.RE
.IP \(em
.B DL_ALTER
is provided by
.B @PACKAGE_TITLE@
for source compatibility with DLS Providers and Users written for use with
.IR AIX \(rg,
and for porting DLS Providers and Users from
.IR AIX \(rg
to
.IR Linux \(rg.
Binary compatibility is not attempted.  Any binary compatibility experienced
may be removed from a future release.
.PP
See
.BR dlpi_ioctl (4),
.BR dlpi (7),
.BR STREAMS (9),
for additional compatiblity information.
.\"
.\"
.SH CONFORMANCE
.PP
None.
.\"
.\"
.SH HISTORY
.PP
The GDLC input-output controls are specific to
.IR AIX \(rg.
.[
aixdlpi
.]
.\"
.\"
.[
$LIST$
.]
.\"
.TI
