'\" rtp
.\" -*- nroff -*- vim: ft=nroff nocin nosi
.\"
.\" @(#) $Id: osr61.5.man,v 0.9.2.1 2007/02/25 12:45:05 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (c) 2001-2007  OpenSS7 Corporation <http://www.openss7.com/>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.  The author(s) will take no responsibility in it.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" -------------------------------------------------------------------------
.\"
.\" U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
.\" on behalf of the U.S. Government ("Government"), the following
.\" provisions apply to you.  If the Software is supplied by the Department
.\" of Defense ("DoD"), it is classified as "Commercial Computer Software"
.\" under paragraph 252.227-7014 of the DoD Supplement to the Federal
.\" Acquisition Regulations ("DFARS") (or any successor regulations) and the
.\" Government is acquiring only the license rights granted herein (the
.\" license rights customarily provided to non-Government users).  If the
.\" Software is supplied to any unit or agency of the Government other than
.\" DoD, it is classified as "Restricted Computer Software" and the
.\" Government's rights in the Software are defined in paragraph 52.227-19
.\" of the Federal Acquisition Regulations ("FAR") (or any successor
.\" regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
.\" NASA Supplement to the FAR (or any successor regulations).
.\"
.\" =========================================================================
.\" 
.\" Commercial licensing and support of this software is available from
.\" OpenSS7 Corporation at a fee.  See http://www.openss7.com/
.\" 
.\" =========================================================================
.\"
.\" Last Modified $Date: 2007/02/25 12:45:05 $ by $Author: brian $
.\"
.\" -------------------------------------------------------------------------
.\"
.\" $Log: osr61.5.man,v $
.\" Revision 0.9.2.1  2007/02/25 12:45:05  brian
.\" - added new files for release package
.\"
.\" =========================================================================
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database osr61.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.so osr61.macros
.\"
.\"
.TH STRTTY 5 "@PACKAGE_DATE@" "@PACKAGE@-@VERSION@" "@PACKAGE_TITLE@ System File Formats"
.\"
.\"
.SH NAME
.B @PACKAGE@
\- @PACKAGE_TITLE@ package
.\"
.\"
.SH OVERVIEW
.PP
This is the
.BR "@PACKAGE_TITLE@ " ( @PACKAGE@-@VERSION@ )
package for
.BR "Linux Fast-STREAMS" .
.PP
OpenSS7
.I STREAMS
add-on packages are separate add-on packages to the
.B Linux Fast-STREAMS
.[
lfs
.]
release that provide additional functionality and protocol support not traditionally found on UNIX
systems, or which have traditionally fallen into the domain of value-add system software, or where
the functionality was optional for a number of implementations.  The
.B @PACKAGE_TITLE@
package is one of several optional add-on packages that provides enhanced
.I STREAMS
support beyond that provided by the base
.I STREAMS
packages.  This package provides support for the
.I Dialogic Open System Release 6.1
not provided by the base
.I STREAMS
package.
.\"
.\"
.SH DESCRIPTION
.PP
The
.B @PACKAGE_TITLE@
package provides
.I STREAMS
modules and drivers, libraries, programs, initialization scripts, and daemons that
implement the 
.IR "Dialogic Open System Release 6.1" .
.PP
The package builds and installs the following
.I STREAMS
kernel modules and drivers:
.IP \(en \w'\(en\(em'u
.B streams_gncfd.ko
driver
.IP \(en
.B streams_dlgn.ko
driver
.IP \(en
.B streams_dvbm.ko
module
.IP \(en
.B streams_gpio.ko
driver
.IP \(en
.B streams_sctmr.ko
module
.IP \(en
.B streams_pty.ko
driver
.RI \(lq /dev/ptmx \(rq,
.RI \(lq /dev/pts/0 \(rq.
.PD 0
.IP \(en
.B streams_ptem.ko
module
.RI \(lq ptem \(rq.
.IP \(en
.B streams_pckt.ko
module
.RI \(lq pckt \(rq.
.IP \(en
.B streams_ldterm.ko
module
.RI \(lq ldterm \(rq.
.IP \(en
.B streams_ttcompat.ko
module
.RI \(lq ttcompat \(rq.
.PD
.TP
.BR pty (4)
The
.BR pty (4)
driver is a Pseudo-Terminal Driver that provides the classical
.IR UNIX \(rg
master and slave pseudo-terminals.
.IP ""
This driver is complete but untested.
.TP
.BR ptem (4)
The
.BR ptem (4)
module is a Pseudo-Terminal Emulation Module that provide
hardware terminal emulation for the slave side of a Pseudo-Terminal provided
by the
.BR pty (4)
driver.  This module is pushed over the slave side of a
pseudo-terminal before pusing
.BR ldterm (4).
.IP ""
This module is complete but untested.
.TP
.BR pckt (4)
The
.BR pckt (4)
module is a Packet Module.  This is the classical
.IR UNIX \(rg
packetization module that is pushed over the master side of a pseudo-terminal
to allow the master to view the detailed state of the pseudo-terminal.
.IP ""
This module is complete but untested.
.TP
.BR ldterm (4)
The
.BR ldterm (4)
module is a Line Discipline Terminal Module.  This
is the classical
.IR UNIX \(rg
line discipline module for terminals.  This module
is pushed last on the slave side of a psuedo-terminal, after
.BR ptem (4)
and
provides the
.I POSIX
.[
susv3
.]
terminal interface to the user.
.IP ""
This module is incomplete.
.TP
.BR ttcompat (4)
The
.BR ttcompat (4)
module is a TTY Compatibility Module.  This is a module that
provides
.IR UNIX \(rg " Version 7"
and
.I 4BSD
compatible terminal interfaces.  These
interfaces are no longer in use and this module has only marginal value.
.IP ""
This module is incomplete.
.PP
The package builds and installs the following shared object libraries:
.TP
.BR libtty (3)
The
.BR libtty (3)
library provides replacements for
.I POSIX
.[
susv3
.]
terminal handling
functions that are not properly implemented in
`glibc'.  These functions are:
.RS
.TP \w'\fBunlockpt\fR(3tty)\(em'u
.BR openpt (3tty)
\-\ open a master pseudo-terminal
.PD 0
.TP
.BR ptsname (3tty)
\-\ obtain name for slave device
.TP
.BR grantpt (3tty)
\-\ grant access to the slave device
.TP
.BR unlockpt (3tty)
\-\ unlock the pseudo-terminal
.PD
.RE
.PP
This library is incomplete.
.PP
The
.B @PACKAGE_TITLE@
package includes kernel modules,
.I "SVR 4.2"
.[
svr42
.]
.I STREAMS
drivers, modules, libraries, utilities, test programs, daemons, and
development environment for the development and execution of
.B @PACKAGE_TITLE@
protocol stack components and applications for the
.I "SVR 4.2"
.I STREAMS
environment.
.PP
This distribution is only currently applicable to
.B Linux
2.4 and 2.6 kernels and was targeted at
.IR ix86 ", " x86_64 ", " ppc " and " ppc64
architectures, but should build and install for other architectures as well.
.PP
This package is currently incomplete.
It is being released as a reference point for the community.  If you are interested in completion of
this package, contact
.RB < info@openss7.com >.
.\"
.\"
.SH "PACKAGE CONTENTS"
.PP
The
.BR "@PACKAGE_TITLE@ " ( @PACKAGE@-@VERSION@ )
package contains the following manual pages:
.HP
.BR grantpt (3tty)\ \-\ \c
grant access to a slave pseudo-terminal device.
.PD 0
.HP
.BR ptsname (3tty)\ \-\ \c
get the file system path to a slave pseudo-terminal device.
.HP
.BR unlockpt (3tty)\ \-\ \c
unlock a slave pseudo-terminal device.
.HP
.BR ldterm (4)\ \-\ \c
Line Discipline \fISTREAMS\fR module.
.HP
.BR pckt (4)\ \-\ \c
Packet mode \fISTREAMS\fR module.
.HP
.BR ptc (4)\ \-\ \c
controlling pty device.
.HP
.BR ptem (4)\ \-\ \c
Pseudo-Terminal Emulation Module.
.HP
.BR ptm (4)\ \-\ \c
Master pseudo-terminal driver.
.HP
.BR ptmx (4tty)\ \-\ \c
Master pseduo-terminal \fBclone\fR(4) device.
.HP
.BR pts (4tty)\ \-\ \c
Slave pseudo-terminal driver.
.HP
.BR pty (4)\ \-\ \c
Pseudo-terminal drivers.
.HP
.BR ttcompat (4)\ \-\ \c
TTY compatibility \fISTREAMS\fR module.
.HP
.BR osr61 (5)\ \-\ \c
The \fB@PACKAGE_TITLE@\fR package.
.HP
.BR osr61 (8)\ \-\ \c
create \fB@PACKAGE@\fR device nodes.
.HP
.BR test-tty (8)\ \-\ \c
test case executable for the \fB@PACKAGE@\fR package.
.PD
.\"
.\"
.SH MODULES
.PP
The
.B osr61
package provides the following
.I STREAMS
modules:
.HP
.BR pckt (4)\ \-\ \c
Packet Mode module.
.PD 0
.HP
.BR ptem (4)\ \-\ \c
Pseudo-terminal Emulation modules.
.HP
.BR ldterm (4)\ \-\ \c
Line Discipline for Terminals module.
.HP
.BR ttcompat (4)\ \-\ \c
Teletypewriter compatibiltiy module.
.PD
.\"
.\"
.SH DEVICES
.PP
The
.B osr61
package provides the following
.I STREAMS
drivers:
.HP
.BR pty (4)\ \-\ \c
Pseudo-terminal device driver.
.\"
.\"
.\".SH FILES
.\".PP
.\"
.\"
.SH PREREQUISITES
.PP
The
.B @PACKAGE@
package request the following packages to be installed:
.TP
.BR streams (5)
The
.B Linux Fast-STREAMS
base package.
.TP
.BR strcompat (5)
The
.B Linux Fast-STREAMS
compatibility modules package.
.\"
.\"
.SH NOTICES
.PP
No release of the
.B @PACKAGE@
package is compatible with
.IR LiS .
.I LiS
lacks the Stream head support necessary to properly implement a terminal device.  As
.I LiS
is long deprecated, this should not present a problem.  The
.B @PACKAGE@
package is comatible with
.BR "Linux Fast-STREAMS" ,
which always contained full terminal support in the Stream head.
.PP
The
.B @PACKAGE_TITLE@
package has known and unknown defects.  This is a
.I pre-alpha
release.  Some defects might be harmful.  No validation testing whatsoever has been performed by the
.I OpenSS7 Project
on this software.  The software might not even configure or compile.  The
.I OpenSS7 Project
recommends that you do not use this software. Use at your own risk.  Remember that there is
.BR "NO WARRANTY" .
(See the section
.RI \(lq "NO WARRANTY" \(rq
under the
.RI \(lq "GNU General Public License" \(rq,
in the manual.)
.PP
This software is
.I pre-alpha
software.  As such, it will crash your kernel.  Installation of the software will irreparably mangle
your header files or Linux distribution in such a way as to make it unusable.  Crashes will lock
your system and rebooting the system will not repair the problem.  You will lose all the data on
your system.  Because this software will crash your kernel, the resulting unstable system can
destroy computer hardware or peripherals making them unusable.  You will void the warranty on any
system on which you run this software.
.BR "YOU HAVE BEEN WARNED" .
.\"
.\"
.SH BUGS
.PP
The
.B @PACKAGE@
package is compatible with a wide array of production
.B Linux
distributions, kernels, and target architectures, but is considered
.I pre-alpha
grade by
.IR "The OpenSS7 Project" .
At the time of release, the
.B @PACKAGE@
package had no known bugs.  Problems or development requests can be reported to
.RB < bugs@openss7.org >.
Please, however, use the included
.B send-pr
script for generating actionable problem reports or development requests.
Please see the file
.RI \(lq PROBLEMS \(rq
in the release for problem reporting guidelines.
.\"
.\"
.SH "SEE ALSO"
.PP
.BR grantpt (3tty),
.BR ptsname (3tty),
.BR unlockpt (3tty),
.BR ldterm (4),
.BR pckt (4),
.BR ptc (4),
.BR ptem (4),
.BR ptm (4),
.BR ptmx (4tty),
.BR pts (4tty),
.BR pty (4),
.BR ttcompat (4),
.BR osr61 (5),
.BR osr61_mknod (8),
.BR test-tty (8).
.\"
.\"
.SH COMPATIBILITY
.PP
The
.B @PACKAGE@
package is compatible with
.I "SVR 4.2"
and systems based on
.IR "SVR 4.2" ,
such as
.IR Solaris \(rg
and
.IR UnixWare \(rg,
with the following portability considerations:
.IP \(em \w'\(em\(em'u
An attempt was made to make each of the modules and drivers contained in this
package as compatible as possible with all documented implementations of the
.I SVR 4
style
.I "Terminal Subsystem" .
As the package is incomplete and as yet does not have a fully functional
validation test suite, this claim is currently difficult to substatiate.
.IP \(em
There is some deviation between documented implementations of the
.BR pckt (4)
module.  In fact, it appears that many implementations do this somewhat
differently.  One of the major problems is how many bytes are included to hold
the message type.  See
.BR pckt (4)
for more information.
.IP \(em
Each manual page contains compatibility information that was documented during
the development of the associated component.  Please refer to the individual
manual pages for additional compatibility information.
.\"
.\"
.SH CONFORMANCE
.PP
.IR "UNIX95" ,
.IR "UNIX98" ,
.IR "SUSv2" ,
.[
susv2
.]
.IR "SUSv3" ,
.[
susv3
.]
.IR "SVR 4.2" ,
.[
svr42spg
.]
.IR Solaris \(rg,
.[
solspg
.]
.IR UnixWare \(rg.
.[
uw7spg
.]
.PP
Much of the behavior of
.I SVR 4
pseudo-terminals within the
.I SVR 4 Terminal Subsystem
made it into
.I POSIX
and particularly into the
.I UNIX 98
specifications from the
.IR OpenGroup .
Consult individual manual pages for additional conformance information.
.\"
.\"
.SH HISTORY
.PP
The first
.IR STREAMS -based
.I Terminal Subsystem
was released with
.IR "SVR 4" .
.PP
The
.B @PACKAGE@
package was first publicly released (version
.BR 0.9.2.1 )
at the end of 2006.
.\"
.\"
.[
$LIST$
.]
.\"
.TI
