/*****************************************************************************

 @(#) $Id: m2uaMIB.h,v 0.9.2.1 2008-12-27 10:01:52 brian Exp $

 -----------------------------------------------------------------------------

 Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
 Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>

 All Rights Reserved.

 This program is free software; you can redistribute it and/or modify it under
 the terms of the GNU Affero General Public License as published by the Free
 Software Foundation; version 3 of the License.

 This program is distributed in the hope that it will be useful, but WITHOUT
 ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 FOR A PARTICULAR PURPOSE.  See the GNU Affero General Public License for more
 details.

 You should have received a copy of the GNU Affero General Public License
 along with this program.  If not, see <http://www.gnu.org/licenses/>, or
 write to the Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA
 02139, USA.

 -----------------------------------------------------------------------------

 U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
 behalf of the U.S. Government ("Government"), the following provisions apply
 to you.  If the Software is supplied by the Department of Defense ("DoD"), it
 is classified as "Commercial Computer Software" under paragraph 252.227-7014
 of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
 successor regulations) and the Government is acquiring only the license rights
 granted herein (the license rights customarily provided to non-Government
 users).  If the Software is supplied to any unit or agency of the Government
 other than DoD, it is classified as "Restricted Computer Software" and the
 Government's rights in the Software are defined in paragraph 52.227-19 of the
 Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
 the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
 (or any successor regulations).

 -----------------------------------------------------------------------------

 Commercial licensing and support of this software is available from OpenSS7
 Corporation at a fee.  See http://www.openss7.com/

 -----------------------------------------------------------------------------

 Last Modified $Date: 2008-12-27 10:01:52 $ by $Author: brian $

 -----------------------------------------------------------------------------

 $Log: m2uaMIB.h,v $
 Revision 0.9.2.1  2008-12-27 10:01:52  brian
 - updated mibs and stubs

 *****************************************************************************/

#ifndef __LOCAL_M2UAMIB_H__
#define __LOCAL_M2UAMIB_H__

#ident "@(#) $RCSfile: m2uaMIB.h,v $ $Name: OpenSS7-0_9_2 $($Revision: 0.9.2.1 $) Copyright (c) 2001-2008 OpenSS7 Corporation."

/*
 * This file was generated by mib2c and is intended for use as a mib module
 * for the ucd-snmp snmpd agent.
 */
/* our storage structure(s) */
struct m2uaMIB_data {
	uint m2uaMIB_request;
	uint32_t m2uaAsNextIndex;

	uint32_t m2uaIfNextIndex;

	uint32_t m2uaAspNextIndex;

	uint32_t m2uaSgNextIndex;

};
struct m2uaAsTable_data {
	uint m2uaAsTable_request;
	uint32_t m2uaAsIndex;
	char *m2uaAsName;
	int m2uaAsNameLen;
	int32_t m2uaAsAdministrativeState;
	int32_t m2uaAsOperationalState;
	char *m2uaAsProceduralStatus;
	int m2uaAsProceduralStatusLen;
	int32_t m2uaASUsageState;
	int32_t m2uaAsStatus;
};
struct m2uaIfTable_data {
	uint m2uaIfTable_request;
	uint32_t m2uaIfIndex;
	char *m2uaIfName;
	int m2uaIfNameLen;
	uint32_t m2uaIfAsIndex;
	int32_t m2uaIfIdNum;
	char *m2uaIfIdName;
	int m2uaIfIdNameLen;
	int32_t m2uaIfAdministrativeState;
	int32_t m2uaIfOperationalState;
	char *m2uaIfProceduralStatus;
	int m2uaIfProceduralStatusLen;
	int32_t m2uaIfUsageState;
	oid *m2uaIfEquipment;
	int m2uaIfEquipmentLen;
	int32_t m2uaIfMaxSifSize;
	int32_t m2uaIfTransmissionRate;
	int32_t m2uaIfCic;
	int32_t m2uaIfRowStatus;
};
struct m2uaAsIfTable_data {
	uint m2uaAsIfTable_request;
	uint32_t m2uaIfIndex;
};
struct m2uaAspTable_data {
	uint m2uaAspTable_request;
	uint32_t m2uaAspIndex;
	char *m2uaAspName;
	int m2uaAspNameLen;
	uint32_t m2uaSgIndex;
	int32_t m2uaAspAdministrativeState;
	int32_t m2uaAspOperationalState;
	int32_t m2uaAspUsageState;
	char *m2uaAspProceduralStatus;
	int m2uaAspProceduralStatusLen;
	int32_t m2uaAspState;
	int32_t m2uaAspRowStatus;
};
struct m2uaAspSgTable_data {
	uint m2uaAspSgTable_request;
	uint32_t m2uaAspIndex;
	uint32_t m2uaSgIndex;
	uint32_t m2uaAspSgAspId;
	int32_t m2uaAspSgAspPort;
	int32_t m2uaAspSgAspState;
	int32_t m2uaAspSgAdministrativeState;
};
struct m2uaSgTable_data {
	uint m2uaSgTable_request;
	uint32_t m2uaSgIndex;
	char *m2uaSgName;
	int m2uaSgNameLen;
	int32_t m2uaSgRowStatus;
};
struct m2uaSgAspTable_data {
	uint m2uaSgAspTable_request;
	uint32_t m2uaSgIndex;
	uint32_t m2uaAspIndex;
	uint32_t m2uaSgAspId;
	int32_t m2uaSgAspPort;
	int32_t m2uaSgAspState;
	int32_t m2uaSgAspAdministrativeState;
	int32_t m2uaSgAspOperationalState;
};
struct m2uaSgAspAsTable_data {
	uint m2uaSgAspAsTable_request;
	uint32_t m2uaSgIndex;
	uint32_t m2uaAspIndex;
	uint32_t m2uaAsIndex;
	int32_t m2uaSgAspAsRegistrationRequired;
	int32_t m2uaSgAspAsState;
	int32_t m2uaSgAspAsAdministrativeState;
	int32_t m2uaSgAspAsOperationalState;
};
struct m2uaSgAsTable_data {
	uint m2uaSgAsTable_request;
	uint32_t m2uaSgIndex;
	uint32_t m2uaAsIndex;
	oid *m2uaSgAsTrafficMode;
	int m2uaSgAsTrafficModeLen;
	int32_t m2uaSgAsState;
	int32_t m2uaSgAsAdministrativeState;
	int32_t m2uaSgAsOperationalState;
	int32_t m2uaSgAsRowStatus;
};

/* storage declarations */
extern struct m2uaMIB_data *m2uaMIBStorage;
extern struct header_complex_index *m2uaAsTableStorage;
extern struct header_complex_index *m2uaIfTableStorage;
extern struct header_complex_index *m2uaAsIfTableStorage;
extern struct header_complex_index *m2uaAspTableStorage;
extern struct header_complex_index *m2uaAspSgTableStorage;
extern struct header_complex_index *m2uaSgTableStorage;
extern struct header_complex_index *m2uaSgAspTableStorage;
extern struct header_complex_index *m2uaSgAspAsTableStorage;
extern struct header_complex_index *m2uaSgAsTableStorage;

/* enum definitions from the covered mib sections */

#define M2UAASADMINISTRATIVESTATE_LOCKED         0
#define M2UAASADMINISTRATIVESTATE_UNLOCKED       1
#define M2UAASADMINISTRATIVESTATE_SHUTTINGDOWN   2

#define M2UAASOPERATIONALSTATE_DISABLED          0
#define M2UAASOPERATIONALSTATE_ENABLED           1

#define M2UAASPROCEDURALSTATUS_INITIALIZATIONREQUIRED 0
#define M2UAASPROCEDURALSTATUS_NOTINITIALIZED    1
#define M2UAASPROCEDURALSTATUS_INITIALIZING      2
#define M2UAASPROCEDURALSTATUS_REPORTING         3
#define M2UAASPROCEDURALSTATUS_TERMINATING       4

#define M2UAASUSAGESTATE_IDLE                    0
#define M2UAASUSAGESTATE_ACTIVE                  1
#define M2UAASUSAGESTATE_BUSY                    2

#define M2UAIFADMINISTRATIVESTATE_LOCKED         0
#define M2UAIFADMINISTRATIVESTATE_UNLOCKED       1
#define M2UAIFADMINISTRATIVESTATE_SHUTTINGDOWN   2

#define M2UAIFOPERATIONALSTATE_DISABLED          0
#define M2UAIFOPERATIONALSTATE_ENABLED           1

#define M2UAIFPROCEDURALSTATUS_INITIALIZATIONREQUIRED 0
#define M2UAIFPROCEDURALSTATUS_NOTINITIALIZED    1
#define M2UAIFPROCEDURALSTATUS_INITIALIZING      2
#define M2UAIFPROCEDURALSTATUS_REPORTING         3
#define M2UAIFPROCEDURALSTATUS_TERMINATING       4

#define M2UAIFUSAGESTATE_IDLE                    0
#define M2UAIFUSAGESTATE_ACTIVE                  1
#define M2UAIFUSAGESTATE_BUSY                    2

#define M2UAIFMAXSIFSIZE_LSL                     0
#define M2UAIFMAXSIFSIZE_HSL                     1
#define M2UAIFMAXSIFSIZE_ATM                     2

#define M2UAIFTRANSMISSIONRATE_UNKNOWN           0
#define M2UAIFTRANSMISSIONRATE_MODEM             1
#define M2UAIFTRANSMISSIONRATE_DS0A              2
#define M2UAIFTRANSMISSIONRATE_DS0               3
#define M2UAIFTRANSMISSIONRATE_T1J1              4
#define M2UAIFTRANSMISSIONRATE_E1                5
#define M2UAIFTRANSMISSIONRATE_ATM               6

#define M2UAASPADMINISTRATIVESTATE_LOCKED        0
#define M2UAASPADMINISTRATIVESTATE_UNLOCKED      1
#define M2UAASPADMINISTRATIVESTATE_SHUTTINGDOWN  2

#define M2UAASPOPERATIONALSTATE_DISABLED         0
#define M2UAASPOPERATIONALSTATE_ENABLED          1

#define M2UAASPUSAGESTATE_IDLE                   0
#define M2UAASPUSAGESTATE_ACTIVE                 1
#define M2UAASPUSAGESTATE_BUSY                   2

#define M2UAASPPROCEDURALSTATUS_INITIALIZATIONREQUIRED 0
#define M2UAASPPROCEDURALSTATUS_NOTINITIALIZED   1
#define M2UAASPPROCEDURALSTATUS_INITIALIZING     2
#define M2UAASPPROCEDURALSTATUS_REPORTING        3
#define M2UAASPPROCEDURALSTATUS_TERMINATING      4

#define M2UAASPSTATE_ASPDOWN                     0
#define M2UAASPSTATE_ASPUP                       1

#define M2UAASPSGASPSTATE_DOWN                   1
#define M2UAASPSGASPSTATE_INITIALIZING           2
#define M2UAASPSGASPSTATE_TERMINATING            3
#define M2UAASPSGASPSTATE_UP                     4

#define M2UAASPSGADMINISTRATIVESTATE_LOCKED      0
#define M2UAASPSGADMINISTRATIVESTATE_UNLOCKED    1
#define M2UAASPSGADMINISTRATIVESTATE_SHUTTINGDOWN 2

#define M2UASGASPSTATE_DOWN                      1
#define M2UASGASPSTATE_INITIALIZING              2
#define M2UASGASPSTATE_TERMINATING               3
#define M2UASGASPSTATE_UP                        4

#define M2UASGASPADMINISTRATIVESTATE_LOCKED      0
#define M2UASGASPADMINISTRATIVESTATE_UNLOCKED    1
#define M2UASGASPADMINISTRATIVESTATE_SHUTTINGDOWN 2

#define M2UASGASPOPERATIONALSTATE_DISABLED       0
#define M2UASGASPOPERATIONALSTATE_ENABLED        1

#define M2UASGASPASREGISTRATIONREQUIRED_UNKNOWN  1
#define M2UASGASPASREGISTRATIONREQUIRED_FORBIDDEN 2
#define M2UASGASPASREGISTRATIONREQUIRED_PERMITTED 3
#define M2UASGASPASREGISTRATIONREQUIRED_REQUIRED 4

#define M2UASGASPASSTATE_DOWN                    1
#define M2UASGASPASSTATE_INITIALIZING            2
#define M2UASGASPASSTATE_TERMINATING             3
#define M2UASGASPASSTATE_INACTIVE                4
#define M2UASGASPASSTATE_ACTIVATING              5
#define M2UASGASPASSTATE_DEACTIVATING            6
#define M2UASGASPASSTATE_ACTIVE                  7

#define M2UASGASPASADMINISTRATIVESTATE_LOCKED    0
#define M2UASGASPASADMINISTRATIVESTATE_UNLOCKED  1
#define M2UASGASPASADMINISTRATIVESTATE_SHUTTINGDOWN 2

#define M2UASGASPASOPERATIONALSTATE_DISABLED     0
#define M2UASGASPASOPERATIONALSTATE_ENABLED      1

#define M2UASGASSTATE_DOWN                       1
#define M2UASGASSTATE_INITIALIZING               2
#define M2UASGASSTATE_TERMINATING                3
#define M2UASGASSTATE_INACTIVE                   4
#define M2UASGASSTATE_ACTIVATING                 5
#define M2UASGASSTATE_DEACTIVATING               6
#define M2UASGASSTATE_ACTIVE                     7

#define M2UASGASADMINISTRATIVESTATE_LOCKED       0
#define M2UASGASADMINISTRATIVESTATE_UNLOCKED     1
#define M2UASGASADMINISTRATIVESTATE_SHUTTINGDOWN 2

#define M2UASGASOPERATIONALSTATE_DISABLED        0
#define M2UASGASOPERATIONALSTATE_ENABLED         1

/* function prototypes */
void init_m2uaMIB(void);
void deinit_m2uaMIB(void);
int term_m2uaMIB(int majorID, int minorID, void *serverarg, void *clientarg);
FindVarMethod var_m2uaMIB;
void parse_m2uaMIB(const char *, char *);
SNMPCallback store_m2uaMIB;
void refresh_m2uaMIB(void);
FindVarMethod var_m2uaAsTable;
void parse_m2uaAsTable(const char *, char *);
SNMPCallback store_m2uaAsTable;
void refresh_m2uaAsTable(void);
FindVarMethod var_m2uaIfTable;
void parse_m2uaIfTable(const char *, char *);
SNMPCallback store_m2uaIfTable;
void refresh_m2uaIfTable(void);
FindVarMethod var_m2uaAsIfTable;
void parse_m2uaAsIfTable(const char *, char *);
SNMPCallback store_m2uaAsIfTable;
void refresh_m2uaAsIfTable(void);
FindVarMethod var_m2uaAspTable;
void parse_m2uaAspTable(const char *, char *);
SNMPCallback store_m2uaAspTable;
void refresh_m2uaAspTable(void);
FindVarMethod var_m2uaAspSgTable;
void parse_m2uaAspSgTable(const char *, char *);
SNMPCallback store_m2uaAspSgTable;
void refresh_m2uaAspSgTable(void);
FindVarMethod var_m2uaSgTable;
void parse_m2uaSgTable(const char *, char *);
SNMPCallback store_m2uaSgTable;
void refresh_m2uaSgTable(void);
FindVarMethod var_m2uaSgAspTable;
void parse_m2uaSgAspTable(const char *, char *);
SNMPCallback store_m2uaSgAspTable;
void refresh_m2uaSgAspTable(void);
FindVarMethod var_m2uaSgAspAsTable;
void parse_m2uaSgAspAsTable(const char *, char *);
SNMPCallback store_m2uaSgAspAsTable;
void refresh_m2uaSgAspAsTable(void);
FindVarMethod var_m2uaSgAsTable;
void parse_m2uaSgAsTable(const char *, char *);
SNMPCallback store_m2uaSgAsTable;
void refresh_m2uaSgAsTable(void);

WriteMethod write_m2uaAsName;
WriteMethod write_m2uaAsAdministrativeState;
WriteMethod write_m2uaAsStatus;
WriteMethod write_m2uaIfName;
WriteMethod write_m2uaIfAsIndex;
WriteMethod write_m2uaIfIdNum;
WriteMethod write_m2uaIfIdName;
WriteMethod write_m2uaIfAdministrativeState;
WriteMethod write_m2uaIfEquipment;
WriteMethod write_m2uaIfMaxSifSize;
WriteMethod write_m2uaIfTransmissionRate;
WriteMethod write_m2uaIfCic;
WriteMethod write_m2uaIfRowStatus;
WriteMethod write_m2uaSgIndex;
WriteMethod write_m2uaAspAdministrativeState;
WriteMethod write_m2uaAspOperationalState;
WriteMethod write_m2uaAspRowStatus;
WriteMethod write_m2uaSgIndex;
WriteMethod write_m2uaAspSgAspId;
WriteMethod write_m2uaAspSgAspPort;
WriteMethod write_m2uaAspSgAdministrativeState;
WriteMethod write_m2uaSgName;
WriteMethod write_m2uaSgRowStatus;
WriteMethod write_m2uaSgIndex;
WriteMethod write_m2uaSgAspId;
WriteMethod write_m2uaSgAspPort;
WriteMethod write_m2uaSgAspAdministrativeState;
WriteMethod write_m2uaSgIndex;
WriteMethod write_m2uaSgAspAsRegistrationRequired;
WriteMethod write_m2uaSgAspAsAdministrativeState;
WriteMethod write_m2uaSgIndex;
WriteMethod write_m2uaSgAsTrafficMode;
WriteMethod write_m2uaSgAsState;
WriteMethod write_m2uaSgAsAdministrativeState;
WriteMethod write_m2uaSgAsRowStatus;

#endif				/* __LOCAL_M2UAMIB_H__ */
