#!/bin/sh
#
# @(#) $RCSfile: specfs,v $ $Name:  $($Revision: 0.9.2.4 $) $Date: 2005/02/13 12:16:21 $
# Copyright (c) 2001-2005  OpenSS7 Corporation <http://www.openss7.com>
# Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
# All Rights Reserved.
#
# Distributed by OpenSS7 Corporation.  See the bottom of this script for copying
# permissions.
#
# Redhat chkconfig init script conventions
#
# specfs:	mount and unmount specfs
# chkconfig:	2345 55 88
# lockfile:	/var/lock/subsys/specfs
# config:	/etc/sysconfig/specfs
# probe:	true
# hide:		false
# license:	GPL
# description:	The SPECFS is a special shadow filesystem used for \
#		Linux Fast-STREAMS.  The purpose of this init script \
#		is to detect whether the specfs is supported for the \
#		running kernel, and if it is, to configure and load \
#		the kernel module associated with the special filesystem.
#
# LSB init init script conventions
#
### BEGIN INIT INFO
# Provides: specfs
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: mount and unmount specfs
# License: GPL
# Description:	The SPECFS is a special shadow filesystem used for Linux
#	Fast-STREAMS.  The purpose of this init script is to detect whether the
#	specfs is supported for the running kernel, and if it is, to configure
#	and load the kernel module associated with the special filesystem.
### END INIT INFO

# Source init script functions library
. /etc/init.d/functions

# Specify defaults

MOUNTPOINT="/dev/streams"

# Source redhat and/or debian config file
[ -f /etc/specfs.conf ] && . /etc/specfs.conf
[ -f /etc/default/specfs ] && . /etc/default/specfs
[ -f /etc/sysconfig/specfs.conf ] && . /etc/sysconfig/specfs

RETVAL=0

umask 077

start() {
    echo "Mounting SPECFS filesystem: "
    [ -d /dev/streams ] || mkdir -p /dev/streams || return 1
    mount -t specfs specfs $MOUNTPOINT
    # FIXME: add options
    RETVAL=$?
    echo ""
    [ $RETVAL -eq 0 ] && touch /var/log/subsys/specfs
    return $RETVAL
}

stop() {
}

probe() {
#
#   subsystem unlocked, need to start
#
    [ ! -f /var/log/subsys/strace ] && { echo 'start' ; return 0 }
#
#   unmounted but subsystem locked, need to restart
#
    ( grep -q '\<specfs\>' /etc/mtab | grep -q '/dev/streams' ) 2>/dev/null \
    || { echo 'restart' ; return 0 }
#
#   configuration files updated, need to reload
#
    [ -f /etc/sysconfig/specfs -a /etc/sysconfig/specfs -nt /var/lock/subsys/specfs ] \
    && { echo 'reload' ; return 0 }
    [ -f /etc/default/specfs   -a /etc/default/specfs   -nt /var/lock/subsys/specfs ] \
    && { echo 'reload' ; return 0 }
    [ -f /etc/specfs.conf      -a /etc/specfs.conf      -nt /var/lock/subsys/specfs ] \
    && { echo 'reload' ; return 0 }
#
#   do not need to do anything
#
    return $?
}

# =============================================================================
# 
# @(#) $RCSfile: specfs,v $ $Name:  $($Revision: 0.9.2.4 $) $Date: 2005/02/13 12:16:21 $
#
# -----------------------------------------------------------------------------
#
# Copyright (c) 2001-2005  OpenSS7 Corporation <http://www.openss7.com>
# Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
#
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 675 Mass
# Ave, Cambridge, MA 02139, USA.
#
# -----------------------------------------------------------------------------
#
# U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
# behalf of the U.S. Government ("Government"), the following provisions apply
# to you.  If the Software is supplied by the Department of Defense ("DoD"), it
# is classified as "Commercial Computer Software" under paragraph 252.227-7014
# of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
# successor regulations) and the Government is acquiring only the license rights
# granted herein (the license rights customarily provided to non-Government
# users).  If the Software is supplied to any unit or agency of the Government
# other than DoD, it is classified as "Restricted Computer Software" and the
# Government's rights in the Software are defined in paragraph 52.227-19 of the
# Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
# the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
# (or any successor regulations).
#
# -----------------------------------------------------------------------------
#
# Commercial licensing and support of this software is available from OpenSS7
# Corporation at a fee.  See http://www.openss7.com/
#
# -----------------------------------------------------------------------------
#
# Last Modified $Date: 2005/02/13 12:16:21 $ by $Author: brian $
#
# =============================================================================

# vim: ft=sh sw=4 tw=80
