#!/bin/sh
#
# @(#) $RCSfile: strace,v $ $Name:  $($Revision: 0.9.2.3 $) $Date: 2005/02/13 12:16:21 $
# Copyright (c) 2001-2005  OpenSS7 Corporation <http://www.openss7.com>
# Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
# All Rights Reserved.
#
# Distributed by OpenSS7 Corporation.  See the bottom of this script for copying
# permissions.
#
# Redhat chkconfig init script conventions
#
# strace:	start and stop strace facility
# chkconfig:	- 55 88
# processname:	strace
# pidfile:	/var/run/strace.pid
# lockfile:	/var/lock/subsys/strace
# config:	/etc/sysconfig/strace
# probe:	true
# hide:		false
# license:	GPL
# description:	This STREAMS init script is part of Linux Fast-STREAMS.  It is \
#		responsible for starting and stopping the STREAMS trace \
#		logger.  The STREAMS trace logger should only be run under \
#		exceptional circumstances and this init script not activated \
#		automatically.
#
# LSB init init script conventions
#
### BEGIN INIT INFO
# Provides: strace
# Required-Start: $local_fs $network $remote_fs specfs streams
# Required-Stop: $local_fs $network $remote_fs specfs streams
# Default-Start: 
# Default-Stop: 0 1 2 3 4 5 6
# Short-Description: start and stop strace
# License: GPL
# Description:	This STREAMS init script is part of Linux Fast-STREAMS.  It is
#	responsible for starting and stopping the STREAMS trace logger.  The
#	STREAMS trace logger should only be run under exceptional circumstances
#	and this init script is not activated in any run level by default.
### END INIT INFO

# Source init script functions library.
. /etc/init.d/functions

[ -f /sbin/strace ] || [ -f /usr/sbin/strace ] || exit 0

# Specify defaults

STRACEOPTIONS=""
DIRECTORY="/var/log/streams"
BASENAME="trace"
OUTFILE=""
ERRFILE=""
LOGDEVICE="/dev/streams/log"
MODULES=""

# Source redhat and/or debian config file
[ -f /etc/strace.conf ] && . /etc/strace.conf
[ -f /etc/default/strace ] && . /etc/default/strace
[ -f /etc/sysconfig/strace.conf ] && . /etc/sysconfig/strace

STRACE_OPTIONS="\
${STRACEOPTIONS:+ $STRACEOPTIONS}\
${DIRECTORY:+ -d $DIRECTORY}\
${BASENAME:+ -b $BASENAME}\
${OUTFILE:+ -o $OUTFILE}\
${ERRFILE:+ -e $ERRFILE}\
${LOGDEVICE:+ -l $LOGDEVICE}\
${MODULES:+ $MODULES}"

RETVAL=0

umask 077

start() {
    echo "Starting STREAMS trace logger: "
    daemon strace $STRACE_OPTIONS
    RETVAL=$?
    echo ""
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/strace
    return $RETVAL
}

stop() {
    echo "Shutting down STREAMS trace logger: "
    killproc strace
    RETVAL=$?
    echo ""
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/strace
    return $RETVAL
}

rhstatus() {
    status strace
}

reload() {
    echo "Reloading the STREAMS trace logger: "
    killproc strace -HUP
}

restart() {
    stop
    start
}

probe() {
#
#   subsystem unlocked, need to start
#
    [ ! -f /var/log/subsys/strace ] && { echo 'start' ; return 0 }
#
#   strace dead but subsystem locked, need to restart
#
    /sbin/pidof strace >/dev/null 2>&1 || { echo 'restart' ; return 0 }
#
#   configuration files updated, need to reload
#
    [ -f /etc/sysconfig/strace -a /etc/sysconfig/strace -nt /var/lock/subsys/strace ] \
    && { echo 'reload' ; return 0 }
    [ -f /etc/default/strace   -a /etc/default/strace   -nt /var/lock/subsys/strace ] \
    && { echo 'reload' ; return 0 }
    [ -f /etc/strace.conf      -a /etc/strace.conf      -nt /var/lock/subsys/strace ] \
    && { echo 'reload' ; return 0 }
#
#   do not need to do anything
#
    return $?
}

case "$1" in
    (start)
	start
	;;
    (stop)
	stop
	;;
    (status)
	rhstatus
	;;
    (restart)
	restart
	;;
    (reload)
	reload
	;;
    (condrestart)
	[ -f /var/lock/subsys/strace ] && restart || :
	;;
    (probe)
	probe
	;;
    (*)
	echo "Usage: $0 (start|stop|status|restart|condrestart|probe)\n"
	;;
esac

exit $?


# =============================================================================
# 
# @(#) $RCSfile: strace,v $ $Name:  $($Revision: 0.9.2.3 $) $Date: 2005/02/13 12:16:21 $
#
# -----------------------------------------------------------------------------
#
# Copyright (c) 2001-2005  OpenSS7 Corporation <http://www.openss7.com>
# Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
#
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 675 Mass
# Ave, Cambridge, MA 02139, USA.
#
# -----------------------------------------------------------------------------
#
# U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
# behalf of the U.S. Government ("Government"), the following provisions apply
# to you.  If the Software is supplied by the Department of Defense ("DoD"), it
# is classified as "Commercial Computer Software" under paragraph 252.227-7014
# of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
# successor regulations) and the Government is acquiring only the license rights
# granted herein (the license rights customarily provided to non-Government
# users).  If the Software is supplied to any unit or agency of the Government
# other than DoD, it is classified as "Restricted Computer Software" and the
# Government's rights in the Software are defined in paragraph 52.227-19 of the
# Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
# the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
# (or any successor regulations).
#
# -----------------------------------------------------------------------------
#
# Commercial licensing and support of this software is available from OpenSS7
# Corporation at a fee.  See http://www.openss7.com/
#
# -----------------------------------------------------------------------------
#
# Last Modified $Date: 2005/02/13 12:16:21 $ by $Author: brian $
#
# =============================================================================
# vim: sw=4 tw=80
