#!/bin/sh
#
# @(#) $RCSfile: streams,v $ $Name:  $($Revision: 0.9.2.4 $) $Date: 2005/02/14 06:47:18 $
# Copyright (c) 2001-2005  OpenSS7 Corporation <http://www.openss7.com>
# Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
# All Rights Reserved.
#
# Distributed by OpenSS7 Corporation.  See the bottom of this script for copying
# permissions.
#
# Redhat chkconfig init script conventions
#
# streams:	start and stop streams subsystem
# chkconfig:	2345 02 97
# lockfile:	/var/lock/subsys/streams
# config:	/etc/sysconfig/streams
# probe:	true
# hide:		false
# license:	GPL
# description:	This STREAMS init script is part of Linux Fast-STREAMS.  \
#		It is responsible for ensuring that the necessary STREAMS \
#		character devices are present in the /dev directory and \
#		that the STREAMS subsystem is configured and loaded.  It \
#		is also responsible for starting the STREAMS log and trace \
#		facilities.
#
# LSB init script conventions
#
### BEGIN INIT INFO
# Provides: streams
# Required-Start: specfs
# Required-Stop: specfs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: start and stop streams subsystem
# License: GPL
# Description:	This STREAMS init script is part of Linux Fast-STREAMS.  It is
#	reponsible for ensuring that the necessary STREAMS character devices are
#	present in the /dev directory and that the STREAMS subsystem is
#	configured and loaded.  It is also responsible for starting the STREAMS
#	log and trace facilities.
### END INIT INFO

# Source init script functions library.
. /etc/init.d/functions

if [ -x /sbin/streams_mknod ] ; then
    STREAMS_MKNOD='/sbin/streams_mknod'
elif [ -x /usr/bin/streams_mknod ]; then
    STREAMS_MKNOD='/usr/sbin/streams_mknod'
else
    STREAMS_MKNOD=''
fi

# Specify defaults

MAKEDEVICES="no"
REMOVEDEVICES="no"
MOUNTSPECFS="yes"
MOUNTPOINT="/dev/streams"

# Source redhat and/or debian config file
[ -f /etc/streams.conf ] && . /etc/streams.conf
[ -f /etc/default/streams ] && . /etc/default/streams
[ -f /etc/sysconfig/streams.conf ] && . /etc/sysconfig/streams

RETVAL=0

umask 077

start() {
    echo "Starting STREAMS subsystem: "
}

stop() {
}

rhstatus() {
}

reload() {
    stop
    start
}

restart() {
    stop
    start
}

probe() {
#
#   subsystem unlocked, need to start
#
    [ ! -f /var/log/subsys/streams ] && { echo 'start' ; return 0 }
#
#   streams unloaded but subsystem locked, need to restart
#
    grep -q '\<streams\>' /proc/modules 2>/dev/null || { echo 'restart' ; return 0 }
#
#   configuration files updated, need to reload
#
    [ -f /etc/sysconfig/streams -a /etc/sysconfig/streams -nt /var/lock/subsys/streams ] \
    && { echo 'reload' ; return 0 }
    [ -f /etc/default/streams   -a /etc/default/streams   -nt /var/lock/subsys/streams ] \
    && { echo 'reload' ; return 0 }
    [ -f /etc/streams.conf      -a /etc/streams.conf      -nt /var/lock/subsys/streams ] \
    && { echo 'reload' ; return 0 }
#
#   do not need to do anything
#
    return $?
}

case "$1" in
    (start)
	start
	;;
    (stop)
	stop
	;;
    (status)
	rhstatus
	;;
    (restart)
	restart
	;;
    (reload)
	reload
	;;
    (condrestart)
	[ -f /var/log/subsys/streams ] && restart || :
	;;
    (probe)
	probe
	;;
    (*)
	echo "Usage: $0 (start|stop|status|restart|condrestart|probe)\n"
	;;
esac

exit $?


#
# =============================================================================
# 
# @(#) $RCSfile: streams,v $ $Name:  $($Revision: 0.9.2.4 $) $Date: 2005/02/14 06:47:18 $
#
# -----------------------------------------------------------------------------
#
# Copyright (c) 2001-2005  OpenSS7 Corporation <http://www.openss7.com>
# Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
#
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 675 Mass
# Ave, Cambridge, MA 02139, USA.
#
# -----------------------------------------------------------------------------
#
# U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
# behalf of the U.S. Government ("Government"), the following provisions apply
# to you.  If the Software is supplied by the Department of Defense ("DoD"), it
# is classified as "Commercial Computer Software" under paragraph 252.227-7014
# of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
# successor regulations) and the Government is acquiring only the license rights
# granted herein (the license rights customarily provided to non-Government
# users).  If the Software is supplied to any unit or agency of the Government
# other than DoD, it is classified as "Restricted Computer Software" and the
# Government's rights in the Software are defined in paragraph 52.227-19 of the
# Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
# the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
# (or any successor regulations).
#
# -----------------------------------------------------------------------------
#
# Commercial licensing and support of this software is available from OpenSS7
# Corporation at a fee.  See http://www.openss7.com/
#
# -----------------------------------------------------------------------------
#
# Last Modified $Date: 2005/02/14 06:47:18 $ by $Author: brian $
#
# =============================================================================

# vim: ft=sh sw=4 tw=80
