'\" rtp
.\" -*- nroff -*- vim: ft=nroff noautoindent nocindent nosmartindent
.\"
.\" @(#) $Id: connld.old.4.man,v 0.9.2.7 2005/05/11 20:08:38 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (C) 2001-2005  OpenSS7 Corporation <www.openss7.com>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" -------------------------------------------------------------------------
.\"
.\" U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
.\" on behalf of the U.S. Government ("Government"), the following
.\" provisions apply to you.  If the Software is supplied by the Department
.\" of Defense ("DoD"), it is classified as "Commercial Computer Software"
.\" under paragraph 252.227-7014 of the DoD Supplement to the Federal
.\" Acquisition Regulations ("DFARS") (or any successor regulations) and the
.\" Government is acquiring only the license rights granted herein (the
.\" license rights customarily provided to non-Government users).  If the
.\" Software is supplied to any unit or agency of the Government other than
.\" DoD, it is classified as "Restricted Computer Software" and the
.\" Government's rights in the Software are defined in paragraph 52.227-19
.\" of the Federal Acquisition Regulations ("FAR") (or any success
.\" regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
.\" NASA Supplement to the FAR (or any successor regulations).
.\"
.\" =========================================================================
.\" 
.\" Commercial licensing and support of this software is available from
.\" OpenSS7 Corporation at a fee.  See http://www.openss7.com/
.\" 
.\" =========================================================================
.\"
.\" Last Modified $Date: 2005/05/11 20:08:38 $ by $Author: brian $
.\"
.\" =========================================================================
.so streams.macros
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database streams.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.\"
.\"
.TH CONNLD 4 "@PACKAGE_DATE@" "@PACKAGE@-@VERSION@" "@PACKAGE_TITLE@ Devices"
.\"
.\"
.SH NAME
.B connld
\- \fISTREAMS\fR module supporting the generation of unique new \fISTREAMS\fR \fIpipes\fR from an existing pipe end
.\"
.\"
.SH SYNOPSIS
.\"
.\"
.SH DESCRIPTION
The
.B connld
module provides a means to generate multiple unique
.I STREAMS
.I pipes
from a single existing
.I pipe
end.
.sb
.B connld
may only be
.I pushed
(via the
.I STREAMS
.B I_PUSH
.IR ioctl )
onto a
.I STREAMS
.IR pipe .
When first
.IR pushed ,
.B connld
does nothing; on each subsequent
.BR open (2),
.B connld
will generate a unique
.I STREAMS
.IR pipe .
One end of each new pipe replaces the original pipe end from the
perspective of the
.B open
call.
The other end of each new pipe is sent, effectively as if by
the
.B I_SENDFD
.IR ioctl ,
to the other end of the original pipe, ostensibly to be received
by a subsequent
.B I_RECVFD
.I ioctl
operation.
.\"
.\"
.SH "APPLICATION USAGE"
The intent of
.B connld
is to provide a means to generate unique pipes which separately
and independently connect client processes to a server process.
The point of access for such clients is expected to be a path
name known to all such clients and to which a pipe end may be
connected (via
.BR fattach (3))
by the server process.
The server establishes the original pipe, pushes
.B connld
onto the client end, and then listens via
.B I_RECVFD
for new connections on the server end.
A client wishing to connect to the server will
.BR open (2)
the path name representing the client end, and can determine via
.BR isastream (3)
whether or not the server process is active and attached.  If 
it is, the
.BR open ()
call returns one end of a unique new pipe that thus connects
the client to the server.
.sp
Such a server is responsible both for accepting new connections
via
.B I_RECVFD
on the original pipe, and for communicating with clients so
connected via the received pipe ends.
It would also be reasonable for such a server process to invalidate
the point of access by calling
.BR fdetach (3)
before terminating.
.sp
It should be noted that the
.BR poll (2)
primitive may be used to indicate when an 
.B M_PASSFP
representing a newly passed file is available on the original server
pipe end.
This is reflected by the
.B POLLIN
status setting in the
.B events
and
.B revents
fields of a
.B pollfd
structure.
Moreover, any attempt to read an
.B M_PASSFP
message via the data-receiving primitives (i.e., 
.BR read "(2), " getmsg "(3), and " getpmsg (3))
will fail with
.BR errno (3)
returning an
.RB [ EBADMSG ]
indication without discarding the message.
.sp
Even so, it should be reasonable to expect only
.B M_PASSFP
messages will be received on the original server pipe end,
since it is not possible to carry on normal data traffic which
has
.B connld
on one end, since
.B connld
does not support such traffic.
.sp
The use of
.B connld
can be made entirely free-standing by attaching well-known paths to
.I both
ends of the original pipe.  The relevant capabilities are implemented
in
.B LiS
.[
LiS
.]
so that the original creator of the
.B pipe
can close both ends after attaching paths to them, and the
process of passing file descriptors can still be carried out via
new
.BR open ()'s
as long as both ends remain attached.
.\"
.\"
.SH "SEE ALSO"
.BR fattach (3),
.BR fattach (8),
.BR fdetach (3),
.BR fifo (4),
.BR pipe (3),
.BR STREAMS (4).
.\"
.\"
.SH HISTORY
UNIX\(rg\ System V Release 4 (SVR4)
.[
svr4
.]
.\"
.\"
.SH AUTHOR
John Boyd, protologos LLC.
.[
$LIST$
.]
.TI
