'\" rtp
.\" -*- nroff -*- vim: ft=nroff nocin nosi tw=100
.\"
.\" @(#) $Id: m2ua-as.4.man,v 0.9.2.2 2007/01/23 10:00:42 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (c) 2001-2007  OpenSS7 Corporation <http://www.openss7.com/>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.  The author(s) will take no responsibility in it.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" -------------------------------------------------------------------------
.\"
.\" U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
.\" on behalf of the U.S. Government ("Government"), the following
.\" provisions apply to you.  If the Software is supplied by the Department
.\" of Defense ("DoD"), it is classified as "Commercial Computer Software"
.\" under paragraph 252.227-7014 of the DoD Supplement to the Federal
.\" Acquisition Regulations ("DFARS") (or any successor regulations) and the
.\" Government is acquiring only the license rights granted herein (the
.\" license rights customarily provided to non-Government users).  If the
.\" Software is supplied to any unit or agency of the Government other than
.\" DoD, it is classified as "Restricted Computer Software" and the
.\" Government's rights in the Software are defined in paragraph 52.227-19
.\" of the Federal Acquisition Regulations ("FAR") (or any successor
.\" regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
.\" NASA Supplement to the FAR (or any successor regulations).
.\"
.\" =========================================================================
.\" 
.\" Commercial licensing and support of this software is available from
.\" OpenSS7 Corporation at a fee.  See http://www.openss7.com/
.\" 
.\" =========================================================================
.\"
.\" Last Modified $Date: 2007/01/23 10:00:42 $ by $Author: brian $
.\"
.\" -------------------------------------------------------------------------
.\"
.\" $Log: m2ua-as.4.man,v $
.\" Revision 0.9.2.2  2007/01/23 10:00:42  brian
.\" - added test program and m2ua-as updates
.\"
.\" Revision 0.9.2.1  2007/01/21 20:20:06  brian
.\" - added documetation
.\"
.\" =========================================================================
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database sigtran.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.so sigtran.macros
.\"
.\"
.TH M2UA-AS 4 "@PACKAGE_DATE@" "@PACKAGE@-@VERSION@" "@PACKAGE_TITLE@ Devices"
.SH NAME
.B m2ua-as
\- SS7 MTP2 User Adaptation Layer (M2UA) Application Server (AS)
.\"
.\"
.SH SYNOPSIS
.PP
.\"
.\"
.SH DESCRIPTION
.PP
The M2UA-AS is a multiplexing driver the implements the ASP side of the M2UA
.[
rfc3331
.]
protocol.
Streams opened on the upper multiplex provide the
.IR "Signalling Link Interface (SLI)" ,
.BR sli (7).
Streams linked under the lower multiplex provide the SCTP transport interface,
.BR sctp_t (4).
.\"
.SS Configuration
.PP
When the M2UA-AS driver is configured, SCTP Streams are opened and linked under the multiplexing
driver.  Each SCTP stream represents an association between a local ASP and a remote Signalling
Gateway.  Input-output controls are used to configure each lower multiplex Stream.  Once a lower
multiplex Stream is configured, the M2UA-AS driver attempts to form an SCTP association with the
remote SG, and to bring the M2UA association into the ASP Up state.  Should the association be
dropped, the ASP-SG relation is moved to the ASP Down state and the M2UA-AS driver attempts to
reconnect the association and bring it to the ASP Up state and activate all active interfaces.
.PP
Once configured, SL Streams can be opened on the upper multiplex.  These SL Streams are not
associated with an ASP-SG association until they are attached.  When the
.BR LMI_ATTACH_REQ (7)
primitive is issued, the PPA contained in the request is composed of an SG identifier, and either an
SDLI/SDTI tuple (if the SG supports dynamic configuration), or an Interface Identifier (if the SG
supports static configuration).  This information is sufficient for the M2UA-AS driver to determine
the association and Link Key that is to be used to register the interface.  When the
.BR LMI_ENABLE_REQ (7)
primitive is issued, the registered or assigned Interface Identifier is used to activate the
interface with the remote SG.
.PP
After the link has been attached with the
.BR LMI_ATTACH_REQ (7),
it can be linked beneath the SL-MUX multiplexing device driver and assigned a CLEI and global PPA.
.PP
Configuration is performed using an M2UA-AS driver configuration utility.  This utility reads a
configuration file used to define the objects necessary for configuration.  The configuration file
contains entries that define ASP-SG relationships as follows:
.TP
.I sgid
An integer number identifying the ASP-SG relation.
.TP
.I aspid
The ASPID that is used in communciation with the remote SG.  This ASPID can be null (a single dash,
.RB ` - ')
indicating that no ASPID is to be used in communication with the remote SG.  This ASPID corresponds
also to the value zero
.RB ( 0 ).
.TP
.I streams
The number of SCTP streams that will be requested to the SG.
.TP
.I local-endpoint
The local endpoint address to which an SCTP association is bound to communicate with the remote SG.
This can take the form:
\fIhostname\fR[\fB,\fIhostname\fR][\fB:\fIport\fR]
or the form:
\fIipaddress\fR[\fB,\fIipaddress\fR][\fB:\fIservice\fR]
or combinations of hostnames and IP addresses and either port or service.  The special hostname
consisting of a single star,
.RB ` * ',
can be used to indicate a wildcard address.  If the port or service is not specified, then a dynamic
port will be allocated.  If the service is specified as
.BR m2ua ,
then the M2UA well-known port number will be used.
.TP
.I remote-endpoint
The remote endpoint addess to which an SCTP association will connect to communicate with the remote
SG.  This can take the form:
\fIhostname\fR[\fB,\fIhostname\fR][\fB:\fIport\fR]
or the form:
\fIipaddress\fR[\fB,\fIipaddress\fR][\fB:\fIservice\fR]
or combinations of hostnames and IP addresses and either port or service.  If the port or service is
not specified, the M2UA well-known port number will be used.
.TP
.I options
Contains a comma separated list of SG options, with no embedded whitespace.  The following options
are defined:
.RS
.TP
.B dynamic
When included in the options, this keyword specifies that the SG requires dynamic registration.  If
this option is not included, the SG requires static registration.
.RE
.PP
The configuration utility, reads this configuration file and performs the following steps for each
entry in the file:
.IP 1. \w'0.\(em'u
The utility opens an SCTP association by opening the
.B /dev/sctp_t
device.
.IP 2.
The utility opens a Stream on the M2UA-AS driver using the
.B /dev/m2ua-as
device and links the Stream for the SCTP association under the M2UA-AS multiplexing driver using the
.IR I_LINK (7)
or
.IR I_PLINK (7)
input-output control.
.IP 3.
The utility uses a single specialized M2UA-AS input-output control to associate the lower multiplex
Stream with an SG (and local ASP).  The input-output control takes the information provided in the
configuration file line entry, and the mulltiplexer identifier returned from the
.IR I_LINK (7)
or
.IR I_PLINK (7)
input-output control operation.  The M2UA-AS driver then creates a new ASP object if necessary and
completes the SG object information as part of the lower multiplex Stream private structure.  The
M2UA-AS driver also binds and connects the SCTP association and attempts to bring the ASP to the ASP
Up state with the remote SG.
.IP 4.
The steps 1 through 3 above are repeated for each entry in the configuration file.
.IP 5.
The utility can also open and attach signalling link Streams and link them under the SL-MUX
multiplexing driver with a global PPA and CLEI.
.\"
.SS Addressing
.PP
All M2UA-AS upper multiplex Streams (SL) are Style II links.  That is, they must be attached with an
.BR LMI_ATTACH_REQ (7)
primitive containing a PPA before they are enabled.  For M2UA-AS, the interpretation of the PPA
depends upon whether the SG requires dynamic registration or not.  When the SG requires dynamic
registration, the PPA is interpreted as an optional SGID and an SDLI and SDTI.  When the SG requires
static configuration, the PPA is interpreted as an optional SGI and an IID.
.PP
It is possible to use the minor device number opened on the M2UA-AS driver to imply the SGID;
however, because the PPA is variable length for the SLI, it is quite possible to provide 64-bits or
more of information (unlike the DLPI interface).  This saves creating many device nodes or using
.BI /dev/streams/m2ua-as/ NNN
minor device nodes.  Therefore, when the device is opened was minor device zero (0); and SGID must
be specified in the PPA.  When the device opened  was minor device
.IR NNN ,
where
.I NNN
is a number from 1 to 16367, the SGID does not need to be present in the PPA and the opened minor
device number is used as the SGID instead.
.PP
For OpenSS7 SGs, the SDLI/SDTI combination and the IID are the same numeric value.  When an ASP
registers the Link Key containing an SDLI and SDTI, the IID returned to the registration request is
simply the 16-bit SDLI and SDTI concatenated into a 32-bit IID.  Therefore, regardless of whether
the SG requires dynamic registration or not, the PPA is formatted as a 32-bit SGID followed by a
32-bit IID that can be interpreted as composed of a 16-bit SDLI concatenated with a 16-bit SDTI when
the SG requires dynamic registration.
.PP
The driver also accepts text IIDs.  Text IIDs are of any length other than 4 or 8 bytes.  4 byte
long PPAs are interpreted by the driver as an integer IID (or SDLI/SDTI) if the opened device was a
non-zero minor device number.  8 byte long PPAs are interpreted as an integer SGID followed by an
integer IID (or SDLI/SDTI).  When the opened device was a non-zero minor device, PPAs of length
other than 4 are interpreted as a text IID.  The text IID must include the terminating null
character if it is shorter than the PPA.  (This way the PPA can be made of arbitrary length,
regardless of the length of the text identifier.)  When the opened device was the zero minor
device, PPAs of length other than 8 are interpreted as a 4 byte integer SGID followed by a text IID
(including the null terminating character if the text IID is shorter than the PPA).
The driver allocates storage for 32 bytes of text IID.  Text IIDs longer than 32 bytes will be
truncated to 32 bytes.
.PP
The form and interpretation of the address is summarized in the following table:
.sp
.RS
.TS
tab(:);
lblblb
l|l|l.
PPA Length:Zero Minor:Non-Zero Minor
_:_:_
4 bytes:error:int IID
5-7 bytes:int SGID, text IID:text IID
8 bytes:int SGID, int IID:text IID
9+ bytes:int SGID, text IID:text IID
.TE
.RE
.PP
The SGID is used directly to locate the lower multiplex Stream.  If there does not exist a lower
multiplex stream with the requested SGID, the request will fail.  When the lower multiplex stream
exists, the SL streams attached to the stream are searched to determine if another stream is already
attached to the SDLI/SDTI or IID.  Only one stream can be attached to a given SDLI/SDTI or IID at a
time.  The second request to attach to the same SDLI/SDTI or IID will fail.  When successful, and
the lower SCTP stream is active (ASP Up), and the SG requires dynamic registration, dynamic
registration will be performed on the SDLI/SDTI used as a Link Key.  If the lower stream is not ASP
Up, or the regsitration fails, the attach request will fail.  If the SG does not require
registration, the IID will be assigned to the attached stream and the attach operation will succeed.
The SCTP association does not need to be in the ASP Up state at this point (it will when the
.BR LMI_ENABLE_REQ (7)
appears).
.PP
When SL Streams opened on the upper multiplex of the M2UA-AS driver are attached, the form of the
PPA depends upon whether the SG requires dynamic registration or not.  When the SG requires dynamic
configuration, the PPA consists of the
.I sgid
and an tuple consisting of the Signalling Data Link Identifier (SDLI) and the Signalling Data
Terminal Identifier (SDTI).  When the SG requires static configuration, the PPA consists of the
.I sgid
and the assigned Interface Identifier (integer or text).  The M2UA-AS driver identifies the
association and interface identifier for which to activate and process messages for the interface
using the
.I sgid
and the Interface Identifier that was either specified or was obtained by registering the link key
consisting of the SDLI and SDTI specified.
An additional, optional, traffic mode type can also be specified as part of the PPA.
.\"
.\"
.SH IOCTLS
.PP
The M2UA-AS driver provides several input-output controls for configuring the driver as follows:
.\"
.SS M2UA_AS_IOCSCONFIG
.PP
.\"
.SS M2UA_AS_IOCGCONFIG
.PP
This input-output control takes as an argument a pointer to a buffer area into which to place the
configuration information.
.\"
.\"
.SH SYNOPSIS
.PP
.\"
.\"
.SH SYNOPSIS
.PP
.\"
.\"
.SH SYNOPSIS
.PP
.\"
.\"
.SH SYNOPSIS
.PP
.\"
.\"
.SH SYNOPSIS
.PP
.\"
.\"
.SH BUGS
.PP
.\"
.\"
.SH COMPATIBLITY
.PP
.\"
.\"
.SH CONFORMANCE
.PP
.IR "RFC 3331" ,
.[
rfc3331
.]
.IR "ETSI TS 102 141" ,
.[
etsim2ua
.]
.IR "draft-bidulock-sigtran-m2ua-ss7test" ,
.[
draft-bidulock-sigtran-m2ua-ss7test-02
.]
.IR "ETSI TS 102 380" .
.[
etsitestm2ua
.]
.PP
Conformance to
.IR "ETSI TS 102 141"
.[
etsim2ua
.]
per tests specified by
.IR "ETSI TS 102 380" ,
.[
etsitestm2ua
.]
is validated using the
.BR test-m2ua_as (8)
test case executable and the package
.B autotest
test suite.
.PP
Conformance to
.IR "RFC 3331" ,
.[
rfc3331
.]
per tests specified by
.IR "draft-bidulock-sigtran-m2ua-ss7test" ,
.[
draft-bidulock-sigtran-m2ua-ss7test-02
.]
is validated using the
.BR test-m2ua (8)
test case executable and the package
.B autotest
test suite.
.\"
.\"
.SH HISTORY
.PP
.\"
.\"
.[
$LIST$
.]
.TI
