'\" rtp
.\" -*- nroff -*- vim: ft=nroff noautoindent nocindent nosmartindent
.\"
.\" @(#) $Id: allocq.9.man,v 0.9.2.6 2004/04/19 02:58:16 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (C) 2001-2003  OpenSS7 Corporation <www.openss7.com>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" -------------------------------------------------------------------------
.\"
.\" U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
.\" on behalf of the U.S. Government ("Government"), the following
.\" provisions apply to you.  If the Software is supplied by the Department
.\" of Defense ("DoD"), it is classified as "Commercial Computer Software"
.\" under paragraph 252.227-7014 of the DoD Supplement to the Federal
.\" Acquisition Regulations ("DFARS") (or any successor regulations) and the
.\" Government is acquiring only the license rights granted herein (the
.\" license rights customarily provided to non-Government users).  If the
.\" Software is supplied to any unit or agency of the Government other than
.\" DoD, it is classified as "Restricted Computer Software" and the
.\" Government's rights in the Software are defined in paragraph 52.227-19
.\" of the Federal Acquisition Regulations ("FAR") (or any success
.\" regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
.\" NASA Supplement to the FAR (or any successor regulations).
.\"
.\" =========================================================================
.\" 
.\" Commercial licensing and support of this software is available from
.\" OpenSS7 Corporation at a fee.  See http://www.openss7.com/
.\" 
.\" =========================================================================
.\"
.\" Last Modified $Date: 2004/04/19 02:58:16 $ by $Author: brian $
.\"
.\" =========================================================================
.so streams.macros
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database streams.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.\"
.\"
.TH ALLOCQ 9 "$Date: 2004/04/19 02:58:16 $" "$Name:  $" "Linux Fast-STREAMS DDI/DKI"
.\"
.\"
.SH NAME
.B allocq
\- allocate a \fISTREAMS\fP queue pair
.\"
.\"
.SH SYNOPSIS
.PP
.B #include <sys/stream.h>
.HP
.B queue_t *allocq(void);
.\"
.\"
.SH ARGUMENTS
.PP
None.
.\"
.\"
.SH DESCRIPTION
.PP
Allocate a new
.BR NULL -initialized
queue pair.
Queue pairs allocated with
.BR allocq ()
can be freed with
.BR freeq (9).
.PP
Queue pairs allocated with
.BR allocq ()
will have no putp, srvp, open or close procedures associated with either
queue, will have zero maximum and minimum packet sizes and high and low water
marks; and will have no syncrhonization queues associated with the queue pair.
.\"
.\"
.SH RETURN
Upon success,
.BR allocq ()
returns the newly allocated queue pair as a pointer to the read queue of the
pair.
.PP
Upon failure,
.BR allocq ()
returns
.BR NULL .
.\"
.\"
.SH ERRORS
.PP
When
.BR allocq ()
encounters and error, it fails and returns
.BR NULL .
.BR allocq ()
fails when there is insufficient
.B queinfo
cache memory available to allocate the queue pair.
.\"
.\"
.SH CONTEXT
.PP
.BR allocq ()
can be called from any context.
.\"
.\"
.SH MP-STREAMS
.PP
.BR allocq ()
is MP-safe.  The caller has exclusive access to the returned queue pair.
.\"
.\"
.SH NOTICES
.PP
Although this function is documented as an internal function of
.IR "SVR 4" ,
.[
magic
.]
.BR allocq ()
it is not normally called directly by
.I STREAMS
modules or drivers.  This function is normally internal to the
.I STREAMS
scheduler, yet,
.B Linux Fast-STREAMS
provides an exported version of this function for use by modules and drivers
so that private queue pairs can be allocated.
.PP
All
.B Linux Fast-STREAMS
queue functions (e.g., 
.BR putq (9),
.BR insq (9),
.BR appq (9),
.BR rmvq (9))
can be executed on a detached queue pair.  This function can be used to
allocate a private queue pair for use as a message buffer by
.I STREAMS
modules and drivers.  The queue pair is not linked into any stream and no
message size or water marks or queue procedures are associated with the queue.
.PP
Message sizes, water marks and procedures can be associated with a private
queue pair using
.BR setq (9).
.PP
The queue can also be pushed onto or removed from a stream using
.BR qattach (9)
and
.BR qdetach (9).
.PP
This function should not be used by portable
.I STREAMS
modules or drivers.
.\"
.\"
.SH "SEE ALSO"
.PP
.BR freeq (9),
.BR putq (9),
.BR insq (9),
.BR appq (9),
.BR rmvq (9),
.BR setq (9),
.BR qattach (9),
.BR qdetach (9).
.\"
.\"
.SH BUGS
.PP
.BR allocq ()
has no known bugs.
.\"
.\"
.SH COMPATIBILITY
.PP
.BR allocq ()
is compatible with
.IR LiS .
.[
lis
.]
with the following portability considerations:
.IP \(em \w'\(em\(em'u
.BR allocq ()
and symbol
.BR lis_allocq ()
is provided for compatibility with LiS.  See
.BR lisbcm (8).
.BR lis_allocq ()
simply calls
.BR allocq ()
directly.
.IP \(em
.BR allocq ()
should not be called by normal
.I STREAMS
modules or drivers and is implementation specific.
.IP \(em
This function is not exported by
.IR "SVR 4.2 MP DDI/DKI " or
any other UNIX directly.
.IP \(em
Binary compatibility is not guaranteed.
.PP
See
.BR STREAMS (9)
for additional compatibilitye information.
.\"
.\"
.SH CONFORMANCE
.PP
.BR allocq ()
is compliant with the description of the internal
.BR allocq ()
function in SVR 4
.[
svr4
.]
as described in
.IR "\*(lqThe Magic Garden\*(rq" .
.[
magic
.]
.\"
.\"
.SH HISTORY
.PP
.BR allocq ()
is an internal
.I "SVR 4"
.I STREAMS
function described in
.IR "\*(lqThe Magic Garden\*(rq" .
.[
magic
.]
.\"
.\"
.[
$LIST$
.]
.TI
