'\" rtp
.\" -*- nroff -*- vim: ft=nroff noautoindent nocindent nosmartindent
.\"
.\" @(#) $Id: esballoc.9.man,v 0.9.2.8 2004/08/22 06:17:45 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (C) 2001-2003  OpenSS7 Corporation <www.openss7.com>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" -------------------------------------------------------------------------
.\"
.\" U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
.\" on behalf of the U.S. Government ("Government"), the following
.\" provisions apply to you.  If the Software is supplied by the Department
.\" of Defense ("DoD"), it is classified as "Commercial Computer Software"
.\" under paragraph 252.227-7014 of the DoD Supplement to the Federal
.\" Acquisition Regulations ("DFARS") (or any successor regulations) and the
.\" Government is acquiring only the license rights granted herein (the
.\" license rights customarily provided to non-Government users).  If the
.\" Software is supplied to any unit or agency of the Government other than
.\" DoD, it is classified as "Restricted Computer Software" and the
.\" Government's rights in the Software are defined in paragraph 52.227-19
.\" of the Federal Acquisition Regulations ("FAR") (or any success
.\" regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
.\" NASA Supplement to the FAR (or any successor regulations).
.\"
.\" =========================================================================
.\" 
.\" Commercial licensing and support of this software is available from
.\" OpenSS7 Corporation at a fee.  See http://www.openss7.com/
.\" 
.\" =========================================================================
.\"
.\" Last Modified $Date: 2004/08/22 06:17:45 $ by $Author: brian $
.\"
.\" =========================================================================
.so streams.macros
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database streams.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.\"
.\"
.TH ESBALLOC 9 "$Date: 2004/08/22 06:17:45 $" "$Name:  $" "Linux Fast-STREAMS DDI/DKI"
.\"
.\"
.SH NAME
.B esballoc
\- allocate a \fISTREAMS\fP message and data block with a caller supplied data buffer
.\"
.\"
.SH SYNOPSIS
.PP
.B #include <sys/stream.h>
.HP
.BI "mblk_t *esballoc(unsigned char *" base ", int " size, ", int " priority ", frtn_t *" freeinfo );
.\"
.\"
.SH ARGUMENTS
.TP \w'\ priority\ 'u
.I base
the base of the user supplied message buffer.
.TP
.I size
the size of the user supplied message buffer.
.TP
.I priority
the priority of the request.
.TP
.I freeinfo
a pointer to a free routine description structure.
.\"
.\"
.SH DESCRIPTION
.PP
.BR esballoc ()
is used where the
.IR STREAMS (4)
driver needs control over the location, allocation and deallocation of data
buffers.  This may be because the data buffers are subject to some physical
contraints (e.g. must be allocated in DMA-able memory, or must exist in
dual-ported RAM or in a decriptor ring).  This may also be because some other
mechanism outside of
.IR STREAMS (4)
has already allocated and passed the data buffer to a
.IR STREAMS (4)
driver.
.PP
Where it is not necessary that the caller provide the data buffer,
.BR allocb (9)
is more appropriate.
.PP
.BR esballoc ()
allocates a message block and a data block using the caller supplied data
buffer at
.I base
of the specified
.IR size " and " priority .
.PP
The
.I priority
can be one of the following values:
.TP \w'\ BPRI_WAITOK\ 'u
.B BPRI_LO
The caller requests a low priority message buffer.
.PD 0
.TP
.B BPRI_MED
The caller requests a medium priority message buffer.
.TP
.B BPRI_HI
The caller requests a high priority message buffer.
.TP
.B BPRI_WAITOK
The caller requests a low priority message buffer and can block.
.PD
.PP
If
.BR esballoc ()
is called with a
.I priority
other than
.BR BPRI_LO ", " BPRI_MED ", " BPRI_HI " or " BPRI_WAITOK ,
the request will be treated as
.BR BPRI_LO .
.PP
The data buffer of length
.I size
and with the necessary physical memory type has already been allocated by the
caller and is pointed to by the argument
.IR base .
In addition,
.BR esballoc ()
accepts a pointer to a
.B free_rtn
structure that contains the following elements:
.TP
.BI "void (*" free_func ")(char *)"
A function pointer
.I free_func
to a function returning void and taking a single character
pointer argument.  This function should perform whatever actions are necessary
to free the buffer pointed to by
.I base
in the call to
.BR esballoc ().
.TP
.BI "char *" free_arg
A character pointer argument
.I free_arg
that will be passed to a call to
.I free_func
when the message block returned by
.BR esballoc ()
is freed with
.BR freeb "(9) or " freemsg (9).
.PP
The allocated message block will have a data block type of
.BR M_DATA .
.\"
.\"
.SH RETURN
.PP
Upon success,
.BR esballoc ()
returns a pointer to the allocated message block.
.PP
Upon failure,
.BR esballoc ()
returns a
.B NULL
message pointer.
.\"
.\"
.SH ERRORS
.PP
When
.BR esballoc ()
fails to allocate a message or data block,
it returns
.BR NULL .
Failure to allocate a message block will typically be followed by a call to
.BR esbbcall (9).
.PP
.BR esballoc ()
will always fail to allocate a message block when the number of outstanding
combined message data blocks allocated by the system exceeds the system
control
.BR sysctl_str_nstrmsgs .
.BR esballoc ()
will also fail if
.I size
is greater than system control
.BR sysctl_str_strmsgsz ,
the maximum
.I STREAMS
message size.
.\"
.\"
.SH CONTEXT
.PP
.BR esballoc ()
can be called from any context.
The priority
.B BPRI_WAITOK
must only be used from a blockable context.
.\"
.\"
.SH MP-STREAMS
.PP
.BR esballoc ()
is MP-safe.  The caller has exclusive access to the returned message.
.\"
.\"
.SH NOTICES
.PP
Many post-SVR 4.2
.[
svr42
.]
compliant
.IR STREAMS (4)
implementations ignore the
.I priority
argument to
.BR esballoc ().
The message block
.I priority
was an SVR 3
.[
svr3
.]
concept which was found not to be useful, primarily due to priority inversion.
For a history of the
.I priority
mechanism and a discussion as to why the mechanism was abandonned in SVR 4.2,
.[
svr42
.]
see \*(lqThe Magic Garden\*(rq section 7.2.2.
.[
magic
%P Section 7.2.2
.]
.PP
.B Linux Fast-STREAMS
keeps two stores for combined message data blocks
.RB ( mdbblock s):
a per-CPU free block list that is maintained during the 
.BR runqueues (9)
pass to hold freed message blocks (but freed to the memory cache at the end of
the pass), and an
.B mdbblock
memory cache.
.PP
In consideration of
.IR priority ,
.BR esballoc ()
uses the following allocation differences based on the value of
.IR priority :
.TP \w'\ BPRI_WAITOK\ 'u
.B BPRI_LO
The message block will be allocated from the
.I STREAMS
.B mdbblock
memory cache.
.BR kmem_cache_alloc (9)
will not be permitted to grow the
.B mdbblock
memory cache to meet the request.
When speed is not criticial and a lower degree of immediate success is acceptable, use
.BR BPRI_LO .
.TP
.B BPRI_MED
The message block will be allocated from the
.I STREAMS
.B mdbblock
memory cache.
.BR kmem_cache_alloc (9)
will be permitted to grow the
.B mdbblock
memory cache as necessary to allocate the block.
Where speed is not so critical, but a higher probability of immediate success is needed, use
.BR BPRI_MED .
.TP
.B BPRI_HI
The message block will be allocated from the per-CPU
.B STREAMS
scheduler fast free chain, or if there is no message block in the fast free
chain, it will be allocated from the
.B mdbblock
memory cache.
.BR kmem_cache_alloc (9)
will be permitted to grow the
.B mdbblock
memory cache as necessary to allocate the block.
Where speed is critical, and a high degree of immediate success is also needed, use
.BR BPRI_HI .
When
.BR esballoc (9)
is called immediately following
.BR freeb (9),
use
.B BPRI_HI
to obtain the same block that was freed.
.TP
.B BPRI_WAITOK
The buffer allocation will be treated as
.BR BPRI_LO ,
but the caller will block waiting to obtain a buffer.
.PP
In this way, the
.I priority
argument determines the delay in satisfying the request rather than the
ultimate probability of success, permitting low latency tasks to specify
.B BPRI_HI
and high-latency tasks to specify
.BR BPRI_LO .
.PP
.BR esballoc ()
presents challenges when used from within
.B Linux
kernel modules.  Particularly when the
.I free_func
function pointer references a function which is resident only within the
kernel module.
Care must be taken that the kernel module containing the
.I free_func
does not get unloaded from the system before all message blocks referencing
.I free_func
are freed.  This is the caller's responsibility and
.B Linux Fast-STREAMS
provides no automatic facility for this purpose.  If a kernel module contains
the
.I free_func
that is passed to
.BR esballoc (),
the caller should increment the kernel module use count with
.B MOD_INC_USE_COUNT
prior to the allocation, and decrement the module use count with
.B MOD_DEC_USE_COUNT
within the function referenced by
.IR free_func .
See
.RI \*(lq EXAMPLES \*(rq
below.
.\"
.\"
.SH EXAMPLES
.PP
The following examples shows how a data buffer suitable for use by Direct
Memory Access is allocated:
.nf
\fC\s-2
void xxx_free_func(char *buf)
{
    kfree(buf);
    MOD_DEC_USE_COUNT;
}

mblk_t *xxx_alloc_dma_buf(size_t bufsize)
{
    unsigned char *buf;
    MOD_INC_USE_COUNT;
    if ((buf = kmalloc(bufsize, GFP_ATOMIC | GFP_DMA))) {
        mblk_t *mp;
        frtn_t freertn = {
            free_func:&xxx_free_func,
            free_arg:(char *) buf,
        };
        if (!(mp = esballoc(buf, bufsize, BPRI_MED, &freertn)))
            xxx_free_func(buf);
        return (mp);
    }
    MOD_DEC_USE_COUNT;
    return (NULL);
}
\s+2\fP
.fi
.PP
The example, above, also shows the technique for keeping the current kernel
module from unloading before the free function is called for all outstanding
message blocks that reference the free function.  See
.RI \*(lq NOTICES \*(rq,
above.
.\"
.\"
.SH "SEE ALSO"
.PP
.BR freeb (9),
.BR freemsg (9),
.BR bufcall "(9), and "
.BR esbbcall (9).
.\"
.\"
.SH BUGS
.PP
.BR esballoc ()
has no known bugs.
.\"
.\"
.SH COMPATIBILITY
.PP
.BR esballoc ()
is compatible with
.IR "SVR 4.2 MP DDI/DKI" ,
.[
usldk
.]
and implementations based on
.IR "SVR 4" ,
with the following portability considerations:
.IP \(em \w'\(em\(em'u
.BR esballoc ()
uses the priority mechanism described above under
.RI \*(lq NOTICES \*(rq,
above.
.IR "SVR 4.2 MP DDI/DKI" ,
.IR AIX \(rg,
.[
aixspg
.]
.IR Solaris \(rg
.[
solspg
.]
and
.I LiS
.[
lis
.]
ignore the
.I priority
argument as also described above under
.RI \*(lq NOTICES \*(rq.
Portable
.I STREAMS
drivers and modules will not rely upon the response of
.BR esballoc ()
to any given value of the
.I priority
argument.
.IP \(em
.BR esballoc ()
will return
.B NULL
only if the allocation fails.
Under LiS,
.BR esballoc ()
will return
.B NULL
if
.IR base " or " freeinfo
is
.BR NULL .
.BR esballoc ()
will panic when
.IR base " or " freeinfo
are
.BR NULL .
Under LiS, the same conditions will return
.BR NULL .
Portable
.I STREAMS
drivers and modules will not pass invalid or
.B NULL
arguments to
.BR esballoc ().
.IP \(em
.BR esballoc ()
accepts the priority
.BR BPRI_WAITOK ,
which is
.IR OSF/1 \(rg-specific
.[
osfspg
.]
and non-portable.
.BR BPRI_WAITOK
will block the calling thread if a message block is not immediately available,
and is only intended to be called from a blockable context (e.g. from the
.BR qopen (9)
and
.BR qclose (9)
procedures).
Portable
.I STREAMS
drivers and modules will only use the priority values of
.BR BPRI_LO ,
.BR BPRI_MED
and
.BR BPRI_HI .
.IP \(em
Symbol
.BR lis_esballoc ()
is provided for compatibility with LiS.  See
.BR lisbcm (9).
.BR lis_esballoc ()
simply calls
.BR esballoc ()
directly.
.IP \(em
Binary compatibility is not guaranteed.
.PP
See
.BR STREAMS (9)
for additional compatibility information.
.\"
.\"
.SH CONFORMANCE
.PP
SVR 4.2 MP DDI/DKI
.[
usldk
.]
.\"
.\"
.SH HISTORY
.PP
.BR esballoc ()
first appeared in SVR 4 DDI/DKI.
.[
svr4dk
.]
.\"
.\"
.[
$LIST$
.]
.TI
