'\" rtp
.\" -*- nroff -*- vim: ft=nroff nocin nosi
.\"
.\" @(#) $Id: qopen.9.man,v 0.9.2.14 2006/04/05 09:44:15 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (c) 2001-2006  OpenSS7 Corporation <http://www.openss7.com/>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.  The author(s) will take no responsibility in it.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" -------------------------------------------------------------------------
.\"
.\" U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
.\" on behalf of the U.S. Government ("Government"), the following
.\" provisions apply to you.  If the Software is supplied by the Department
.\" of Defense ("DoD"), it is classified as "Commercial Computer Software"
.\" under paragraph 252.227-7014 of the DoD Supplement to the Federal
.\" Acquisition Regulations ("DFARS") (or any successor regulations) and the
.\" Government is acquiring only the license rights granted herein (the
.\" license rights customarily provided to non-Government users).  If the
.\" Software is supplied to any unit or agency of the Government other than
.\" DoD, it is classified as "Restricted Computer Software" and the
.\" Government's rights in the Software are defined in paragraph 52.227-19
.\" of the Federal Acquisition Regulations ("FAR") (or any successor
.\" regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
.\" NASA Supplement to the FAR (or any successor regulations).
.\"
.\" =========================================================================
.\" 
.\" Commercial licensing and support of this software is available from
.\" OpenSS7 Corporation at a fee.  See http://www.openss7.com/
.\" 
.\" =========================================================================
.\"
.\" Last Modified $Date: 2006/04/05 09:44:15 $ by $Author: brian $
.\"
.\" -------------------------------------------------------------------------
.\"
.\" $Log: qopen.9.man,v $
.\" Revision 0.9.2.14  2006/04/05 09:44:15  brian
.\" - moved .so line and updated headers
.\"
.\" =========================================================================
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database streams.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.so streams.macros
.\"
.\"
.TH QOPEN 9 "@PACKAGE_DATE@" "@PACKAGE@-@VERSION@" "@PACKAGE_TITLE@ DDI/DKI"
.\"
.\"
.SH NAME
.B qopen
\- call a \fISTREAMS\fR driver or module open routine
.\"
.\"
.SH SYNOPSIS
.PP
.B #include <sys/stream.h>
.HP
.BI "int qopen(queue_t *" q ", dev_t *" devp ", int " oflag ", int " sflag ", cred_t *" crp );
.\"
.\"
.SH ARGUMENTS
.PP
.TP
.I q
pointer to the driver or module's read queue.
.PD 0
.TP
.I devp
pointer to the device number.
.TP
.I oflag
open flags.
.TP
.I sflag
stream flags.
.TP
.I crp
pointer to the credentials of the opening user.
.PD
.\"
.\"
.SH INTERFACE
.PP
.IR STREAMS ,
internal,
implementation specific.
.\"
.\"
.SH DESCRIPTION
.PP
.BR qopen ()
is an internal
.B @PACKAGE_TITLE@
function which invokes the
.I STREAMS
driver or module
.IR qi_qopen (9)
routine associated with
.IR q .
If there is no
.IR qi_qopen (9)
routine associated with
.IR q ,
then
.BR qopen ()
returns
.RB [ ENOPKG ].
If
.BR mp-streams (9)
synchronization has been specified for the driver or module, the inner synchronization barrier is
entered shared or exlusive, according to the synchornization specification for the driver or module.
Otherwise, the
.IR qi_qopen (9)
routine is invoked directly.
.BR qopen ()
then returns the value returned by the driver or module
.IR qi_qopen (9)
routine.
.PP
.BR qopen ()
accepts the same arguments as the
.IR qi_qopen (9)
routine defined for the driver or module,
and, with the exception of
.RB [ ENOPKG ],
returns the same error numbers as the driver or module
.IR qi_qopen (9)
routine.
.PP
Since the
.BR qopen ()
function directly invokes the driver or module
.IR qi_qopen (9)
routine, the description of the
.IR qi_qopen (9)
is also applicable to
.BR qopen ().
See
.BR qinit (9)
and
.IR qi_qopen (9)
for details.
.\"
.\"
.SH USAGE
.PP
.BR qopen ()
is an internal
.I STREAMS
function that is not intended to be called
directly by the driver or module writer.  See
.BR open (2s)
and
.BR I_PUSH (7)
for indirect methods of invoking this function.  See
.IR qi_qopen (9)
for design guidelines for writing driver or module open routines.
This function is exported for
use by clone drivers and stream heads.  See
.BR register_inode (9).
.\"
.\"
.SH RETURN
.PP
Upon success,
.BR qopen ()
returns zero (0) and the device number associated with a driver in the area
pointed to by
.IR devp .
Upon failure,
.BR qopen ()
returns a negative error number.
.\"
.\"
.SH ERRORS
.PP
When
.BR qopen ()
fails, it returns a negative error number as follows:
.TP \w'[EWOULDBLOCK]\(em'u
.RB [ ENOPKG ]
the module has no
.IR qi_qopen (9)
routine.
.PP
.BR qopen ()
can also return any error returned by the modules
.IR qi_qopen (9)
routine.  In general,
the following errors are provided by module
.IR qi_qopen (9)
routines:
.TP \w'[EWOULDBLOCK]\(em'u
.RB [ ENXIO ]
the
.IR qi_qopen ()
routine for the driver or module failed.
.TP
.RB [ ENXIO ]
a driver was opened as a module.
.TP
.RB [ EIO ]
a module was opened as a driver.
.TP
.RB [ EACCES ]
the opening process did not have sufficient credentials to open the specified
device or push the specified module.
.TP
.RB [ EPERM ]
same as
.RB [ EACCES ]
above.
.TP
.RB [ ENOMEM ]
memory could not be allocated to hold the driver or module's private
structures.
.TP
.RB [ ENOBUFS ]
a buffer could not be allocated as part of the open.
.TP
.RB [ ENOSR ]
same as
.RB [ ENOMEM ]
and
.RB [ ENOBUFS ],
above.
.TP
.RB [ ENOSR ]
a
.I STREAMS
resource could not be allocated as part of the open.
.\"
.\"
.SH CONTEXT
.PP
.BR qopen ()
is only called by
.I STREAMS
in user context with the
.BR STRWOPEN
bit held in the Stream head private structure
.BR stdata (9),
(to prevent other simultaneous opens and closes of the same Stream),
and no locks held.
.\"
.\"
.SH MP-STREAMS
.PP
If the driver or module has a
.BR mp-streams (9)
specification,
.BR qopen ()
will enter the inner synchronization barrier shared or exclusive (depending on the specification)
before invoking the
.IR qi_qopen (9)
routine for the driver or module.  Before return,
.BR qopen ()
will leave the inner synchronization barrier.
.PP
Otherwise, if the driver or module does not have a
.BR mp-streams (9)
specification, or does not specify an inner barrier,
the
.IR qi_qopen (9)
routine of the driver or module will be called directly.
.PP
See
.BR mp-streams (9),
for more information.
.\"
.\"
.SH NOTICES
.PP
.BR qopen ()
is an internal
.I STREAMS
function which was not intended to be called directly by
.I STREAMS
drivers or modules.
.BR qopen ()
is not part of the DDI/DKI and should not be called by portable programs.
.\"
.\"
.SH EXAMPLES
.PP
See
.IR qi_qopen (9)
for examples of driver and module open routines.
.\"
.\"
.SH "SEE ALSO"
.PP
.BR qinit (9),
.IR qi_qopen (9),
.BR mp-streams (9),
.BR stdata (9),
.BR open (2s),
.BR I_PUSH (7),
.BR register_inode (9),
.BR STREAMS (9).
.\"
.\"
.SH BUGS
.PP
.BR qopen ()
has no known bugs.
.\"
.\"
.SH COMPATIBILITY
.PP
.BR qopen ()
is compatible with
.IR "SVR 4.2"
.[
usldk
.]
and implementations based on
.IR "SVR 4" ,
.[
svr4spg
.]
with the following portability considerations:
.IP \(em \w'\(em\(em'u
Although
.BR qopen ()
is consistent with the description of the internal
.IR "SVR 4"
operation,
.[
magic
.]
.BR qopen ()
is not an exported function in
.IR "SVR 4.2"
.[
svr42spg
.]
or any implementation based on
.IR "SVR 4" .
.[
svr4spg
.]
.IP ""
.BR qopen ()
will not be used by portable
.I STREAMS
drivers and modules, and the
.IR qi_qopen (9)
routine of a driver or module will not be directly invoked.
.PP
See
.BR STREAMS (9)
for additional compatibility considerations.
.\"
.\"
.SH CONFORMANCE
.PP
.RI \*(lq "Magic Garden" \*(rq
.[
magic
.]
description of internal
.I SVR 4
.[
svr4
.]
operation.
.\"
.\"
.SH HISTORY
.PP
.BR qopen ()
first appears in
.BR "@PACKAGE_TITLE@" .
.[
lfs
.]
.\"
.\"
.[
$LIST$
.]
.TI
