'\" rtp
.\" -*- nroff -*- vim: ft=nroff noautoindent nocindent nosmartindent
.\"
.\" @(#) $Id: sd_get.9.man,v 0.9.2.4 2005/12/06 09:39:20 brian Exp $
.\"
.\" =========================================================================
.\"
.\" Copyright (C) 2001-2005  OpenSS7 Corporation <www.openss7.com>
.\"
.\" All Rights Reserved.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" -------------------------------------------------------------------------
.\"
.\" U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
.\" on behalf of the U.S. Government ("Government"), the following
.\" provisions apply to you.  If the Software is supplied by the Department
.\" of Defense ("DoD"), it is classified as "Commercial Computer Software"
.\" under paragraph 252.227-7014 of the DoD Supplement to the Federal
.\" Acquisition Regulations ("DFARS") (or any successor regulations) and the
.\" Government is acquiring only the license rights granted herein (the
.\" license rights customarily provided to non-Government users).  If the
.\" Software is supplied to any unit or agency of the Government other than
.\" DoD, it is classified as "Restricted Computer Software" and the
.\" Government's rights in the Software are defined in paragraph 52.227-19
.\" of the Federal Acquisition Regulations ("FAR") (or any successor
.\" regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
.\" NASA Supplement to the FAR (or any successor regulations).
.\"
.\" =========================================================================
.\" 
.\" Commercial licensing and support of this software is available from
.\" OpenSS7 Corporation at a fee.  See http://www.openss7.com/
.\" 
.\" =========================================================================
.\"
.\" Last Modified $Date: 2005/12/06 09:39:20 $ by $Author: brian $
.\"
.\" =========================================================================
.so streams.macros
.R1
bracket-label "\fR[\fB" "\fR]" "\fR, \fB"
no-default-database
database streams.refs
accumulate
move-punctuation
abbreviate A
join-authors ", " ", " " and "
et-al " et al" 2 3
abbreviate-label-ranges ".."
sort-adjacent-labels
.R2
.\"
.\"
.TH SD_GET 9 "@PACKAGE_DATE@" "@PACKAGE@-@VERSION@" "@PACKAGE_TITLE@ DDI/DKI"
.\"
.\"
.SH NAME
.B sd_get, sd_put
\- acquire and release a reference to the Stream head
.\"
.\"
.SH SYNOPSIS
.PP
.B #include <sys/stream.h>
.br
.B #include <sys/strsubr.h>
.HP
.BI "struct stdata *sd_get(struct stdata *" sd ");
.PD 0
.HP
.BI "void sd_put(struct stdata **" sdp ");
.PD
.\"
.\"
.SH ARGUMENTS
.PP
.TP
.I sd
a pointer to a
.BR stdata (9)
structure representing the Stream head.
.PD 0
.TP
.I sdp
a pointer to a pointer to a
.BR stdata (9)
structure representing a reference to a Stream head to release.
.PD
.\"
.\"
.SH INTERFACE
.PP
.IR STREAMS ,
internal,
implementation specific.
.\"
.\"
.SH DESCRIPTION
.PP
.BR sd_get ()
and
.BR sd_put ()
provide reference counting for the
.BR stdata (9)
structure.
.BR sd_get ()
increments the reference count and returns
.IR sd .
.BR sd_put ()
decrements the reference count and nulls the pointer referenced by
.IR sdp .
If the reference count drops to zero,
.BR sd_put ()
will cause the
.BR stdata (9)
structure to be deallocated.
.\"
.\"
.SH USAGE
.PP
.PP
.BR sd_get ()
and
.BR sd_put ()
are used to reference count
.BR stdata (9)
structures within the Stream head module,
.BR sth (4).
.\"
.\"
.SH RETURN
.PP
.BR sd_put ()
returns void.
.PP
.BR sd_get ()
returns the pass in
.BR stdata (9)
pointer,
.IR sd .
.\"
.\"
.SH ERRORS
.PP
When
.BR sd_get ()
fails it returns
.BR NULL .
.BR sd_get ()
fails when the passed in
.BR stdata (9)
structure pointer,
.IR sd ,
is
.BR NULL .
When
.BR sd_put ()
fails it fails silently.
.BR sd_put ()
fails when the passed in structure pointer referenced,
.IR sdp ,
is
.BR NULL .
.\"
.\"
.SH CONTEXT
.PP
.BR sd_get ()
and
.BR sd_put ()
can be called from any context including process context, module procedures, callouts, callbacks,
soft interrupts (tasklets and bottom halves), and interrupt service routines.
As
.BR sd_put ()
may result in the deallocation of a
.BR stdata (9)
structure, care should be taken invoking it from an ISR.
.\"
.\"
.SH MP-STREAMS
.PP
.BR sd_get ()
and
.BR sd_put ()
use atomic integer operations and are MP-safe.
.\"
.\"
.SH NOTICES
.PP
.BR sd_get ()
and
.BR sd_put ()
are not intended to be called by portable
.I STREAMS
drivers and modules.  They are only used by the Stream head,
.BR sth (4),
within the
.I "@PACKAGE_TITLE@"
.B @PACKAGE@-@VERSION@
distribution.
.\"
.\"
.SH IMPLEMENTATION
.PP
See the source file
.I src/kernel/strsched.c
in the
.B @PACKAGE@-@VERSION@
distribution directory for implementation details.
.\"
.\"
.SH EXAMPLES
.PP
None.
See the source file
.I src/modules/sth.c
in the
.B @PACKAGE@-@VERSION@
distribution directory for example usage.
.\"
.\"
.SH "SEE ALSO"
.PP
.BR stdata (9),
.BR sth (4).
.\"
.\"
.SH BUGS
.PP
.BR sd_get "() and " sd_put ()
have no known bugs.
.\"
.\"
.SH COMPATIBILITY
.PP
The
.BR sd_get ()
and
.BR sd_put ()
functions provide the ability to acquire and release reference counts on
.BR stdata (9)
structures.
These are
.B "@PACKAGE_TITLE@"
implementation specific functions not intended to be used by
.I STREAMS
drivers and modules and not subject to standardization.
.\"
.\"
.SH CONFORMANCE
.PP
None.
.\"
.\"
.SH HISTORY
.PP
These functions are new for
.BR "@PACKAGE_TITLE@" .
.\"
.\"
.[
$LIST$
.]
.TI
