#!/bin/sh
#
# @(#) $RCSfile: strerr,v $ $Name:  $($Revision: 0.9.2.4 $) $Date: 2005/02/14 06:47:18 $
# Copyright (c) 2001-2005  OpenSS7 Corporation <http://www.openss7.com>
# Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
# All Rights Reserved.
#
# Distributed by OpenSS7 Corporation.  See the bottom of this script for copying
# permissions.
#
# Redhat chkconfig init script conventions
#
# strerr:	start and stop strerr facility
# chkconfig:	- 55 55
# processname:	strerr
# pidfile:	/var/run/strerr.pid
# lockfile:	/var/lock/subsys/strerr
# config:	/etc/sysconfig/strerr
# probe:	true
# hide:		false
# license:	GPL
# description:	This STREAMS init script is part of Linux Fast-STREAMS.  It is \
#		responsible for starting and stopping the STREAMS error \
#		logger.  The STREAMS error logger should only be run under \
#		exceptional circumstances and this init script not activated \
#		automatically.
#
# LSB init script conventions
#
### BEGIN INIT INFO
# Provides: strerr
# Required-Start: streams
# Required-Stop: streams
# Default-Start: 
# Default-Stop: 0 1 2 3 4 5 6
# Short-Description: start and stop strerr
# License: GPL
# Description:	This STREAMS init script is part of Linux Fast-STREAMS.  It is
#	responsible for starting and stopping the STREAMS error logger.  The
#	STREAMS error logger should only be run under exceptional circumstances
#	and this init script is not activated in any run level by default.
### END INIT INFO

# Source init script functions library.
. /etc/init.d/functions

[ -f /sbin/strerr ] || [ -f /usr/sbin/strerr ] || exit 0

# Specify defaults

STRERROPTIONS=""
MAILUID=""
DIRECTORY="/var/log/streams"
BASENAME="error"
OUTFILE=""
ERRFILE=""
LOGDEVICE="/dev/streams/log"

# Source redhat and/or debian config file
[ -f /etc/strerr.conf ] && . /etc/strerr.conf
[ -f /etc/default/strerr ] && . /etc/default/strerr
[ -f /etc/sysconfig/strerr.conf ] && . /etc/sysconfig/strerr

STRERR_OPTIONS="-n\
${STRERROPTIONS:+ $STRERROPTIONS}\
${MAILUID:+ -a $MAILID}\
${DIRECTORY:+ -d $DIRECTORY}\
${BASENAME:+ -b $BASENAME}\
${OUTFILE:+ -o $OUTFILE}\
${ERRFILE:+ -e $ERRFILE}\
${LOGDEVICE:+ -l $LOGDEVICE}"

RETVAL=0

umask 077

start() {
    echo "Starting STREAMS error logger: "
    daemon strerr $STRERR_OPTIONS
    RETVAL=$?
    echo ""
    [ $RETVAL -eq 0 ] && touch /var/lock/subsys/strerr
    return $RETVAL
}

stop() {
    echo "Shutting down STREAMS error logger: "
    killproc strerr
    RETVAL=$?
    echo ""
    [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/strerr
    return $RETVAL
}

rhstatus() {
    status strerr
}

reload() {
    echo "Reloading the STREAMS error logger: "
    killproc strerr -HUP
}

restart() {
    stop
    start
}

probe() {
#
#   subsystem unlocked, need to start
#
    [ ! -f /var/log/subsys/strerr ] && { echo 'start' ; return 0 }
#
#   strerr dead but subsystem locked, need to restart
#
    /sbin/pidof strerr >/dev/null 2>&1 || { echo 'restart' ; return 0 }
#
#   configuration files updated, need to reload
#
    [ -f /etc/sysconfig/strerr -a /etc/sysconfig/strerr -nt /var/lock/subsys/strerr ] \
    && { echo 'reload' ; return 0 }
    [ -f /etc/default/strerr   -a /etc/default/strerr   -nt /var/lock/subsys/strerr ] \
    && { echo 'reload' ; return 0 }
    [ -f /etc/strerr.conf      -a /etc/strerr.conf      -nt /var/lock/subsys/strerr ] \
    && { echo 'reload' ; return 0 }
#
#   do not need to do anything
#
    return $?
}

case "$1" in
    (start)
	start
	;;
    (stop)
	stop
	;;
    (status)
	rhstatus
	;;
    (restart)
	restart
	;;
    (reload)
	reload
	;;
    (condrestart)
	[ -f /var/lock/subsys/strerr ] && restart || :
	;;
    (probe)
	probe
	;;
    (*)
	echo "Usage: $0 (start|stop|status|restart|condrestart|probe)\n"
	;;
esac

exit $?


# =============================================================================
# 
# @(#) $RCSfile: strerr,v $ $Name:  $($Revision: 0.9.2.4 $) $Date: 2005/02/14 06:47:18 $
#
# -----------------------------------------------------------------------------
#
# Copyright (c) 2001-2005  OpenSS7 Corporation <http://www.openss7.com>
# Copyright (c) 1997-2000  Brian F. G. Bidulock <bidulock@openss7.org>
#
# All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 675 Mass
# Ave, Cambridge, MA 02139, USA.
#
# -----------------------------------------------------------------------------
#
# U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software on
# behalf of the U.S. Government ("Government"), the following provisions apply
# to you.  If the Software is supplied by the Department of Defense ("DoD"), it
# is classified as "Commercial Computer Software" under paragraph 252.227-7014
# of the DoD Supplement to the Federal Acquisition Regulations ("DFARS") (or any
# successor regulations) and the Government is acquiring only the license rights
# granted herein (the license rights customarily provided to non-Government
# users).  If the Software is supplied to any unit or agency of the Government
# other than DoD, it is classified as "Restricted Computer Software" and the
# Government's rights in the Software are defined in paragraph 52.227-19 of the
# Federal Acquisition Regulations ("FAR") (or any successor regulations) or, in
# the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to the FAR
# (or any successor regulations).
#
# -----------------------------------------------------------------------------
#
# Commercial licensing and support of this software is available from OpenSS7
# Corporation at a fee.  See http://www.openss7.com/
#
# -----------------------------------------------------------------------------
#
# Last Modified $Date: 2005/02/14 06:47:18 $ by $Author: brian $
#
# =============================================================================
# vim: sw=4 tw=80
