#!/bin/sh
#
# Install man pages
#
MANDIR=${1:-/usr/man}

if [ ! -d $MANDIR/man3 ]; then
    mkdir -p $MANDIR/man3
fi
if [ ! -d $MANDIR/man8 ]; then
    mkdir -p $MANDIR/man8
fi
if [ ! -d $MANDIR/man9 ]; then
    mkdir -p $MANDIR/man9
fi

cp -f man3/* $MANDIR/man3
cp -f man8/* $MANDIR/man8
cp -f man9/* $MANDIR/man9

echo "LiS man pages installed"
