/* This file was generated by mib2c and is intended for use as a mib module
  for the ucd-snmp snmpd agent. */

#ifndef _MIBGROUP_LAPBMIB_SIMPLE_H
#define _MIBGROUP_LAPBMIB_SIMPLE_H

/* we may use header_generic and header_simple_table from the util_funcs module */

config_require(util_funcs)

/* function prototypes */
	void init_lapbMIB_simple(void);
	FindVarMethod var_lapbMIB_simple;
	FindVarMethod var_lAPBDLETable;
	FindVarMethod var_dLSAPTable;
	FindVarMethod var_sLPPMTable;
	FindVarMethod var_sLPConnectionTable;
	FindVarMethod var_sLPConnectionIVMOTable;

	WriteMethod write_lAPBDLElocalSapNames;
	WriteMethod write_lAPBDLEoperationalState;
	WriteMethod write_lAPBDLEproviderEntityNames;
	WriteMethod write_lAPBDLEmT1Timer;
	WriteMethod write_lAPBDLEmT3Timer;
	WriteMethod write_lAPBDLEmW;
	WriteMethod write_lAPBDLEmXSend;
	WriteMethod write_lAPBDLEmXReceive;
	WriteMethod write_lAPBDLEmT2Timer;
	WriteMethod write_lAPBDLERowStatus;
	WriteMethod write_dLSAPRowStatus;
	WriteMethod write_sLPPMadministrativeState;
	WriteMethod write_sLPPMRowStatus;
	WriteMethod write_sLPConnectionUnderlyingConnectionNames;
	WriteMethod write_sLPConnectionSupportedConnectionNames;
	WriteMethod write_sLPConnectionInterfaceType;
	WriteMethod write_sLPConnectionK;
	WriteMethod write_sLPConnectionN1;
	WriteMethod write_sLPConnectionN2;
	WriteMethod write_sLPConnectionSequenceModulus;
	WriteMethod write_sLPConnectionT1Timer;
	WriteMethod write_sLPConnectionT2Timer;
	WriteMethod write_sLPConnectionT3Timer;
	WriteMethod write_sLPConnectionT4Timer;
	WriteMethod write_sLPConnectionAdministrativeState;
	WriteMethod write_sLPConnectionRowStatus;
	WriteMethod write_sLPConnectionIVMOinterfaceType;
	WriteMethod write_sLPConnectionIVMOk;
	WriteMethod write_sLPConnectionIVMOn1;
	WriteMethod write_sLPConnectionIVMOn2;
	WriteMethod write_sLPConnectionIVMOsequenceModulus;
	WriteMethod write_sLPConnectionIVMOt1Timer;
	WriteMethod write_sLPConnectionIVMOt2Timer;
	WriteMethod write_sLPConnectionIVMOt3Timer;
	WriteMethod write_sLPConnectionIVMOt4Timer;
	WriteMethod write_sLPConnectionIVMORowStatus;
	WriteMethod write_sLPConnectionDefaultInterfaceType;
	WriteMethod write_sLPConnectionDefaultK;
	WriteMethod write_sLPConnectionDefaultN1;
	WriteMethod write_sLPConnectionDefaultN2;
	WriteMethod write_sLPConnectionDefaultSequenceModulus;
	WriteMethod write_sLPConnectionDefaultT1Timer;
	WriteMethod write_sLPConnectionDefaultT2Timer;
	WriteMethod write_sLPConnectionDefaultT3Timer;
	WriteMethod write_sLPConnectionDefaultT4Timer;

#endif				/* _MIBGROUP_LAPBMIB_SIMPLE_H */
