% -*- texinfo -*- vim: ft=texinfo
% vim: ft=texinfo nosmartindent nocindent noautoindent tw=100
% =========================================================================
%
% @(#) $Id: libsocket.texi,v 0.9.2.11 2009-05-01 04:50:47 brian Exp $
%
% =========================================================================
%
% Copyright (c) 2008-2009  Monavacon Limited <http://www.monavacon.com/>
% Copyright (c) 2001-2008  OpenSS7 Corporation <http://www.openss7.com/>
% Copyright (c) 1997-2001  Brian F. G. Bidulock <bidulock@openss7.org>
%
% All Rights Reserved.
%
% Permission is granted to copy, distribute and/or modify this document
% under the terms of the GNU Free Documentation License, Version 1.3 or
% any later version published by the Free Software Foundation; with no
% Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A
% copy of the license is included in the section entitled "GNU Free
% Documentation License".
% 
% Permission to use, copy and distribute this documentation without
% modification, for any purpose and without fee or royalty is hereby
% granted, provided that both the above copyright notice and this
% permission notice appears in all copies and that the name of OpenSS7
% Corporation not be used in advertising or publicity pertaining to
% distribution of this documentation or its contents without specific,
% written prior permission.  OpenSS7 Corporation makes no representation
% about the suitability of this documentation for any purpose.  It is
% provided "as is" without express or implied warranty.
% 
% Permission is granted to process this file through Tex and print the
% results, provided the printed document carries copying permission
% notice identical to this one except for the removal of this paragraph
% (this paragraph not being relevant to the printed manual).
% 
% OPENSS7 CORPORATION DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS
% DOCUMENTATION INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY,
% FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR TITLE; THAT THE
% CONTENTS OF THE DOCUMENT ARE SUITABLE FOR ANY PURPOSE, OR THAT THE
% IMPLEMENTATION OF SUCH CONTENTS WILL NOT INFRINGE ON ANY THIRD PARTY
% PATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.  IN NO EVENT SHALL
% OPENSS7 CORPORATION BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR
% CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF
% USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
% OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH ANY USE OF
% THIS DOCUMENT OR THE PERFORMANCE OR IMPLEMENTATION OF THE CONTENTS
% THEREOF.
% 
% Since the Linux kernel and libraries are constantly changing, this
% manual page may be incorrect or out-of-date.  The author(s) assume no
% responsibility for errors or omissions, or for damages resulting from
% the use of the information contained herein.  The author(s) may not
% have taken the same level of care in the production of this manual,
% which is licensed free of charge, as they might when working
% professionally.
% 
% Formatted or processed versions of this manual, if unaccompanied by
% the source, must acknowledge the copyright and authors of this work.
%
% -------------------------------------------------------------------------
%
% U.S. GOVERNMENT RESTRICTED RIGHTS.  If you are licensing this Software
% on behalf of the U.S. Government ("Government"), the following
% provisions apply to you.  If the Software is supplied by the Department
% of Defense ("DoD"), it is classified as "Commercial Computer Software"
% under paragraph 252.227-7014 of the DoD Supplement to the Federal
% Acquisition Regulations ("DFARS") (or any successor regulations) and the
% Government is acquiring only the license rights granted herein (the
% license rights customarily provided to non-Government users).  If the
% Software is supplied to any unit or agency of the Government other than
% DoD, it is classified as "Restricted Computer Software" and the
% Government's rights in the Software are defined in paragraph 52.227-19
% of the Federal Acquisition Regulations ("FAR") (or any successor
% regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the
% NASA Supplement to the FAR (or any successor regulations).
%
% =========================================================================
% 
% Commercial licensing and support of this software is available from
% OpenSS7 Corporation at a fee.  See http://www.openss7.com/
% 
% =========================================================================
%
% Last Modified $Date: 2009-05-01 04:50:47 $ by $Author: brian $
%
% =========================================================================

\input texinfo
@setfilename libsocket.info
@include @texi/args.texi
@set MANUAL_TITLE OpenSS7 Sockets Library
@set MANUAL_TYPE Reference Manual
@settitle @value{MANUAL_TITLE}

@dircategory GNU libraries
@direntry
* Libsocket: (libsocket).	    An Open Sockets library for STREAMS.
@end direntry

@defindex op

@include texi/args.texi
@set MANUAL_TITLE OpenSS7 Sockets Library
@set MANUAL_TYPE Reference Manual

@comment The following copyright information goes at the head of each .info file.
@ifinfo
This file provides the @value{MANUAL_TYPE} for @value{MANUAL_TITLE}.

This is Edition @value{PACKAGE_RELEASE}@value{PACKAGE_PATCHLEVEL}, last updated @value{PACKAGE_DATE}, of the
@cite{@value{MANUAL_TITLE} @value{MANUAL_TYPE}}, for Version @value{PACKAGE_VERSION}
Release @value{PACKAGE_RELEASE}@value{PACKAGE_PATCHLEVEL}.

Copyright @copyright{} 2008-2009  @uref{http://www.monavacon.com/, Monavacon Limited} @*
Copyright @copyright{} 2001-2008  @uref{http://www.openss7.com/, OpenSS7 Corporation} @*
Copyright @copyright{} 1997-2001  @email{bidulock@@openss7.org, Brian F. G. Bidulock} @*

All Rights Reserved.

Permission is granted to copy, distribute and/or modify this document under the terms of the GNU
Free Documentation License, Version 1.3 or any later version published by the Free Software
Foundation; with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A copy of
the license is included in the section entitled @ref{GNU Free Documentation License}.

Permission to use, copy and distribute this documentation without modification, for any purpose and
without fee or royalty is hereby granted, provided that both the above copyright notice and this
permission notice appears in all copies and that the name of @cite{OpenSS7 Corporation} not be used in
advertising or publicity pertaining to distribution of this documentation or its contents without
specific, written prior permission.  @cite{OpenSS7 Corporation} makes no representation about the
suitability of this documentation for any purpose.  It is provided ``as is'' without express or
implied warranty.

@ignore
Permission is granted to process this file through Tex and print the results, provided the printed
document carries copying permission notice identical to this one except for the removal of this
paragraph (this paragraph not being relevant to the printed manual).

@end ignore
OPENSS7 CORPORATION DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS DOCUMENTATION INCLUDING ALL IMPLIED
WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR TITLE; THAT
THE CONTENTS OF THE DOCUMENT ARE SUITABLE FOR ANY PURPOSE, OR THAT THE IMPLEMENTATION OF SUCH
CONTENTS WILL NOT INFRINGE ON ANY THIRD PARTY PATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.  IN
NO EVENT SHALL OPENSS7 CORPORATION BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR CONSEQUENTIAL
DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH ANY USE OF
THIS DOCUMENT OR THE PERFORMANCE OR IMPLEMENTATION OF THE CONTENTS THEREOF.
@end ifinfo

@include texi/args.texi
@set MANUAL_TITLE OpenSS7 Sockets Library
@set MANUAL_TYPE Reference Manual

@shorttitlepage @value{MANUAL_TITLE} @value{MANUAL_TYPE}
@titlepage
@titlefont{@value{MANUAL_TITLE}}
@sp 0.5
@title @value{MANUAL_TYPE}
@subtitle Version @value{PACKAGE_VERSION} Edition @value{PACKAGE_RELEASE}@value{PACKAGE_PATCHLEVEL}
@subtitle Updated @value{PACKAGE_DATE}
@sp 0.2
@subtitle Distributed with Package @value{PACKAGE}-@value{VERSION}
@sp 2
@subtitle Copyright @copyright{} 2008-2009  Monavacon Limited
@subtitle All Rights Reserved.
@sp 4
@quotation
@subheading Abstract
This document is a @value{MANUAL_TYPE} containing technical details concerning the implementation of
the @value{MANUAL_TITLE} for OpenSS7.  It contains recommendations on software architecture as well
as platform and system applicability of the @value{MANUAL_TITLE}.
@end quotation
@author Brian Bidulock <@email{bidulock@@openss7.org}> for
@sp 0.2
@author The OpenSS7 Project <@uref{http://www.openss7.org/}>

@page
@vskip 0pt plus 1filll

@subsubheading Published by:

@sp 1

@noindent
@uref{http://www.openss7.com/,OpenSS7 Corporation} @*
1469 Jefferys Crescent @*
Edmonton, Alberta  T6L 6T1 @*
Canada @*

@noindent
Copyright @copyright{} 2008-2009  @uref{http://www.monavacon.com/, Monavacon Limited} @*
Copyright @copyright{} 2001-2008  @uref{http://www.openss7.com/, OpenSS7 Corporation} @*
Copyright @copyright{} 1997-2000  @email{bidulock@@openss7.org, Brian F. G. Bidulock} @*

@noindent
All Rights Reserved.

@sp 1

@noindent
Unauthorized distribution or duplication is prohibited.

@sp 1

@noindent
Permission is granted to copy, distribute and/or modify this document under the terms of the GNU
Free Documentation License, Version 1.3 or any later version published by the Free Software
Foundation; with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.  A copy of
the license is included in the section entitled @ref{GNU Free Documentation License}.

@noindent
Permission to use, copy and distribute this documentation without modification, for any purpose and
without fee or royalty is hereby granted, provided that both the above copyright notice and this
permission notice appears in all copies and that the name of @cite{OpenSS7 Corporation} not be used in
advertising or publicity pertaining to distribution of this documentation or its contents without
specific, written prior permission.  @cite{OpenSS7 Corporation} makes no representation about the
suitability of this documentation for any purpose.  It is provided ``as is'' without express or
implied warranty.

@subsubheading Notice:

@noindent
@strong{OPENSS7 CORPORATION DISCLAIMS ALL WARRANTIES WITH REGARD TO THIS DOCUMENTATION INCLUDING ALL
IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, OR TITLE;
THAT THE CONTENTS OF THE DOCUMENT ARE SUITABLE FOR ANY PURPOSE, OR THAT THE IMPLEMENTATION OF SUCH
CONTENTS WILL NOT INFRINGE ON ANY THIRD PARTY PATENTS, COPYRIGHTS, TRADEMARKS OR OTHER RIGHTS.  IN
NO EVENT SHALL OPENSS7 CORPORATION BE LIABLE FOR ANY DIRECT, INDIRECT, SPECIAL OR CONSEQUENTIAL
DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION
OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH ANY USE OF
THIS DOCUMENT OR THE PERFORMANCE OR IMPLEMENTATION OF THE CONTENTS THEREOF.}

@vskip 0pt
@end titlepage
@iftex
@headings off
@everyheading @thistitle @| @thisfile @| @thischaptername
@evenheading @thischapter @| @| @thisfile
@oddheading @thistitle @| @| @thischaptername
@everyfooting Version @value{PACKAGE_VERSION} Rel. @value{PACKAGE_RELEASE}@value{PACKAGE_PATCHLEVEL} @| @value{PACKAGE_DATE} @| @thispage
@evenfooting @thispage @| @| Version @value{PACKAGE_VERSION} Rel. @value{PACKAGE_RELEASE}@value{PACKAGE_PATCHLEVEL}
@oddfooting @value{PACKAGE_DATE} @| @| @thispage
@end iftex
@page

@c Define an index of authors.
@defindex au

@c Define an index of makefile targets
@defcodeindex mk

@c Define an index of configure output variables.
@c @defcodeindex ov

@c Define an index of configure variables.
@c @defcodeindex cv

@c Define an index of options.
@defcodeindex op

@c Define an index of targets.
@c @defcodeindex tr

@c Define an index of commands.
@c @defcodeindex cm

@c Put the macros and variables into their own index.
@c @syncodeindex fn cp
@c @syncodeindex ov vr
@c @syncodeindex cv vr
@c @syncodeindex fn vr

@c Put everything else into one index (arbitrarily chosen to be the concept index).
@c @syncodeindex op cp
@c @syncodeindex tr cp
@c @syncodeindex cm cp

@c An index of manual pages
@defcodeindex mp

@include texi/macros.texi
@include texi/versions.texi

@ifnottex
@node Top
@top @value{MANUAL_TITLE} @value{MANUAL_TYPE}
@unnumbered About This Manual
This is Edition @value{PACKAGE_RELEASE}@value{PACKAGE_PATCHLEVEL}, last updated @value{PACKAGE_DATE}, of
@cite{The @value{MANUAL_TITLE} @value{MANUAL_TYPE}}, for Version
@value{PACKAGE_VERSION} release @value{PACKAGE_RELEASE}@value{PACKAGE_PATCHLEVEL} of the
@value{PACKAGE_TITLE} package.
@end ifnottex

@menu
* Preface::			Preface to this manual
* Introduction::		Introduction to the package
* Reference::			Contents of the package
* Conformance::			Conformance of the package
* Multi-Threading::		Threading issues in the package
* Error Handling::		Error handling for the pakcage
* Licenses::			Copies of OpenSource Licenses
* Indices::			Index of Indices
@end menu

@c --------------------------------------------------------------------------

@node Preface
@unnumbered Preface

@menu
* Notice::			Notices for this package
* Abstract::			Abstract for this manual
* Revisions::			Revisions of this manual
* Disclaimer::			IPR Disclaimers for this package
* Acknowledgements::		Sponsors of and Contributors to the package
* Authors::			Authors of the package
* Maintainer::			Maintainers of the package
* Web Resources::		Web Resources for the package
@end menu

@node Notice
@section Notice
@cindex manual notice
@cindex licensing

This package is released and distributed under the @cite{AGPL} (@pxrefman{GNU Affero General Public
License}).  Please note, however, that there are different licensing terms for the manual pages and
some of the documentation (derived from OpenGroup@footnote{Formerly X/Open and UNIX International.}
publications and other sources).  Consult the permission notices contained in the documentation for
more information.

Also note that parts of this software, as identified in @refman{Possible BSD Sources}, may be
derived from software developed by the @cite{University of California, Berkeley} covered under the
@cite{Combined USL BSD License} (@pxrefman{BSD/USL Combined License}).

This manual is released under the @cite{FDL} (@pxrefman{GNU Free Documentation License}) with no
invariant sections, no front-cover texts and no back-cover texts.

@node Abstract
@section Abstract
@cindex manual abstract

This manual provides a @cite{@value{MANUAL_TYPE}} for @cite{@value{PACKAGE_TITLE}}.

@subsection Objective
@cindex manual objective

The objective of this manual is to provide a guide for the @cite{@value{PACKAGE_TITLE}} developer
when downloading, building, installing and using the @cite{@value{PACKAGE_TITLE}} package.

This guide provides information to developers on the downloading, building, installation and use of
the @cite{@value{PACKAGE_TITLE}} package.

@subsection Intent
@cindex manual intent

The intent of this manual is to act as an installation guide and reference manual to the
@cite{@value{PACKAGE_TITLE}} developer.  It is intended to be read alone and is not intended to
replace or supplement the @cite{@value{PACKAGE_TITLE}} manual pages.  For a reference for writing
code, the manual pages (see @manref{STREAMS(9)}) provide a better reference to the programmer.

Although this describes the features of the @cite{@value{PACKAGE_TITLE}} package,
@uref{http://www.openss7.com/,OpenSS7 Corporation} is under no obligation to provide any software,
system or feature listed herein.

@subsection Audience
@cindex manual audience

This manual is intended for a highly technical audience.  The reader should already be familiar
with @cite{Linux} kernel programming, the @cite{Linux} file system, character devices, driver input
and output, interrupts, software interrupt handling, scheduling, process contexts, multiprocessor
locks, administration, kernel dumps, crashes, oops logs, package managers, the autoconf packaging
system, etc.

The guide is intended for installers and maintainers of @cite{@value{PACKAGE_TITLE}} software.

Readers of the guide are expected to possess prior knowledge of the @cite{Linux} and @cite{UNIX}
system, programming, networking, and data communication.

@node Revision History
@section Revision History
@cindex manual revisions

Take care that you are working with a current version of this manual: you will not be notified of
updates.  To ensure that you are working with a current version, contact the
@uref{mailto:bidulock@@openss7.org,Author}, or check @uref{http://www.openss7.org/,The OpenSS7
Project} website for a current version.

A current version of this manual is normally distributed with the @cite{@value{PACKAGE_TITLE}}
package, @file{@value{PACKAGE}-@value{VERSION}}.@footnote{@url{http://www.openss7.org/repos/tarballs/@value{PACKAGE}-@value{VERSION}.tar.bz2}}


@subsection Version Control

@noindent
Although the author has attempted to ensure that the information in this document is complete and
correct, neither the Author nor OpenSS7 Corporation will take any responsibility in it.
@cite{OpenSS7 Corporation} is making this documentation available as a reference point for the
industry.  While @cite{OpenSS7 Corporation} believes that these interfaces are well defined in this
release of the document, minor changes may be made prior to products conforming to the interfaces
being made available.  @cite{OpenSS7 Corporation} reserves the right to revise this software and
documentation for any reason, including but not limited to, conformity with standards promulgated by
various agencies, utilization of advances in the state of the technical arts, or the reflection of
changes in the design of any techniques, or procedures embodied, described, or referred to herein.
@cite{OpenSS7 Corporation} is under no obligation to provide any feature listed herein.

@smallexample
@verbatim
$Log: libsocket.texi,v $
Revision 0.9.2.11  2009-05-01 04:50:47  brian
- update documentation for release

Revision 0.9.2.10  2008-11-26 12:01:46  brian
- updated to FDL 1.3

Revision 0.9.2.9  2008-09-20 11:04:39  brian
- added package patchlevel

Revision 0.9.2.8  2008-08-03 06:03:38  brian
- protected agains texinfo commands in log entries

Revision 0.9.2.7  2008/07/27 08:49:41  brian
- no invariant sections, more libtool ignores

Revision 0.9.2.6  2008-04-28 22:33:30  brian
- updated headers for release

Revision 0.9.2.5  2008-04-25 11:50:54  brian
- updates to AGPLv3

Revision 0.9.2.4  2007/08/12 06:45:02  brian
- updated licenses in manuals

Revision 0.9.2.3  2007/06/23 01:38:27  brian
- updates for release

Revision 0.9.2.2  2007/02/28 06:31:28  brian
- updates and corrections, #ifdef instead of #if

Revision 0.9.2.1  2006/09/18 00:10:34  brian
- added libsocket source files and manuals
@end verbatim
@end smallexample

@subsection ISO 9000 Compliance

Only the @TeX{}, texinfo, or roff source for this manual is controlled.  An opaque (printed,
postscript or portable document format) version of this manual is an @strong{UNCONTROLLED VERSION}.

@node Disclaimer
@section Disclaimer
@cindex manual disclaimer

@noindent
@strong{@cite{OpenSS7 Corporation} disclaims all warranties with regard to this documentation
including all implied warranties of merchantability, fitness for a particular purpose,
non-infringement, or title; that the contents of the manual are suitable for any purpose, or that
the implementation of such contents will not infringe on any third party patents, copyrights,
trademarks or other rights.  In no event shall @cite{OpenSS7 Corporation} be liable for any direct,
indirect, special or consequential damages or any damages whatsoever resulting from loss of use,
data or profits, whether in an action or contract, negligence or other tortious action, arising out
of or in connection with any use of this documentation or the performance or implementation of the
contents thereof.}

@subsection U.S. Government Restricted Rights

If you are licensing this Software on behalf of the U.S. Government ("Government"), the following
provisions apply to you.  If the Software is supplied by the Department of Defense ("DoD"), it is
classified as "Commercial Computer Software" under paragraph 252.227-7014 of the DoD Supplement to
the Federal Acquisition Regulations ("DFARS") (or any successor regulations) and the Government is
acquiring only the license rights granted herein (the license rights customarily provided to
non-Government users).  If the Software is supplied to any unit or agency of the Government other
than DoD, it is classified as "Restricted Computer Software" and the Government's rights in the
Software are defined in paragraph 52.227-19 of the Federal Acquisition Regulations ("FAR") (or any
successor regulations) or, in the cases of NASA, in paragraph 18.52.227-86 of the NASA Supplement to
the FAR (or any successor regulations).

@c ----------------------------------------------------------------------------

@node Acknowledgements
@section Acknowledgements
@cindex credits

@include texi/funding.texi

@node Authors
@section Authors
@cindex authors

The authors of the @cite{OpenSS7 @value{PACKAGE_TITLE}} package include:

@multitable @columnfractions .05 .95
@item @tab @minus{} @email{bidulock@@openss7.org, Brian Bidulock}
@auindex Bidulock, Brian
@end multitable

See @refman{Author Index}, for a complete listing and cross-index of authors to
sections of this manual.

@node Maintainer
@section Maintainer
@cindex maintainer

The maintainer of the @cite{OpenSS7 @value{PACKAGE_TITLE}} package is:

@multitable @columnfractions .05 .95
@item @tab @minus{} @email{bidulock@@openss7.org, Brian Bidulock}
@end multitable

Please send bug reports to @email{@value{PACKAGE_BUGREPORT}} using the @file{send-pr} script
included in the package, only after reading the @file{BUGS} file in the release, or @xrefman{Problem
Reports}.

@node Web Resources
@section Web Resources
@cindex web resources

@include texi/mail.texi

@c ----------------------------------------------------------------------------

@node Introduction
@chapter Introduction
@cindex introduction

This manual documents the design, implementation, installation, operation and future development
schedule of the @cite{@value{PACKAGE_TITLE}} package.

@c ----------------------------------------------------------------------------

@menu
* Overview::			Overview
* Organization::		Organization
* Conventions::			Conventions
@end menu

@node Overview
@section Overview
@cindex overview

This manual documents the design, implementation, installation, operation and future development of
the @cite{@value{PACKAGE_TITLE}} package.

This manual is organized (loosely) into several sections as follows:

@ifnottex
@menu
  Introduction::		This introduction
* Reference::			Contents of the package
* Conformance::			Conformance of the package
@end menu
@end ifnottex
@ifnotinfo
@multitable @columnfractions .50 .50
@item @ref{Introduction}.
@tab This introduction
@item @ref{Reference}.
@tab Contents of the package
@item @ref{Conformance}.
@tab Conformance of the package
@end multitable
@end ifnotinfo
@ifplaintext
@multitable @columnfractions .50 .50
@item @cite{Introduction}.
@tab This introduction
@item @cite{Reference}.
@tab Contents of the package
@item @cite{Conformance}.
@tab Conformance of the package
@end multitable
@end ifplaintext

@node Conventions
@section Conventions and Definitions
@cindex conventions
@cindex definitions

This manual uses @cite{texinfo} typographic conventions.

@c ----------------------------------------------------------------------------
@c ----------------------------------------------------------------------------

@c ----------------------------------------------------------------------------
@c ----------------------------------------------------------------------------

@node Possible BSD Sources
@appendix Possible BSD Sources
@cindex possible BSD sources
@cindex sources BSD

It is possible that some of the software contained in the following files might be ultimately
derived from the associated @cite{BSD Net2} sources:

@multitable {@file{src/include/sys/socketvar.h}}{@file{usr/src/lib/libsocket/socket/_conn_util.c}}
@item @emph{OpenSS7 File}		@tab @emph{BSD Net2 File}
@item @file{src/drivers/socksys.c}	@tab @file{usr/src/uts/i386/io/osocket.c}
@item @file{src/modules/sockmod.c}	@tab @file{usr/src/uts/i386/io/sockmod.c}
@item @file{src/include/sys/sockmod.h}	@tab @file{usr/src/uts/i386/sys/sockmod.h}
@item @file{src/include/sys/protosw.h}	@tab @file{usr/src/uts/i386/sys/protosw.h}
@item @file{src/include/sys/socksys.h}	@tab @file{usr/src/uts/i386/sys/osocket.h}
@item @file{src/include/sys/socket.h}	@tab @file{usr/src/uts/i386/sys/socket.h}
@item @file{src/include/sys/socketvar.h}@tab @file{usr/src/uts/i386/sys/socketvar.h}
@item @file{src/include/sys/sockio.h}	@tab @file{usr/src/uts/i386/sys/sockio.h}
@item @file{src/lib/sockets.c}		@tab @file{usr/src/lib/libsocket/socket/_conn_util.c}
@item @file{src/lib/sockets.c}		@tab @file{usr/src/lib/libsocket/socket/_utility.c}
@item @file{src/lib/accept.c}		@tab @file{usr/src/lib/libsocket/socket/accept.c}
@item @file{src/lib/bind.c}		@tab @file{usr/src/lib/libsocket/socket/bind.c}
@item @file{src/lib/connect.c}		@tab @file{usr/src/lib/libsocket/socket/connect.c}
@item @file{src/lib/getpeername.c}	@tab @file{usr/src/lib/libsocket/socket/getpeernm.c}
@item @file{src/lib/getsockname.c}	@tab @file{usr/src/lib/libsocket/socket/getsocknm.c}
@item @file{src/lib/getsockopt.c}	@tab @file{usr/src/lib/libsocket/socket/getsockopt.c}
@item @file{src/lib/listen.c}		@tab @file{usr/src/lib/libsocket/socket/listen.c}
@item @file{src/lib/receive.c}		@tab @file{usr/src/lib/libsocket/socket/receive.c}
@item @file{src/lib/ioctl.c}		@tab @file{usr/src/lib/libsocket/socket/s_ioctl.c}
@item @file{src/lib/send.c}		@tab @file{usr/src/lib/libsocket/socket/send.c}
@item @file{src/lib/setpeername.c}	@tab @file{usr/src/lib/libsocket/socket/setpeernm.c}
@item @file{src/lib/setsockname.c}	@tab @file{usr/src/lib/libsocket/socket/setsocknm.c}
@item @file{src/lib/setsockopt.c}	@tab @file{usr/src/lib/libsocket/socket/setsockopt.c}
@item @file{src/lib/shutdown.c}		@tab @file{usr/src/lib/libsocket/socket/shutdown.c}
@item @file{src/lib/socket.c}		@tab @file{usr/src/lib/libsocket/socket/socket.c}
@item @file{src/lib/socketpair.c}	@tab @file{usr/src/lib/libsocket/socket/socketpair.c}
@end multitable

The files on the right were listed in @cite{Exhibit C} of @cite{The 1994 USL-Regents of UCal
Settlement Agreement} and are therefore possibly subject to the @cite{USL/BSD Combined License} of
@cite{Exhibit F} (@pxrefman{BSD/USL Combined License}).

@c ----------------------------------------------------------------------------
@c ----------------------------------------------------------------------------

@node Licenses
@unnumbered Licenses
@cindex licenses

@menu
* BSD/USL Combined License::		The BSD license
* GNU Affero General Public License::	The AGPL license
* GNU General Public License::		The GPL license
* GNU Lesser General Public License::	The LGPL license
* GNU Free Documentation License::	The FDL license
@end menu

@page
@include texi/uslbsd.texi
@page
@include texi/agpl3.texi
@page
@include texi/gpl3.texi
@page
@include texi/lgpl3.texi
@page
@include texi/fdl13.texi

@c ----------------------------------------------------------------------------
@c ----------------------------------------------------------------------------

@node Indices
@unnumbered Indices
@cindex indices

@c ----------------------------------------------------------------------------

@menu
* Concept Index::		Index of Concepts
* Type Index::			Index of Data Types
* Function Index::		Index of Functions and Macros
* Variable Index::		Index of Variables and Constants
* File Index::			Index of Files and Programs
* Option Index::		Index of Configuration Options
* Makefile Target Index::	Index of Makefile Targets
* Author Index::		Index of Authors
* Manual Page Index::		Index of Manual Pages Referenced
@end menu

@c ----------------------------------------------------------------------------

@node Concept Index
@unnumberedsec Index of Concepts
@printindex cp

@page
@node Type Index
@unnumberedsec Index of Data Types
@printindex tp

@page
@node Function Index
@unnumberedsec Index of Functions and Macros
@printindex fn

@page
@node Variable Index
@unnumberedsec Index of Variables and Constants
@printindex vr

@page
@node File Index
@unnumberedsec Index of Files and Programs
@printindex pg

@page
@node Option Index
@unnumberedsec Index of Configuration Options
@printindex op

@page
@node Makefile Target Index
@unnumberedsec Index of Makefile Targets
@printindex mk

@page
@node Author Index
@unnumberedsec Index of Authors
@printindex au

@page
@node Manual Page Index
@unnumberedsec Index of Manual Pages Referenced
@printindex mp

@c ----------------------------------------------------------------------------

@page
@shortcontents
@page
@contents
@bye

@c ============================================================================
